Insert into nxtServiceCategory(CategoryName) values('Automobile')
Insert into nxtServiceCategory(CategoryName) values('Home Appliance')
Insert into nxtServiceCategory(CategoryName) values('Home Maintenance')
Insert into nxtServiceCategory(CategoryName) values('Home Maintenance / Cleaning Service')
Insert into nxtServiceCategory(CategoryName) values('Cleaning Service')
Insert into nxtServiceCategory(CategoryName) values('Photography')
Insert into nxtServiceCategory(CategoryName) values('Health')
Insert into nxtServiceCategory(CategoryName) values('Personal Health')
Insert into nxtServiceCategory(CategoryName) values('Event')
Insert into nxtServiceCategory(CategoryName) values('Electrician')
Insert into nxtServiceCategory(CategoryName) values('Packers and Movers')
Insert into nxtServiceCategory(CategoryName) values('Beauty')