insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Two Wheeler', (select [CategoryId] from nxtServiceCategory where CategoryName = 'Automobile'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Four Wheeler', (select [CategoryId] from nxtServiceCategory where CategoryName = 'Automobile'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Breakdown Assistance',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Automobile'),'', '')

Insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Refrigerator',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Home Appliance'),'', '')
Insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('AC Repair',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Home Appliance'),'', '')
Insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Washing Machine',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Home Appliance'),'', '')
Insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Microwave Oven',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Home Appliance'),'', '')
Insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Electric Geyser',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Home Appliance'),'', '')
Insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Inverter',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Home Appliance'),'', '')
Insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Water Purifier',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Home Appliance'),'', '')
Insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Water Pump',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Home Appliance'),'', '')

insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('House Shifting',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Packers and Movers'),'', '')			

Insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Plumbers',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Home Maintenance'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Sofa Repair & Service',(select [CategoryId] from nxtServiceCategory where CategoryName = 'Home Maintenance'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Pest Control',(select [CategoryId] from nxtServiceCategory where CategoryName ='Home Maintenance'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('House Cleaning',(select [CategoryId] from nxtServiceCategory where CategoryName ='Home Maintenance'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Water Tank Cleaning',(select [CategoryId] from nxtServiceCategory where CategoryName ='Home Maintenance'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Electriction',(select [CategoryId] from nxtServiceCategory where CategoryName ='Home Maintenance'),'', '')

insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Pest Control',(select [CategoryId] from nxtServiceCategory where CategoryName ='Cleaning Service'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('House Cleaning',(select [CategoryId] from nxtServiceCategory where CategoryName ='Cleaning Service'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Water Tank Cleaning',(select [CategoryId] from nxtServiceCategory where CategoryName ='Cleaning Service'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Laundry Services',(select [CategoryId] from nxtServiceCategory where CategoryName ='Cleaning Service'),'', '')

insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Photography',(select [CategoryId] from nxtServiceCategory where CategoryName ='Photography'),'', '')

insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Physiotherapy at Home',(select [CategoryId] from nxtServiceCategory where CategoryName ='Health'),'', '')

insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Beauty Services',(select [CategoryId] from nxtServiceCategory where CategoryName ='Beauty'),'', '')
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Bridal Makeup',(select [CategoryId] from nxtServiceCategory where CategoryName ='Beauty'),'', '')

insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Caterers',(select [CategoryId] from nxtServiceCategory where CategoryName ='Event'),'', '')

insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Home Maintenance',(select [CategoryId] from nxtServiceCategory where CategoryName ='Home Maintenance / Cleaning Service'),'', '')
    
insert into nxtServiceItem ([CategoryItemName],[CategoryId],[Description], [Type]) 
    VALUES('Cleaning Service',(select [CategoryId] from nxtServiceCategory where CategoryName ='Home Maintenance / Cleaning Service'),'', '')




INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Bellow 180 CC',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Two Wheeler'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Above 180 CC',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Two Wheeler'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Bullet',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Two Wheeler'))


INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('General Service',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),400,350)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Body Wash',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),150,100)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Coolant',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),150,100)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Oil Filter Change',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),150,100)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Air Filter',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),200,150)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Battery Service Recharge',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),100,50)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Suspension',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),250,200)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Wheel',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),250,200)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Electrical',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),400,350)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Acessory Fittings',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),400,350)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Engine Cease - Half',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),1100,950)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Engine Cease - Full',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),1100,950)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Oil Change with Oil',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),550,450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Brake Shoe  ( Part + Labor)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),400,350)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Brake Pad ( Part + Labor)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bellow 180 CC'),400,350)


INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('General Service',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),650,500)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Body Wash',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),150,100)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Coolant',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),150,100)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Oil Filter Change',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),150,100)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Air Filter',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),200,150)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Battery Service Recharge',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),100,50)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Suspension',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),450,400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Wheel',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),300,250)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Electrical',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),350,300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Acessory Fittings',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),400,350)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Engine Cease - Half',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),1200,1000)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Engine Cease - Full',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),1200,1000)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Oil Change with Oil',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),900,700)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Brake Shoe  ( Part + Labor)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),300,250)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[Rate],[OfferRate]) VALUES('Brake Pad ( Part + Labor)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Bullet'),450,400)

INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Engine Oil',300,400.00 ,300.00 ,400.00 ,300.00 ,400.00 ,700,900)
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Air Filter  (Normal)',100,250.00 ,100,250.00 ,100,250.00 ,100.00 ,250.00 )
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Oil Filter ',40,100.00 ,40,100.00 ,40,100.00 ,40.00 ,100.00 )
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('RARE Suspension',800,1000.00 ,800,1000.00 ,650.00 ,2000,1500,3000)
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Disc Oil',30,80.00 ,30,80.00 ,30,80.00 ,30.00 ,80.00 )
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Disc Plate',1000,2500.00 ,1000,2500.00 ,1000,2500.00 ,1000.00 ,2500.00 )
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Engine Case (Half)',4500,8000.00 ,4500,8000.00 ,4500.00 ,10000.00 ,0,15000)
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Engine Cease (Full)',10000,12000.00 ,10000,12000.00 ,10000.00 ,14500,0,30000)
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Break Shoe',0,200.00 ,0,200.00 ,0,200.00 ,0,250.00 )
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Break Pad',0,350.00 ,0,350.00 ,0,350.00 ,0,350.00 )
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Clutch Assembly',750,1700.00 ,750,1700.00 ,1000.00 ,20000,2000,5000)
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Carborator',2000,4500.00 ,2000,4500.00 ,2000,4500.00 ,2000.00 ,4500.00 )
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Spark Plug',80,150.00 ,80,150.00 ,80,150.00 ,80.00 ,150.00 )
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Chain Frocket',650,1500.00 ,650,1500.00 ,650,1500.00 ,650.00 ,1500.00 )
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Suspension Fork Overall',0,850.00 ,0,850.00 ,0,1100,1500,1700)
INSERT INTO TwoWheelerSparePartRate ( SparePartName, Moped_Min, Moped_Max, CC_150_180_Min, CC_150_180_Max, CC_Above_180_Min, CC_Above_180_Max, Bullet_Min, Bullet_Max) VALUES('Swing Arm Overall',650,1500,650,1500,650,1500,650,1500)

INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Single Door - Compressor unit',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Single Door - Gas Charge',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Single Door - Power unit',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Single Door - Accessories',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Single Door - Others',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Double door - Accessories',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Double door - Compressor unit',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Double door - Cooling issue',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Double door - Defrost issue',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Double door - Gas charge',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Double door - Others',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Double door - Power unit',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Refrigerator'))

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Capacitor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Compressor unit'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Relay',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Compressor unit'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Compressor (Single Door) including Relay+OLP+capacitor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Compressor unit'),200)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Box Type Relay',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Compressor unit'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Over Load Protector (OLP)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Compressor unit'),300)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Refrigerant Gas Charge (Single Door)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Gas charge'),300)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain tray',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Door Lock',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Freezer door',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power Cord',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power 3 Pin Plug Top',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Freezer door frame',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Gasket',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power Cord',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power Plug',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Insulation',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Accessories'),299)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Door Switch',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Others'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('LED Light',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Others'),100)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Bulb Holder',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Others'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Coil / Def Sensor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Others'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Bulb',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Others'),250)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Thermostat',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Others'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Door Adjust',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Others'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Refrigeration Deodour',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Others'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Cleaning',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Single door - Others'),300)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power 3 Pin Plug Top',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power Cord',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Insulation',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power Cord',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power 3 Pin Plug Top',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain tray',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Gasket',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Door Lock',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Accessories'),400)


INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Relay',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Compressor unit'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Relay /OLP/Cap Combo',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Compressor unit'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Capacitor Start',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Compressor unit'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Over Load Protector (OLP)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Compressor unit'),400)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Dampher',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Cooling issue'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Thermostat',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Cooling issue'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Magnetic Switch',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Cooling issue'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Temperature Knob',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Cooling issue'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Freezer /Con/Ref Fan Motor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Cooling issue'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Assmbly Duct Repair',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Cooling issue'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('DC Fan Motor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Cooling issue'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Rotary Switch',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Cooling issue'),400)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('P Cord heater',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Defrost issue '), 400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Thermal Fuse and Biometal both',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Defrost issue '), 400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Heater Glass',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Defrost issue '), 400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Bio Metal',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Defrost issue '), 400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Defrost Timer',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Defrost issue '), 400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Thermal Fuse',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Defrost issue '), 400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Coil / Def Sensor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Defrost issue '), 400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Defrost Sensor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Defrost issue '), 400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Coil Heater',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Defrost issue '), 400)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Refrigerant Gas Charge (Double Door)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Gas charge'),400)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Door Switch',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Others'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('LED Light',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Others'),100)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Fan blade',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Others'),100)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Bulb',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Others'),250)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Bulb Holder',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Double door - Others'),299)

-------------------------------------------------------------

INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Service & Installation',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'AC Repair'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Electrical parts',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'AC Repair'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Fans and Motors',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'AC Repair'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Gas Charging',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'AC Repair'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Minor repairs',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'AC Repair'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Other parts',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'AC Repair'))

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Capacitor 35-50 mfd',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electrical parts'),349)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Replace sensor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electrical parts'),499)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Capacitor 50-60 mfd',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electrical parts'),349)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Capacitor 10-25 mfd',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electrical parts'),349)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Replace LVT',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electrical parts'),499)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Capacitor 2-5 mfd',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electrical parts'),349)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Contactor replaced',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electrical parts'),499)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Contactor Daikin/ O-General',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electrical parts'),449)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Fan motor outdoor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Fans and Motors'),499)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Blower motor replaced',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Fans and Motors'),499)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Blower replaced',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Fans and Motors'),499)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Replace Flap/Swing Motor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electrical parts'),499)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Tighten/ Replace Thimble',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Minor repairs'),349)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Connector wires replaced (1m)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Minor repairs'),349)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Adjust Grill Locks',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Minor repairs'),349)		
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Adjust pipe and tight compressor screw',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Minor repairs'),349)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('AC fan blade',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Other parts'),499)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Swing blade replaced',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Other parts'),349)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Grill Cover',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Other parts'),349)

----------------------------------
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Installation',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Descaling',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Semi WM - Accessories',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Semi WM - Water leakage',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Semi WM - Wash issue',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Semi WM - Power unit',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Semi WM - Spin issue',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Semi WM - External',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Semi WM - Aesthetics',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Top load WM - Accessories',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Top load WM - Wash issue',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Top load WM - Spin issue',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Top load WM - Power unit',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Top load WM - Water leakage',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Front load WM - Accessories',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Front load WM - Wash issue',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Front load WM - Spin issue',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Front load WM - Power unit',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Front load WM - Water leakage',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Front load WM - Noise issue',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))
INSERT INTO [nxtRepairItems] (RepairItems,CategoryItemId)VALUES('Front load WM - External',(SELECT  CategoryItemId from nxtServiceItem where CategoryItemName = 'Washing Machine'))

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Installation/Un-installation',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Installation'),399)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Descaling',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Descaling'),399)			

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Outer Body',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Spin Cap',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Pulsator',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Snap',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power Cord',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Spin Lid',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Selector',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power 3 Pin Plug Top',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Hose Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inner Body',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Filter',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Knob',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Spin Tub',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Spin Lid Switch',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Spin Tub',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inlet Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Strip drain',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Outer Body',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Spin Cap',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Below OTP/Spin OTP',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('OTP',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Accessories'),350)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId], [OfferRate]) VALUES('DV Bellow',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Water leakage'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId], [OfferRate]) VALUES('DV Assembly',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Water leakage'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId], [OfferRate]) VALUES('Bellow',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Water leakage'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId], [OfferRate]) VALUES('DV Spring',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Water leakage'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId], [OfferRate]) VALUES('Drain Assembly Cleaning (Complete)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Water leakage'),400)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Heater',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Wash issue'),300)		
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Pulley',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Wash issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Capacitor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Wash issue'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Wash Motor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Wash issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Timer Wash',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Wash issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('V Belt',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Wash issue'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Gear Box',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Wash issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Thermostat',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Wash issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Timer Wash (Electro Mechanical)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Wash issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Over Flow Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Wash issue'),299)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Repair PCB semi ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Power unit'),	300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Replace Pcb ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Power unit'),301)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('PCB New ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Power unit'),302)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Wiring Kit ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Power unit'),303)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Re wiring (Heavy damage) ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Power unit'),304)


INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Timer Spin',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Assmby Shocker 3 qty',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Spin Motor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Coupler',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Coupler Bush',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Brake Shoe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Break Plate',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Spring',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Break Wire',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Selector',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Lid Switch',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Strip',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Spin issue'),300)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Wash Lid',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Aesthetics'),350)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Back Cover',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Aesthetics'),350)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Panel Top Cover',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Semi WM - Aesthetics'),350)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power Cord',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inner Body',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Hose Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inlet Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('filter',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Spin lid',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inner SpinTub',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inley Panel',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Sensor Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Lid Switch',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Pulsator',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Snap',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Agitator',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power 3 Pin Plug Top',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Outer tub',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inlet pipe Adaptor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Outer Body',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Pulley',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Knob',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Stand/Trolley',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('DC Inlet valve 3/4 way',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Extension Inlet Pipe 4Mtr',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)		
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('water filter',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Damper rod/Balancing rod',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Accessories'),400)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inlet valve ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Main Motor ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Hall sensor ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Capacitor ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),299) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('V Belt ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),299) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Direct Drive Motor ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Wash timer ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Heater Sensor ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Heater ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Pressure Sensor ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Thermostat ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Chuck Nut ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inlet valve 3/4 way ',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Wash issue'),400)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Clutch assembly',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Spin issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Mechanism(TSP)wirlpool',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Spin issue'),300)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Shocker set',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Spin issue'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Motor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Spin issue'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Spin Timer',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Spin issue'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Lid Switch',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Spin issue'),299)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Replace Sub New PCB',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Power unit'),400) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Replace New PCB',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Power unit'),400) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('LVT',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Power unit'),400) 			
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Wiring Kit',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Power unit'),350) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Re wiring (Heavy damage)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Power unit'),350) 

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain bellow Assembly',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Water leakage'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('DV bellow',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Water leakage'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Dv Spring',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Top load WM - Water leakage'),299)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Rubber Hose',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Hose Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inlet Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Knob',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Noise Filter',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inley Panel / control panel',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Sensor Pipe',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Outer Body',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inlet pipe Adaptor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power 3 Pin Plug Top',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Outer Body',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Back tub',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inlet Rubber Hose',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Power Cord',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Gas kit',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Gas kit Spring',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Extension Inlet Pipe 4Mtr',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Front holder/ Door lever',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),400)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Back holder',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),400)		
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Socher pair',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Pulley drive',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),299)	
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('RF Filter',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Outer Tub',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),350)	
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Dispenser angle',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),400)	
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Door assembly',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Accessories'),400)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Capacitor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),299)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Hall sensor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Thermostat',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Direct Drive Motor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Heater',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Heater Sensor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Pressure Sensor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Pulley',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inlet valve',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Motor Universal',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('V Belt',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Inlet valve 3/4 way',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('DC Inlet valve 3/4 way',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Door Lock',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Wash issue'),450)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('shocker set',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Spin issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Pump Motor',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Spin issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Complete Drum Assembly',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Spin issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Assy Drain Pump',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Spin issue'),450)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drain Pump Motor(Double way)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Spin issue'),450)

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Replace Sub New PCB',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Power unit'),450) 	
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Replace New PCB',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Power unit'),450) 	
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('LVT',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Power unit'),450) 				
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Timer',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Power unit'),450) 	
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Motor Control Unit(MCU)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Power unit'),299) 	
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Re wiring (Heavy damage)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Power unit'),400) 	
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Wiring Kit',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Power unit'),400) 	

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Back and front tub',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Water leakage'),450) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Front tub',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Water leakage'),450) 

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Flange shaft Tri angle',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Noise issue'),450) 
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Drum Bearing/ oil Seal',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - Noise issue'),450) 		

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Stand/Trolley',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Front load WM - External'),450) 
-----------------


