INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Compressor unit'),'Capacitor',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Compressor unit'),'Relay',450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Compressor unit'),'Compressor (Single Door) including Relay+OLP+capacitor',4100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Compressor unit'),'Box Type Relay',450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Compressor unit'),'Over Load Protector (OLP)',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Compressor unit'),'Inverter Compressor',6000)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Gas charge'),'Condensor coil',1100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Gas charge'),'Dryer (Freezer)',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Gas charge'),'Capillary',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Gas charge'),'Cooling Coil (Single Door)',2100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Gas charge'),'Refrigerant Gas Charge (Single Door)',1050)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Gas charge'),'Pin valve',80)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Power unit'),'Repair Pcb',1500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Power unit'),'Repair inverter Pcb',2500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Power unit'),'Replace PCB Inverter',3500)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Drain tray',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Drain Pipe',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Door Lock',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Freezer door',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Power Cord',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Power 3 Pin Plug Top',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Freezer door frame',380)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Gasket',450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Power Cord',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Power Plug',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Accessories'),'Insulation',150)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Others'),'Door Switch',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Others'),'LED Light',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Others'),'Bulb Holder',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Others'),'Coil / Def Sensor',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Others'),'Bulb',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Single door - Others'),'Thermostat',700)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Accessories'),'Power 3 Pin Plug Top',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Accessories'),'Power Cord',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Accessories'),'Insulation',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Accessories'),'Power Cord',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Accessories'),'Power 3 Pin Plug Top',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Accessories'),'Drain tray',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Accessories'),'Drain Pipe',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Accessories'),'Gasket',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Accessories'),'Door Lock',250)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Compressor unit'),'Relay',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Compressor unit'),'Compressor (Double Door) including Relay,OLP and Capacitor',6100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Compressor unit'),'Relay /OLP/Cap Combo',750)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Compressor unit'),'Capacitor Start',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Compressor unit'),'Over Load Protector (OLP)',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Compressor unit'),'Compressor (Double Door) including Relay,OLP and Capacitor >500 liter',6000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Compressor unit'),'Inverter Compressor',7000)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Cooling issue'),'Dampher',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Cooling issue'),'Thermostat',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Cooling issue'),'Magnetic Switch',200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Cooling issue'),'Temperature Knob',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Cooling issue'),'Freezer /Con/Ref Fan Motor',800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Cooling issue'),'Assmbly Duct Repair',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Cooling issue'),'DC Fan Motor',1600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Double door - Cooling issue'),'Rotary Switch',550)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Capacitor 35-50 mfd',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Replace sensor',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Non-Inverter PCB repaired',1500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Capacitor 50-60 mfd',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Capacitor 10-25 mfd',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Inverter PCB repaired',4000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Replace LVT',900)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Capacitor 2-5 mfd',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Contactor replaced',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Contactor Daikin/ O-General',1500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Electrical parts'),'Convert PCB with remote',1500)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Condensor repaired',500)	 
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Copper Coil Condensor 1.5 ton Split',3800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Flair nut replaced',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Copper Coil Condensor 2 ton Split',4200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Copper Coil Condensor 1 ton Split',3200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Copper Cooling Coil',4200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Compressor 0.8-1 ton',6500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Expansion valve replaced',1200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Service valve replaced',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Capillary and filter replaced',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Compressor 1.5 ton',7500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Compressor 2 ton',9200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Gas Charging',2500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Dead nut (1 pc)',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'U Band replaced (1 pc)',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Gas Charging'),'Pin Valve for window AC',50)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Minor repairs'),'Tighten/ Replace Thimble',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Minor repairs'),'Connector wires replaced (1m)',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Minor repairs'),'Adjust Grill Locks',0)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Minor repairs'),'Adjust Grill Locks',0)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Minor repairs'),'Water Leakage Repaired',599)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Minor repairs'),'Adjust pipe and tight compressor screw',0)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Other parts'),'AC fan blade',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Other parts'),'Swing blade replaced',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Other parts'),'Grill Cover',1500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Other parts'),'Universal remote',800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Other parts'),'Compressor grommets set',299)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Other parts'),'Rubber washer (1 pc)',50)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Descaling'),'Descaling',395)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Outer Body',2500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Spin Cap',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Pulsator',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Snap',200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Power Cord',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Spin Lid',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Drain Selector',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Power 3 Pin Plug Top',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Drain Hose Pipe',200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Inner Body',2800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Filter',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Knob',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Spin Tub',1250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Spin Lid Switch',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Spin Tub',900)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Inlet Pipe',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Strip drain',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Outer Body',2000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Cover',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Spin Cap',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'Below OTP/Spin OTP',450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Accessories'),'OTP',350)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Water leakage'),'DV Bellow',200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Water leakage'),'DV Assembly',300)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Water leakage'),'Bellow',300)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Water leakage'),'DV Spring',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Water leakage'),'Drain Assembly Cleaning (Complete)',0)


INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Wash issue'),'Heater',800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Wash issue'),'Pulley',450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Wash issue'),'Capacitor',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Wash issue'),'Wash Motor',1600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Wash issue'),'Timer Wash',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Wash issue'),'V Belt',300)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Wash issue'),'Gear Box',1000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Wash issue'),'Thermostat',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Wash issue'),'Timer Wash (Electro Mechanical)',900)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Wash issue'),'Over Flow Pipe',120)


INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Power unit'),'Repair PCB semi ',1000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Power unit'),'Replace Pcb ',1500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Power unit'),'PCB New ',1500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Power unit'),'Wiring Kit ',0)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Power unit'),'Re wiring (Heavy damage) ',300)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Timer Spin',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Assmby Shocker 3 qty',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Spin Motor',1350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Coupler',550)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Coupler Bush',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Brake Shoe',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Break Plate',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Spring',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Break Wire',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Drain Selector',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Lid Switch',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Spin issue'),'Drain Strip',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - External '),'D scale Powder',100)
							
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Aesthetics '),'Wash Lid',800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Aesthetics '),'Back Cover',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Semi WM - Aesthetics '),'Panel Top Cover',1000)
														
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Power Cord',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Inner Body',2500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Drain Hose Pipe',200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Inlet Pipe',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'filter',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Spin lid',550)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Inner SpinTub',2800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Inley Panel',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Sensor Pipe',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Lid Switch',380)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Pulsator',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Snap',200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Agitator',900)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Power 3 Pin Plug Top',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Outer tub',1500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Inlet pipe Adaptor',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Outer Body',3300)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Pulley',450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Knob',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Stand/Trolley',900)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'DC Inlet valve 3/4 way',1450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Extension Inlet Pipe 4Mtr',800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Cover',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'water filter',1200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Accessories '),'Damper rod/Balancing rod',1200)


INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Inlet valve',850)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Main Motor',1950)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Hall sensor',900)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Capacitor',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'V Belt',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Direct Drive Motor',4000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Wash timer',750)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Heater Sensor',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Heater',750)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Pressure Sensor',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Thermostat',380)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Chuck Nut',200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Wash issue'),'Inlet valve 3/4 way',1150)
									
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Spin issue'),'Clutch assembly',3800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Spin issue'),'Mechanism(TSP)wirlpool',3800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Spin issue'),'Shocker set',1000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Spin issue'),'Drain Motor',1200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Spin issue'),'Spin Timer',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Spin issue'),'Lid Switch',350)
													
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Power unit'),'Replace Sub New PCB',0)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Power unit'),'Replace New PCB',0)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Power unit'),'LVT',650)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Power unit'),'Repair PCB',1500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Power unit'),'Wiring Kit',0)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Power unit'),'Re wiring (Heavy damage)',500)
													
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Water leakage'),'Drain bellow Assembly',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Water leakage'),'DV bellow',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Water leakage'),'Dv Spring',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Water leakage'),'D scale Powder',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Top load WM - Water leakage'),'Drain Cleaining',400)
							
						
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Drain Rubber Hose',550)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Drain Hose Pipe',200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Inlet Pipe',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Knob',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Noise Filter',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Inley Panel / control panel',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Sensor Pipe',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Outer Body',3800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Inlet pipe Adaptor',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Power 3 Pin Plug Top',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Outer Body',3000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Back tub',2200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Inlet Rubber Hose',550)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Power Cord',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Gas kit',1750)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Gas kit Spring',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Extension Inlet Pipe 4Mtr',800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Front holder/ Door lever',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Back holder',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Cover',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Socher pair',1050)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Pulley drive',750)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'RF Filter',450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Outer Tub',2500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Dispenser angle',450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Accessories'),'Door assembly',1500)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Capacitor',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Hall sensor',900)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Thermostat',380)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Direct Drive Motor',4000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Heater',900)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Heater Sensor',350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Pressure Sensor',750)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Pulley',450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Inlet valve',1350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Motor Universal',4000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'V Belt',850)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Inlet valve 3/4 way',1250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'DC Inlet valve 3/4 way',1900)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Wash issue'),'Door Lock',1250)
							
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Spin issue'),'shocker set',1000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Spin issue'),'Drain Pump Motor',1450)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Spin issue'),'Complete Drum Assembly',4000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Spin issue'),'Assy Drain Pump',1750)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Spin issue'),'Drain Pump Motor(Double way)',2200)
																			
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Power unit'),'Replace Sub New PCB',0)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Power unit'),'Replace New PCB',0)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Power unit'),'LVT',650)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Power unit'),'Repair PCB',2200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Power unit'),'Timer',3000)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Power unit'),'Motor Control Unit(MCU)',1350)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Power unit'),'Re wiring (Heavy damage)',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Power unit'),'Wiring Kit',0)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Power unit'),'Inverter PCB Repair',3000)
												
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Water leakage'),'Back and front tub',4800)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Water leakage'),'Front tub',2400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Water leakage'),'Drain Cleaining',450)
												
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Noise issue'),'Flange shaft Tri angle',2500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - Noise issue'),'Drum Bearing/ oil Seal',2200)
												
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - External'),'Stand/Trolley',1250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Front load WM - External'),'D scale Powder',100)

-------
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'No heating'),'Magnetron4fins',1300)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'No heating'),'HVCapacitor',750)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'No heating'),'GrillHeater',700)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'No heating'),'SmartovenGrillHeater',1650)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'No heating'),'HVDiode',500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'No heating'),'Magnetron6Fins',1500)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'No heating'),'ConvHeater',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'No heating'),'HVTransformer',250)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'No heating'),'Megnatron5Fins',1400)

INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'NoiseIssue'),'FanMotor',750)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'NoiseIssue'),'TurnTableMotor',650)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'NoiseIssue'),'Roller',250)
											
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'BulbHolder',80)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'DoorLatch',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'PowerCord',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'MicaSheet',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'Coupler',200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'FanBladeMetal',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'DoorSwitch',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'GlassTurntable',1050)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'Power3PinPlugTop',150)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'TimerKnob',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'DoorHing',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'FanBlade',100)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'SelectorSwitch',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Accessories'),'HVFuse',250)
												
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Powerunit'),'PCBNew',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Powerunit'),'LVT',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Powerunit'),'Fuse5/15Amp',50)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Powerunit'),'SwitchMembrane/InleyPanelRepair',1200)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Powerunit'),'TCO',400)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Powerunit'),'Timer',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Powerunit'),'Cavitysensor',600)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Powerunit'),'PCBRepair',1300)
INSERT INTO [dbo].[RepairPartsRate] (RepairItemID, RepairPartName, Min_Rate) VALUES((select RepairItemID from nxtRepairItems WHERE RepairItems = 'Powerunit'),'Bulb',150)


INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Geyser-Major Parts',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Electric Geyser'))
INSERT INTO [dbo].[nxtRepairItems] ([RepairItems],[CategoryItemId]) VALUES ('Accessories',(SELECT  [CategoryItemId] FROM nxtServiceItem WHERE CategoryItemName ='Electric Geyser'))

INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Geyser Installation',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electric Geyser Service'),499)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Geyser Servicing (Small Geyser <10L)',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electric Geyser Service'),599)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Geyser Un-installation',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electric Geyser Service'),399)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Geyser Servicing (Medium Size Geyser (10-30L))',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electric Geyser Service'),599)
INSERT INTO [dbo].[nxtRepairServiceCharge] ([RepairItemsPart],[RepairItemId],[OfferRate]) VALUES('Geyser Servicing (Commercial Geyser (30L-50L))',(SELECT [RepairItemId] FROM [nxtRepairItems] WHERE [RepairItems] = 'Electric Geyser Service'),599)



