INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'PARLE MANGO BITE 390G', 'productPool/1.jpg', 176 ),
( 'PARLE MELODY 220.5GM', 'productPool/1.jpg', 212 ),
( 'PARLE MELODY CHOCOLATE 319G', 'productPool/1.jpg', 190 ),
( 'PARLE MILANO CHCO& HAZELNUT 60G', 'productPool/1.jpg', 163 ),
( 'PARLE MILANO CHCOLATE CHIP COOKIES 75G', 'productPool/1.jpg', 195 ),
( 'PARLE MILANO MINI CHOCOCHIP COOKIES 100G', 'productPool/1.jpg', 195 ),
( 'PARLE MILANO MINIS 100G', 'productPool/1.jpg', 168 ),
( 'PARLE MILK SHAKTI 300G', 'productPool/1.jpg', 119 ),
( 'PARLE MILK SHAKTI 98.09G', 'productPool/1.jpg', 8 ),
( 'PARLE MILK SHAKTI BISCUITS 200G', 'productPool/1.jpg', 23 ),
( 'PARLE MONACO 200G', 'productPool/1.jpg', 144 ),
( 'PARLE MONACO 92.8G', 'productPool/1.jpg', 268 ),
( 'PARLE MONACO CHEESLINGS 150G', 'productPool/1.jpg', 53 ),
( 'PARLE MONACO CHEESLINGS CLASSIC 150G', 'productPool/1.jpg', 169 ),
( 'PARLE MONACO CHEESLINGS JAR 300G', 'productPool/1.jpg', 193 ),
( 'PARLE MONACO CHEESLINGS PIZZA JAR 150G', 'productPool/1.jpg', 249 ),
( 'PARLE MONACO CLASSIC 400G', 'productPool/1.jpg', 214 ),
( 'PARLE MONACO JEFFS 200G', 'productPool/1.jpg', 226 ),
( 'PARLE MONACO JEFFS JAR', 'productPool/1.jpg', 164 ),
( 'PARLE MONACO PIZZA 120G', 'productPool/1.jpg', 49 ),
( 'PARLE MONACO SALTY SNACK 75G', 'productPool/1.jpg', 147 ),
( 'PARLE MONACO SIXER JAR 200G', 'productPool/1.jpg', 139 ),
( 'PARLE NUTRICRUNCH CRACKER 150G', 'productPool/1.jpg', 139 ),
( 'PARLE NUTRICRUNCH DIGESTIVE 100G', 'productPool/1.jpg', 136 ),
( 'PARLE NUTRICRUNCH DIGESTIVE MARIE 120G', 'productPool/1.jpg', 101 ),
( 'PARLE NUTRICRUNCH DIGESTIVE MARIE 250G', 'productPool/1.jpg', 33 ),
( 'PARLE NUTRICRUNCH HONEY AND OATS 100G', 'productPool/1.jpg', 101 ),
( 'PARLE NUTRICRUNNCH CRACKERS200G', 'productPool/1.jpg', 84 ),
( 'PARLE ORANGE BITE 390G', 'productPool/1.jpg', 244 ),
( 'PARLE ORGINAL GLUCO BISCUIT 140G', 'productPool/1.jpg', 139 ),
( 'PARLE ORGINAL GLUCO BISCUT 300GM', 'productPool/1.jpg', 145 ),
( 'PARLE PARLE - G GOLD 200G', 'productPool/1.jpg', 85 ),
( 'PARLE PARLE G GOLD 500G', 'productPool/1.jpg', 210 ),
( 'PARLE PARLE-G 800G', 'productPool/1.jpg', 268 ),
( 'PARLE PARLE-G GOLD 500G', 'productPool/1.jpg', 121 ),
( 'PARLE PARLE-G GOLD BISCUITS 1KG', 'productPool/1.jpg', 69 ),
( 'PARLE PARLEG 130G', 'productPool/1.jpg', 136 ),
( 'PARLE PARLEG 800G', 'productPool/1.jpg', 58 ),
( 'PARLE POPPINS 16.2G', 'productPool/1.jpg', 229 ),
( 'PARLE PREMIUM RUSK 63G MRP 10', 'productPool/1.jpg', 70 ),
( 'PARLE RUSK 300G', 'productPool/1.jpg', 36 ),
( 'PARLE RUSK 400G', 'productPool/1.jpg', 58 ),
( 'PARLE RUSK ELACHI 200G RS 30', 'productPool/1.jpg', 277 ),
( 'PARLE RUSK ELAICHI 218G', 'productPool/1.jpg', 142 ),
( 'PARLE RUSK MILK 200GM', 'productPool/1.jpg', 196 ),
( 'PARLE RUSK REAL ELAICHI 273G', 'productPool/1.jpg', 15 ),
( 'PARLE SIMPLY CRACKER AJWAIN 250G', 'productPool/1.jpg', 186 ),
( 'PARLE SIMPLY GGOD DIGESTIVES 250G', 'productPool/1.jpg', 34 ),
( 'PARLE TOP BUTER CRAKER 250G', 'productPool/1.jpg', 64 ),
( 'PARLE TOP BUTTER CRACKERS 200G', 'productPool/1.jpg', 129 ),
( 'PARLE TOP CRACKER 100G', 'productPool/1.jpg', 160 ),
( 'PARLE TOP RICH BUTTERY CRACKERS 200G', 'productPool/1.jpg', 111 ),
( 'PARLE TOP SPIN CRACKERS 200G', 'productPool/1.jpg', 22 ),
( 'PARLE-G GOLD 600GM', 'productPool/1.jpg', 84 ),
( 'PARLE-G HIDE & SEEK BOURBON150G', 'productPool/1.jpg', 91 ),
( 'PARLE-G MILKY SANDWICH 120GM', 'productPool/1.jpg', 236 ),
( 'PARLEHIDE &SEEK HEART BEATEZCOOKIES 350G', 'productPool/1.jpg', 177 ),
( 'PARLET BAKESMITH MARIE 250G', 'productPool/1.jpg', 202 ),
( 'Parotta', 'productPool/1.jpg', 29 ),
( 'PARRY WHITE LABEL SUGAR 5KG', 'productPool/1.jpg', 188 ),
( 'PARRYS AMRIT JAGGERY POWDER 500G', 'productPool/1.jpg', 119 ),
( 'PARRYS AMRIT SUGAR 500G PKT', 'productPool/1.jpg', 50 ),
( 'PARRYS AMRIT SUGAR 750G JAR', 'productPool/1.jpg', 261 ),
( 'PARRYS DELITE MILK POWDER 1KG', 'productPool/1.jpg', 242 ),
( 'PARRYS PUR REFINED SUGAR 1KG', 'productPool/1.jpg', 30 ),
( 'PARRYS PURE REFINED SUGAR 1KG JAR', 'productPool/1.jpg', 84 ),
( 'PARRYS SUGAR CUBE 500G', 'productPool/1.jpg', 86 ),
( 'PARRYS VITA SUGAR 1KG', 'productPool/1.jpg', 178 ),
( 'PARRYS WHITE LABEL SUGAR 1KG', 'productPool/1.jpg', 167 ),
( 'PARTY POPPER 100', 'productPool/1.jpg', 69 ),
( 'PARTY POPPER 30 CM', 'productPool/1.jpg', 38 ),
( 'PARTY POPPER 40', 'productPool/1.jpg', 185 ),
( 'PARTY POPPER 40 GOLD', 'productPool/1.jpg', 23 ),
( 'PARTY POPPER 50', 'productPool/1.jpg', 140 ),
( 'PARTY POPPER 50CM', 'productPool/1.jpg', 63 ),
( 'PARTY POPPER 60', 'productPool/1.jpg', 115 ),
( 'PARTY POPPER 60 GOLD', 'productPool/1.jpg', 69 ),
( 'PARTY POPPER HEART', 'productPool/1.jpg', 148 ),
( 'PARTY POPPER ROSE PETALS', 'productPool/1.jpg', 272 ),
( 'PARTY POPPER SNOW WHITE', 'productPool/1.jpg', 135 ),
( 'PARTY POPPER WHITE', 'productPool/1.jpg', 71 ),
( 'PASEO BATHROOM TISSE 2ROLL 2PLY', 'productPool/1.jpg', 99 ),
( 'PASEO ELEGANT FACIAL TISSUE 200S', 'productPool/1.jpg', 271 ),
( 'PASEO HANKY TISSUE 3P', 'productPool/1.jpg', 186 ),
( 'PASEO KITCHEN TOWEL 60SHEET', 'productPool/1.jpg', 56 ),
( 'PASEO LUNCHEON NAPKIN 100SHEET', 'productPool/1.jpg', 253 ),
( 'PASEO PRINTED HOUSEHOLD TOWEL 70SHEET', 'productPool/1.jpg', 177 ),
( 'PASEO SMART FACIAL TISSUES 200SHEET', 'productPool/1.jpg', 182 ),
( 'PASEO ULTRA SOFT ALOE VERA TISSUES 95 SHEETS', 'productPool/1.jpg', 227 ),
( 'PASSIO PASSION FRUIT PULP 6KG', 'productPool/1.jpg', 111 ),
( 'PASSIOM FRUIT SQUASH 6KG JAR', 'productPool/1.jpg', 160 ),
( 'PASTRY', 'productPool/1.jpg', 125 ),
( 'PATANJALI ALOE VERA HAND WASH 250ML', 'productPool/1.jpg', 93 ),
( 'PATANJALI ALOEVERA KANTI 150G', 'productPool/1.jpg', 58 ),
( 'PATANJALI ALOEVERA KANTI 450G', 'productPool/1.jpg', 228 ),
( 'PATANJALI DANT KANTI 100G', 'productPool/1.jpg', 135 ),
( 'PATANJALI DANT KANTI NATURAL 200G', 'productPool/1.jpg', 4 ),
( 'PATANJALI DISHWASH BAR 280G', 'productPool/1.jpg', 216 ),
( 'PATANJALI HALDI CHANDAN KANTI 150G', 'productPool/1.jpg', 57 ),
( 'PATANJALI HALDI CHANDAN KANTI 450G', 'productPool/1.jpg', 240 ),
( 'PATANJALI HERB WASH 250G', 'productPool/1.jpg', 57 ),
( 'PATANJALI HERBAL HAND WASH 250ML', 'productPool/1.jpg', 240 ),
( 'PATANJALI HERBAL KAJAL 3G', 'productPool/1.jpg', 153 ),
( 'PATANJALI NEEM KANTI 150G', 'productPool/1.jpg', 59 ),
( 'PATANJALI PANCHGAVYA KANTI 150G', 'productPool/1.jpg', 171 ),
( 'PATANJALI SAUNDARYA ALOEVERA GEL 150ML', 'productPool/1.jpg', 251 ),
( 'PATANJALI SOMYA LIQUID DETERGENT 500ML', 'productPool/1.jpg', 166 ),
( 'PATANJALI WHOLE WHEAT CHAKKI ATTA 2KG', 'productPool/1.jpg', 34 ),
( 'PATANJALIWHOLE WHEAT CHAKKI ATTA 5KG', 'productPool/1.jpg', 185 ),
( 'PATHANJALI WHOLE WHEAT ATTA 1KG', 'productPool/1.jpg', 134 ),
( 'PATHANJALI WHOLE WHEAT ATTA 2KG', 'productPool/1.jpg', 3 ),
( 'PATTANI FRIED 90G', 'productPool/1.jpg', 14 ),
( 'PAV BHAJI MASALA 100G', 'productPool/1.jpg', 152 ),
( 'PAVAKKA', 'productPool/1.jpg', 3 ),
( 'PAVAKKA WHITE', 'productPool/1.jpg', 25 ),
( 'PAVAN DUSTPAN MEDIUM', 'productPool/1.jpg', 255 ),
( 'PAVAN GINGELLY OIL 500 ML', 'productPool/1.jpg', 37 ),
( 'PAVAN GINGELLYOIL 200ML', 'productPool/1.jpg', 174 ),
( 'PAVAN GINGELY OIL 1LTR', 'productPool/1.jpg', 213 ),
( 'PAVANGINGELLYOIL 100ML', 'productPool/1.jpg', 189 ),
( 'PAVITHRAM GINGELLY OIL 1LTR', 'productPool/1.jpg', 99 ),
( 'PAVITHRAM GINGELY OIL 200ML', 'productPool/1.jpg', 143 ),
( 'PAVITHRAM OIL 100ML', 'productPool/1.jpg', 7 ),
( 'PAVITHRAM SESAME OIL 500ML', 'productPool/1.jpg', 207 ),
( 'PAVIZHAM CHILLI POWDER 100G', 'productPool/1.jpg', 243 ),
( 'PAVIZHAM CHILLI POWDER 250G', 'productPool/1.jpg', 81 ),
( 'PAVIZHAM COCONUT OIL 1LTR POUCH', 'productPool/1.jpg', 119 ),
( 'PAVIZHAM CORIANDER POWDER 100G', 'productPool/1.jpg', 261 ),
( 'PAVIZHAM CORIANDER POWDER 250G', 'productPool/1.jpg', 256 ),
( 'PAVIZHAM JAYA RICE 10KG', 'productPool/1.jpg', 206 ),
( 'PAVIZHAM JAYA RICE 25KG', 'productPool/1.jpg', 87 ),
( 'PAVIZHAM JAYA RICE 50KG', 'productPool/1.jpg', 197 ),
( 'PAVIZHAM JAYA RICE 5KG', 'productPool/1.jpg', 65 ),
( 'PAVIZHAM POOJA AGARBATHIS MRP 10', 'productPool/1.jpg', 115 ),
( 'PAVIZHAM RF RED BRAN RICE 5KG', 'productPool/1.jpg', 137 ),
( 'PAVIZHAM RICE BRAN OIL 1L POUCH', 'productPool/1.jpg', 163 ),
( 'PAVIZHAM RICE BRAN OIL 1LTR BOTTLE', 'productPool/1.jpg', 206 ),
( 'PAVIZHAM SUNFLOWER 1LTR BOTTLE', 'productPool/1.jpg', 25 ),
( 'PAVIZHAM SUNFLOWER OIL 1LTR POUCH', 'productPool/1.jpg', 159 ),
( 'PAVIZHAM SUREKHA 5KG', 'productPool/1.jpg', 26 ),
( 'PAVIZHAM SUREKHA RICE 10KG', 'productPool/1.jpg', 41 ),
( 'PAVIZHAM TURMERIC POWDER 100G', 'productPool/1.jpg', 5 ),
( 'PAVIZHAM TURMERIC POWDER 250G', 'productPool/1.jpg', 50 ),
( 'PAVIZHAM UNDA RICE 10KG', 'productPool/1.jpg', 174 ),
( 'PAVIZHAM UNDA RICE 5KG', 'productPool/1.jpg', 277 ),
( 'PAVIZHAM VADI RICE 10KG', 'productPool/1.jpg', 61 ),
( 'PAVIZHAM VADI RICE 25KG', 'productPool/1.jpg', 178 ),
( 'PAVIZHAM VADI RICE 50KG', 'productPool/1.jpg', 40 ),
( 'PAVIZHAM VADI RICE 5KG', 'productPool/1.jpg', 154 ),
( 'PAYASAM BROKEN RICE 50KG', 'productPool/1.jpg', 245 ),
( 'PC BEETER PE11', 'productPool/1.jpg', 102 ),
( 'PC GRATER PE1', 'productPool/1.jpg', 229 ),
( 'PC GRATER PE13', 'productPool/1.jpg', 249 ),
( 'PC KNIFE PE5', 'productPool/1.jpg', 192 ),
( 'PC PEELER PE6', 'productPool/1.jpg', 178 ),
( 'PC PEELER PE9', 'productPool/1.jpg', 94 ),
( 'PC SCISSORS PE8', 'productPool/1.jpg', 116 ),
( 'PE BIRDS ACQUA WATER BOTTLE 450ML', 'productPool/1.jpg', 77 ),
( 'PE BIRDS FUNTOS WATER BOTTLE 1000ML', 'productPool/1.jpg', 106 ),
( 'PE BIRDS FUNTOS WATER BOTTLE 660ML', 'productPool/1.jpg', 233 ),
( 'PE BIRDS GEO WATER BOTTLE 800ML', 'productPool/1.jpg', 79 ),
( 'PE BIRDS MAXO WATER BOTTLE 750ML', 'productPool/1.jpg', 54 ),
( 'PE BIRDS PINNU WATER BOTTLE 750ML', 'productPool/1.jpg', 177 ),
( 'PE BIRDS PONY WATER BOTTLE 400ML', 'productPool/1.jpg', 254 ),
( 'PE BIRDS PONY WATER BOTTLE 600ML', 'productPool/1.jpg', 73 ),
( 'PE BIRDS SPORTY WATER BOTTLE 1000ML', 'productPool/1.jpg', 259 ),
( 'PE BIRDS TINY WATER BOTTLE 600ML', 'productPool/1.jpg', 217 ),
( 'PE BIRDS TWINKLE WATER BOTTLE 750ML', 'productPool/1.jpg', 195 ),
( 'PE BIRDS WATER BOTTLE SPORTY 1000ML', 'productPool/1.jpg', 233 ),
( 'PE BIRDS WATER BOTTLE SPORTY 750ML', 'productPool/1.jpg', 164 ),
( 'PE BIRDS WATER BOTTLE STRIKER 800ML', 'productPool/1.jpg', 215 ),
( 'PE BIRDS ZIPPER WATER BOTTLE 800ML', 'productPool/1.jpg', 174 ),
( 'PEACCOCK VENICE DESERT KNIFE', 'productPool/1.jpg', 214 ),
( 'PEACH DRIED 100G', 'productPool/1.jpg', 29 ),
( 'PEACOCK ANDHRA PALTA-2', 'productPool/1.jpg', 31 ),
( 'PEACOCK ELITE BABY SPOON 6NOS', 'productPool/1.jpg', 111 ),
( 'PEACOCK ELITE DESEERT SPOON', 'productPool/1.jpg', 168 ),
( 'PEACOCK ELITE DESERT FORK 6NOS', 'productPool/1.jpg', 263 ),
( 'PEACOCK GALAXY DESERT FORK', 'productPool/1.jpg', 212 ),
( 'PEACOCK GALAXY DESERT SPOON', 'productPool/1.jpg', 148 ),
( 'PEACOCK HA TEA SPOON 6NOS', 'productPool/1.jpg', 260 ),
( 'PEACOCK KHUSHI LADDLE', 'productPool/1.jpg', 91 ),
( 'PEACOCK KHUSHI OVAL', 'productPool/1.jpg', 122 ),
( 'PEACOCK KHUSHI PALTA', 'productPool/1.jpg', 69 ),
( 'PEACOCK LADDLE-2', 'productPool/1.jpg', 136 ),
( 'PEACOCK ORBIT DESERT SPOON 6NOS', 'productPool/1.jpg', 130 ),
( 'PEACOCK ORBIT TEA SPOON 6NOS', 'productPool/1.jpg', 233 ),
( 'PEACOCK POWDER HAIR DYE IMP', 'productPool/1.jpg', 94 ),
( 'PEACOCK SAPHIRE TABLE SPOON 2NOS', 'productPool/1.jpg', 144 ),
( 'PEACOCK SAPPHIRE BABY FORK', 'productPool/1.jpg', 97 ),
( 'PEACOCK SAPPHIRE BABY SPOON 6NOS', 'productPool/1.jpg', 112 ),
( 'PEACOCK SAPPHIRE TABLE FORK', 'productPool/1.jpg', 198 ),
( 'PEACOCK SAPPHIRE TEA FORK', 'productPool/1.jpg', 55 ),
( 'PEACOCK SAPPHIRE TEA SPOON', 'productPool/1.jpg', 100 ),
( 'PEACOCK SERVING SPOON', 'productPool/1.jpg', 229 ),
( 'PEACOCK SKIMMER -4', 'productPool/1.jpg', 100 ),
( 'PEACOCK SKIMMER -5', 'productPool/1.jpg', 238 ),
( 'PEACOCK VENICE BABY PORK', 'productPool/1.jpg', 135 ),
( 'PEACOCK VENICE DESERT PORK', 'productPool/1.jpg', 228 ),
( 'PEACOCK VENICE DESERT SPOON', 'productPool/1.jpg', 194 ),
( 'PEACOCK VENICE ICECREAM SPOON', 'productPool/1.jpg', 212 ),
( 'PEACOCK VENICE SODA SPOON', 'productPool/1.jpg', 165 ),
( 'PEACOCK VENICE TEA SPOON', 'productPool/1.jpg', 196 ),
( 'PEACOCK VENICE TURNER PLAIN 11', 'productPool/1.jpg', 90 ),
( 'PEACOCK VENICE TURNER PLAIN 14', 'productPool/1.jpg', 117 ),
( 'PEACOCKS ANDHRA PALTA-3', 'productPool/1.jpg', 92 ),
( 'PEACOCKS BELITA WATER BOTTLE 900ML', 'productPool/1.jpg', 16 ),
( 'PEACOCKS COPPER FLOW WATER BOTTLE 1L', 'productPool/1.jpg', 140 ),
( 'PEACOCKS DESERT FORK 6NOS', 'productPool/1.jpg', 140 ),
( 'PEACOCKS ELITE COFFEE SPOON', 'productPool/1.jpg', 27 ),
( 'PEACOCKS ELITE ICE CREAM SPOON 6NOS', 'productPool/1.jpg', 20 ),
( 'PEACOCKS ELITE TEA SPOON 6NOS', 'productPool/1.jpg', 46 ),
( 'PEACOCKS FANTOS WATER BOTTLE 350ML', 'productPool/1.jpg', 139 ),
( 'PEACOCKS GALAXY BABY FORK 6NOS', 'productPool/1.jpg', 203 ),
( 'PEACOCKS GALAXY BABY SPOON 6N', 'productPool/1.jpg', 263 ),
( 'PEACOCKS GALAXY SERVICE SPOON 2N', 'productPool/1.jpg', 30 ),
( 'PEACOCKS GALAXY TEA FORK 6NOS', 'productPool/1.jpg', 75 ),
( 'PEACOCKS GALAXY TEA SPOON 6NOS', 'productPool/1.jpg', 216 ),
( 'PEACOCKS GELITO LUNCH PACK STEEL', 'productPool/1.jpg', 9 ),
( 'PEACOCKS KALORS WATER BOOTTLE', 'productPool/1.jpg', 188 ),
( 'PEACOCKS KHUSHI JHARA', 'productPool/1.jpg', 210 ),
( 'PEACOCKS KHUSHI KHURPI', 'productPool/1.jpg', 167 ),
( 'PEACOCKS LADDLE HAM 5', 'productPool/1.jpg', 59 ),
( 'PEACOCKS LADDLE-3', 'productPool/1.jpg', 66 ),
( 'PEACOCKS LARA BIG BOX', 'productPool/1.jpg', 272 ),
( 'PEACOCKS LARA LUNCH BOX SMALL', 'productPool/1.jpg', 108 ),
( 'PEACOCKS OVAL-1', 'productPool/1.jpg', 3 ),
( 'PEACOCKS OVAL-3', 'productPool/1.jpg', 230 ),
( 'PEACOCKS OVAL-4', 'productPool/1.jpg', 45 ),
( 'PEACOCKS PAN -3', 'productPool/1.jpg', 269 ),
( 'PEACOCKS PAN-1', 'productPool/1.jpg', 253 ),
( 'PEACOCKS PAN-4', 'productPool/1.jpg', 133 ),
( 'PEACOCKS RICE OVAL', 'productPool/1.jpg', 17 ),
( 'PEACOCKS RICE PANJA BIG', 'productPool/1.jpg', 135 ),
( 'PEACOCKS SAPPHIR DESERT SPOON 3N', 'productPool/1.jpg', 16 ),
( 'PEACOCKS SAPPHIRE DESERT SPOON', 'productPool/1.jpg', 100 ),
( 'PEACOCKS SPECTRA LUNCH PACK', 'productPool/1.jpg', 254 ),
( 'PEACOCKS SQUADE WATER BOTTLE 750ML', 'productPool/1.jpg', 100 ),
( 'PEACOCKS TLC LUNCH BOX B', 'productPool/1.jpg', 72 ),
( 'PEACOCKS VENICE COFFEE SPOON 6N', 'productPool/1.jpg', 263 ),
( 'PEACOCKS VENICE LADDLE 11', 'productPool/1.jpg', 230 ),
( 'PEACOCKS VENICE LADDLE 9', 'productPool/1.jpg', 235 ),
( 'PEACOCKS VENICE SOUP SPOON 6N', 'productPool/1.jpg', 25 ),
( 'PEACOCOK BUDS', 'productPool/1.jpg', 32 ),
( 'PEACOCOK SLIM BULLET FLASK', 'productPool/1.jpg', 87 ),
( 'PEACOCOK SLIM BULLET FLASK 1000SS', 'productPool/1.jpg', 131 ),
( 'PEACOCOK SLIM BULLET FLASK 500SS', 'productPool/1.jpg', 197 ),
( 'PEACOCOK SLIM BULLET FLASK 750SS', 'productPool/1.jpg', 82 ),
( 'PEACOCOK VENICE BABY SPOON', 'productPool/1.jpg', 44 ),
( 'PEANUT BALL 100G', 'productPool/1.jpg', 66 ),
( 'PEANUT CANDY 450G', 'productPool/1.jpg', 170 ),
( 'PEANUT PERKS COOKIES 200G', 'productPool/1.jpg', 154 ),
( 'PEARLDEW BOROTAG ANTISEPTIC CREAM 30G', 'productPool/1.jpg', 176 ),
( 'PEARLDEW DENTOMIST HERBAL TOOTHPAST 100G', 'productPool/1.jpg', 132 ),
( 'PEARS FRESHNESS FACEWASH 60G', 'productPool/1.jpg', 109 ),
( 'PEARS OIL CLEAR GLOW 75G', 'productPool/1.jpg', 139 ),
( 'PEARS OILCLEAR GLOW FACEWASH 60G', 'productPool/1.jpg', 60 ),
( 'PEARS PURE & GENTLE SOAP 4*125G', 'productPool/1.jpg', 259 ),
( 'PEARS PURE AND GENTILE 225G', 'productPool/1.jpg', 229 ),
( 'PEARS PURE AND GENTLE 75G', 'productPool/1.jpg', 128 ),
( 'PEARS PURE GENTILE 125G', 'productPool/1.jpg', 262 ),
( 'PEARS PURE GENTLE 3GET 1 FREE', 'productPool/1.jpg', 89 ),
( 'PEARS PURE GENTLE SOAP 3*125G', 'productPool/1.jpg', 123 ),
( 'PEARS PUREGENFACWASH 60G', 'productPool/1.jpg', 193 ),
( 'PEARS SOAP IMP', 'productPool/1.jpg', 82 ),
( 'PEARS SOFT & FRESH SOAP 3*125G', 'productPool/1.jpg', 271 ),
( 'PEARS SOFT AND FRESH 100G', 'productPool/1.jpg', 200 ),
( 'PEARS SOFT AND FRESH 75G', 'productPool/1.jpg', 258 ),
( 'PEDIA SURE CHOCOATE 200JAR', 'productPool/1.jpg', 109 ),
( 'PEDIA SURE PREMIUM CHOCOLATE 1KG', 'productPool/1.jpg', 117 ),
( 'PEDIA SURE VANILLA DELIGHT 200G JAR', 'productPool/1.jpg', 94 ),
( 'PEDIA SURE VANILLA DELIGHT 400G JAR', 'productPool/1.jpg', 228 ),
( 'PEDIALYTE ELECTROLYTE 200ML', 'productPool/1.jpg', 184 ),
( 'PEDIALYTE ELECTROLYTE APPLE 200ML', 'productPool/1.jpg', 220 ),
( 'PEDIASURE CHOCO 400G JAR', 'productPool/1.jpg', 188 ),
( 'PEDIASURE CHOCOLATE 200G REFILL', 'productPool/1.jpg', 246 ),
( 'PEDIASURE CHOCOLATE FLAVOUR 1KG', 'productPool/1.jpg', 176 ),
( 'PEDIASURE CHOCOLATE JAR 1 KG', 'productPool/1.jpg', 221 ),
( 'PEDIASURE CHOCOLATE JAR 200G', 'productPool/1.jpg', 154 ),
( 'PEDIASURE CHOCOLATE REFIL 400G', 'productPool/1.jpg', 159 ),
( 'PEDIASURE CHOCOLATE REFIL 750G', 'productPool/1.jpg', 110 ),
( 'PEDIASURE KESAR BADAM 200G', 'productPool/1.jpg', 262 ),
( 'PEDIASURE KESAR BEDAM FL 200G', 'productPool/1.jpg', 277 ),
( 'PEDIASURE PREMUIM CHOCOLATE 400G', 'productPool/1.jpg', 99 ),
( 'PEDIASURE VANILA 400G REFIL', 'productPool/1.jpg', 269 ),
( 'PEDIASURE VANILA 400G TIN', 'productPool/1.jpg', 19 ),
( 'PEDIASURE VANILA DELIGHT 1KG RF', 'productPool/1.jpg', 6 ),
( 'PEDIASURE VANILLA 200G JAR', 'productPool/1.jpg', 94 ),
( 'PEDIASURE VANILLA 200G REFILL', 'productPool/1.jpg', 133 ),
( 'PEDIASURE VANILLA 750G REFILL', 'productPool/1.jpg', 140 ),
( 'PEDIASURE VANILLA DELIGHT 1KG RF', 'productPool/1.jpg', 142 ),
( 'PEDIGREE ADULT CHICKEN & VEG 1.2KG', 'productPool/1.jpg', 6 ),
( 'PEDIGREE ADULT CHICKEN & VEG 20KG', 'productPool/1.jpg', 256 ),
( 'PEDIGREE ADULT CHICKEN AND VEG 100G', 'productPool/1.jpg', 112 ),
( 'PEDIGREE ADULT CHICKEN&VEG 3KG', 'productPool/1.jpg', 118 ),
( 'PEDIGREE ADULT CHK & VEG 10KG', 'productPool/1.jpg', 266 ),
( 'PEDIGREE ADULT MEAT RICE 1.2KG', 'productPool/1.jpg', 207 ),
( 'PEDIGREE ADULTCHICKEN & VEG 400G', 'productPool/1.jpg', 267 ),
( 'PEDIGREE PUPPY CHICKEN & MILK 10KG', 'productPool/1.jpg', 175 ),
( 'PEDIGREE PUPPY CHICKEN MILK 400G', 'productPool/1.jpg', 24 ),
( 'PEDIGREE PUPPY CHICKEN&MILK 1.2KG', 'productPool/1.jpg', 60 ),
( 'PEDIGREE PUPY CHICKEN MILK 3KG', 'productPool/1.jpg', 169 ),
( 'PEE SAFE NATURAL NTIMATE WASH 27ML', 'productPool/1.jpg', 154 ),
( 'PEE SAFE TOILET SEAT SANITIZER FLORAL 75ML', 'productPool/1.jpg', 98 ),
( 'PEE SAFE TOILET SEAT SANITIZER MINT 75ML', 'productPool/1.jpg', 184 ),
( 'PEECHINGA', 'productPool/1.jpg', 107 ),
( 'PEELAR', 'productPool/1.jpg', 123 ),
( 'PEELAR IMP', 'productPool/1.jpg', 198 ),
( 'PEELAR RS39', 'productPool/1.jpg', 79 ),
( 'PEELAR RS98', 'productPool/1.jpg', 207 ),
( 'PEELER', 'productPool/1.jpg', 186 ),
( 'PEELER RS16.50', 'productPool/1.jpg', 181 ),
( 'PEELER RS45', 'productPool/1.jpg', 56 ),
( 'PEESAFE NATURAL INTIMATE WASH105ML', 'productPool/1.jpg', 248 ),
( 'PEESAFE TIOLET SEAT SANITIZER LAVENDER 300ML', 'productPool/1.jpg', 189 ),
( 'PEESAFE TIOLET SEAT SANITIZER MINT 300ML', 'productPool/1.jpg', 13 ),
( 'PEESAFE TOILET SEAT SANITIZER LAVENDER 75ML', 'productPool/1.jpg', 25 ),
( 'PEN ELKOS COLOURS 20PCS', 'productPool/1.jpg', 10 ),
( 'PENCIL BOX RS 114', 'productPool/1.jpg', 206 ),
( 'PENCIL BOX RS 135', 'productPool/1.jpg', 190 ),
( 'PENCIL BOX RS 36', 'productPool/1.jpg', 139 ),
( 'PENCIL BOX RS 50', 'productPool/1.jpg', 48 ),
( 'PENCIL BOX RS 52', 'productPool/1.jpg', 191 ),
( 'PENCIL BOX RS 60', 'productPool/1.jpg', 180 ),
( 'PENCIL BOX RS110', 'productPool/1.jpg', 108 ),
( 'PENCIL BOX RS44', 'productPool/1.jpg', 203 ),
( 'PENCIL BOX RS54', 'productPool/1.jpg', 165 ),
( 'PENCIL BOX RS58', 'productPool/1.jpg', 267 ),
( 'PENCIL BOX RS70', 'productPool/1.jpg', 97 ),
( 'PENCIL BOX RS76', 'productPool/1.jpg', 218 ),
( 'PENCIL BOX RS79', 'productPool/1.jpg', 162 ),
( 'PENCIL BOX RS85', 'productPool/1.jpg', 33 ),
( 'PENCIL BOX RS90', 'productPool/1.jpg', 228 ),
( 'PENCIL POUCH 28', 'productPool/1.jpg', 109 ),
( 'PENCIL POUCH RS 110', 'productPool/1.jpg', 169 ),
( 'PENCIL POUCH RS 115', 'productPool/1.jpg', 163 ),
( 'PENCIL POUCH RS 118', 'productPool/1.jpg', 57 ),
( 'PENCIL POUCH RS 36', 'productPool/1.jpg', 139 ),
( 'PENCIL POUCH RS 40', 'productPool/1.jpg', 37 ),
( 'PENCIL POUCH RS 65', 'productPool/1.jpg', 220 ),
( 'PENCIL POUCH RS 70', 'productPool/1.jpg', 217 ),
( 'PENCIL POUCH RS 76', 'productPool/1.jpg', 275 ),
( 'PENCIL POUCH RS 88', 'productPool/1.jpg', 6 ),
( 'PENCIL POUCH RS120', 'productPool/1.jpg', 202 ),
( 'PENCIL POUCH RS130', 'productPool/1.jpg', 255 ),
( 'PENCIL POUCH RS140', 'productPool/1.jpg', 61 ),
( 'PENCIL POUCH RS155', 'productPool/1.jpg', 139 ),
( 'PENCIL POUCH RS36', 'productPool/1.jpg', 228 ),
( 'PENCIL POUCH RS40', 'productPool/1.jpg', 46 ),
( 'PENCIL POUCH RS60', 'productPool/1.jpg', 268 ),
( 'PENCIL POUCH RS85', 'productPool/1.jpg', 178 ),
( 'PEPE BBQ CHARCOAL FUEL 180G', 'productPool/1.jpg', 33 ),
( 'PEPPER CHICKEN MASALA 100G', 'productPool/1.jpg', 39 ),
( 'PEPPER PAPPADAM 100G', 'productPool/1.jpg', 168 ),
( 'PEPSI 1250ML', 'productPool/1.jpg', 107 ),
( 'PEPSI 150ML CAN', 'productPool/1.jpg', 32 ),
( 'PEPSI 250ML BOTTLE', 'productPool/1.jpg', 155 ),
( 'PEPSI 2L', 'productPool/1.jpg', 31 ),
( 'PEPSI 600ML BOTTLE', 'productPool/1.jpg', 142 ),
( 'PEPSI BLACK 250ML CAN', 'productPool/1.jpg', 43 ),
( 'PEPSI COLA CAN 250ML', 'productPool/1.jpg', 129 ),
( 'PEPSI COLA PET 2L', 'productPool/1.jpg', 102 ),
( 'PEPSI COLA PET 600+150ML FREE', 'productPool/1.jpg', 196 ),
( 'PEPSI DIET CAN 250ML', 'productPool/1.jpg', 80 ),
( 'PEPSODENT 2 IN 1 TOOTH PASTE 150G', 'productPool/1.jpg', 155 ),
( 'PEPSODENT 2IN1 80G', 'productPool/1.jpg', 189 ),
( 'PEPSODENT CERM CHEK 200G', 'productPool/1.jpg', 217 ),
( 'PEPSODENT CLOVE SALT 100G', 'productPool/1.jpg', 39 ),
( 'PEPSODENT CLOVE SALT TOOTH PASTE 100G', 'productPool/1.jpg', 235 ),
( 'PEPSODENT CLOVE-SALT 23G+5G', 'productPool/1.jpg', 266 ),
( 'PEPSODENT EXPERT PROTECTION GUM CARE 280G', 'productPool/1.jpg', 237 ),
( 'PEPSODENT GERMCHECK TOOTHPASTE 140G', 'productPool/1.jpg', 4 ),
( 'PEPSODENT GERMI CHECK 25G', 'productPool/1.jpg', 239 ),
( 'PEPSODENT GERMI CHECK CLOVE 27G', 'productPool/1.jpg', 172 ),
( 'PEPSODENT GERMICHECK TOOTH PASTE 200G', 'productPool/1.jpg', 90 ),
( 'PEPSODENT GERMICHECK TOOTH PASTE FREE LIFEBOUY', 'productPool/1.jpg', 273 ),
( 'PEPSODENT GUMCARE PASTE 140G', 'productPool/1.jpg', 57 ),
( 'PEPSODENT GUMCARE PASTE 70G', 'productPool/1.jpg', 127 ),
( 'PEPSODENT TOOTH PASTE 300G', 'productPool/1.jpg', 49 ),
( 'PEPSODENT WHITENIN 150G', 'productPool/1.jpg', 59 ),
( 'PEPSODNT WHITENING 80G', 'productPool/1.jpg', 216 ),
( 'PERMANENT MARKER BLUE', 'productPool/1.jpg', 49 ),
( 'PERMANENT MARKER RED/BLUE/BLACK', 'productPool/1.jpg', 279 ),
( 'PERSIL LIQUID 2.7L', 'productPool/1.jpg', 82 ),
( 'PERSIL LIQUID 2L', 'productPool/1.jpg', 35 ),
( 'PERSIL LIQUID SILK 750ML', 'productPool/1.jpg', 196 ),
( 'PERUMJEERAKAM 100G', 'productPool/1.jpg', 212 ),
( 'PERUMJEERAKAM 200G', 'productPool/1.jpg', 37 ),
( 'PERUMJEERAKAM PREMIUM 100GM', 'productPool/1.jpg', 95 ),
( 'PESPSODENT GERMI CHECK 100G', 'productPool/1.jpg', 202 ),
( 'PET KING DBL SIDE COMB', 'productPool/1.jpg', 207 ),
( 'PETSO VET SHAMPOO 100ML', 'productPool/1.jpg', 149 ),
( 'PETSO VET SOAP 65G', 'productPool/1.jpg', 148 ),
( 'PEXPO ARISTO 750ML COLOUR WATER BOTTLE', 'productPool/1.jpg', 119 ),
( 'PEXPO ARISTO 750ML PLAIN WATER BOTTLE', 'productPool/1.jpg', 238 ),
( 'PEZ ANGRY BIRDS 17G', 'productPool/1.jpg', 25 ),
( 'PHALHARI CHIWDA 150G', 'productPool/1.jpg', 180 ),
( 'PHENYLE DOCTORS 450ML', 'productPool/1.jpg', 211 ),
( 'PHILIPS AVENT BOTTLE AND TEAT BRUSH GENERAL', 'productPool/1.jpg', 185 ),
( 'PHILIPS AVENT CLASSIC SPOUT CUP SCF551/03', 'productPool/1.jpg', 264 ),
( 'PHILIPS AVENT CLASSIC SPOUT CUP SCF551/05', 'productPool/1.jpg', 145 ),
( 'PHILIPS AVENT CLASSIC SPOUT CUP SCF553/03', 'productPool/1.jpg', 28 ),
( 'PHILIPS AVENT CLASSIC SPOUT CUP SCF553/05', 'productPool/1.jpg', 215 ),
( 'PHILIPS AVENT FEEDING BOTTLE 125ML', 'productPool/1.jpg', 246 ),
( 'PHILIPS AVENT FEEDING BOTTLE 260ML', 'productPool/1.jpg', 98 ),
( 'PHILIPS AVENT FEEDING BOTTLE 330ML', 'productPool/1.jpg', 139 ),
( 'PHILIPS AVENT SOOTHER SCF178/13', 'productPool/1.jpg', 139 ),
( 'PHILIPS AVENT SOOTHER SCF178/14', 'productPool/1.jpg', 48 ),
( 'PHILIPS AVENT TEAT TWIN PACK FAST FLOW', 'productPool/1.jpg', 59 ),
( 'PHILIPS AVENT TEAT TWIN PACK MEDIUM FLOW', 'productPool/1.jpg', 100 ),
( 'PHILIPS AVENT TEAT TWIN PACK SLOW FLOW', 'productPool/1.jpg', 277 ),
( 'PHILIPS TUBE 36W', 'productPool/1.jpg', 87 ),
( 'PHOTO PRINTING ON CAKE', 'productPool/1.jpg', 56 ),
( 'PICADELI CHOCOLATE PKT IMP', 'productPool/1.jpg', 212 ),
( 'PICK UP JCB', 'productPool/1.jpg', 261 ),
( 'PIETRO CORICE OLIVE OIL 100ML', 'productPool/1.jpg', 173 ),
( 'PIETRO CORICELLI EXTRA VIRGIN OLIVE OIL 100ML', 'productPool/1.jpg', 190 ),
( 'PIETRO CORICELLI EXTRA VIRGIN OLIVE OIL 250ML', 'productPool/1.jpg', 131 ),
( 'PIETRO EXTRA VIRGIN OLIVE OIL 1 LTR', 'productPool/1.jpg', 54 ),
( 'PIETRO OLIVE OIL 250ML', 'productPool/1.jpg', 222 ),
( 'PIETRO OLIVE POMACE OIL 1LTR', 'productPool/1.jpg', 198 ),
( 'PIETROCORICELLI EXTRA VIRGIN OLIVE OIL 500ML', 'productPool/1.jpg', 227 ),
( 'PIGEON BLING SS WATER BOTTLE 750ML', 'productPool/1.jpg', 96 ),
( 'PIGEON DUOS HOOK 2PCS SET', 'productPool/1.jpg', 75 ),
( 'PIGEON JUMBO GAS LIGHTER', 'productPool/1.jpg', 209 ),
( 'PIGEON LEMON SQUEEZER SPLASH', 'productPool/1.jpg', 259 ),
( 'PIGEON LPG HOSE', 'productPool/1.jpg', 133 ),
( 'PIGEON PLUTO HOOK 6PCS SET', 'productPool/1.jpg', 259 ),
( 'PIGEON SMART GAS LIGHTER', 'productPool/1.jpg', 235 ),
( 'PIGEON SMART GASLIGHTER', 'productPool/1.jpg', 205 ),
( 'PIGEON STEELO GAS LIGHTER', 'productPool/1.jpg', 107 ),
( 'PIGEON SUPER GASLIGHTER', 'productPool/1.jpg', 160 ),
( 'PIGEON SWIG WATER BOTTLE 500ML', 'productPool/1.jpg', 171 ),
( 'PIGEON SWIG WATERBOTTLE 750ML', 'productPool/1.jpg', 80 ),
( 'PILLSBERY FRENCH VANILA CAKE MIX 520G', 'productPool/1.jpg', 74 ),
( 'PILLSBURY ATTA 10KG', 'productPool/1.jpg', 187 ),
( 'PILLSBURY ATTA 1KG', 'productPool/1.jpg', 102 ),
( 'PILLSBURY ATTA 2KG', 'productPool/1.jpg', 123 ),
( 'PILLSBURY ATTA 5KG', 'productPool/1.jpg', 199 ),
( 'PILLSBURY CHOCO IDLI CAKE MIX 120G', 'productPool/1.jpg', 273 ),
( 'PILLSBURY COOKIE CAKE CHOCO 23G', 'productPool/1.jpg', 113 ),
( 'PILLSBURY COOKIE CAKE CHOCO 6P', 'productPool/1.jpg', 187 ),
( 'PILLSBURY COOKIE CAKE NUT BUTTER 60G', 'productPool/1.jpg', 240 ),
( 'PILLSBURY COOKIE CAKE TUTTI FRUTTI 138G', 'productPool/1.jpg', 215 ),
( 'PILLSBURY COOKIE CAKE TUTTI FRUTTI 23G', 'productPool/1.jpg', 253 ),
( 'PILLSBURY COOKIE CAKE VANILA 6P', 'productPool/1.jpg', 18 ),
( 'PILLSBURY COOKIE CAKE VANILLA 23G', 'productPool/1.jpg', 126 ),
( 'PILLSBURY CUSTARD POWDER VANILLA 100G', 'productPool/1.jpg', 83 ),
( 'PILLSBURY LAVA CAKE CHOCO 28G', 'productPool/1.jpg', 50 ),
( 'PILLSBURY LAVA CAKE VANILA 28G', 'productPool/1.jpg', 279 ),
( 'PILLSBURY MILK CHOCO SPREAD 180GM', 'productPool/1.jpg', 164 ),
( 'PILLSBURY MINI COOKIE CAKE 2IN1 60G', 'productPool/1.jpg', 255 ),
( 'PILLSBURY MINI COOKIE CAKE 77G', 'productPool/1.jpg', 104 ),
( 'PILLSBURY MINI COOKIE CAKE CHOCO 66G', 'productPool/1.jpg', 264 ),
( 'PILLSBURY PASTRY CAKE CHOCO25G', 'productPool/1.jpg', 47 ),
( 'PILLSBURY PASTRY CAKE RED VELVET 23G', 'productPool/1.jpg', 89 ),
( 'PILLSBURY PASTRY CAKE RED VELVET92G', 'productPool/1.jpg', 41 ),
( 'PILLSBURY PASTRY CAKE STRAWBERY 25G', 'productPool/1.jpg', 208 ),
( 'PILLSBURY PASTRY CAKE STRAWBERY 25G*4', 'productPool/1.jpg', 192 ),
( 'PILLSBURY VANILA OVEN CAKE MIX 225G', 'productPool/1.jpg', 139 ),
( 'PINA COLADA SKORE CONDOMS', 'productPool/1.jpg', 142 ),
( 'PINA SAFFRON SUPREME 3G', 'productPool/1.jpg', 233 ),
( 'PINE SOL MULTI PURPOSE CLEANER LAVENDER 828ML', 'productPool/1.jpg', 104 ),
( 'PINE SOL MULTI PURPOSE CLEANER LEMON 828ML', 'productPool/1.jpg', 255 ),
( 'PINE SOL SPARKLING WAVE 1.41L', 'productPool/1.jpg', 157 ),
( 'PINEAPPLE', 'productPool/1.jpg', 184 ),
( 'PINEAPPLE FRUIT CRUSH 750ML', 'productPool/1.jpg', 144 ),
( 'PINEAPPLE FRUIT JAM1 KG', 'productPool/1.jpg', 26 ),
( 'PINEAPPLE MOOSE', 'productPool/1.jpg', 246 ),
( 'PINEAPPLE PEEL 100G', 'productPool/1.jpg', 29 ),
( 'PINESOLMULTISURFACEDEODORIZERLEMON 1.41L', 'productPool/1.jpg', 249 ),
( 'PING PANG LOLLIPOP', 'productPool/1.jpg', 240 ),
( 'PINK GUAVA DRINK 250ML', 'productPool/1.jpg', 188 ),
( 'PINK LADY APPLE USA', 'productPool/1.jpg', 276 ),
( 'PINKY SOAP BOX', 'productPool/1.jpg', 248 ),
( 'PIPPY COCONUT 50G', 'productPool/1.jpg', 166 ),
( 'PIPPY COCONUT BON BON 80G', 'productPool/1.jpg', 50 ),
( 'PIPPY GINGER CANDY 100G', 'productPool/1.jpg', 70 ),
( 'PIPPY JAGGERY CANDY 75G', 'productPool/1.jpg', 243 ),
( 'PIPPY LACTO BON BON 80G', 'productPool/1.jpg', 243 ),
( 'PIPPY MIX FRUIT CANDY 110G', 'productPool/1.jpg', 257 ),
( 'PIPPY ORANGE CANDY 100G', 'productPool/1.jpg', 132 ),
( 'PIPPY PEANUT CANDY 70G', 'productPool/1.jpg', 87 ),
( 'PIRIYAN CHILLI 100G', 'productPool/1.jpg', 103 ),
( 'PIRIYAN CHILLI 250G', 'productPool/1.jpg', 44 ),
( 'PIRIYAN CHILLI 250GMS', 'productPool/1.jpg', 51 ),
( 'PIRIYAN CHILLI 500G', 'productPool/1.jpg', 161 ),
( 'PIRIYAN CHILLI II 100G', 'productPool/1.jpg', 269 ),
( 'PISTA 100G', 'productPool/1.jpg', 160 ),
( 'PISTA 200G', 'productPool/1.jpg', 59 ),
( 'PISTA 250G', 'productPool/1.jpg', 26 ),
( 'PISTA PEELED 100G', 'productPool/1.jpg', 258 ),
( 'PISTA SALTED', 'productPool/1.jpg', 267 ),
( 'PITAMBARI DISH WASH 500G', 'productPool/1.jpg', 104 ),
( 'PITAMBARI DISHWASH BAR 300G', 'productPool/1.jpg', 70 ),
( 'PITAMBARI DISHWASH CAKE 500G', 'productPool/1.jpg', 17 ),
( 'PITAMBARI DISHWASH TUB 500G', 'productPool/1.jpg', 250 ),
( 'PITAMBARI JAGGERY POWDER 500G', 'productPool/1.jpg', 204 ),
( 'PITAMBARI ROOPERI 50ML', 'productPool/1.jpg', 182 ),
( 'PITAMBARI SANIT ALL SUPER POWER 500ML', 'productPool/1.jpg', 200 ),
( 'PITAMBARI SHINING POWDER 100G', 'productPool/1.jpg', 113 ),
( 'PITAMBARI SHINING POWDER 200G', 'productPool/1.jpg', 246 ),
( 'PITAMBARI SHINING POWDER50G', 'productPool/1.jpg', 222 ),
( 'PIXCY GARBAGE BAGS30PCS', 'productPool/1.jpg', 121 ),
( 'PIXY GARBAGE BAG LARGE GCC108C', 'productPool/1.jpg', 154 ),
( 'PIXY GARBAGE BAG MEDIUM ME14', 'productPool/1.jpg', 101 ),
( 'PLAIN FILE', 'productPool/1.jpg', 165 ),
( 'PLAIN SAGO APPALAM 100G', 'productPool/1.jpg', 155 ),
( 'PLAKER EO', 'productPool/1.jpg', 52 ),
( 'PLASTIC GLASS 250ML 50P', 'productPool/1.jpg', 266 ),
( 'PLASTIC ROLL RED', 'productPool/1.jpg', 90 ),
( 'PLASTIC ROLL WHITE', 'productPool/1.jpg', 237 ),
( 'PLASTIC SPOON 100S', 'productPool/1.jpg', 273 ),
( 'PLASTIC SPOON SILKY 100PCS', 'productPool/1.jpg', 173 ),
( 'PLASTIC SPOON SPARKO', 'productPool/1.jpg', 218 ),
( 'PLASTIC TONGUE CLEANER', 'productPool/1.jpg', 274 ),
( 'PLATE SMALL 4 INCH 100P', 'productPool/1.jpg', 180 ),
( 'PLATE SMALL 6 INCH', 'productPool/1.jpg', 33 ),
( 'PLATE SMALL 7 INCH 100P', 'productPool/1.jpg', 226 ),
( 'PLUCKER', 'productPool/1.jpg', 251 ),
( 'PLUNGER BIG', 'productPool/1.jpg', 152 ),
( 'PMI FRUIT SALAD YOGURT 125G', 'productPool/1.jpg', 147 ),
( 'PMI FRUIT STRAWBERY YOGURT 125G', 'productPool/1.jpg', 186 ),
( 'PMP CORIANDER POWDER 200G', 'productPool/1.jpg', 175 ),
( 'PMP CORIANDER POWDER 500G', 'productPool/1.jpg', 189 ),
( 'PMP KASHMIRICHILLIPOWDER200G', 'productPool/1.jpg', 110 ),
( 'POABS SUPER BLEND TEA 1 KG', 'productPool/1.jpg', 109 ),
( 'POABS SUPREME CTC DUST TEA 250 KG', 'productPool/1.jpg', 207 ),
( 'POABS SUPREME CTC DUST TEA 500 KG', 'productPool/1.jpg', 186 ),
( 'POCKET TISSUE', 'productPool/1.jpg', 229 ),
( 'POCKET TISSUE IMP', 'productPool/1.jpg', 66 ),
( 'POLAR HANDY BOTTLE 500ML', 'productPool/1.jpg', 235 ),
( 'POLLO MINT 15G', 'productPool/1.jpg', 127 ),
( 'POLO 15G', 'productPool/1.jpg', 225 ),
( 'POLO 6G JUG MRP2', 'productPool/1.jpg', 55 ),
( 'POLO DEO - 9 BLAZER 175ML', 'productPool/1.jpg', 135 ),
( 'POLO DEO - 9 MISOURIE 150ML', 'productPool/1.jpg', 201 ),
( 'POLO DEO -2 GRANDE SPRAY 175ML', 'productPool/1.jpg', 57 ),
( 'POLO DEO -8 HIGHLANDER SPRAY 175ML', 'productPool/1.jpg', 190 ),
( 'POLO DEO 8 FOR WOMEN SPRAY 150ML', 'productPool/1.jpg', 211 ),
( 'POLO DEO BUY 2GET 1-3*150ML', 'productPool/1.jpg', 279 ),
( 'POLO DEO DARLEY MEN -1 150ML', 'productPool/1.jpg', 30 ),
( 'POLO DEO MUSTANG SPRAY -1 175ML', 'productPool/1.jpg', 52 ),
( 'POLO DOUBLE HOCKEY BRUSH', 'productPool/1.jpg', 31 ),
( 'POLO MINI 6G', 'productPool/1.jpg', 118 ),
( 'POLO MINT NEW TASTE 30G', 'productPool/1.jpg', 266 ),
( 'POLO RS2', 'productPool/1.jpg', 162 ),
( 'POLO SPORT DEO -2-175ML', 'productPool/1.jpg', 159 ),
( 'POLO SPORT DEO -8-175ML', 'productPool/1.jpg', 77 ),
( 'POLO SPORT DEO 1 175ML', 'productPool/1.jpg', 204 ),
( 'POLO SPORT DEO9-175ML', 'productPool/1.jpg', 216 ),
( 'POLPAT NO 11', 'productPool/1.jpg', 169 ),
( 'POLPAT NO.10', 'productPool/1.jpg', 154 ),
( 'POLPAT NO.9', 'productPool/1.jpg', 236 ),
( 'POLY BAG 30*50', 'productPool/1.jpg', 75 ),
( 'POMEGRANATE 1KG', 'productPool/1.jpg', 205 ),
( 'POMEGRANITE', 'productPool/1.jpg', 203 ),
( 'POMELO GREEN DRIED 100G', 'productPool/1.jpg', 152 ),
( 'PONDS AGE DAY CREAM 10G', 'productPool/1.jpg', 203 ),
( 'PONDS AGE MIRACLE CORRECTING CREAM 50G', 'productPool/1.jpg', 151 ),
( 'PONDS AGE MIRACLE FACIAL FOAM 100G', 'productPool/1.jpg', 189 ),
( 'PONDS AGE MIRACLE KIT', 'productPool/1.jpg', 270 ),
( 'PONDS AGE MIRACLESPF15 CREAM 35G', 'productPool/1.jpg', 229 ),
( 'PONDS COLD CREAM MOISTURISE 100ML', 'productPool/1.jpg', 124 ),
( 'PONDS COLD CREAM MOISTURISE 55ML', 'productPool/1.jpg', 148 ),
( 'PONDS COLD CREAM30ML', 'productPool/1.jpg', 263 ),
( 'PONDS DAILY FACE WASH 50G', 'productPool/1.jpg', 111 ),
( 'PONDS DREAM FLOWER FRAGRANT 100G', 'productPool/1.jpg', 200 ),
( 'PONDS DREAMFLOWER FRAGRANT TALC 100G', 'productPool/1.jpg', 60 ),
( 'PONDS DREAMFLOWER FRAGRANT TALC 200G', 'productPool/1.jpg', 45 ),
( 'PONDS DREAMFLOWER FRAGRANT TALC 25G', 'productPool/1.jpg', 17 ),
( 'PONDS DREAMFLOWER FRAGRANT TALC 400G', 'productPool/1.jpg', 173 ),
( 'PONDS DREAMFLOWER FRAGRANT TALC 50G', 'productPool/1.jpg', 142 ),
( 'PONDS DREAMFLOWER TALC100G', 'productPool/1.jpg', 25 ),
( 'PONDS FLAWLESS RADIANCE DERMA BB CREAM 25G', 'productPool/1.jpg', 261 ),
( 'PONDS FLAWLESS RADIANCE DERMA DAY CREAM 25G', 'productPool/1.jpg', 15 ),
( 'PONDS FLAWLESS RADIANCE DERMA SERUM 30ML', 'productPool/1.jpg', 264 ),
( 'PONDS LIGHT MOISTURISER CREAM 74G', 'productPool/1.jpg', 250 ),
( 'PONDS MAGIC FRESHNESS TALC 100G', 'productPool/1.jpg', 173 ),
( 'PONDS MAGIC FRESHNESS TALC 25G', 'productPool/1.jpg', 218 ),
( 'PONDS MAGIC TALC 100G', 'productPool/1.jpg', 220 ),
( 'PONDS MAGIC TALC 400G', 'productPool/1.jpg', 108 ),
( 'PONDS MAGIC TALC 50G', 'productPool/1.jpg', 126 ),
( 'PONDS MEN ENERGY CARE FACE WASH 50G', 'productPool/1.jpg', 195 ),
( 'PONDS MEN ENERGY CHARGE FACEWASH 100G', 'productPool/1.jpg', 124 ),
( 'PONDS MOISTURISE COLD CREAM 49G', 'productPool/1.jpg', 112 ),
( 'PONDS MOISTURISING COLD CREAM 100ML', 'productPool/1.jpg', 214 ),
( 'PONDS MOISTURIZING DAY CREAM 50G', 'productPool/1.jpg', 266 ),
( 'PONDS OIL CONTROL 100G', 'productPool/1.jpg', 42 ),
( 'PONDS OIL CONTROL TALC350G', 'productPool/1.jpg', 61 ),
( 'PONDS PIMPLE CLEAR FACE WASH 100G', 'productPool/1.jpg', 131 ),
( 'PONDS POLLUTION OUT 50G DEEP CLEAN', 'productPool/1.jpg', 166 ),
( 'PONDS PURE WHITE FACE WASH 50G', 'productPool/1.jpg', 105 ),
( 'PONDS SANDAL RADIANCE TALC 100G', 'productPool/1.jpg', 249 ),
( 'PONDS SANDAL RADIANCE TALC 300G', 'productPool/1.jpg', 126 ),
( 'PONDS SANDAL TALC 300G', 'productPool/1.jpg', 49 ),
( 'PONDS SANDAL TALC 50G', 'productPool/1.jpg', 23 ),
( 'PONDS SILK CREAM 55ML', 'productPool/1.jpg', 125 ),
( 'PONDS STARLIGHT PERFUMED TALC 100G', 'productPool/1.jpg', 20 ),
( 'PONDS TRIPLE VITAMIN 300ML', 'productPool/1.jpg', 64 );