INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'ARIEL MATIC FRONT LOAD (4+2)KG', 'productPool/1.jpg', 83 ),
( 'ARIEL MATIC FRONT LOAD 1KG', 'productPool/1.jpg', 255 ),
( 'ARIEL MATIC FRONT LOAD 2KG', 'productPool/1.jpg', 108 ),
( 'ARIEL MATIC FRONT LOAD 3KG', 'productPool/1.jpg', 24 ),
( 'ARIEL MATIC FRONT LOAD 4KG+2KG', 'productPool/1.jpg', 123 ),
( 'ARIEL MATIC FRONT LOAD 500G', 'productPool/1.jpg', 114 ),
( 'ARIEL MATIC FRONT LOAD 6KG FREE CONTAINER', 'productPool/1.jpg', 175 ),
( 'ARIEL MATIC LIQUID 1.5L POUCH', 'productPool/1.jpg', 171 ),
( 'ARIEL MATIC LIQUID 1L', 'productPool/1.jpg', 56 ),
( 'ARIEL MATIC LIQUID 2L', 'productPool/1.jpg', 227 ),
( 'ARIEL MATIC LIQUID 500ML', 'productPool/1.jpg', 160 ),
( 'ARIEL MATIC LIQUID DETERGENT 2L', 'productPool/1.jpg', 167 ),
( 'ARIEL MATIC TOP LOAD (4+2)KG', 'productPool/1.jpg', 65 ),
( 'ARIEL MATIC TOP LOAD 1KG', 'productPool/1.jpg', 190 ),
( 'ARIEL MATIC TOP LOAD 2KG', 'productPool/1.jpg', 33 ),
( 'ARIEL MATIC TOP LOAD 3KG', 'productPool/1.jpg', 253 ),
( 'ARIEL MATIC TOP LOAD 3KG FREE CONTAINER', 'productPool/1.jpg', 265 ),
( 'ARIEL MATIC TOP LOAD 4+2 KG', 'productPool/1.jpg', 224 ),
( 'ARIEL MATIC TOP LOAD 4KG+2KG', 'productPool/1.jpg', 60 ),
( 'ARIEL MATIC TOP LOAD 500G', 'productPool/1.jpg', 63 ),
( 'ARIEL MATIC TOP LOAD 6KG FREE CONTAINER', 'productPool/1.jpg', 96 ),
( 'ARIEL PEERFECT WASH 500G', 'productPool/1.jpg', 187 ),
( 'ARIEL TOP LOAD 500G', 'productPool/1.jpg', 167 ),
( 'ARISTO AROMA BRUSH WITH STAND', 'productPool/1.jpg', 118 ),
( 'ARISTO BUDDA MONEY BANK', 'productPool/1.jpg', 149 ),
( 'ARISTO CAPTIVA BRUSH WITH CONTAINER', 'productPool/1.jpg', 209 ),
( 'ARISTO CEILING BROOM ARISTO', 'productPool/1.jpg', 132 ),
( 'ARISTO CHARLEE CUP', 'productPool/1.jpg', 177 ),
( 'ARISTO COSMOS BRUSH', 'productPool/1.jpg', 261 ),
( 'ARISTO COSMOS BRUSH WITH DUST PAN', 'productPool/1.jpg', 256 ),
( 'ARISTO DOLBY CUP', 'productPool/1.jpg', 272 ),
( 'ARISTO ELEPHANT BANK BIG', 'productPool/1.jpg', 267 ),
( 'ARISTO ELEPHANT BANK MEDIUM', 'productPool/1.jpg', 115 ),
( 'ARISTO EVER GREEN PEDAL BUCKET NO.1', 'productPool/1.jpg', 51 ),
( 'ARISTO EVER GREEN PEDAL BUCKET NO.2', 'productPool/1.jpg', 3 ),
( 'ARISTO GOLDIE CUP', 'productPool/1.jpg', 118 ),
( 'ARISTO JUMBO WATER JUG SMALL', 'productPool/1.jpg', 258 ),
( 'ARISTO LOTUS JUG DOUBLE COLOUR', 'productPool/1.jpg', 4 ),
( 'ARISTO NEPUTNE FLOOR BRUSH', 'productPool/1.jpg', 209 ),
( 'ARISTO OIL DISPENSER 1000ML', 'productPool/1.jpg', 229 ),
( 'ARISTO OSCAR MUG 1500ML PRINTED', 'productPool/1.jpg', 124 ),
( 'ARISTO PIGGY BANK BIG', 'productPool/1.jpg', 183 ),
( 'ARISTO PIGGY BANK SMALL', 'productPool/1.jpg', 72 ),
( 'ARISTO PLUTO DOUBLE HOCKEY BRUSH', 'productPool/1.jpg', 191 ),
( 'ARISTO RAMBO SPRAYER', 'productPool/1.jpg', 220 ),
( 'ARISTO RAPID FLOOR WIPER', 'productPool/1.jpg', 105 ),
( 'ARISTO STORE QUEEN 888 PRINT', 'productPool/1.jpg', 58 ),
( 'ARISTO STORE QUEEN 999 PRINT', 'productPool/1.jpg', 46 ),
( 'ARISTO STOREQUEEN 111 JAR', 'productPool/1.jpg', 51 ),
( 'ARISTO STOREQUEEN 222', 'productPool/1.jpg', 277 ),
( 'ARISTO STOREQUEEN 333 PRT 3PCS', 'productPool/1.jpg', 271 ),
( 'ARISTO STOREQUEEN 444 JAR', 'productPool/1.jpg', 94 ),
( 'ARISTO STOREQUEEN 555 PRINTED', 'productPool/1.jpg', 159 ),
( 'ARISTO STOREQUEEN 666 JAR', 'productPool/1.jpg', 198 ),
( 'ARISTO STOREWEL 201 3PCS SET', 'productPool/1.jpg', 185 ),
( 'ARISTO STOREWEL 202 3PCS SET', 'productPool/1.jpg', 94 ),
( 'ARISTO STOREWEL 203 3PCS SET', 'productPool/1.jpg', 22 ),
( 'ARISTO SUPER DELUXE FLOOR MOP', 'productPool/1.jpg', 268 ),
( 'ARISTO SUPRIYA DUST PAN BIG', 'productPool/1.jpg', 261 ),
( 'ARISTO SUPRIYA DUST PAN SMALL', 'productPool/1.jpg', 23 ),
( 'ARISTO WONDER KITCHEN WIPER', 'productPool/1.jpg', 43 ),
( 'ARIX AUTO FLASH CAR CHAMOIS', 'productPool/1.jpg', 136 ),
( 'ARIX BATH SPONGE', 'productPool/1.jpg', 261 ),
( 'ARIX BATH SPONGE AQUA MASSAGE', 'productPool/1.jpg', 247 ),
( 'ARIX BATH SPONGE AQUA MASSAGE FANTASY', 'productPool/1.jpg', 80 ),
( 'ARIX BATH SPONGE AQUA MASSAGE MOVIDA', 'productPool/1.jpg', 215 ),
( 'ARIX BATH SPONGE AQUA MASSAGE SOFT', 'productPool/1.jpg', 134 ),
( 'ARIX BATH SPONGE DEMA QUILAGE 2 PCS', 'productPool/1.jpg', 59 ),
( 'ARIX BATH SPONGE TONICA', 'productPool/1.jpg', 121 ),
( 'ARIX BETTINA SCOURING PAD 3PC', 'productPool/1.jpg', 151 ),
( 'ARIX BOTTLE BRUSH', 'productPool/1.jpg', 207 ),
( 'ARIX BROOM BASSA', 'productPool/1.jpg', 133 ),
( 'ARIX BROOM PUSH', 'productPool/1.jpg', 24 ),
( 'ARIX BROOM SARA', 'productPool/1.jpg', 263 ),
( 'ARIX CAR SPONGE JUMBO', 'productPool/1.jpg', 187 ),
( 'ARIX CAR SPONGE MAXI SMALL', 'productPool/1.jpg', 262 ),
( 'ARIX CELLULOSE SPONGE KIDS 946', 'productPool/1.jpg', 12 ),
( 'ARIX CELLULOSE SPONGE OVAL', 'productPool/1.jpg', 174 ),
( 'ARIX CLASSIC FIBRA ABRASIVA PAD', 'productPool/1.jpg', 112 ),
( 'ARIX COTTON TONKITA MOP', 'productPool/1.jpg', 200 ),
( 'ARIX DINAMICA OUT DOOR BROOM TK660', 'productPool/1.jpg', 258 ),
( 'ARIX DUAL INDOOR BROOM TK625', 'productPool/1.jpg', 279 ),
( 'ARIX DUST PAN TONKITA', 'productPool/1.jpg', 133 ),
( 'ARIX DUST PAN WITH BRUSH', 'productPool/1.jpg', 267 ),
( 'ARIX FLOOR MOP CLOTH STRIPS', 'productPool/1.jpg', 104 ),
( 'ARIX FLOOR RUBBER WIPER 33 CM', 'productPool/1.jpg', 240 ),
( 'ARIX GREEN SCOURING PAD 2 PCS', 'productPool/1.jpg', 128 ),
( 'ARIX GREEN SCOURING PAD SPENDELLI', 'productPool/1.jpg', 155 ),
( 'ARIX LATEX MAKE UP SPONGE SQUARE 2PC', 'productPool/1.jpg', 174 ),
( 'ARIX MAGNUM PUSH BROOM', 'productPool/1.jpg', 241 ),
( 'ARIX MICRO FIBER REFIL MOP', 'productPool/1.jpg', 4 ),
( 'ARIX MOP NEW FORMULA', 'productPool/1.jpg', 144 ),
( 'ARIX MULTIPURPOSE DUST CLOTH 1PC', 'productPool/1.jpg', 77 ),
( 'ARIX PANNOSPUGNA NEW SOFTY', 'productPool/1.jpg', 162 ),
( 'ARIX PLASTIC CLOTH LINE', 'productPool/1.jpg', 80 ),
( 'ARIX RADIATOR BRUSH TK077', 'productPool/1.jpg', 66 ),
( 'ARIX RILIEVI XTRA MOP EMBOSSED STRIPS', 'productPool/1.jpg', 67 ),
( 'ARIX SCRUBBER LARGE SIZE', 'productPool/1.jpg', 112 ),
( 'ARIX SPECTRO YELLOW DUST CLOTH', 'productPool/1.jpg', 202 ),
( 'ARIX SPLENDELLI GREEN PAD 2PC', 'productPool/1.jpg', 97 ),
( 'ARIX SPONGE SCOURER', 'productPool/1.jpg', 116 ),
( 'ARIX SPONGE SCOURER LARGE', 'productPool/1.jpg', 183 ),
( 'ARIX SPONGE SCOURER SMALL', 'productPool/1.jpg', 65 ),
( 'ARIX SPONGE SCRUBBER 2PCS', 'productPool/1.jpg', 65 ),
( 'ARIX SUNNY CELL SPONGE CLOTH', 'productPool/1.jpg', 174 ),
( 'ARIX SUNNY PANNO MULTIUSO', 'productPool/1.jpg', 65 ),
( 'ARIX SUNNY STEEL SCRUBBER', 'productPool/1.jpg', 169 ),
( 'ARIX SUNNY WOVEN MOP STRIPS', 'productPool/1.jpg', 183 ),
( 'ARIX SYNTHETIC SPONGE SCOURER', 'productPool/1.jpg', 54 ),
( 'ARIX TOILET BRUSH SET RS 298', 'productPool/1.jpg', 66 ),
( 'ARIX TONKITA BOTTLE BRUSH TK11506', 'productPool/1.jpg', 158 ),
( 'ARIX TONKITA CLOTH BRUSH', 'productPool/1.jpg', 241 ),
( 'ARIX TONKITA CORDA CLOTH LINE TK082', 'productPool/1.jpg', 168 ),
( 'ARIX TONKITA DISH WASHING BRUSH', 'productPool/1.jpg', 66 ),
( 'ARIX TONKITA DUST PAN WITH HANDIL', 'productPool/1.jpg', 165 ),
( 'ARIX TONKITA DUSTER FOR COMPUTER', 'productPool/1.jpg', 120 ),
( 'ARIX TONKITA FILTER BRUSH', 'productPool/1.jpg', 105 ),
( 'ARIX TONKITA FLOOR WIPER 44 CM', 'productPool/1.jpg', 195 ),
( 'ARIX TONKITA FLOOR WIPER 55CM', 'productPool/1.jpg', 56 ),
( 'ARIX TONKITA INDOOR BROOM TK004', 'productPool/1.jpg', 251 ),
( 'ARIX TONKITA MOP STRIPS', 'productPool/1.jpg', 210 ),
( 'ARIX TONKITA NON WOVEN MOP', 'productPool/1.jpg', 258 ),
( 'ARIX TONKITA OUT DOOR BROOM TK010', 'productPool/1.jpg', 136 ),
( 'ARIX TONKITA PIPON ECO FIBRE', 'productPool/1.jpg', 136 ),
( 'ARIX TONKITA PLASTIC PEGS 20PC', 'productPool/1.jpg', 253 ),
( 'ARIX TONKITA PUSH BROOM', 'productPool/1.jpg', 251 ),
( 'ARIX TONKITA TOILET BRUSH', 'productPool/1.jpg', 194 ),
( 'ARIX TONKITA UNIVERSALE BROOM TK620', 'productPool/1.jpg', 248 ),
( 'ARIX TONKITA WC BRUSH', 'productPool/1.jpg', 166 ),
( 'ARIX TONKITA WIPER', 'productPool/1.jpg', 196 ),
( 'ARIX TONKITA WOODEN PEGS 12PC', 'productPool/1.jpg', 242 ),
( 'ARIX WIPER WITH SPONGE', 'productPool/1.jpg', 71 ),
( 'AROGYA HEALTH MIX 1KG', 'productPool/1.jpg', 101 ),
( 'ARROWROOT POWDER 100GM', 'productPool/1.jpg', 164 ),
( 'ARROWROOT POWDER 50GM', 'productPool/1.jpg', 268 ),
( 'ARTISTO BUBLEE BANK', 'productPool/1.jpg', 86 ),
( 'ARVEE ACHU PEDA', 'productPool/1.jpg', 205 ),
( 'ARVEE AMERICAN CHOCO CHIPS COOKIES', 'productPool/1.jpg', 201 ),
( 'ARVEE APPLE PEDA', 'productPool/1.jpg', 70 ),
( 'ARVEE BANANA BISCUIT 12 NOS', 'productPool/1.jpg', 104 ),
( 'ARVEE BANANA CAKE 500gms', 'productPool/1.jpg', 208 ),
( 'ARVEE BANANA CHIPS 200G', 'productPool/1.jpg', 86 ),
( 'ARVEE BANANA CHIPS 500G', 'productPool/1.jpg', 266 ),
( 'ARVEE BANANA FRY', 'productPool/1.jpg', 225 ),
( 'ARVEE BANANA PUFFS', 'productPool/1.jpg', 229 ),
( 'ARVEE BEANS BISCUIT', 'productPool/1.jpg', 214 ),
( 'ARVEE BLACK FOREST 500 GMS', 'productPool/1.jpg', 58 ),
( 'ARVEE BLACK FOREST CAKE', 'productPool/1.jpg', 125 ),
( 'ARVEE BLUE BERRY CAKE 500 GMS', 'productPool/1.jpg', 82 ),
( 'ARVEE BLUEBERRY CAKE', 'productPool/1.jpg', 196 ),
( 'ARVEE BURGER', 'productPool/1.jpg', 235 ),
( 'ARVEE BUTTER CREAM CAKE 150GM', 'productPool/1.jpg', 74 ),
( 'ARVEE BUTTER LOAF BREAD 400G', 'productPool/1.jpg', 155 ),
( 'ARVEE BUTTERSCOTCH CAKE', 'productPool/1.jpg', 41 ),
( 'ARVEE CAPPUCINO CAKE', 'productPool/1.jpg', 33 ),
( 'ARVEE CARROT CAKE 500 GMS', 'productPool/1.jpg', 240 ),
( 'ARVEE CARROT HALWA', 'productPool/1.jpg', 176 ),
( 'ARVEE CHAKKAVARATTY', 'productPool/1.jpg', 113 ),
( 'ARVEE CHEMBA APPAM IDIYAPPAM PODI 1KG', 'productPool/1.jpg', 260 ),
( 'ARVEE CHICKEN BREAD ROLL', 'productPool/1.jpg', 242 ),
( 'ARVEE CHICKEN BURGER', 'productPool/1.jpg', 135 ),
( 'ARVEE CHICKEN PUFFS', 'productPool/1.jpg', 136 ),
( 'ARVEE CHICKEN ROLL', 'productPool/1.jpg', 123 ),
( 'ARVEE CHILLI POWDER 200G', 'productPool/1.jpg', 269 ),
( 'ARVEE CHILLI POWDER 500G', 'productPool/1.jpg', 2 ),
( 'ARVEE CHILLY PUFFS 200G', 'productPool/1.jpg', 234 ),
( 'ARVEE CHOCLATE CAKE 200 GMS', 'productPool/1.jpg', 210 ),
( 'ARVEE CHOCLATE PLUM CAKE 800GM', 'productPool/1.jpg', 197 ),
( 'ARVEE CHOCO ALMOND CAKE', 'productPool/1.jpg', 53 ),
( 'ARVEE CHOCO CHIPS CAKE', 'productPool/1.jpg', 146 ),
( 'ARVEE CHOCO FOREST CAKE', 'productPool/1.jpg', 112 ),
( 'ARVEE CHOCO VANILA CAKE', 'productPool/1.jpg', 55 ),
( 'ARVEE CHOCOLATE CAKE', 'productPool/1.jpg', 114 ),
( 'ARVEE CHOCOLATE PEDA', 'productPool/1.jpg', 60 ),
( 'ARVEE CHOCOLATE TRUFFLE CAKE', 'productPool/1.jpg', 31 ),
( 'ARVEE CHOCOLATE TRUFFLE CAKE 500 GMS', 'productPool/1.jpg', 96 ),
( 'ARVEE CITY KAPPA STICK 175 GMS', 'productPool/1.jpg', 276 ),
( 'ARVEE COCONUT OATS COOKIES', 'productPool/1.jpg', 97 ),
( 'ARVEE COCONUT OIL 1L', 'productPool/1.jpg', 43 ),
( 'ARVEE CREAM BUN', 'productPool/1.jpg', 94 ),
( 'ARVEE CRUNCH RING 100GM', 'productPool/1.jpg', 217 ),
( 'ARVEE CRUNCHY CHOCOLATE CAKE', 'productPool/1.jpg', 201 ),
( 'ARVEE CRUNCHY RING 100GM', 'productPool/1.jpg', 205 ),
( 'ARVEE CRUNCHY SNACKS', 'productPool/1.jpg', 66 ),
( 'ARVEE CUT CAKE 200G', 'productPool/1.jpg', 130 ),
( 'ARVEE DOUBLE TRUFFLE CAKE', 'productPool/1.jpg', 61 ),
( 'ARVEE EGG PUFFS', 'productPool/1.jpg', 273 ),
( 'ARVEE EGGLESS CHO CAKE 250GM', 'productPool/1.jpg', 161 ),
( 'ARVEE EGGLESS CHO CAKE 450', 'productPool/1.jpg', 156 ),
( 'ARVEE ELLU BISCUIT', 'productPool/1.jpg', 233 ),
( 'ARVEE FERRARO ROCHER CAKE', 'productPool/1.jpg', 114 ),
( 'ARVEE FIG AND HONEY CAKE 450G', 'productPool/1.jpg', 2 ),
( 'ARVEE FISH BUN', 'productPool/1.jpg', 242 ),
( 'ARVEE FRESH BUTTERSCOTCH CAKE', 'productPool/1.jpg', 220 ),
( 'ARVEE FRESH CREAM CHOCOLATE CAKE', 'productPool/1.jpg', 139 ),
( 'ARVEE FRESH CREAM DESIGN CAKE', 'productPool/1.jpg', 8 ),
( 'ARVEE FRESH STRAWBERRY CAKE', 'productPool/1.jpg', 87 ),
( 'ARVEE FRESH VANILA CAKE', 'productPool/1.jpg', 87 ),
( 'ARVEE FRUIT SALAD', 'productPool/1.jpg', 106 ),
( 'ARVEE FRUITS HALWA', 'productPool/1.jpg', 135 ),
( 'ARVEE GAJUR LADDU', 'productPool/1.jpg', 127 ),
( 'ARVEE GHEE APPAM', 'productPool/1.jpg', 72 ),
( 'ARVEE GHEE CAKE 320G', 'productPool/1.jpg', 247 ),
( 'ARVEE Ghee Mysorepakk', 'productPool/1.jpg', 219 ),
( 'ARVEE GHEE MYSOREPAV', 'productPool/1.jpg', 208 ),
( 'ARVEE GIFT PACK', 'productPool/1.jpg', 77 ),
( 'ARVEE HAZLENUT CAKE', 'productPool/1.jpg', 277 ),
( 'ARVEE HONEY ALMOND CAKE', 'productPool/1.jpg', 242 ),
( 'ARVEE HONEY ALMOND CAKE 800G', 'productPool/1.jpg', 217 ),
( 'ARVEE ICING CAKE', 'productPool/1.jpg', 266 ),
( 'ARVEE IRIS COFFEE CAKE 500 GMS', 'productPool/1.jpg', 260 ),
( 'ARVEE JAGGERY CAKE 150G', 'productPool/1.jpg', 115 ),
( 'ARVEE JAM PUFFS', 'productPool/1.jpg', 169 ),
( 'ARVEE KASHMIRI CHILLI POWDER 200G', 'productPool/1.jpg', 221 ),
( 'ARVEE KASHMIRI CHILLI POWDER 500G', 'productPool/1.jpg', 128 ),
( 'ARVEE KIWI CAKE', 'productPool/1.jpg', 85 ),
( 'ARVEE LADDU', 'productPool/1.jpg', 52 ),
( 'ARVEE MADAKKU', 'productPool/1.jpg', 48 ),
( 'ARVEE MANGO CAKE', 'productPool/1.jpg', 274 ),
( 'ARVEE MANGO PEDA', 'productPool/1.jpg', 117 ),
( 'ARVEE MASALA COOKIES', 'productPool/1.jpg', 255 ),
( 'ARVEE MASALA COOKIES 13NOS', 'productPool/1.jpg', 67 ),
( 'ARVEE MEAT CUTLET', 'productPool/1.jpg', 249 ),
( 'ARVEE MEAT PUFFS', 'productPool/1.jpg', 220 ),
( 'ARVEE MEAT ROLL', 'productPool/1.jpg', 33 ),
( 'ARVEE MILK BUN (5 NOS)', 'productPool/1.jpg', 168 ),
( 'ARVEE MILK HALWA 1 KG', 'productPool/1.jpg', 258 ),
( 'ARVEE MILK HALWA 500 GMS', 'productPool/1.jpg', 63 ),
( 'ARVEE MILK LADDU', 'productPool/1.jpg', 101 ),
( 'ARVEE MIRROR CAKE', 'productPool/1.jpg', 113 ),
( 'ARVEE MIXTURE 180GMS', 'productPool/1.jpg', 82 ),
( 'ARVEE MODERN CHOCOLATE CAKE', 'productPool/1.jpg', 241 ),
( 'ARVEE MODERN CUP CAKE', 'productPool/1.jpg', 163 ),
( 'ARVEE MOTHICHOR LADDU', 'productPool/1.jpg', 235 ),
( 'ARVEE MUFFINS', 'productPool/1.jpg', 233 ),
( 'ARVEE MULTIGRAIN BREAD', 'productPool/1.jpg', 257 ),
( 'ARVEE MYSOREAVU', 'productPool/1.jpg', 175 ),
( 'ARVEE NICE MIXTURE 500GMS', 'productPool/1.jpg', 208 ),
( 'ARVEE NUTS BISCUITS 180 GMS', 'productPool/1.jpg', 77 ),
( 'ARVEE NUTS HALWA 1 KG', 'productPool/1.jpg', 210 ),
( 'ARVEE OATS WHEAT PUTTU PODI MIX 1KG', 'productPool/1.jpg', 17 ),
( 'ARVEE PAKKAVADA 200G', 'productPool/1.jpg', 207 ),
( 'ARVEE PANEER PUFFS', 'productPool/1.jpg', 156 ),
( 'ARVEE PAPPADA BOLLY', 'productPool/1.jpg', 199 ),
( 'ARVEE PARRUPU VADA', 'productPool/1.jpg', 196 ),
( 'ARVEE PASSION FRUIT CAKE', 'productPool/1.jpg', 54 ),
( 'ARVEE PEANUT COOKIES', 'productPool/1.jpg', 87 ),
( 'ARVEE PEDA (KG)', 'productPool/1.jpg', 205 ),
( 'ARVEE PINEAPPLE CAKE', 'productPool/1.jpg', 57 ),
( 'ARVEE PINEAPPLE HALWA', 'productPool/1.jpg', 21 ),
( 'ARVEE PINEAPPLE HALWA 1 KG', 'productPool/1.jpg', 201 ),
( 'ARVEE PINEAPPLE PEDA', 'productPool/1.jpg', 31 ),
( 'ARVEE PINEAPPLE PUFFS', 'productPool/1.jpg', 208 ),
( 'ARVEE PISTA CAKE', 'productPool/1.jpg', 177 ),
( 'ARVEE PISTA HALWA', 'productPool/1.jpg', 91 ),
( 'ARVEE PISTA PEDA', 'productPool/1.jpg', 224 ),
( 'ARVEE PLUM & PUMPKIN CAKE 150G', 'productPool/1.jpg', 207 ),
( 'ARVEE PUNCHA PUTTU PODI 1KG', 'productPool/1.jpg', 204 ),
( 'ARVEE RAGI CHAPATHI MIX 1KG', 'productPool/1.jpg', 159 ),
( 'ARVEE RAGI OATS WHEAT CORN PUTTU PODI 1KG', 'productPool/1.jpg', 274 ),
( 'ARVEE RAGI WHEAT PUTTU MIX 1KG', 'productPool/1.jpg', 113 ),
( 'ARVEE RAINBOW CAKE', 'productPool/1.jpg', 88 ),
( 'ARVEE RAINBOW CAKE 500 GMS', 'productPool/1.jpg', 41 ),
( 'ARVEE RAINBOW CAKE PIECE', 'productPool/1.jpg', 235 ),
( 'ARVEE RED BEE CAKE', 'productPool/1.jpg', 145 ),
( 'ARVEE RED HALWA', 'productPool/1.jpg', 275 ),
( 'ARVEE RED VELVET CAKE', 'productPool/1.jpg', 28 ),
( 'ARVEE RED VELVET CAKE PIECE', 'productPool/1.jpg', 114 ),
( 'ARVEE REDVELVET CAKE 500 GMS', 'productPool/1.jpg', 3 ),
( 'ARVEE RICE BALL', 'productPool/1.jpg', 137 ),
( 'ARVEE RICE HALWA 1 KG', 'productPool/1.jpg', 20 ),
( 'ARVEE RICE HALWA 500GMS', 'productPool/1.jpg', 253 ),
( 'ARVEE RICH PLUM CAKE', 'productPool/1.jpg', 151 ),
( 'ARVEE ROASTED BREAD', 'productPool/1.jpg', 83 ),
( 'ARVEE ROASTED CHICKEN ROLL', 'productPool/1.jpg', 54 ),
( 'ARVEE ROASTED MEAT ROLL', 'productPool/1.jpg', 14 ),
( 'ARVEE ROASTED PEANUT 180GMS', 'productPool/1.jpg', 68 ),
( 'ARVEE ROASTED RAVA 1KG', 'productPool/1.jpg', 156 ),
( 'ARVEE ROASTED RICE FLOUR 1KG', 'productPool/1.jpg', 170 ),
( 'ARVEE ROASTED VEG ROLL', 'productPool/1.jpg', 144 ),
( 'ARVEE RUSK 200 GMS', 'productPool/1.jpg', 199 ),
( 'ARVEE SAMBA WHEAT PUTTU PODI 1KG', 'productPool/1.jpg', 51 ),
( 'ARVEE SAMOOSA PUNJABI', 'productPool/1.jpg', 119 ),
( 'ARVEE SANDWICH BREAD 440GMS', 'productPool/1.jpg', 4 ),
( 'ARVEE SPECIAL CHICKEN PUFFS', 'productPool/1.jpg', 84 ),
( 'ARVEE SPECIAL HALWA 1 KG', 'productPool/1.jpg', 90 ),
( 'ARVEE SPECIAL HALWA 500GMS', 'productPool/1.jpg', 23 ),
( 'ARVEE STRAWBERRY CAKE', 'productPool/1.jpg', 242 ),
( 'ARVEE Strawberry Cake 400 Gms', 'productPool/1.jpg', 14 ),
( 'ARVEE STRAWBERRY CAKE 800GM', 'productPool/1.jpg', 222 ),
( 'ARVEE STRAWBERRY PEDA', 'productPool/1.jpg', 113 ),
( 'ARVEE SUGAR FREE BUN', 'productPool/1.jpg', 145 ),
( 'ARVEE SUKHIYAN', 'productPool/1.jpg', 226 ),
( 'ARVEE SWEET PUFFS', 'productPool/1.jpg', 258 ),
( 'ARVEE SWEETNAN', 'productPool/1.jpg', 103 ),
( 'ARVEE TEA CAKE 800 GMS', 'productPool/1.jpg', 276 ),
( 'ARVEE TEA RUSK CONTAINER 170GMS', 'productPool/1.jpg', 245 ),
( 'ARVEE TISSUE 27*30CM', 'productPool/1.jpg', 37 ),
( 'ARVEE TISSUE PAPER 27*30', 'productPool/1.jpg', 129 ),
( 'ARVEE ULLI VADA', 'productPool/1.jpg', 63 ),
( 'ARVEE UNNIAPPAM 10 NOS PKT', 'productPool/1.jpg', 142 ),
( 'ARVEE UNNIYAPPAM', 'productPool/1.jpg', 90 ),
( 'ARVEE USMANIA SALT COOKIES', 'productPool/1.jpg', 260 );