INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'J.K. FOODS ACHAPPAM BIG', 'productPool/1.jpg', 146 ),
( 'J.K.FOODS ACHAPPAM SMALL', 'productPool/1.jpg', 53 ),
( 'JACKER POTATA CRISP VEGETABLE 160 GM', 'productPool/1.jpg', 254 ),
( 'JACKER POTATO CRISPS BARBECUE 75GM', 'productPool/1.jpg', 20 ),
( 'JACKER POTATO CRISPS BARBECUE160GM', 'productPool/1.jpg', 273 ),
( 'JACKER POTATO CRISPS CHEESE 160GM', 'productPool/1.jpg', 47 ),
( 'JACKER POTATO CRISPS HOT & SPICY 160GM', 'productPool/1.jpg', 111 ),
( 'JACKER POTATO CRISPS HOT&SPICY 75 GM', 'productPool/1.jpg', 21 ),
( 'JACKER POTATO CRISPS ORIGINAL 160GM', 'productPool/1.jpg', 126 ),
( 'JACKER POTATO CRISPS ORIGINAL 75GM', 'productPool/1.jpg', 96 ),
( 'JACKER POTATO CRISPS SOUR& ONION 75G', 'productPool/1.jpg', 67 ),
( 'JACKER POTATO CRISPS SOUR&ONION 160GM', 'productPool/1.jpg', 83 ),
( 'JACKER POTATO CRISPS TOMATO 160GM', 'productPool/1.jpg', 205 ),
( 'JAGGERY 500G', 'productPool/1.jpg', 148 ),
( 'JAI INTERNATIONAL LEMON SPLASH50G', 'productPool/1.jpg', 144 ),
( 'JAM BUN 2NOS', 'productPool/1.jpg', 174 ),
( 'JANAPRIYAN DATES &LEMON PICKLE 200G', 'productPool/1.jpg', 48 ),
( 'JANAPRIYAN DATES &LEMON PICKLE 400G', 'productPool/1.jpg', 277 ),
( 'JANAPRIYAN DATES PICKLE 200G', 'productPool/1.jpg', 272 ),
( 'JANAPRIYAN DATES PICKLE 400G', 'productPool/1.jpg', 279 ),
( 'JANAPRIYAN LEMON PICKLE 200G', 'productPool/1.jpg', 177 ),
( 'JANAPRIYAN LEMON PICKLE 80G', 'productPool/1.jpg', 160 ),
( 'JANAPRIYAN MANGO PICKLE 80G', 'productPool/1.jpg', 152 ),
( 'JANAPRIYAN MIXED VEGETABLES 80G', 'productPool/1.jpg', 74 ),
( 'JANAPRIYAN YAM PICKLE 200G', 'productPool/1.jpg', 172 ),
( 'JANAPRIYAN YAM PICKLE 400G', 'productPool/1.jpg', 227 ),
( 'JANATHA KNIFE 12PCS', 'productPool/1.jpg', 66 ),
( 'JAR 1000ML', 'productPool/1.jpg', 155 ),
( 'JAR 3 LTR', 'productPool/1.jpg', 254 ),
( 'JASMINE SOAP BOX', 'productPool/1.jpg', 229 ),
( 'JAYAMARI ABSORBENT COTTON WO0L 30G', 'productPool/1.jpg', 93 ),
( 'JEERAKAM 100G', 'productPool/1.jpg', 100 ),
( 'JEERAKAM CANDY 70G', 'productPool/1.jpg', 178 ),
( 'JEERAKAM TOYS CANDY 20G', 'productPool/1.jpg', 85 ),
( 'JEEVA NATURALS MILK PROTEIN SOAP 75GM', 'productPool/1.jpg', 23 ),
( 'JEEVAMRUTHAM DAHASAMANI', 'productPool/1.jpg', 116 ),
( 'JEEVUS CHUKKU KARUPPOTTI 200G', 'productPool/1.jpg', 195 ),
( 'JEEVUS GINGER COFFEE 150G BOTTLE', 'productPool/1.jpg', 217 ),
( 'JEEVUS KUNTHIRIKAM THIRI 15N', 'productPool/1.jpg', 22 ),
( 'JEEVUS KUNTHIRIKAM THIRI 8N', 'productPool/1.jpg', 270 ),
( 'JEEVUS PALM GUR 500G KARUPPATTY', 'productPool/1.jpg', 179 ),
( 'JEEVUS PALMGUR 500G', 'productPool/1.jpg', 189 ),
( 'JELIMALA FROOTSZ 869G', 'productPool/1.jpg', 207 ),
( 'JELLO MELLOW MARSHMALLOWS 120G', 'productPool/1.jpg', 246 ),
( 'JELLY CRYSTALS LEMON 85GM', 'productPool/1.jpg', 52 ),
( 'JELLY CRYSTALS PINEAPPLE', 'productPool/1.jpg', 63 ),
( 'JELLY CRYSTALS STRAWBERY FLAVOUR', 'productPool/1.jpg', 254 ),
( 'JELLY POPS IMP', 'productPool/1.jpg', 157 ),
( 'JELLY STICK', 'productPool/1.jpg', 211 ),
( 'JENIFER CLOTH CLIP 12PC', 'productPool/1.jpg', 200 ),
( 'JERGENS 496ML', 'productPool/1.jpg', 29 ),
( 'JERGENS LOTION', 'productPool/1.jpg', 139 ),
( 'JERGENS LOTION 200ML', 'productPool/1.jpg', 272 ),
( 'JERGENS LOTION 600ML IMP', 'productPool/1.jpg', 135 ),
( 'JERGENS LOTION IMP', 'productPool/1.jpg', 158 ),
( 'JERGENS LOTION IMP 200ML', 'productPool/1.jpg', 278 ),
( 'JERGENS SOAP IMP', 'productPool/1.jpg', 268 ),
( 'JESSORE COMB', 'productPool/1.jpg', 122 ),
( 'JESSORE COMB RS 18', 'productPool/1.jpg', 64 ),
( 'JESSORE COMB RS 25', 'productPool/1.jpg', 78 ),
( 'JESSORE COMB RS17', 'productPool/1.jpg', 123 ),
( 'JESSORE LICE COMB RS 12.50', 'productPool/1.jpg', 267 ),
( 'JESSORE LICE COMB RS 13.50', 'productPool/1.jpg', 17 ),
( 'JESSORE LICE COMB RS 24', 'productPool/1.jpg', 166 ),
( 'JESSORE LICE COMB RS 9.50', 'productPool/1.jpg', 183 ),
( 'JESSORE LICE COMB RS12', 'productPool/1.jpg', 102 ),
( 'JESSORE LICE COMB RS16.50', 'productPool/1.jpg', 69 ),
( 'JESSORE LICE COMB RS19.50', 'productPool/1.jpg', 139 ),
( 'JETTER METALIX BLUE', 'productPool/1.jpg', 82 ),
( 'JETTER YOUTH', 'productPool/1.jpg', 143 ),
( 'JINJIALI KITCHEN SCISSORS', 'productPool/1.jpg', 118 ),
( 'JINNI BALLONS PACKET MRP25', 'productPool/1.jpg', 248 ),
( 'JL MORISON BPA FREE FEEDER 150ML', 'productPool/1.jpg', 70 ),
( 'JL POWER PUFF 70', 'productPool/1.jpg', 214 ),
( 'JO EYELINER6.5ML', 'productPool/1.jpg', 220 ),
( 'JOBHA ALOEVERA NEEM SOAP 125G', 'productPool/1.jpg', 132 ),
( 'JOBHA BASIL & PARSLEY OIL CONTROL SOAP 125G', 'productPool/1.jpg', 231 ),
( 'JOBHA GOAT MILK SOAP BUTTER ALMOND 125G', 'productPool/1.jpg', 28 ),
( 'JOBHA GOAT MILK SOAP BUTTER ALMOND 375G', 'productPool/1.jpg', 203 ),
( 'JOBHA GOAT MILK SOAP JOJOBA OLIVE 125G', 'productPool/1.jpg', 252 ),
( 'JOBHA LICORICE ANTI ACNE SOAP 125G', 'productPool/1.jpg', 210 ),
( 'JOBHA LICORICE MOISTURIZE SOAP 125G', 'productPool/1.jpg', 149 ),
( 'JOE POPCORN CHEESE CARAMEL 60G', 'productPool/1.jpg', 176 ),
( 'JOE POPCORN CHILLI TOMATO 60G', 'productPool/1.jpg', 268 ),
( 'JOE POPCORN PERI PERI CARAMEL 60G', 'productPool/1.jpg', 272 ),
( 'JOHNSON ACTIVE CLEAN LAUNDRY DETERGENT 1LTR', 'productPool/1.jpg', 211 ),
( 'JOHNSON ACTIVE CLEAN LAUNDRY DETERGENT 500ML', 'productPool/1.jpg', 230 ),
( 'JOHNSON ACTIVE KIDS CLEAN &FRESH SHAMPOO 200ML', 'productPool/1.jpg', 119 ),
( 'JOHNSON BABY BLOSSOM POWDER 100G', 'productPool/1.jpg', 117 ),
( 'JOHNSON BABY BLOSSOM POWDER 200G', 'productPool/1.jpg', 71 ),
( 'JOHNSON BABY CARE COLLECTION', 'productPool/1.jpg', 105 ),
( 'JOHNSON BABY CREAM 30G', 'productPool/1.jpg', 248 ),
( 'JOHNSON BABY CREAM ILD 50G', 'productPool/1.jpg', 277 ),
( 'JOHNSON BABY CREAM NEW FORMULA100G', 'productPool/1.jpg', 177 ),
( 'JOHNSON BABY LOTION 100ML', 'productPool/1.jpg', 33 ),
( 'JOHNSON BABY LOTION 200ML', 'productPool/1.jpg', 272 ),
( 'JOHNSON BABY LOTION 50ML', 'productPool/1.jpg', 96 ),
( 'JOHNSON BABY MILK CREAM 100G', 'productPool/1.jpg', 156 ),
( 'JOHNSON BABY MILK CREAM 50G', 'productPool/1.jpg', 217 ),
( 'JOHNSON BABY MILK LOTION 100ML', 'productPool/1.jpg', 127 ),
( 'JOHNSON BABY MILK LOTION 200ML', 'productPool/1.jpg', 37 ),
( 'JOHNSON BABY MILK LOTION 50ML', 'productPool/1.jpg', 236 ),
( 'JOHNSON BABY MILK SOAP 75', 'productPool/1.jpg', 214 ),
( 'JOHNSON BABY OIL 100ML WITH VITAMIN E', 'productPool/1.jpg', 114 ),
( 'JOHNSON BABY OIL 200ML', 'productPool/1.jpg', 272 ),
( 'JOHNSON BABY OIL 50ML', 'productPool/1.jpg', 148 ),
( 'JOHNSON BABY OIL WITH VITAMINE E 500ML', 'productPool/1.jpg', 123 ),
( 'JOHNSON BABY POWDER 100G', 'productPool/1.jpg', 151 ),
( 'JOHNSON BABY POWDER 200G', 'productPool/1.jpg', 27 ),
( 'JOHNSON BABY POWDER 50G', 'productPool/1.jpg', 154 ),
( 'JOHNSON BABY POWDER 700G', 'productPool/1.jpg', 145 ),
( 'JOHNSON BABY SHAPOO 100 ML', 'productPool/1.jpg', 152 ),
( 'JOHNSON BABY SHAPOO 200 ML', 'productPool/1.jpg', 186 ),
( 'JOHNSON BABY SKIN WIPES 10', 'productPool/1.jpg', 238 ),
( 'JOHNSON BABY SKINCARE WIPES 20', 'productPool/1.jpg', 269 ),
( 'JOHNSON BABY SOAP 100G', 'productPool/1.jpg', 170 ),
( 'JOHNSON BABY TALCUM POWDER 400G', 'productPool/1.jpg', 166 ),
( 'JOHNSON BABY TOE -TO-TOE WASH 50ML', 'productPool/1.jpg', 84 ),
( 'JOHNSON BABY TOOTH BRUSH', 'productPool/1.jpg', 59 ),
( 'JOHNSON BABY WIPES 80N', 'productPool/1.jpg', 263 ),
( 'JOHNSON BUDS 60S', 'productPool/1.jpg', 49 ),
( 'JOHNSON GENTLE CLEAN LAUNDRY DETERGENT 1LTR', 'productPool/1.jpg', 115 ),
( 'JOHNSON GENTLE CLEAN LAUNDRY DETERGENT 500ML', 'productPool/1.jpg', 48 ),
( 'JOHNSON GLADE GEL FLORAL PERFECTION 70G', 'productPool/1.jpg', 96 ),
( 'JOHNSON GLADE GEL JASMINE 70G', 'productPool/1.jpg', 157 ),
( 'JOHNSON KIWI POLISHBLACKLEATHER 15G', 'productPool/1.jpg', 253 ),
( 'JOHNSONS ACTIVE KIDS CLEAN &FRESH SHAMPOO 100ML', 'productPool/1.jpg', 152 ),
( 'JOHNSONS ACTIVE KIDS SOFT & SMOOTH SHAMPOO 200ML', 'productPool/1.jpg', 22 ),
( 'JOHNSONS BABY AVACADO HAIR OIL', 'productPool/1.jpg', 160 ),
( 'JOHNSONS BABY HAIR OIL AVOCADO 200ML', 'productPool/1.jpg', 239 ),
( 'JOHNSONS BABY LOTION 100ML', 'productPool/1.jpg', 73 ),
( 'JOHNSONS BABY LOTION 200ML', 'productPool/1.jpg', 140 ),
( 'JOHNSONS BABY LOTION 50 ML', 'productPool/1.jpg', 170 ),
( 'JOHNSONS BABY MILK CREAM 30G', 'productPool/1.jpg', 246 ),
( 'JOHNSONS BABY MILK SOAP 75G', 'productPool/1.jpg', 261 ),
( 'JOHNSONS BABY OIL 100ML', 'productPool/1.jpg', 177 ),
( 'JOHNSONS BABY OIL 200ML', 'productPool/1.jpg', 11 ),
( 'JOHNSONS BABY OIL 50ML', 'productPool/1.jpg', 128 ),
( 'JOHNSONS BABY POWDER 400G', 'productPool/1.jpg', 99 ),
( 'JOHNSONS BABY POWDER BLOSSOMS 100G', 'productPool/1.jpg', 140 ),
( 'JOHNSONS BABY SHAMPOO 50ML', 'productPool/1.jpg', 248 ),
( 'JOHNSONS BABY SKINCARE WIPES 80N', 'productPool/1.jpg', 164 ),
( 'JOHNSONS BABY SOAP 150G', 'productPool/1.jpg', 266 ),
( 'JOHNSONS BABY SOAP 75G', 'productPool/1.jpg', 155 ),
( 'JOHNSONS BABY SOAP BLOSSOMS 75G', 'productPool/1.jpg', 155 ),
( 'JOHNSONS BLOSSOM POWDER 200G', 'productPool/1.jpg', 261 ),
( 'JOHNSONS BUDS 15S', 'productPool/1.jpg', 279 ),
( 'JOHNSONS BUDS 75N', 'productPool/1.jpg', 65 ),
( 'JOHNSONS MILK LOTION 50ML', 'productPool/1.jpg', 174 ),
( 'JOHNSONS MILK SOAP 100G', 'productPool/1.jpg', 222 ),
( 'JOHNSONS MILK+RICE LOTION 100 ML', 'productPool/1.jpg', 258 ),
( 'JOHNSONS MILK+RICE LOTION 2OO ML', 'productPool/1.jpg', 258 ),
( 'JOHNSONS SHINY DROPS SHAMPOO 100ML', 'productPool/1.jpg', 182 ),
( 'JOLLY RANCHER LOLLIPOP', 'productPool/1.jpg', 96 ),
( 'JOLLY RANCHER LOLLIPOP GREEN APPLE 10.5G', 'productPool/1.jpg', 274 ),
( 'JOLLY RANCHER LOLLIPOP MANGO 10.5G', 'productPool/1.jpg', 108 ),
( 'JOLLY RANCHER LOLLIPOP STRAWBERRY 10.5G', 'productPool/1.jpg', 74 ),
( 'JOLLY RANCHER LOLLIPOP WATERMELON 10.5G', 'productPool/1.jpg', 149 ),
( 'JOLLY RANCHER LOLLIPOPS 100PC JAR', 'productPool/1.jpg', 3 ),
( 'JOLLY RANCHER LOLLIPOPS 525G', 'productPool/1.jpg', 207 ),
( 'JOLLY RANCHER LOLLIPOPS 9G', 'productPool/1.jpg', 196 ),
( 'JOLLY RANCHER LOLLIPOPS GREENAPPLE', 'productPool/1.jpg', 63 ),
( 'JOLLY RANCHER LOLLIPOPS WATERMELON', 'productPool/1.jpg', 61 ),
( 'JOLLY RANCHER PKT', 'productPool/1.jpg', 49 ),
( 'JORDAN RIVER DATES 908G', 'productPool/1.jpg', 17 ),
( 'JOVEES 24 CART GOLD FACI 545', 'productPool/1.jpg', 68 ),
( 'JOVEES 30+YOUTH FACE CREAM 100G', 'productPool/1.jpg', 37 ),
( 'JOVEES ALMOND LIP CARE 4G', 'productPool/1.jpg', 56 ),
( 'JOVEES ALOE VERA LOTION 100ML', 'productPool/1.jpg', 231 ),
( 'JOVEES ANTI AGEING MINI FACIAL KIT', 'productPool/1.jpg', 107 ),
( 'JOVEES ANTI BLEMISH FACE MASK120G', 'productPool/1.jpg', 92 ),
( 'JOVEES ANTI BLMISH PIGMENTATION CREAM 60G', 'productPool/1.jpg', 35 ),
( 'JOVEES ANTI DANDRUFF THYME &TEA TREE SHAMPOO 250ML', 'productPool/1.jpg', 218 ),
( 'JOVEES ANTI HAIR LOSS SHAMPOO 125ML', 'productPool/1.jpg', 113 ),
( 'JOVEES ANTI TANPACK WHEAT CARROT FACE PACK 100G', 'productPool/1.jpg', 177 ),
( 'JOVEES ANTT ANPAK 50G', 'productPool/1.jpg', 4 ),
( 'JOVEES APLEVERCO SHAM 250M', 'productPool/1.jpg', 145 ),
( 'JOVEES APRIC OALMO SCRUB 100G', 'productPool/1.jpg', 233 ),
( 'JOVEES APRICO AL MO SCRUB 220G', 'productPool/1.jpg', 56 ),
( 'JOVEES APRICOT FACE SCRUB 50G', 'productPool/1.jpg', 58 ),
( 'JOVEES APRICOT PEAL MASK 100G', 'productPool/1.jpg', 93 ),
( 'JOVEES ARGAN OIL HAIR SPA', 'productPool/1.jpg', 91 ),
( 'JOVEES AYUANTPIM CREAM 60G', 'productPool/1.jpg', 206 ),
( 'JOVEES AYUOIL SKIN LOTION 100ML', 'productPool/1.jpg', 191 ),
( 'JOVEES BODY MASSAGE OIL 110 ML', 'productPool/1.jpg', 160 ),
( 'JOVEES BODY WASH ROSE 300ML', 'productPool/1.jpg', 264 ),
( 'JOVEES CITRUS CLEAMIL 100ML', 'productPool/1.jpg', 93 ),
( 'JOVEES COCOA BUTTER HAND & BODY LOTION 400ML', 'productPool/1.jpg', 192 ),
( 'JOVEES COCOABUTEBOLO 200ML', 'productPool/1.jpg', 134 ),
( 'JOVEES COLD CREAM 60G', 'productPool/1.jpg', 240 ),
( 'JOVEES COLOUR LOCK SHAMPOO 125ML', 'productPool/1.jpg', 152 ),
( 'JOVEES DE TAN SCRUB 100G', 'productPool/1.jpg', 140 ),
( 'JOVEES DE-TAN FACE WASH 100ML', 'productPool/1.jpg', 66 ),
( 'JOVEES DE-TAN FACEWASH', 'productPool/1.jpg', 178 ),
( 'JOVEES DE-TAN SCRUB 50G', 'productPool/1.jpg', 161 ),
( 'JOVEES EYE CONTOUR CREAM20G', 'productPool/1.jpg', 270 ),
( 'JOVEES EYE LINER ZAFFRE BLUE 6.5ML', 'productPool/1.jpg', 240 ),
( 'JOVEES EYELINER EMERALD GREEN', 'productPool/1.jpg', 26 ),
( 'JOVEES FAIRNESS CREAM 60G', 'productPool/1.jpg', 223 ),
( 'JOVEES FAMAS WHE TG CREAM 50G', 'productPool/1.jpg', 225 ),
( 'JOVEES FOOT CREAM 60G', 'productPool/1.jpg', 30 ),
( 'JOVEES FOOT CREAM AND SCRUB 50G', 'productPool/1.jpg', 185 ),
( 'JOVEES FRUIT MINI FACIAL', 'productPool/1.jpg', 178 ),
( 'JOVEES GOLD EYE CONGE 20G', 'productPool/1.jpg', 189 ),
( 'JOVEES GOLD MASSGEGE 50G', 'productPool/1.jpg', 255 ),
( 'JOVEES GRAPE FACE WASH 50ML', 'productPool/1.jpg', 73 ),
( 'JOVEES GRAPE FACEWASH 120ML', 'productPool/1.jpg', 111 ),
( 'JOVEES HAIR CONDITI', 'productPool/1.jpg', 247 ),
( 'JOVEES HAIR CONDITIONER', 'productPool/1.jpg', 114 ),
( 'JOVEES HAIR HERBAL CONDITIONER 110ML', 'productPool/1.jpg', 21 ),
( 'JOVEES HAIR PACK 200G', 'productPool/1.jpg', 221 ),
( 'JOVEES HAIR REP SHAMPOO', 'productPool/1.jpg', 167 ),
( 'JOVEES HAIR REVITALISER', 'productPool/1.jpg', 205 ),
( 'JOVEES HAIRSERUMGR 50ML', 'productPool/1.jpg', 127 ),
( 'JOVEES HEABUT MOIST 50G', 'productPool/1.jpg', 216 ),
( 'JOVEES HENNGINAN SHAM 250M', 'productPool/1.jpg', 253 ),
( 'JOVEES HERBAL HENNA POUCH 75G', 'productPool/1.jpg', 63 ),
( 'JOVEES HERBAL SINDOOR 5ML', 'productPool/1.jpg', 71 ),
( 'JOVEES HERBME HAND 150G', 'productPool/1.jpg', 105 ),
( 'JOVEES HERBSINDOR 8ML', 'productPool/1.jpg', 222 ),
( 'JOVEES HIMACHERY BODY LOTION 200ML', 'productPool/1.jpg', 18 ),
( 'JOVEES HONEAPLSHAM 250ML', 'productPool/1.jpg', 166 ),
( 'JOVEES HONEY APPLE CONDITIONING SHAMPOO 125ML', 'productPool/1.jpg', 25 ),
( 'JOVEES HYDRA LIP CARE HONEY', 'productPool/1.jpg', 183 ),
( 'JOVEES HYDRA LIP CARE KIWI FRUIT', 'productPool/1.jpg', 202 ),
( 'JOVEES HYDRA LIP CARE PASSION FRUIT', 'productPool/1.jpg', 168 ),
( 'JOVEES HYDRA LIP CARE STRAWBERRY', 'productPool/1.jpg', 128 ),
( 'JOVEES INSTFAI LIQU GLOWP 120G', 'productPool/1.jpg', 35 ),
( 'JOVEES JOJO BA NEEM SCRUB 100G', 'productPool/1.jpg', 116 ),
( 'JOVEES JOJOBA NEEM', 'productPool/1.jpg', 219 ),
( 'JOVEES KAJAL HERBAL KOHL 3G', 'productPool/1.jpg', 148 ),
( 'JOVEES LAVENDER LIP BALM 5G', 'productPool/1.jpg', 107 ),
( 'JOVEES LEMOM LIP BALM 5G', 'productPool/1.jpg', 79 ),
( 'JOVEES MINI ANTI BLEMISH KIT', 'productPool/1.jpg', 21 ),
( 'JOVEES MINI FACIAL KIT', 'productPool/1.jpg', 96 ),
( 'JOVEES MOISAQUA BODY WASH 200ML', 'productPool/1.jpg', 59 ),
( 'JOVEES MOISTURISER 50G', 'productPool/1.jpg', 20 ),
( 'JOVEES NEEM FACE WASH 120ML', 'productPool/1.jpg', 73 ),
( 'JOVEES NEEM FACE WASH 50ML', 'productPool/1.jpg', 47 ),
( 'JOVEES PAPA & HON SCRUB 100G', 'productPool/1.jpg', 269 ),
( 'JOVEES PAPAYA FACE WASH120ML', 'productPool/1.jpg', 41 ),
( 'JOVEES PAPAYA FACEWASH 50ML', 'productPool/1.jpg', 248 ),
( 'JOVEES PAPAYA HONEY FACE SCRUB 50G', 'productPool/1.jpg', 59 ),
( 'JOVEES PEARL FACE PACK60G', 'productPool/1.jpg', 215 ),
( 'JOVEES PEARL FACE SCRUB 60G', 'productPool/1.jpg', 88 ),
( 'JOVEES PEARL WHITE FACE CREAM 60G', 'productPool/1.jpg', 80 ),
( 'JOVEES PEARLWHITKIT', 'productPool/1.jpg', 254 ),
( 'JOVEES PRODRY SAND W CREAM 50G', 'productPool/1.jpg', 14 ),
( 'JOVEES SIGNATURE KAJAL', 'productPool/1.jpg', 251 ),
( 'JOVEES SKIN TONER HONEY 100ML', 'productPool/1.jpg', 75 ),
( 'JOVEES SKITON CUCUMCLE 100ML', 'productPool/1.jpg', 229 ),
( 'JOVEES SKITON ROSE CLEN 200ML', 'productPool/1.jpg', 39 ),
( 'JOVEES STRAWBE FACE WASH 120ML', 'productPool/1.jpg', 171 ),
( 'JOVEES STRAWBERRY LIP BALM 5G', 'productPool/1.jpg', 136 ),
( 'JOVEES STRWBERY FACEWASH 50ML', 'productPool/1.jpg', 233 ),
( 'JOVEES SUN BLOCK ANJC 50G', 'productPool/1.jpg', 18 ),
( 'JOVEES SUN COVER NATP 100G', 'productPool/1.jpg', 200 ),
( 'JOVEES SUN COVER SPF 30 50G', 'productPool/1.jpg', 76 ),
( 'JOVEES SUN PROTECTIVE CREAM 60G', 'productPool/1.jpg', 54 ),
( 'JOVEES SUN SCREEN FAIRNESS LOTION 100ML', 'productPool/1.jpg', 192 ),
( 'JOVEES SUN SCREEN GEL 60G ALOEVERA', 'productPool/1.jpg', 166 ),
( 'JOVEES SUNBLOCKANJEE 100G', 'productPool/1.jpg', 247 ),
( 'JOVEES TAMARIND VOL.CONDITIONER125ML', 'productPool/1.jpg', 140 ),
( 'JOVEES TAMARIND VOL.CONDITIONER250ML', 'productPool/1.jpg', 215 ),
( 'JOVEES TEA ROSE LIP CARE 4G', 'productPool/1.jpg', 253 ),
( 'JOVEES TEA TREE OIL CO FACE WASH 120ML', 'productPool/1.jpg', 276 ),
( 'JOVEES TEA TREE OIL FACEWASH 50ML', 'productPool/1.jpg', 134 ),
( 'JOVEES THYME AD SHAMPOO 125ML', 'productPool/1.jpg', 187 ),
( 'JOVEES VEG OAT PEEL 100G', 'productPool/1.jpg', 36 ),
( 'JOVEES VOLUMINIZING SHAMPOO 125 ML', 'productPool/1.jpg', 224 ),
( 'JOVEES VOLUMINSHAM 250ML', 'productPool/1.jpg', 273 ),
( 'JOVEES WINTECHERRY LIP CARE 4G', 'productPool/1.jpg', 191 ),
( 'JOVEES YOUTHACFA CREAM 60G', 'productPool/1.jpg', 237 ),
( 'JOYCEE SOAP BOX FAMILY', 'productPool/1.jpg', 177 ),
( 'JOYMEE MASALA NOODLES 3.5G', 'productPool/1.jpg', 182 ),
( 'JOYMEE NOODLES MASALA 73G', 'productPool/1.jpg', 101 ),
( 'JPM POLAND FUDGE CHOCOLATE 700G', 'productPool/1.jpg', 5 ),
( 'JPM POLAND FUDGE COCONUT 700G', 'productPool/1.jpg', 34 ),
( 'JPM POLAND FUDGE CREAM 700G', 'productPool/1.jpg', 57 ),
( 'JPM POLAND FUDGE SESAME 700G', 'productPool/1.jpg', 153 ),
( 'JUIZY MILK CHOCOLATE', 'productPool/1.jpg', 192 ),
( 'JUJU CONE JELLY', 'productPool/1.jpg', 161 ),
( 'JUMBO DATES 200G', 'productPool/1.jpg', 192 ),
( 'JUNAMI APPLE', 'productPool/1.jpg', 270 ),
( 'JUNIOR BADAM LEHYAM 400GM', 'productPool/1.jpg', 275 ),
( 'JUNIOR HORLICKS CHOCO STAGE 2 500 G GP', 'productPool/1.jpg', 84 ),
( 'JUNIR HORLICKS STAG 1200G', 'productPool/1.jpg', 19 ),
( 'JUPITER CEILING BROOM', 'productPool/1.jpg', 96 ),
( 'JYOTHI JAR 1250ML', 'productPool/1.jpg', 85 ),
( 'JYOTHI TAPE', 'productPool/1.jpg', 20 ),
( 'JYOTI PEARL HEAD PIN', 'productPool/1.jpg', 80 ),
( 'JYOTI SCISSORS', 'productPool/1.jpg', 253 ),
( 'JYOTI SWEEING NEEDLE', 'productPool/1.jpg', 2 ),
( 'JYOTI TAPE 20MM', 'productPool/1.jpg', 232 ),
( 'K P NAMBOODIRIS AEDA HANDWASH CLASSIC 200ML', 'productPool/1.jpg', 178 ),
( 'K P NAMBOODIRIS AEDA HANDWASH NATURE 200ML', 'productPool/1.jpg', 226 ),
( 'K P NAMBOODIRIS AEDA MOISTURIZING FACEWASH 50ML', 'productPool/1.jpg', 58 ),
( 'K P NAMBOODIRIS AEDA NOURISHING BODYWASH 200ML', 'productPool/1.jpg', 263 ),
( 'K P NAMBOODIRIS AEDA PURIFYING FACEWASH 50ML', 'productPool/1.jpg', 7 ),
( 'K P NAMBOODIRIS HERBAL MOUTHWASH 60ML', 'productPool/1.jpg', 53 ),
( 'K.P NAMBOODIRIS DANTADHAVANACHOORNAM 15G', 'productPool/1.jpg', 89 ),
( 'K.P NAMBOODIRIS HAIR CARE SHAMPOO 220ML', 'productPool/1.jpg', 135 ),
( 'K.P NAMBOODIRIS MOUTH WASH 250ML', 'productPool/1.jpg', 175 ),
( 'K.P NAMBOODIRIS SCENTED VIBHOOTHI', 'productPool/1.jpg', 32 ),
( 'K.P NAMBOODIRIS TOOTHPASTE 150G', 'productPool/1.jpg', 272 ),
( 'K.P NAMBOODIRIS TOOTHPOWDER 40G', 'productPool/1.jpg', 17 ),
( 'K.P NAMBOOTH SALT TOOTH PASTE 100G', 'productPool/1.jpg', 30 ),
( 'K.P NAMBOOTHIRIS ANTI DANDRUFF SHAMPOO 100 ML', 'productPool/1.jpg', 272 ),
( 'K.P NAMBOOTHIRIS CHEMPARUTHI THALI 100ML', 'productPool/1.jpg', 240 ),
( 'K.P NAMBOOTHIRIS GEL TOOTH PASTE 150G', 'productPool/1.jpg', 53 ),
( 'K.P NAMBOOTHIRIS GEL TOOTH PASTE40G', 'productPool/1.jpg', 113 ),
( 'K.P NAMBOOTHIRIS HAIR SHAMPOO 100ML', 'productPool/1.jpg', 39 ),
( 'K.P NAMBOOTHIRIS PATHI MUGHAM 15G', 'productPool/1.jpg', 90 ),
( 'K.P NAMBOOTHIRIS TOOTH PASTE 100G', 'productPool/1.jpg', 3 ),
( 'K.P NAMBOOTHIRIS TOOTH PASTE 150G', 'productPool/1.jpg', 219 ),
( 'K.P NAMBOOTHIRIS TOOTH PASTE 50G', 'productPool/1.jpg', 131 ),
( 'K.P NAMBOOTHIRIS TOOTH PASTE SALT 50G', 'productPool/1.jpg', 275 ),
( 'K.P NAMBOOTHIRIS TOOTH POWDER 40G', 'productPool/1.jpg', 94 ),
( 'K.P NAMBOOTHIRIS TURMERIC 25 G', 'productPool/1.jpg', 87 ),
( 'K.P. NAMBOOTHIRIS CHOORNAM 80G STRONG', 'productPool/1.jpg', 176 ),
( 'K.P. NAMBOOTHIRIS SALT TOOTH PASTE 150G', 'productPool/1.jpg', 54 ),
( 'K.P.N AEDA GLYCERINE CLEAR & SOFT SOAP 75G', 'productPool/1.jpg', 170 ),
( 'K.P.N AEDA GREEN SOAP 75G', 'productPool/1.jpg', 7 ),
( 'K.P.NAMBOODIRIS GEL 80G', 'productPool/1.jpg', 200 ),
( 'KAACHIL', 'productPool/1.jpg', 185 ),
( 'KABULI ASAFOETIDA POWDER 100G', 'productPool/1.jpg', 198 ),
( 'KABULI ASAFOETIDA POWDER 50G', 'productPool/1.jpg', 203 ),
( 'KADALA FRIED 90G', 'productPool/1.jpg', 78 ),
( 'KADALA MAVU 250G', 'productPool/1.jpg', 117 ),
( 'KADALA PARIPPU 500G', 'productPool/1.jpg', 184 ),
( 'KADALA PARUPPU 500G', 'productPool/1.jpg', 155 ),
( 'KADALAMAVU PREMIUM 500G', 'productPool/1.jpg', 219 ),
( 'KADALAPORI 500G', 'productPool/1.jpg', 220 ),
( 'KADAMKULATHY BRAHMI RICH GRANULES 400G', 'productPool/1.jpg', 235 ),
( 'KADAMKULATHY ELADI LEHYAM 30G', 'productPool/1.jpg', 212 ),
( 'KADAMKULATHY KUMKUMA CHANDANADI OIL 10ML', 'productPool/1.jpg', 214 ),
( 'KADUKU 100G', 'productPool/1.jpg', 5 ),
( 'KADUKU 200 GM', 'productPool/1.jpg', 98 ),
( 'KADUKU PARIPPU 100G', 'productPool/1.jpg', 236 ),
( 'KAIRALI COCONUT POWDER 1KG', 'productPool/1.jpg', 190 ),
( 'KAIRALI WHITE BREAD 400G', 'productPool/1.jpg', 104 ),
( 'KAJAH MATCHES', 'productPool/1.jpg', 156 ),
( 'KAKKI SHARONI FRUIT', 'productPool/1.jpg', 83 ),
( 'KALANS NEELIBHRINGADI COCONUT OIL 100ML', 'productPool/1.jpg', 27 ),
( 'KALANS NEELIBHRINGADI COCONUT OIL 200ML', 'productPool/1.jpg', 275 ),
( 'KALANS NEELIBHRINGADI COCONUT OIL 450ML', 'productPool/1.jpg', 262 ),
( 'KALIBER BARREL BOTTLE 650ML', 'productPool/1.jpg', 260 ),
( 'KALIBER SS BOTTLE 555', 'productPool/1.jpg', 182 ),
( 'KALIBER STAINLESS STEEL SS-1111 BOTTLE 750ML', 'productPool/1.jpg', 230 ),
( 'KALIBER STAINLESS STEEL SS-333 BOTTLE 750ML', 'productPool/1.jpg', 196 ),
( 'KALIBER TWISTER 500ML', 'productPool/1.jpg', 23 ),
( 'KALKANDAM BIG 100G', 'productPool/1.jpg', 47 ),
( 'KALKANDAM BIG 1KG', 'productPool/1.jpg', 9 ),
( 'KALKANDAM CRYSTAL 100G', 'productPool/1.jpg', 172 ),
( 'KALKANDAM CRYSTAL 1KG', 'productPool/1.jpg', 51 ),
( 'KAMILA HAIR O MAX OIL 100 ML', 'productPool/1.jpg', 85 ),
( 'KANDAMKULATHY AJAMAMSA RASAYANAM 500G', 'productPool/1.jpg', 11 ),
( 'KANDAMKULATHY DAHASHAMANI 25G', 'productPool/1.jpg', 78 ),
( 'KANDAMKULATHY ELADI 20 PKT', 'productPool/1.jpg', 53 ),
( 'KANDAMKULATHY ELADI COUGH SYRUP 100ML', 'productPool/1.jpg', 168 ),
( 'KANDAMKULATHY ELADI COUGH SYRUP SUGARFREE 100ML', 'productPool/1.jpg', 244 ),
( 'KANDAMKULATHY ELADI GINGER 500GM', 'productPool/1.jpg', 208 ),
( 'KANDAMKULATHY ELADI GINGER TABLET', 'productPool/1.jpg', 153 ),
( 'KANDAMKULATHY ELADI LEHYAM 100G', 'productPool/1.jpg', 91 ),
( 'KANDAMKULATHY ELADI POUCH 10N', 'productPool/1.jpg', 58 ),
( 'KANDAMKULATHY ELADI TABLET 125ML JAR', 'productPool/1.jpg', 27 ),
( 'KANDAMKULATHY ELADI TABLET 200ML JAR', 'productPool/1.jpg', 121 ),
( 'KANDAMKULATHY KASTHURIMANJAL PODI 40G', 'productPool/1.jpg', 243 ),
( 'KANDAMKULATHY KUMKUMADHI LEPAM 15G', 'productPool/1.jpg', 150 ),
( 'KANDAMKULATHY MURIVENNA 100ML', 'productPool/1.jpg', 95 ),
( 'KANDAMKULATHY NEELIBHRINGADI KERAM 100ML', 'productPool/1.jpg', 125 ),
( 'KANDAMKULATHY PATHUMUKAM 10G', 'productPool/1.jpg', 260 ),
( 'KANDAMKULATHY RED SANDAL POWDER 40G', 'productPool/1.jpg', 19 ),
( 'KANDY KING CREAMY LACTO TOFFY 399G', 'productPool/1.jpg', 92 ),
( 'KANGARO 3TAPLES 23/10 -H 10MM', 'productPool/1.jpg', 202 ),
( 'KANGARO CRYSTAL CLEAR TAPE TD-18/Y', 'productPool/1.jpg', 19 ),
( 'KANGARO DP 500', 'productPool/1.jpg', 83 ),
( 'KANGARO HSR10 STAPLER ', 'productPool/1.jpg', 92 ),
( 'KANGARO MUNIX TD-18/Y TAPE', 'productPool/1.jpg', 203 ),
( 'KANGARO ONE HOLE PUNCH', 'productPool/1.jpg', 173 ),
( 'KANGARO PUNCH DP 280', 'productPool/1.jpg', 19 ),
( 'KANGARO PUNCH DP 540', 'productPool/1.jpg', 131 ),
( 'KANGARO PUNCH DP-600', 'productPool/1.jpg', 3 ),
( 'KANGARO PUNCH DP-700', 'productPool/1.jpg', 230 ),
( 'KANGARO PUNCH DP480', 'productPool/1.jpg', 29 ),
( 'KANGARO PUNCH DP52', 'productPool/1.jpg', 23 ),
( 'KANGARO PUNCH FP-20', 'productPool/1.jpg', 176 ),
( 'KANGARO REMOVER SR-100', 'productPool/1.jpg', 181 ),
( 'KANGARO STAPLER 10', 'productPool/1.jpg', 101 ),
( 'KANGARO STAPLER 999', 'productPool/1.jpg', 189 ),
( 'KANGARO STAPLER GOLD 10', 'productPool/1.jpg', 62 ),
( 'KANGARO STAPLER HP-10', 'productPool/1.jpg', 181 ),
( 'KANGARO STAPLER HP-45', 'productPool/1.jpg', 261 ),
( 'KANGARO STAPLER ICON', 'productPool/1.jpg', 199 ),
( 'KANGARO STAPLER M 10 Y2', 'productPool/1.jpg', 269 ),
( 'KANGARO STAPLER M10', 'productPool/1.jpg', 144 ),
( 'KANGARO STAPLER REMOVER SR-45', 'productPool/1.jpg', 58 ),
( 'KANGARO STAPLES 23/6', 'productPool/1.jpg', 158 ),
( 'KANGARO STAPLES 23/8H', 'productPool/1.jpg', 26 ),
( 'KANGARO STAPLES 24/6', 'productPool/1.jpg', 267 ),
( 'KANGAROO STAPLES NO10', 'productPool/1.jpg', 77 ),
( 'KANGARO STAPLER HD-10D STAR', 'productPool/1.jpg', 233 ),
( 'KANNAN DEVAN DUET 100G', 'productPool/1.jpg', 271 ),
( 'KANNAN DEVAN DUET 250G', 'productPool/1.jpg', 107 ),
( 'KANNAN DEVAN STRONG TEA 100G', 'productPool/1.jpg', 67 ),
( 'KANNANDEVAN STRONG 1KG', 'productPool/1.jpg', 17 ),
( 'KAPPA', 'productPool/1.jpg', 38 ),
( 'KAPPA 1kg', 'productPool/1.jpg', 18 ),
( 'KAPRIKA TRUFFLES 300G', 'productPool/1.jpg', 204 ),
( 'KAPRIKA TRUFFLES 450G', 'productPool/1.jpg', 72 ),
( 'KAPRIKA TRUFFLES 500G', 'productPool/1.jpg', 48 ),
( 'KARA COCONUT CREAM 400ML', 'productPool/1.jpg', 61 ),
( 'KARA COCONUT MILK 425ML', 'productPool/1.jpg', 169 ),
( 'KARA COCONUT MILK CLASSIC 425 ML', 'productPool/1.jpg', 161 ),
( 'KARA COCONUT WATER 250ML', 'productPool/1.jpg', 1 ),
( 'KARA COCOUNT MILK 200ML', 'productPool/1.jpg', 211 ),
( 'KARE IN ADULT DIAPER PANTS 10PCS', 'productPool/1.jpg', 150 ),
( 'KARE IN ADULT LARGE 10', 'productPool/1.jpg', 151 ),
( 'KARE IN ADULT UNDER PADS L 10PCS', 'productPool/1.jpg', 237 ),
( 'KAREIN ADULT DIAPERS M 10PCS', 'productPool/1.jpg', 179 ),
( 'KARIKKA', 'productPool/1.jpg', 246 ),
( 'KARIM JEERA 25G', 'productPool/1.jpg', 12 ),
( 'KARTHIKA CANDLES', 'productPool/1.jpg', 47 ),
( 'KARUPATTI WEIGHTED', 'productPool/1.jpg', 236 ),
( 'KARUVAPATTA 17G', 'productPool/1.jpg', 67 ),
( 'KARUVAPATTA 25G', 'productPool/1.jpg', 251 ),
( 'KAS NEELIBHRINGADI COCONUT OIL 200ML', 'productPool/1.jpg', 61 ),
( 'KASHAYA AYUR MIX SOAP 75G', 'productPool/1.jpg', 265 ),
( 'KASHIS NANNARI SYRUP 750ML', 'productPool/1.jpg', 163 ),
( 'KASHIS NELLIKAKANTHARI SYRUP 750ML', 'productPool/1.jpg', 55 ),
( 'KASHMIR CHILY500G', 'productPool/1.jpg', 183 ),
( 'KASHMIRI CHILLI POWDER 5KG', 'productPool/1.jpg', 230 ),
( 'KASKAS WHITE 50G', 'productPool/1.jpg', 187 ),
( 'KASKASA WHITE 25GM', 'productPool/1.jpg', 90 ),
( 'KASTHURI BLACK ELLUNDA 20PCS', 'productPool/1.jpg', 227 ),
( 'KASTHURI ELLU BAR', 'productPool/1.jpg', 188 ),
( 'KASTHURI ELLU MIX BAR', 'productPool/1.jpg', 103 ),
( 'KASTHURI GROUNDNUT ROUND DISK 25', 'productPool/1.jpg', 113 ),
( 'KASTHURI GROUNDNUT SWEET BIG', 'productPool/1.jpg', 23 ),
( 'KASTHURI GROUNDNUT SWEET SMALL 15', 'productPool/1.jpg', 70 ),
( 'KASTHURI MIXTURE UNDA 30', 'productPool/1.jpg', 201 ),
( 'KASTHURI MIXURE BAR', 'productPool/1.jpg', 55 ),
( 'KASTHURI WHITE ELLUNDA 20PCS', 'productPool/1.jpg', 89 ),
( 'KASTHURIS GROUNDNUT SWEET MEDIUM 40', 'productPool/1.jpg', 1 ),
( 'KASTURI GROUNDNUT BALL', 'productPool/1.jpg', 115 ),
( 'KATCHEN TREASURES PUTTU PODI 1KG', 'productPool/1.jpg', 224 ),
( 'KATHI RS 35', 'productPool/1.jpg', 108 ),
( 'KATHI RS 40', 'productPool/1.jpg', 164 ),
( 'KATHI RS 55', 'productPool/1.jpg', 164 ),
( 'KATHI RS 75', 'productPool/1.jpg', 120 ),
( 'KATHI RS45', 'productPool/1.jpg', 12 ),
( 'KATHIRIKKA', 'productPool/1.jpg', 120 ),
( 'KAVERI CREAM 30G', 'productPool/1.jpg', 149 ),
( 'KAYTRA HAIR OIL 100ML', 'productPool/1.jpg', 257 ),
( 'KAYTRA HAIR PACK 250G', 'productPool/1.jpg', 130 ),
( 'KAYTRA HAIR PACK 400G', 'productPool/1.jpg', 108 ),
( 'KAYTRA HAIR PACK 50G', 'productPool/1.jpg', 110 ),
( 'KAYTRA REVITALIZING HAIR CREAM 100G', 'productPool/1.jpg', 188 ),
( 'KAYTRA SHAMPOO FRIZZY HAIR 200ML', 'productPool/1.jpg', 240 ),
( 'KAYTRA SHAMPOO TREATED HAIR 200ML', 'productPool/1.jpg', 231 ),
( 'KDD HARVEST RICH GUAVA 1L', 'productPool/1.jpg', 69 ),
( 'KEDAR MOSQUITO SWATTER SA 9921C', 'productPool/1.jpg', 180 ),
( 'KEDAR MOSQUITO SWATTER SA 999C', 'productPool/1.jpg', 24 ),
( 'KEERTHI Chappathi', 'productPool/1.jpg', 188 ),
( 'KELLOGGS ALL BR WHEAT FLAKES 425G', 'productPool/1.jpg', 27 ),
( 'KELLOGGS CHOCO CRUNCHY BITES 390G', 'productPool/1.jpg', 220 ),
( 'KELLOGGS CHOCO DUET 125G', 'productPool/1.jpg', 273 ),
( 'KELLOGGS CHOCO DUET 26G', 'productPool/1.jpg', 119 ),
( 'KELLOGGS CHOCO FILLS VANILLA 35G', 'productPool/1.jpg', 168 ),
( 'KELLOGGS CHOCO MOONS & STARS 350G', 'productPool/1.jpg', 21 ),
( 'KELLOGGS CHOCOS 1.2KG MRP 435', 'productPool/1.jpg', 206 ),
( 'KELLOGGS CHOCOS 125G', 'productPool/1.jpg', 220 ),
( 'KELLOGGS CHOCOS 250G', 'productPool/1.jpg', 94 ),
( 'KELLOGGS CHOCOS 375G', 'productPool/1.jpg', 102 ),
( 'KELLOGGS CHOCOS 58G POUCH', 'productPool/1.jpg', 276 ),
( 'KELLOGGS CHOCOS 700G', 'productPool/1.jpg', 103 ),
( 'KELLOGGS CHOCOS FILLS 180G', 'productPool/1.jpg', 214 ),
( 'KELLOGGS CHOCOS FILLS 250G', 'productPool/1.jpg', 28 ),
( 'KELLOGGS CHOCOS FILLS 32G', 'productPool/1.jpg', 99 ),
( 'KELLOGGS CHOCOS FILLS VANILLA 180G', 'productPool/1.jpg', 65 ),
( 'KELLOGGS CHOCOS LADDOO 425G', 'productPool/1.jpg', 47 ),
( 'KELLOGGS CHOCOS MOCNS STARS 27G', 'productPool/1.jpg', 114 ),
( 'KELLOGGS CHOCOS SPIDER-MAN 300G', 'productPool/1.jpg', 202 ),
( 'KELLOGGS CHOCOSDUET 375G', 'productPool/1.jpg', 72 ),
( 'KELLOGGS CORN FLAKAES ALMOND &HONEY 300G', 'productPool/1.jpg', 9 ),
( 'KELLOGGS CORN FLAKE ORG250G', 'productPool/1.jpg', 253 ),
( 'KELLOGGS CORN FLAKES 30G', 'productPool/1.jpg', 218 ),
( 'KELLOGGS CORN FLAKES 875GM', 'productPool/1.jpg', 268 ),
( 'KELLOGGS CORN FLAKES ALMOND HONEY 30G', 'productPool/1.jpg', 226 ),
( 'KELLOGGS CORN FLAKES ORGINAL 70G POUCH', 'productPool/1.jpg', 160 ),
( 'KELLOGGS CORN HONEY 125G', 'productPool/1.jpg', 50 ),
( 'KELLOGGS CORN MUESLI FRUIT NUT 500G', 'productPool/1.jpg', 30 ),
( 'KELLOGGS CORNFLAKES 100G', 'productPool/1.jpg', 129 ),
( 'KELLOGGS CORNFLAKES 475G', 'productPool/1.jpg', 58 ),
( 'KELLOGGS CORNFLAKES BANANA 300G', 'productPool/1.jpg', 109 ),
( 'KELLOGGS CORNFLAKES HONEY 300G', 'productPool/1.jpg', 219 ),
( 'KELLOGGS CORNFLAKES MANGO 300G', 'productPool/1.jpg', 83 ),
( 'KELLOGGS CORNFLAKES STRAWBERRY 100G', 'productPool/1.jpg', 159 ),
( 'KELLOGGS CORN FLAKES STRAWBERRY 275G', 'productPool/1.jpg', 132 ),
( 'KELLOGGS GRANOLA ALMONDS AND CRANBERRIES 150G', 'productPool/1.jpg', 225 ),
( 'KELLOGGS GRANOLA ALMONDS AND CRANBERRIES 460G', 'productPool/1.jpg', 249 ),
( 'KELLOGGS HONEYLOOPS 300G', 'productPool/1.jpg', 109 ),
( 'KELLOGGS HONY LOOPS 125G', 'productPool/1.jpg', 83 ),
( 'KELLOGGS MOON & STAR 140G', 'productPool/1.jpg', 71 ),
( 'KELLOGGS MUESELI NUT DELI 550G', 'productPool/1.jpg', 208 ),
( 'KELLOGGS MUESLI FRU MAGI 550G', 'productPool/1.jpg', 220 ),
( 'KELLOGGS MUSELI NO ADDED SUGAR 500G', 'productPool/1.jpg', 8 ),
( 'KELLOGGS OATS 1KG', 'productPool/1.jpg', 231 ),
( 'KELLOGGS OATS 450G', 'productPool/1.jpg', 59 ),
( 'KELLOGGS OATS 500G', 'productPool/1.jpg', 275 ),
( 'KELLOGGS OATS 500G*2 FREE CONTAINER', 'productPool/1.jpg', 98 ),
( 'KELLOGGS OATS CHOCOS LOOPS', 'productPool/1.jpg', 179 ),
( 'KELLOGGS RAGI CHOCOS', 'productPool/1.jpg', 33 ),
( 'KELLOGGS RAGI CHOCOS 125G', 'productPool/1.jpg', 103 ),
( 'KELLOGGS RAGI CHOCOS 350 G', 'productPool/1.jpg', 235 ),
( 'KELLOGGS REAL KESAR PISTA BADAM 120G', 'productPool/1.jpg', 267 ),
( 'KELLOGGS REAL KESAR PISTA BADAM 280G', 'productPool/1.jpg', 108 ),
( 'KELLOGGS REAL ROSE BADAM 120G', 'productPool/1.jpg', 11 ),
( 'KELLOGGS REAL ROSE BADAM 280G', 'productPool/1.jpg', 133 ),
( 'KELLOGGS REAL THANDAI BADAM 120G', 'productPool/1.jpg', 100 ),
( 'KELLOGGS REAL THANDAI BADAM 280G', 'productPool/1.jpg', 106 ),
( 'KELLOGGS SPECIAL K 140G', 'productPool/1.jpg', 110 ),
( 'KELLOGGS SPECIAL K 290G', 'productPool/1.jpg', 141 ),
( 'KELLOGGS SPECIAL K 435G', 'productPool/1.jpg', 161 ),
( 'KELLOGGS SPECIAL K MULTIGRAIN 135G', 'productPool/1.jpg', 93 ),
( 'KELLOGGS SPECIAL K ORIGINAL 140G', 'productPool/1.jpg', 249 ),
( 'KELLOGGS SPECIAL PROTEIN FIBRE 445G', 'productPool/1.jpg', 123 ),
( 'KEO KARPIN 100ML', 'productPool/1.jpg', 278 ),
( 'KEO KARPIN 200ML', 'productPool/1.jpg', 255 ),
( 'KEO KARPIN HAIR OIL 300ML', 'productPool/1.jpg', 252 ),
( 'KERA COCONUT BOTTLE OIL 1LTR', 'productPool/1.jpg', 118 ),
( 'KERA COCONUT OIL 1 LTR', 'productPool/1.jpg', 34 ),
( 'KERA COCONUT OIL 500ML', 'productPool/1.jpg', 272 ),
( 'KERA COCONUT OIL 500ML BOTTLE', 'productPool/1.jpg', 209 ),
( 'KERA KAUMUDI COCONUT OIL 1000ML', 'productPool/1.jpg', 171 ),
( 'KERALA CANDLE 500G', 'productPool/1.jpg', 131 ),
( 'KERALA CANDLE RS 24', 'productPool/1.jpg', 49 ),
( 'KERALA CANDLE RS 30', 'productPool/1.jpg', 64 ),
( 'KERALA CANDLE RS36', 'productPool/1.jpg', 215 ),
( 'KERALA CANDLE SMALL MRP 60', 'productPool/1.jpg', 82 ),
( 'KERALA CANDLES RS 12', 'productPool/1.jpg', 105 ),
( 'KERALA CANDLES RS 18', 'productPool/1.jpg', 92 ),
( 'KERALA CANDLES RS 42', 'productPool/1.jpg', 132 ),
( 'KERALA CHICKEN FRY 100G', 'productPool/1.jpg', 65 ),
( 'KERALA CUP CANDLE', 'productPool/1.jpg', 34 ),
( 'KERALA EGG CURRY 100G', 'productPool/1.jpg', 248 ),
( 'KERALA FISH CURRY 100G', 'productPool/1.jpg', 6 ),
( 'KERALA SAMBAR 100G', 'productPool/1.jpg', 112 ),
( 'KERALA STAND CANDLES', 'productPool/1.jpg', 247 ),
( 'KERALA TORCH CANDLE MRP 60', 'productPool/1.jpg', 244 ),
( 'KERALA WHITE CANDLES', 'productPool/1.jpg', 38 ),
( 'KESARI SAFFRON POWDER 1G', 'productPool/1.jpg', 152 ),
( 'KESARI SAFFRON SUPREME 1G', 'productPool/1.jpg', 195 ),
( 'KESARI SAFFRON THREADS 0.5G', 'productPool/1.jpg', 31 ),
( 'KESARI SAFFRON THREADS 1G', 'productPool/1.jpg', 15 ),
( 'KESARI SAFFRON THREADS 250MG', 'productPool/1.jpg', 174 ),
( 'KESARI SAFFRON THREADS 50MG', 'productPool/1.jpg', 187 ),
( 'KEYA LEMONGRASS 15G', 'productPool/1.jpg', 157 ),
( 'KEYA ROSEMARY 17G', 'productPool/1.jpg', 5 ),
( 'KHYATI EXAM PAD S594', 'productPool/1.jpg', 104 ),
( 'KIAN CHOCOLATE 410G IMP', 'productPool/1.jpg', 89 ),
( 'KIAN CHOCOLATE 600G IMP', 'productPool/1.jpg', 99 ),
( 'KIKKOMAN SOY SAUCE 200ML', 'productPool/1.jpg', 35 ),
( 'KIMIA DATES 400G', 'productPool/1.jpg', 188 ),
( 'KIMS EGG NOODLES 1KG', 'productPool/1.jpg', 163 ),
( 'KIMS EGG NOODLES 900G', 'productPool/1.jpg', 77 ),
( 'KIMS VEG HAKA NODDLES 1KG', 'productPool/1.jpg', 241 ),
( 'KINDER JOY BOYS 20G', 'productPool/1.jpg', 216 ),
( 'KINDER JOY GIRLS', 'productPool/1.jpg', 121 ),
( 'KINDER JOY MRP 42', 'productPool/1.jpg', 25 ),
( 'KINDER SCHOKO BONS CRIPCY', 'productPool/1.jpg', 62 ),
( 'KINDER SCHOKO BONS CRISPY', 'productPool/1.jpg', 275 ),
( 'KINDER SCHOKO BONS CRISPY 5.8G', 'productPool/1.jpg', 154 ),
( 'KING BERNI DATES 500G', 'productPool/1.jpg', 128 ),
( 'KING FISHER WATER 1L', 'productPool/1.jpg', 68 ),
( 'KING PREMIUM FARD DATES 500G', 'productPool/1.jpg', 129 ),
( 'KINGFISHER SODA 1.5L', 'productPool/1.jpg', 150 ),
( 'KINGFISHER SODA 600ML', 'productPool/1.jpg', 231 ),
( 'KINLEY SODA 1.25 L', 'productPool/1.jpg', 167 ),
( 'KINLEY SODA 750ML', 'productPool/1.jpg', 132 ),
( 'KINLEY WATER 500ML', 'productPool/1.jpg', 178 ),
( 'KINO ORANGE', 'productPool/1.jpg', 64 ),
( 'KISMIS BLACK 100G', 'productPool/1.jpg', 46 ),
( 'KISMIS RED 100G', 'productPool/1.jpg', 68 ),
( 'KISMIS RED 200G', 'productPool/1.jpg', 273 ),
( 'KISMIS WHITE BOX', 'productPool/1.jpg', 18 ),
( 'KISS WALNUT 250G', 'productPool/1.jpg', 136 ),
( 'KISSAN BERRY BLAST 320GM', 'productPool/1.jpg', 49 ),
( 'KISSAN CHILLI TOMATO SAUCE 465G', 'productPool/1.jpg', 94 ),
( 'KISSAN CHILLY TOMATO SAUCE 200G', 'productPool/1.jpg', 10 ),
( 'KISSAN CHOTU TOMATO KET 90G', 'productPool/1.jpg', 214 ),
( 'KISSAN FRESH TOMATO 1K', 'productPool/1.jpg', 217 ),
( 'KISSAN FRESH TOMATO KETCHUP 200G', 'productPool/1.jpg', 224 ),
( 'KISSAN FRESH TOMATO KETCHUP 450G', 'productPool/1.jpg', 127 ),
( 'KISSAN GRAPES SQUASH 750ML', 'productPool/1.jpg', 147 ),
( 'KISSAN LIME JUICE CORDIAL 750ML', 'productPool/1.jpg', 153 ),
( 'KISSAN MANCHURIAN SAUCE 200G', 'productPool/1.jpg', 83 ),
( 'KISSAN MANGO JAM 188G', 'productPool/1.jpg', 203 ),
( 'KISSAN MANGO JAM 490G', 'productPool/1.jpg', 111 ),
( 'KISSAN MANGO SQUASH 750ML', 'productPool/1.jpg', 193 );