INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'LUVIT CARAMELICIOUS 20G', 'productPool/1.jpg', 161 ),
( 'LUVIT CHOCOLATE WITH FRUIT AND NUT 45G', 'productPool/1.jpg', 76 ),
( 'LUVIT CHOCOLATE WITH MILK CHOCOLATE 33G', 'productPool/1.jpg', 75 ),
( 'LUVIT CHOCOLATE WITH RICE CRISPIES 27G', 'productPool/1.jpg', 260 ),
( 'LUVIT CHOCOLATE WITH ROASTED ALMOND 45G', 'productPool/1.jpg', 91 ),
( 'LUVIT CHOCSMACKERS', 'productPool/1.jpg', 230 ),
( 'LUVIT CHOCSMACKERS LOLLIPOP 10G', 'productPool/1.jpg', 218 ),
( 'LUVIT CHOCWICH RS 10', 'productPool/1.jpg', 43 ),
( 'LUVIT CHOCWICH WHITE 10G', 'productPool/1.jpg', 279 ),
( 'LUVIT CRAZYSMACKERS', 'productPool/1.jpg', 204 ),
( 'LUVIT DAIRY RICH 6G MRP 5', 'productPool/1.jpg', 117 ),
( 'LUVIT DAIRY RICH FRUIT AND NUT 40G', 'productPool/1.jpg', 265 ),
( 'LUVIT DAIRY RICH MILK 13G MRP 10', 'productPool/1.jpg', 223 ),
( 'LUVIT DAIRY RICH MILK 30G MRP 20', 'productPool/1.jpg', 173 ),
( 'LUVIT DAIRY RICH ROASTED ALMOND 40G', 'productPool/1.jpg', 274 ),
( 'LUVIT LOCA CHOCOLATE 26G', 'productPool/1.jpg', 251 ),
( 'LUVIT LOLLIPOP BLUE LEMONADE 10G', 'productPool/1.jpg', 185 ),
( 'LUVIT LOLLIPOP CHOCOLATE VANILLA 10G', 'productPool/1.jpg', 117 ),
( 'LUVIT LUSCIOUS FRUIT AND NUT 27G', 'productPool/1.jpg', 132 ),
( 'LUVIT LUSCIOUS MILK CHOCOLATE 52G', 'productPool/1.jpg', 80 ),
( 'LUVLAP DOLPHIN SIPPER BLUE 160ML', 'productPool/1.jpg', 120 ),
( 'LUVLAP DOLPHIN SIPPER PNK 160ML', 'productPool/1.jpg', 187 ),
( 'LUVLAP HIPPO SPOUT CUP 225ML GREEN', 'productPool/1.jpg', 61 ),
( 'LUVLAP HIPPO SPOUT CUP 225ML ORANGE', 'productPool/1.jpg', 182 ),
( 'LUVLAP JUMBO SIPPER 240ML BLUE', 'productPool/1.jpg', 27 ),
( 'LUVLAP JUMBO SIPPER 240ML GREEN', 'productPool/1.jpg', 201 ),
( 'LUVLAP MOISTURISING WIPES ALOE VERA 72N', 'productPool/1.jpg', 15 ),
( 'LUVLAP MOISTURISING WIPES ALOE VERA MRP 115', 'productPool/1.jpg', 215 ),
( 'LUVLAP MOISTURISING WIPES JOJOBA OIL', 'productPool/1.jpg', 259 ),
( 'LUVLAP TURTLE SIPPER 360ML GREEN', 'productPool/1.jpg', 76 ),
( 'LUVLAP TURTLE SIPPER 360ML ORANGE', 'productPool/1.jpg', 129 ),
( 'LUVLT CHOCWICH 10G', 'productPool/1.jpg', 156 ),
( 'LUX CREAMY PERFECTION 75G', 'productPool/1.jpg', 18 ),
( 'LUX FRESH SOAP 3*100G', 'productPool/1.jpg', 242 ),
( 'LUX FRESH SPL SOAP 100GM', 'productPool/1.jpg', 211 ),
( 'LUX SANDAL &CREAM 100 GM', 'productPool/1.jpg', 208 ),
( 'LUX SOAP IMP', 'productPool/1.jpg', 165 ),
( 'LUX SOFT BODY WASH 100ML', 'productPool/1.jpg', 55 ),
( 'LUX SOFT TOUCH BATH SOAP 100G', 'productPool/1.jpg', 275 ),
( 'LUX SOFT TOUCH BATH SOAP 3*150G', 'productPool/1.jpg', 85 ),
( 'LUX SOFT TOUCH BODY WASH 240ML', 'productPool/1.jpg', 11 ),
( 'LUX SOFT TOUCH ROSE WATER SOAP 400G', 'productPool/1.jpg', 271 ),
( 'LUX SOFT TOUCH SOAP 100GM', 'productPool/1.jpg', 158 ),
( 'LUX SOFT TOUCH SOAP 150GM', 'productPool/1.jpg', 36 ),
( 'LUX SOFT TOUCH SOAP 3X100GM', 'productPool/1.jpg', 100 ),
( 'LUX VELVET BODYWASH 100ML', 'productPool/1.jpg', 72 ),
( 'LUX VELVET TOUCH 100GM', 'productPool/1.jpg', 71 ),
( 'LUX VELVET TOUCH BODY WASH 240ML', 'productPool/1.jpg', 153 ),
( 'LUX VELVET TOUCH SOAP 400G', 'productPool/1.jpg', 79 ),
( 'LUX VELVET TOUCH SOAP300G', 'productPool/1.jpg', 119 ),
( 'LUXAR PARKER BALL PEN VECTOR GOLD 1N', 'productPool/1.jpg', 50 ),
( 'LUXAR PARKER BETA PRTEAMIUM BALL PEN 1N', 'productPool/1.jpg', 132 ),
( 'LUXAR PARKER BETA STANDARD BALL PEN 1N', 'productPool/1.jpg', 129 ),
( 'LUXAR PARKER CLASSIC GOLD BALL PEN', 'productPool/1.jpg', 184 ),
( 'LUXAR PARKER CLASSIC MATTE BLACK BALL PEN', 'productPool/1.jpg', 7 ),
( 'LUXAR PARKER FOUNTAIN PEN STANDARD BETA 1N', 'productPool/1.jpg', 74 ),
( 'LUXAR PARKER FRONTIER STEEL BALL PEN', 'productPool/1.jpg', 43 ),
( 'LUXAR PARKER GALAXY STANDARAD BAAL PEN', 'productPool/1.jpg', 256 ),
( 'LUXAR PARKER GALAXY STANDARD BALL PEN', 'productPool/1.jpg', 217 ),
( 'LUXAR PARKER JOTTER STEEL BALL PEN 1N', 'productPool/1.jpg', 258 ),
( 'LUXAR PARKER MATTE BLACK VECTOR ROLLER PEN', 'productPool/1.jpg', 84 ),
( 'LUXAR PARKER METALLIX VECTOR SERIES ROLLER PEN 1N', 'productPool/1.jpg', 256 ),
( 'LUXAR PARKER PREMIUM BETA FOUNTAIN PEN 1N', 'productPool/1.jpg', 86 ),
( 'LUXAR PARKER PROFILE BALL PEN BLUE', 'productPool/1.jpg', 206 ),
( 'LUXAR PARKER ROLLER PEN PREMIUM BETA 1N', 'productPool/1.jpg', 138 ),
( 'LUXAR PARKER STANDARD BETA ROLLER BALL PEN 1N', 'productPool/1.jpg', 147 ),
( 'LUXAR PARKER STEEL VECTOR FOUNTAIN PEN 1N', 'productPool/1.jpg', 78 ),
( 'LUXAR PARKER STEEL VECTOR ROLLER BALL PEN 1N', 'productPool/1.jpg', 88 ),
( 'LUXAR PARKER V SIGMA BETA ROLLER PEN BB 1N', 'productPool/1.jpg', 204 ),
( 'LUXAR PARKER VECTOR BALL PEN CLASSIC STEEL 1N', 'productPool/1.jpg', 3 ),
( 'LUXAR PARKER VECTOR FOUNTAIN STANDARD BALL PEN 1N', 'productPool/1.jpg', 76 ),
( 'LUXAR PARKER VECTOR GOLD FOUNTAIN PEN', 'productPool/1.jpg', 176 ),
( 'LUXAR PARKER VECTOR MATTE BALL PEN BLACK', 'productPool/1.jpg', 278 ),
( 'LUXAR PARKER VECTOR MATTE BLACK FOUNTAIN PEN 1N', 'productPool/1.jpg', 137 ),
( 'LUXAR PARKER VECTOR ROLLER BALL PEN GOLD 1N', 'productPool/1.jpg', 26 ),
( 'LUXAR PARKER VECTOR STANDARD BALL PEN REFILL', 'productPool/1.jpg', 144 ),
( 'LUXAR PARKER VECTOR STANDARD FOUNTAIN PEN 1N', 'productPool/1.jpg', 54 ),
( 'LUXAR PARKER VECTOR STANDARD ROLLER BALL PEN', 'productPool/1.jpg', 251 ),
( 'LUXAR PARKER VECTOR STEEL BALL PEN 1N', 'productPool/1.jpg', 172 ),
( 'LUXAR PARKER VECTOR STEEL FOUNTAIN PEN', 'productPool/1.jpg', 155 ),
( 'LUXEAPERS BLACK OILVES PITTED 450G', 'productPool/1.jpg', 98 ),
( 'LUXEAPERS GREEN OLIVES SLICED 450G', 'productPool/1.jpg', 162 ),
( 'LUXOR CD MARKER BLACK', 'productPool/1.jpg', 75 ),
( 'LUXOR CD MARKER PEN 1237 NF', 'productPool/1.jpg', 242 ),
( 'LUXOR CORRECTION PEN 1450', 'productPool/1.jpg', 89 ),
( 'LUXOR FOCUS BALL PEN 1756', 'productPool/1.jpg', 144 ),
( 'LUXOR GELONE GEL PEN 1760', 'productPool/1.jpg', 165 ),
( 'LUXOR HIGHLIGHTER 5N MRP 100', 'productPool/1.jpg', 77 ),
( 'LUXOR HIGHLIGHTER YELLOW', 'productPool/1.jpg', 48 ),
( 'LUXOR PERFECTO INSTRUMENTS BOX', 'productPool/1.jpg', 241 ),
( 'LUXOR PERMANENT MARKER BLACK', 'productPool/1.jpg', 123 ),
( 'LUXOR PILOT 05 PEN 801 H', 'productPool/1.jpg', 94 ),
( 'LUXOR PILOT BP1 RT BALL PEN', 'productPool/1.jpg', 204 ),
( 'LUXOR PILOT V5 HITECPOINT PEN 811S', 'productPool/1.jpg', 240 ),
( 'LUXOR PILOT V7 HITECPOINT PEN 812S', 'productPool/1.jpg', 150 ),
( 'LUXOR POCKET SPIRAL BOOK', 'productPool/1.jpg', 268 ),
( 'LUXOR SKETCH 12 COLOURES', 'productPool/1.jpg', 46 ),
( 'LUXOR SKETCH O MATIC WATER COLOUR', 'productPool/1.jpg', 148 ),
( 'LUXOR STUDYMATE INSTRUMENTS BOX', 'productPool/1.jpg', 110 ),
( 'LUXOR SUBJECT 5 NOTEBOOK RULED 20406', 'productPool/1.jpg', 184 ),
( 'LUXOR SUBJECT 5 NOTEBOOK RULED 20409', 'productPool/1.jpg', 231 ),
( 'LUXOR SUBJECT 5 NOTEBOOK RULED 20413', 'productPool/1.jpg', 8 ),
( 'LUXOR SUBJECT1 NOTEBOOK RULED 20405', 'productPool/1.jpg', 181 ),
( 'LUXOR SUBJECT1 NOTEBOOK RULED 20408', 'productPool/1.jpg', 150 ),
( 'LUXOR SUPER CHISEL MARKER 999', 'productPool/1.jpg', 129 ),
( 'LUXOR UNIFLO BALL POINT PEN 1759', 'productPool/1.jpg', 163 ),
( 'LUXOR WHITE BOARD MARKER BLACK', 'productPool/1.jpg', 201 ),
( 'LUXOR WHITE BOARD MARKER RED', 'productPool/1.jpg', 189 ),
( 'LUXOR WHITEBOARD MARKER 1223', 'productPool/1.jpg', 162 ),
( 'LUXURY SOAP CASE', 'productPool/1.jpg', 185 ),
( 'LXP OLIVES PITTED', 'productPool/1.jpg', 141 ),
( 'LXP OLIVES STUFFED', 'productPool/1.jpg', 251 ),
( 'LYALLPUR DRY PETHA 300G', 'productPool/1.jpg', 4 ),
( 'M & M CHOCOLATE 45G', 'productPool/1.jpg', 64 ),
( 'M SEAL 100GM', 'productPool/1.jpg', 144 ),
( 'M SEAL 40G', 'productPool/1.jpg', 20 ),
( 'M&MS CHOCOLATE100G', 'productPool/1.jpg', 240 ),
( 'MAA MANGO DRINK 1200 ML', 'productPool/1.jpg', 62 ),
( 'MAAMEES BLACK ELLUNDA', 'productPool/1.jpg', 242 ),
( 'MAAMEES ELLUNDA WHITE', 'productPool/1.jpg', 200 ),
( 'MAAMEES RICE MURUK', 'productPool/1.jpg', 10 ),
( 'MAAVILA DANT CARE TOOTH PASTE 100G', 'productPool/1.jpg', 221 ),
( 'MAAZA DRINK 150ML', 'productPool/1.jpg', 196 ),
( 'MAAZA MANGO 250ML BOTTLE', 'productPool/1.jpg', 244 ),
( 'MAAZA MANGO 600ML', 'productPool/1.jpg', 131 ),
( 'MAAZA MANGO CAN 240ML', 'productPool/1.jpg', 220 ),
( 'MACAIN POTATO BITES 420G', 'productPool/1.jpg', 9 ),
( 'MACHINE BELT', 'productPool/1.jpg', 60 ),
( 'MACHINE BELT 600MM', 'productPool/1.jpg', 214 ),
( 'MACHINE NEEDLE', 'productPool/1.jpg', 51 ),
( 'MACKAYS BLACKCURRANT PRESERVE 340G', 'productPool/1.jpg', 225 ),
( 'MACKAYS BLUEBERRY PRESERVE 340G', 'productPool/1.jpg', 244 ),
( 'MACKAYS ORANG LEMON MARMALADE 340G', 'productPool/1.jpg', 277 ),
( 'MACKAYS RASBERRY PRESERVE 340G', 'productPool/1.jpg', 170 ),
( 'MACKAYS SCOTTISH STRAWBERRY PRESERVE 340G', 'productPool/1.jpg', 158 ),
( 'MACKAYS SCOTTISH THREE BERRY PRESERVE 340G', 'productPool/1.jpg', 153 ),
( 'MADAKKU BOLLY 5 NOS', 'productPool/1.jpg', 84 ),
( 'MADHURAKIZHANGU', 'productPool/1.jpg', 43 ),
( 'MADHURAM BANANA CHIPS 150G', 'productPool/1.jpg', 234 ),
( 'MADHURAM CHILLI LONG MURUKKU 150G', 'productPool/1.jpg', 157 ),
( 'MADHURAM FRID BISCUITS 150G', 'productPool/1.jpg', 26 ),
( 'MADHURAM GARLIC MURUKKU 20N', 'productPool/1.jpg', 196 ),
( 'MADHURAM GROUNDNUT 150G', 'productPool/1.jpg', 66 ),
( 'MADHURAM MADAKKU 150G', 'productPool/1.jpg', 209 ),
( 'MADHURAM POTATO CHIPS 90G', 'productPool/1.jpg', 105 ),
( 'MADHURAM RAGI MURUKKU20N', 'productPool/1.jpg', 164 ),
( 'MADHURAM RICE MURUKKU 10N', 'productPool/1.jpg', 165 ),
( 'MADHURAM RICE MURUKU 5', 'productPool/1.jpg', 185 ),
( 'MADHURAM SPRILL O SPRILL WHITE MURUKKU', 'productPool/1.jpg', 165 ),
( 'MADHURAM SPRILL-O-SPRILL CHILLI MURUKKU', 'productPool/1.jpg', 198 ),
( 'MADHURAM SPRILL-O-SPRILL MASALA MURUKKU', 'productPool/1.jpg', 238 ),
( 'MADHURAM SPRILL-O-SPRILL WHITE MURUKKU', 'productPool/1.jpg', 121 ),
( 'MADHURAM SWEET BANANA CHIPS', 'productPool/1.jpg', 40 ),
( 'MADHURAM SWEET BANANA CHIPS 150G', 'productPool/1.jpg', 14 ),
( 'MADHURAM SWEET MIXTURE 150G', 'productPool/1.jpg', 149 ),
( 'MADHURAM WHITE LONG MURUKKU 150G', 'productPool/1.jpg', 187 ),
( 'MAEPRANOM SWEET CHILLI SAUCE 390G', 'productPool/1.jpg', 166 ),
( 'MAGGI 2 MIN NOODLES OATS 292G', 'productPool/1.jpg', 176 ),
( 'MAGGI 2 MIN NOODLES VEG ATTA 320G', 'productPool/1.jpg', 235 ),
( 'MAGGI 2-MINUTE NOODLES 280G', 'productPool/1.jpg', 29 ),
( 'MAGGI 2-MINUTE NOODLES 420G RS 67', 'productPool/1.jpg', 244 ),
( 'MAGGI 2-MINUTE NOODLES MASALA 420G', 'productPool/1.jpg', 121 ),
( 'MAGGI 2MIN NOODLES 560G', 'productPool/1.jpg', 179 ),
( 'MAGGI 2MINUTE NOODLES 280G', 'productPool/1.jpg', 9 ),
( 'MAGGI ATTA MASALA NOODLES 75G', 'productPool/1.jpg', 251 ),
( 'MAGGI ATTA NOODLES 300G', 'productPool/1.jpg', 9 ),
( 'MAGGI CHICKEN CUPPA NOODLES 67G', 'productPool/1.jpg', 110 ),
( 'MAGGI CHICKEN NOODLES 142G', 'productPool/1.jpg', 116 ),
( 'MAGGI CHICKEN NOODLES 2*284G COMBI', 'productPool/1.jpg', 107 ),
( 'MAGGI CHICKEN NOODLES 280G 4 PACK', 'productPool/1.jpg', 176 ),
( 'MAGGI CHICKEN NOODLES 284G', 'productPool/1.jpg', 165 ),
( 'MAGGI CHICKEN STOCK 20GM', 'productPool/1.jpg', 28 ),
( 'MAGGI CHIKEN NOODLES 71G', 'productPool/1.jpg', 254 ),
( 'MAGGI CHILLY CHOW CUPPA NOODLES 70G', 'productPool/1.jpg', 246 ),
( 'MAGGI COCONUT MILK POWDER 1KG', 'productPool/1.jpg', 235 ),
( 'MAGGI COCONUT MILK POWDER 25GM', 'productPool/1.jpg', 46 ),
( 'MAGGI COCOUNT MILK POWDER 100GM', 'productPool/1.jpg', 35 ),
( 'MAGGI CUP SOUPS CORN WITH PEPPER15G', 'productPool/1.jpg', 183 ),
( 'MAGGI CUP SOUPS TOMATO MARGHERITA 15G', 'productPool/1.jpg', 130 ),
( 'MAGGI CUP SOUPS VEG CHILLI PEPPER 15G', 'productPool/1.jpg', 196 ),
( 'MAGGI CUP SOUPS WINTER VEG AND GINGER 15G', 'productPool/1.jpg', 110 ),
( 'MAGGI CUPPA CHICKEN NOODLES 67G', 'productPool/1.jpg', 277 ),
( 'MAGGI CUPPA CHILLI CHOW NOODLES 70G', 'productPool/1.jpg', 275 ),
( 'MAGGI CUPPA CHILLY CHOW 70G', 'productPool/1.jpg', 150 ),
( 'MAGGI CUPPA NOODLES CHILLY CHOW 70G', 'productPool/1.jpg', 215 ),
( 'MAGGI CUPPA NOODLES MASALA 70G', 'productPool/1.jpg', 128 ),
( 'MAGGI HOT & SWEET SAUCE 500ML', 'productPool/1.jpg', 210 ),
( 'MAGGI HOT & SWEET SAUCE DOY', 'productPool/1.jpg', 138 ),
( 'MAGGI HOT & SWEET TOMATO SAUCE 500G', 'productPool/1.jpg', 158 ),
( 'MAGGI HOT AND SWEET TOMATO CHILLY SAUCE 500G', 'productPool/1.jpg', 99 ),
( 'MAGGI HOT HEADS CHILLI CHICKEN NOODLES', 'productPool/1.jpg', 206 ),
( 'MAGGI HOT HEADS GREEN CHILLI 71G', 'productPool/1.jpg', 177 ),
( 'MAGGI HOT HEADS PEPPER NOODLES', 'productPool/1.jpg', 21 ),
( 'MAGGI HOT HEADS PERI NOODLES', 'productPool/1.jpg', 141 ),
( 'MAGGI HOT SWEET 200GM', 'productPool/1.jpg', 23 ),
( 'MAGGI MAGIC CUBES 40G', 'productPool/1.jpg', 81 ),
( 'MAGGI MASALA CUPPA NOODLES 70G', 'productPool/1.jpg', 141 ),
( 'MAGGI MASALA NOODLES 140G', 'productPool/1.jpg', 255 ),
( 'MAGGI MASALA NOODLES 280G', 'productPool/1.jpg', 111 ),
( 'MAGGI MASALA NOODLES 420G', 'productPool/1.jpg', 2 ),
( 'MAGGI MASALA NOODLES 70G', 'productPool/1.jpg', 251 ),
( 'MAGGI NOODLES VEG ATTA', 'productPool/1.jpg', 40 ),
( 'MAGGI OATS NOODLES 290G', 'productPool/1.jpg', 195 ),
( 'MAGGI OATS NOODLES 300G', 'productPool/1.jpg', 127 ),
( 'MAGGI PAZZTA CHEESE MACARONI 64G', 'productPool/1.jpg', 202 ),
( 'MAGGI PAZZTA CHEESE MACARONI 70G', 'productPool/1.jpg', 198 ),
( 'MAGGI PAZZTA CHEESY TOMATO TWIST 64G', 'productPool/1.jpg', 239 ),
( 'MAGGI PAZZTA MASALA PENNE 64G', 'productPool/1.jpg', 4 ),
( 'MAGGI PAZZTA MASALA PENNE 65G', 'productPool/1.jpg', 99 ),
( 'MAGGI PAZZTA MUSHROOM PENNE 64G', 'productPool/1.jpg', 202 ),
( 'MAGGI RICH TOMATO KETCHUP 200GM', 'productPool/1.jpg', 90 ),
( 'MAGGI RICH TOMATO SAUCE 200GM', 'productPool/1.jpg', 196 ),
( 'MAGGI RICH TOMATO SAUCE 500G', 'productPool/1.jpg', 122 ),
( 'MAGGI SUPER CHENNAI MASALA NOODLES 73G', 'productPool/1.jpg', 256 ),
( 'MAGGI TOMATO KET PICHKOO 90G', 'productPool/1.jpg', 240 ),
( 'MAGGI TOMATO KETCHUP BOTTLE 500G', 'productPool/1.jpg', 224 ),
( 'MAGGI TOMATO KETCHUP PICHKOO', 'productPool/1.jpg', 194 ),
( 'MAGGI TOMATO PICHKOO 90G', 'productPool/1.jpg', 76 ),
( 'MAGGI VEGETABLE CUBE IMP', 'productPool/1.jpg', 102 ),
( 'MAGI X ORANGE', 'productPool/1.jpg', 57 ),
( 'MAGIC BOLL', 'productPool/1.jpg', 269 ),
( 'MAGIC FINGER COMB', 'productPool/1.jpg', 130 ),
( 'MAGIC FINGER COMB IMP', 'productPool/1.jpg', 20 ),
( 'MAGIC ORANGE 250G', 'productPool/1.jpg', 139 ),
( 'MAGIC ORGE SCRB SOAP 75G', 'productPool/1.jpg', 17 ),
( 'MAGIC POCKET COMB', 'productPool/1.jpg', 148 ),
( 'MAGIC POPS CANDY LEMON APPLE 5.5G', 'productPool/1.jpg', 32 ),
( 'MAGIC ROUND COMB', 'productPool/1.jpg', 145 ),
( 'MAGIC SUMMER COMB', 'productPool/1.jpg', 44 ),
( 'MAGIC SUMMER COMB RS2', 'productPool/1.jpg', 214 ),
( 'MAGIC SUMMER COMB RS4', 'productPool/1.jpg', 97 ),
( 'MAGIC TOWEL', 'productPool/1.jpg', 10 ),
( 'MAGIX CHOCO BISCUTS 250G', 'productPool/1.jpg', 34 ),
( 'MAGNA ROUND JAR 1700ML', 'productPool/1.jpg', 203 ),
( 'MAGNIFYING GLASS', 'productPool/1.jpg', 47 ),
( 'MAHARAJA COCONUT POWDER 1KG', 'productPool/1.jpg', 238 ),
( 'MAHARANI COCONUT POWDER 1KG', 'productPool/1.jpg', 170 ),
( 'MAHENDRA BEETER SS-2', 'productPool/1.jpg', 197 ),
( 'MAHIMA MARAYOOR JAGGERY 500G', 'productPool/1.jpg', 43 ),
( 'MAHIMAS CHICKEN ACHAR 250G', 'productPool/1.jpg', 109 ),
( 'MAHIMAS FISH ACHAR 250G', 'productPool/1.jpg', 211 ),
( 'MAIDA 1KG', 'productPool/1.jpg', 275 ),
( 'MAIDA 500G', 'productPool/1.jpg', 205 ),
( 'MAIYAS BADAM MILK 100G', 'productPool/1.jpg', 183 ),
( 'MAIYAS BADAM MILK DRINK 180ML', 'productPool/1.jpg', 81 ),
( 'MAIYAS BUTTER MURUKKU 190G', 'productPool/1.jpg', 92 ),
( 'MAIYAS CHOW CHOW MIXTURE 150G', 'productPool/1.jpg', 177 ),
( 'MAIYAS RASGULLA 275G', 'productPool/1.jpg', 50 ),
( 'MAIYAS SOAN PAPDI COCONUT 200G', 'productPool/1.jpg', 69 ),
( 'MAIZE 500GM', 'productPool/1.jpg', 64 ),
( 'MAJOR BROKEN WHEAT 500G', 'productPool/1.jpg', 138 ),
( 'MAJOR CHEMBA PUTTU PODI 500G', 'productPool/1.jpg', 191 ),
( 'MAJOR IDIYAPPAM 500G', 'productPool/1.jpg', 235 ),
( 'MAJOR IDIYAPPAM PODI 1KG', 'productPool/1.jpg', 234 ),
( 'MAJOR INSTAND PALAPPAM PODI 500G', 'productPool/1.jpg', 204 ),
( 'MAJOR MATTA BROKEN RICE 500G', 'productPool/1.jpg', 149 ),
( 'MAJOR PATHIRI RICE POWDER 1KG', 'productPool/1.jpg', 189 ),
( 'MAJOR PURE WHEAT POWDER 1KG', 'productPool/1.jpg', 257 ),
( 'MAJOR PUTTU PODI 1KG', 'productPool/1.jpg', 237 ),
( 'MAJOR PUTTUPODI 500G', 'productPool/1.jpg', 253 ),
( 'MAJOR RICE POWDER 500G', 'productPool/1.jpg', 140 ),
( 'MAJOR ROASTED RAVA 1KG', 'productPool/1.jpg', 143 ),
( 'MAJOR ROASTED RAVA 500G', 'productPool/1.jpg', 273 ),
( 'MAJOR SAMBA BROKEN WHEAT 500G', 'productPool/1.jpg', 12 ),
( 'MAJOR SAMBA BROKEN WHEAT RAVA 500G', 'productPool/1.jpg', 252 ),
( 'MAJOR WHEAT PUTTU PODI 500G', 'productPool/1.jpg', 95 ),
( 'MALABAR BIRIYANI KIT 1KG', 'productPool/1.jpg', 35 ),
( 'MALABAR SINDHOORI 175G', 'productPool/1.jpg', 79 ),
( 'MALANAD MANGO CRUSH 605KG', 'productPool/1.jpg', 73 ),
( 'MALANAD PASSION FRUIT DRINK 300ML', 'productPool/1.jpg', 97 ),
( 'MALANAD PASSION FRUIT SQUASH 500ML', 'productPool/1.jpg', 34 ),
( 'MALANAD PASSION FRUIT SQUASH 750ML', 'productPool/1.jpg', 77 ),
( 'MALANAD PASSION FRUIT SYRUP 600ML', 'productPool/1.jpg', 200 ),
( 'MALANAD PINK GUAVA CRUSH 6.5KG', 'productPool/1.jpg', 25 ),
( 'MALANADU GHEE 100ML', 'productPool/1.jpg', 118 ),
( 'MALANADU GHEE 200ML', 'productPool/1.jpg', 87 ),
( 'MALANADU GHEE 500ML', 'productPool/1.jpg', 185 ),
( 'MALANO EASY BLACK HAIR SHAMPOO 15ML', 'productPool/1.jpg', 245 ),
( 'MALANO EASY BLACK HAIR SHAMPOO 25ML', 'productPool/1.jpg', 133 ),
( 'MALAYALA MANORAMA SAMBADHYAM', 'productPool/1.jpg', 89 ),
( 'MALAYALA MANORAMMA KALIKUDUKKA', 'productPool/1.jpg', 73 ),
( 'malayala manoramma THE WEEK', 'productPool/1.jpg', 184 ),
( 'MALAYALI CHAMMANTHI PODI 140G', 'productPool/1.jpg', 165 ),
( 'MALAYALI CHAMMANTHI PODI 160G', 'productPool/1.jpg', 267 ),
( 'MALAYALI CHAMMANTHI PODI 70G', 'productPool/1.jpg', 231 ),
( 'MALAYALI DOSAMAVU', 'productPool/1.jpg', 107 ),
( 'MALAYALI PAPPADAM 50G', 'productPool/1.jpg', 144 ),
( 'MALAYALI PORATTA', 'productPool/1.jpg', 17 ),
( 'MALAYALI WHEAT PORATTA', 'productPool/1.jpg', 49 ),
( 'MALLI 250G', 'productPool/1.jpg', 50 ),
( 'MALLI 500G', 'productPool/1.jpg', 209 ),
( 'MALLI 500GM', 'productPool/1.jpg', 215 ),
( 'MALLI FINE 250GM', 'productPool/1.jpg', 1 ),
( 'MALLI LEAVES', 'productPool/1.jpg', 35 ),
( 'MALLI SPILT 250G', 'productPool/1.jpg', 29 ),
( 'MALTOVA 500G PKT', 'productPool/1.jpg', 135 ),
( 'MALTOVITAA MILKOSE 200G', 'productPool/1.jpg', 262 ),
( 'MAMAS BEEF CUTLET 200GMS', 'productPool/1.jpg', 54 ),
( 'MAMAS CHICKEN CUTLET 200 GMS', 'productPool/1.jpg', 40 ),
( 'MAMAS FISH CUTLET 200 GMS', 'productPool/1.jpg', 17 ),
( 'MAMAS MUTTON CUTLET 200 GMS', 'productPool/1.jpg', 187 ),
( 'MAMAS VEG CUTLET 200 GMS', 'productPool/1.jpg', 4 ),
( 'MAMEES PEANUT BALL', 'productPool/1.jpg', 175 ),
( 'MAMY POKO MEDIUM 40 PCS', 'productPool/1.jpg', 99 ),
( 'MAMY POKO PANT STD M4', 'productPool/1.jpg', 224 ),
( 'MAMY POKO PANTS L4', 'productPool/1.jpg', 254 ),
( 'MAMY POKO PANTS L46', 'productPool/1.jpg', 233 ),
( 'MAMY POKO PANTS M 8', 'productPool/1.jpg', 152 ),
( 'MAMY POKO PANTS M4', 'productPool/1.jpg', 219 ),
( 'MAMY POKO PANTS M56PCS', 'productPool/1.jpg', 222 ),
( 'MAMY POKO PANTS STANDARD SMALL 46N', 'productPool/1.jpg', 55 ),
( 'MAMY POKO PANTS XL 38', 'productPool/1.jpg', 29 ),
( 'MAMY POKO PANTS XL14', 'productPool/1.jpg', 37 ),
( 'MAMY POKO SMALL 8 PCS', 'productPool/1.jpg', 62 ),
( 'MAMY POKO STANDAR M36', 'productPool/1.jpg', 211 ),
( 'MAMY POKO STANDARD L17', 'productPool/1.jpg', 184 ),
( 'MAMY POKO XL 26', 'productPool/1.jpg', 96 ),
( 'MAMY POKO XXL 12', 'productPool/1.jpg', 93 ),
( 'MAMY POKO XXL 22 PCS', 'productPool/1.jpg', 132 ),
( 'MAMY POKO XXXL 7', 'productPool/1.jpg', 142 ),
( 'MAMY POKOPANTS XL 7N', 'productPool/1.jpg', 147 ),
( 'MAMYPOKO PANTS EXTRA ABSORB LARGE 7', 'productPool/1.jpg', 210 ),
( 'MAMYPOKO PANTS EXTRA ABSORB S4N', 'productPool/1.jpg', 234 ),
( 'MAMYPOKO PANTS L12', 'productPool/1.jpg', 245 ),
( 'MAMYPOKO PANTS L32', 'productPool/1.jpg', 131 ),
( 'MAMYPOKO PANTS L34S', 'productPool/1.jpg', 268 ),
( 'MAMYPOKO PANTS L44', 'productPool/1.jpg', 237 ),
( 'MAMYPOKO PANTS L6', 'productPool/1.jpg', 32 ),
( 'MAMYPOKO PANTS L7N', 'productPool/1.jpg', 119 ),
( 'MAMYPOKO PANTS M14', 'productPool/1.jpg', 38 ),
( 'MAMYPOKO PANTS M15', 'productPool/1.jpg', 44 ),
( 'MAMYPOKO PANTS M36', 'productPool/1.jpg', 222 ),
( 'MAMYPOKO PANTS M52', 'productPool/1.jpg', 2 ),
( 'MAMYPOKO PANTS M7', 'productPool/1.jpg', 27 ),
( 'MAMYPOKO PANTS M8', 'productPool/1.jpg', 164 ),
( 'MAMYPOKO PANTS M9 PANTS', 'productPool/1.jpg', 9 ),
( 'MAMYPOKO PANTS NB 10N', 'productPool/1.jpg', 217 ),
( 'MAMYPOKO PANTS NB 9N', 'productPool/1.jpg', 24 ),
( 'MAMYPOKO PANTS NB-1 EXTRA ABSORB 10PC', 'productPool/1.jpg', 167 ),
( 'MAMYPOKO PANTS S 60S', 'productPool/1.jpg', 208 ),
( 'MAMYPOKO PANTS S17', 'productPool/1.jpg', 118 ),
( 'MAMYPOKO PANTS S42', 'productPool/1.jpg', 177 ),
( 'MAMYPOKO PANTS S58', 'productPool/1.jpg', 139 ),
( 'MAMYPOKO PANTS S8', 'productPool/1.jpg', 9 ),
( 'MAMYPOKO PANTS S9 PANTS', 'productPool/1.jpg', 151 ),
( 'MAMYPOKO PANTS SMALL 16', 'productPool/1.jpg', 97 ),
( 'MAMYPOKO PANTS STANDARD L-8PC', 'productPool/1.jpg', 26 ),
( 'MAMYPOKO PANTS STANDARD L4N', 'productPool/1.jpg', 61 ),
( 'MAMYPOKO PANTS STANDARD MEDIUM 18N', 'productPool/1.jpg', 142 ),
( 'MAMYPOKO PANTS STANDARD S-4N', 'productPool/1.jpg', 70 ),
( 'MAMYPOKO PANTS STANDARD S11', 'productPool/1.jpg', 182 ),
( 'MAMYPOKO PANTS XL 26', 'productPool/1.jpg', 128 ),
( 'MAMYPOKO PANTS XL 36', 'productPool/1.jpg', 219 ),
( 'MAMYPOKO PANTS XL 5 PANTS', 'productPool/1.jpg', 83 ),
( 'MAMYPOKO PANTS XL 7', 'productPool/1.jpg', 6 ),
( 'MAMYPOKO PANTS XL13', 'productPool/1.jpg', 159 ),
( 'MAMYPOKO PANTS XL14', 'productPool/1.jpg', 54 ),
( 'MAMYPOKO PANTS XL7', 'productPool/1.jpg', 196 ),
( 'MAMYPOKO PANTS XXL 22', 'productPool/1.jpg', 214 ),
( 'MAMYPOKO PANTS XXL12', 'productPool/1.jpg', 128 ),
( 'MANACHA PONNI', 'productPool/1.jpg', 165 ),
( 'MANGALADEEP MOGRA AGARBATHI 14N MRP 10', 'productPool/1.jpg', 13 ),
( 'MANGALADEEP ROSE AGARBATHI 14N MRP 10', 'productPool/1.jpg', 192 ),
( 'MANGALADEEP TREYA AGARBATHI 14N MRP 10', 'productPool/1.jpg', 12 ),
( 'MANGALADEEP TREYA AGARBATHI 84N MRP 50', 'productPool/1.jpg', 89 ),
( 'MANGALASSERIL FISH PICKLE 250G', 'productPool/1.jpg', 218 ),
( 'MANGO ALPHONSO DRIED 100G', 'productPool/1.jpg', 23 ),
( 'MANGO PULP 3.1KG', 'productPool/1.jpg', 242 ),
( 'MANGO PULP 3KG', 'productPool/1.jpg', 95 ),
( 'MANGO TANG 125G', 'productPool/1.jpg', 35 ),
( 'MANGO TANG 500G RS 125', 'productPool/1.jpg', 97 ),
( 'MANNA BITTERGUARD PICKLE 1KG', 'productPool/1.jpg', 87 ),
( 'MANNA CUT MANGO PICKLE 1KG', 'productPool/1.jpg', 127 ),
( 'MANNA DATES PICKLE 1KG', 'productPool/1.jpg', 12 ),
( 'MANNA GARLIC PICKLE 1KG', 'productPool/1.jpg', 95 ),
( 'MANNA LEMON PICKLE 1KG', 'productPool/1.jpg', 13 ),
( 'MANNA TENDER MANGO PICKLE 1KG', 'productPool/1.jpg', 217 ),
( 'MANORAMMA AROGYA MAGAZINE', 'productPool/1.jpg', 249 ),
( 'MANORAMMA BALARAMA', 'productPool/1.jpg', 134 ),
( 'MANORAMMA CALENDAR', 'productPool/1.jpg', 183 ),
( 'MANORAMMA DIGEST', 'productPool/1.jpg', 117 ),
( 'MANORAMMA PACHAKAM', 'productPool/1.jpg', 39 ),
( 'MANORAMMA TELL ME WHY', 'productPool/1.jpg', 99 ),
( 'MANORAMMA VEEDU', 'productPool/1.jpg', 85 ),
( 'MANORAMMA WEEKLY', 'productPool/1.jpg', 69 ),
( 'MAPRO ALPHONSO MANGO CRUSH 750ML', 'productPool/1.jpg', 128 ),
( 'MAPRO BLUEBERRY CRUSH 750ML', 'productPool/1.jpg', 52 ),
( 'MAPRO CITRUS BLUE CRUSH 750ML', 'productPool/1.jpg', 257 ),
( 'MAPRO GRAPE CRUSH 750ML', 'productPool/1.jpg', 269 ),
( 'MAPRO GREEN APPLE CRUSH 750ML', 'productPool/1.jpg', 38 ),
( 'MAPRO KIWI CRUSH 750ML', 'productPool/1.jpg', 210 ),
( 'MAPRO LITCHI CRUSH 750ML', 'productPool/1.jpg', 45 ),
( 'MAPRO MANGO CRUSH 750ML', 'productPool/1.jpg', 87 ),
( 'MAPRO ORANGE CRUSH 750ML', 'productPool/1.jpg', 130 ),
( 'MAPRO PINEAPPLE CRUSH 750ML', 'productPool/1.jpg', 59 ),
( 'MAPRO PINK GUAVA CRUSH 750ML', 'productPool/1.jpg', 209 ),
( 'MAPRO STRAWBERRY CRUSH 750ML', 'productPool/1.jpg', 169 ),
( 'MARAYOOR SARKARA 1KG', 'productPool/1.jpg', 53 ),
( 'MARAYOOR SARKARA 500G', 'productPool/1.jpg', 92 ),
( 'MARGO GLYCERINE 3+1 -300G', 'productPool/1.jpg', 207 ),
( 'MARGO GLYCERINE 50G', 'productPool/1.jpg', 257 ),
( 'MARGO GLYCERINE 75G', 'productPool/1.jpg', 188 ),
( 'MARGO MOISTURISER SOAP 100G', 'productPool/1.jpg', 114 ),
( 'MARGO NATURAL NEEM HANDWASH 200ML', 'productPool/1.jpg', 98 ),
( 'MARGO NEEM SOAP 75G', 'productPool/1.jpg', 254 ),
( 'MARGO ORIGINAL NEEM 75G', 'productPool/1.jpg', 253 ),
( 'MARGO ORIGINAL NEEM SOAP 100G', 'productPool/1.jpg', 101 ),
( 'MARIAS MANGO PULP 3 KG', 'productPool/1.jpg', 79 ),
( 'MARIAS BEEF IDIYIRACHI 100G PKT', 'productPool/1.jpg', 125 ),
( 'MARIAS BEEF IDIYIRACHI 200G', 'productPool/1.jpg', 175 ),
( 'MARIAS BEEFG IDIYIRACHI 50G', 'productPool/1.jpg', 91 ),
( 'MARIAS BEEFG IDIYIRACHI COMBO75G', 'productPool/1.jpg', 127 ),
( 'MARIAS CHILLY SAUCE 200ML', 'productPool/1.jpg', 261 ),
( 'MARIAS CHILLY SAUCE 700G', 'productPool/1.jpg', 36 ),
( 'MARIAS COCONUT CHUTNEY POWDER 100G', 'productPool/1.jpg', 214 ),
( 'MARIAS COCONUT CHUTNEY POWDER 250GMS', 'productPool/1.jpg', 179 ),
( 'MARIAS COCONUT CHUTNEY POWDER 500G', 'productPool/1.jpg', 165 ),
( 'MARIAS CUT MANGO PICKLE 200G', 'productPool/1.jpg', 17 ),
( 'MARIAS CUT MANGO PICKLE 200G BOTTLE', 'productPool/1.jpg', 186 ),
( 'MARIAS CUT MANGO PICKLE 400G', 'productPool/1.jpg', 239 ),
( 'MARIAS CUT MANGO PICKLE 500G', 'productPool/1.jpg', 104 ),
( 'MARIAS CUT MANGO PICKLE 500G POUCH', 'productPool/1.jpg', 224 ),
( 'MARIAS DRY CHILLI CHAMMANDI 200G', 'productPool/1.jpg', 55 ),
( 'MARIAS DRY CHILLY CHUTNEY 100G', 'productPool/1.jpg', 20 ),
( 'MARIAS FISH PICKLE 200G JAR', 'productPool/1.jpg', 91 ),
( 'MARIAS FISH PICKLE 60G', 'productPool/1.jpg', 75 ),
( 'MARIAS GARLIC PASTE 100G', 'productPool/1.jpg', 174 ),
( 'MARIAS GARLIC PICKLE 200G BOTTLE', 'productPool/1.jpg', 176 ),
( 'MARIAS GARLIC PICKLE 200G JAR', 'productPool/1.jpg', 164 ),
( 'MARIAS GARLIC PICKLE 200G PKT', 'productPool/1.jpg', 118 ),
( 'MARIAS GARLIC PICKLE 400G BOTTLE', 'productPool/1.jpg', 190 ),
( 'MARIAS GARLIC PICKLE 500G PKT', 'productPool/1.jpg', 28 ),
( 'MARIAS GINGER GARLIC PASTE 100G', 'productPool/1.jpg', 37 ),
( 'MARIAS GINGER PICKLE 200G', 'productPool/1.jpg', 109 ),
( 'MARIAS GINGER PICKLE 200G PKT', 'productPool/1.jpg', 46 ),
( 'MARIAS GOOSEBERRY PICKLE 200G PKT', 'productPool/1.jpg', 102 ),
( 'MARIAS GRAPE SQUASH 700ML', 'productPool/1.jpg', 139 ),
( 'MARIAS GREEN CHILLY PICKLE 200G', 'productPool/1.jpg', 140 ),
( 'MARIAS HOT SWEET LIME PICKLE 200G', 'productPool/1.jpg', 27 ),
( 'MARIAS INSTANT FRY PASTE 100G', 'productPool/1.jpg', 37 ),
( 'MARIAS KANTHARI CHAMMANDI 100G', 'productPool/1.jpg', 233 ),
( 'MARIAS KANTHARI CHILLI CHAMMANDI 200G', 'productPool/1.jpg', 97 ),
( 'MARIAS LIME PICKLE 200G BOTTLE', 'productPool/1.jpg', 168 ),
( 'MARIAS LIME PICKLE 200G PKT', 'productPool/1.jpg', 164 ),
( 'MARIAS LIME PICKLE 400G BOTTLE', 'productPool/1.jpg', 248 ),
( 'MARIAS LIME PICKLE 500G', 'productPool/1.jpg', 207 ),
( 'MARIAS LIME PICKLE 500G PKT', 'productPool/1.jpg', 3 ),
( 'MARIAS MANGO JAM 100G', 'productPool/1.jpg', 204 ),
( 'MARIAS MANGO SQUASH 700ML', 'productPool/1.jpg', 46 ),
( 'MARIAS MARIAS MIXED FRUIT JAM 1KG', 'productPool/1.jpg', 109 ),
( 'MARIAS MIXED FRUIT JAM 100G', 'productPool/1.jpg', 160 ),
( 'MARIAS MIXED FRUIT JAM 200G', 'productPool/1.jpg', 81 ),
( 'MARIAS MIXED FRUIT JAM 500G', 'productPool/1.jpg', 85 ),
( 'MARIAS PINE APPLE FRUIT JAM 200G', 'productPool/1.jpg', 241 ),
( 'MARIAS PINE APPLE FRUIT JAM 500G', 'productPool/1.jpg', 58 ),
( 'MARIAS PINEAPPLE FRUIT JAM 100G', 'productPool/1.jpg', 18 ),
( 'MARIAS PINEAPPLE SQUASH 700ML', 'productPool/1.jpg', 279 ),
( 'MARIAS PRAWN CHUTNEY POWDER 250G', 'productPool/1.jpg', 12 ),
( 'MARIAS PRAWN PICKLE 200G', 'productPool/1.jpg', 45 ),
( 'MARIAS PRAWN PICKLE 200G B', 'productPool/1.jpg', 189 ),
( 'MARIAS PRAWNS CHILLI CHAMMANDHI 80G', 'productPool/1.jpg', 189 ),
( 'MARIAS PRAWNS CHUTNEY POWDER 100G', 'productPool/1.jpg', 279 ),
( 'MARIAS PRAWNS CHUTNEY POWDER 250G', 'productPool/1.jpg', 64 ),
( 'MARIAS PRAWNS CHUTNEY POWDER 500G', 'productPool/1.jpg', 163 ),
( 'MARIAS PRAWNS PICKLE 60G PKT', 'productPool/1.jpg', 263 ),
( 'MARIAS PULIYINCHI 200G', 'productPool/1.jpg', 152 ),
( 'MARIAS RED CHILLI SAUCE 200G', 'productPool/1.jpg', 172 ),
( 'MARIAS SOFT DRINK CON ORANGE 200ML', 'productPool/1.jpg', 151 ),
( 'MARIAS SOFT DRINK CON PINEAPPLE 200ML', 'productPool/1.jpg', 231 ),
( 'MARIAS SOFT DRINK MANGO FLAVOUR 200ML', 'productPool/1.jpg', 241 ),
( 'MARIAS SOYA BEAN SAUCE 200GM', 'productPool/1.jpg', 170 ),
( 'MARIAS SOYA BEAN SAUCE 700ML', 'productPool/1.jpg', 59 ),
( 'MARIAS SYNTHETIC VINEGAR 1 L', 'productPool/1.jpg', 200 ),
( 'MARIAS SYNTHETIC VINEGAR 500ML', 'productPool/1.jpg', 62 ),
( 'MARIAS TENDER MANGO PICKLE 400G B', 'productPool/1.jpg', 52 ),
( 'MARIAS TENDER MANGO PICKLE 500G', 'productPool/1.jpg', 130 ),
( 'MARIAS TENDER MANGO PICKLE 500G PKT', 'productPool/1.jpg', 245 ),
( 'MARIAS TENDER MANGO PICKLE 500G POUCH', 'productPool/1.jpg', 168 ),
( 'MARIAS TOMATO KETCHUP 200G', 'productPool/1.jpg', 183 ),
( 'MARIAS TOMATO SAUC E1KG', 'productPool/1.jpg', 108 ),
( 'MARIAS TOMATO SAUCE 1KG', 'productPool/1.jpg', 61 ),
( 'MARIAS TOMATO SAUCE 200G', 'productPool/1.jpg', 56 ),
( 'MARIAS ULUVA MANGO PICKLES 100G', 'productPool/1.jpg', 200 ),
( 'MARIAS VADUKAPPULI PICKLE 200G', 'productPool/1.jpg', 170 ),
( 'MARICOS HAIR CARE 200ML', 'productPool/1.jpg', 102 ),
( 'MARICOS HAIR CARE 300ML', 'productPool/1.jpg', 115 ),
( 'MARS CHOCOLATE 51G', 'productPool/1.jpg', 255 ),
( 'MARSHMALLOW FRUIT FLAVOUR 160G IMP', 'productPool/1.jpg', 94 ),
( 'MARUTHA PANCHAJEERAKAGUDAM 450G', 'productPool/1.jpg', 228 ),
( 'MARUTHI TONGUE CLEANER', 'productPool/1.jpg', 239 ),
( 'MARYAMI DATES 200G', 'productPool/1.jpg', 130 ),
( 'MARYAMI DATES 400G', 'productPool/1.jpg', 19 ),
( 'MARYAMI DATES 500G', 'productPool/1.jpg', 43 ),
( 'MASAFI APPLE JUICE 200ML', 'productPool/1.jpg', 269 ),
( 'MASAFI FRUITS APPLE JUICE 1L', 'productPool/1.jpg', 212 ),
( 'MASAFI FRUITS MANGO JUICE 1L', 'productPool/1.jpg', 233 ),
( 'MASAFI FRUITS MANGO NECTAR 200ML', 'productPool/1.jpg', 63 ),
( 'MASAFI FRUITS TROPICAL NECTAR JUICE 1L', 'productPool/1.jpg', 258 ),
( 'MASAFI MANGO NECTAR 200ML', 'productPool/1.jpg', 222 ),
( 'MASALA BANANA CHIPS 150G', 'productPool/1.jpg', 214 ),
( 'MASALA MIX PKT', 'productPool/1.jpg', 86 ),
( 'MASOOR DAL 500G', 'productPool/1.jpg', 207 ),
( 'MASOOR DAL MOGAR 500G', 'productPool/1.jpg', 99 ),
( 'MASOOR DAL RED 500G', 'productPool/1.jpg', 173 ),
( 'MASOOR DALL RED 500G', 'productPool/1.jpg', 110 ),
( 'MAT RS135', 'productPool/1.jpg', 40 ),
( 'MAT RS200', 'productPool/1.jpg', 277 ),
( 'MATHA CHAMMANTHIPODI 100G', 'productPool/1.jpg', 49 ),
( 'MATHA FOOD CHAMMANTHIPODI 1KG', 'productPool/1.jpg', 96 ),
( 'MATHA FOOD CHAMMANTHIPODI 500G', 'productPool/1.jpg', 71 ),
( 'MATHA FOOD KANTHARI PICKLE 100G', 'productPool/1.jpg', 156 ),
( 'MATHA FOOD KANTHARI PICKLE 500G', 'productPool/1.jpg', 222 ),
( 'MATHA FOODS BIRIYANI KIT 1.2KG', 'productPool/1.jpg', 185 ),
( 'MATHA FOODS CHAMMANTHIPODI 250G', 'productPool/1.jpg', 120 ),
( 'MATHA FOODS CHAMMANTHIPODI 300G', 'productPool/1.jpg', 273 ),
( 'MATHA FOODS PRAWN CHAMMANTHI PODI 100G', 'productPool/1.jpg', 126 ),
( 'MATHA FOODS PRAWNS ROASTED 50G', 'productPool/1.jpg', 168 ),
( 'MATHA FOODS SPECIAL BIRIYANI MIX 1.5KG', 'productPool/1.jpg', 53 ),
( 'MATHA KANTHARI PICKLE 250G', 'productPool/1.jpg', 116 ),
( 'MATHANGA', 'productPool/1.jpg', 185 ),
( 'MATHANGA SMALL', 'productPool/1.jpg', 227 ),
( 'MATHRUBHOOMI AROGYAM', 'productPool/1.jpg', 60 ),
( 'MATHRUBHOOMI PANJANKAM', 'productPool/1.jpg', 271 ),
( 'MATHRUBHOOMI YEAR BOOK ENGLISH', 'productPool/1.jpg', 198 ),
( 'MATHRUBHOOMI YEAR BOOK MALAYALAM', 'productPool/1.jpg', 208 ),
( 'MATHRUBHUMI STAR STYLE RS50', 'productPool/1.jpg', 264 ),
( 'MATHRUBHUMI YATHRA', 'productPool/1.jpg', 256 ),
( 'MATTEES 5STAR ALARABI KABSA KIT 1KG', 'productPool/1.jpg', 23 ),
( 'MATTEES 5STAR ALARABI MANDI KIT 1KG', 'productPool/1.jpg', 159 ),
( 'MATTEES 5STAR ARABIAN KABSA KIT 1KG', 'productPool/1.jpg', 95 ),
( 'MATTEES 5STAR ARABIAN QAHWA 50GM', 'productPool/1.jpg', 162 ),
( 'MATTEES 5STAR BROAST POWDER 200GM', 'productPool/1.jpg', 276 ),
( 'MATTEES 5STAR BROAST POWDER SPECIAL 200GM', 'productPool/1.jpg', 254 ),
( 'MATTEES 5STAR HYDERABADI BIRYANI KIT 1KG', 'productPool/1.jpg', 182 ),
( 'MATTEES 5STAR KABSA MASALA 100GM', 'productPool/1.jpg', 235 ),
( 'MATTEES 5STAR MANDI KIT 1KG', 'productPool/1.jpg', 275 ),
( 'MATTEES 5STAR MANDI MASALA 100GM', 'productPool/1.jpg', 279 ),
( 'MAVELIL KRISHNANEELI HAIR OIL 100ML', 'productPool/1.jpg', 263 ),
( 'MAX PROTEIN ACTIVE CHOCO FUDGE BAR 75G', 'productPool/1.jpg', 14 ),
( 'MAX PROTEIN DAILY CHOCO ALMOND BAR 50G', 'productPool/1.jpg', 176 ),
( 'MAX PROTEIN SNACK CHEESE JALAPENO 30G', 'productPool/1.jpg', 131 ),
( 'MAX PROTEIN SNACK CHINESE MANCHURIAN 150G', 'productPool/1.jpg', 49 ),
( 'MAX PROTEIN SNACK CHINESE MANCHURIAN 30G', 'productPool/1.jpg', 214 ),
( 'MAX PROTEIN SNACK CHINESE MANCHURIAN 60G', 'productPool/1.jpg', 223 ),
( 'MAX PROTEIN SNACK CREAM AND ONION 150G', 'productPool/1.jpg', 274 ),
( 'MAX PROTEIN SNACK CREAM AND ONION 30G', 'productPool/1.jpg', 119 ),
( 'MAX PROTEIN SNACK CREAM AND ONION 60G', 'productPool/1.jpg', 129 ),
( 'MAX PROTEIN SNACK DESI MASALA 30G', 'productPool/1.jpg', 64 ),
( 'MAX PROTEIN SNACK DESI MASALA 60G', 'productPool/1.jpg', 64 ),
( 'MAX PROTEIN SNACK PERI PERI 30G', 'productPool/1.jpg', 200 ),
( 'MAX PROTEIN SNACK SALT AND PEPPER 150G', 'productPool/1.jpg', 178 ),
( 'MAX PROTEIN SNACK SALT AND PEPPER 30G', 'productPool/1.jpg', 172 ),
( 'MAX PROTEIN SNACK SALT AND PEPPER 60G', 'productPool/1.jpg', 187 ),
( 'MAX PROTEIN SNACK SPANISH TOMATO 30G', 'productPool/1.jpg', 16 ),
( 'MAX WAX POLISH 50 ML BLACK', 'productPool/1.jpg', 220 ),
( 'MAX WAX POLISH75 ML', 'productPool/1.jpg', 269 ),
( 'MAX WAX SHOE BRUSH', 'productPool/1.jpg', 270 ),
( 'MAX WAX XTRA SHINE40G', 'productPool/1.jpg', 21 ),
( 'MAX WET WIPES', 'productPool/1.jpg', 144 ),
( 'MAX WHITE 120G', 'productPool/1.jpg', 177 ),
( 'MAXI WET DATES 500G', 'productPool/1.jpg', 129 ),
( 'MAXO A GRADE COMBIC MACHINE 45ML', 'productPool/1.jpg', 77 ),
( 'MAXO A GRADE SET', 'productPool/1.jpg', 268 ),
( 'MAXO COIL GREEN', 'productPool/1.jpg', 60 ),
( 'MAXO GENIUS CALMING AROMA 45ML', 'productPool/1.jpg', 250 ),
( 'MAXO GENIUS COMBI 35ML', 'productPool/1.jpg', 273 ),
( 'MAXO GENIUS COMBO', 'productPool/1.jpg', 268 ),
( 'MAXO GENIUS LIQUID VAPORISER', 'productPool/1.jpg', 98 ),
( 'maxo genus autoshift mrp 81', 'productPool/1.jpg', 86 ),
( 'MAXO LIQUID REFILL 45ML', 'productPool/1.jpg', 274 ),
( 'MAXO PRESS FIT COMBI RS-63', 'productPool/1.jpg', 98 ),
( 'MAXO RED 8 HR MOSQUITO COIL', 'productPool/1.jpg', 136 ),
( 'MAXO REFIL 45ML', 'productPool/1.jpg', 72 ),
( 'MAXTRON GOLD PEN', 'productPool/1.jpg', 94 ),
( 'MAXWAX SHOE BRUSH BIG', 'productPool/1.jpg', 133 ),
( 'MAXWAX SHOE POLISH 50ML BROWN', 'productPool/1.jpg', 98 ),
( 'MAXWAX SHOE POLISH BIG', 'productPool/1.jpg', 64 ),
( 'MAXWAX SHOE POLISH BLACK 15GM', 'productPool/1.jpg', 34 ),
( 'MAXWAX SHOE POLISH DTAN 40G', 'productPool/1.jpg', 181 ),
( 'MAXWAX XTRA SHINE BLACK 7ML', 'productPool/1.jpg', 77 ),
( 'MAXWAX XTRA SHINE NEUTRAL 7ML', 'productPool/1.jpg', 146 ),
( 'MAXWAX XTRA SHINE PRESS 15G', 'productPool/1.jpg', 159 ),
( 'MAXWAX XTRA SHINE PRESS 40G', 'productPool/1.jpg', 35 ),
( 'MAYA BAKTHI AGARBATHI', 'productPool/1.jpg', 38 ),
( 'MAYA DURGA SHAKTI AGARBATHI', 'productPool/1.jpg', 147 ),
( 'MAYA JASMINE AGARBATHI RS 10', 'productPool/1.jpg', 223 ),
( 'MAYA ROSE AGARBATHI 20 STICKS', 'productPool/1.jpg', 234 ),
( 'MAYA SANADL AGARBATHI RS 10', 'productPool/1.jpg', 96 ),
( 'MAYA SUPREME ROSE 18G', 'productPool/1.jpg', 65 ),
( 'MAYBELLENE BABY LIPS CHERRY KISS LIPBALM 4G', 'productPool/1.jpg', 199 ),
( 'MAYBELLINE BABY LIP COLOUR BERRY CRUSH', 'productPool/1.jpg', 145 ),
( 'MAYBELLINE BABY LIP COLOUR HW 4G', 'productPool/1.jpg', 215 ),
( 'MAYBELLINE BABY LIP COLOUR MM 4G', 'productPool/1.jpg', 111 ),
( 'MAYBELLINE BABY LIP COLOUR WATERMELON 4G', 'productPool/1.jpg', 200 ),
( 'MAYBELLINE BABY LIPS BC 8G', 'productPool/1.jpg', 61 ),
( 'MAYBELLINE BABY LIPS BROOKLYN BRONZE 8G', 'productPool/1.jpg', 97 ),
( 'MAYBELLINE BABY LIPS BW 8G', 'productPool/1.jpg', 67 ),
( 'MAYBELLINE BABY LIPS CHERRY KISS 4G B1G1', 'productPool/1.jpg', 73 ),
( 'MAYBELLINE BABY LIPS COLOUR BB 4G', 'productPool/1.jpg', 272 ),
( 'MAYBELLINE BABY LIPS COLOUR BR 4G', 'productPool/1.jpg', 70 );