INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'DHATHRI CHEMAPARATHI THAALI 200 ML', 'productPool/1.jpg', 132 ),
( 'DHATHRI CHEMPAKAM SOAP 75G', 'productPool/1.jpg', 147 ),
( 'DHATHRI DAHASAMANI 50G', 'productPool/1.jpg', 13 ),
( 'DHATHRI DAILY HAIR OIL 90ML', 'productPool/1.jpg', 219 ),
( 'DHATHRI DANDRUFF OIL 75ML', 'productPool/1.jpg', 265 ),
( 'DHATHRI DHEEDHI DAILY SHAMPOO 400ML', 'productPool/1.jpg', 201 ),
( 'DHATHRI DHEEDHI HERBAL SHAMPOO 100 ML', 'productPool/1.jpg', 86 ),
( 'DHATHRI DHEEDHI SHAMPOO 200 ML', 'productPool/1.jpg', 176 ),
( 'DHATHRI FAIR SKIN CREAM 50G', 'productPool/1.jpg', 219 ),
( 'DHATHRI FAIRNESS FACE PACK 50G', 'productPool/1.jpg', 59 ),
( 'DHATHRI FAIRNESS TURMERIC FACE CREAM 25G', 'productPool/1.jpg', 266 ),
( 'DHATHRI FAIRNESS TURMERIC FACE CREAM 50G', 'productPool/1.jpg', 277 ),
( 'DHATHRI HAIR CARE PLUS 200 ML', 'productPool/1.jpg', 122 ),
( 'DHATHRI HAIR CARE PLUS HERBAL OIL 100 ML', 'productPool/1.jpg', 2 ),
( 'DHATHRI HAIR PROTECTOR 50G', 'productPool/1.jpg', 136 ),
( 'DHATHRI HERBAL CONDITIONER 100ML', 'productPool/1.jpg', 164 ),
( 'DHATHRI HERBAL CONDITIONER 200ML', 'productPool/1.jpg', 73 ),
( 'DHATHRI HERBAL KAJAL 1G', 'productPool/1.jpg', 173 ),
( 'DHATHRI HERBAL OIL 100 ML', 'productPool/1.jpg', 222 ),
( 'DHATHRI KASTHURIMANJAL POWDER 50G', 'productPool/1.jpg', 94 ),
( 'DHATHRI MOISTURIZING ALOE VERA HW 250ML', 'productPool/1.jpg', 261 ),
( 'DHATHRI NEELIBHRINGADI KERAM HAIR OIL 100ML', 'productPool/1.jpg', 143 ),
( 'DHATHRI NEEM FACE WASH 100ML', 'productPool/1.jpg', 154 ),
( 'DHATHRI NEEM FACE WASH 50ML', 'productPool/1.jpg', 240 ),
( 'DHATHRI PREMEHA DAHASAMANI', 'productPool/1.jpg', 224 ),
( 'DHATHRI SKIN CARE CREAM 20G', 'productPool/1.jpg', 272 ),
( 'DHATHRI TURMERIC FACE WASH 100ML', 'productPool/1.jpg', 37 ),
( 'DHATHRI TURMERIC FACE WASH 50ML', 'productPool/1.jpg', 274 ),
( 'DHATHRI WHITENING SAFFRON FACEWASH 100ML', 'productPool/1.jpg', 126 ),
( 'DHATHU BRAHMI PEANUT CHIKKI 100G', 'productPool/1.jpg', 254 ),
( 'DHATHU BRAHMI PEANUT CHIKKI 180G', 'productPool/1.jpg', 138 ),
( 'DHATHU COCONUT NEERA JAGGERY 400G', 'productPool/1.jpg', 217 ),
( 'DHATHU COCONUT NEERA JAGGERY 500G', 'productPool/1.jpg', 79 ),
( 'DHATHU COCONUT NEERA PEANUT CHIKKI 180G', 'productPool/1.jpg', 211 ),
( 'DHATHU COCONUT NEERA SESAME BALLS BLACK 90G', 'productPool/1.jpg', 25 ),
( 'DHATHU COCONUT SUGAR 300G', 'productPool/1.jpg', 36 ),
( 'DHATHU FLAX SEED 300G', 'productPool/1.jpg', 164 ),
( 'DHATHU FLAX SEED OMEGA 400G', 'productPool/1.jpg', 247 ),
( 'DHATHU FLAX SEED PEANUT CHIKKI 180G', 'productPool/1.jpg', 89 ),
( 'DHATHU HIMALAYAN MINERAL SALT 1KG', 'productPool/1.jpg', 177 ),
( 'DHATHU MORINGA PEANUT CHIKKI 100G', 'productPool/1.jpg', 105 ),
( 'DHATHU PEANUT CHIKKI 100G', 'productPool/1.jpg', 113 ),
( 'DHATHU PEANUT CHIKKI 180G', 'productPool/1.jpg', 202 ),
( 'DHATHU RAMDANA CHIKKI BALLS 160G', 'productPool/1.jpg', 133 ),
( 'DHATHU RAMDANA CHIKKI BAR 75G', 'productPool/1.jpg', 157 ),
( 'DHATHU ROSE PEANUT CHIKKI 100G', 'productPool/1.jpg', 10 ),
( 'DHATHU SEASAME BALL 90G', 'productPool/1.jpg', 259 ),
( 'DHATHU SEASAME CHIKKI 100G', 'productPool/1.jpg', 79 ),
( 'DHATRI FAIRNESS MOSTURIZER 100ML', 'productPool/1.jpg', 181 ),
( 'DHATU BLACK RAISIN 100G', 'productPool/1.jpg', 275 ),
( 'DHATU COCONUT BLOSSOM SUGAR 250G', 'productPool/1.jpg', 19 ),
( 'DHATU COWPEA RED 500G', 'productPool/1.jpg', 78 ),
( 'DHATU HIMALAYAN PINK SALT 500G', 'productPool/1.jpg', 129 ),
( 'DHATU ORGANIC CASHEW WHOLE 100G', 'productPool/1.jpg', 6 ),
( 'DHATU ORGANIC FLOUR 1KG', 'productPool/1.jpg', 111 ),
( 'DHATU ORGANIC JAGGERY 450G', 'productPool/1.jpg', 263 ),
( 'DHATU ORGANIC JAGGERY POWDER 500G', 'productPool/1.jpg', 257 ),
( 'DHATU ORGANIC RAGI 1KG', 'productPool/1.jpg', 223 ),
( 'DHATU ORGANIC RAISINS 100G', 'productPool/1.jpg', 146 ),
( 'DHATU ORGANIC RED RICE 1KG', 'productPool/1.jpg', 242 ),
( 'DHATU ORGANIC WHITE RICE 1KG', 'productPool/1.jpg', 40 ),
( 'DHEEDHI ANT-HAIR FALLHERBAL SHAMPOO 100ML', 'productPool/1.jpg', 139 ),
( 'DHEEDHI ANTI DANDRUFF SHAMPOO 100ML', 'productPool/1.jpg', 75 ),
( 'DHEEDHI ANTI DANDRUFF SHAMPOO 200ML', 'productPool/1.jpg', 41 ),
( 'DHEEDHI SHAMPOO SACHET 5ML', 'productPool/1.jpg', 90 ),
( 'DHONY CUTLARY STAND', 'productPool/1.jpg', 211 ),
( 'DIABETIC GREEN TEA TEFE 50 GM', 'productPool/1.jpg', 245 ),
( 'DIABLISS COMBO TEA 300G', 'productPool/1.jpg', 268 ),
( 'DIABLISS DIABETIC FRENDLY SUGAR 500G', 'productPool/1.jpg', 107 ),
( 'DIABLISS GINGER TEA 100G', 'productPool/1.jpg', 18 ),
( 'DIABLISS HERBAL LEMON TEA 100G', 'productPool/1.jpg', 95 ),
( 'DIABLISS HERBAL LEMON TEA 300G', 'productPool/1.jpg', 87 ),
( 'DIABLISS MASALA TEA 100G', 'productPool/1.jpg', 70 ),
( 'DIABLISS MILLET COOKIES 150G', 'productPool/1.jpg', 60 ),
( 'DIABLISS MILLET COOKIES SEEDS 150G', 'productPool/1.jpg', 85 ),
( 'DIABLISS MIXED FRUIT JAM 250G', 'productPool/1.jpg', 267 ),
( 'DIABLISS WHOLE WHEAT ATTA 1KG', 'productPool/1.jpg', 26 ),
( 'DIABLISSMILLET COOKIES MORINGA LEAF 150G', 'productPool/1.jpg', 263 ),
( 'DIABLSS LEMON TEA WITH SUGAR 100G', 'productPool/1.jpg', 245 ),
( 'DIAMOND BASKET WITH LID FAMILY', 'productPool/1.jpg', 66 ),
( 'DIAMOND CUTLARY STAND', 'productPool/1.jpg', 197 ),
( 'DIAMOND DRAGON CHINESE EGG NOODLES 300G', 'productPool/1.jpg', 220 ),
( 'DIANA LAUNDRY SKEP', 'productPool/1.jpg', 67 ),
( 'DIET COKE 300ML', 'productPool/1.jpg', 230 ),
( 'DIMPU AMPLE CUP WITH HOOD', 'productPool/1.jpg', 159 ),
( 'DIMPU BABY BOTTLE BRUSH', 'productPool/1.jpg', 117 ),
( 'DIMPU BABY FEEDING CUP', 'productPool/1.jpg', 109 ),
( 'DIMPU HOT WATER BAG', 'productPool/1.jpg', 109 ),
( 'DIMPU POOP CEE COLOURS BOTTLE 140ML', 'productPool/1.jpg', 15 ),
( 'DIMPU POOP CEE COLOURS BOTTLE 240ML', 'productPool/1.jpg', 4 ),
( 'DIMPU POOP CEE DOODLE BOTTLE 140ML', 'productPool/1.jpg', 37 ),
( 'DIMPU POOP CEE DOODLE BOTTLE 240ML', 'productPool/1.jpg', 151 ),
( 'DIMPU POOP-CEE NIPPLE', 'productPool/1.jpg', 109 ),
( 'DIMPU POWDER PUFF DELUXE', 'productPool/1.jpg', 47 ),
( 'DIMPU POWDER PUFF REGULAR', 'productPool/1.jpg', 178 ),
( 'DIMPU SILICONE NIPPLE', 'productPool/1.jpg', 192 ),
( 'DIMPU SOOTHER WITH COVER', 'productPool/1.jpg', 274 ),
( 'DIMPU TEETHING FINGER BRUSH', 'productPool/1.jpg', 57 ),
( 'DIMU POOP-CEE BUBBLES 125ML', 'productPool/1.jpg', 69 ),
( 'DINETTE TEA STRAINER NO.1', 'productPool/1.jpg', 120 ),
( 'DINETTE TEA STRAINER NO.2', 'productPool/1.jpg', 51 ),
( 'DINETTE TEA STRAINER NO.3', 'productPool/1.jpg', 246 ),
( 'DINNER ROLL(4 NOS)', 'productPool/1.jpg', 191 ),
( 'DISANO APPLE CIDER MOTHER VINEGAR 500ML', 'productPool/1.jpg', 263 ),
( 'DISANO APPLE CIDER VINEGAR FILTERED 500ML', 'productPool/1.jpg', 173 ),
( 'DISANO CANOLA OIL 1L B1G2', 'productPool/1.jpg', 228 ),
( 'DISANO ELBOWS 500G', 'productPool/1.jpg', 31 ),
( 'DISANO EXTRA LIGHT OLIVE OIL 1LT', 'productPool/1.jpg', 103 ),
( 'DISANO EXTRA LIGHT OLIVE OIL 500ML', 'productPool/1.jpg', 137 ),
( 'DISANO EXTRA VIRGIN OLIVE OIL 1', 'productPool/1.jpg', 123 ),
( 'DISANO EXTRA VIRGIN OLIVE OIL 250ML', 'productPool/1.jpg', 136 ),
( 'DISANO EXTRA VIRGIN OLIVE OIL 500', 'productPool/1.jpg', 208 ),
( 'DISANO FUSILLI 500G', 'productPool/1.jpg', 258 ),
( 'DISANO OLIVE OIL 1L', 'productPool/1.jpg', 278 ),
( 'DISANO OLIVE OIL 250ML', 'productPool/1.jpg', 62 ),
( 'DISANO OLIVE OIL 500ML', 'productPool/1.jpg', 151 ),
( 'DISANO OLIVE POMACE OIL 1 LTS', 'productPool/1.jpg', 60 ),
( 'DISANO OLIVE POMACE OIL 500 ML', 'productPool/1.jpg', 213 ),
( 'DISANO OLIVE POMACE OIL 5L TIN', 'productPool/1.jpg', 237 ),
( 'DISANO PEANUT BUTTER CHOCO CREAMY 350G', 'productPool/1.jpg', 90 ),
( 'DISANO PEANUT BUTTER CREAMY 350G', 'productPool/1.jpg', 273 ),
( 'DISANO PEANUT BUTTER CRUNCHY 350G', 'productPool/1.jpg', 99 ),
( 'DISANO PENNE RIGATE 500G', 'productPool/1.jpg', 186 ),
( 'DISANO SPAGHETTI 500G', 'productPool/1.jpg', 203 ),
( 'DISCOVERY BETTA FISH FOOD 20G', 'productPool/1.jpg', 50 ),
( 'DISH GOLD DISHWASHBAR250G', 'productPool/1.jpg', 266 ),
( 'DISH GOLD LEMON 500G', 'productPool/1.jpg', 210 ),
( 'DIVINE ROYAL CASHEWS 100G', 'productPool/1.jpg', 7 ),
( 'DIVINE ROYAL CASHEWS 125G TIN', 'productPool/1.jpg', 247 ),
( 'DIVINE ROYAL CASHEWS 200G', 'productPool/1.jpg', 214 ),
( 'DIVINE ROYAL CASHEWS 250G TIN', 'productPool/1.jpg', 147 ),
( 'DIZZLE CHOCO MILK CANDY 250G', 'productPool/1.jpg', 30 ),
( 'DIZZLE COCKTAIL CANDY 220G', 'productPool/1.jpg', 255 ),
( 'DIZZLE DIGESTIVE MITHA AMLA 160G', 'productPool/1.jpg', 3 ),
( 'DIZZLE DILBAHAR MIX', 'productPool/1.jpg', 246 ),
( 'DIZZLE FRUIT BALL MOCKTAIL 250G', 'productPool/1.jpg', 262 ),
( 'DIZZLE KALA KHATTA CANDY 220G', 'productPool/1.jpg', 3 ),
( 'DIZZLE MANGO CANDY200GM', 'productPool/1.jpg', 100 ),
( 'DIZZLE MANGO SHOTS CANDY 250G', 'productPool/1.jpg', 132 ),
( 'DIZZLE MASALA SHORT CANDY 250G', 'productPool/1.jpg', 74 ),
( 'DIZZLE MINT CANDY 220G', 'productPool/1.jpg', 13 ),
( 'DIZZLE MOUTH FRESHENER GREEN MIX 210G', 'productPool/1.jpg', 265 ),
( 'DIZZLE MOUTH FRESHENER MADRASI SOUNFF 180G', 'productPool/1.jpg', 79 ),
( 'DIZZLE MOUTH FRESHENER TINI MINI 255G', 'productPool/1.jpg', 168 ),
( 'DIZZLE MOUTH FRESHNER STRANGEE MIX 200G', 'productPool/1.jpg', 66 ),
( 'DIZZLE ORANGE CANDY 200G', 'productPool/1.jpg', 258 ),
( 'DIZZLE PAN CANDY 220G', 'productPool/1.jpg', 275 ),
( 'DNA POCKET PERFUME BLUE SUEDE 18ML', 'productPool/1.jpg', 104 ),
( 'DNA POCKET PERFUME DIABLO 18ML', 'productPool/1.jpg', 124 ),
( 'DNA POCKET PERFUME GLAM AND GLITZ 18ML', 'productPool/1.jpg', 145 ),
( 'DNA POCKET PERFUME XTREME SPORT 18ML', 'productPool/1.jpg', 168 ),
( 'DND PREVENTS MOSQUITOES LIQUID 45ML', 'productPool/1.jpg', 103 ),
( 'DOCTORS PHENYLE 450ML', 'productPool/1.jpg', 103 ),
( 'DOCUMENT ENVELOPE BAG DE841', 'productPool/1.jpg', 186 ),
( 'DOG PIN BRUSH MEDIUM 160', 'productPool/1.jpg', 145 ),
( 'DOLL CHOCOLATE', 'productPool/1.jpg', 195 ),
( 'DOLL SET 25-84-90', 'productPool/1.jpg', 270 ),
( 'DOLL TOY', 'productPool/1.jpg', 246 ),
( 'DOMESTOS RIM BLOCK LIME 55G', 'productPool/1.jpg', 268 ),
( 'DOMESTOS RIM BLOCK OCEAN 55G', 'productPool/1.jpg', 184 ),
( 'DOMEX FLOOR CLEANER 500ML', 'productPool/1.jpg', 220 ),
( 'DOMEX PHENOL CLEAN 2-1 500ML', 'productPool/1.jpg', 207 ),
( 'DOMEX TOILET CLEANER 500ML', 'productPool/1.jpg', 217 ),
( 'DOMEX TOILET EXPERT 1LT RS-141', 'productPool/1.jpg', 24 ),
( 'DOMEX TOILET THICK CLEANER 500ML', 'productPool/1.jpg', 86 ),
( 'DOMEX ZERO STAIN LEMON POWER 450ML', 'productPool/1.jpg', 271 ),
( 'DOMEX ZERO STAIN LEMON POWER 750ML', 'productPool/1.jpg', 45 ),
( 'DON MONTE ALMOND 450G', 'productPool/1.jpg', 109 ),
( 'DON MONTE ANEER 200G', 'productPool/1.jpg', 123 ),
( 'DON MONTE BLACK KISMIS 200G', 'productPool/1.jpg', 80 ),
( 'DON MONTE CALIFORNIA ALMONDS 180G', 'productPool/1.jpg', 44 ),
( 'DON MONTE MIX BERRIES 300G', 'productPool/1.jpg', 162 ),
( 'DON MONTE PRUNES 200G', 'productPool/1.jpg', 209 ),
( 'DON MONTE SALTED PISTA 200G', 'productPool/1.jpg', 183 ),
( 'DON MONTE TRIAL MIX 200G', 'productPool/1.jpg', 235 ),
( 'DOOR MAT KIDS MAT 14*21', 'productPool/1.jpg', 238 ),
( 'DOOR MAT MILLET PRIME 2*4', 'productPool/1.jpg', 16 ),
( 'DOOR MAT SHAGGY DESIGN 16*24', 'productPool/1.jpg', 274 ),
( 'DOOR MAT SHAGGY OVAL 13*19', 'productPool/1.jpg', 176 ),
( 'DOOR MAT SHAGGY OVAL 16*24', 'productPool/1.jpg', 29 ),
( 'DOOR MAT SHAGGY STONE 13*19', 'productPool/1.jpg', 251 ),
( 'DOOR MAT SHAGGY STONE 16*24', 'productPool/1.jpg', 175 ),
( 'DOOR MAT SHENILE ROPE 14*22', 'productPool/1.jpg', 216 ),
( 'DORITOS SWEET CHILLI 525G', 'productPool/1.jpg', 83 ),
( 'DOTS SKORE CONDOMS80R', 'productPool/1.jpg', 153 ),
( 'DOUBLE DEER DEHRADUNI RICE 1KG', 'productPool/1.jpg', 98 ),
( 'DOUBLE DEER PAKWAAN RICE 1KG', 'productPool/1.jpg', 35 ),
( 'DOUBLE DEER PAKWAN RICE 1KG', 'productPool/1.jpg', 118 ),
( 'DOUBLE DEER ZEERA SAMBA RICE 1KG', 'productPool/1.jpg', 204 ),
( 'DOUBLE GOLD BASMATI RICE 1KG', 'productPool/1.jpg', 157 ),
( 'DOUBLE HORSE APPAM IDIYAPPAM PATHIRI 1KG', 'productPool/1.jpg', 115 ),
( 'DOUBLE HORSE APPAM/ IDIAPPAM / PATHIRI 500G', 'productPool/1.jpg', 213 ),
( 'DOUBLE HORSE AVAL THICK RICE 500G', 'productPool/1.jpg', 159 ),
( 'DOUBLE HORSE AVAL WHITE THICK 400G', 'productPool/1.jpg', 234 ),
( 'DOUBLE HORSE AVALOSE PODI 200G', 'productPool/1.jpg', 277 ),
( 'DOUBLE HORSE AVALOSE PODI 500G', 'productPool/1.jpg', 279 ),
( 'DOUBLE HORSE BANANA POWDER 250G', 'productPool/1.jpg', 171 ),
( 'DOUBLE HORSE BASMATI RICE 1KG', 'productPool/1.jpg', 218 ),
( 'DOUBLE HORSE BIRIYANI MASALA 100GMS', 'productPool/1.jpg', 5 ),
( 'DOUBLE HORSE BLACK TAMARIND 100G', 'productPool/1.jpg', 222 ),
( 'DOUBLE HORSE BRAHMIN SAMBAR POWDER 100GM', 'productPool/1.jpg', 57 ),
( 'DOUBLE HORSE BROKEN WHEAT 1KG', 'productPool/1.jpg', 229 ),
( 'DOUBLE HORSE BROKEN WHEAT 500G', 'productPool/1.jpg', 269 ),
( 'DOUBLE HORSE CASHEW MACAROONS 50G', 'productPool/1.jpg', 192 ),
( 'DOUBLE HORSE CHAKI ATTA 1KG', 'productPool/1.jpg', 206 ),
( 'DOUBLE HORSE CHAKI FRESH ATTA 5KG', 'productPool/1.jpg', 266 ),
( 'DOUBLE HORSE CHAKKI FRESH ATTA 2KG', 'productPool/1.jpg', 178 ),
( 'DOUBLE HORSE CHEF MATE 1KG', 'productPool/1.jpg', 153 ),
( 'DOUBLE HORSE CHEMBA PUTTU PODI 500G', 'productPool/1.jpg', 149 ),
( 'DOUBLE HORSE CHEMPA PUTTU PODI 1KG', 'productPool/1.jpg', 245 ),
( 'DOUBLE HORSE CHICKEN MASALA 100G', 'productPool/1.jpg', 73 ),
( 'DOUBLE HORSE CHICKEN PICKLE 400G', 'productPool/1.jpg', 101 ),
( 'DOUBLE HORSE CHICKEN PICKLE 400G B1G1', 'productPool/1.jpg', 100 ),
( 'DOUBLE HORSE CHILLI POWDER 1 KG', 'productPool/1.jpg', 111 ),
( 'DOUBLE HORSE CHILLI POWDER 250G', 'productPool/1.jpg', 228 ),
( 'DOUBLE HORSE CHILLY POWDER 500G', 'productPool/1.jpg', 113 ),
( 'DOUBLE HORSE CHILY POWDER 100G', 'productPool/1.jpg', 75 ),
( 'DOUBLE HORSE CHUTNEY POWDER 100G', 'productPool/1.jpg', 261 ),
( 'DOUBLE HORSE COCONUT MILK 200G', 'productPool/1.jpg', 232 ),
( 'DOUBLE HORSE COCONUT WATER VINEGAR 500ML', 'productPool/1.jpg', 179 ),
( 'DOUBLE HORSE COM POU ASAFOETID 50G', 'productPool/1.jpg', 3 ),
( 'DOUBLE HORSE COMPOUNDED ASAFOETIDA 50G', 'productPool/1.jpg', 137 ),
( 'DOUBLE HORSE CORIANDER POWDER 100G', 'productPool/1.jpg', 188 ),
( 'DOUBLE HORSE CORIANDER POWDER 250G', 'productPool/1.jpg', 42 ),
( 'DOUBLE HORSE CORIENDER POWDER 500G', 'productPool/1.jpg', 261 ),
( 'DOUBLE HORSE CORN FLOUR 350G', 'productPool/1.jpg', 209 ),
( 'DOUBLE HORSE CORN PUTTU PODI 500G', 'productPool/1.jpg', 256 ),
( 'DOUBLE HORSE CORNFLOUR150G', 'productPool/1.jpg', 55 ),
( 'DOUBLE HORSE CORRIANDER POWDER 1 KG', 'productPool/1.jpg', 99 ),
( 'DOUBLE HORSE CRUSH CHILLY 100G', 'productPool/1.jpg', 56 ),
( 'DOUBLE HORSE CUT MANGO PICKLE 150G', 'productPool/1.jpg', 163 ),
( 'DOUBLE HORSE CUT MANGO PICKLE 200GMS REFILL', 'productPool/1.jpg', 39 ),
( 'DOUBLE HORSE CUT MANGO PICKLE 400G', 'productPool/1.jpg', 172 ),
( 'DOUBLE HORSE CUT MANGO PICKLE 500GMS REFILL', 'productPool/1.jpg', 153 ),
( 'DOUBLE HORSE CUT MANGO PICKLE 900G', 'productPool/1.jpg', 177 ),
( 'DOUBLE HORSE CUT MANGO PICKLE5KG', 'productPool/1.jpg', 23 ),
( 'DOUBLE HORSE CUTMANGO PICKLE 100G REFILL', 'productPool/1.jpg', 62 ),
( 'DOUBLE HORSE DATE MANGO PICKLE 400G', 'productPool/1.jpg', 114 ),
( 'DOUBLE HORSE DATE PICKLE 200G', 'productPool/1.jpg', 186 ),
( 'DOUBLE HORSE DATE PICKLE 400G', 'productPool/1.jpg', 193 ),
( 'DOUBLE HORSE DATES PICKLE 150G', 'productPool/1.jpg', 231 ),
( 'DOUBLE HORSE DATES PICKLE 150G B1G1', 'productPool/1.jpg', 232 ),
( 'DOUBLE HORSE DATES PICKLE 400G B1G1', 'productPool/1.jpg', 28 ),
( 'DOUBLE HORSE DATES PICKLE 500G', 'productPool/1.jpg', 236 ),
( 'DOUBLE HORSE DIET PAYASAM MIX SUGAR FREE 75G', 'productPool/1.jpg', 254 ),
( 'DOUBLE HORSE DOSA CHUTNEY 100G', 'productPool/1.jpg', 19 ),
( 'DOUBLE HORSE DOSA MIX 500G', 'productPool/1.jpg', 219 ),
( 'DOUBLE HORSE EGG ROAST MASALA 100G', 'productPool/1.jpg', 95 ),
( 'DOUBLE HORSE EXTRA VIRGIN COCONUT OIL 230ML', 'productPool/1.jpg', 249 ),
( 'DOUBLE HORSE FENNEL100G', 'productPool/1.jpg', 22 ),
( 'DOUBLE HORSE FISH MASALA 100G', 'productPool/1.jpg', 79 ),
( 'DOUBLE HORSE FISH PICKLE 150G', 'productPool/1.jpg', 53 ),
( 'DOUBLE HORSE FISH PICKLE 200G', 'productPool/1.jpg', 187 ),
( 'DOUBLE HORSE FISH PICKLE 400G', 'productPool/1.jpg', 272 ),
( 'DOUBLE HORSE FISH PICKLE 500GMS', 'productPool/1.jpg', 215 ),
( 'DOUBLE HORSE GARAM MASALA 50G', 'productPool/1.jpg', 27 ),
( 'DOUBLE HORSE GARLIC PASTE 100G', 'productPool/1.jpg', 109 ),
( 'DOUBLE HORSE GARLIC PICKLE 150G', 'productPool/1.jpg', 225 ),
( 'DOUBLE HORSE GARLIC PICKLE 150G B1G1', 'productPool/1.jpg', 202 ),
( 'DOUBLE HORSE GARLIC PICKLE 200G REFILL', 'productPool/1.jpg', 218 ),
( 'DOUBLE HORSE GARLIC PICKLE 400 GMS', 'productPool/1.jpg', 273 ),
( 'DOUBLE HORSE GARLIC PICKLE 400G B1G1', 'productPool/1.jpg', 60 ),
( 'DOUBLE HORSE GARLIC PICKLE 500G', 'productPool/1.jpg', 49 ),
( 'DOUBLE HORSE GINGER GARLIC PASTE 100GMS', 'productPool/1.jpg', 100 ),
( 'DOUBLE HORSE GINGER PASTE 100G', 'productPool/1.jpg', 262 ),
( 'DOUBLE HORSE GINGER PICKLE 150G', 'productPool/1.jpg', 137 ),
( 'DOUBLE HORSE GINGER PICKLE 400 GMS', 'productPool/1.jpg', 30 ),
( 'DOUBLE HORSE GOOSBERY PICKLE 150G', 'productPool/1.jpg', 258 ),
( 'DOUBLE HORSE GOOSEBERY PICKLE 150G B1G1', 'productPool/1.jpg', 46 ),
( 'DOUBLE HORSE GOOSEBERY PICKLE 400G B1G1', 'productPool/1.jpg', 275 ),
( 'DOUBLE HORSE H & S LIME DATE PICKLE 400G', 'productPool/1.jpg', 15 ),
( 'DOUBLE HORSE HEALTH MIX 500G', 'productPool/1.jpg', 137 ),
( 'DOUBLE HORSE HOT&SWEET LIME DATE PICKLE 150G', 'productPool/1.jpg', 7 ),
( 'DOUBLE HORSE IDIYAPPAM POWDER 1KG', 'productPool/1.jpg', 21 ),
( 'DOUBLE HORSE IDIYAPPAM POWDER 500G', 'productPool/1.jpg', 50 ),
( 'DOUBLE HORSE IDLI MIX500G', 'productPool/1.jpg', 246 ),
( 'DOUBLE HORSE INDIAN TAMARIND 200 G', 'productPool/1.jpg', 70 ),
( 'DOUBLE HORSE INDIAN TAMARIND 500G', 'productPool/1.jpg', 244 ),
( 'DOUBLE HORSE INSTANT GINGER COFFEE 150G', 'productPool/1.jpg', 273 ),
( 'DOUBLE HORSE INSTANT IDIYAPPAM 100G', 'productPool/1.jpg', 161 ),
( 'DOUBLE HORSE INSTANT PALADA MIX 200G', 'productPool/1.jpg', 36 ),
( 'DOUBLE HORSE INSTANT UPPUMA 250G', 'productPool/1.jpg', 58 ),
( 'DOUBLE HORSE INSTAT IDIYAPAM 200G', 'productPool/1.jpg', 90 ),
( 'DOUBLE HORSE JAYA RICE 10KG', 'productPool/1.jpg', 23 ),
( 'DOUBLE HORSE JAYA RICE 5KG', 'productPool/1.jpg', 224 ),
( 'DOUBLE HORSE JEERAKASALA RICE 1KG', 'productPool/1.jpg', 245 ),
( 'DOUBLE HORSE KADUKU MANGO PICKLE 400G', 'productPool/1.jpg', 116 ),
( 'DOUBLE HORSE KASHMIRI CHILLY POWDER 250 G', 'productPool/1.jpg', 24 ),
( 'DOUBLE HORSE KASHMIRI CHILLY POWDER 500GMS', 'productPool/1.jpg', 249 ),
( 'DOUBLE HORSE KASHMIRI CHILLYPOWDER 100G', 'productPool/1.jpg', 126 ),
( 'DOUBLE HORSE KASURIMETHI 25G', 'productPool/1.jpg', 50 ),
( 'DOUBLE HORSE LIME PICKLE 100G REFILL', 'productPool/1.jpg', 199 ),
( 'DOUBLE HORSE LIME PICKLE 150G', 'productPool/1.jpg', 215 ),
( 'DOUBLE HORSE LIME PICKLE 200G', 'productPool/1.jpg', 185 ),
( 'DOUBLE HORSE LIME PICKLE 400G', 'productPool/1.jpg', 100 ),
( 'DOUBLE HORSE LIME PICKLE 400G B1G1', 'productPool/1.jpg', 3 ),
( 'DOUBLE HORSE LIME PICKLE 5 KG', 'productPool/1.jpg', 48 ),
( 'DOUBLE HORSE LIME PICKLE 500G REFILL', 'productPool/1.jpg', 231 ),
( 'DOUBLE HORSE LIME PICKLE 900G', 'productPool/1.jpg', 141 ),
( 'DOUBLE HORSE LIME PICKLE 900G B1G1', 'productPool/1.jpg', 196 ),
( 'DOUBLE HORSE LONG VERMICILLI 400G', 'productPool/1.jpg', 251 ),
( 'DOUBLE HORSE MACARONI 200G', 'productPool/1.jpg', 223 ),
( 'DOUBLE HORSE MACRONI 400G', 'productPool/1.jpg', 3 ),
( 'DOUBLE HORSE MATTA BROCKEN RICE 500G', 'productPool/1.jpg', 100 ),
( 'DOUBLE HORSE MATTA BROKEN RICE 1KG', 'productPool/1.jpg', 20 ),
( 'DOUBLE HORSE MEAT MASALA 100G', 'productPool/1.jpg', 191 ),
( 'DOUBLE HORSE MEAT PICKLE 400 G', 'productPool/1.jpg', 210 ),
( 'DOUBLE HORSE MEAT PICKLE 400G B1G1', 'productPool/1.jpg', 269 ),
( 'DOUBLE HORSE MIXED FRUIT JAM 100G', 'productPool/1.jpg', 180 ),
( 'DOUBLE HORSE MIXED FRUIT JAM 200G', 'productPool/1.jpg', 114 ),
( 'DOUBLE HORSE MIXED VEG PICKLE 400G', 'productPool/1.jpg', 249 ),
( 'DOUBLE HORSE MIXED VEG PICKLE 400G B1G1', 'productPool/1.jpg', 224 ),
( 'DOUBLE HORSE PALADA PAYASAM 300G', 'productPool/1.jpg', 45 ),
( 'DOUBLE HORSE PALAPPAM MIX 1KG', 'productPool/1.jpg', 180 ),
( 'DOUBLE HORSE PALAPPAM MIX 500G', 'productPool/1.jpg', 54 ),
( 'DOUBLE HORSE PAYASAM BROKEN500G', 'productPool/1.jpg', 69 ),
( 'DOUBLE HORSE PEANUT CHIKKI 160G', 'productPool/1.jpg', 115 ),
( 'DOUBLE HORSE PEPPER POWDER 100G', 'productPool/1.jpg', 20 ),
( 'DOUBLE HORSE PEPPER POWDER 50G', 'productPool/1.jpg', 50 ),
( 'DOUBLE HORSE PICKLE POWDER 100 G', 'productPool/1.jpg', 109 ),
( 'DOUBLE HORSE PINEAPPLE DROPS 150G', 'productPool/1.jpg', 151 ),
( 'DOUBLE HORSE PRAWN CHAMMANTHI PODI 100G', 'productPool/1.jpg', 111 ),
( 'DOUBLE HORSE PRAWN PICKLE 200G', 'productPool/1.jpg', 82 ),
( 'DOUBLE HORSE PRAWN PICKLE 400G', 'productPool/1.jpg', 197 ),
( 'DOUBLE HORSE PRAWN PICKLE 400G B1G1', 'productPool/1.jpg', 140 ),
( 'DOUBLE HORSE PRAWN PICKLE 500G', 'productPool/1.jpg', 237 ),
( 'DOUBLE HORSE PRAWNS PICKLE 150G', 'productPool/1.jpg', 3 ),
( 'DOUBLE HORSE RAGI PUTTU PODI 500G', 'productPool/1.jpg', 220 ),
( 'DOUBLE HORSE RASAM POWDER 100G', 'productPool/1.jpg', 220 ),
( 'DOUBLE HORSE RED AVAL 500G', 'productPool/1.jpg', 192 ),
( 'DOUBLE HORSE RIBBON ADA 200G', 'productPool/1.jpg', 237 ),
( 'DOUBLE HORSE RICE PALADA 1KG', 'productPool/1.jpg', 97 ),
( 'DOUBLE HORSE RICE PALADA 200G', 'productPool/1.jpg', 126 ),
( 'DOUBLE HORSE RICE PALADA 500G', 'productPool/1.jpg', 81 ),
( 'DOUBLE HORSE RICE PALADA MIX 300G', 'productPool/1.jpg', 128 ),
( 'DOUBLE HORSE ROAST VERMICELLI 400G', 'productPool/1.jpg', 129 ),
( 'DOUBLE HORSE ROAST WHITE RICE FLOUR 1KG', 'productPool/1.jpg', 168 ),
( 'DOUBLE HORSE ROASTED RAGI POWDER 500G', 'productPool/1.jpg', 88 ),
( 'DOUBLE HORSE ROASTED RAVA 1KG', 'productPool/1.jpg', 233 ),
( 'DOUBLE HORSE ROASTED RAVA 500G', 'productPool/1.jpg', 239 ),
( 'DOUBLE HORSE ROASTED RAVA 500G', 'productPool/1.jpg', 61 ),
( 'DOUBLE HORSE ROASTED VERMICELLI 800G PKT', 'productPool/1.jpg', 57 ),
( 'DOUBLE HORSE ROASTED WHITE RICE FLOUR500G', 'productPool/1.jpg', 225 ),
( 'DOUBLE HORSE SAMBA BROCKEN WHEAT 1KG', 'productPool/1.jpg', 54 ),
( 'DOUBLE HORSE SAMBA BROKEN WHEAT 500G', 'productPool/1.jpg', 270 ),
( 'DOUBLE HORSE SAMBA WHEAT PUTTU PODI 500G', 'productPool/1.jpg', 119 ),
( 'DOUBLE HORSE SAMBAR POWDER 100G', 'productPool/1.jpg', 208 ),
( 'DOUBLE HORSE SEMIYA PAYASAM 300G', 'productPool/1.jpg', 81 ),
( 'DOUBLE HORSE SOYA CHUNKS 200G', 'productPool/1.jpg', 275 ),
( 'DOUBLE HORSE SOYA CHUNKS NANO 200G', 'productPool/1.jpg', 196 ),
( 'DOUBLE HORSE SUREKHA RICE 10KG', 'productPool/1.jpg', 108 ),
( 'DOUBLE HORSE SUREKHA RICE 5KG', 'productPool/1.jpg', 158 ),
( 'DOUBLE HORSE SYNTHETIC VINEGAR 1 LTR', 'productPool/1.jpg', 30 ),
( 'DOUBLE HORSE SYNTHETIC VINEGAR 500ML', 'productPool/1.jpg', 236 ),
( 'DOUBLE HORSE TAMARIND PASTE 100G', 'productPool/1.jpg', 200 ),
( 'DOUBLE HORSE TENDER MANGO PICKLE 150G', 'productPool/1.jpg', 270 ),
( 'DOUBLE HORSE TENDER MANGO PICKLE 200GMS', 'productPool/1.jpg', 98 ),
( 'DOUBLE HORSE TENDER MANGO PICKLE 400G', 'productPool/1.jpg', 170 ),
( 'DOUBLE HORSE TENDER MANGO PICKLE 500GMS REFILL', 'productPool/1.jpg', 96 ),
( 'DOUBLE HORSE TURMERIC POWDER 100G', 'productPool/1.jpg', 25 ),
( 'DOUBLE HORSE TURMERIC POWDER 250G', 'productPool/1.jpg', 141 ),
( 'DOUBLE HORSE UNDA MATTA 5KG', 'productPool/1.jpg', 41 ),
( 'DOUBLE HORSE UNDA MATTA RICE 10KG', 'productPool/1.jpg', 57 ),
( 'DOUBLE HORSE UNROASTED VERMICELLI', 'productPool/1.jpg', 218 ),
( 'DOUBLE HORSE VADI MATTA 10KG', 'productPool/1.jpg', 115 ),
( 'DOUBLE HORSE VADI MATTA 5KG', 'productPool/1.jpg', 185 ),
( 'DOUBLE HORSE VATTAYAPAM MIX 500G', 'productPool/1.jpg', 223 ),
( 'DOUBLE HORSE VEGTABLE MASALA 100G', 'productPool/1.jpg', 138 ),
( 'DOUBLE HORSE VIRGIN COCONUT OIL 250ML', 'productPool/1.jpg', 3 ),
( 'DOUBLE HORSE WHEAT BROKEN FINE 500G', 'productPool/1.jpg', 251 ),
( 'DOUBLE HORSE WHEAT RAVA 500G', 'productPool/1.jpg', 165 ),
( 'DOUBLE HORSE WHITE AVAL 500G', 'productPool/1.jpg', 166 ),
( 'DOUBLE HORSE WHITE LIME PICKLE 150G', 'productPool/1.jpg', 161 ),
( 'DOUBLE HORSE WHITE LIME PICKLE 150G B1G1', 'productPool/1.jpg', 96 ),
( 'DOUBLE HORSE WHITE LIME PICKLE 400G', 'productPool/1.jpg', 9 ),
( 'DOUBLE HORSE WHITE PUTTU PODI 1KG', 'productPool/1.jpg', 169 ),
( 'DOUBLE HORSE WHITE PUTTU PODI 500G', 'productPool/1.jpg', 127 ),
( 'DOUBLE HOURSE CUSTARD POWDER 150G', 'productPool/1.jpg', 227 ),
( 'DOUBLE HOURSE EXPORT RICE 75KG', 'productPool/1.jpg', 31 ),
( 'DOUBLE HOURSE WHEAT BROKEN FINE 1KG', 'productPool/1.jpg', 31 ),
( 'DOUBLE SIDE FOAM TAPE 24MM*4M', 'productPool/1.jpg', 2 ),
( 'DOUBLEHORSE JAGGERY POWDER 400G', 'productPool/1.jpg', 176 ),
( 'DOVE BABY LOTION 200ML', 'productPool/1.jpg', 204 ),
( 'DOVE BABY MASSAGE OIL 100ML', 'productPool/1.jpg', 47 ),
( 'DOVE BABY MASSAGE OIL 200ML', 'productPool/1.jpg', 146 ),
( 'DOVE BEAUTY FINISH 150ML', 'productPool/1.jpg', 202 ),
( 'DOVE BEAUTY MOISTURE 50G', 'productPool/1.jpg', 110 ),
( 'DOVE BODY LOTION (B)', 'productPool/1.jpg', 230 ),
( 'DOVE BODY LOTION (S) IMP', 'productPool/1.jpg', 20 ),
( 'DOVE BODY LOTION 250ML', 'productPool/1.jpg', 260 ),
( 'DOVE BODY LOTION 400ML', 'productPool/1.jpg', 8 ),
( 'DOVE BODY WASH ALMOND 250ML', 'productPool/1.jpg', 80 ),
( 'DOVE BODY WASH COCONUT 250ML', 'productPool/1.jpg', 129 ),
( 'DOVE BODY WASH PISTACHIO 250ML', 'productPool/1.jpg', 51 ),
( 'DOVE BODY WASH SHEA BUTTER 250ML', 'productPool/1.jpg', 59 ),
( 'DOVE CREAM 150 IMP', 'productPool/1.jpg', 9 ),
( 'DOVE CREAM 150 IMP BIG', 'productPool/1.jpg', 137 ),
( 'DOVE CREAM 250 IMP', 'productPool/1.jpg', 256 ),
( 'DOVE CREAM 75 IMP RS130', 'productPool/1.jpg', 185 ),
( 'DOVE CREAM BATHING BAR 75GM', 'productPool/1.jpg', 250 ),
( 'DOVE CREAM BATHING SOAP 4*75G', 'productPool/1.jpg', 140 ),
( 'DOVE CREAM BEAUTI BAR 225G', 'productPool/1.jpg', 35 ),
( 'DOVE CREAM BEAUTY 100G', 'productPool/1.jpg', 152 ),
( 'DOVE CREAM BIG BARRS 121', 'productPool/1.jpg', 67 ),
( 'DOVE CREM BEABA 50G', 'productPool/1.jpg', 202 ),
( 'DOVE DAILY SHINE CONDITIONER', 'productPool/1.jpg', 223 ),
( 'DOVE DAILY SHINE SHAMPOO 180ML', 'productPool/1.jpg', 34 ),
( 'DOVE DAILY SHINE SHAMPOO 340ML', 'productPool/1.jpg', 159 ),
( 'DOVE DAILY SHINE SHAMPOO 650ML', 'productPool/1.jpg', 251 ),
( 'DOVE DAILY SHINE SHAMPOO 80ML', 'productPool/1.jpg', 155 ),
( 'DOVE DANDRUFF CARE SHAMPOO 340ML', 'productPool/1.jpg', 215 ),
( 'DOVE DEEP CARE COMPLEX BODY LOTION 250ML', 'productPool/1.jpg', 142 ),
( 'DOVE DEO SENSITIVE 150ML', 'productPool/1.jpg', 262 ),
( 'DOVE DEO SOFT FEEL 150ML', 'productPool/1.jpg', 83 ),
( 'DOVE DEO WOMAN COTTON SOFT 150ML', 'productPool/1.jpg', 168 ),
( 'DOVE DRYNESS CARE CONDITIONER 180ML', 'productPool/1.jpg', 137 ),
( 'DOVE DRYNESS CARE SHAMPOO 180ML', 'productPool/1.jpg', 19 ),
( 'DOVE DRYNESS CARE SHAMPOO 340ML', 'productPool/1.jpg', 274 ),
( 'DOVE DRYNESS CARE SHAMPOO 80ML', 'productPool/1.jpg', 46 ),
( 'DOVE ENVIRONMENTAL DEFENCE SHAMPOO 180ML', 'productPool/1.jpg', 110 ),
( 'DOVE ENVIRONMENTAL DEFENCE SHAMPOO 650ML', 'productPool/1.jpg', 169 ),
( 'DOVE ESSENTIAL NOURISHMENT BODY LOTION100ML', 'productPool/1.jpg', 191 ),
( 'DOVE ESSN BODY LOTION 400ML', 'productPool/1.jpg', 235 ),
( 'DOVE GLOWING RITUAL BODY LOTION 250ML', 'productPool/1.jpg', 252 ),
( 'DOVE GLOWING RITUAL BODY LOTION 400ML', 'productPool/1.jpg', 175 ),
( 'DOVE GO FRESH BODY LOTION 100ML', 'productPool/1.jpg', 32 ),
( 'DOVE GO FRESH BODY WASH 250ML', 'productPool/1.jpg', 127 ),
( 'DOVE GO FRESH CUCUMBER DEO 150ML', 'productPool/1.jpg', 78 ),
( 'DOVE GO FRESH LEMON DEO 150ML', 'productPool/1.jpg', 26 ),
( 'DOVE GO FRESH NOURISHMENT LOTION 250ML', 'productPool/1.jpg', 25 ),
( 'DOVE GO FRESH REVIVE 3*100G SET SOAP', 'productPool/1.jpg', 139 ),
( 'DOVE HAIR FALL RESCUE 80ML', 'productPool/1.jpg', 4 ),
( 'DOVE HAIR FALL RESCUE CONDITIONER 80ML', 'productPool/1.jpg', 44 ),
( 'DOVE HAIR FALL RESCUE SHAMPOO 180ML', 'productPool/1.jpg', 28 ),
( 'DOVE HAIR FALL RESCUE SHAMPOO 340ML', 'productPool/1.jpg', 3 ),
( 'DOVE HAIR FALL RESCUE SHAMPOO 650ML', 'productPool/1.jpg', 210 ),
( 'DOVE HAIR THE INTENSE REPAIR SHAMPOO 180ML', 'productPool/1.jpg', 203 ),
( 'DOVE HAIR THERAPY DANDRUFF CARE SHA 80ML', 'productPool/1.jpg', 91 ),
( 'DOVE HAIR THERAPY DRYNESS CARE SHAMPOO 180ML', 'productPool/1.jpg', 60 ),
( 'DOVE HAIR THERAPY HAIR FALL RESCUE180ML', 'productPool/1.jpg', 88 ),
( 'DOVE HAIR THERAPY REPAIR SHAMPOO 180ML', 'productPool/1.jpg', 39 ),
( 'DOVE HAIRFALL RESCUE SHAMPOO 650ML', 'productPool/1.jpg', 153 ),
( 'DOVE INTENSE REPAIR CONDITIONER', 'productPool/1.jpg', 251 ),
( 'DOVE INTENSE REPAIR CONDITIONER75ML', 'productPool/1.jpg', 141 ),
( 'DOVE INTENSE REPAIR SHAMPOO 340ML', 'productPool/1.jpg', 201 ),
( 'DOVE INTENSE REPAIR SHAMPOO 650ML', 'productPool/1.jpg', 264 ),
( 'DOVE INTENSE REPAIR SHAMPOO 80ML', 'productPool/1.jpg', 271 ),
( 'DOVE INVIGORATING RITUAL BODY LOTION 250ML', 'productPool/1.jpg', 196 ),
( 'DOVE INVISIBLE DRY 150ML', 'productPool/1.jpg', 201 ),
( 'DOVE MINERAL TOUCH 150ML', 'productPool/1.jpg', 194 ),
( 'DOVE MOISTURE 75G', 'productPool/1.jpg', 199 ),
( 'DOVE ORIGNAL MOISTURISING CREAM 150ML', 'productPool/1.jpg', 91 ),
( 'DOVE OXYGEN MOISTURE SHAMPOO 340ML', 'productPool/1.jpg', 91 ),
( 'DOVE OXYGEN MOISTURE SHAMPOO 650ML', 'productPool/1.jpg', 92 ),
( 'DOVE OXYGEN MOISTURE SHAMPOO 80ML', 'productPool/1.jpg', 136 ),
( 'DOVE OXYGEN SHAMPOO 180 ML', 'productPool/1.jpg', 193 ),
( 'DOVE PINK SOAP 100G', 'productPool/1.jpg', 173 ),
( 'DOVE PURELY PAMPERING400ML', 'productPool/1.jpg', 183 ),
( 'DOVE REGENERATIVE REPAIR CONDITIONER 240ML', 'productPool/1.jpg', 146 ),
( 'DOVE REGENERATIVE REPAIR SHAMPOO 240ML', 'productPool/1.jpg', 21 ),
( 'DOVE REJUVENATED VOLUME SHAMPOO 240ML', 'productPool/1.jpg', 18 ),
( 'DOVE RICH MOISTURE 50G', 'productPool/1.jpg', 234 ),
( 'DOVE RICH MOISTURE BABY SHAMPOO 200ML', 'productPool/1.jpg', 37 ),
( 'DOVE SOAP 300G', 'productPool/1.jpg', 58 ),
( 'DOVE SOAP IMP 100G', 'productPool/1.jpg', 210 ),
( 'DOVE SOAP IMP RS68', 'productPool/1.jpg', 27 ),
( 'DOVE SOAP IMP RS90', 'productPool/1.jpg', 127 ),
( 'DOVE WHITENING ORIGINAL DEODRANT 169ML AP', 'productPool/1.jpg', 139 ),
( 'DOWN TO EARTH BARLEY WHOLE 500G', 'productPool/1.jpg', 91 ),
( 'DOWN TO EARTH BIRIYANI PULAV RICE 1KG', 'productPool/1.jpg', 194 ),
( 'DOWN TO EARTH BROWN SUGAR 1 KG', 'productPool/1.jpg', 174 ),
( 'DOWN TO EARTH BROWN SUGAR 500G', 'productPool/1.jpg', 202 ),
( 'DOWN TO EARTH CORIANDER POWDER 100G', 'productPool/1.jpg', 87 ),
( 'DOWN TO EARTH FLAXSEED 500G', 'productPool/1.jpg', 155 ),
( 'DOWN TO EARTH HONEY 250G', 'productPool/1.jpg', 233 ),
( 'DOWN TO EARTH HONEY 500G', 'productPool/1.jpg', 2 ),
( 'DOWN TO EARTH JAGGERY POWDER 500G', 'productPool/1.jpg', 131 ),
( 'DOWN TO EARTH ORGANIC CLOVE WHOLE 15G', 'productPool/1.jpg', 42 ),
( 'DOWN TO EARTH ORGANIC JAGGERY POWDER 500G', 'productPool/1.jpg', 127 ),
( 'DOWN TO EARTH RED CHILLI POWDER 100G', 'productPool/1.jpg', 68 ),
( 'DOWN TO EARTH WHITE SUGAR 500G', 'productPool/1.jpg', 241 ),
( 'DR BATRAS ACNE CLEAR FACE WASH 100G', 'productPool/1.jpg', 201 ),
( 'DR BATRAS ACNE CLEAR TULSI FW 50G', 'productPool/1.jpg', 127 ),
( 'DR BATRAS ALOE VERA HAND WASH 300ML', 'productPool/1.jpg', 164 ),
( 'DR BATRAS AMLA CONDITIONER 100ML', 'productPool/1.jpg', 169 ),
( 'DR BATRAS AMLA CONDITIONER 200ML', 'productPool/1.jpg', 112 ),
( 'DR BATRAS ANTI DANDRUFF HAIR SERUM125G', 'productPool/1.jpg', 278 ),
( 'DR BATRAS BATHING BAR BERBERIS 75G', 'productPool/1.jpg', 223 ),
( 'DR BATRAS BATHING BAR NEEM 125G', 'productPool/1.jpg', 142 ),
( 'DR BATRAS BATHING BAR PROTECTION 125G', 'productPool/1.jpg', 234 ),
( 'DR BATRAS BATHING BAR REFRESHING 125G', 'productPool/1.jpg', 239 ),
( 'DR BATRAS BATHING BAR REFRESHING 75G', 'productPool/1.jpg', 69 ),
( 'DR BATRAS DAILY CARE TEA TREE FW 100G', 'productPool/1.jpg', 114 ),
( 'DR BATRAS DAILY CARE TEA TREE FW 50G', 'productPool/1.jpg', 245 ),
( 'DR BATRAS DANDRUFF SHAMPOO THUJA 100ML', 'productPool/1.jpg', 5 ),
( 'DR BATRAS DANDRUFF SHAMPOO THUJA 200ML', 'productPool/1.jpg', 200 ),
( 'DR BATRAS DEODORANT OCEANIC BREEZE 150ML', 'productPool/1.jpg', 83 ),
( 'DR BATRAS DEODORANT ROSE-JASMINE-LILLY 150ML', 'productPool/1.jpg', 271 ),
( 'DR BATRAS FAIRNESS FACEWASH 100G', 'productPool/1.jpg', 129 ),
( 'DR BATRAS FOOT CARE CREAM BUTTER 100G', 'productPool/1.jpg', 90 ),
( 'DR BATRAS FOOT CARE CREAM BUTTER 50G', 'productPool/1.jpg', 67 ),
( 'DR BATRAS HAIR COLOUR CREAM BLACK', 'productPool/1.jpg', 68 ),
( 'DR BATRAS HAIR FALL CONTROL SHAMPOO 200ML', 'productPool/1.jpg', 1 ),
( 'DR BATRAS HAIR FALL SERUM 125ML', 'productPool/1.jpg', 48 ),
( 'DR BATRAS HAIR GEL WET LOOK THUJA 100G', 'productPool/1.jpg', 55 ),
( 'DR BATRAS HAND SANITIZER 100ML', 'productPool/1.jpg', 130 ),
( 'DR BATRAS INSTANT GLOW FACE WASH 100G', 'productPool/1.jpg', 227 ),
( 'DR BATRAS INSTANT GLOW FACE WASH 50G', 'productPool/1.jpg', 268 ),
( 'DR BATRAS JOJOBA HAIR OIL 100ML', 'productPool/1.jpg', 231 ),
( 'DR BATRAS JOJOBA HAIR OIL 200ML', 'productPool/1.jpg', 125 ),
( 'DR BATRAS MOISTURIZING ALOE VERA FW 50G', 'productPool/1.jpg', 235 ),
( 'DR BATRAS NATURAL ANTI ACNE CREAM 30G', 'productPool/1.jpg', 112 ),
( 'DR BATRAS NATURAL ANTI-ACNE CREAM 100G', 'productPool/1.jpg', 197 ),
( 'DR BATRAS NATURAL CLEANSING MILK 100ML', 'productPool/1.jpg', 52 ),
( 'DR BATRAS NATURAL MOISTURIZING LOTION 100ML', 'productPool/1.jpg', 16 ),
( 'DR BATRAS OIL CONTROL FACE WASH 100G', 'productPool/1.jpg', 152 ),
( 'DR BATRAS OIL CONTROL FACEWASH 50G', 'productPool/1.jpg', 38 ),
( 'DR BATRAS SHAMPOO HENNA 100ML', 'productPool/1.jpg', 130 ),
( 'DR BATRAS SHAMPOO HENNA 200ML', 'productPool/1.jpg', 92 ),
( 'DR BATRAS SKIN CLEAR ACNE CARE SOAP 75GM', 'productPool/1.jpg', 243 ),
( 'DR BATRAS SKIN TONER GREEN TEA 100ML', 'productPool/1.jpg', 27 ),
( 'DR BATRAS SUN PROTECTION CREAM FW 100G', 'productPool/1.jpg', 197 ),
( 'DR BATTAS MOISTURIZING FACE WASH 100G', 'productPool/1.jpg', 165 ),
( 'DR BNATRAS BATHING BAR PROTECTION 75G', 'productPool/1.jpg', 162 ),
( 'DR BRIGHT WASHING SOAP 200G', 'productPool/1.jpg', 39 ),
( 'DR MEDI GLOW WASHING SOAP 200G', 'productPool/1.jpg', 122 ),
( 'DR WASH BUY 1 GET 1 300ML', 'productPool/1.jpg', 267 ),
( 'DR WASH COMBI 250G*3', 'productPool/1.jpg', 210 ),
( 'DR WASH DETERGENT POWDER 1 KG', 'productPool/1.jpg', 105 ),
( 'DR WASH DETERGENT POWDER 2 KG', 'productPool/1.jpg', 73 ),
( 'DR WASH HAND WASH FRUITY 225ML', 'productPool/1.jpg', 120 ),
( 'DR WASH HAND WASH NEEM 300ML', 'productPool/1.jpg', 142 ),
( 'DR WASH PARDA WASH 200ML', 'productPool/1.jpg', 178 ),
( 'DR WASH WASHING POWDER 1.5KG', 'productPool/1.jpg', 135 ),
( 'DR WASH WASHING SOAP 200G', 'productPool/1.jpg', 174 ),
( 'DR WASH WASHING SOAP COMBI', 'productPool/1.jpg', 248 ),
( 'DRAGON FRUITS (VIETNAM)', 'productPool/1.jpg', 70 ),
( 'DRINKING CHOCOLATE 100G', 'productPool/1.jpg', 37 ),
( 'DRINKO BASIL SEED DRINK 290ML', 'productPool/1.jpg', 214 ),
( 'DROLLS DISHA PATCNI3KG', 'productPool/1.jpg', 215 ),
( 'DRONN DRAINAGE BLOCK CLEANER 200GM', 'productPool/1.jpg', 9 ),
( 'DROOLS ADULT NUTRITION 1.2KG', 'productPool/1.jpg', 125 ),
( 'DROOLS ADULT NUTRITION 100G', 'productPool/1.jpg', 192 ),
( 'DROOLS ADULT NUTRITION 3KG', 'productPool/1.jpg', 250 ),
( 'DROOLS ADULT NUTRITION 400G', 'productPool/1.jpg', 210 ),
( 'DROOLS ADULT NUTRITION 6KG', 'productPool/1.jpg', 159 ),
( 'DROOLS ADULT POUCH 80G', 'productPool/1.jpg', 80 ),
( 'DROOLS ADULT POUCH RS 25', 'productPool/1.jpg', 214 ),
( 'DROOLS CAT FOOD 3KG', 'productPool/1.jpg', 131 ),
( 'DROOLS CAT FOOD 400G', 'productPool/1.jpg', 141 ),
( 'DROOLS CAT FOOD COMPLETE NUTRITION 1.2KG', 'productPool/1.jpg', 223 ),
( 'DROOLS CAT FOOD KITTEN NUTRITION 1.2KG', 'productPool/1.jpg', 210 ),
( 'DROOLS KITTEN NUTRITION 400G', 'productPool/1.jpg', 51 ),
( 'DROOLS LETS BITE ACTIVE PUPPY 3KG', 'productPool/1.jpg', 164 ),
( 'DROOLS PUPPY 6.5KG', 'productPool/1.jpg', 123 ),
( 'DROOLS PUPPY NUTRIRION 400GM', 'productPool/1.jpg', 33 ),
( 'DROOLS PUPPY NUTRITIAN 3KG', 'productPool/1.jpg', 210 ),
( 'DROOLS PUPPY NUTRITION 1.2 K', 'productPool/1.jpg', 190 ),
( 'DROOLS PUPPY NUTRITION 3KG', 'productPool/1.jpg', 258 ),
( 'DROOLS PUPPY NUTRITION POUCH 150G', 'productPool/1.jpg', 258 ),
( 'DROOLS PUPPY POUCH 80G', 'productPool/1.jpg', 133 ),
( 'DROOLS PUPPY WELL FED 100GM', 'productPool/1.jpg', 42 ),
( 'DROOLS PUREPET BISCUIT 500G', 'productPool/1.jpg', 158 ),
( 'DROOLS PUREPET BISCUIT 500GM', 'productPool/1.jpg', 133 ),
( 'DRUK BAKED BEANS 450G', 'productPool/1.jpg', 129 ),
( 'DRUK NANNARI SYRUP 700ML', 'productPool/1.jpg', 58 ),
( 'DRUK SWEET CORN 450G', 'productPool/1.jpg', 53 ),
( 'DRUMSTICK', 'productPool/1.jpg', 158 ),
( 'DRY APRICOT 100G', 'productPool/1.jpg', 141 ),
( 'DRY FRUIT HALWA 1KG', 'productPool/1.jpg', 141 ),
( 'DRY FRUITS HALWA 500G', 'productPool/1.jpg', 82 ),
( 'DRY GRAPE CORDIAL', 'productPool/1.jpg', 153 ),
( 'DRY KISMIS', 'productPool/1.jpg', 228 ),
( 'DTE AJWAIN 100G', 'productPool/1.jpg', 182 ),
( 'DTE BLACK SALT 50G', 'productPool/1.jpg', 237 ),
( 'DTE CHANA WHOLE 500G', 'productPool/1.jpg', 134 ),
( 'DTE CINNAMON STICK 25G', 'productPool/1.jpg', 254 ),
( 'DTE CORIANDER WHOLE 75G', 'productPool/1.jpg', 50 ),
( 'DTE FENUGRREEK 100G', 'productPool/1.jpg', 174 ),
( 'DTE FLAX SEED 250G', 'productPool/1.jpg', 2 ),
( 'DTE GREEN CARDMOM WHOLE 20G', 'productPool/1.jpg', 198 ),
( 'DTE HONEY 250G', 'productPool/1.jpg', 75 ),
( 'DTE MOONG WHOLE 1 KG', 'productPool/1.jpg', 36 ),
( 'DTE MOONG WHOLE 500G', 'productPool/1.jpg', 185 ),
( 'DTE MUSTARD BLACK100G', 'productPool/1.jpg', 256 ),
( 'DTE ORAGANIC DESI CHANA 500G', 'productPool/1.jpg', 113 ),
( 'DTE ORGANIC ARHAR DAL 1 KG', 'productPool/1.jpg', 199 ),
( 'DTE ORGANIC COW GHEE 250ML', 'productPool/1.jpg', 211 ),
( 'DTE ORGANIC CUMIN WHOLE 100G', 'productPool/1.jpg', 263 ),
( 'DTE ORGANIC GROUNDNUT 500G', 'productPool/1.jpg', 76 ),
( 'DTE ORGANIC KASHMIRI LAL MIRCH POWDER 250G', 'productPool/1.jpg', 160 ),
( 'DTE ORGANIC KASMIRI LAL MIRCH POWDER 100G', 'productPool/1.jpg', 28 ),
( 'DTE ORGANIC VERMICELLI 250G', 'productPool/1.jpg', 153 ),
( 'DTE PEANUTS 250G', 'productPool/1.jpg', 77 ),
( 'DTE PEANUTS 500G', 'productPool/1.jpg', 255 ),
( 'DTE PENNE PASTA 500G', 'productPool/1.jpg', 119 ),
( 'DTE ROCK SALT 1 KG', 'productPool/1.jpg', 38 ),
( 'DTE SESAME BLACK NATURAL 75G', 'productPool/1.jpg', 225 ),
( 'DTE SOYBEAN WHOLE 500G', 'productPool/1.jpg', 48 ),
( 'DTE SUGAR BROWN 1 KG', 'productPool/1.jpg', 207 );