INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'SPOTZERO SHUBHRA GRASS BROOM', 'productPool/1.jpg', 102 ),
( 'SPOTZERO SLENDER FLOOR WIPER', 'productPool/1.jpg', 151 ),
( 'SPOTZERO SUPER CLOTH BRUSH 1S', 'productPool/1.jpg', 57 ),
( 'SPOTZERO TOILET BRUSH -ROUND', 'productPool/1.jpg', 183 ),
( 'SPOTZERO TOILET BRUSH OVAL', 'productPool/1.jpg', 120 ),
( 'SPOTZERO TOILET BRUSH WITH CADDY ROUND', 'productPool/1.jpg', 135 ),
( 'SPOTZERO TUFF FLOOR SCRUBBER', 'productPool/1.jpg', 101 ),
( 'SPOTZERO TWIST-SQUEEZE MICROFIBER MOP', 'productPool/1.jpg', 249 ),
( 'SPOTZERO TWIST-SQUEEZE MICROFIBER PREMIUM MOP', 'productPool/1.jpg', 117 ),
( 'SPOTZERO WEB BLASTER (JALA BROOM)', 'productPool/1.jpg', 249 ),
( 'SPOTZERO YOGA BROOM', 'productPool/1.jpg', 36 ),
( 'SPRING ONION', 'productPool/1.jpg', 237 ),
( 'SPRITE 300ML CAN', 'productPool/1.jpg', 218 ),
( 'SPRITE 330ML', 'productPool/1.jpg', 146 ),
( 'SPRITE ZERO 300ML CAN', 'productPool/1.jpg', 30 ),
( 'SREE KRISHNA COTTON WICK', 'productPool/1.jpg', 121 ),
( 'SREEDHAREEYAM HERBAL BABY KAJAL 3G', 'productPool/1.jpg', 202 ),
( 'SREEDHAREEYAM HERBALBABYKAJAL3 G', 'productPool/1.jpg', 268 ),
( 'SREEMATHYS GARAM MASALAKOOTU 100G', 'productPool/1.jpg', 185 ),
( 'SREEMATHYS ROASTED CASHEW 100G', 'productPool/1.jpg', 244 ),
( 'SS EASY STYLE 350 ML', 'productPool/1.jpg', 266 ),
( 'SS EASY STYLE 500ML', 'productPool/1.jpg', 150 ),
( 'SS PEELER', 'productPool/1.jpg', 33 ),
( 'SSJ MUMTAZ NATURAL FIG 400G', 'productPool/1.jpg', 119 ),
( 'SSK ORANGE RICE', 'productPool/1.jpg', 1 ),
( 'ST JOHN BLACK SEA50ML', 'productPool/1.jpg', 144 ),
( 'ST MARYS WHITE CANDLE', 'productPool/1.jpg', 176 ),
( 'ST THOMAS CANDLES 6NOS', 'productPool/1.jpg', 27 ),
( 'STAEDTLER BALL PEN 432 M', 'productPool/1.jpg', 195 ),
( 'STAEDTLER LUNA ERASER MRP30', 'productPool/1.jpg', 11 ),
( 'STAEDTLER LUNA OIL PASTELS 12S', 'productPool/1.jpg', 192 ),
( 'STAETA SOY MILKY NATURAL 1L', 'productPool/1.jpg', 157 ),
( 'STAETA SOY MILKY ORIGINAL 1L', 'productPool/1.jpg', 157 ),
( 'STAR 5000 PERFUME', 'productPool/1.jpg', 25 ),
( 'STAR 60 STICK BROOM', 'productPool/1.jpg', 92 ),
( 'STAR ALUMINIUM FOIL 9M', 'productPool/1.jpg', 45 ),
( 'STAR DRAGEE SWEET BALL', 'productPool/1.jpg', 120 ),
( 'STAR DUST PAN FAMILY', 'productPool/1.jpg', 124 ),
( 'STAR KENZ 50ML', 'productPool/1.jpg', 95 ),
( 'STAR SOAP BOX', 'productPool/1.jpg', 1 ),
( 'STAR SWEET BALL', 'productPool/1.jpg', 60 ),
( 'STAY FREE ADVANCED UT XL 14S', 'productPool/1.jpg', 97 ),
( 'STAY FREE ADVANCED XL 7S', 'productPool/1.jpg', 44 ),
( 'STAY FREE DRY MAX 8', 'productPool/1.jpg', 264 ),
( 'STAY FREE DRY MAX ALL NIGHT 14S', 'productPool/1.jpg', 190 ),
( 'STAY FREE DRY MAX ALL NIGHT 28S MEDIUM', 'productPool/1.jpg', 15 ),
( 'STAY FREE DRY MAX XL 7S', 'productPool/1.jpg', 11 ),
( 'STAY FREE SECURE COTTONY REGULAR 8S', 'productPool/1.jpg', 158 ),
( 'STAY FREE SECURE WINGS 8S', 'productPool/1.jpg', 37 ),
( 'STAYFREE ADVANCED ALL NIGHT 7S', 'productPool/1.jpg', 127 ),
( 'STAYFREE ADVANCED ALL NIGHT ULTRA XL 7N', 'productPool/1.jpg', 82 ),
( 'STAYFREE ADVANCED XL 14', 'productPool/1.jpg', 153 ),
( 'STAYFREE COTTON SOFT 20', 'productPool/1.jpg', 202 ),
( 'STAYFREE COTTONY REGULAR 7S', 'productPool/1.jpg', 179 ),
( 'STAYFREE DRY ALL NIGHT 7', 'productPool/1.jpg', 12 ),
( 'STAYFREE DRY MAX ALL NIGHT 28N', 'productPool/1.jpg', 213 ),
( 'STAYFREE DRY MAX ALL NIGHT 7S', 'productPool/1.jpg', 7 ),
( 'STAYFREE DRY MAX ALL NIGHT XL 14N', 'productPool/1.jpg', 256 ),
( 'STAYFREE DRY MAX ULTRA DRY 8N', 'productPool/1.jpg', 65 ),
( 'STAYFREE DRY-MAX 8S', 'productPool/1.jpg', 170 ),
( 'STAYFREE DRYMAX 16', 'productPool/1.jpg', 224 ),
( 'STAYFREE DRYMAX 16S', 'productPool/1.jpg', 107 ),
( 'STAYFREE SECURE COTTONY 20+2 PCS', 'productPool/1.jpg', 163 ),
( 'STAYFREE SECURE DRY 7 XL', 'productPool/1.jpg', 39 ),
( 'STAYFREE SECURE DRY XL 10S', 'productPool/1.jpg', 24 ),
( 'STAYFREE SECURE DRY XL WINGS 6S', 'productPool/1.jpg', 180 ),
( 'STAYFREE SECURE EXTRA LARGE 12P', 'productPool/1.jpg', 206 ),
( 'STAYFREE SECURE EXTRA LARGE 40N', 'productPool/1.jpg', 15 ),
( 'STAYFREE SECURE EXTRA LARGE 6S', 'productPool/1.jpg', 155 ),
( 'STAYFREE SECURE REGULAR 7S', 'productPool/1.jpg', 91 ),
( 'STAYFREE SECURE REGULAR 8S', 'productPool/1.jpg', 196 ),
( 'STAYFREE SECURE XL 20S', 'productPool/1.jpg', 77 ),
( 'STAYFREE SECURE XL 20S + XL COTTONY FREE', 'productPool/1.jpg', 59 ),
( 'STAYFREE SECURE XL 40N', 'productPool/1.jpg', 269 ),
( 'STAYFREE SECURE XL DRY 7PADS', 'productPool/1.jpg', 118 ),
( 'STAYFREE SECURE XL ULTRA THIN 10N', 'productPool/1.jpg', 28 ),
( 'STAYFREE SECURE XL ULTRATHIN 6S', 'productPool/1.jpg', 215 ),
( 'STAYFREE ULTRA COMFORT XL 7N', 'productPool/1.jpg', 206 ),
( 'STAYFREE XL WINGS 7S', 'productPool/1.jpg', 199 ),
( 'STEEL CORE 10MTS', 'productPool/1.jpg', 184 ),
( 'STEEL CORE ROPE 15 MTS', 'productPool/1.jpg', 272 ),
( 'STEEL HANGER', 'productPool/1.jpg', 23 ),
( 'STEEL MUG JUNIOR', 'productPool/1.jpg', 96 ),
( 'STEEL PAKKAD BIG', 'productPool/1.jpg', 77 ),
( 'STEEL TONGUE CLEANER', 'productPool/1.jpg', 77 ),
( 'STEELGRIP SUPER', 'productPool/1.jpg', 159 ),
( 'STEELGRIP SUPER RED', 'productPool/1.jpg', 5 ),
( 'STEP IN 2 PEDAL DUST BIN FAMILY', 'productPool/1.jpg', 78 ),
( 'STICKY FILE SF810', 'productPool/1.jpg', 150 ),
( 'STING BERRY DRINK 250ML', 'productPool/1.jpg', 96 ),
( 'STING ENERGY DRINK 250ML CAN', 'productPool/1.jpg', 79 ),
( 'STOFF BROOM V CUT', 'productPool/1.jpg', 157 ),
( 'STOFF CEILING BROOM', 'productPool/1.jpg', 271 ),
( 'STOFF CEILING FAN CLEANER', 'productPool/1.jpg', 46 ),
( 'STOFF FRUIT PLUCKER BIG', 'productPool/1.jpg', 269 ),
( 'STOFF FRUIT PLUCKER SMALL', 'productPool/1.jpg', 151 ),
( 'STOFF KITCHEN KNIFE SKACC SP0024', 'productPool/1.jpg', 195 ),
( 'STOFF KITCHEN KNIFE SKRB SP0016', 'productPool/1.jpg', 109 ),
( 'STOFF KITCHEN KNIFE SKVJP-BP', 'productPool/1.jpg', 156 ),
( 'STOFF KITCHEN KNIFE SKVJR BP', 'productPool/1.jpg', 266 ),
( 'STOFF KITCHEN KNIFE SKVJR SP0001', 'productPool/1.jpg', 26 ),
( 'STOFF KITCHEN KNIFE SKVJR SP001', 'productPool/1.jpg', 234 ),
( 'STOFF KITCHEN KNIFE SKVOP SP0010', 'productPool/1.jpg', 189 ),
( 'STOFF KITCHEN KNIFE SKVPE SP006', 'productPool/1.jpg', 185 ),
( 'STOFF KITCHEN KNIFE SKVPE-BP', 'productPool/1.jpg', 225 ),
( 'STOFF KITCHEN KNIFE SKVR SP0014', 'productPool/1.jpg', 226 ),
( 'STOFF KITCHEN KNIFE SKVR-BP', 'productPool/1.jpg', 76 ),
( 'STOFF KITCHEN KNIFE SKVRE SP005', 'productPool/1.jpg', 12 ),
( 'STOFF KITCHEN KNIFE SKVRE-BP', 'productPool/1.jpg', 258 ),
( 'STOFF KITCHEN KNIFE SKVREW SP0021', 'productPool/1.jpg', 210 ),
( 'STOFF KITCHEN KNIFE SKVREW-BP', 'productPool/1.jpg', 47 ),
( 'STOFF KITCHEN KNIFE SKVRS-BP', 'productPool/1.jpg', 47 ),
( 'STOFF KITCHEN KNIFE SKVRW SP0017', 'productPool/1.jpg', 254 ),
( 'STOFF KITCHEN KNIFE SKVRW-BP', 'productPool/1.jpg', 143 ),
( 'STOFF KITCHEN KNIFE SKVW SP0019', 'productPool/1.jpg', 217 ),
( 'STOFF KITCHEN SCISSOR MEDIUM SP-554', 'productPool/1.jpg', 21 ),
( 'STOFF SCISSOR SMALL SP-551', 'productPool/1.jpg', 82 ),
( 'STOFF SCISSORS MEDIUM SP-552', 'productPool/1.jpg', 145 ),
( 'STOFF WHITE BROOM', 'productPool/1.jpg', 278 ),
( 'STOP O POWER BAG LEMONGRASS 10G', 'productPool/1.jpg', 100 ),
( 'STOP O POWER BAG MELON 10G', 'productPool/1.jpg', 153 ),
( 'STOP O POWER BAG TANGERINE 10G', 'productPool/1.jpg', 264 ),
( 'STOP-OSTOPS ODOUR POWER BAG APPLE10G', 'productPool/1.jpg', 121 ),
( 'STRATEGI ANT REPELLENT 100ML', 'productPool/1.jpg', 73 ),
( 'STRATEGI BATHROOM CLENER 500ML', 'productPool/1.jpg', 213 ),
( 'STRATEGI BED BUG REPELLENT SPRAY 100ML', 'productPool/1.jpg', 152 ),
( 'STRATEGI GLASS CLEANER SPRAY 500ML', 'productPool/1.jpg', 96 ),
( 'STRATEGI HERBAL COCKROACH REPELLENT', 'productPool/1.jpg', 99 ),
( 'STRATEGI HERBAL DISH WASH 250ML', 'productPool/1.jpg', 143 ),
( 'STRATEGI HERBAL DISH WASH 500ML', 'productPool/1.jpg', 54 ),
( 'STRATEGI HERBAL FOAM HAND WASH 150ML', 'productPool/1.jpg', 263 ),
( 'STRATEGI HERBAL HOUSEFLY REPELLENT 100ML', 'productPool/1.jpg', 208 ),
( 'STRATEGI HERBAL LIZARD REPELLENT 100ML', 'productPool/1.jpg', 13 ),
( 'STRATEGI HERBAL MOSQUITO REPELLENT 100ML', 'productPool/1.jpg', 143 ),
( 'STRATEGI JUSTMOP FLOOR CLEANER 500ML', 'productPool/1.jpg', 141 ),
( 'STRATEGI KITCHEN CLEANER 500ML', 'productPool/1.jpg', 112 ),
( 'STRATEGI LAVENDER INCENSE 20STICKS', 'productPool/1.jpg', 52 ),
( 'STRATEGI LAVENDER ROOM FRESHNER 250ML', 'productPool/1.jpg', 258 ),
( 'STRATEGI LEMON ROOM FRESHNER 250ML', 'productPool/1.jpg', 32 ),
( 'STRATEGI MOSQUITO SPRAY 100ML', 'productPool/1.jpg', 226 ),
( 'STRATEGI MOSQUITO VAPORIZER 40ML', 'productPool/1.jpg', 64 ),
( 'STRATEGI MOSTICK 40STICKS', 'productPool/1.jpg', 90 ),
( 'STRATEGI NATURAL FABRIC WASH 500ML', 'productPool/1.jpg', 97 ),
( 'STRATEGI NATURESPRAY WHITE LILY 250ML', 'productPool/1.jpg', 109 ),
( 'STRATEGI RAT REPELLENT 50G', 'productPool/1.jpg', 158 ),
( 'STRATEGI ROSE ROOM FRESHNER 250ML', 'productPool/1.jpg', 235 ),
( 'STRATEGI SANDAL INCENSE STICK 20N', 'productPool/1.jpg', 39 ),
( 'STRATEGI SANDAL ROOM FRESHNER 250ML', 'productPool/1.jpg', 20 ),
( 'STRATEGI TERMITE REPELLENT 100ML', 'productPool/1.jpg', 100 ),
( 'STRATEGI TOILET BATHROOM CLEANER 500ML', 'productPool/1.jpg', 153 ),
( 'STRATEGI YESPRAY DOG SPRAY 200ML', 'productPool/1.jpg', 210 ),
( 'STRAW', 'productPool/1.jpg', 25 ),
( 'STRAWBERRY', 'productPool/1.jpg', 59 ),
( 'STRAWBERRY DRIED 100G', 'productPool/1.jpg', 92 ),
( 'STRAWBERRY MIX POWDER 80G', 'productPool/1.jpg', 19 ),
( 'STRAWBERRY SKORE CONDOMS80R', 'productPool/1.jpg', 145 ),
( 'STRAWBERY MOOSE', 'productPool/1.jpg', 74 ),
( 'STREAK INSTA BURGUNDY 3.16 HAIR COLOR', 'productPool/1.jpg', 253 ),
( 'STREAX BODY MIST CLUB 100ML', 'productPool/1.jpg', 78 ),
( 'STREAX BODY MIST DERBY 100ML', 'productPool/1.jpg', 175 ),
( 'STREAX BODY MIST GLAM 100ML', 'productPool/1.jpg', 158 ),
( 'STREAX BODY MIST LILY VANILA 100ML', 'productPool/1.jpg', 82 ),
( 'STREAX HAIR COLOR NO.3 DARK BROWN', 'productPool/1.jpg', 236 ),
( 'STREAX HAIR COLOUR 1 NATURAL BLACK 120ML', 'productPool/1.jpg', 231 ),
( 'STREAX HAIR COLOUR 3 DARK BROWN 120ML', 'productPool/1.jpg', 266 ),
( 'STREAX HAIR COLOUR 50ML BURGANDY', 'productPool/1.jpg', 143 ),
( 'STREAX HAIR COLOUR NO.1 NATURAL BLACK', 'productPool/1.jpg', 222 ),
( 'STREAX HAIR COLOUR SACHET', 'productPool/1.jpg', 123 ),
( 'STREAX HAIR SERUM 100ML', 'productPool/1.jpg', 178 ),
( 'STREAX HAIR SERUM 45ML', 'productPool/1.jpg', 228 ),
( 'STREAX HAIRCOLOUR 3.16 BURGUNDY 120ML', 'productPool/1.jpg', 196 ),
( 'STREAX INSTA HAIR COLOUR DARK BROWN 3', 'productPool/1.jpg', 247 ),
( 'STREAX INSTA HAIR COLOUR SHAMPOO 12.5ML', 'productPool/1.jpg', 155 ),
( 'STREAX INSTA NATURAL BLACK COLOUR 30ML', 'productPool/1.jpg', 22 ),
( 'STREAX INSTA SHAMPOO HAIR COLOUR BLACK 13ML', 'productPool/1.jpg', 165 ),
( 'STREAX INSTA SHAMPOOHAIR COLOUR7.5ML', 'productPool/1.jpg', 137 ),
( 'STREAX ORIENT BLOSSOM BODY MIST100ML', 'productPool/1.jpg', 147 ),
( 'STREAX PEACH BODY MIST100ML', 'productPool/1.jpg', 243 ),
( 'STREAX PRO HAIR SERUM100ML', 'productPool/1.jpg', 6 ),
( 'STRENGTH PLUS 400 GM', 'productPool/1.jpg', 173 ),
( 'STRENGTH PLUS 400G', 'productPool/1.jpg', 273 ),
( 'STRUDEL CHICKEN PIE', 'productPool/1.jpg', 40 ),
( 'STRUDEL MEAT PIE', 'productPool/1.jpg', 246 ),
( 'STRUDEL VEGETABLE PIE', 'productPool/1.jpg', 35 ),
( 'STYLE SAFETY PIN', 'productPool/1.jpg', 39 ),
( 'SU SWAD CHURUT 10NOS', 'productPool/1.jpg', 142 ),
( 'SU SWAD KUZHALAPPAM 150G', 'productPool/1.jpg', 275 ),
( 'SUGANDA KUMKUM 20G', 'productPool/1.jpg', 218 ),
( 'SUGAR 1KG', 'productPool/1.jpg', 106 ),
( 'SUGAR 2 KG', 'productPool/1.jpg', 92 ),
( 'SUGAR 2KG', 'productPool/1.jpg', 154 ),
( 'SUGAR BAG', 'productPool/1.jpg', 117 ),
( 'SUGAR CUBE', 'productPool/1.jpg', 191 ),
( 'SUGAR FREE GOLD 100G JAR', 'productPool/1.jpg', 133 ),
( 'SUGAR FREE GOLD 110 PELLET', 'productPool/1.jpg', 33 ),
( 'SUGAR FREE GOLD 300 PELLET', 'productPool/1.jpg', 159 ),
( 'SUGAR FREE GOLD 50 SACHETS', 'productPool/1.jpg', 139 ),
( 'SUGAR FREE GOLD 500 PELLET', 'productPool/1.jpg', 111 ),
( 'SUGAR FREE GREEN 100 PELLETS', 'productPool/1.jpg', 248 ),
( 'SUGAR FREE GREEN 100G JAR', 'productPool/1.jpg', 76 ),
( 'SUGAR FREE GREEN 40 PELLETS', 'productPool/1.jpg', 268 ),
( 'SUGAR FREE NATURA 100 TABLET', 'productPool/1.jpg', 214 ),
( 'SUGAR FREE NATURA 100G', 'productPool/1.jpg', 173 ),
( 'SUGAR FREE NATURA 200 TABLET', 'productPool/1.jpg', 106 ),
( 'SUGAR FREE NATURA 300 PELLETS', 'productPool/1.jpg', 274 ),
( 'SUGAR FREE NATURA 300 TABLET', 'productPool/1.jpg', 132 ),
( 'SUGAR FREE NATURA 500 PELLETS', 'productPool/1.jpg', 167 ),
( 'SUGAR FREE NATURA SACHET 100N', 'productPool/1.jpg', 192 ),
( 'SUGAR FREE NATURA SACHET 50N', 'productPool/1.jpg', 266 ),
( 'SUGAR FREE SUGARLITE SUGAR 500G POUCH', 'productPool/1.jpg', 268 ),
( 'SUGARFREE SHARBHAT LITCHI 300GM', 'productPool/1.jpg', 172 ),
( 'SUGARLESS KALA JAMUN 300G', 'productPool/1.jpg', 10 ),
( 'SUGERFREE NATURA 500 TABLET', 'productPool/1.jpg', 10 ),
( 'SUGERFREE NATURA SWEET DROPS', 'productPool/1.jpg', 18 ),
( 'SUGUNA BONELESS CHICKEN LEG', 'productPool/1.jpg', 231 ),
( 'SUGUNA CHICKEN CURRY CUT 450G', 'productPool/1.jpg', 93 ),
( 'SUGUNA CHICKEN CURRYCUT SKINLESS', 'productPool/1.jpg', 221 ),
( 'SUGUNA CHICKEN LIVER 45GM', 'productPool/1.jpg', 269 ),
( 'SUMERU CHEESE CORN NUGGETS 200G', 'productPool/1.jpg', 24 ),
( 'SUMERU CHEESE POPZ 200G', 'productPool/1.jpg', 238 ),
( 'SUMERU CHICKEN BREAKFAST SAUSAGE 200G', 'productPool/1.jpg', 92 ),
( 'SUMERU CHICKEN BURGER PATTY 300G', 'productPool/1.jpg', 162 ),
( 'SUMERU CHICKEN CHEESE SAUSAGE 200G', 'productPool/1.jpg', 102 ),
( 'SUMERU CHICKEN KABABI SAUSAGE 200G', 'productPool/1.jpg', 55 ),
( 'SUMERU CHICKEN NUGGETS 450G', 'productPool/1.jpg', 166 ),
( 'SUMERU CHICKEN POPS PIRI PIRI 450G', 'productPool/1.jpg', 185 ),
( 'SUMERU CHICKEN SMOKED SAUSAGE 200G', 'productPool/1.jpg', 198 ),
( 'SUMERU FRENCH FRIES', 'productPool/1.jpg', 238 ),
( 'SUMERU FRENCH FRIES CHICKEN GARLIC 250G', 'productPool/1.jpg', 140 ),
( 'SUMERU FRENCH FRIES CHICKEN TANDOORI 250G', 'productPool/1.jpg', 200 ),
( 'SUMERU FRENCH FRIES CHILLY GARLIC 400 GMS', 'productPool/1.jpg', 4 ),
( 'SUMERU FRENCH FRIES PUNJABI TADKA 400G', 'productPool/1.jpg', 154 ),
( 'SUMERU GRATED COCONUT 200 GMS', 'productPool/1.jpg', 264 ),
( 'SUMERU MALAI PANEER 200G', 'productPool/1.jpg', 88 ),
( 'SUMERU SWITZ SAMOOSA SHEET 50N', 'productPool/1.jpg', 19 ),
( 'SUMERU VEGGIE BURGER PARTY 360G', 'productPool/1.jpg', 257 ),
( 'SUMERU WASSUP CHICKEN SALAMI', 'productPool/1.jpg', 16 ),
( 'SUMO SPOON 100P', 'productPool/1.jpg', 160 ),
( 'SUN PEANUT BUTTER 200G', 'productPool/1.jpg', 88 ),
( 'SUN PLUS WASHING POWDER 1KG', 'productPool/1.jpg', 247 ),
( 'SUN PLUS WASHING POWDER 500G', 'productPool/1.jpg', 246 ),
( 'SUN RICH REFINED SUNFLOWER OIL 2LTR', 'productPool/1.jpg', 31 ),
( 'SUN RICH SUNFLOWER OIL 5 LTR', 'productPool/1.jpg', 73 ),
( 'SUNDAE CHOOCOLATE', 'productPool/1.jpg', 274 ),
( 'SUNDEFENS CREAM 60G', 'productPool/1.jpg', 267 ),
( 'SUNDROP CHEESE POPCORN COMBI', 'productPool/1.jpg', 106 ),
( 'SUNDROP GOLDLITE OIL 1L', 'productPool/1.jpg', 151 ),
( 'SUNDROP HEALTHY OIL 1L', 'productPool/1.jpg', 137 ),
( 'SUNDROP HEALTHY WORLD RICE BRAN OIL 1L', 'productPool/1.jpg', 220 ),
( 'SUNDROP HEART OIL 1L', 'productPool/1.jpg', 181 ),
( 'SUNDROP NUTILITE 1L', 'productPool/1.jpg', 19 ),
( 'SUNDROP OIL 1L', 'productPool/1.jpg', 223 ),
( 'SUNDROP PEANUT BUTTER CREAMY 100G', 'productPool/1.jpg', 273 ),
( 'SUNDROP PEANUT BUTTER CREAMY 200G', 'productPool/1.jpg', 137 ),
( 'SUNDROP PEANUT BUTTER CREAMY 462G', 'productPool/1.jpg', 44 ),
( 'SUNDROP PEANUT BUTTER CREAMY925G', 'productPool/1.jpg', 173 ),
( 'SUNDROP PEANUT BUTTER CRUNCHY 100G', 'productPool/1.jpg', 198 ),
( 'SUNDROP PEANUT BUTTER CRUNCHY 200G', 'productPool/1.jpg', 16 ),
( 'SUNDROP PEANUT BUTTER JELLY 340G', 'productPool/1.jpg', 222 ),
( 'SUNDROP PEANUT BUTTER R.CRUNCHY 462G', 'productPool/1.jpg', 150 ),
( 'SUNDROP PEANUT SPREAD CREAMY 100G', 'productPool/1.jpg', 174 ),
( 'SUNDROP PEANUT SPREAD CREAMY 200G', 'productPool/1.jpg', 260 ),
( 'SUNDROP PEANUT SPREAD CRUNCHY 100G', 'productPool/1.jpg', 111 ),
( 'SUNDROP PEANUT SPREAD HR.CRUNCHY 462G', 'productPool/1.jpg', 120 ),
( 'SUNDROP SPREAD HONEY ROAST CREAMY 425G', 'productPool/1.jpg', 143 ),
( 'SUNDROP SUPERLITE OIL 3LITRE', 'productPool/1.jpg', 76 ),
( 'SUNDROPPEANUTBUTTERCRUNCHY 924G', 'productPool/1.jpg', 113 ),
( 'SUNFEAST BOUNCE CHOCO TWIST 100G', 'productPool/1.jpg', 102 ),
( 'SUNFEAST BOUNCE DREAM CREAM BUTTERSCOTCH 120G', 'productPool/1.jpg', 76 ),
( 'SUNFEAST BOUNCE DREAM CREAM CHOCO VANILA 120G', 'productPool/1.jpg', 252 ),
( 'SUNFEAST BOUNCE DREAM CREAM STRAWBERRY 120G', 'productPool/1.jpg', 35 ),
( 'SUNFEAST BOUNCE ELAICHI DELIGHT100G', 'productPool/1.jpg', 178 ),
( 'SUNFEAST BOUNCE MINIS STRAWBERRY 25G', 'productPool/1.jpg', 104 ),
( 'SUNFEAST BOUNCE PINEAPPLE ZING 100G', 'productPool/1.jpg', 90 ),
( 'SUNFEAST BOUNCE TANGY ORANGE CB 100G', 'productPool/1.jpg', 215 ),
( 'SUNFEAST BOURBON BLISS 120G', 'productPool/1.jpg', 246 ),
( 'SUNFEAST BOURBON BLISS 150G', 'productPool/1.jpg', 27 ),
( 'SUNFEAST DAIRY WHITENER 200G', 'productPool/1.jpg', 66 ),
( 'SUNFEAST DAIRY WHITENER 30G', 'productPool/1.jpg', 42 ),
( 'SUNFEAST DAIRY WHITENER 400G', 'productPool/1.jpg', 32 ),
( 'SUNFEAST DARK FANTASY COFFEE FILLS 75 GMS', 'productPool/1.jpg', 45 ),
( 'SUNFEAST DARK FANTASY ORANGE 76.8G', 'productPool/1.jpg', 120 ),
( 'SUNFEAST DARK FANTASY STRAWBERRY 76.8G', 'productPool/1.jpg', 240 ),
( 'SUNFEAST DARK FANTASY YUMFILLS 138G', 'productPool/1.jpg', 102 ),
( 'SUNFEAST DARK FANTASY YUMFILLS CAKE 138G', 'productPool/1.jpg', 7 ),
( 'SUNFEAST DARK FANTASY YUMFILLS CAKE 414G', 'productPool/1.jpg', 192 ),
( 'SUNFEAST DELISHUS GHANA CHOCO CHIP COOKIES', 'productPool/1.jpg', 209 ),
( 'SUNFEAST DELISHUS NUT BISCOTTI 75G', 'productPool/1.jpg', 130 ),
( 'SUNFEAST DELISHUS NUTS RAISINS 75G', 'productPool/1.jpg', 174 ),
( 'SUNFEAST DREAM CREAM BUTTER SCOTCH 120G', 'productPool/1.jpg', 208 ),
( 'SUNFEAST DREAM CREAM CHOCO VANILA (120+30)GMS', 'productPool/1.jpg', 179 ),
( 'SUNFEAST DREAM CREAM STRAWBERRY 120G', 'productPool/1.jpg', 178 ),
( 'SUNFEAST GLUCOSE BISCUITS 128G', 'productPool/1.jpg', 55 ),
( 'SUNFEAST GLUCOSE BISCUITS 250GMS', 'productPool/1.jpg', 261 ),
( 'SUNFEAST MARI LIGHT VITA 150G', 'productPool/1.jpg', 210 ),
( 'SUNFEAST MARI LIGHT VITA 300G', 'productPool/1.jpg', 198 ),
( 'SUNFEAST MARIE LIGHT OATS 120 GMS', 'productPool/1.jpg', 198 ),
( 'SUNFEAST MARIE LIGHT OATS 250G', 'productPool/1.jpg', 186 ),
( 'SUNFEAST MARIE LIGHT ORANGE 120G', 'productPool/1.jpg', 14 ),
( 'SUNFEAST MARIE LIGHT ORANGE 75G', 'productPool/1.jpg', 211 ),
( 'SUNFEAST MARIE LIGHT RICH TASTE 200G', 'productPool/1.jpg', 246 ),
( 'SUNFEAST MARIE LIGHT RICH TASTE 300G', 'productPool/1.jpg', 110 ),
( 'SUNFEAST MARIE LIGHT RICH TASTE 85G', 'productPool/1.jpg', 72 ),
( 'SUNFEAST MARIE LIGHT VEDA 250G', 'productPool/1.jpg', 23 ),
( 'SUNFEAST MARIE LIGHT VITA 90G', 'productPool/1.jpg', 10 ),
( 'SUNFEAST MOMS MAGIC CHOCO CHIP 120G', 'productPool/1.jpg', 93 ),
( 'SUNFEAST MOMS MAGIC FRUIT MILK 200G', 'productPool/1.jpg', 113 ),
( 'SUNFEAST MOMS MAGIC RICH BUTTER 150G', 'productPool/1.jpg', 268 ),
( 'SUNFEAST MOMS MAGIC RICH BUTTER 2*200G', 'productPool/1.jpg', 140 ),
( 'SUNFEAST MOMSMAGIC CASHEW &ALMOND 200G', 'productPool/1.jpg', 176 ),
( 'SUNFEAST NICE SUGAR SPRINKLED B 150G', 'productPool/1.jpg', 230 ),
( 'SUNFEAST SNACKY CHILLY TWIST CRACKERS 64G', 'productPool/1.jpg', 31 ),
( 'SUNFEAST SNACKY SALTED MASTI CRACKS 64G', 'productPool/1.jpg', 205 ),
( 'SUNFEAST SWEET IN SALT 150G', 'productPool/1.jpg', 40 ),
( 'SUNFEAST YIIPPEE MAGIC MASALA 420G', 'productPool/1.jpg', 252 ),
( 'SUNFEAST YIPPE CLASSIC MASALA 280G', 'productPool/1.jpg', 143 ),
( 'SUNFEAST YIPPEE CLASSIC MASALA NOODLES 70G', 'productPool/1.jpg', 155 ),
( 'SUNFEAST YIPPEE MAGIC MASALA 280G', 'productPool/1.jpg', 3 ),
( 'SUNFEAST YIPPEE MAGIC MASALA 420G', 'productPool/1.jpg', 70 ),
( 'SUNFEAST YIPPEE MAGIC MASALA 70G', 'productPool/1.jpg', 161 ),
( 'SUNFEAST YIPPEE MAGIC MASALA NOODLES 140G', 'productPool/1.jpg', 267 ),
( 'SUNFEAST YIPPEE MAGIC MASALA NOODLES 70GM', 'productPool/1.jpg', 141 ),
( 'SUNFEAST YIPPEE MAGIC MASALA NOODLES DBL 280GM', 'productPool/1.jpg', 259 ),
( 'SUNFEAST YIPPEE MOOD MASALA 280G', 'productPool/1.jpg', 141 ),
( 'SUNFEAST YIPPEE MOOD MASALA 70G', 'productPool/1.jpg', 218 ),
( 'SUNFEAST YIPPEE MOOD MASALA NOODLS 70G', 'productPool/1.jpg', 222 ),
( 'SUNFEAST YUMFILLS WHOOPIE PIE 150G', 'productPool/1.jpg', 24 ),
( 'SUNFEASTB GINGER DAIRY WHITENER 20GM', 'productPool/1.jpg', 60 ),
( 'SUNFLOWER SEED 500G', 'productPool/1.jpg', 158 ),
( 'SUNLIGHT COLOUR GUARD 1KG', 'productPool/1.jpg', 5 ),
( 'SUNLIGHT COLOUR GUARD 4KG', 'productPool/1.jpg', 208 ),
( 'SUNLIGHT COLOUR GUARD 500G', 'productPool/1.jpg', 215 ),
( 'SUNLIGHT LANDRY BAR SOAP150G', 'productPool/1.jpg', 65 ),
( 'SUNPLUS DETERGENT POWDER 1KG', 'productPool/1.jpg', 166 ),
( 'SUNPLUS SUPREME DETERGENT POWDER 500G', 'productPool/1.jpg', 128 ),
( 'SUNPLUSAQUA WASHING POWDER4KG', 'productPool/1.jpg', 209 ),
( 'SUNPURE SUNFLOWER 500ML', 'productPool/1.jpg', 95 ),
( 'SUNPURE SUNFLOWER OIL 1LTR', 'productPool/1.jpg', 153 ),
( 'SUNRICH REFINED SUNFLOWER OIL 500ML', 'productPool/1.jpg', 121 ),
( 'SUNRICH SUNFLOWER OIL 1LTR', 'productPool/1.jpg', 35 ),
( 'SUNRISE 1KG', 'productPool/1.jpg', 206 ),
( 'SUNSILK BLACK SHINE CONDITIONER 80ML', 'productPool/1.jpg', 158 ),
( 'SUNSILK BLACK SHINE SHAMPOO 180ML', 'productPool/1.jpg', 185 ),
( 'SUNSILK BLACK SHINE SHAMPOO 650ML', 'productPool/1.jpg', 197 ),
( 'SUNSILK BLACK SHINE SHAMPOO 80ML', 'productPool/1.jpg', 35 ),
( 'SUNSILK CO CREATION THICK LONG 180ML', 'productPool/1.jpg', 169 ),
( 'SUNSILK LONG GROWTH SHAMPOO 80ML', 'productPool/1.jpg', 205 ),
( 'SUNSILK LONG HEALTHY GROWTH SHAMPOO 180ML', 'productPool/1.jpg', 181 ),
( 'SUNSILK LONG HEALTHY GROWTH SHAMPOO 340ML', 'productPool/1.jpg', 184 ),
( 'SUNSILK NOURISHING SOFT & SMOOTH 180ML', 'productPool/1.jpg', 264 ),
( 'SUNSILK NOURISHING SOFT AND SMOOTH 180ML', 'productPool/1.jpg', 235 ),
( 'SUNSILK NOURSHING SOFT & SMOOTH SHAMPOO 80ML', 'productPool/1.jpg', 145 ),
( 'SUNSILK PERFECT SHAMPOO80ML', 'productPool/1.jpg', 78 ),
( 'SUNSILK PERFECT STRAIGHT CONDITIONER', 'productPool/1.jpg', 136 ),
( 'SUNSILK PERFECT STRAIGHT SHAMPOO 180ML', 'productPool/1.jpg', 195 ),
( 'SUNSILK PERFECT STRAIGHT SHAMPOO 340ML', 'productPool/1.jpg', 94 ),
( 'SUNSILK PERFECT STRAIGHT SHAMPOO 650ML', 'productPool/1.jpg', 104 ),
( 'SUNSILK SHAMPOO 35ML', 'productPool/1.jpg', 8 ),
( 'SUNSILK SOFT AND SMOOTH SHAMPOO 340ML', 'productPool/1.jpg', 203 ),
( 'SUNSILK SOFT AND SMOOTH SHAMPOO 650ML', 'productPool/1.jpg', 250 ),
( 'SUNSILK SOFT SMOOTH CONDITIONER 80ML', 'productPool/1.jpg', 114 ),
( 'SUNSILK STRAIGHT SHAMPOO 80ML', 'productPool/1.jpg', 82 ),
( 'SUNSILK STUNNING BLACK SHINE 180ML', 'productPool/1.jpg', 132 ),
( 'SUNSILK THICK & LONG SHAMPOO 180ML', 'productPool/1.jpg', 107 ),
( 'SUNSILK THICK & LONG SHAMPOO 80ML', 'productPool/1.jpg', 76 ),
( 'SUNSILK THICK AND LONG SHAMPOO 340ML', 'productPool/1.jpg', 188 ),
( 'SUNSILK THICK AND LONG SHAMPOO 650ML', 'productPool/1.jpg', 34 ),
( 'SUNSILK THICK LONG CONDITIONER 80ML', 'productPool/1.jpg', 100 ),
( 'SUNSWEET DRIED CRANBERRIES 170G', 'productPool/1.jpg', 200 ),
( 'SUNSWEET PITTED PRUNES JAR 340G', 'productPool/1.jpg', 179 ),
( 'SUPER CHEK DETERGENT POWDER 170G', 'productPool/1.jpg', 247 ),
( 'SUPER CHEK ORANGE FRESH DETERGENT 1KG', 'productPool/1.jpg', 161 ),
( 'SUPER CHEK ORANGE FRESH DETERGENT 200G', 'productPool/1.jpg', 176 ),
( 'SUPER CHEK ORANGE FRESH DETERGENT 500G', 'productPool/1.jpg', 31 ),
( 'SUPER NO.3 LEMON STRAINER', 'productPool/1.jpg', 237 ),
( 'SUPER SEED', 'productPool/1.jpg', 126 ),
( 'SUPER SONAL 4*6 FOLD', 'productPool/1.jpg', 204 ),
( 'SUPER SOUP FILTER NO.3', 'productPool/1.jpg', 133 ),
( 'SUPER STRAINER NO.7', 'productPool/1.jpg', 188 ),
( 'SUPERIA NATURALS LEMON MINT 70G', 'productPool/1.jpg', 210 ),
( 'SUPERIA NATURALS NEEM COCONUT OIL 70G', 'productPool/1.jpg', 24 ),
( 'SUPERIA NATURALS S&H 35ML', 'productPool/1.jpg', 279 ),
( 'SUPERIA NATURALS SANDAL-ALMOND SOAP 232G', 'productPool/1.jpg', 221 ),
( 'SUPERIA NATURALS SB 35ML', 'productPool/1.jpg', 87 ),
( 'SUPERMAX 10 BLADES', 'productPool/1.jpg', 154 ),
( 'SUPERMAX BLADE', 'productPool/1.jpg', 218 ),
( 'SUPREME CAKES NUTRIFUD CAKE LINGS 350G', 'productPool/1.jpg', 82 ),
( 'SUPREME CAKES NUTRIFUD CELEBRITY CAKE 650G', 'productPool/1.jpg', 254 ),
( 'SUPREME CAKES NUTRIFUD CHERRY BERRY CAKE 350G', 'productPool/1.jpg', 249 ),
( 'SUPREME CAKES NUTRIFUD EUROPEN DELIGHT CAKES 250G', 'productPool/1.jpg', 49 ),
( 'SUPREME CAKES NUTRIFUD FRUIT CAKE 450G', 'productPool/1.jpg', 177 ),
( 'SUPREME CAKES NUTRIFUD FRUIT CAKE 650G', 'productPool/1.jpg', 90 ),
( 'SUPREME CAKES NUTRIFUD FRUIT&NUT 350G', 'productPool/1.jpg', 2 ),
( 'SUPREME CAKES NUTRIFUD FRUITCAKE 350G', 'productPool/1.jpg', 149 ),
( 'SUPREME CAKES NUTRIFUD GIFT IT 1 KG', 'productPool/1.jpg', 225 ),
( 'SUPREME CAKES NUTRIFUD PLUM CAKE 350G', 'productPool/1.jpg', 48 ),
( 'SUPREME CAKES NUTRIFUD PLUM CAKE 450G', 'productPool/1.jpg', 172 ),
( 'SUPREME CAKES NUTRIFUD PLUM CAKE 650G', 'productPool/1.jpg', 236 ),
( 'SUPREME CAKES NUTRIFUD RICH MILK CAKES 250G', 'productPool/1.jpg', 74 ),
( 'SUPREME CAKES NUTRIFUD RICHPLUM 700G', 'productPool/1.jpg', 243 ),
( 'SUPREME CAKES NUTRIFUD SWISS CHOCOLATE 250G', 'productPool/1.jpg', 232 ),
( 'SUPREME CAKES NUTRIFUD VANILA CAKE 500G', 'productPool/1.jpg', 140 ),
( 'SURAJ MATTA PALADA 1KG', 'productPool/1.jpg', 145 ),
( 'SURAJ MATTA RICE ADA XL 1KG', 'productPool/1.jpg', 18 ),
( 'SURAJ PALADA 1KG', 'productPool/1.jpg', 275 ),
( 'SURAJ PALADA 200G', 'productPool/1.jpg', 234 ),
( 'SURAJ PALADA MATTA 200G', 'productPool/1.jpg', 29 ),
( 'SURAJ RICE ADA 1KG', 'productPool/1.jpg', 87 ),
( 'SURAJ RICE ADA 200G', 'productPool/1.jpg', 146 ),
( 'SURAJ RICE ADA XL 500G', 'productPool/1.jpg', 117 ),
( 'SURAJ RICE ADA XL200G', 'productPool/1.jpg', 98 ),
( 'SURAKSHA HOUSEHOLD GLOVES', 'productPool/1.jpg', 115 ),
( 'SURE WOMEN SHIELD 40ML', 'productPool/1.jpg', 42 ),
( 'SUREDAY WOMAN 25ML', 'productPool/1.jpg', 93 ),
( 'SUREWODRYSHI40ML', 'productPool/1.jpg', 131 ),
( 'SUREWODRYSHIE27G', 'productPool/1.jpg', 197 ),
( 'SURF EXCEL BAR 150G', 'productPool/1.jpg', 85 ),
( 'SURF EXCEL BAR 95G', 'productPool/1.jpg', 266 ),
( 'SURF EXCEL BAR 95G MRP 10', 'productPool/1.jpg', 206 ),
( 'SURF EXCEL BAR FW 250GM', 'productPool/1.jpg', 161 ),
( 'SURF EXCEL BAR FW 400GM', 'productPool/1.jpg', 197 ),
( 'SURF EXCEL BAR STAIN ERASER 150G RS-15', 'productPool/1.jpg', 215 ),
( 'SURF EXCEL BAR VALUE PACK 800G', 'productPool/1.jpg', 157 ),
( 'SURF EXCEL DETERGENT LIQIUD 200ML', 'productPool/1.jpg', 141 ),
( 'SURF EXCEL DETERGENT LIQUID 1.5L', 'productPool/1.jpg', 38 ),
( 'SURF EXCEL DETERGENT LIQUID 500ML', 'productPool/1.jpg', 234 ),
( 'SURF EXCEL EASY WASH 1KG', 'productPool/1.jpg', 114 ),
( 'SURF EXCEL EASY WASH 3KG', 'productPool/1.jpg', 102 ),
( 'SURF EXCEL EASY WASH 500G', 'productPool/1.jpg', 24 ),
( 'SURF EXCEL EASY WASH 90G', 'productPool/1.jpg', 182 ),
( 'SURF EXCEL EASY WASH POWDER 1.5KG', 'productPool/1.jpg', 4 ),
( 'SURF EXCEL EASY WASH POWDER 1KG', 'productPool/1.jpg', 278 ),
( 'SURF EXCEL EASY WASH200G', 'productPool/1.jpg', 22 ),
( 'SURF EXCEL EASY WASH95G', 'productPool/1.jpg', 259 ),
( 'SURF EXCEL MATIC FRONT LOAD 1KG', 'productPool/1.jpg', 136 ),
( 'SURF EXCEL MATIC FRONT LOAD 500G', 'productPool/1.jpg', 176 ),
( 'SURF EXCEL MATIC FRONT LOAD 500ML', 'productPool/1.jpg', 18 ),
( 'SURF EXCEL MATIC FRONT LOAD LIQUID 1L', 'productPool/1.jpg', 39 ),
( 'SURF EXCEL MATIC FRONT LOAD LIQUID 500ML', 'productPool/1.jpg', 153 ),
( 'SURF EXCEL MATIC FRONTLOAD LIQUID 1L', 'productPool/1.jpg', 140 ),
( 'SURF EXCEL MATIC LIQUD 500ML RS-130', 'productPool/1.jpg', 219 ),
( 'SURF EXCEL MATIC LIQUID 1.2LTR', 'productPool/1.jpg', 94 ),
( 'SURF EXCEL MATIC LIQUID TOP LOAD 500ML', 'productPool/1.jpg', 172 ),
( 'SURF EXCEL MATIC POWDER TOP LOAD 2KG', 'productPool/1.jpg', 209 ),
( 'SURF EXCEL MATIC TOP LOAD 1KG', 'productPool/1.jpg', 26 ),
( 'SURF EXCEL MATIC TOP LOAD 4KG+2KG', 'productPool/1.jpg', 30 ),
( 'SURF EXCEL MATIC TOPLOAD LIQUID 1L', 'productPool/1.jpg', 44 ),
( 'SURF EXCEL MATICTOP LOAD500G', 'productPool/1.jpg', 85 ),
( 'SURF EXCEL QUICK WASH 500G', 'productPool/1.jpg', 2 ),
( 'SURF EXCEL QUICK WASH POWDER 1KG', 'productPool/1.jpg', 252 ),
( 'SURF EXCEL QUICK WASH POWDER 2KG', 'productPool/1.jpg', 234 ),
( 'SURF EXCEL QUIICK WASH 1KG', 'productPool/1.jpg', 77 ),
( 'SURF EXCEL STAIN ERASER 250G', 'productPool/1.jpg', 275 ),
( 'SURF EXCEL WASHING SOAP 250G', 'productPool/1.jpg', 134 ),
( 'SURF XL QUICK WASH POWDER 1KG', 'productPool/1.jpg', 77 ),
( 'SUTHLI SADA', 'productPool/1.jpg', 205 ),
( 'SUTLI SADA 500G', 'productPool/1.jpg', 176 ),
( 'SUVIDHA ALUMINIUM FOIL 9M', 'productPool/1.jpg', 275 ),
( 'SUVITHA 10 WITH OUT INNER', 'productPool/1.jpg', 62 ),
( 'SUVITHA 15 WITH OUT INNER FAMILY', 'productPool/1.jpg', 231 ),
( 'SWAD ADATT MATTA RICE 5KG', 'productPool/1.jpg', 174 ),
( 'SWAD ADATT PLUS MATTA RICE 1KG', 'productPool/1.jpg', 251 ),
( 'SWAD APPAM PODI 500G', 'productPool/1.jpg', 3 ),
( 'SWAD BENCY RAVA 1KG', 'productPool/1.jpg', 157 ),
( 'SWAD BENCY RAVA 500G', 'productPool/1.jpg', 3 ),
( 'SWAD BROKEN RICE PREMIUM 500GMS', 'productPool/1.jpg', 259 ),
( 'SWAD BROKEN WHEAT 500G', 'productPool/1.jpg', 230 ),
( 'SWAD FRESH ATTA 1KG', 'productPool/1.jpg', 207 ),
( 'SWAD ORGANIC BROKEN WHEAT 500G', 'productPool/1.jpg', 99 ),
( 'SWAD ORGANIC ROASTED RAVA 907G', 'productPool/1.jpg', 69 ),
( 'SWAD ORGANIC WHEAT FLOUR 907G', 'productPool/1.jpg', 154 ),
( 'SWAD PALAPPAM VELLEPPAM PODI 500G', 'productPool/1.jpg', 279 ),
( 'SWAD PATHIRI PODI 500G', 'productPool/1.jpg', 166 ),
( 'SWAD PREMIUM PUTTU PODI 1KG', 'productPool/1.jpg', 267 ),
( 'SWAD PREMIUM PUTTU PODI 500G', 'productPool/1.jpg', 164 ),
( 'SWAD ROASTED RAVA 1KG', 'productPool/1.jpg', 51 ),
( 'SWAD SHARBATI ATTA 1KG', 'productPool/1.jpg', 183 ),
( 'SWAD WHITE PUTTU PODI 1KG', 'productPool/1.jpg', 193 ),
( 'SWAD WHITE PUTTU PODI 500G', 'productPool/1.jpg', 254 ),
( 'SWARANA MOGRA AGARBATHI', 'productPool/1.jpg', 74 ),
( 'SWARNA CHANDAN AGARBATTI 15G', 'productPool/1.jpg', 108 ),
( 'SWARNAM GINGELLY OIL 100ML', 'productPool/1.jpg', 136 ),
( 'SWARNAM GINGELLY OIL 1L', 'productPool/1.jpg', 181 ),
( 'SWARNAM GINGELLY OIL 200ML', 'productPool/1.jpg', 72 ),
( 'SWARNAM GINGELLY OIL 500ML', 'productPool/1.jpg', 41 ),
( 'SWARNAM GINGELY OIL 200ML', 'productPool/1.jpg', 144 ),
( 'SWARNNA MALLIKA AGARBATHI RS 12', 'productPool/1.jpg', 57 ),
( 'SWASTIK CASTOR OIL 100ML', 'productPool/1.jpg', 150 ),
( 'SWASTIK CASTOR OIL 50ML', 'productPool/1.jpg', 128 ),
( 'SWEET BOX-2 SINGLE', 'productPool/1.jpg', 14 ),
( 'SWEET CORN VEG SOUP 44G', 'productPool/1.jpg', 136 ),
( 'SWEET JEERAKAM 100GMS', 'productPool/1.jpg', 279 ),
( 'SWEET MELON DRIED 150G', 'productPool/1.jpg', 167 ),
( 'SWEET TAMARIND 250G', 'productPool/1.jpg', 55 ),
( 'SWIFT CLOTH CLIP 24PCS', 'productPool/1.jpg', 235 ),
( 'SWIFT PATLA BIG', 'productPool/1.jpg', 271 ),
( 'SWING LID WITH DRUM D-30', 'productPool/1.jpg', 60 ),
( 'SYNERGY PEN STAND HEXAGON S623', 'productPool/1.jpg', 116 ),
( 'SYSKA LED TUBE LIGHT 18W', 'productPool/1.jpg', 69 ),
( 'T - SHINE TOILET CLEANER FLORAL 200 ML', 'productPool/1.jpg', 58 ),
( 'T SHINE DISINFECTANT LAVENDER 500ML', 'productPool/1.jpg', 171 ),
( 'T- SHINE TOILET CLEANER ELENGI 200 ML', 'productPool/1.jpg', 71 ),
( 'T-SHINE TOILET CLEANER ELENGI 500ML', 'productPool/1.jpg', 32 ),
( 'T-SHINE TOILET CLEANER FLORAN 500ML', 'productPool/1.jpg', 93 ),
( 'TAILORING TAPE', 'productPool/1.jpg', 1 ),
( 'TAIYO FAST RED FISH FOOD 330G JAR', 'productPool/1.jpg', 168 ),
( 'TAIYO FISH FOOD 100G JAR', 'productPool/1.jpg', 13 ),
( 'TAIYO FISH FOOD 100G PKT', 'productPool/1.jpg', 181 ),
( 'TAIYO FISH FOOD 1KG PKT', 'productPool/1.jpg', 56 ),
( 'TAIYO FISH FOOD 200G PKT', 'productPool/1.jpg', 6 ),
( 'TAIYO FISH FOOD 20G', 'productPool/1.jpg', 144 ),
( 'TAIYO FISH FOOD 50G PKT', 'productPool/1.jpg', 55 ),
( 'TAIYO FISH FOODS 500G PKT', 'productPool/1.jpg', 190 ),
( 'TAIYO SHRIMP FISH FOOD 16G', 'productPool/1.jpg', 98 ),
( 'TAJ MAHAL SPICY GINGER TEA BAG', 'productPool/1.jpg', 108 ),
( 'TAJ PLASTIC JUICE STRAINER NO 6', 'productPool/1.jpg', 258 ),
( 'TAJ PLASTIC JUICE STRAINER NO 7', 'productPool/1.jpg', 114 ),
( 'TAJ PLASTIC JUICE STRAINER NO 8', 'productPool/1.jpg', 132 ),
( 'TAJ TEA COFFEE STRAINERS', 'productPool/1.jpg', 218 ),
( 'TAJMAHAL LEAF 250G', 'productPool/1.jpg', 23 ),
( 'TAJMAHAL LEAF 500G', 'productPool/1.jpg', 267 ),
( 'TAMARIND 100G', 'productPool/1.jpg', 181 ),
( 'TAMARIND 250G', 'productPool/1.jpg', 84 ),
( 'TAMARIND 250GMS', 'productPool/1.jpg', 252 ),
( 'TAMARIND 500G', 'productPool/1.jpg', 110 ),
( 'TAMARIND 500GMS', 'productPool/1.jpg', 85 ),
( 'TANG 500G IMP ZIPLOCK', 'productPool/1.jpg', 272 ),
( 'TANG LEMON 100G', 'productPool/1.jpg', 208 ),
( 'TANG LEMON 500G', 'productPool/1.jpg', 22 ),
( 'TANG LEMON 500G POUCH', 'productPool/1.jpg', 273 ),
( 'TANG LEMON MINT 500G POUCH', 'productPool/1.jpg', 89 ),
( 'TANG LEMON MINT ZIP LOCK 500 GM', 'productPool/1.jpg', 191 ),
( 'TANG MANGO 100G', 'productPool/1.jpg', 49 ),
( 'TANG MANGO 125G', 'productPool/1.jpg', 111 ),
( 'TANG MANGO 2.5 KG', 'productPool/1.jpg', 98 ),
( 'TANG MANGO 500G', 'productPool/1.jpg', 77 ),
( 'TANG MANGO 500G IMP ZIP LOCK POUCH', 'productPool/1.jpg', 105 ),
( 'TANG MANGO 500G POUCH', 'productPool/1.jpg', 141 ),
( 'TANG MANGO 750G PKT', 'productPool/1.jpg', 220 ),
( 'TANG MOSAMBI 500 G', 'productPool/1.jpg', 268 ),
( 'TANG ORANE ORANGE 250G PKT', 'productPool/1.jpg', 251 ),
( 'TANG ORANGE 100G', 'productPool/1.jpg', 170 ),
( 'TANG ORANGE 125G', 'productPool/1.jpg', 20 ),
( 'TANG ORANGE 1KG CONTAINER', 'productPool/1.jpg', 33 ),
( 'TANG ORANGE 1LTR', 'productPool/1.jpg', 197 ),
( 'TANG ORANGE 2.5K', 'productPool/1.jpg', 161 ),
( 'TANG ORANGE 2.5KG', 'productPool/1.jpg', 214 ),
( 'TANG ORANGE 2.5KG TIN', 'productPool/1.jpg', 225 ),
( 'TANG ORANGE 4*100G', 'productPool/1.jpg', 60 ),
( 'TANG ORANGE 400G SIPPER', 'productPool/1.jpg', 13 ),
( 'TANG ORANGE 500G', 'productPool/1.jpg', 36 ),
( 'TANG ORANGE 500G IMP', 'productPool/1.jpg', 214 ),
( 'TANG ORANGE 500G IMP ZIP LOCK POUCH', 'productPool/1.jpg', 264 ),
( 'TANG ORANGE 500G PKT', 'productPool/1.jpg', 48 ),
( 'TANG ORANGE 500G POUCH', 'productPool/1.jpg', 86 ),
( 'TANG ORANGE 750G', 'productPool/1.jpg', 70 ),
( 'TANG ORANGE CONTAINAER 1KG', 'productPool/1.jpg', 81 ),
( 'TANG ORANGE IMP 750G', 'productPool/1.jpg', 199 ),
( 'TANG PINEAPPLE ZIP LOCK 500 GM', 'productPool/1.jpg', 34 ),
( 'TANG TROPICAL COCKTAIL 500G ZIPLOCK', 'productPool/1.jpg', 42 ),
( 'TANGO MANGO IMP 2.5KG', 'productPool/1.jpg', 129 ),
( 'TAPE 1 INCH BROWN', 'productPool/1.jpg', 68 ),
( 'TAPE 1 INCH CLEAR', 'productPool/1.jpg', 72 ),
( 'TAPE 18 MM CLEAR', 'productPool/1.jpg', 159 ),
( 'TAPE 2 INCH BROWN', 'productPool/1.jpg', 40 ),
( 'TAPE 2 INCH CLEAR', 'productPool/1.jpg', 163 ),
( 'TAPE 3 INCH BROWN', 'productPool/1.jpg', 262 ),
( 'TAPE 3 INCH CLEAR', 'productPool/1.jpg', 57 ),
( 'TAPE 3/4 INCH CLEAR', 'productPool/1.jpg', 268 ),
( 'TAPE ABRO 48MM', 'productPool/1.jpg', 240 ),
( 'TAPE RS 65', 'productPool/1.jpg', 187 ),
( 'TAPE RS115', 'productPool/1.jpg', 250 ),
( 'TAPE RS145', 'productPool/1.jpg', 276 ),
( 'TAPE RS85', 'productPool/1.jpg', 80 ),
( 'TASTY BUTTON MUSHROOM 800G', 'productPool/1.jpg', 178 ),
( 'TASTY NIBBLE CUT MANGO PICKLE 1KG', 'productPool/1.jpg', 2 ),
( 'TASTY NIBBLES ANCHOVY PICKLE 150G', 'productPool/1.jpg', 28 ),
( 'TASTY NIBBLES CLAM PICKLE 400G', 'productPool/1.jpg', 65 ),
( 'TASTY NIBBLES FRIED MASALA PRAWNS 50G', 'productPool/1.jpg', 185 ),
( 'TASTY NIBBLES LIME DATES PICKLE 100G', 'productPool/1.jpg', 6 ),
( 'TASTY NIBBLES LIME DATES PICKLE 150G', 'productPool/1.jpg', 127 ),
( 'TASTY NIBBLES LIME DATES PICKLE 400G', 'productPool/1.jpg', 217 ),
( 'TASTY NIBBLES LIME PICKLE 1KG', 'productPool/1.jpg', 56 ),
( 'TASTY NIBBLES MANGO CARROT PICKLE 150G', 'productPool/1.jpg', 249 ),
( 'TASTY NIBBLES MIXED VEG + CUT MANGO PICKLE 400G', 'productPool/1.jpg', 208 ),
( 'TASTY NIBBLES PRAWN PICKLE 150G', 'productPool/1.jpg', 14 ),
( 'TASTY NIBBLES PRAWN PICKLE 400G', 'productPool/1.jpg', 10 ),
( 'TASTY NIBBLES SQUID PICKLE 400G', 'productPool/1.jpg', 178 ),
( 'TASTY NIBBLES TUNA CHUNKS IN OIL 185G', 'productPool/1.jpg', 207 ),
( 'TASTY NIBBLES TUNA CHUNKS IN WATER 185G', 'productPool/1.jpg', 103 ),
( 'TASTY NIBBLES TUNA CHUNKS WATER 185G', 'productPool/1.jpg', 121 ),
( 'TASTY NIBBLES TUNA FALKES SUNFLOWER OIL 185G', 'productPool/1.jpg', 266 ),
( 'TASTY NIBBLES TUNA FALKES SUNFLOWER OIL185G', 'productPool/1.jpg', 122 ),
( 'TASTY NIBBLES TUNA FALKES WATER SALT 185G', 'productPool/1.jpg', 215 ),
( 'TASTY NIBBLES TUNA FLAKES IN OIL 185G', 'productPool/1.jpg', 49 ),
( 'TASTY NIBBLES TUNA FLAKES IN WATER 185G', 'productPool/1.jpg', 217 ),
( 'TASTY NIBBLES TUNA FLAKES WATER SALT 185G', 'productPool/1.jpg', 128 ),
( 'TASTY NIBBLES TUNACHUNKS WATER SALT 185G', 'productPool/1.jpg', 238 ),
( 'TASTY NIBBLESTUNACHUNKS SUNFLOWEROIL180M', 'productPool/1.jpg', 186 ),
( 'TASTY PLUS GRAPE PULP 3KG', 'productPool/1.jpg', 90 );