INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'DTE SUGAR BROWN 500G', 'productPool/1.jpg', 137 ),
( 'DTE TOMATO KETCHUP 200G', 'productPool/1.jpg', 219 ),
( 'DTE TURMERIC POWDER 100G', 'productPool/1.jpg', 197 ),
( 'DTE URAD DAL MOGAR 1 KG', 'productPool/1.jpg', 94 ),
( 'DTE URAD DAL MOGAR 500G', 'productPool/1.jpg', 63 ),
( 'DTE URAD GOTA 1KG', 'productPool/1.jpg', 13 ),
( 'DTE URAD GOTA 500GM', 'productPool/1.jpg', 207 ),
( 'DTE WHEAT CHAKKI ATTA 1 KG', 'productPool/1.jpg', 198 ),
( 'DUBUR BABOOL TOOTHPASTE 350G', 'productPool/1.jpg', 47 ),
( 'DUBUR RED TOOTH PASTE300G', 'productPool/1.jpg', 221 ),
( 'DUBUR SPECIALHAIR OIL200ML', 'productPool/1.jpg', 220 ),
( 'DUCK FRICTION', 'productPool/1.jpg', 48 ),
( 'DURABLE HANGER 6PCS', 'productPool/1.jpg', 247 ),
( 'DURACELL 9V 2 BATTERIES', 'productPool/1.jpg', 193 ),
( 'DURACELL 9VCELL', 'productPool/1.jpg', 1 ),
( 'DURACELL A A BATTERY', 'productPool/1.jpg', 227 ),
( 'DURACELL AA 2 BCD', 'productPool/1.jpg', 241 ),
( 'DURACELL AA 4BCD 8281', 'productPool/1.jpg', 138 ),
( 'DURACELL AA8', 'productPool/1.jpg', 15 ),
( 'DURACELL AAA 2BCD', 'productPool/1.jpg', 77 ),
( 'DURACELL AAA 4 BATTERTY', 'productPool/1.jpg', 138 ),
( 'DURACELL AAA ALKALINE BATTERY', 'productPool/1.jpg', 111 ),
( 'DURACELL AAA2 BCD', 'productPool/1.jpg', 91 ),
( 'DURACELL AAA4', 'productPool/1.jpg', 186 ),
( 'DURACELL RECHARGABLE AA2', 'productPool/1.jpg', 82 ),
( 'DURACELL RECHARGABLE AAA2', 'productPool/1.jpg', 87 ),
( 'DURACELL ULTRA AA 2 BCD', 'productPool/1.jpg', 16 ),
( 'DURACELL ULTRA AA 4 BCD', 'productPool/1.jpg', 40 ),
( 'DURACELLC2 BCD', 'productPool/1.jpg', 10 ),
( 'DUREX CONDOMS VANILLA 3N', 'productPool/1.jpg', 228 ),
( 'DUREX CONDOMS WILD BERRY 3N', 'productPool/1.jpg', 183 ),
( 'DUREX CONDUMS JEANS', 'productPool/1.jpg', 95 ),
( 'DUREX EXTRA TIME CONDOMS 3', 'productPool/1.jpg', 267 ),
( 'DUREX KOHINOOR CONDOMS 10', 'productPool/1.jpg', 198 ),
( 'DUREX KOHINOOR CONDOMS CHOCOLATE 3N', 'productPool/1.jpg', 106 ),
( 'DUREX KOHINOOR CONDOMS KALA KHATTA 3N', 'productPool/1.jpg', 271 ),
( 'DUREX KOHINOOR CONDOMS MEETHA PAAN 3N', 'productPool/1.jpg', 3 ),
( 'DUST PAN CLEAN PLUS 230 B', 'productPool/1.jpg', 271 ),
( 'DUST PAN HOUSE MAID -1', 'productPool/1.jpg', 234 ),
( 'DYE BRUSH RS15', 'productPool/1.jpg', 220 ),
( 'DYE BRUSH RS24', 'productPool/1.jpg', 260 ),
( 'DYE BRUSH RS33', 'productPool/1.jpg', 51 ),
( 'DYE BRUSH RS36', 'productPool/1.jpg', 42 ),
( 'DYNA PEDAL BIN 108 PRINT', 'productPool/1.jpg', 24 ),
( 'DYNA TOILET SOAP', 'productPool/1.jpg', 136 ),
( 'DYNAMIC MUG 1000ML MOULD', 'productPool/1.jpg', 149 ),
( 'EASSY CLEAN LEMON GRASS ESSENCE 100ML', 'productPool/1.jpg', 134 ),
( 'EASTARN PANEER BUTTER MASALA 40G', 'productPool/1.jpg', 49 ),
( 'EASTERN ADIMALI KAPPI 100G', 'productPool/1.jpg', 10 ),
( 'EASTERN ASAFOETIDA POWDER 25G', 'productPool/1.jpg', 232 ),
( 'EASTERN ASAFOETIDA POWDER 50G', 'productPool/1.jpg', 210 ),
( 'EASTERN BIRIYANI MASALA 100G', 'productPool/1.jpg', 152 ),
( 'EASTERN BRAHMINS SAMBAR 100G', 'productPool/1.jpg', 166 ),
( 'EASTERN BUTTER CHICKEN MASALA 40', 'productPool/1.jpg', 24 ),
( 'EASTERN CHANA MASALA 100G', 'productPool/1.jpg', 134 ),
( 'EASTERN CHICKEN FRY MASALA KABAB 100G', 'productPool/1.jpg', 46 ),
( 'EASTERN CHICKEN MASALA 100G', 'productPool/1.jpg', 272 ),
( 'EASTERN CHILLI POWDER 250G', 'productPool/1.jpg', 108 ),
( 'EASTERN CHILLY CHICKEN 100G', 'productPool/1.jpg', 66 ),
( 'EASTERN CHILLY POWDER 1 KG', 'productPool/1.jpg', 38 ),
( 'EASTERN CHILLY POWDER 100G', 'productPool/1.jpg', 117 ),
( 'EASTERN CHILLY POWDER 500G', 'productPool/1.jpg', 54 ),
( 'EASTERN CHUKKUKAPI 100G', 'productPool/1.jpg', 139 ),
( 'EASTERN COCONUT OIL 1L BOTTEL', 'productPool/1.jpg', 13 ),
( 'EASTERN CORIANDER POWDER 100G', 'productPool/1.jpg', 183 ),
( 'EASTERN CORIANDER POWDER 1KG', 'productPool/1.jpg', 93 ),
( 'EASTERN CORIANDER POWDER 250G', 'productPool/1.jpg', 72 ),
( 'EASTERN CORIANDER POWDER 500G', 'productPool/1.jpg', 244 ),
( 'EASTERN CORIANDER POWDER 5KG', 'productPool/1.jpg', 6 ),
( 'EASTERN CRUSHED CHILLY 100', 'productPool/1.jpg', 209 ),
( 'EASTERN CUMIN POWDER 100G', 'productPool/1.jpg', 83 ),
( 'EASTERN DRY GINGER POWDER 100G', 'productPool/1.jpg', 39 ),
( 'EASTERN DUST TEA 250 G', 'productPool/1.jpg', 125 ),
( 'EASTERN EASTEA 100GM', 'productPool/1.jpg', 33 ),
( 'EASTERN EASTEA 250G BOTTLE', 'productPool/1.jpg', 189 ),
( 'EASTERN EASTEA 500GM', 'productPool/1.jpg', 173 ),
( 'EASTERN EGG MASALA 100G', 'productPool/1.jpg', 136 ),
( 'EASTERN FENNEL POWDER 100G', 'productPool/1.jpg', 78 ),
( 'EASTERN FENU GREEK POWDER 100G', 'productPool/1.jpg', 78 ),
( 'EASTERN FISH FRY MASALA 25G', 'productPool/1.jpg', 101 ),
( 'EASTERN FISH MASALA 100G', 'productPool/1.jpg', 84 ),
( 'EASTERN GARAM MASALA 50G', 'productPool/1.jpg', 212 ),
( 'EASTERN GREEN GRAM POWDER 100G', 'productPool/1.jpg', 178 ),
( 'EASTERN INSTANT UPMA 200G', 'productPool/1.jpg', 88 ),
( 'EASTERN JACKFRUIT 365 POWDER 200G', 'productPool/1.jpg', 168 ),
( 'EASTERN JACKFRUIT 365 POWDER 30G', 'productPool/1.jpg', 87 ),
( 'EASTERN KASHMIRI CHILLI 1KG', 'productPool/1.jpg', 190 ),
( 'EASTERN KASHMIRI CHILLI POWDER 250G', 'productPool/1.jpg', 219 ),
( 'EASTERN KASHMIRI CHILLI POWDER 5KG', 'productPool/1.jpg', 50 ),
( 'EASTERN KASHMIRI CHILLY 100G', 'productPool/1.jpg', 184 ),
( 'EASTERN KASHMIRI CHILLY 500G', 'productPool/1.jpg', 147 ),
( 'EASTERN MASALA POWDER 25G', 'productPool/1.jpg', 106 ),
( 'EASTERN MEAT MASALA 100G', 'productPool/1.jpg', 244 ),
( 'EASTERN MEAT ULARTHU MASALA 100G', 'productPool/1.jpg', 254 ),
( 'EASTERN MUTTON MASALA 100G', 'productPool/1.jpg', 260 ),
( 'EASTERN MUTTON MASALA 50G', 'productPool/1.jpg', 37 ),
( 'EASTERN PALADA MIX 200G', 'productPool/1.jpg', 113 ),
( 'EASTERN PALAK PANEER MASALA 40G', 'productPool/1.jpg', 55 ),
( 'EASTERN PAYASAM MIX 200G', 'productPool/1.jpg', 54 ),
( 'EASTERN PEPPER CHICKEN MASALA 100G', 'productPool/1.jpg', 50 ),
( 'EASTERN PEPPER POWDER 100G', 'productPool/1.jpg', 248 ),
( 'EASTERN PEPPER POWDER 50G', 'productPool/1.jpg', 129 ),
( 'EASTERN PICKLE POWDER 100G', 'productPool/1.jpg', 94 ),
( 'EASTERN PURE ADIMALI KAPPI 100 G', 'productPool/1.jpg', 117 ),
( 'EASTERN RASAM POWDER 100G', 'productPool/1.jpg', 29 ),
( 'EASTERN SAMBA BROKEN WHEAT 500G', 'productPool/1.jpg', 171 ),
( 'EASTERN SAMBAR POWDER 100G', 'productPool/1.jpg', 68 ),
( 'EASTERN TAMARIND 200G', 'productPool/1.jpg', 84 ),
( 'EASTERN TURMERIC POWDER 100G', 'productPool/1.jpg', 153 ),
( 'EASTERN TURMERIC POWDER 250G', 'productPool/1.jpg', 32 ),
( 'EASTERN VEGETABLE MASALA 100G', 'productPool/1.jpg', 224 ),
( 'EASTERN WHITE PEPPER POWDER50G', 'productPool/1.jpg', 57 ),
( 'EASY BROOM STOFF KITCHENWARE', 'productPool/1.jpg', 184 ),
( 'EASY ON IMP', 'productPool/1.jpg', 53 ),
( 'ECO FRESH BROWN SUGAR 1KG', 'productPool/1.jpg', 52 ),
( 'ECO FRESH BROWN SUGAR 500G', 'productPool/1.jpg', 22 ),
( 'ECO FRESH CASHEW WHOLE 100G', 'productPool/1.jpg', 7 ),
( 'ECO FRESH CHANA DAL 500G', 'productPool/1.jpg', 261 ),
( 'ECO FRESH CHANA KABULI 500G', 'productPool/1.jpg', 127 ),
( 'ECO FRESH CHANA WHOLE 500G', 'productPool/1.jpg', 147 ),
( 'ECO FRESH CHANNA DAL 500G', 'productPool/1.jpg', 261 ),
( 'ECO FRESH CORIANDER POWDER 100G', 'productPool/1.jpg', 235 ),
( 'ECO FRESH FENUGREEK 100G', 'productPool/1.jpg', 74 ),
( 'ECO FRESH FLAX SEED 100G', 'productPool/1.jpg', 134 ),
( 'ECO FRESH GREEN PEAS WATANA 500G', 'productPool/1.jpg', 245 ),
( 'ECO FRESH GROUNDNUT 500G', 'productPool/1.jpg', 77 ),
( 'ECO FRESH KABULI CHANA 500G', 'productPool/1.jpg', 45 ),
( 'ECO FRESH MASOOR DAL 500G', 'productPool/1.jpg', 39 ),
( 'ECO FRESH MOONG DAL 500G', 'productPool/1.jpg', 70 ),
( 'ECO FRESH MOONG WHOLE 1KG', 'productPool/1.jpg', 215 ),
( 'ECO FRESH MOONG WHOLE 500G', 'productPool/1.jpg', 246 ),
( 'ECO FRESH MUSTARD SEED 100GM', 'productPool/1.jpg', 64 ),
( 'ECO FRESH ORGANIC AJWAIN SEED 100G', 'productPool/1.jpg', 239 ),
( 'ECO FRESH ORGANIC BESAN 500G', 'productPool/1.jpg', 133 ),
( 'ECO FRESH ORGANIC BROWN SUGAR 1KG', 'productPool/1.jpg', 251 ),
( 'ECO FRESH ORGANIC CHANA 1KG', 'productPool/1.jpg', 75 ),
( 'ECO FRESH ORGANIC CHENNA 500G', 'productPool/1.jpg', 112 ),
( 'ECO FRESH ORGANIC CHILLY POWDER 100G', 'productPool/1.jpg', 59 ),
( 'ECO FRESH ORGANIC CORIENDER SEED 100G', 'productPool/1.jpg', 46 ),
( 'ECO FRESH ORGANIC CUMIN SEED 100G', 'productPool/1.jpg', 159 ),
( 'ECO FRESH ORGANIC FLEX SEED 100G', 'productPool/1.jpg', 172 ),
( 'ECO FRESH ORGANIC FUNNEL SEED 100G', 'productPool/1.jpg', 31 ),
( 'ECO FRESH ORGANIC KABULI CHANA 1KG', 'productPool/1.jpg', 87 ),
( 'ECO FRESH ORGANIC MASOOR DAL 500G', 'productPool/1.jpg', 223 ),
( 'ECO FRESH ORGANIC MOONG WHOLE 1KG', 'productPool/1.jpg', 147 ),
( 'ECO FRESH ORGANIC MOONG WHOLE 500GM', 'productPool/1.jpg', 210 ),
( 'ECO FRESH ORGANIC POHA 500G', 'productPool/1.jpg', 79 ),
( 'ECO FRESH ORGANIC SUGAR 500G', 'productPool/1.jpg', 98 ),
( 'ECO FRESH ORGANIC SUGAR BROWN 500G', 'productPool/1.jpg', 121 ),
( 'ECO FRESH ORGANIC TOOR DAL 1KG', 'productPool/1.jpg', 267 ),
( 'ECO FRESH ORGANIC TOOR DAL 500G', 'productPool/1.jpg', 151 ),
( 'ECO FRESH RAJMA CHITRA 500G', 'productPool/1.jpg', 103 ),
( 'ECO FRESH RED CHILLY WHOLE 100G', 'productPool/1.jpg', 60 ),
( 'ECO FRESH REDRICE 1KG', 'productPool/1.jpg', 266 ),
( 'ECO FRESH ROCK SALT 1KG', 'productPool/1.jpg', 87 ),
( 'ECO FRESH SONA MASURI RICE 1KG', 'productPool/1.jpg', 17 ),
( 'ECO FRESH SUGAR WHITE 1KG', 'productPool/1.jpg', 22 ),
( 'ECO FRESH SUGAR WHITE 500G', 'productPool/1.jpg', 54 ),
( 'ECO FRESH TOOR DAL 500', 'productPool/1.jpg', 86 ),
( 'ECO FRESH TURMERIC POWDER 100G', 'productPool/1.jpg', 228 ),
( 'ECO FRESH URAD GOTA 500G', 'productPool/1.jpg', 219 ),
( 'ECO FRESH URAD GOTTA 1KG', 'productPool/1.jpg', 198 ),
( 'ECO FRESH URAD WHITE WHOLE 500G', 'productPool/1.jpg', 238 ),
( 'ECO FRESH WHEAT FLOUR LOKWAN 1KG', 'productPool/1.jpg', 252 ),
( 'ECO FRESH WHEAT WHEAT DALIYA 500G', 'productPool/1.jpg', 112 ),
( 'ECO FRESH WHITE SUGAR 1KG', 'productPool/1.jpg', 77 ),
( 'ECO FRIENDLY SEPTICLEEN 500ML', 'productPool/1.jpg', 90 ),
( 'ECO VALLEY MUSHROOMS', 'productPool/1.jpg', 67 ),
( 'ECONOMY 1000 MUG FAMILY', 'productPool/1.jpg', 129 ),
( 'ECONOMY 750 MUG', 'productPool/1.jpg', 183 ),
( 'EGG BEATER B', 'productPool/1.jpg', 147 ),
( 'EGG BEATER S', 'productPool/1.jpg', 197 ),
( 'EGG HAKA NOODLS 150G', 'productPool/1.jpg', 109 ),
( 'EGG ROLL', 'productPool/1.jpg', 262 ),
( 'EGG TRAY MOULD', 'productPool/1.jpg', 171 ),
( 'EGO OF PARIS COMB RS 15', 'productPool/1.jpg', 181 ),
( 'EGO OF PARIS COMB RS 15.50', 'productPool/1.jpg', 56 ),
( 'EGO OF PARIS COMB RS 18', 'productPool/1.jpg', 271 ),
( 'EKOS DEO OFFER PACK', 'productPool/1.jpg', 183 ),
( 'EKOZ FASHION POUR BODY SPRAY 200ML', 'productPool/1.jpg', 66 ),
( 'EKOZ GAGRA DEODORANT SPRAY 200ML', 'productPool/1.jpg', 257 ),
( 'EKOZ GT ROUGE DEODORANT SPRAY 200ML', 'productPool/1.jpg', 117 ),
( 'EKOZ JUST SPORT DEODORANT SPRAY 200ML', 'productPool/1.jpg', 8 ),
( 'EKOZ RUNWAY DEODORANT SPRAY 200ML', 'productPool/1.jpg', 65 ),
( 'EKOZ STRIKE FEMME DEODORANT SPRAY 200ML', 'productPool/1.jpg', 156 ),
( 'ELADI PAEDIATIC COUGH SYRUP 100ML', 'productPool/1.jpg', 229 ),
( 'ELANEER KUZHAMBU 5ML', 'productPool/1.jpg', 22 ),
( 'ELECTRO ORS ORANGE DRINK 200ML', 'productPool/1.jpg', 99 ),
( 'ELECTRO POP BABY LIP COLOUR PINK 3.5G', 'productPool/1.jpg', 179 ),
( 'ELEGANT PASEO LUNCHEON NAPKIN 50S', 'productPool/1.jpg', 226 ),
( 'ELEPHANT FOOT', 'productPool/1.jpg', 165 ),
( 'ELEPHANT GINGER BEER 330ML', 'productPool/1.jpg', 171 ),
( 'ELEPHANT JUICE STRAINER -4', 'productPool/1.jpg', 73 ),
( 'ELEPHANT JUICE STRAINER -5', 'productPool/1.jpg', 276 ),
( 'ELITE AROGYA BROWN BREAD 450G', 'productPool/1.jpg', 269 ),
( 'ELITE AROGYA OAT RUSK 200G', 'productPool/1.jpg', 23 ),
( 'ELITE ATTA PLUS OATS 1KG', 'productPool/1.jpg', 48 ),
( 'ELITE BLACK FOREST CAKE 300G', 'productPool/1.jpg', 239 ),
( 'ELITE BLACK FOREST CAKE 600G', 'productPool/1.jpg', 272 ),
( 'ELITE BROKEN WHEAT 500G', 'productPool/1.jpg', 15 ),
( 'ELITE BUTTER CUP CAKE 100G', 'productPool/1.jpg', 98 ),
( 'ELITE CAKE ORANGE 130G', 'productPool/1.jpg', 154 ),
( 'ELITE CAKES CHOCOLATE 130G', 'productPool/1.jpg', 234 ),
( 'ELITE CAKES CHOCOLATE PLUM 680G', 'productPool/1.jpg', 96 ),
( 'ELITE CAKES ELITE VANILLA 130G', 'productPool/1.jpg', 26 ),
( 'ELITE CAKES ORANGE 140G', 'productPool/1.jpg', 58 ),
( 'ELITE CAKES PINEAPPLE CHOCOLATE 130G', 'productPool/1.jpg', 193 ),
( 'ELITE CARROT CUP CAKE 150G', 'productPool/1.jpg', 267 ),
( 'ELITE CARROT PUDDING CAKE 275G', 'productPool/1.jpg', 254 ),
( 'ELITE CARROT PUDDING CAKE 500G', 'productPool/1.jpg', 95 ),
( 'ELITE CHAKKI FRESH ATTA1KG', 'productPool/1.jpg', 194 ),
( 'ELITE CHAKKIATTA 1.2KG', 'productPool/1.jpg', 193 ),
( 'ELITE CHEMPA PUTTU PODI 500G', 'productPool/1.jpg', 278 ),
( 'ELITE CHERRY NUT CAKE 330G', 'productPool/1.jpg', 152 ),
( 'ELITE CHOCLATE PLUM DELIGHT CAKES 350G', 'productPool/1.jpg', 12 ),
( 'ELITE CHOCO PLUM CAKE 330G', 'productPool/1.jpg', 270 ),
( 'ELITE CHOCO PUDDING CAKE 275G', 'productPool/1.jpg', 229 ),
( 'ELITE CHOCO PUDDING CAKE 500G', 'productPool/1.jpg', 21 ),
( 'ELITE CUP BUTTER CAKE170G', 'productPool/1.jpg', 253 ),
( 'ELITE CUP CAKE CHOCO 100G', 'productPool/1.jpg', 192 ),
( 'ELITE CUP CAKE STRAWBEERY 170G', 'productPool/1.jpg', 192 ),
( 'ELITE CUP CHOCOLATE CAKE 170G', 'productPool/1.jpg', 145 ),
( 'ELITE DATES PUDDING CAKE 500G', 'productPool/1.jpg', 182 ),
( 'ELITE DATES PUDDING CAKE275G', 'productPool/1.jpg', 127 ),
( 'ELITE DELITE RICE PUTTU PODI 1KG', 'productPool/1.jpg', 190 ),
( 'ELITE DELITE RICE PUTTU PODI 500G', 'productPool/1.jpg', 275 ),
( 'ELITE DOUBLE ROASTED RAVA 500G', 'productPool/1.jpg', 84 ),
( 'ELITE DOUBLE ROASTED RAVA1KG', 'productPool/1.jpg', 1 ),
( 'ELITE EASY PALAPPAM 500G', 'productPool/1.jpg', 269 ),
( 'ELITE ELAICHI RUSK 200G', 'productPool/1.jpg', 93 ),
( 'ELITE FRUIT SLICE CAKE 160G', 'productPool/1.jpg', 264 ),
( 'ELITE INSTANT PALADA PAYASAM MIX 200G', 'productPool/1.jpg', 133 ),
( 'ELITE INSTANT VERMICELLI PAYASAM MIX 300G', 'productPool/1.jpg', 269 ),
( 'ELITE JACKFRUIT PUDDING CAKE 275G', 'productPool/1.jpg', 16 ),
( 'ELITE JACKFRUIT PUDDING CAKE 500G', 'productPool/1.jpg', 120 ),
( 'ELITE MAIDA 1KG', 'productPool/1.jpg', 36 ),
( 'ELITE MAIDA 500G', 'productPool/1.jpg', 259 ),
( 'ELITE MATTA BROKEN RICE 500G', 'productPool/1.jpg', 207 ),
( 'ELITE MILK RUSK 180GM', 'productPool/1.jpg', 128 ),
( 'ELITE MILK RUSK 204G', 'productPool/1.jpg', 167 ),
( 'ELITE MILK RUSK 270G+20G', 'productPool/1.jpg', 37 ),
( 'ELITE MILK RUSK 272G', 'productPool/1.jpg', 38 ),
( 'ELITE MILK RUSK RS 30', 'productPool/1.jpg', 27 ),
( 'ELITE MULTIGRAIN ATTA 1KG', 'productPool/1.jpg', 80 ),
( 'ELITE NATURAL OATS 1KG POUCH', 'productPool/1.jpg', 129 ),
( 'ELITE NATURAL OATS 500G', 'productPool/1.jpg', 14 ),
( 'ELITE ORANGE CAKE 80G', 'productPool/1.jpg', 234 ),
( 'ELITE ORGINAL RUSK 428G', 'productPool/1.jpg', 139 ),
( 'ELITE ORIGINAL RUSK 375G', 'productPool/1.jpg', 245 ),
( 'ELITE ORIGINAL RUSK 480G', 'productPool/1.jpg', 124 ),
( 'ELITE PALADA PAYASAM MIX 300G', 'productPool/1.jpg', 48 ),
( 'ELITE PINE APPLE CAKE 300G', 'productPool/1.jpg', 225 ),
( 'ELITE PINEAPLE CAKE 80G', 'productPool/1.jpg', 76 ),
( 'ELITE PINEAPPLE BAR CAKE130G', 'productPool/1.jpg', 121 ),
( 'ELITE PINEAPPLE CAKE 350G', 'productPool/1.jpg', 240 ),
( 'ELITE PLUM CAKE 300 G', 'productPool/1.jpg', 41 ),
( 'ELITE PLUM CLASSIC 680G', 'productPool/1.jpg', 64 ),
( 'ELITE PLUM DELIGHT CAKE 680G', 'productPool/1.jpg', 177 ),
( 'ELITE PLUM SURPRISE CAKES 330G', 'productPool/1.jpg', 183 ),
( 'ELITE PLUM SURPRISE CAKES 680G', 'productPool/1.jpg', 148 ),
( 'ELITE PREMIUM RICE PUTTU PODI 500G', 'productPool/1.jpg', 204 ),
( 'ELITE PREMIUM RICE PUTTUPODI 1KG', 'productPool/1.jpg', 51 ),
( 'ELITE RAGI PUTTU PODI 500G', 'productPool/1.jpg', 46 ),
( 'ELITE RICE POWDER 1KG', 'productPool/1.jpg', 253 ),
( 'ELITE RICE POWDER 500G', 'productPool/1.jpg', 245 ),
( 'ELITE RICE PUTTU PODI 1.2KG', 'productPool/1.jpg', 170 ),
( 'ELITE RICE PUTTUPODI 500G', 'productPool/1.jpg', 102 ),
( 'ELITE RICH PLUM CAKE 600G', 'productPool/1.jpg', 26 ),
( 'ELITE ROAST RAVA 1KG', 'productPool/1.jpg', 46 ),
( 'ELITE ROASTED RAGI POWDER 500G', 'productPool/1.jpg', 178 ),
( 'ELITE ROASTED RAVA 500Gms', 'productPool/1.jpg', 247 ),
( 'ELITE ROSTED RAVA 1KG', 'productPool/1.jpg', 61 ),
( 'ELITE SAMBA BROKEN WHEAT 500G', 'productPool/1.jpg', 243 ),
( 'ELITE SAMBA BROKN WHEAT 500G', 'productPool/1.jpg', 173 ),
( 'ELITE SOOJI ELAICHI RUSK 250G', 'productPool/1.jpg', 167 ),
( 'ELITE SOOJI RUSK 180G', 'productPool/1.jpg', 84 ),
( 'ELITE SOOJI RUSK 204G', 'productPool/1.jpg', 66 ),
( 'ELITE SPONGE CAKE300G', 'productPool/1.jpg', 125 ),
( 'ELITE TASTY TREAT', 'productPool/1.jpg', 107 ),
( 'ELITE UPPUMA MIX 200G', 'productPool/1.jpg', 141 ),
( 'ELITE VERMICELLI PAYASAM MIX 200G', 'productPool/1.jpg', 30 ),
( 'ELITE WHEAT PUTTU PODI 500G', 'productPool/1.jpg', 83 ),
( 'ELITE WHOLE WHEAT ATTA 1KG', 'productPool/1.jpg', 138 ),
( 'ELITE WHOLE WHEAT ATTA 5KG', 'productPool/1.jpg', 142 ),
( 'ELITE WHOLE WHEAT RUSK 200G', 'productPool/1.jpg', 185 ),
( 'ELITEBLACK RAISIN RICHCAKE 150G', 'productPool/1.jpg', 225 ),
( 'ELKOS GENIUS BALL PEN', 'productPool/1.jpg', 272 ),
( 'ELKOS JAVA PEN', 'productPool/1.jpg', 271 ),
( 'ELKOS LITTLE ANGEL SKETCH PEN SMALL', 'productPool/1.jpg', 133 ),
( 'ELKOS OXER PEN', 'productPool/1.jpg', 122 ),
( 'ELKOS PEN', 'productPool/1.jpg', 101 ),
( 'ELKOS QUBA GLITTER GEL PEN', 'productPool/1.jpg', 11 ),
( 'ELKOS QUE GEL PEN', 'productPool/1.jpg', 203 ),
( 'ELKOS ULTRA BALL PEN', 'productPool/1.jpg', 86 ),
( 'ELKOS WILLY SKETCH PEN BIG', 'productPool/1.jpg', 249 ),
( 'ELLE 18 NAIL POPS SHADE - 31', 'productPool/1.jpg', 15 ),
( 'ELLE 18 NAIL POPS SHADE-30', 'productPool/1.jpg', 41 ),
( 'ELLUNDA 20NOS', 'productPool/1.jpg', 279 ),
( 'EMAMI 7 OILS IN ONE DAMAGE CONTROL HAIR OIL 100ML', 'productPool/1.jpg', 149 ),
( 'EMAMI BOROPLUS H-POWDER ICE COOL 150GM', 'productPool/1.jpg', 121 ),
( 'EMAMI FAIR & HANDSOME 15GMS', 'productPool/1.jpg', 85 ),
( 'EMAMI FAIR & HANDSOME 30GMS', 'productPool/1.jpg', 226 ),
( 'EMAMI FAIR & HANDSOME CREAM 60G', 'productPool/1.jpg', 33 ),
( 'EMAMI FAIR & HANDSOME FACE WASH 100GMS', 'productPool/1.jpg', 91 ),
( 'EMAMI FAIR & HANDSOME LASER 12 CREAM 60G', 'productPool/1.jpg', 91 ),
( 'EMAMI FAIR AND HANDSOME 15G', 'productPool/1.jpg', 275 ),
( 'EMAMI FAIR AND HANDSOME 50G', 'productPool/1.jpg', 244 ),
( 'EMAMI FAIR AND HANDSOME CREAM 30G', 'productPool/1.jpg', 37 ),
( 'EMAMI FAIR AND HANDSOME CREAM 30ML', 'productPool/1.jpg', 181 ),
( 'EMAMI FAIR AND HANDSOME CREAM 60 ML', 'productPool/1.jpg', 185 ),
( 'EMAMI FAIR AND HANDSOME FACE WASH 50GM', 'productPool/1.jpg', 257 ),
( 'EMAMI FAIR AND HANDSOME FAIRNESS CREAM FOR MEN', 'productPool/1.jpg', 196 ),
( 'EMAMI FAIR AND HANDSOME FAIRNESS FACE WASH 100G', 'productPool/1.jpg', 177 ),
( 'EMAMI FAIR AND HANDSOME FAIRNESS FACE WASH 50G', 'productPool/1.jpg', 233 ),
( 'EMAMI FAIR AND HANDSOME OIL CONTROL FACEWASH100G', 'productPool/1.jpg', 70 ),
( 'EMAMI FAIR AND HANDSOME50G', 'productPool/1.jpg', 213 ),
( 'EMAMI FAIR HANDSOME OIL CLEAR FACE WASH50G', 'productPool/1.jpg', 86 ),
( 'EMAMI FAIR& HANDSOME LASER12 CREAM 30G', 'productPool/1.jpg', 242 ),
( 'EMAMI GOLDEN BEAUTY TALC 100G', 'productPool/1.jpg', 99 ),
( 'EMAMI GOLDEN BEAUTY TALC 400G B1G1 MOON DROP', 'productPool/1.jpg', 32 ),
( 'EMAMI GOLDEN BEAUTY TALC MD100G', 'productPool/1.jpg', 50 ),
( 'EMAMI HE BODY SPRAY MEN 150ML', 'productPool/1.jpg', 229 ),
( 'EMAMI MALAI KESAR COLD CREAM 30MKL', 'productPool/1.jpg', 257 ),
( 'EMAMI NAVARATHNA ICOOL TALC 100G', 'productPool/1.jpg', 224 ),
( 'EMAMI NAVARATNA OIL 100 ML', 'productPool/1.jpg', 110 ),
( 'EMAMI NAVARATNA OIL 200 ML', 'productPool/1.jpg', 268 ),
( 'EMAMI NAVARATNA OIL 50 ML', 'productPool/1.jpg', 262 ),
( 'EMAMI TALC 400GM B1G1 ALPINE DEW FRENCH', 'productPool/1.jpg', 94 ),
( 'EMAMI VASOCARE JELLY25ML', 'productPool/1.jpg', 91 ),
( 'EMAMI ZANDU BALM 8ML', 'productPool/1.jpg', 55 ),
( 'EMAMIFAIR AND HANDSOME FACE WASH 150G', 'productPool/1.jpg', 121 ),
( 'EMPEROR SAFAWI DATES 400G', 'productPool/1.jpg', 139 ),
( 'ENCHANTEOUR PURE ROMANTIC SOAP', 'productPool/1.jpg', 230 ),
( 'ENCHANTER BODY LOTION 100ML', 'productPool/1.jpg', 74 ),
( 'ENCHANTEUR CHARMING TALC 125 gm', 'productPool/1.jpg', 21 ),
( 'ENCHANTEUR CHARMING TALC 75 gm', 'productPool/1.jpg', 188 ),
( 'ENCHANTER LOTION 100ML IMP', 'productPool/1.jpg', 4 ),
( 'ENCHANTER LOTION IMP', 'productPool/1.jpg', 128 ),
( 'ENCHANTER ROMANTIC TALC 250G', 'productPool/1.jpg', 154 ),
( 'ENCHANTEUR BODY LOTION COCOA 250ML', 'productPool/1.jpg', 40 ),
( 'ENCHANTEUR BODY LOTION100M', 'productPool/1.jpg', 44 ),
( 'ENCHANTEUR CHAR SOAP 100G', 'productPool/1.jpg', 151 ),
( 'ENCHANTEUR CHARMING BODY LOTION 250ML', 'productPool/1.jpg', 253 ),
( 'ENCHANTEUR CHARMING SOAP 75G', 'productPool/1.jpg', 21 ),
( 'ENCHANTEUR CHARMING TALC 250G', 'productPool/1.jpg', 72 ),
( 'ENCHANTEUR DEO CHARMING', 'productPool/1.jpg', 47 ),
( 'ENCHANTEUR DEO ROMANTIC', 'productPool/1.jpg', 31 ),
( 'ENCHANTEUR ROMANTIC BODY LOTION 250ML', 'productPool/1.jpg', 260 ),
( 'ENCHANTEUR ROMANTIC SOAP 75G', 'productPool/1.jpg', 107 ),
( 'ENCHANTEUR ROMANTIC TALC 125G', 'productPool/1.jpg', 3 ),
( 'ENCHANTEUR ROMANTIC TALC 75G', 'productPool/1.jpg', 278 ),
( 'ENGAGE BLUSH WOMAN 110G', 'productPool/1.jpg', 105 ),
( 'ENGAGE CITRUS FRESH POCKET PERFUME 18ML', 'productPool/1.jpg', 252 ),
( 'ENGAGE DAY AND NIGHT MAN 28ML', 'productPool/1.jpg', 23 ),
( 'ENGAGE DAY AND NIGHT WOMEN 28ML', 'productPool/1.jpg', 183 ),
( 'ENGAGE DEO COMBO', 'productPool/1.jpg', 58 ),
( 'ENGAGE DEO INTRIGUE 150ML', 'productPool/1.jpg', 143 ),
( 'ENGAGE DRIZZLE DEO SPRAY 165ML', 'productPool/1.jpg', 125 ),
( 'ENGAGE EAU DE PARFUM FEMME 90ML', 'productPool/1.jpg', 71 ),
( 'ENGAGE EAU DE PARFUM HOMME 90ML', 'productPool/1.jpg', 236 ),
( 'ENGAGE EAU DE PARFUM YANG 90ML', 'productPool/1.jpg', 260 ),
( 'ENGAGE EAU DE PARFUM YIN 90ML', 'productPool/1.jpg', 150 ),
( 'ENGAGE FROST MAN DEO 165ML', 'productPool/1.jpg', 235 ),
( 'ENGAGE M1 PERFUME SPRAY 120ML', 'productPool/1.jpg', 140 ),
( 'ENGAGE M2 PERFUME SPARY 120ML', 'productPool/1.jpg', 265 ),
( 'ENGAGE M3 PERFUME SPRAY 120ML', 'productPool/1.jpg', 206 ),
( 'ENGAGE M4 PERFUME SPRAY 120ML', 'productPool/1.jpg', 98 ),
( 'ENGAGE MAN SILVER MUSK 18ML', 'productPool/1.jpg', 191 ),
( 'ENGAGE MAN SPIRIT 150ML', 'productPool/1.jpg', 39 ),
( 'ENGAGE MAN SPORT FRESH DEO 150ML', 'productPool/1.jpg', 191 ),
( 'ENGAGE MATE MEN DEO 165ML', 'productPool/1.jpg', 204 ),
( 'ENGAGE ON MEN 2 IN 1 WORK AND PARTY 28ML', 'productPool/1.jpg', 37 ),
( 'ENGAGE ON CLASSIC WOODY POCKET PERFUME 18ML', 'productPool/1.jpg', 215 ),
( 'ENGAGE ON COOL AQUA POCKET PERFUME 18ML', 'productPool/1.jpg', 109 ),
( 'ENGAGE ON COOL MARINE POCKET PERFUME 18ML', 'productPool/1.jpg', 38 ),
( 'ENGAGE ON EAU DE ARGENTIA 10ML', 'productPool/1.jpg', 178 ),
( 'ENGAGE ON EAU DE IMPERIAL 10ML', 'productPool/1.jpg', 109 ),
( 'ENGAGE ON FLORAL FRESH POCKET PERFUME 18ML', 'productPool/1.jpg', 157 ),
( 'ENGAGE ON POCKET BREEZY FLIP PERFUME', 'productPool/1.jpg', 264 ),
( 'ENGAGE ON POCKET FOREST FLIP PERFUME', 'productPool/1.jpg', 127 ),
( 'ENGAGE ON POCKET MUSKY FLIP PERFUME', 'productPool/1.jpg', 96 ),
( 'ENGAGE ON SWEET BLOSSOM POCKET PERFUME 18ML', 'productPool/1.jpg', 195 ),
( 'ENGAGE RUSH MAN DEO 165ML', 'productPool/1.jpg', 54 ),
( 'ENGAGE SPELL DEO WOMAN 165ML', 'productPool/1.jpg', 227 ),
( 'ENGAGE SPORT COOL HER DEO 150ML', 'productPool/1.jpg', 174 ),
( 'ENGAGE SPORT COOL HIM DEO 150ML', 'productPool/1.jpg', 146 ),
( 'ENGAGE TEASE DEO WOMAN 165ML', 'productPool/1.jpg', 62 ),
( 'ENGAGE TEMPT DEO SPRAY', 'productPool/1.jpg', 123 ),
( 'ENGAGE URGE DEO MEN 165ML', 'productPool/1.jpg', 278 ),
( 'ENGAGE W1 PERFUME SPRAY 120ML', 'productPool/1.jpg', 255 ),
( 'ENGAGE W2 PERFUME SPARY 120ML', 'productPool/1.jpg', 152 ),
( 'ENGAGE W3 PERFUME SPRAY 120ML', 'productPool/1.jpg', 263 ),
( 'ENGAGE W4 PERFUME SPRAY 120ML', 'productPool/1.jpg', 243 ),
( 'ENGAGE WOMAN INTRIGUE 150ML', 'productPool/1.jpg', 111 ),
( 'ENGAGE WOMAN SPIRIT 150ML', 'productPool/1.jpg', 86 ),
( 'ENGAGE WOMAN SPORT FRSH DEO 150ML', 'productPool/1.jpg', 77 ),
( 'ENGAGE WOMAN WORK AND PARTY 2 IN 1 28ML', 'productPool/1.jpg', 53 ),
( 'ENO 5GM PLAIN SACHET', 'productPool/1.jpg', 45 ),
( 'ENO COLA FLAVOUR 5G', 'productPool/1.jpg', 222 ),
( 'ENO COOLING LEMON 5G', 'productPool/1.jpg', 10 ),
( 'ENO LEMON 100G', 'productPool/1.jpg', 117 ),
( 'ENO LEMON FLAVOUR FRUIT SALT 60N', 'productPool/1.jpg', 55 ),
( 'ENO SACHET LEMON 5G', 'productPool/1.jpg', 89 ),
( 'ENSURE CHOCOLATE 400G', 'productPool/1.jpg', 128 ),
( 'ENSURE CHOCOLATE 400G JAR', 'productPool/1.jpg', 32 ),
( 'ENSURE DIABETES CARE VANILLA 1KG', 'productPool/1.jpg', 75 ),
( 'ENSURE VANILA 1 KG TIN', 'productPool/1.jpg', 98 ),
( 'ENSURE VANILLA REFILL 1KG', 'productPool/1.jpg', 233 ),
( 'ERAND TAIL 50ML', 'productPool/1.jpg', 35 ),
( 'ERASER RS 10', 'productPool/1.jpg', 182 ),
( 'ERASER RS 30', 'productPool/1.jpg', 56 ),
( 'ERASER RS 4.50', 'productPool/1.jpg', 16 ),
( 'ERASER RS30', 'productPool/1.jpg', 16 ),
( 'ERASER RS5', 'productPool/1.jpg', 223 ),
( 'EROZ WHITE GRAPE JUICE 750ML IMP', 'productPool/1.jpg', 18 ),
( 'ETIQUETTE MISTY DEW WET WIPES', 'productPool/1.jpg', 45 ),
( 'EUROPE CHEWING GUM 11G', 'productPool/1.jpg', 215 ),
( 'EVA APPLE JUICE 750ML', 'productPool/1.jpg', 57 ),
( 'EVA BLUSHDEO 125ML', 'productPool/1.jpg', 112 ),
( 'EVA DEO DOLL 125ML', 'productPool/1.jpg', 202 ),
( 'EVA DEO FRESH 125ML', 'productPool/1.jpg', 8 ),
( 'EVA DEO SWEET 125ML', 'productPool/1.jpg', 132 ),
( 'EVA DEW DEO 125ML', 'productPool/1.jpg', 240 ),
( 'EVA EVA FLIRT 75G', 'productPool/1.jpg', 60 ),
( 'EVA EVA FRESH TALC POWDER 50G', 'productPool/1.jpg', 175 ),
( 'EVA EVA SANDAL 100G', 'productPool/1.jpg', 40 ),
( 'EVA EVA SANDAL 50G', 'productPool/1.jpg', 127 ),
( 'EVA EVA WILD 75G', 'productPool/1.jpg', 226 ),
( 'EVA MYSTIQUE TALC 100G', 'productPool/1.jpg', 123 ),
( 'EVA MYSTIQUE TALC 50G', 'productPool/1.jpg', 79 ),
( 'EVA  EXOCTIC ROSE 50G', 'productPool/1.jpg', 3 ),
( 'EVA  EXOCTIC ROSE 100G', 'productPool/1.jpg', 222 ),
( 'EVA PERFUMED TALC 100GM', 'productPool/1.jpg', 83 ),
( 'EVA  FLORAL FUN FANTASY 100G', 'productPool/1.jpg', 186 ),
( 'EVA RE GRAPE 750ML', 'productPool/1.jpg', 146 ),
( 'EVA SPORTZ BOUNCE DEO 125ML', 'productPool/1.jpg', 150 ),
( 'EVA SPORTZ RUSH DEO 125ML', 'productPool/1.jpg', 35 ),
( 'EVA SPORTZ SKIP DEO 125ML', 'productPool/1.jpg', 61 ),
( 'EVA SWEETROSE TALC 100G', 'productPool/1.jpg', 178 ),
( 'EVA URBANE DEO 125ML', 'productPool/1.jpg', 189 ),
( 'EVA WHITE GRAPE JUICE 750ML', 'productPool/1.jpg', 157 ),
( 'EVEREADY 10005 BATTERY', 'productPool/1.jpg', 34 ),
( 'EVEREADY 1035 BATTERY', 'productPool/1.jpg', 278 ),
( 'EVEREADY 1050 BATTERY', 'productPool/1.jpg', 83 ),
( 'EVEREADY AAA 1012 BATTERY', 'productPool/1.jpg', 153 ),
( 'EVERGREEN CLOTH CLIP BIG 12P', 'productPool/1.jpg', 236 ),
( 'EVERGREEN CLOTH CLIP SMALL 12P', 'productPool/1.jpg', 182 ),
( 'EVEREADY AA 1015 BATTERY', 'productPool/1.jpg', 46 ),
( 'EVERYDAY FISH WASH 250ML', 'productPool/1.jpg', 179 ),
( 'EVERYDAY VEGGIE WASH 250ML', 'productPool/1.jpg', 156 ),
( 'EVERYUTH APRICOT SCRUB 50G', 'productPool/1.jpg', 75 ),
( 'EVERYUTH CUCUMBER FACE PACK 50G', 'productPool/1.jpg', 121 ),
( 'EVERYUTH FRUIT FACE WASH 50G', 'productPool/1.jpg', 211 ),
( 'EVERYUTH GOLDEN GLOW PEEL OFF MASK 30G', 'productPool/1.jpg', 45 ),
( 'EVERYUTH GOLDEN GLOW PEEL OFF MASK 50G', 'productPool/1.jpg', 50 ),
( 'EVERYUTH HALDI CHANDAN FACE PACK 25G', 'productPool/1.jpg', 160 ),
( 'EVERYUTH LEMON CHERRY FACE WASH 50G', 'productPool/1.jpg', 278 ),
( 'EVERYUTH LEMON FACE WASH 50G', 'productPool/1.jpg', 98 ),
( 'EVERYUTH NEEM FACE PACK 25G', 'productPool/1.jpg', 156 ),
( 'EVERYUTH NEEM FACE WASH 50G', 'productPool/1.jpg', 34 ),
( 'EVERYUTH NEEM PAPAYA SCRUB 25G', 'productPool/1.jpg', 69 ),
( 'EVERYUTH NEEM PAPAYA SCRUB 50G', 'productPool/1.jpg', 44 ),
( 'EVERYUTH ORANGE MASK 50G', 'productPool/1.jpg', 226 ),
( 'EVERYUTH PAPAYA FACE PACK 25G', 'productPool/1.jpg', 41 ),
( 'EVERYUTH ROSE FACE PACK 25G', 'productPool/1.jpg', 21 ),
( 'EVERYUTH TULISI TURMERIC FACE WASH 100G', 'productPool/1.jpg', 132 ),
( 'EVERYUTH TULISI TURMERIC FACE WASH 50G', 'productPool/1.jpg', 160 ),
( 'EVERYUTH WAL APRI SCRUB 50G', 'productPool/1.jpg', 53 ),
( 'EVERYUTH WAL NUT SCRUB 50G', 'productPool/1.jpg', 182 ),
( 'EVLIYA JIVAL CHOCOLATE BOX 650G IMP', 'productPool/1.jpg', 86 ),
( 'EVLIYA TRENT CHOCOLATE BOX 400G IMP', 'productPool/1.jpg', 85 ),
( 'EVLIYA TRENT CHOCOLATE BOX 435G IMP', 'productPool/1.jpg', 205 ),
( 'EVLIYA TRENT CHOCOLATE BOX 500G IMP', 'productPool/1.jpg', 149 ),
( 'EVLIYA TRENT CHOCOLATE BOX 650G IMP', 'productPool/1.jpg', 118 ),
( 'EVLIYA WALNUT DUO CHOCOLATE 2KG', 'productPool/1.jpg', 27 ),
( 'EXAM PAD', 'productPool/1.jpg', 24 ),
( 'EXAM PAD 3D', 'productPool/1.jpg', 212 ),
( 'EXAM PAD 444 24CM*36CM', 'productPool/1.jpg', 155 ),
( 'EXAM PAD H 3D', 'productPool/1.jpg', 95 ),
( 'EXAM PAD PLASTIC MODEL NO 501', 'productPool/1.jpg', 68 ),
( 'EXCEL PIZZA CUTTER', 'productPool/1.jpg', 43 ),
( 'EXCEL SOFT GRIP PLAIN KNIFE', 'productPool/1.jpg', 124 ),
( 'EXCEL SOFT GRIP TOMATO KNIFE', 'productPool/1.jpg', 119 ),
( 'EXCELL LEMON SQEEZER', 'productPool/1.jpg', 10 ),
( 'EXIDE 6FL 40H BATTERY', 'productPool/1.jpg', 124 ),
( 'EXO BACTO SCRUB 2 IN 1 MRP 20', 'productPool/1.jpg', 111 ),
( 'EXO DISH SHINE BAR 300G', 'productPool/1.jpg', 21 ),
( 'EXO DISH SHINE BAR 75G', 'productPool/1.jpg', 95 ),
( 'EXO DISH WASH BAR 100G', 'productPool/1.jpg', 221 ),
( 'EXO DISH WASH BAR 170G', 'productPool/1.jpg', 126 ),
( 'EXO DISHWASH BAR 170G', 'productPool/1.jpg', 61 ),
( 'EXO FLOOR SHINE LIQUID JASMINE 500ML', 'productPool/1.jpg', 62 ),
( 'EXO FLOOR SHINE LIQUID TULSI 500ML', 'productPool/1.jpg', 139 ),
( 'EXO FLOOR SHINE MAHAGANY 500ML', 'productPool/1.jpg', 162 ),
( 'EXO FLOOR SHINE MAHOGANY 200ML', 'productPool/1.jpg', 170 ),
( 'EXO LEMON LIQUID 250ML', 'productPool/1.jpg', 150 ),
( 'EXO LEMONZING POWDER 1KG', 'productPool/1.jpg', 55 ),
( 'EXO LIQUID 80ML', 'productPool/1.jpg', 5 ),
( 'EXO ROUND 500G (EXO BAR 130G FREE)', 'productPool/1.jpg', 168 ),
( 'EXO ROUND 700GMS', 'productPool/1.jpg', 31 ),
( 'EXO SAFAI 2 IN 1 SET', 'productPool/1.jpg', 41 ),
( 'EXO SAFAI BIG', 'productPool/1.jpg', 205 ),
( 'EXO SAFAI DISHSCRUB', 'productPool/1.jpg', 140 ),
( 'EXO SAFAI STEEL SCRUBBER', 'productPool/1.jpg', 150 ),
( 'EXO SAFAI STEEL SCRUBBER 20GM', 'productPool/1.jpg', 71 ),
( 'EXO SAFAI STRONG SCRUBBER', 'productPool/1.jpg', 151 ),
( 'EXO SUPER GEL 250G', 'productPool/1.jpg', 24 ),
( 'EXO T&S ROUND 250GM', 'productPool/1.jpg', 175 ),
( 'EXO TOUCH & SHINE SCOURING POWDER 1KG', 'productPool/1.jpg', 77 ),
( 'EXO TOUCH AND SHINE BAR 300G RS-24', 'productPool/1.jpg', 241 ),
( 'EXO TOUCH AND SHINE LIQUID 250ML', 'productPool/1.jpg', 142 ),
( 'EXO TOUCH AND SHINE POWDER 1.1KG', 'productPool/1.jpg', 11 ),
( 'EXO TOUCH AND SHINE POWDER 400G', 'productPool/1.jpg', 199 ),
( 'EXPERT BROWN CREAM', 'productPool/1.jpg', 76 ),
( 'EXPERT CREAM BURGUNDY', 'productPool/1.jpg', 125 ),
( 'EXPERT EASY HAIR COLOUR SHAMPOO10ML', 'productPool/1.jpg', 203 ),
( 'EXPERT RICH CREME NATURAL BLACK 20ML', 'productPool/1.jpg', 263 ),
( 'EYE ROLL-ON 15 ML', 'productPool/1.jpg', 170 ),
( 'EYECONIC KAJAL 22HR', 'productPool/1.jpg', 140 ),
( 'EYETEX DAZLER EYE LINER 6.5G', 'productPool/1.jpg', 118 ),
( 'EYETEX DAZLLER EYEBROW PENCIL', 'productPool/1.jpg', 202 ),
( 'EYETEX DEO N FRESH SANI CUBES 90G', 'productPool/1.jpg', 84 ),
( 'EYETEX KAJAL STICK 1.5G', 'productPool/1.jpg', 125 ),
( 'EYETEX KAJAL STICK 3.5G', 'productPool/1.jpg', 205 ),
( 'EYETEX KAJAL SUPREME 2G', 'productPool/1.jpg', 156 ),
( 'EYETEX PALLAVI SINDOOR 15G', 'productPool/1.jpg', 233 ),
( 'EYETEX PALLAVI SINDOOR STICK 1.5G', 'productPool/1.jpg', 212 ),
( 'EYETEX PALLAVI SINDOOR STICK 3.5G', 'productPool/1.jpg', 56 ),
( 'EYTEX STANDARD RS10', 'productPool/1.jpg', 161 ),
( 'EZEE CLING WRAP 30MTR', 'productPool/1.jpg', 99 ),
( 'EZEE DETERGENT LIQUID 500ML', 'productPool/1.jpg', 94 ),
( 'EZEE PAPER STRAW 6MM', 'productPool/1.jpg', 53 ),
( 'EZEE PAPER STRAW 8MM', 'productPool/1.jpg', 95 ),
( 'FA DRY PROTECT ROLL ON 50ML', 'productPool/1.jpg', 181 ),
( 'FA FLORAL PROTECT ORCHID &VIOLA 502ML', 'productPool/1.jpg', 144 ),
( 'FA FRESH &DRY 50ML', 'productPool/1.jpg', 204 ),
( 'FA GLAMOROUS MOMENTS ROLL ON 50ML', 'productPool/1.jpg', 152 ),
( 'FA INVISIBLE POWER ROLL ON 50ML', 'productPool/1.jpg', 103 ),
( 'FA MEN SPORT ROLL ON 50ML', 'productPool/1.jpg', 36 ),
( 'FA PINK PASSION ROLL ON 50ML', 'productPool/1.jpg', 212 ),
( 'FA ROLL ON MYSTIC MOMENTS 50ML', 'productPool/1.jpg', 81 ),
( 'FA SPORT ENERGIZING FRESH ROLL ON 50ML', 'productPool/1.jpg', 182 ),
( 'FA AQUA FRESH 50ML', 'productPool/1.jpg', 36 ),
( 'FABER 24 COLOUR PENCILS', 'productPool/1.jpg', 241 ),
( 'FABER CASTELL 12 BI COLOUR PENCILS', 'productPool/1.jpg', 50 ),
( 'FABER CASTELL 12 CRAYONS', 'productPool/1.jpg', 135 ),
( 'FABER CASTELL 12 JUMBO WAX CRAYONS', 'productPool/1.jpg', 236 ),
( 'FABER CASTELL 12 POSTER COLOUR', 'productPool/1.jpg', 228 ),
( 'FABER CASTEL 12 WAX CRAYONS', 'productPool/1.jpg', 158 ),
( 'FABER CASTELL 15 OIL PASTEL 60ML', 'productPool/1.jpg', 76 ),
( 'FABER CASTELL 15 TRAIN CRAYONS', 'productPool/1.jpg', 141 ),
( 'FABER CASTELL 5 PASTEL PEN', 'productPool/1.jpg', 268 ),
( 'FABER CASTELL 6 COLORS', 'productPool/1.jpg', 144 ),
( 'FABER CASTELL OIL PAINT BRUSHES 3', 'productPool/1.jpg', 159 ),
( 'FABER CASTEL OIL PAINT BRUSHES RS140', 'productPool/1.jpg', 191 ),
( 'FABER CASTEL PAINT BRUSHES PONY HAIR', 'productPool/1.jpg', 218 ),
( 'FABER CASTEL PONY HAIR PAINT BRUSHES', 'productPool/1.jpg', 60 ),
( 'FABER CASTELL 10 CD OHP MARKER BLACK', 'productPool/1.jpg', 84 ),
( 'FABER CASTELL 10 CD OHP MARKER PENS', 'productPool/1.jpg', 232 ),
( 'FABER CASTELL 10 CD OHP MARKER PENS RED', 'productPool/1.jpg', 101 ),
( 'FABER CASTELL 10 CONNECTOR PENS', 'productPool/1.jpg', 131 ),
( 'FABER CASTELL 10 LEAD 0.5 2B', 'productPool/1.jpg', 194 ),
( 'FABER CASTELL 12 FABRIC COLOURS', 'productPool/1.jpg', 210 ),
( 'FABER CASTELL 12 PENCIL', 'productPool/1.jpg', 272 ),
( 'FABER CASTELL 12 POSTER COLOURS', 'productPool/1.jpg', 28 ),
( 'FABER CASTELL 12 WATER COLOUR', 'productPool/1.jpg', 271 ),
( 'FABER CASTELL 15 CONNECTOR PENS', 'productPool/1.jpg', 74 ),
( 'FABER CASTELL 18 BI-COLOUR PENCILS', 'productPool/1.jpg', 47 ),
( 'FABER CASTELL 24 JUMBO WAX CRAYONS', 'productPool/1.jpg', 92 ),
( 'FABER CASTELL 24 WAX CRAYONS PLT', 'productPool/1.jpg', 58 ),
( 'FABER CASTELL 25 CONNECTOR PENS', 'productPool/1.jpg', 66 ),
( 'FABER CASTELL 25 OIL PASTELS', 'productPool/1.jpg', 96 ),
( 'FABER CASTELL 4 MODELLING DOUGH', 'productPool/1.jpg', 160 ),
( 'FABER CASTELL 50 OIL PASTELS', 'productPool/1.jpg', 171 ),
( 'FABER CASTELL 6 DRAWING PENCIL', 'productPool/1.jpg', 218 ),
( 'FABER CASTELL 6 FABRIC COLOURS', 'productPool/1.jpg', 267 ),
( 'FABER CASTELL 9 PONY ROUND', 'productPool/1.jpg', 48 ),
( 'FABER CASTELL 9 PONY ROUND 5', 'productPool/1.jpg', 231 ),
( 'FABER CASTELL ARTIST 12 WATER COLOUR', 'productPool/1.jpg', 161 ),
( 'FABER CASTELL BLACK MATT PENCIL', 'productPool/1.jpg', 132 ),
( 'FABER CASTELL CHILD SAFE SCISSORS', 'productPool/1.jpg', 255 ),
( 'FABER CASTELL CORRECTION PEN', 'productPool/1.jpg', 184 ),
( 'FABER CASTELL DUST ERASER', 'productPool/1.jpg', 28 ),
( 'FABER CASTELL ECON MECHANIC PENCIL 0.7MM', 'productPool/1.jpg', 103 ),
( 'FABER CASTELL ERASABLE PLASTIC CRAYONS', 'productPool/1.jpg', 28 ),
( 'FABER CASTELL EXAM PAD RS 100', 'productPool/1.jpg', 67 ),
( 'FABER CASTELL FX BALL PEN', 'productPool/1.jpg', 186 ),
( 'FABER CASTELL GLUE STICK 15G', 'productPool/1.jpg', 132 ),
( 'FABER CASTELL GLUE STICK 9 GMS', 'productPool/1.jpg', 248 ),
( 'FABER CASTELL INSTRUMENT BOX', 'productPool/1.jpg', 184 ),
( 'FABER CASTELL KINDER SCISSORS', 'productPool/1.jpg', 208 ),
( 'FABER CASTELL LEADS 0.5 HB PKT', 'productPool/1.jpg', 170 ),
( 'FABER CASTELL MODELLING 8 CLAY 100G', 'productPool/1.jpg', 168 ),
( 'FABER CASTELL MODELLING 8 CLAY SET 100G', 'productPool/1.jpg', 191 ),
( 'FABER CASTELL OLE GOLD PENCIL', 'productPool/1.jpg', 63 ),
( 'FABER CASTELL PAINT BRUSH 0', 'productPool/1.jpg', 122 ),
( 'FABER CASTELL PAINT BRUSH 1', 'productPool/1.jpg', 206 ),
( 'FABER CASTELL PAINT BRUSH 13 ROUND', 'productPool/1.jpg', 90 ),
( 'FABER CASTELL PAINT BRUSH 5', 'productPool/1.jpg', 40 ),
( 'FABER CASTELL PAINT BRUSH 6', 'productPool/1.jpg', 276 );