INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'GODREJ EXPERT BROWN MRP 30', 'productPool/1.jpg', 184 ),
( 'GODREJ EXPERT CREAM NATURAL BLACK', 'productPool/1.jpg', 45 ),
( 'GODREJ EXPERT CREME MULTIPACK NATURAL BLACK', 'productPool/1.jpg', 127 ),
( 'GODREJ EXPERTNTUB 24G', 'productPool/1.jpg', 93 ),
( 'GODREJ FABRIC ROLL-ON 8ML', 'productPool/1.jpg', 29 ),
( 'GODREJ GODREJ SHAVE CREAM MENTHOL 78G', 'productPool/1.jpg', 206 ),
( 'GODREJ GOOD KNIGHT ACTIVE REFIL 45ML', 'productPool/1.jpg', 249 ),
( 'GODREJ GOOD KNIGHT MOSQUITO COIL GREEN 10N', 'productPool/1.jpg', 190 ),
( 'GODREJ HAND WASH GREEN 300ML', 'productPool/1.jpg', 245 ),
( 'GODREJ HANDWASH BLUE 300ML', 'productPool/1.jpg', 216 ),
( 'GODREJ HANDWASH BLUE 300ML BOTTLE', 'productPool/1.jpg', 67 ),
( 'GODREJ HANDWASH GREEN POUCH 180ML 3+1', 'productPool/1.jpg', 165 ),
( 'GODREJ KALI MEHENDI 10G', 'productPool/1.jpg', 171 ),
( 'GODREJ KALIMEHENDI 25ML', 'productPool/1.jpg', 137 ),
( 'GODREJ MYLOCK CANDY MRP 167.00', 'productPool/1.jpg', 250 ),
( 'GODREJ MYLOCKPADLOCK NEEDS MRP186', 'productPool/1.jpg', 7 ),
( 'GODREJ NO 1 LIME ALOE VERA SOAP 125G', 'productPool/1.jpg', 273 ),
( 'GODREJ NO 1 SANDAL SOAP 125G', 'productPool/1.jpg', 115 ),
( 'GODREJ NO.1 ALOE VERA SOAP 70G', 'productPool/1.jpg', 9 ),
( 'GODREJ NO.1 LIME & ALOEVERA 100G', 'productPool/1.jpg', 105 ),
( 'GODREJ NO.1 LIME&ALOE VERA SOAP 70G', 'productPool/1.jpg', 158 ),
( 'GODREJ NO.1 ROSE 100G', 'productPool/1.jpg', 26 ),
( 'GODREJ NO.1 SANDAL SOAP 4*100G COMBI', 'productPool/1.jpg', 237 ),
( 'GODREJ NO.1 SANDAL SOAP 70G', 'productPool/1.jpg', 157 ),
( 'GODREJ NO1 COCONUT NEEM 400G', 'productPool/1.jpg', 170 ),
( 'GODREJ NO1 COCONUT NEEM 70G', 'productPool/1.jpg', 163 ),
( 'GODREJ NO1 JASMINE 400G', 'productPool/1.jpg', 76 ),
( 'GODREJ NUPUR HENNA POWDER 120G', 'productPool/1.jpg', 103 ),
( 'GODREJ NUPUR HENNA POWDER 50G', 'productPool/1.jpg', 187 ),
( 'GODREJ ORIGINAL NATURAL BLACK 408RS', 'productPool/1.jpg', 246 ),
( 'GODREJ PAD LOCK 7940', 'productPool/1.jpg', 183 ),
( 'GODREJ POCKET AER FRESH GREEN 10G', 'productPool/1.jpg', 69 ),
( 'GODREJ PROTEKT HANDWASH 3*180ML', 'productPool/1.jpg', 73 ),
( 'GODREJ PROTEKT MASTER HANDWASH 5L', 'productPool/1.jpg', 30 ),
( 'GODREJ PROTEKT MASTER HANDWASH 720ML', 'productPool/1.jpg', 96 ),
( 'GODREJ ROUND PADLOCKA 175 MRP', 'productPool/1.jpg', 211 ),
( 'GODREJ SHAVE CREAM SEN 78G', 'productPool/1.jpg', 255 ),
( 'GODREJ SHAVE CREAM SENS 20G', 'productPool/1.jpg', 213 ),
( 'GODREJ SHAVING CREAM COOL 20G', 'productPool/1.jpg', 146 ),
( 'GODREJ SHAVING ROUND 50G', 'productPool/1.jpg', 226 ),
( 'GODREJ SQUARE PADLOCK 6LEVERS WITH 4KEYS', 'productPool/1.jpg', 171 ),
( 'GODS OWN WALNUT', 'productPool/1.jpg', 55 ),
( 'GOHNSON ANDGOHNSONBAND AID MRP 60', 'productPool/1.jpg', 75 ),
( 'GOLD 916 WASHING SOAP 850G', 'productPool/1.jpg', 92 ),
( 'GOLD 916 WASHINSOAP 400G', 'productPool/1.jpg', 133 ),
( 'GOLD COIN ROUND', 'productPool/1.jpg', 35 ),
( 'GOLD LEAF OFFICE SCISSORS MS145', 'productPool/1.jpg', 204 ),
( 'GOLD LEAF OFFICE SCISSORS MS160', 'productPool/1.jpg', 32 ),
( 'GOLD LEAF SCISSORS MS125', 'productPool/1.jpg', 15 ),
( 'GOLD LEAF SCISSORS NO 6304', 'productPool/1.jpg', 29 ),
( 'GOLD WASHING BRUSH', 'productPool/1.jpg', 75 ),
( 'GOLD WINNER GROUN OIL POUCH 1LTR', 'productPool/1.jpg', 279 ),
( 'GOLD WINNER GROUNDNUT OIL 1LTR BOTTLE', 'productPool/1.jpg', 277 ),
( 'GOLD WINNER SUN FLOWER1LTR POUCH', 'productPool/1.jpg', 227 ),
( 'GOLD WINNER SUNFLOWER 500ML', 'productPool/1.jpg', 50 ),
( 'GOLD WINNER SUNFLOWER 5LTR', 'productPool/1.jpg', 268 ),
( 'GOLD WINNER SUNFLOWER OIL 1LTR BOTTLE', 'productPool/1.jpg', 98 ),
( 'GOLD WINNER SUNFLOWER OIL 2LT', 'productPool/1.jpg', 223 ),
( 'GOLD XL BAR SOAP 1KG', 'productPool/1.jpg', 158 ),
( 'GOLD-XL WASHING SOAP 900G', 'productPool/1.jpg', 34 ),
( 'GOLDEN CROWN BUTTON MUSHROOM 800G TIN', 'productPool/1.jpg', 179 ),
( 'GOLDEN KIWI', 'productPool/1.jpg', 6 ),
( 'GOLDEN PEAR', 'productPool/1.jpg', 210 ),
( 'GOLDEN STAR EGG NOODLES 900G', 'productPool/1.jpg', 222 ),
( 'GOLDWINNER VANASPATI 200ML', 'productPool/1.jpg', 134 ),
( 'GONE MAD CASHEW MITHAI STICK 12G', 'productPool/1.jpg', 109 ),
( 'GONE MAD CHOCO STICK 12G', 'productPool/1.jpg', 154 ),
( 'GONE MAD CHOCO STRAWBERRY STICKS 12G', 'productPool/1.jpg', 125 ),
( 'GONE MAD PREMIUM BADAM STICKS 100G', 'productPool/1.jpg', 161 ),
( 'GONE MAD PREMIUM COFFEE STICKS 100G', 'productPool/1.jpg', 63 ),
( 'GONE MAD PREMIUM DARK CHOCO STICK 100G', 'productPool/1.jpg', 202 ),
( 'GOOD DAY CASHEW PP 5+1 600G', 'productPool/1.jpg', 94 ),
( 'GOOD DAY CHUNKY COOKIES 60G', 'productPool/1.jpg', 158 ),
( 'GOOD GIRL BRUSH', 'productPool/1.jpg', 29 ),
( 'GOOD HOME AFRS ORCHADS 50G', 'productPool/1.jpg', 173 ),
( 'GOOD HOME AIR FLORAL FANTASY 50G', 'productPool/1.jpg', 68 ),
( 'GOOD HOME AIR FRESHENER DREAM DEW 75G', 'productPool/1.jpg', 54 ),
( 'GOOD HOME AIR FRESHNER LEMON ZEST 50G', 'productPool/1.jpg', 70 ),
( 'GOOD HOME AIR FRESHNER LEMON ZEST 75G', 'productPool/1.jpg', 155 ),
( 'GOOD HOME AIR FRESHNER ROSE', 'productPool/1.jpg', 208 ),
( 'GOOD HOME DRAIN CLEANER', 'productPool/1.jpg', 53 ),
( 'GOOD HOME DREAMS OF DEW 50G', 'productPool/1.jpg', 5 ),
( 'GOOD HOME FLORAL FANTASY 75GM', 'productPool/1.jpg', 95 ),
( 'GOOD HOME FR SOUL BLOSSOM 75G', 'productPool/1.jpg', 64 ),
( 'GOOD HOME ORCHARDS 75GM', 'productPool/1.jpg', 79 ),
( 'GOOD HOME ROOM FRESHENER SERENE AURA 160G', 'productPool/1.jpg', 193 ),
( 'GOOD HOME ROOM FRESHNER DREAMS OF DEW', 'productPool/1.jpg', 67 ),
( 'GOOD HOME ROOM FRESHNER FLORA', 'productPool/1.jpg', 137 ),
( 'GOOD HOME ROOM FRESHNER LEMON', 'productPool/1.jpg', 181 ),
( 'GOOD HOME ROOM FRESHNER SOUL BLOSSOM', 'productPool/1.jpg', 89 ),
( 'GOOD HOME ROOM FRESHNER WHISPERS OF PASSION', 'productPool/1.jpg', 119 ),
( 'GOOD HOME SOUL BLOSSOM', 'productPool/1.jpg', 9 ),
( 'GOOD KNIGHT ADV FAST CARD 10CARD', 'productPool/1.jpg', 55 ),
( 'GOOD KNIGHT ADVANCE XPRESS CARTRIDGE 35ML', 'productPool/1.jpg', 133 ),
( 'GOOD KNIGHT ADVANCED XPRESS DUAL MODE', 'productPool/1.jpg', 198 ),
( 'GOOD KNIGHT COOL GEL', 'productPool/1.jpg', 121 ),
( 'GOOD KNIGHT COOL GEL 50G', 'productPool/1.jpg', 177 ),
( 'GOOD KNIGHT FABRIC ROLL ON', 'productPool/1.jpg', 141 ),
( 'GOOD KNIGHT FABRIC ROLL ON 1.8ML', 'productPool/1.jpg', 271 ),
( 'GOOD KNIGHT GOLD FLASH COMBI 45ML', 'productPool/1.jpg', 202 ),
( 'GOOD KNIGHT GOLD FLASH REFILL 45ML', 'productPool/1.jpg', 78 ),
( 'GOOD KNIGHT NATURAL NEEM AGARBATTI 10N', 'productPool/1.jpg', 241 ),
( 'GOOD KNIGHT SILLVER 30 NOS MAT', 'productPool/1.jpg', 188 ),
( 'GOOD KNIGNT MACHINE1N', 'productPool/1.jpg', 11 ),
( 'GOOD LIFE MILK 1 LT', 'productPool/1.jpg', 48 ),
( 'GOOD LIFE MILK 500ML', 'productPool/1.jpg', 204 ),
( 'GOOD LIFE SAMPOORNA MILK 1LTR', 'productPool/1.jpg', 71 ),
( 'GOOD LIFE SLIM MILK 1LTR', 'productPool/1.jpg', 124 ),
( 'GOOD LIFE SLIM MILK 500ML', 'productPool/1.jpg', 277 ),
( 'GOOD MORNING SAVING LOTION 50ML', 'productPool/1.jpg', 64 ),
( 'GOOD NIGHT ADVANCE REFILL 45ML', 'productPool/1.jpg', 114 ),
( 'GOOD NIGHT PATCHES BABY SAFE 14N', 'productPool/1.jpg', 111 ),
( 'GOOD NIGHT SILVER REF 45ML 45NIGHTS', 'productPool/1.jpg', 24 ),
( 'GOODDAY CASHEW 100G PP', 'productPool/1.jpg', 97 ),
( 'GOODDAY CHOCO ALMOND 120G', 'productPool/1.jpg', 181 ),
( 'GOODDAY CHUNKY TRIPLE CHOCO CHIP COOKIES 120G', 'productPool/1.jpg', 213 ),
( 'GOODDAY CHUNKY TRIPLE CHOCOCHIP COOKIES 75G', 'productPool/1.jpg', 20 ),
( 'GOODDAY WONDERFULLS BERRIES 75G', 'productPool/1.jpg', 134 ),
( 'GOODDAY WONDERFULLS BUTTER 75G', 'productPool/1.jpg', 164 ),
( 'GOODDAY WONDERFULLS CHOCONUT 75G', 'productPool/1.jpg', 140 ),
( 'GOODKNIGHT MAHA JUMBO COIL', 'productPool/1.jpg', 241 ),
( 'GOODN HOME PASSION AIR FRESHNER', 'productPool/1.jpg', 261 ),
( 'GOODNIGHT ADVANCED LOWSMO10N', 'productPool/1.jpg', 215 ),
( 'GOODNIGHT ADVANCEDUALPOWER 45ML', 'productPool/1.jpg', 202 ),
( 'GOODNIGHT MAHA JUMBO', 'productPool/1.jpg', 121 ),
( 'GOODNIGHT MINI JUMB 10N', 'productPool/1.jpg', 24 ),
( 'GOODNIGHT SILVER POWER 30NIGHT 45ML', 'productPool/1.jpg', 141 ),
( 'GOODNIGHT SILVER POWER 45+NIGHT REFILL 45ML', 'productPool/1.jpg', 35 ),
( 'GOODNIGHT SILVER REFILL 45ML 60 NIGHT', 'productPool/1.jpg', 258 ),
( 'GOOFEE APRON', 'productPool/1.jpg', 173 ),
( 'GOOSEBERY', 'productPool/1.jpg', 145 ),
( 'GOPURAM SAMBRANI', 'productPool/1.jpg', 146 ),
( 'GORE MAD GHANA CHOCO STICKS 300G', 'productPool/1.jpg', 243 ),
( 'GORE MAD SHARING PACK CHOCO 26.4G', 'productPool/1.jpg', 204 ),
( 'GOVERNOR WASHING BRUSH', 'productPool/1.jpg', 51 ),
( 'GPET 550ML SILVER LINE JAR', 'productPool/1.jpg', 9 ),
( 'GPET AQUA FRIDGE BOTTLE 1L', 'productPool/1.jpg', 9 ),
( 'GPET BLUEBELL WATERBOTTLE 1000ML', 'productPool/1.jpg', 222 ),
( 'GPET BOTTLE 1000ML', 'productPool/1.jpg', 63 ),
( 'GPET DAFFODIL BOTTLE 1000ML', 'productPool/1.jpg', 222 ),
( 'GPET DIAMOND BOTTLE 1000ML', 'productPool/1.jpg', 28 ),
( 'GPET GARLIC BOTTLE 1000ML', 'productPool/1.jpg', 133 ),
( 'GPET ICE BERGE BOTTLE 1000ML', 'productPool/1.jpg', 110 ),
( 'GPET ICE BERGE BOTTLE 500ML', 'productPool/1.jpg', 6 ),
( 'GPET LILY BOTTLE 1000ML', 'productPool/1.jpg', 51 ),
( 'GPET ORCHID BOTTLE 1000ML', 'productPool/1.jpg', 265 ),
( 'GPET ORCHID BOTTLE 500ML', 'productPool/1.jpg', 212 ),
( 'GPET PANSY BOTTLE 1L', 'productPool/1.jpg', 119 ),
( 'GPET PRINT MAGIC JAR 1000ML', 'productPool/1.jpg', 6 ),
( 'GPET PRINT MAGIC JAR 1200ML', 'productPool/1.jpg', 197 ),
( 'GPET PRINT MAGIC JAR 1500ML', 'productPool/1.jpg', 243 ),
( 'GPET PRINT MAGIC JAR 2000ML', 'productPool/1.jpg', 86 ),
( 'GPET PRINT MAGIC JAR 200ML', 'productPool/1.jpg', 211 ),
( 'GPET PRINT MAGIC JAR 2200ML', 'productPool/1.jpg', 107 ),
( 'GPET PRINT MAGIC JAR 550ML', 'productPool/1.jpg', 83 ),
( 'GPET PRINT MAGIC JAR 750ML', 'productPool/1.jpg', 101 ),
( 'GPET ROSE STEEL CAP BOTTLE 1000ML', 'productPool/1.jpg', 96 ),
( 'GPET ROUND JAR 250ML', 'productPool/1.jpg', 244 ),
( 'GPET SAFFRON BOTTLE 1000ML', 'productPool/1.jpg', 242 ),
( 'GPET SILVER LINE JAR 1000ML', 'productPool/1.jpg', 44 ),
( 'GPET SILVER LINE JAR 300ML', 'productPool/1.jpg', 241 ),
( 'GRAND FOODS MULLU MURUKKU 170GM', 'productPool/1.jpg', 102 ),
( 'GRAND FOODS RING MURUKKU 170G', 'productPool/1.jpg', 84 ),
( 'GRAND FOODS SWEET MIXTURE 170GM', 'productPool/1.jpg', 72 ),
( 'GRANDMAS ANCIENT KERALA MASALA 400G', 'productPool/1.jpg', 251 ),
( 'GRANDMAS BANANA JAM 500G', 'productPool/1.jpg', 139 ),
( 'GRANDMAS CUT MANGO PICKLE 400G', 'productPool/1.jpg', 61 ),
( 'GRANDMAS FISH PICKLE 400G', 'productPool/1.jpg', 262 ),
( 'GRANDMAS GARLIC PICKLE 400G', 'productPool/1.jpg', 207 ),
( 'GRANDMAS GINGER PICKLE 400G', 'productPool/1.jpg', 45 ),
( 'GRANDMAS GOOSE BERRY PICKLE 400 G', 'productPool/1.jpg', 221 ),
( 'GRANDMAS GRAPE JAM 500G', 'productPool/1.jpg', 255 ),
( 'GRANDMAS HOT LIME PICKLE 400G', 'productPool/1.jpg', 226 ),
( 'GRANDMAS JACK FRUIT JAM 500G', 'productPool/1.jpg', 255 ),
( 'GRANDMAS KADUKU MANGO 400G', 'productPool/1.jpg', 83 ),
( 'GRANDMAS LIME WHITE PICKLE 400G', 'productPool/1.jpg', 153 ),
( 'GRANDMAS MANGO JAM 500G', 'productPool/1.jpg', 248 ),
( 'GRANDMAS MIX FRUIT JAM 350G', 'productPool/1.jpg', 68 ),
( 'GRANDMAS MIXED FRUIT JAM 500 G', 'productPool/1.jpg', 271 ),
( 'GRANDMAS MIXEDVEGETABLE PICKLE 400G', 'productPool/1.jpg', 24 ),
( 'GRANDMAS ORANGE JAM 500G', 'productPool/1.jpg', 179 ),
( 'GRANDMAS PAVAKAIP ICKLES 400G', 'productPool/1.jpg', 30 ),
( 'GRANDMAS PINE APPLE JAM 350 G', 'productPool/1.jpg', 49 ),
( 'GRANDMAS PINEAPPLE JAM 500G', 'productPool/1.jpg', 266 ),
( 'GRANDMAS PRAWNS PICKLE 400G', 'productPool/1.jpg', 85 ),
( 'GRANDMAS STRAWBERY JAM500G', 'productPool/1.jpg', 125 ),
( 'GRANDMAS TENDER MANGO PICKLE 400G', 'productPool/1.jpg', 84 ),
( 'GRANDMAS VADUKA PULI 400 G', 'productPool/1.jpg', 180 ),
( 'GRANDMAS VADUKAPPULI LIME PICKLE 400G', 'productPool/1.jpg', 168 ),
( 'GRANDMAS VATTAL MANGO PICKLE 400G', 'productPool/1.jpg', 211 ),
( 'GRAPE CORDIAL CHURCH USE', 'productPool/1.jpg', 148 ),
( 'GRAPE DRAKSHA ARISHTAM 750ML', 'productPool/1.jpg', 174 ),
( 'GRAPE FRUITS', 'productPool/1.jpg', 96 ),
( 'GRATER AHK', 'productPool/1.jpg', 16 ),
( 'GRAVIOLA MULLATHA GREEN TEA 50 GM', 'productPool/1.jpg', 261 ),
( 'GRB BUTTERSCOTCH SOAN CAKE 100G', 'productPool/1.jpg', 128 ),
( 'GRB CHOCOLATE SON PAPDI 200G', 'productPool/1.jpg', 135 ),
( 'GRB GHEE 100ML', 'productPool/1.jpg', 248 ),
( 'GRB GHEE 200ML', 'productPool/1.jpg', 45 ),
( 'GRB GHEE 500ML', 'productPool/1.jpg', 15 ),
( 'GRB GHEE 50ML', 'productPool/1.jpg', 169 ),
( 'GRB GULAB JAMUN 300G', 'productPool/1.jpg', 5 ),
( 'GRB RASXOGOLLA 300G', 'productPool/1.jpg', 234 ),
( 'GRB SOAN CAKE MOUTHWATERING100G', 'productPool/1.jpg', 205 ),
( 'GRB SOAN CAKE PINEAPPLE 100G', 'productPool/1.jpg', 147 ),
( 'GRB SOAN PAPADI BUTTER SCOTCH 200G', 'productPool/1.jpg', 52 ),
( 'GRB SOAN PAPADI BUTTER SCOTCH 250G', 'productPool/1.jpg', 181 ),
( 'GRB SOAN PAPADI ELACHI 250G', 'productPool/1.jpg', 145 ),
( 'GRB SOAN PAPADI ORANGE 200G', 'productPool/1.jpg', 65 ),
( 'GRB SOAN PAPADI PINEAPPLE 250G', 'productPool/1.jpg', 257 ),
( 'GRB SOAN PAPDI 200G', 'productPool/1.jpg', 233 ),
( 'GRB SOAN PAPDI COCONUT 200G', 'productPool/1.jpg', 144 ),
( 'GRB SOAN PAPDI ORANGE 250G', 'productPool/1.jpg', 271 ),
( 'GRB SOAN PAPDI PINEAPPLE 200G', 'productPool/1.jpg', 112 ),
( 'GREEN APPLE', 'productPool/1.jpg', 177 ),
( 'GREEN CHEERA', 'productPool/1.jpg', 141 ),
( 'GREEN CHILLIES', 'productPool/1.jpg', 210 ),
( 'GREEN GRAPES', 'productPool/1.jpg', 111 ),
( 'GREEN LINES COCONUT POWDER 1KG', 'productPool/1.jpg', 80 ),
( 'GREEN MANGO', 'productPool/1.jpg', 7 ),
( 'GREEN OLIVES SLICED 430G', 'productPool/1.jpg', 70 ),
( 'GREEN PEAR', 'productPool/1.jpg', 272 ),
( 'GREEN PEAS', 'productPool/1.jpg', 216 ),
( 'GREEN TEA JAR RIPL250', 'productPool/1.jpg', 126 ),
( 'GREEN TEA TEFE 50 GM', 'productPool/1.jpg', 139 ),
( 'GREENPEAS 500G', 'productPool/1.jpg', 253 ),
( 'GREENPEAS PREMIUM 500G', 'productPool/1.jpg', 187 ),
( 'GREENVALLEY COCONUT OIL 1LTR', 'productPool/1.jpg', 42 ),
( 'GREENVALLEY COCONUT OIL 500ML', 'productPool/1.jpg', 182 ),
( 'GROCERY WH', 'productPool/1.jpg', 18 ),
( 'GROCERY WH WT', 'productPool/1.jpg', 237 ),
( 'GROUNDNUT PEPPER GUJARAT BAG', 'productPool/1.jpg', 99 ),
( 'GROUNDNUT ROASTED 100G', 'productPool/1.jpg', 64 ),
( 'GROUNDNUT ROASTED 200G', 'productPool/1.jpg', 79 ),
( 'GROUNDNUT ROASTED 500G', 'productPool/1.jpg', 158 ),
( 'GSM MARGARIN 1KG', 'productPool/1.jpg', 210 ),
( 'GUARATHI PEANUT PEPPER 40G', 'productPool/1.jpg', 173 ),
( 'GUAVA', 'productPool/1.jpg', 203 ),
( 'GUJATATHI PEANUT SALTED 1KG', 'productPool/1.jpg', 245 ),
( 'GULAB JAMMUN 1KG', 'productPool/1.jpg', 248 ),
( 'GUMON CHEWING GUM 675G JAR', 'productPool/1.jpg', 250 ),
( 'GURUVAYOOR PAPPADAM 15NOS', 'productPool/1.jpg', 257 ),
( 'GURUVAYOOR PEPPER PAPPADAM', 'productPool/1.jpg', 124 ),
( 'GURUVAYOOR PEPPER PAPPADAM 100G', 'productPool/1.jpg', 263 ),
( 'GURUVAYUR ANA MARK PAPPAD RS 21', 'productPool/1.jpg', 151 ),
( 'H & S COOL METHOL 2 IN 1 180ML', 'productPool/1.jpg', 4 ),
( 'HABIT APPLE CIDER VINEGAR', 'productPool/1.jpg', 116 ),
( 'HABIT BARBECUE SAUCE 510G', 'productPool/1.jpg', 137 ),
( 'HABIT BLACK OLIVES PITTED IN BRINE 430G', 'productPool/1.jpg', 18 ),
( 'HABIT BLACK OLIVES SLICED 430G', 'productPool/1.jpg', 246 ),
( 'HABIT COCONUT MILK 400ML', 'productPool/1.jpg', 18 ),
( 'HABIT GREEN OLIVES PITTED 430G', 'productPool/1.jpg', 63 ),
( 'HABIT OLIVES STUFFED 450G', 'productPool/1.jpg', 29 ),
( 'HABIT TOMATO PUREE 825G', 'productPool/1.jpg', 46 ),
( 'HAIDIRAMS MINI BHAKARWADI', 'productPool/1.jpg', 80 ),
( 'HAIR & CARE OIL 200ML', 'productPool/1.jpg', 212 ),
( 'HAIR AND CARE FRUIT OILS 100ML', 'productPool/1.jpg', 129 ),
( 'HAIR BRUSH CGM66', 'productPool/1.jpg', 46 ),
( 'HAIR BRUSH MODEL RTS50', 'productPool/1.jpg', 24 ),
( 'HAIR BRUSH RS 57', 'productPool/1.jpg', 39 ),
( 'HAIR BRUSH RS160', 'productPool/1.jpg', 131 ),
( 'HAIR BRUSH RS55', 'productPool/1.jpg', 79 ),
( 'HAIR BRUSH RS70', 'productPool/1.jpg', 51 ),
( 'HAIR COMB RS33', 'productPool/1.jpg', 221 ),
( 'HAIR COMB RS42', 'productPool/1.jpg', 42 ),
( 'HAIR DYE BRUSH', 'productPool/1.jpg', 33 ),
( 'HAIR DYE BRUSH RS15', 'productPool/1.jpg', 7 ),
( 'HAIR DYE BRUSH RS17', 'productPool/1.jpg', 231 ),
( 'HAIR DYE BRUSH RS21', 'productPool/1.jpg', 192 ),
( 'HAITAI CHEWING GUM IMP', 'productPool/1.jpg', 93 ),
( 'HAJMOLA IMLI 50 TAB BOTTLE', 'productPool/1.jpg', 124 ),
( 'HAJMOLA MAHA CANDY 315G JAR', 'productPool/1.jpg', 211 ),
( 'HAJMOLA REGULAR 50 TAB BOTTLE', 'productPool/1.jpg', 202 ),
( 'HALDIRAM AGRA TAJ PETHA 200G', 'productPool/1.jpg', 200 ),
( 'HALDIRAM AGRA TAJ PETHA 350G', 'productPool/1.jpg', 230 ),
( 'HALDIRAM ALL IN ONE 150G', 'productPool/1.jpg', 124 ),
( 'HALDIRAM ALOO BHUJIA 150G', 'productPool/1.jpg', 204 ),
( 'HALDIRAM BOONDI 150G', 'productPool/1.jpg', 50 ),
( 'HALDIRAM MANGO HALWA 200G', 'productPool/1.jpg', 142 ),
( 'HALDIRAM RASGULLA 450G', 'productPool/1.jpg', 1 ),
( 'HALDIRAM SWEET WONDER 500G', 'productPool/1.jpg', 211 ),
( 'HALDIRAMAS SALTED PEANUT 150G', 'productPool/1.jpg', 166 ),
( 'HALDIRAMS ALOO LACHHA 100G', 'productPool/1.jpg', 155 ),
( 'HALDIRAMS BADAM HALWA', 'productPool/1.jpg', 124 ),
( 'HALDIRAMS BHEL PURI 150G', 'productPool/1.jpg', 90 ),
( 'HALDIRAMS BHEL PURI 300G', 'productPool/1.jpg', 42 ),
( 'HALDIRAMS BHUJIA SEV 150 G', 'productPool/1.jpg', 243 ),
( 'HALDIRAMS BHUJIA SEV 150G', 'productPool/1.jpg', 102 ),
( 'HALDIRAMS BHUJIA SEV 350G', 'productPool/1.jpg', 30 ),
( 'HALDIRAMS CHANA NUTS 150G', 'productPool/1.jpg', 80 ),
( 'HALDIRAMS CHATPATA DAL 150G', 'productPool/1.jpg', 182 ),
( 'HALDIRAMS CHOCLATE SOAN PAPADI 250G', 'productPool/1.jpg', 42 ),
( 'HALDIRAMS COCONUT SOAN PAPAD 250G', 'productPool/1.jpg', 242 ),
( 'HALDIRAMS CORN FLAKES MIXTURE 150G', 'productPool/1.jpg', 148 ),
( 'HALDIRAMS CORNFLAKES MIXTURE 350G', 'productPool/1.jpg', 276 ),
( 'HALDIRAMS DRY FRUIT MIX 150G', 'productPool/1.jpg', 100 ),
( 'HALDIRAMS ELACHI BREAD TOAST 250G', 'productPool/1.jpg', 101 ),
( 'HALDIRAMS GOL KANCHAURI 150G', 'productPool/1.jpg', 274 ),
( 'HALDIRAMS GULAB JAM 450G', 'productPool/1.jpg', 139 ),
( 'HALDIRAMS GULAB JAMUN 500G', 'productPool/1.jpg', 216 ),
( 'HALDIRAMS KHATA MEETHA 150G', 'productPool/1.jpg', 140 ),
( 'HALDIRAMS KHATTA MEETHA 400G', 'productPool/1.jpg', 187 ),
( 'HALDIRAMS LAHSUN SEV 150G', 'productPool/1.jpg', 134 ),
( 'HALDIRAMS LEMON BHEL 150G', 'productPool/1.jpg', 4 ),
( 'HALDIRAMS MILK BREAD TOAST 250G', 'productPool/1.jpg', 97 ),
( 'HALDIRAMS MINI SAMOSA 200G', 'productPool/1.jpg', 127 ),
( 'HALDIRAMS MIXTURE 150G', 'productPool/1.jpg', 196 ),
( 'HALDIRAMS MOONG DAL 150G', 'productPool/1.jpg', 26 ),
( 'HALDIRAMS MOONG DAL 350 G', 'productPool/1.jpg', 191 ),
( 'HALDIRAMS NAVARATAN MIX 150G', 'productPool/1.jpg', 225 ),
( 'HALDIRAMS NIMBU MASALA 150G', 'productPool/1.jpg', 186 ),
( 'HALDIRAMS NIMBU MASALA 160G', 'productPool/1.jpg', 9 ),
( 'HALDIRAMS ORANGE SOAN 250G', 'productPool/1.jpg', 41 ),
( 'HALDIRAMS PANCHRATA MIX 150G', 'productPool/1.jpg', 16 ),
( 'HALDIRAMS PUNJABI TADKA 150G', 'productPool/1.jpg', 92 ),
( 'HALDIRAMS RASA GULA 450G', 'productPool/1.jpg', 115 ),
( 'HALDIRAMS RUSKY ATTA TOAST 250G', 'productPool/1.jpg', 6 ),
( 'HALDIRAMS RUSKY ELAICHI TOAST 100G', 'productPool/1.jpg', 29 ),
( 'HALDIRAMS RUSKY MILK TOAST 250G', 'productPool/1.jpg', 121 ),
( 'HALDIRAMS SOAN CAKE 200G', 'productPool/1.jpg', 217 ),
( 'HALDIRAMS SOAN PAPDI 250G BOX', 'productPool/1.jpg', 100 ),
( 'HALDIRAMS SOAN PAPDI 250G RED', 'productPool/1.jpg', 138 ),
( 'HALDIRAMS SOAN PAPDI IND SW 100G', 'productPool/1.jpg', 56 ),
( 'HALDIRAMS SPECIAL SOAN PAPPAD 250G', 'productPool/1.jpg', 42 ),
( 'HALDIRAMS TASTY NUTS 150G', 'productPool/1.jpg', 95 ),
( 'HALDIRANS FATAFAT BHEL 65G', 'productPool/1.jpg', 116 ),
( 'HALDRIRAMS ALOO BHUJIA 400G', 'productPool/1.jpg', 163 ),
( 'HALDRIRAMS SOYA CHIPS 150G', 'productPool/1.jpg', 68 ),
( 'HALO NOURISHING SHAMPOO 1LTR', 'productPool/1.jpg', 37 ),
( 'HAMAM SOAP 100G', 'productPool/1.jpg', 109 ),
( 'HAMAM SOAP 150GM', 'productPool/1.jpg', 155 ),
( 'HAMAM SOAP 3*150G', 'productPool/1.jpg', 146 ),
( 'HANDGUARD FINGERCAP', 'productPool/1.jpg', 208 ),
( 'HANDLE COMB', 'productPool/1.jpg', 141 ),
( 'HANGER 040 12 PCS SET', 'productPool/1.jpg', 277 ),
( 'HANGER RS 84', 'productPool/1.jpg', 136 ),
( 'HANGER RS 96', 'productPool/1.jpg', 149 ),
( 'HAPPILO SUPERMIX BERRIES 200G', 'productPool/1.jpg', 38 ),
( 'HAPPY CATER MATE TOMATO SAUCE 1KG', 'productPool/1.jpg', 206 ),
( 'HAPPY DARK SOYA SAUCE 200G', 'productPool/1.jpg', 266 ),
( 'HAPPY GRAPE CRUSH 750ML', 'productPool/1.jpg', 278 ),
( 'HAPPY GRAPE FRUIT SQUASH 700ML', 'productPool/1.jpg', 256 ),
( 'HAPPY GREEN CHILLI 200G', 'productPool/1.jpg', 98 ),
( 'HAPPY GROVE VIRGINCOCONUTOIL200ML', 'productPool/1.jpg', 278 ),
( 'HAPPY HOO DAUGH KIT LARGE', 'productPool/1.jpg', 228 ),
( 'HAPPY HOO DAUGH KIT MEDIUM', 'productPool/1.jpg', 133 ),
( 'HAPPY HOO FUN DOUGH KIT', 'productPool/1.jpg', 245 ),
( 'HAPPY MANGO CRUSH 750ML', 'productPool/1.jpg', 104 ),
( 'HAPPY MANGO FRUIT SQUASH 700ML', 'productPool/1.jpg', 40 ),
( 'HAPPY MANGO SOFT DRINK CONCENTRATE 200ML', 'productPool/1.jpg', 135 ),
( 'HAPPY MIX FRUIT JAM 100G', 'productPool/1.jpg', 86 ),
( 'HAPPY MIX FRUIT JAM 500G', 'productPool/1.jpg', 146 ),
( 'HAPPY MIXED FRUIT JAM 200G', 'productPool/1.jpg', 105 ),
( 'HAPPY MIXED FRUIT JAM 250G', 'productPool/1.jpg', 212 ),
( 'HAPPY MIXED FRUIT JAM 350G', 'productPool/1.jpg', 266 ),
( 'HAPPY ORANGE CRUSH 750ML', 'productPool/1.jpg', 164 ),
( 'HAPPY ORANGE FRUIT 700 ML', 'productPool/1.jpg', 126 ),
( 'HAPPY PEANUT BUTTER CREAMY 200G', 'productPool/1.jpg', 204 ),
( 'HAPPY PEANUT BUTTER CRUNCHY 200G', 'productPool/1.jpg', 10 ),
( 'HAPPY PINAAPLE JAM 1KG', 'productPool/1.jpg', 275 ),
( 'HAPPY PINAPLE JAM 350G', 'productPool/1.jpg', 36 ),
( 'HAPPY PINAPPLE JAM 200G', 'productPool/1.jpg', 29 ),
( 'HAPPY PINE APPLE FRUIT JAM 500G', 'productPool/1.jpg', 127 ),
( 'HAPPY PINE APPLE SOFT DRINK CONCENTRATE 200ML', 'productPool/1.jpg', 146 ),
( 'HAPPY PINE APPLE SQUASH 700ML', 'productPool/1.jpg', 53 ),
( 'HAPPY PINEAPPLE JAM 100G', 'productPool/1.jpg', 215 ),
( 'HAPPY PINEAPPLE JAM 250G', 'productPool/1.jpg', 86 ),
( 'HAPPY RED CHILLI 200G', 'productPool/1.jpg', 22 ),
( 'HAPPY STRAWBERRY FRIUT JAM 100G', 'productPool/1.jpg', 278 ),
( 'HAPPY STRAWBERY FRUIT 750ML', 'productPool/1.jpg', 30 ),
( 'HAPPY TOMOTO CHILLI SAUCE 200G', 'productPool/1.jpg', 124 ),
( 'HAPPY TOMOTO KETCHUP 200G', 'productPool/1.jpg', 162 ),
( 'HARIMA BARLEY POWDER 100G', 'productPool/1.jpg', 180 ),
( 'HARIMA CHOCO CHIPS 100G', 'productPool/1.jpg', 207 ),
( 'HARIMA DEMERARA SUGAR 200G', 'productPool/1.jpg', 222 ),
( 'HARIMA JALJEERA POWDER 100G', 'productPool/1.jpg', 257 ),
( 'HARIMA NOODLES MASALA 50G', 'productPool/1.jpg', 55 ),
( 'HARIMA PALMYRAH PALM SUGAR CANDY 100G', 'productPool/1.jpg', 162 ),
( 'HARIMA PAV BHAJI MASALA 50G', 'productPool/1.jpg', 31 ),
( 'HARIPPA PUMPKIN HONEY ROASTED 30G', 'productPool/1.jpg', 138 ),
( 'HARIPPA ROSASTED PUMPKIN CHEESY ONION 30G', 'productPool/1.jpg', 110 ),
( 'HARMONY SOAP IMP', 'productPool/1.jpg', 12 ),
( 'HARPIC 1LTR FREE BATHROOM CLEANER', 'productPool/1.jpg', 131 ),
( 'HARPIC 500ML COMBI', 'productPool/1.jpg', 82 ),
( 'HARPIC 500ML COMBI PACK', 'productPool/1.jpg', 97 ),
( 'HARPIC 750 ML BLACK', 'productPool/1.jpg', 20 ),
( 'HARPIC BATHR ROOM CLEAN 500ML', 'productPool/1.jpg', 26 ),
( 'HARPIC BATHROOM CLEANER 200ML', 'productPool/1.jpg', 145 ),
( 'HARPIC BATHROOM CLEANER 500ML', 'productPool/1.jpg', 266 ),
( 'HARPIC BATHROOM CLEANER 500ML LIZOL FREE', 'productPool/1.jpg', 201 ),
( 'HARPIC BATHROOM CLEANER LEMON 1LTR', 'productPool/1.jpg', 9 ),
( 'HARPIC BATHROOM CLEANING SPARY 400ML', 'productPool/1.jpg', 124 ),
( 'HARPIC CITRUS 500 ML', 'productPool/1.jpg', 233 ),
( 'HARPIC FLUSH MATIC 100G', 'productPool/1.jpg', 35 ),
( 'HARPIC FLUSHMATIC AQUARINE 50G', 'productPool/1.jpg', 61 ),
( 'HARPIC FLUSHMATIC TWIN', 'productPool/1.jpg', 94 ),
( 'HARPIC FLUSMAT PINE 50G', 'productPool/1.jpg', 214 ),
( 'HARPIC FRESH 500ML', 'productPool/1.jpg', 8 ),
( 'HARPIC FRESH CITRUS 500ML', 'productPool/1.jpg', 261 ),
( 'HARPIC FRESH FLORAL 500ML', 'productPool/1.jpg', 22 ),
( 'HARPIC FRESH PINE 500ML', 'productPool/1.jpg', 233 ),
( 'HARPIC FRESH TOILET CLEANER ORANGE 500ML', 'productPool/1.jpg', 69 ),
( 'HARPIC GERM CITRUS 750ML', 'productPool/1.jpg', 44 ),
( 'HARPIC HYGIENIC 26G', 'productPool/1.jpg', 105 ),
( 'HARPIC HYGINIC 26 G', 'productPool/1.jpg', 99 ),
( 'HARPIC ORIGINAL 200ML', 'productPool/1.jpg', 152 ),
( 'HARPIC ORIGINAL 500ml', 'productPool/1.jpg', 244 ),
( 'HARPIC ORIGINAL POWER PLUS 200ML', 'productPool/1.jpg', 137 ),
( 'HARPIC PLATINUM DISINFECTANT 500ML', 'productPool/1.jpg', 19 ),
( 'HARPIC PLUS BLEACH 500 ML', 'productPool/1.jpg', 103 ),
( 'HARPIC POWER PLUS 1 LTR', 'productPool/1.jpg', 224 ),
( 'HARPIC POWER PLUS ORANGE 1 LTR', 'productPool/1.jpg', 86 ),
( 'HARPIC TOILET CLEANER 1L', 'productPool/1.jpg', 173 ),
( 'HARPIC TOILET CLEANER ORIGINAL 200ML', 'productPool/1.jpg', 93 ),
( 'HARPIC TOLIET CLEANET 1L', 'productPool/1.jpg', 137 ),
( 'HARPIC TOLIET CLEANET 900ML', 'productPool/1.jpg', 58 ),
( 'HARVEST MIXED FRUIT 1LTR', 'productPool/1.jpg', 135 ),
( 'HARVEST RICH MANGO 1LTR', 'productPool/1.jpg', 87 ),
( 'HARVEYS CHOCOLATE WAFER 110G', 'productPool/1.jpg', 148 ),
( 'HARVEYS ORANGE WAFER POUCH 110G', 'productPool/1.jpg', 244 ),
( 'HARVEYS STRAWBERY WAFER POUCH 110G', 'productPool/1.jpg', 194 ),
( 'HARVEYS VANILA WAFER POUCH 110G', 'productPool/1.jpg', 64 ),
( 'HASEENA CASHEW NUT 1KG', 'productPool/1.jpg', 169 ),
( 'HASEENA W180 CASHEW 1KG', 'productPool/1.jpg', 173 ),
( 'HATHIKULI ORGANIC TEA 250G', 'productPool/1.jpg', 118 ),
( 'HAUTE GIFT ZIPPOUCH BIG', 'productPool/1.jpg', 78 ),
( 'HAUTE GIFT ZIPPOUCH SMALL', 'productPool/1.jpg', 111 ),
( 'HAVELLS BEARD TRIMMER BT5100C', 'productPool/1.jpg', 266 ),
( 'HAVELLS HAIR DRYER HD 3104', 'productPool/1.jpg', 109 ),
( 'HAVELLS HAIR DRYER HD3152', 'productPool/1.jpg', 163 ),
( 'HAVELLS HAIR STRAIGHTENER HS4104', 'productPool/1.jpg', 44 ),
( 'HAVELLS HAIR STRAIGHTENER HS4121', 'productPool/1.jpg', 119 ),
( 'HAZELLA CHOCO SPREAD 350G', 'productPool/1.jpg', 46 ),
( 'HE ADVANCED GROOMING RESPECT150ML', 'productPool/1.jpg', 211 ),
( 'HEAD & SHOULDER 2 IN 1 SMOOTH SILKY 180ML', 'productPool/1.jpg', 142 ),
( 'HEAD & SHOULDER 2IN1 COOL MENTHOL 340ML', 'productPool/1.jpg', 88 ),
( 'HEAD & SHOULDER 2IN1 COOL MENTHOL 72ML', 'productPool/1.jpg', 44 ),
( 'HEAD & SHOULDER 2IN1 SMOOTH SILKY 340ML', 'productPool/1.jpg', 103 ),
( 'HEAD & SHOULDER 2IN1 SMOOTH SILKY SHAMPOO 360ML', 'productPool/1.jpg', 229 ),
( 'HEAD & SHOULDER 2IN1 SMOOTH SILKY SHAMPOO 675ML', 'productPool/1.jpg', 244 ),
( 'HEAD & SHOULDER ACTIVE PROTECT 180ML', 'productPool/1.jpg', 265 ),
( 'HEAD & SHOULDER ACTIVE PROTECT 360ML', 'productPool/1.jpg', 271 ),
( 'HEAD & SHOULDER AHF CONDITIONER 80ML', 'productPool/1.jpg', 213 ),
( 'HEAD & SHOULDER AHF TOTAL DAMAGE CARE 650ML', 'productPool/1.jpg', 196 ),
( 'HEAD & SHOULDER ANTI HAIR FALL SHAMPOO 180ML', 'productPool/1.jpg', 267 ),
( 'HEAD & SHOULDER ANTI HAIR FALL SHAMPOO 360ML', 'productPool/1.jpg', 236 ),
( 'HEAD & SHOULDER ANTI HAIR SHAMPOO 80ML', 'productPool/1.jpg', 167 ),
( 'HEAD & SHOULDER ANTI HAIRFALL 675ML', 'productPool/1.jpg', 59 ),
( 'HEAD & SHOULDER COOL MENTHOL 180ML', 'productPool/1.jpg', 132 ),
( 'HEAD & SHOULDER COOL MENTHOL 2 IN 1 180ML', 'productPool/1.jpg', 162 ),
( 'HEAD & SHOULDER COOL MENTHOL 2IN1 180ML', 'productPool/1.jpg', 142 ),
( 'HEAD & SHOULDER COOL MENTHOL 340+180ML', 'productPool/1.jpg', 107 ),
( 'HEAD & SHOULDER COOL MENTHOL 650ML', 'productPool/1.jpg', 138 ),
( 'HEAD & SHOULDER COOL MENTHOL SHAMPOO + CONDI 360ML', 'productPool/1.jpg', 10 ),
( 'HEAD & SHOULDER COOL MENTHOL SHAMPOO 180ML', 'productPool/1.jpg', 125 ),
( 'HEAD & SHOULDER COOL MENTHOL2IN1 675ML', 'productPool/1.jpg', 73 ),
( 'HEAD & SHOULDER LEMON FRESH 360ML', 'productPool/1.jpg', 9 ),
( 'HEAD & SHOULDER SILKY BLACK SHAMPOO 360ML', 'productPool/1.jpg', 136 ),
( 'HEAD & SHOULDER SMOOTH & SILKY 675ML', 'productPool/1.jpg', 81 ),
( 'HEAD & SHOULDER SMOOTH & SILKY CONDITIONER 170ML', 'productPool/1.jpg', 215 ),
( 'HEAD & SHOULDER SMOOTH SILK SHAMPOO 180ML', 'productPool/1.jpg', 137 ),
( 'HEAD & SHOULDER SMOOTH SILKY 180ML', 'productPool/1.jpg', 116 ),
( 'HEAD & SHOULDER SMOOTH SILKY 2 IN 1 180ML', 'productPool/1.jpg', 54 ),
( 'HEAD & SHOULDER SMOOTH SILKY SHAMPOO 675ML', 'productPool/1.jpg', 171 ),
( 'HEAD & SHOULDER SMOOTH SILLKY SHAMPOO 80ML', 'productPool/1.jpg', 252 ),
( 'HEAD & SHOULDER SMOOTH&SILKY 675ML', 'productPool/1.jpg', 167 ),
( 'HEAD & SHOULDER SS CONDITIONER 80ML', 'productPool/1.jpg', 104 ),
( 'HEAD & SHOULDERS ANTI HAIR FALL 170ML', 'productPool/1.jpg', 142 ),
( 'HEAD & SHOULDERS ANTI HAIRFALL 650ML', 'productPool/1.jpg', 239 ),
( 'HEAD & SHOULDERS COOL MENTHOL 675ML', 'productPool/1.jpg', 89 ),
( 'HEAD & SHOULDERS SILKY BLACK 170ML', 'productPool/1.jpg', 5 ),
( 'HEAD & SHOULDERS SMOOTH SILKY 72ML', 'productPool/1.jpg', 67 ),
( 'HEAD & SJHOULDER SMOOTH SILKY 650ML', 'productPool/1.jpg', 156 ),
( 'HEAD &SHOULDERS COOL MENTHOL 650ML', 'productPool/1.jpg', 189 ),
( 'HEAD AND SHOULDER ANTI HAIR FALL 180ML', 'productPool/1.jpg', 259 ),
( 'HEAD AND SHOULDER ANTI HAIR FALL 340ML', 'productPool/1.jpg', 90 ),
( 'HEAD AND SHOULDER ANTI HAIR FALL 72ML', 'productPool/1.jpg', 189 ),
( 'HEAD AND SHOULDER COOL MENTHOL 180ML', 'productPool/1.jpg', 275 ),
( 'HEAD AND SHOULDER COOL MENTHOL 2 IN 1 360ML', 'productPool/1.jpg', 110 ),
( 'HEAD AND SHOULDER DRY SCALP CARE 180ML', 'productPool/1.jpg', 31 ),
( 'HEAD AND SHOULDER LEMON FRESH 180ML', 'productPool/1.jpg', 95 ),
( 'HEAD AND SHOULDER SMOOTH SILKY 2 IN 1 180ML', 'productPool/1.jpg', 187 ),
( 'HEAD AND SHOULDERS COOL MENTHOL 340ML', 'productPool/1.jpg', 221 ),
( 'HEAD AND SHOULDERS COOL MENTHOL 675ML', 'productPool/1.jpg', 243 ),
( 'HEAD AND SHOULDERS SILKY BLACK SHAMPOO 72ML', 'productPool/1.jpg', 141 ),
( 'HEAD AND SHOULDERS SMOOTH SILKY SHAMPOO 340 ML', 'productPool/1.jpg', 183 ),
( 'HEAD SHOULDERS COOL MENTHOL 72ML', 'productPool/1.jpg', 177 ),
( 'HEAD SHOULDERS LEMON FRESH 72ML', 'productPool/1.jpg', 27 ),
( 'HEAD SHOULDERS SILKY BLACK 180ML', 'productPool/1.jpg', 152 ),
( 'HEAD SHOULDERS SMOOTH SILKY 360ML', 'productPool/1.jpg', 233 ),
( 'HEAD&SHOULDERS ANTI HAIR FALL SHAMPOO 675ML', 'productPool/1.jpg', 185 ),
( 'HEAD&SHOULDERS COOL MENTHOL SHAMPOO 80ML', 'productPool/1.jpg', 119 ),
( 'HEAD&SHOULDERS DRY SCALP CARE 180ML', 'productPool/1.jpg', 33 ),
( 'HEAD&SHOULDERS LEMON FRESH 80ML', 'productPool/1.jpg', 245 ),
( 'HEAD&SHOULDERS LEMON FRESH SHAMPOO 180ML', 'productPool/1.jpg', 211 ),
( 'HEAD&SHOULDERS SILKY BLACK SHAMPOO 180ML', 'productPool/1.jpg', 190 ),
( 'HEAD&SHOULDERS SILKY BLACK SHAMPOO 80ML', 'productPool/1.jpg', 190 ),
( 'HEALTH MIX 1KG', 'productPool/1.jpg', 177 ),
( 'HEALTH MIX POWDER 500G PKT', 'productPool/1.jpg', 227 ),
( 'HEART BEAT BLACK CURRANT', 'productPool/1.jpg', 150 ),
( 'HEART BEAT CANDY MIXED 835G', 'productPool/1.jpg', 128 ),
( 'HEART BEAT CANDY ORANGE 835G', 'productPool/1.jpg', 139 ),
( 'HEART CANDY LYCHEE 150GM', 'productPool/1.jpg', 237 ),
( 'HEART CANDY ORANGE 150GM', 'productPool/1.jpg', 83 ),
( 'HEART CANDY STRAWBERRY 150GM', 'productPool/1.jpg', 180 ),
( 'HEARTBEAT CORAZON MANGO 150GM', 'productPool/1.jpg', 2 ),
( 'HEARTBEAT CORAZON STRAWBERRY CANDY', 'productPool/1.jpg', 250 ),
( 'HEINZ MAYONISE CLASSIC 400G', 'productPool/1.jpg', 160 ),
( 'HEINZ MAYONISE LIGHT 400G', 'productPool/1.jpg', 111 ),
( 'HEINZ SPICY TIKKA MASALA MAYONISE 400G', 'productPool/1.jpg', 7 ),
( 'HEINZ TOMATO KETCHUP 450G', 'productPool/1.jpg', 70 ),
( 'HENKO BAR250G', 'productPool/1.jpg', 241 ),
( 'HENKO MATIC FRONT LOAD 1KG', 'productPool/1.jpg', 68 ),
( 'HENKO MATIC FRONT LOAD 1KG PRIL FREE', 'productPool/1.jpg', 95 ),
( 'HENKO MATIC FRONT LOAD 1KG+500G FREE', 'productPool/1.jpg', 113 ),
( 'HENKO MATIC FRONT LOAD 2KG', 'productPool/1.jpg', 156 ),
( 'HENKO MATIC FRONT LOAD 2KG+1KG FREE', 'productPool/1.jpg', 40 ),
( 'HENKO MATIC REONT LOAD 2KG+1KG', 'productPool/1.jpg', 152 ),
( 'HENKO MATIC TOP LOAD 1KG', 'productPool/1.jpg', 126 ),
( 'HENKO MATIC TOP LOAD 1KG+500G FREE', 'productPool/1.jpg', 10 ),
( 'HENKO MATIC TOPLOAD 2KG FREE 425ML PRIL', 'productPool/1.jpg', 74 ),
( 'HENKO STAIM CHAMPION 500G', 'productPool/1.jpg', 143 ),
( 'HENKO STAIN CHAMPION 1KG', 'productPool/1.jpg', 73 ),
( 'HENKO STAIN CHAMPION 3KG', 'productPool/1.jpg', 177 ),
( 'HENKO STAIN CHAMPION 500G', 'productPool/1.jpg', 44 ),
( 'HENKO STAIN CHAMPION 5KG', 'productPool/1.jpg', 194 ),
( 'HENKO STAIN CHAMPION BAR 115G', 'productPool/1.jpg', 234 ),
( 'HENKO STAIN CHAMPION OXYGEN POWDER 1KG', 'productPool/1.jpg', 68 ),
( 'HENKO STAIN CHAMPION SOAP 250G', 'productPool/1.jpg', 90 ),
( 'HENKO STAIN CHAMPION SOAP 400G', 'productPool/1.jpg', 239 ),
( 'HENKO WONDER WASH 500G', 'productPool/1.jpg', 118 ),
( 'HENKOMATIC TOP LOAD 1KG', 'productPool/1.jpg', 79 ),
( 'HENNA & AMLA VATIKA HEALTH SHAMPOO180ML', 'productPool/1.jpg', 109 ),
( 'HENNA POWDER 40GM', 'productPool/1.jpg', 3 ),
( 'HENNA PREM DULHAN HENNA POWDER 500G', 'productPool/1.jpg', 137 ),
( 'HENZ MAYONISE CHILI 400G', 'productPool/1.jpg', 275 ),
( 'HERBAL BOTTLE', 'productPool/1.jpg', 235 ),
( 'HERBAL MOSQUITO VAPORIZER 40ML', 'productPool/1.jpg', 102 ),
( 'HERITAGE CHANDANAM STICKS 38G', 'productPool/1.jpg', 143 ),
( 'HERITAGE RADIANT ROSE AGARBATHIES', 'productPool/1.jpg', 114 ),
( 'HERSHEY CHOCOLATE SYRUP', 'productPool/1.jpg', 175 ),
( 'HERSHEY STRAWBERRY SYRUP', 'productPool/1.jpg', 77 ),
( 'HERSHEYS CARAMEL SYRUP 625ML', 'productPool/1.jpg', 189 ),
( 'HERSHEYS KISSES ALMONDS CHOCOLATE 33.6G', 'productPool/1.jpg', 31 ),
( 'HERSHEYS KISSES COOKIE CREME CHOCOLATE 100.8G', 'productPool/1.jpg', 79 ),
( 'HERSHEYS KISSES COOKIE CREME CHOCOLATE 33.6G', 'productPool/1.jpg', 202 ),
( 'HERSHEYS KISSES MILK CHOCOLATE 108G', 'productPool/1.jpg', 118 ),
( 'HERSHEYS KISSES MILK CHOCOLATE 36G', 'productPool/1.jpg', 91 ),
( 'HERSHEYS MILK SHAKE CHOCOLATE 1L', 'productPool/1.jpg', 95 ),
( 'HERSHEYS MILK SHAKE CHOCOLATE 200ML', 'productPool/1.jpg', 233 ),
( 'HERSHEYS MILK SHAKE COOKIES N CREME 200ML', 'productPool/1.jpg', 231 ),
( 'HERSHEYS MILK SHAKE STRAWBERRY 1L', 'productPool/1.jpg', 32 ),
( 'HERSHEYS MILK SHAKE STRAWBERRY 200ML', 'productPool/1.jpg', 258 ),
( 'HERSHEYS MILKSHAKE ALMOND 200ML', 'productPool/1.jpg', 106 ),
( 'HERSHEYS SPREAD 135G', 'productPool/1.jpg', 193 ),
( 'HERSHEYS SPREAD 300G', 'productPool/1.jpg', 265 ),
( 'HERSHEYS SPREAD ALMOND 135G', 'productPool/1.jpg', 4 ),
( 'HERSHEYS SPREAD COCOA 300G', 'productPool/1.jpg', 154 ),
( 'HERSHEYS SPREAD COCOA 350G', 'productPool/1.jpg', 9 ),
( 'HERSHEYS SPREADS COCOA 150G', 'productPool/1.jpg', 107 ),
( 'HERSHEYS SPREADS COCOA ALMOND 12G', 'productPool/1.jpg', 67 ),
( 'HERSHEYS SPREADS COCOA ALMOND 350G', 'productPool/1.jpg', 146 ),
( 'HERSHEYS SYRUP CHOCOLATE 1.3KG', 'productPool/1.jpg', 208 ),
( 'HERSHEYS SYRUP CHOCOLATE 200ML', 'productPool/1.jpg', 157 ),
( 'HERSHEYS SYRUP CHOCOLATE 32G', 'productPool/1.jpg', 177 ),
( 'HERSHEYS SYRUP CHOCOLATE FLAVOR', 'productPool/1.jpg', 191 ),
( 'HERSHEYS SYRUP STRAWBERRY 200G', 'productPool/1.jpg', 255 ),
( 'HEYDAY BALLOON BLUE BOY 006', 'productPool/1.jpg', 274 ),
( 'HEYDAY BALLOON BLUE BOY 012', 'productPool/1.jpg', 93 ),
( 'HEYDAY BALLOON MIX HEART 006', 'productPool/1.jpg', 146 ),
( 'HEYDAY BALLOON MIX HEART 008', 'productPool/1.jpg', 166 ),
( 'HEYDAY BALLOON MIX NATURAL 006', 'productPool/1.jpg', 61 ),
( 'HEYDAY BALLOON MIX NATURAL 012', 'productPool/1.jpg', 91 ),
( 'HEYDAY BALLOON PINK LADY 006', 'productPool/1.jpg', 208 ),
( 'HEYDAY BALLOON PINK LADY 012', 'productPool/1.jpg', 219 ),
( 'HEYDAY BALLOON PLAIN 018', 'productPool/1.jpg', 47 ),
( 'HEYDAY BALLOON PLAIN 036', 'productPool/1.jpg', 114 ),
( 'HEYDAY BALLOON POLKA DOTS 006', 'productPool/1.jpg', 249 ),
( 'HEYDAY BALLOON POLKA DOTS 012', 'productPool/1.jpg', 28 ),
( 'HEYDAY BIRTHDAY BALLOON 006', 'productPool/1.jpg', 81 ),
( 'HEYDAY BIRTHDAY BALLOON 012', 'productPool/1.jpg', 243 ),
( 'HEYDAY PREMIUM PLAIN BALLOON 070', 'productPool/1.jpg', 135 ),
( 'HIC BODY SCRUBBER YI025', 'productPool/1.jpg', 196 ),
( 'HIC BODY SCRUBBER YI032', 'productPool/1.jpg', 36 ),
( 'HIC CLEAN CLIP AND FIT MOP YI612', 'productPool/1.jpg', 78 ),
( 'HIC COTTON FLAT MOP Y1 636', 'productPool/1.jpg', 94 ),
( 'HIC DUSTPAN AND BRUSH YI988', 'productPool/1.jpg', 194 ),
( 'HIC GRASS BROOM GRAH LAXMI 130', 'productPool/1.jpg', 153 ),
( 'HIC JUMBO GRASS BROOM YI827', 'productPool/1.jpg', 187 ),
( 'HIC PLASTIC BROOM Y1 971', 'productPool/1.jpg', 54 ),
( 'HIC PLUGER YI070', 'productPool/1.jpg', 158 ),
( 'HIC SINK CLEANING BRUSH Y1 1872', 'productPool/1.jpg', 150 ),
( 'HIC TWIST MOP YI667', 'productPool/1.jpg', 275 ),
( 'HIDE & SEEK 33G', 'productPool/1.jpg', 139 ),
( 'HIDE & SEEK AMERICAN STYLE BUTTER COOKIES 200G', 'productPool/1.jpg', 272 ),
( 'HIDE & SEEK CAFFE MOCHA 120G', 'productPool/1.jpg', 55 ),
( 'HIDE & SEEK CHOCO ROLL', 'productPool/1.jpg', 133 ),
( 'HIDE & SEEK CHOCO ROLLS 120G', 'productPool/1.jpg', 271 ),
( 'HIDE & SEEK CHOCOLATE 75G', 'productPool/1.jpg', 236 ),
( 'HIDE & SEEL BOUR BON 75G', 'productPool/1.jpg', 14 );