INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'VEEBA PEANUT BUTTER CREAMY 340G', 'productPool/1.jpg', 91 ),
( 'VEEBA RANCH SALAD DRESSING 300G', 'productPool/1.jpg', 156 ),
( 'VEEBA SMART MAYONNAISE 250G', 'productPool/1.jpg', 171 ),
( 'VEEBA SMART MAYONNAISE 275G', 'productPool/1.jpg', 271 ),
( 'VEET BRIGHTENING 50G', 'productPool/1.jpg', 78 ),
( 'VEET BRIGHTENING HAIR REMOVAL CREAM 25G', 'productPool/1.jpg', 67 ),
( 'VEET COLD WAX 20S', 'productPool/1.jpg', 188 ),
( 'VEET COLD WAX SENSITIVE SKIN 8S', 'productPool/1.jpg', 148 ),
( 'VEET CREAM DRY SKIN 25G', 'productPool/1.jpg', 39 ),
( 'VEET DRY SKIN 25G', 'productPool/1.jpg', 196 ),
( 'VEET EASY GEL WAX DRY SKIN', 'productPool/1.jpg', 8 ),
( 'VEET EASY GEL WAX NORMAL SKIN 20N', 'productPool/1.jpg', 70 ),
( 'VEET EASY GEL WAX SENSITIVE SKIN 20N', 'productPool/1.jpg', 238 ),
( 'VEET FACE PRECISION WAXING KIT 8N', 'productPool/1.jpg', 134 ),
( 'VEET FULL BODY WAXING KIT DRY SKIN 20', 'productPool/1.jpg', 197 ),
( 'VEET FULL BODY WAXING KIT NORMAL SKIN', 'productPool/1.jpg', 248 ),
( 'VEET HAIR REMOVAL CREAM 25G', 'productPool/1.jpg', 3 ),
( 'VEET HAIR REMOVAL CREAM 50G', 'productPool/1.jpg', 61 ),
( 'VEET HAIR REMOVAL CREAM BRIGHTENING 25G', 'productPool/1.jpg', 22 ),
( 'VEET HAIR REMOVAL CREAM NORMALSKIN 50G', 'productPool/1.jpg', 181 ),
( 'VEET HAIR REMOVAL CREAM SILK FRESH 25G', 'productPool/1.jpg', 115 ),
( 'VEET HAIR REMOVAL CREAM SILK FRESH 50G', 'productPool/1.jpg', 172 ),
( 'VEET HAIR REMOVEL CREAM 50G', 'productPool/1.jpg', 88 ),
( 'VEET HAIR REMOVEL CREAM25G', 'productPool/1.jpg', 142 ),
( 'VEET HAIR REMOVER CEREAM SENSITIVE SKIN 25G', 'productPool/1.jpg', 170 ),
( 'VEET HAIR REMOVER CREAM 25G', 'productPool/1.jpg', 262 ),
( 'VEET HAIR REMOVER SILK AND FRESH 25G', 'productPool/1.jpg', 228 ),
( 'VEET HAIR REMOVER SILK AND FRESH 50G', 'productPool/1.jpg', 100 ),
( 'VEET INSTANT WAXING KIT', 'productPool/1.jpg', 113 ),
( 'VEET INSTANT WAXING KIT NORMAL SKIN 8N', 'productPool/1.jpg', 192 ),
( 'VEET MEN HAIR REMOVAL CREAM 25G', 'productPool/1.jpg', 28 ),
( 'VEET MEN HAIR REMOVAL CREAM 50G', 'productPool/1.jpg', 183 ),
( 'VEET NIKHAAR HAIR REMOVING CREAM 50G', 'productPool/1.jpg', 236 ),
( 'VEET SILK & FRESH 50G', 'productPool/1.jpg', 103 ),
( 'VEET SILK & FRESH 60GM', 'productPool/1.jpg', 118 ),
( 'VEET SILK FRESH 25G', 'productPool/1.jpg', 213 ),
( 'VEET SILK- FRESH CREAM DRY SKIN 50G', 'productPool/1.jpg', 107 ),
( 'VEET WAXING KIT DRY SKIN 8N', 'productPool/1.jpg', 188 ),
( 'VEG HAKA NOODLS 150G', 'productPool/1.jpg', 223 ),
( 'VEG SPRING ROLL', 'productPool/1.jpg', 187 ),
( 'VEGA BABY NAIL CLIPPER BNC-01', 'productPool/1.jpg', 48 ),
( 'VEGA BATH BRUSH BA-1/3', 'productPool/1.jpg', 54 ),
( 'VEGA BLACK EMARRY FOOT FILE PD-06', 'productPool/1.jpg', 93 ),
( 'VEGA BLACK HEAD REMOVER', 'productPool/1.jpg', 137 ),
( 'VEGA COTTON BALLS CB-01', 'productPool/1.jpg', 13 ),
( 'VEGA COTTON PADS CP-01', 'productPool/1.jpg', 186 ),
( 'VEGA DE TANGLING HAIR COMB 1265', 'productPool/1.jpg', 94 ),
( 'VEGA DRASSING COMB HMC-03', 'productPool/1.jpg', 168 ),
( 'VEGA DYE BRUSH MB02', 'productPool/1.jpg', 37 ),
( 'VEGA FOOT SCRUBBER PD 01', 'productPool/1.jpg', 203 ),
( 'VEGA GRADUATED DRESSING COMB HMC-02D', 'productPool/1.jpg', 17 ),
( 'VEGA GRADUATED DRESSING COMB HMC-09D', 'productPool/1.jpg', 239 ),
( 'VEGA GRADUATED SHAMPOO COMB HMC 34D', 'productPool/1.jpg', 260 ),
( 'VEGA GROOMING COMB 1264', 'productPool/1.jpg', 55 ),
( 'VEGA GROOMING COMB 1267', 'productPool/1.jpg', 158 ),
( 'VEGA GROOMING COMB LARGE 1299', 'productPool/1.jpg', 126 ),
( 'VEGA GROOMING COMB LARGE DC-1299', 'productPool/1.jpg', 265 ),
( 'VEGA GROOMING COMB MEDIUM 1279', 'productPool/1.jpg', 209 ),
( 'VEGA HAIR BRUSH E2-PR', 'productPool/1.jpg', 153 ),
( 'VEGA HAIR BRUSH E8-FB', 'productPool/1.jpg', 220 ),
( 'VEGA HAIR BRUSH R1-FB', 'productPool/1.jpg', 221 ),
( 'VEGA HAIR BRUSH R11-RB', 'productPool/1.jpg', 96 ),
( 'VEGA HAIR BRUSH R8-FBS', 'productPool/1.jpg', 261 ),
( 'VEGA HAIR COMB R11-FB', 'productPool/1.jpg', 154 ),
( 'VEGA HAIR DYE BRUSH MB03', 'productPool/1.jpg', 56 ),
( 'VEGA HEAD REMOVER BHR02', 'productPool/1.jpg', 114 ),
( 'VEGA LARGE NAIL CLIPPER 03', 'productPool/1.jpg', 141 ),
( 'VEGA LICE COMP HMC-37', 'productPool/1.jpg', 61 ),
( 'VEGA LUXURY SPONGE', 'productPool/1.jpg', 278 ),
( 'VEGA MEHNDI DYE BRUSH MB-01', 'productPool/1.jpg', 232 ),
( 'VEGA NAIL BRUSH PD-01N', 'productPool/1.jpg', 174 ),
( 'VEGA NAIL CLIPPER', 'productPool/1.jpg', 105 ),
( 'VEGA NAIL CLIPPER LARGE', 'productPool/1.jpg', 261 ),
( 'VEGA PEDICURE FILE PD-03', 'productPool/1.jpg', 242 ),
( 'VEGA PEDICURE FILE PD-03N', 'productPool/1.jpg', 127 ),
( 'VEGA PEDICURE TOOL PD-02', 'productPool/1.jpg', 44 ),
( 'VEGA PREMIUM PEDICURE TOOL PD-09', 'productPool/1.jpg', 249 ),
( 'VEGA PUMICE STONE PD-10', 'productPool/1.jpg', 141 ),
( 'VEGA PUMICE STONE PD-14', 'productPool/1.jpg', 74 ),
( 'VEGA PUMICE STONE PD-16', 'productPool/1.jpg', 170 ),
( 'VEGA ROUND & CURL HAIR BRUSH E8-RB', 'productPool/1.jpg', 251 ),
( 'VEGA TWEEZER SQUARE TW-01', 'productPool/1.jpg', 201 ),
( 'VEGETABLE CUTLET 6NOS', 'productPool/1.jpg', 87 ),
( 'VELLARI', 'productPool/1.jpg', 210 ),
( 'VELLILAM THALI 40GM', 'productPool/1.jpg', 255 ),
( 'VELVET TOUCH DOG SOAP 100G', 'productPool/1.jpg', 124 ),
( 'VELVET TOUCH DOG SOAP100G', 'productPool/1.jpg', 28 ),
( 'VENKEYS CHICKEN BURGER PATTY 500G', 'productPool/1.jpg', 279 ),
( 'VENKEYS CHICKEN NUGGETS', 'productPool/1.jpg', 177 ),
( 'VENKEYS CHICKEN NUGGETS 500G', 'productPool/1.jpg', 1 ),
( 'VENKYS CHICKEN COCKTAIL SAUSAGES 300GM', 'productPool/1.jpg', 15 ),
( 'VENKYS CHICKEN KHEEMA 250GM', 'productPool/1.jpg', 191 ),
( 'VENKYS CHICKEN PLAIN KHEEMA', 'productPool/1.jpg', 9 ),
( 'VENKYS VIENNA CHICKEN SAUSAGES', 'productPool/1.jpg', 20 ),
( 'VENKYS VIENNA SAUSAGES 500GM', 'productPool/1.jpg', 73 ),
( 'VERMICELLI PAYASAM 200G', 'productPool/1.jpg', 19 ),
( 'VEWON TASTE ENHANCER', 'productPool/1.jpg', 270 ),
( 'VI JOHN SHAVI CRE 125G', 'productPool/1.jpg', 210 ),
( 'VI JOHN SHAVING CREAM', 'productPool/1.jpg', 163 ),
( 'VI JOHN SHAVING FOAM', 'productPool/1.jpg', 80 ),
( 'VI JOHN SHAVING FOAM 300G', 'productPool/1.jpg', 248 ),
( 'VI JOHN SHAVING FOAM 400G', 'productPool/1.jpg', 233 ),
( 'VI-JOHN CREAM125G', 'productPool/1.jpg', 135 ),
( 'VI-JOHN SAVIHG CREAM 30G', 'productPool/1.jpg', 86 ),
( 'VI-JOHN SHAVING CREAM CLASSIC 125G', 'productPool/1.jpg', 203 ),
( 'VI-JOHN SHAVING CREAM FRUIT 125G', 'productPool/1.jpg', 237 ),
( 'VI-JOHN SHAVING FOAM 400G', 'productPool/1.jpg', 129 ),
( 'VI-JOHN SHAVING FOAM50G', 'productPool/1.jpg', 146 ),
( 'VI-JOHN SPLASH SHAVE LOTION 50ML', 'productPool/1.jpg', 76 ),
( 'VIBHAVA PREMIUM 555 BROOM', 'productPool/1.jpg', 59 ),
( 'VICC VAJRADANTI SAUNF FLAVOUR 40G', 'productPool/1.jpg', 279 ),
( 'VICC VAJRADANTI SAUNF FLAVOUR 80G', 'productPool/1.jpg', 129 ),
( 'VICCO 150 G', 'productPool/1.jpg', 187 ),
( 'VICCO AYURVEDIC TOOTH PASTE 100G', 'productPool/1.jpg', 80 ),
( 'VICCO TOOTH PASTE 200G', 'productPool/1.jpg', 266 ),
( 'VICCO TOOTH PASTE 50 G', 'productPool/1.jpg', 57 ),
( 'VICCO TURMERIC SKIN CREAM 15G', 'productPool/1.jpg', 102 ),
( 'VICCO TURMERIC SKIN CREAM 30G', 'productPool/1.jpg', 194 ),
( 'VICCO TURMERIC SKIN CREAM 50G', 'productPool/1.jpg', 116 ),
( 'VICCO TURMERIC SKIN CREAM 70GM', 'productPool/1.jpg', 157 ),
( 'VICCO VAJRADANTI DENTALCARE 50G', 'productPool/1.jpg', 210 ),
( 'VICCO VAJRADANTI POWDER 100G', 'productPool/1.jpg', 30 ),
( 'VICCO VAJRADANTI SAUNF FLAVOUR 160G', 'productPool/1.jpg', 29 ),
( 'VICCO VAJRADANTI SAUNF FLAVOUR 20G', 'productPool/1.jpg', 52 ),
( 'VICCO VAJRADANTI TOOTH PAST 160G', 'productPool/1.jpg', 172 ),
( 'VICCO VAJRADANTI TOOTH PAST 40G', 'productPool/1.jpg', 101 ),
( 'VICE CHAIRMAN WASHING BRUSH', 'productPool/1.jpg', 8 ),
( 'VICE PRESIDENT WASHING BRUSH', 'productPool/1.jpg', 210 ),
( 'VICKS 3 IN 1 LOZENGES HONEY 8S', 'productPool/1.jpg', 273 ),
( 'VICKS 3 IN 1 LOZENGES ORANGE 8S', 'productPool/1.jpg', 11 ),
( 'VICKS BABYRUB 10ML', 'productPool/1.jpg', 11 ),
( 'VICKS BABYRUB 25ML', 'productPool/1.jpg', 180 ),
( 'VICKS BABYRUB 50ML', 'productPool/1.jpg', 208 ),
( 'VICKS COUGH DROPS GINGER', 'productPool/1.jpg', 272 ),
( 'VICKS COUGH DROPS JAR', 'productPool/1.jpg', 101 ),
( 'VICKS COUGH DROPS MENTHOL', 'productPool/1.jpg', 72 ),
( 'VICKS COUGH DROPS MIXED BAG', 'productPool/1.jpg', 220 ),
( 'VICKS INHALER 0.5 ML', 'productPool/1.jpg', 83 ),
( 'VICKS INHALER 5ML', 'productPool/1.jpg', 133 ),
( 'VICKS LOZENGES 3-IN-1', 'productPool/1.jpg', 22 ),
( 'VICKS MIXED JAR 280N', 'productPool/1.jpg', 4 ),
( 'VICKS VAPORUB 10ML', 'productPool/1.jpg', 227 ),
( 'VICKS VAPORUB 110ML', 'productPool/1.jpg', 90 ),
( 'VICKS VAPORUB 25 ML', 'productPool/1.jpg', 172 ),
( 'VICKS VAPORUB 50 ML', 'productPool/1.jpg', 75 ),
( 'VICKS VAPORUB 5ML', 'productPool/1.jpg', 171 ),
( 'VICTOR DRINKING CHOCOLATE 200G', 'productPool/1.jpg', 237 ),
( 'VICTORY GLASS STAND FAMILY', 'productPool/1.jpg', 224 ),
( 'VIEDA KACHIYA ENNA 100ML', 'productPool/1.jpg', 43 ),
( 'VIEDA MURINGA SOAP 100G', 'productPool/1.jpg', 28 ),
( 'VIEDA NUVO HAIR OIL 100ML', 'productPool/1.jpg', 257 ),
( 'VIEDA PINK SOAP 100G', 'productPool/1.jpg', 4 ),
( 'VIEDA PINK SOAP 100G 2+1', 'productPool/1.jpg', 255 ),
( 'VIEDA SEA BUCKTHORN SOAP 100G', 'productPool/1.jpg', 163 ),
( 'VIEDA SPA ESSENTIALS HIBISCUS SOAP 100G', 'productPool/1.jpg', 142 ),
( 'VIEDA SPA ESSENTIALS SOAP BLUE PEA 100G', 'productPool/1.jpg', 184 ),
( 'VIEDA WHITE COCONUT-SAFFRON 100G', 'productPool/1.jpg', 103 ),
( 'VIEDA WHITE SOAP 100G 2+1', 'productPool/1.jpg', 201 ),
( 'VIM 300G BAR', 'productPool/1.jpg', 222 ),
( 'VIM BAR 10RS', 'productPool/1.jpg', 159 ),
( 'VIM BAR FW 500G TUB', 'productPool/1.jpg', 6 ),
( 'VIM BAR FW AG 125G', 'productPool/1.jpg', 173 ),
( 'VIM BAR FW ANTI GERM 300GM', 'productPool/1.jpg', 220 ),
( 'VIM BAR LEMONS 150G', 'productPool/1.jpg', 179 ),
( 'VIM DISH WASH ACTIVE GEL LEMON 250 ML', 'productPool/1.jpg', 191 ),
( 'VIM EXTRA ANTI SMELL 250G', 'productPool/1.jpg', 136 ),
( 'VIM FASTEST 390G', 'productPool/1.jpg', 207 ),
( 'VIM FASTEST RS5', 'productPool/1.jpg', 247 ),
( 'VIM FASTEST SCRUBER 500G', 'productPool/1.jpg', 150 ),
( 'VIM GEL LEMON 115ML', 'productPool/1.jpg', 59 ),
( 'VIM GREEN LIQUID 250ML', 'productPool/1.jpg', 227 ),
( 'VIM GREEN LIQUID 500ML', 'productPool/1.jpg', 74 ),
( 'VIM HAND DISHWASHING LIQUID 5L', 'productPool/1.jpg', 190 ),
( 'VIM HANDPRO DISH WASH LIQUID 5L', 'productPool/1.jpg', 73 ),
( 'VIM LEMON GEL LIQUID 125ML', 'productPool/1.jpg', 106 ),
( 'VIM LEMON GEL750ML', 'productPool/1.jpg', 112 ),
( 'VIM LEMON YELLOW LIQUID 500 ML', 'productPool/1.jpg', 158 ),
( 'VIM LEMON YELLOW LIQUID 750ML', 'productPool/1.jpg', 139 ),
( 'VIM LIQUID DROP DISHWASH 500ML', 'productPool/1.jpg', 93 ),
( 'VIM LIQUID POUCH 225ML', 'productPool/1.jpg', 148 ),
( 'VIM NEEM ANTI LIQUID 250ML', 'productPool/1.jpg', 150 ),
( 'VIM NEEM ANTI LIQUID 500ML', 'productPool/1.jpg', 171 ),
( 'VIM POWER LEMONS LIQUID 55ML', 'productPool/1.jpg', 72 ),
( 'VIM POWER LEMONS LIQUID BOTTLE 1.8L', 'productPool/1.jpg', 237 ),
( 'VIM REMOVES GREASE FASTEST 600G', 'productPool/1.jpg', 255 ),
( 'VIM SOAP GREEN 500G', 'productPool/1.jpg', 53 ),
( 'VINAYAKA KUTTY PAPPADAM 80G', 'productPool/1.jpg', 194 ),
( 'VINAYAKA PAPPADAM 120G', 'productPool/1.jpg', 252 ),
( 'VINUT COCO WATER 330ML', 'productPool/1.jpg', 141 ),
( 'VINUT LYCHEE 330ML', 'productPool/1.jpg', 130 ),
( 'VINUT MIXED FRUIT DRINK 330ML', 'productPool/1.jpg', 223 ),
( 'VINUT RED ORANGE 330ML', 'productPool/1.jpg', 208 ),
( 'VINUT SOURSOP 330ML CAN', 'productPool/1.jpg', 250 ),
( 'VINUT TAMARIND 330ML', 'productPool/1.jpg', 26 ),
( 'VIP HAIR COLOUR SHAMPOO BLACK 180ML', 'productPool/1.jpg', 248 ),
( 'VIP HAIR COLOUR SHAMPOO BLACK 20ML', 'productPool/1.jpg', 127 ),
( 'VIP HAIR COLOUR SHAMPOO BLACK 40ML', 'productPool/1.jpg', 13 ),
( 'VIP WET DATES 500G', 'productPool/1.jpg', 252 ),
( 'VISHAL CLIP BIG', 'productPool/1.jpg', 57 ),
( 'VITAAZ APPLE DRINK MIX 500G POUCH', 'productPool/1.jpg', 130 ),
( 'VITAAZ DRINK MIX PASSION FRUIT 500G', 'productPool/1.jpg', 97 ),
( 'VITAAZ FUSION JAR DRINK MIX 750G', 'productPool/1.jpg', 212 ),
( 'VITAAZ GRAPES DINK MIX 750G JAR', 'productPool/1.jpg', 240 ),
( 'VITAAZ GUAVA 2.5KG', 'productPool/1.jpg', 3 ),
( 'VITAAZ GUAVA DRINK MIX 500G', 'productPool/1.jpg', 46 ),
( 'VITAAZ GUAVA FRUIT DRINK MIX2.5KG', 'productPool/1.jpg', 259 ),
( 'VITAAZ HONEY MELON 500G', 'productPool/1.jpg', 264 ),
( 'VITAAZ MANGO 2.5 KG', 'productPool/1.jpg', 6 ),
( 'VITAAZ MANGO DRINK 500G', 'productPool/1.jpg', 3 ),
( 'VITAAZ MANGO DRINK MIX 1KG', 'productPool/1.jpg', 75 ),
( 'VITAAZ ORANGE 1KG', 'productPool/1.jpg', 203 ),
( 'VITAAZ ORANGE 2.5 KG', 'productPool/1.jpg', 118 ),
( 'VITAAZ ORANGE DRINK 500G', 'productPool/1.jpg', 75 ),
( 'VITAAZ ORANGE DRINK MIX 1KG', 'productPool/1.jpg', 125 ),
( 'VITAAZ ORMAN DRINK MIX 750G', 'productPool/1.jpg', 190 ),
( 'VITAAZ PASSION FRUIT 2.5KG', 'productPool/1.jpg', 24 ),
( 'VITAAZ PINEAPPLE 2.5 KG', 'productPool/1.jpg', 118 ),
( 'VITAAZ PINEAPPLE 500G', 'productPool/1.jpg', 35 ),
( 'VITAAZ VITAAZ GUAVA DRINK 500G', 'productPool/1.jpg', 230 ),
( 'VITAAZ VITAAZ MANGO 500G JAR', 'productPool/1.jpg', 268 ),
( 'VITAAZ VITAAZ MANGO DRINK 2.5 KG', 'productPool/1.jpg', 213 ),
( 'VITAAZ VITAAZ ORANGE 500G', 'productPool/1.jpg', 175 ),
( 'VITAAZ VITAAZ PINEAPPLE DRINK 2.5KG', 'productPool/1.jpg', 188 ),
( 'VITAAZ VITAAZ PINEAPPLE DRINK 500G', 'productPool/1.jpg', 188 ),
( 'VITAAZ VITAAZ PINK GUAVA 750 G', 'productPool/1.jpg', 265 ),
( 'VITAAZ WATERMELON 2.5 KG', 'productPool/1.jpg', 149 ),
( 'VITAAZ WATERMELON 2.5KG', 'productPool/1.jpg', 202 ),
( 'VITAAZ WATERMELON DRINK MIX 500G', 'productPool/1.jpg', 229 ),
( 'VITTORIO OLIVE POMACE OIL 1L B1G1', 'productPool/1.jpg', 229 ),
( 'VIVA 500G REFILL', 'productPool/1.jpg', 165 ),
( 'VIVEL ALOE VER 300G', 'productPool/1.jpg', 176 ),
( 'VIVEL ALOE VERA 100*4 BATH SOAP', 'productPool/1.jpg', 144 ),
( 'VIVEL ALOE VERA SOAP 100G', 'productPool/1.jpg', 224 ),
( 'VIVEL ALOE VERA SOAP 4*100G BOX FREE', 'productPool/1.jpg', 103 ),
( 'VIVEL ALOE VERA SOAP 5*150G SET', 'productPool/1.jpg', 18 ),
( 'VIVEL ALOE VERA SOAP100G', 'productPool/1.jpg', 169 ),
( 'VIVEL ALOE VERA SOAP62G', 'productPool/1.jpg', 9 ),
( 'VIVEL ALOEVERA SOAP 30G', 'productPool/1.jpg', 205 ),
( 'VIVEL BODY WASH 100ML', 'productPool/1.jpg', 57 ),
( 'VIVEL BODY WASH LAVENDER ALMOND OIL 100ML', 'productPool/1.jpg', 183 ),
( 'VIVEL BODY WASH LAVENDER ALMOND OIL 200ML', 'productPool/1.jpg', 263 ),
( 'VIVEL BODY WASH LAVENDER ALMOND OIL 400ML', 'productPool/1.jpg', 58 ),
( 'VIVEL BODY WASH LAVENDER ALMOND OIL 500ML', 'productPool/1.jpg', 189 ),
( 'VIVEL BODY WASH MINT CUCUMBER 100ML', 'productPool/1.jpg', 131 ),
( 'VIVEL BODY WASH MINT CUCUMBER 200ML', 'productPool/1.jpg', 200 ),
( 'VIVEL BODY WASH MINT CUCUMBER 400ML', 'productPool/1.jpg', 218 ),
( 'VIVEL BODY WASH MINT CUCUMBER 500ML', 'productPool/1.jpg', 187 ),
( 'VIVEL COOL MINT 100G', 'productPool/1.jpg', 5 ),
( 'VIVEL COOL MINT 400G', 'productPool/1.jpg', 130 ),
( 'VIVEL COOL MINT SOAP 100G', 'productPool/1.jpg', 260 ),
( 'VIVEL COOL MINT SOAP 51G MRP10', 'productPool/1.jpg', 58 ),
( 'VIVEL GLYCERIN SOAP 75*3+1', 'productPool/1.jpg', 206 ),
( 'VIVEL GLYCERIN SOAP 75G', 'productPool/1.jpg', 250 ),
( 'VIVEL GLYCERIN SOFT MOISTURIZED SKIN75*3', 'productPool/1.jpg', 119 ),
( 'VIVEL GLYCERINE SOAP 100G', 'productPool/1.jpg', 257 ),
( 'VIVEL GREEN TEA 4*100GMS BATH SOAP', 'productPool/1.jpg', 224 ),
( 'VIVEL GREEN TEA 4*100GMS+1 BATH SOAP', 'productPool/1.jpg', 81 ),
( 'VIVEL GREEN TEA SOAP 100G', 'productPool/1.jpg', 203 ),
( 'VIVEL LOTUS OIL 100G', 'productPool/1.jpg', 74 ),
( 'VIVEL LOTUS OIL 51G', 'productPool/1.jpg', 101 ),
( 'VIVEL LOTUS OIL SET SOAP 100*4', 'productPool/1.jpg', 20 ),
( 'VIVEL LOTUS OIL SOAP 4*100G BOX FREE', 'productPool/1.jpg', 64 ),
( 'VIVEL LOTUS OIL SOAP 400G', 'productPool/1.jpg', 156 ),
( 'VIVEL LOTUS OIL SOAP 57G', 'productPool/1.jpg', 156 ),
( 'VIVEL LOTUS OIL SOAP100G', 'productPool/1.jpg', 231 ),
( 'VIVEL MIX FRU 300G', 'productPool/1.jpg', 160 ),
( 'VIVEL MIXED FRUIT + CREAM SOAP 100G', 'productPool/1.jpg', 46 ),
( 'VIVEL MIXED FRUIT +CREAM 100G', 'productPool/1.jpg', 128 ),
( 'VIVEL MIXED FRUIT CREAM 100*4GMS BATH SOAP', 'productPool/1.jpg', 171 ),
( 'VIVEL STRONG &SOFT SHAMPOO 6.4 ML', 'productPool/1.jpg', 270 ),
( 'VIVO ECLAIRS CHOCO CREAM 750G', 'productPool/1.jpg', 244 ),
( 'VIVO ECLAIRS HONEY 750G', 'productPool/1.jpg', 127 ),
( 'VIVO ECLAIRS MILK 750G', 'productPool/1.jpg', 98 ),
( 'VLC NEEM FACE WASH FREE ANTI TAN 150ML', 'productPool/1.jpg', 58 ),
( 'VLCC 3D YOUTH BOOST CREME SPF 40 100G', 'productPool/1.jpg', 270 ),
( 'VLCC 3D YOUTH BOOST SPF 40', 'productPool/1.jpg', 191 ),
( 'VLCC ACTIVE FRUITS BODY LAOTION B1G1 200ML', 'productPool/1.jpg', 100 ),
( 'VLCC ALMOND HONEY BODY LOTION 350ML', 'productPool/1.jpg', 193 ),
( 'VLCC ALMOND UNDER EYE CREAM 15G', 'productPool/1.jpg', 209 ),
( 'VLCC ALOE VERA SPF 15 BODY LOTION 350ML', 'productPool/1.jpg', 125 ),
( 'VLCC ANTI AGEING DAY CREAM SPF 25 50G', 'productPool/1.jpg', 125 ),
( 'VLCC ANTI AGEING FACE WASH 100ML', 'productPool/1.jpg', 34 ),
( 'VLCC ANTI TAN SINGLE FACIAL KIT 60G', 'productPool/1.jpg', 239 ),
( 'VLCC AYURVEDA ANTI AGEING CREAM 50G', 'productPool/1.jpg', 109 ),
( 'VLCC AYURVEDA CHANDAN KESAR FACE WASH 100ML', 'productPool/1.jpg', 222 ),
( 'VLCC AYURVEDA DANDRUFF CONTROL SHAMPOO 110ML', 'productPool/1.jpg', 33 ),
( 'VLCC AYURVEDA ESSENTL COMBO 300G', 'productPool/1.jpg', 10 ),
( 'VLCC AYURVEDA HALDI TULSI FACE WASH 100ML', 'productPool/1.jpg', 54 ),
( 'VLCC AYURVEDA SKIN PURIFYING NEEM FW 100ML', 'productPool/1.jpg', 58 ),
( 'VLCC AYUSH MEN FACE SCRUB 50G', 'productPool/1.jpg', 148 ),
( 'VLCC AYUSH MEN FACE WASH 100G', 'productPool/1.jpg', 61 ),
( 'VLCC AYUSH MEN MOISTURISER 50G', 'productPool/1.jpg', 120 ),
( 'VLCC AYUSH MEN SHAVING GEL 60G', 'productPool/1.jpg', 211 ),
( 'VLCC AYUSH SHAVING CREM MEN 125.G', 'productPool/1.jpg', 246 ),
( 'VLCC CHARCOAL FAC WASH 100ML', 'productPool/1.jpg', 193 ),
( 'VLCC CHARCOAL FACE PACK 100G', 'productPool/1.jpg', 110 ),
( 'VLCC CHARCOAL PEEL OFF MASK 100G', 'productPool/1.jpg', 44 ),
( 'VLCC COCOA BUTTER BODY LOTION 350ML', 'productPool/1.jpg', 179 ),
( 'VLCC DAILY PROTECT SPF 25 SUN DWEFENSE 100G', 'productPool/1.jpg', 117 ),
( 'VLCC DANDRUFF CONTROL SHAMPOO 200ML', 'productPool/1.jpg', 241 ),
( 'VLCC DE PIGMENTATION DAY CREAM 50G', 'productPool/1.jpg', 168 ),
( 'VLCC DE PIGMENTATION FACE MUSK CREAM 80G', 'productPool/1.jpg', 84 ),
( 'VLCC DE PIGMENTATION NIGHT SW CREAM 50G', 'productPool/1.jpg', 108 ),
( 'VLCC DE TAN CREME SPF 50 100G', 'productPool/1.jpg', 239 ),
( 'VLCC DEEP PORE CLEANDING HALDI THULSI', 'productPool/1.jpg', 74 ),
( 'VLCC DIAMOND SINGLE FACIAL KIT', 'productPool/1.jpg', 156 ),
( 'VLCC DOUBLE NEEM FACE WASH 50ML', 'productPool/1.jpg', 105 ),
( 'VLCC DOUBLE POWER DOUBLE NEEM FACIAL KIT', 'productPool/1.jpg', 13 ),
( 'VLCC FAIR + GLOW SUN SCREEN LOTION SPF 20 50ML', 'productPool/1.jpg', 173 ),
( 'VLCC FAIR + GLOW SUN SCREEN LOTION SPF20 100ML', 'productPool/1.jpg', 156 ),
( 'VLCC GLOW SPF 20 SUN DEFENSE 100ML', 'productPool/1.jpg', 76 ),
( 'VLCC GLOW SPF 20 SUN SCREEN LOTION 60ML', 'productPool/1.jpg', 157 ),
( 'VLCC GOLD FACIAL KIT GLOW 60G', 'productPool/1.jpg', 246 ),
( 'VLCC HAIR FALL CONTROL SHAMPOO 100ML', 'productPool/1.jpg', 168 ),
( 'VLCC HAIR FALL REPAIR SHAMPOO 200ML', 'productPool/1.jpg', 32 ),
( 'VLCC HAIR FALL REPAIR SHAMPOO 350ML', 'productPool/1.jpg', 98 ),
( 'VLCC HAIR NOURISHMENT SHAMPOO 100ML', 'productPool/1.jpg', 205 ),
( 'VLCC HAIR STRENGTHENING OIL 100ML', 'productPool/1.jpg', 61 ),
( 'VLCC HALDI CHANDAN FACE WASH 100ML', 'productPool/1.jpg', 255 ),
( 'VLCC HALDI CHANDAN FACE WASH 50ML', 'productPool/1.jpg', 201 ),
( 'VLCC HALDI TULSI FACE WASH 50ML', 'productPool/1.jpg', 178 ),
( 'VLCC HENNA 200G', 'productPool/1.jpg', 83 ),
( 'VLCC HENNA NATURA COLOUR 1 NATURAL BLACK', 'productPool/1.jpg', 143 ),
( 'VLCC HENNA NATURA COLOUR 4 NATURAL BROWN', 'productPool/1.jpg', 221 ),
( 'VLCC HONEY MOISTURISER SKIN DEFENSE 100ML', 'productPool/1.jpg', 78 ),
( 'VLCC HYDRATING NIGHT CREAM 50G', 'productPool/1.jpg', 214 ),
( 'VLCC INDIAN BERBERRY FACE SCRUB 80G', 'productPool/1.jpg', 218 ),
( 'VLCC INSTA FAIR & GLOW FAIRNESS CREAM 25G', 'productPool/1.jpg', 196 ),
( 'VLCC INSTA FAIR & GLOW FAIRNESS CREAM 50G', 'productPool/1.jpg', 138 ),
( 'VLCC INSTA FAIR AND GLOW COLD CREAM 10G', 'productPool/1.jpg', 22 ),
( 'VLCC INSTA FAIR AND GLOW COLD CREAM 75G B1G1', 'productPool/1.jpg', 13 ),
( 'VLCC INSTA FAIR AND GLOW FAIRNESS CREAM 25G', 'productPool/1.jpg', 202 ),
( 'VLCC INSTA GLOW DIAMOND BLEACH 30G', 'productPool/1.jpg', 220 ),
( 'VLCC INSTA GLOW DIAMOND BLEACH 6.6G', 'productPool/1.jpg', 189 ),
( 'VLCC INSTA GLOW DIAMOND BLEACH 60G', 'productPool/1.jpg', 147 ),
( 'VLCC INSTA GLOW GOLD BLEACH 30G', 'productPool/1.jpg', 110 ),
( 'VLCC INSTA GLOW GOLD BLEACH 6.6G', 'productPool/1.jpg', 205 ),
( 'VLCC INSTA GLOW GOLD BLEACH 60G', 'productPool/1.jpg', 118 ),
( 'VLCC INSTA GLOW HERBAL BLEACH 27G', 'productPool/1.jpg', 173 ),
( 'VLCC INSTA GLOW HERBAL BLEACH 54G', 'productPool/1.jpg', 55 ),
( 'VLCC INSTA GLOW HERBAL BLEACH 6.6G', 'productPool/1.jpg', 213 ),
( 'VLCC INSTA GLOW OXYGEN BLEACH 25.7G', 'productPool/1.jpg', 243 ),
( 'VLCC INSTA GLOW OXYGEN BLEACH 51.4G', 'productPool/1.jpg', 15 ),
( 'VLCC INSTA GLOW OXYGEN BLEACH 6.9G', 'productPool/1.jpg', 222 ),
( 'VLCC INTENSIVE CARE COLD CREAM 75G', 'productPool/1.jpg', 234 ),
( 'VLCC KAJAL 1G', 'productPool/1.jpg', 133 ),
( 'VLCC KAJAL 2.5 G', 'productPool/1.jpg', 13 ),
( 'VLCC KESAR CHANDAN FACEWASH 50ML', 'productPool/1.jpg', 114 ),
( 'VLCC KESH AYUR SHAKTI HAIR OIL 120ML', 'productPool/1.jpg', 205 ),
( 'VLCC LAVANG MOISTURISER SKIN CREAM 100ML', 'productPool/1.jpg', 48 ),
( 'VLCC LIP BALM 4.5G B1G1', 'productPool/1.jpg', 82 ),
( 'VLCC LIQUORICE COLD CREAM 50G', 'productPool/1.jpg', 10 ),
( 'VLCC LOVABLE LIPS CHERRY 9G', 'productPool/1.jpg', 180 ),
( 'VLCC MANDARIN & TOMATO FACE WASH 175ML', 'productPool/1.jpg', 197 ),
( 'VLCC MANICURE PEDICURE KIT 150G', 'productPool/1.jpg', 55 ),
( 'VLCC MATTE LOOK SPF30 CREME 100G', 'productPool/1.jpg', 148 ),
( 'VLCC MATTE LOOK SPF30 CREME 50G', 'productPool/1.jpg', 160 ),
( 'VLCC MATTE LOOK SUN SCREEN CREAM', 'productPool/1.jpg', 233 ),
( 'VLCC MELIA FACE WASH SKIN DEFENSE 80ML', 'productPool/1.jpg', 231 ),
( 'VLCC MEN AYUSH GROOMING FACE WASH 50G', 'productPool/1.jpg', 113 ),
( 'VLCC MUD FACE PACK SKIN DEFENSE 70G', 'productPool/1.jpg', 143 ),
( 'VLCC MULBERRY ROSE FACE WASH 150ML', 'productPool/1.jpg', 269 ),
( 'VLCC NATURAL DANDRUFF CARE SHAMPOO 350ML', 'productPool/1.jpg', 279 ),
( 'VLCC NATURAL HERBAL HENNA 120G', 'productPool/1.jpg', 211 ),
( 'VLCC NATURAL HERBAL HENNA 50G', 'productPool/1.jpg', 176 ),
( 'VLCC NEEM FACE WASH 100ML', 'productPool/1.jpg', 162 ),
( 'VLCC NEEM FACE WASH SKIN DEFENSE 50ML', 'productPool/1.jpg', 226 ),
( 'VLCC PAPAYA APRICOT FACE SCRUB 80G', 'productPool/1.jpg', 175 ),
( 'VLCC PAPAYA FRUIT FACIAL KIT GLOW 60G', 'productPool/1.jpg', 120 ),
( 'VLCC PARTY GLOW FACIAL KIT 60G', 'productPool/1.jpg', 22 ),
( 'VLCC PEARL FACIAL KIT GLOW 60G', 'productPool/1.jpg', 118 ),
( 'VLCC PEDIGLOW FOOT CARE KIT 295G', 'productPool/1.jpg', 179 ),
( 'VLCC PISTA MASSAGE CREAM SKIN DEFENSE 50G', 'productPool/1.jpg', 211 ),
( 'VLCC PLATINUM FACIAL KIT', 'productPool/1.jpg', 27 ),
( 'VLCC PUNARNAVA ASTRINGENT 100ML', 'productPool/1.jpg', 163 ),
( 'VLCC RADIANCE PRO SPF 30 50ML', 'productPool/1.jpg', 122 ),
( 'VLCC RADIANCE PRO SUN SCREEN GEL SPF30 100G', 'productPool/1.jpg', 1 ),
( 'VLCC ROSE FACE SCRUB 80G', 'productPool/1.jpg', 279 ),
( 'VLCC ROSE WATER TONER 100ML', 'productPool/1.jpg', 187 ),
( 'VLCC SANDAL CLEANSING MILK 100ML', 'productPool/1.jpg', 126 ),
( 'VLCC SHAPE UP 10 IN 1 OIL 25ML', 'productPool/1.jpg', 42 ),
( 'VLCC SILVER FACIAL KIT 60G', 'productPool/1.jpg', 70 ),
( 'VLCC SKIN BRIGHTENING HALDI THULSI FACIAL KIT', 'productPool/1.jpg', 157 ),
( 'VLCC SKIN GLOW MINI FACIAL KIT 25G', 'productPool/1.jpg', 69 ),
( 'VLCC SKIN TIGHTENING MINI FACIAL KIT 25G', 'productPool/1.jpg', 158 ),
( 'VLCC SKIN WHITENING MINI FACIAL KIT 25G', 'productPool/1.jpg', 240 ),
( 'VLCC SMOOTH SHINE SHAMPOO 100ML', 'productPool/1.jpg', 225 ),
( 'VLCC SNIGDHA SKIN WHITENING CREAM 50G', 'productPool/1.jpg', 8 ),
( 'VLCC SNIGDHA SKIN WHITENING SERUM', 'productPool/1.jpg', 19 ),
( 'VLCC SNIGDHA WHITENING FACE WASH 100ML', 'productPool/1.jpg', 163 ),
( 'VLCC SNIGDHA WHITENING NIGHT CREAM 50G', 'productPool/1.jpg', 32 ),
( 'VLCC SOOTHING ALOEVERA GEL 100G', 'productPool/1.jpg', 163 ),
( 'VLCC TULSI FACEWASH ORANGE OIL FREE 300ML', 'productPool/1.jpg', 165 ),
( 'VLCC TURMERIC BERBERIS FACE WASH 150ML', 'productPool/1.jpg', 64 ),
( 'VLCC VITALIFT SERUM 40ML', 'productPool/1.jpg', 193 ),
( 'VLCC WALNUT SCRUB 80G', 'productPool/1.jpg', 83 ),
( 'VLCC WATER RESISTANT SPF 60', 'productPool/1.jpg', 9 ),
( 'VLCC WILD TURMERIC FACE WASH 80ML', 'productPool/1.jpg', 193 ),
( 'VLCC YOUTH BOOST BODY LOTION 100ML', 'productPool/1.jpg', 151 ),
( 'VNUT GUAVA 330ML', 'productPool/1.jpg', 46 ),
( 'VRINDHATONE SYRUP 200ML', 'productPool/1.jpg', 170 ),
( 'W240 PLAIN CASHEW 1KG', 'productPool/1.jpg', 59 ),
( 'W240 ROASTED CASHEW', 'productPool/1.jpg', 103 ),
( 'WALL HANGER NO 5 2PCS FAMILY', 'productPool/1.jpg', 9 ),
( 'WALL HANGER NO 6 2 PCS FAMILY', 'productPool/1.jpg', 260 ),
( 'WALL HANGER NO 7 2 PCS FAMILY', 'productPool/1.jpg', 276 ),
( 'WALNUT 50G', 'productPool/1.jpg', 33 ),
( 'WASH BASIN BRUSH', 'productPool/1.jpg', 16 ),
( 'WASHING SOAD 200G', 'productPool/1.jpg', 21 ),
( 'WAST PAPER BASKET 250 FAMILY', 'productPool/1.jpg', 185 ),
( 'WAST PAPER BASKET 280 WITH RING', 'productPool/1.jpg', 102 ),
( 'WASTE TRAY MOULD 02', 'productPool/1.jpg', 179 ),
( 'WASTECLEEN ECO FRIENDLY 500ML', 'productPool/1.jpg', 261 ),
( 'WATER BOTTLE RS 145', 'productPool/1.jpg', 73 ),
( 'WATER BOTTLE RS 210', 'productPool/1.jpg', 11 ),
( 'WATER BOTTLE RS125', 'productPool/1.jpg', 207 ),
( 'WATER BOTTLE RS130', 'productPool/1.jpg', 220 ),
( 'WATER BOTTLE RS145', 'productPool/1.jpg', 134 ),
( 'WATER BOTTLE RS165', 'productPool/1.jpg', 23 ),
( 'WATER BOTTLE RS170', 'productPool/1.jpg', 164 ),
( 'WATER BOTTLE SPORT', 'productPool/1.jpg', 152 ),
( 'WATER COLOUR TUBES 12SHADES', 'productPool/1.jpg', 41 ),
( 'WATER PROOF EYEL INER 1.5G', 'productPool/1.jpg', 82 ),
( 'WATER PURIFIER WITH COOKER COMBI', 'productPool/1.jpg', 190 ),
( 'WATERMELON', 'productPool/1.jpg', 114 ),
( 'WAX RIBBON 85X 300D', 'productPool/1.jpg', 176 ),
( 'WELL COTTON BUDS', 'productPool/1.jpg', 151 ),
( 'WELLA STRAIT WHITE IMP', 'productPool/1.jpg', 65 ),
( 'WELLS ALMOND OIL', 'productPool/1.jpg', 45 ),
( 'WELLS ALMOND OIL 100ML', 'productPool/1.jpg', 175 ),
( 'WELLS ALMOND OIL 175 ML', 'productPool/1.jpg', 275 ),
( 'WELLS ALMOND OIL 175ML', 'productPool/1.jpg', 266 ),
( 'WELLS ALMOND OIL 70ML', 'productPool/1.jpg', 93 ),
( 'WH OYSTER SAUCE', 'productPool/1.jpg', 139 ),
( 'WH PREMIUM LIGHT SOY SAUCE', 'productPool/1.jpg', 106 ),
( 'WH THAI CHILLI SAUSE', 'productPool/1.jpg', 204 ),
( 'WHEAT CHAKKI ATTA 5 KG', 'productPool/1.jpg', 232 ),
( 'WHEAT MAIDA 500G', 'productPool/1.jpg', 14 ),
( 'WHEAT PAROTTA', 'productPool/1.jpg', 142 ),
( 'WHEAT SUJI 500 KG', 'productPool/1.jpg', 56 ),
( 'WHEEL LEMON & JASMINE 500GM', 'productPool/1.jpg', 32 ),
( 'WHEEL LEMON & JASMINE POWDER 500G', 'productPool/1.jpg', 50 ),
( 'WHEEL LEMON JASMIN POWDER 180G', 'productPool/1.jpg', 165 ),
( 'WHISKAS CAT FOOD ADULT 1.2KG', 'productPool/1.jpg', 5 ),
( 'WHISKAS CAT FOOD JUNIOR 1.1KG', 'productPool/1.jpg', 115 ),
( 'WHISKAS CAT FOOD JUNIOR 450G', 'productPool/1.jpg', 10 ),
( 'WHISPER CHICE WINGS XL 6S', 'productPool/1.jpg', 117 ),
( 'WHISPER CHOCIE WINGS 20S', 'productPool/1.jpg', 125 ),
( 'WHISPER CHOICE ALOE VERA XL 6S', 'productPool/1.jpg', 150 ),
( 'WHISPER CHOICE ALOEVERA 7S', 'productPool/1.jpg', 106 ),
( 'WHISPER CHOICE EXTRA LONG 6S', 'productPool/1.jpg', 34 ),
( 'WHISPER CHOICE EXTRA LONG XL 6S', 'productPool/1.jpg', 135 ),
( 'WHISPER CHOICE ULTRA 6S', 'productPool/1.jpg', 93 ),
( 'WHISPER CHOICE ULTRA XL 20S', 'productPool/1.jpg', 180 ),
( 'WHISPER CHOICE ULTRA XL 6S', 'productPool/1.jpg', 27 ),
( 'WHISPER CHOICE WINGS 7PADS', 'productPool/1.jpg', 65 ),
( 'WHISPER CHOICE WINGS 7S', 'productPool/1.jpg', 204 ),
( 'WHISPER CHOICE WINGS ALOEVERA 20S', 'productPool/1.jpg', 270 ),
( 'WHISPER CHOICE WINGS ALOEVERA 7S', 'productPool/1.jpg', 205 ),
( 'WHISPER CHOICE WINGS REGULAR 20S', 'productPool/1.jpg', 205 ),
( 'WHISPER DAILY LINERS 20N', 'productPool/1.jpg', 171 ),
( 'WHISPER DAILY LINERS 40N', 'productPool/1.jpg', 241 ),
( 'WHISPER MAXI FIT L WINGS 15S', 'productPool/1.jpg', 258 ),
( 'WHISPER MAXI FIT L WINGS 8S', 'productPool/1.jpg', 226 ),
( 'WHISPER MAXI FIT LARGE WINGS 15N', 'productPool/1.jpg', 134 ),
( 'WHISPER MAXI FIT REGULAR 15S', 'productPool/1.jpg', 131 ),
( 'WHISPER MAXI FIT REGULAR 8S', 'productPool/1.jpg', 228 ),
( 'WHISPER MAXI NIGHT 15S', 'productPool/1.jpg', 213 ),
( 'WHISPER MAXI NIGHTS XL WINGS 15S', 'productPool/1.jpg', 213 ),
( 'WHISPER MAXI OVER NIGHT 7S', 'productPool/1.jpg', 206 ),
( 'WHISPER ULTRA CLEAN XL + 15S', 'productPool/1.jpg', 129 ),
( 'WHISPER ULTRA CLEAN XL + 44S', 'productPool/1.jpg', 57 ),
( 'WHISPER ULTRA CLEAN XL + 7S', 'productPool/1.jpg', 238 ),
( 'WHISPER ULTRA CLEAN XL +30S', 'productPool/1.jpg', 59 ),
( 'WHISPER ULTRA CLEAN XL 15S', 'productPool/1.jpg', 174 ),
( 'WHISPER ULTRA CLEAN XL 30 S', 'productPool/1.jpg', 155 ),
( 'WHISPER ULTRA CLEAN XL 8S', 'productPool/1.jpg', 164 ),
( 'WHISPER ULTRA CLEAN XL WINGS 30S', 'productPool/1.jpg', 137 ),
( 'WHISPER ULTRA CLEAN XL+15S * 4', 'productPool/1.jpg', 72 ),
( 'WHISPER ULTRA CLEAN XL+30S', 'productPool/1.jpg', 121 ),
( 'WHISPER ULTRA NIGHT XL+30S', 'productPool/1.jpg', 93 ),
( 'WHISPER ULTRA NIGHTS XL + 15S', 'productPool/1.jpg', 207 ),
( 'WHISPER ULTRA NIGHTS XL + 7S', 'productPool/1.jpg', 11 ),
( 'WHISPER ULTRA NIGHTS XL 15S BUY 3', 'productPool/1.jpg', 169 ),
( 'WHISPER ULTRA NIGHTS XXL + 5S', 'productPool/1.jpg', 35 ),
( 'WHISPER ULTRA NIGHTS XXL+', 'productPool/1.jpg', 111 ),
( 'WHISPER ULTRA NIGHTS XXXL 10S', 'productPool/1.jpg', 116 ),
( 'WHISPER ULTRA NIGHTS XXXL 3S', 'productPool/1.jpg', 118 ),
( 'WHISPER ULTRA SOFT XL + 15S', 'productPool/1.jpg', 145 ),
( 'WHISPER ULTRA SOFT XL +30S', 'productPool/1.jpg', 15 ),
( 'WHISPER ULTRA SOFT XL 15S', 'productPool/1.jpg', 109 ),
( 'WHISPER ULTRA SOFT XL 30S', 'productPool/1.jpg', 212 ),
( 'WHISPER ULTRA SOFT XL 50S', 'productPool/1.jpg', 168 ),
( 'WHISPER ULTRA SOFT XL 7S', 'productPool/1.jpg', 45 ),
( 'WHISPER ULTRA SOFT XL+ 15N', 'productPool/1.jpg', 189 ),
( 'WHISPER ULTRA SOFT XL+ 7S', 'productPool/1.jpg', 185 ),
( 'WHISPER ULTRA XL 15S', 'productPool/1.jpg', 221 ),
( 'WHISPER ULTRA XL+15S*4', 'productPool/1.jpg', 247 ),
( 'WHITE BOARD MARKER BLUE 1223', 'productPool/1.jpg', 53 ),
( 'WHITE ELLU', 'productPool/1.jpg', 36 ),
( 'WHITE ELLU 100G', 'productPool/1.jpg', 116 ),
( 'WHITE FOREST PASTRY', 'productPool/1.jpg', 85 ),
( 'WHITE KADALA 500G', 'productPool/1.jpg', 204 ),
( 'WHITE KADALA 500GMS', 'productPool/1.jpg', 68 ),
( 'WHITE LEMON PICKLE 200G', 'productPool/1.jpg', 103 ),
( 'WHITE NONSTICK PALTA SMALL', 'productPool/1.jpg', 190 ),
( 'WHITE PEANUT 100G', 'productPool/1.jpg', 277 ),
( 'WHITE PEANUT 200G', 'productPool/1.jpg', 218 ),
( 'WHITE PEANUT 70G', 'productPool/1.jpg', 67 ),
( 'WHITE PEPPER 50G', 'productPool/1.jpg', 66 ),
( 'WHITE TONE FACE POWDER 30G', 'productPool/1.jpg', 158 ),
( 'WHITE TONE FACE POWDER 50G', 'productPool/1.jpg', 26 ),
( 'WHITE TONE FACE POWDER 70G', 'productPool/1.jpg', 24 ),
( 'WHITE TONE SOFT SMOOTH FACE CREAM 25G', 'productPool/1.jpg', 192 ),
( 'WHITE TONE SOFT SMOOTH FACE CREAM 50G', 'productPool/1.jpg', 211 ),
( 'WHITNEY WATER 5L', 'productPool/1.jpg', 226 ),
( 'WILKINSON DE BLADE 5S', 'productPool/1.jpg', 171 ),
( 'WINKIES CHOCOLATE CAKE SLICED 140G', 'productPool/1.jpg', 148 ),
( 'WINKIES CHOCOLATE CAKE SLICED 60G', 'productPool/1.jpg', 126 ),
( 'WINKIES ENGLISH TEA CAKE', 'productPool/1.jpg', 225 ),
( 'WINKIES FRUIT CAKE SLICED 140G', 'productPool/1.jpg', 71 ),
( 'WINKIES FRUIT CAKE SLICED 60G', 'productPool/1.jpg', 16 ),
( 'WINKIES MARBLE CAKE SLICED 140G', 'productPool/1.jpg', 137 ),
( 'WINKIES MINI SWISS ROLL APPLE 35G', 'productPool/1.jpg', 57 ),
( 'WINKIES MINI SWISS ROLL STRAWBERRY 30G', 'productPool/1.jpg', 186 ),
( 'WINKIES PINEAPPLE CAKE 130G', 'productPool/1.jpg', 189 ),
( 'WINKIES PINEAPPLE CAKE SLICED 60G', 'productPool/1.jpg', 277 ),
( 'WINKIES SWISS ROLL COCOA CREAM 185G', 'productPool/1.jpg', 267 ),
( 'WINKIES SWISS ROLL MINI CHOCOLATE 30G', 'productPool/1.jpg', 118 ),
( 'WINKIES SWISS ROLL MINI MANGO 30G', 'productPool/1.jpg', 126 ),
( 'WINKIES SWISS ROLL MINI STRAWBERY 30G', 'productPool/1.jpg', 71 ),
( 'WINKIES SWISS ROLL STRAWBERRY 185G', 'productPool/1.jpg', 48 ),
( 'WINNER KITCHEN MATCHES MRP 10', 'productPool/1.jpg', 218 ),
( 'WIPRO 15W CFL', 'productPool/1.jpg', 9 ),
( 'WIPRO 23W CFL', 'productPool/1.jpg', 116 ),
( 'WIPRO COLOR LAMP', 'productPool/1.jpg', 188 ),
( 'WIPRO GARNET 5W LED', 'productPool/1.jpg', 189 ),
( 'WIPRO GARNET LED 12W', 'productPool/1.jpg', 98 ),
( 'WIPRO GARNET LED 14W MRP 320', 'productPool/1.jpg', 69 ),
( 'WIPRO GARNET LED 18W', 'productPool/1.jpg', 80 ),
( 'WIPRO GARNET LED 5W', 'productPool/1.jpg', 104 ),
( 'WIPRO GARNET LED7W', 'productPool/1.jpg', 230 ),
( 'WIPRO GARNET LED9W', 'productPool/1.jpg', 176 ),
( 'WIPRO LED TUBE 20W', 'productPool/1.jpg', 156 ),
( 'WIPRO SAFE WASH BLUE 1000ML', 'productPool/1.jpg', 150 ),
( 'WIPRO SAFE WASH FABRIC CONDITIONER PINK 1LTR', 'productPool/1.jpg', 145 ),
( 'WIPRO SAFE WASH PINK 400ML', 'productPool/1.jpg', 72 ),
( 'WIPRO SAFEWASH BLUE FABRIC CONDITIONER 230ML', 'productPool/1.jpg', 272 ),
( 'WIPRO SAFEWASH OCEAN BREEZE400ML BLUE', 'productPool/1.jpg', 47 ),
( 'WIPRO SAFEWASH PINK FABRIC CONDITIONER 230ML', 'productPool/1.jpg', 30 ),
( 'WIPRO SANTHOOR GOLD 125G*3 SET SOAP', 'productPool/1.jpg', 260 ),
( 'WIPRO SANTOOR GOLD 75G', 'productPool/1.jpg', 60 ),
( 'WIPRO SMARTLITE CFL 11W MRP 160', 'productPool/1.jpg', 232 ),
( 'WIPRO SMARTLITE CFL 28W', 'productPool/1.jpg', 32 ),
( 'WIPRO SMARTLITE CFL 28W MRP 275', 'productPool/1.jpg', 21 ),
( 'WIPRO SMARTLITE CLASSIC 20W', 'productPool/1.jpg', 227 ),
( 'WIPRO SMARTLITE MINI CFL 8W MRP 160', 'productPool/1.jpg', 232 ),
( 'WIPRO TEJAS 5W', 'productPool/1.jpg', 75 ),
( 'WIPRO TEJAS 7W', 'productPool/1.jpg', 265 ),
( 'WOH HUP BLACK PEPPER SAUCE 285G', 'productPool/1.jpg', 213 ),
( 'WOH HUP DARK SOYA SAUCE 640ML', 'productPool/1.jpg', 209 ),
( 'WOH HUP OYSTER SAUCE 480G', 'productPool/1.jpg', 158 ),
( 'WOMENS HORLICKS CARAMEL 400G', 'productPool/1.jpg', 8 ),
( 'WOMENS HORLICKS CARAMEL 400GJAR', 'productPool/1.jpg', 168 ),
( 'WOMENS HORLICKS CHOCOLATE400G JAR', 'productPool/1.jpg', 24 ),
( 'WONDER ARROW BOTTLE 900ML', 'productPool/1.jpg', 45 ),
( 'WONDER LADY WASHING BRUSH', 'productPool/1.jpg', 163 ),
( 'WONDER ORANGE CAKE 150G', 'productPool/1.jpg', 47 ),
( 'WONDER WATER BOTTLE 1L', 'productPool/1.jpg', 140 ),
( 'WONDERCHEF 6 IN SCISSOR', 'productPool/1.jpg', 97 ),
( 'WONDERCHEF CLASSIC STRING CHOPPER', 'productPool/1.jpg', 259 ),
( 'WONDERCHEF COCONUT SCRAPER', 'productPool/1.jpg', 14 ),
( 'WONDERCHEF DOSA TAWA 30CM', 'productPool/1.jpg', 168 ),
( 'WONDERCHEF FLAT DOSA TAWA 28CM', 'productPool/1.jpg', 104 ),
( 'WONDERCHEF FLAT DOSA TAWA 33CM', 'productPool/1.jpg', 7 ),
( 'WONDERCHEF MASON JAR SET', 'productPool/1.jpg', 15 ),
( 'WONDERCHEF NUTRI BLEND BLACK', 'productPool/1.jpg', 103 ),
( 'WONDERCHEF NUTRIBLEND WITH JUICER BLACK', 'productPool/1.jpg', 132 ),
( 'WONDERCHEF NUTRIBLEND WITH JUICER RED', 'productPool/1.jpg', 31 ),
( 'WONDERCHEF OIL POURER 550ML', 'productPool/1.jpg', 258 ),
( 'WONDERCHEF REGALIA HAND MIXER', 'productPool/1.jpg', 28 ),
( 'WONDERCHEF REGALIA STAND MIXER', 'productPool/1.jpg', 196 ),
( 'WONDERCHEF ROTANA STEAM IRON', 'productPool/1.jpg', 228 ),
( 'WONDERFULLS BUTTER JEERA 75G', 'productPool/1.jpg', 152 ),
( 'WONDERFULLS MIXED FRUIT 75G', 'productPool/1.jpg', 29 ),
( 'WONDWERCHEF ROYAL VELVET MINI FRY PAN 14CM', 'productPool/1.jpg', 217 ),
( 'WOOD SPOON B 10P', 'productPool/1.jpg', 28 ),
( 'WOOD SPOON M 10P', 'productPool/1.jpg', 41 ),
( 'WORLDONE A4 INDEX FILE RB406', 'productPool/1.jpg', 87 ),
( 'WORLDONE A5 VOUCHER FILE RB407', 'productPool/1.jpg', 151 ),
( 'WORLDONE ALL PINS WPS084 50G', 'productPool/1.jpg', 265 ),
( 'WORLDONE BINDER CLIPS 12PC', 'productPool/1.jpg', 54 ),
( 'WORLDONE BINDER CLIPS 25MM 12PC', 'productPool/1.jpg', 40 ),
( 'WORLDONE BINDER CLIPS 32MM 12PC', 'productPool/1.jpg', 187 ),
( 'WORLDONE BINDER CLIPS 41MM 12PC', 'productPool/1.jpg', 252 ),
( 'WORLDONE BINDER CLIPS 51MM WPS051', 'productPool/1.jpg', 270 ),
( 'WORLDONE BUTTON ENVELOPE BAG DC202-B', 'productPool/1.jpg', 123 ),
( 'WORLDONE BUTTON ENVELOPE BAG DC207-V', 'productPool/1.jpg', 169 ),
( 'WORLDONE CLEAR BOOK CB500F', 'productPool/1.jpg', 195 ),
( 'WORLDONE CLEAR BOOK CB501F', 'productPool/1.jpg', 32 );