INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'HIDE &SEEK CHCO ROLLS 75G', 'productPool/1.jpg', 76 ),
( 'HIDE&SEEK BLACK BOURBON COMB', 'productPool/1.jpg', 26 ),
( 'HIDE&SEEK BLACKBOURBON CHOCO 100G', 'productPool/1.jpg', 98 ),
( 'HIDE&SEEK BLACKBOURBON VANILLA 100G', 'productPool/1.jpg', 73 ),
( 'HIGH POWER TILE CLEENER CEMENT CLEENER 1000ML', 'productPool/1.jpg', 13 ),
( 'HIGH RANGE INDUPPU 100G', 'productPool/1.jpg', 102 ),
( 'HIGH RANGE KONDATTAM MULAKU 100G', 'productPool/1.jpg', 150 ),
( 'HIGH RANGE KUDAM PULY 100G', 'productPool/1.jpg', 134 ),
( 'HIGH RANGE KUDAM PULY 200G', 'productPool/1.jpg', 120 ),
( 'HIGH RANGE MUSTARD DAL 50G', 'productPool/1.jpg', 82 ),
( 'HIGH RANGE SAJEERAKAM 25G', 'productPool/1.jpg', 114 ),
( 'HIGH RANGE WHITE PEPPER 50G', 'productPool/1.jpg', 276 ),
( 'HIGHRANGE AYAMODAKAM 50GM', 'productPool/1.jpg', 140 ),
( 'HIGHRANGE MAIZE POP CORN 500G', 'productPool/1.jpg', 33 ),
( 'HILLY AQUA WATER 300ML', 'productPool/1.jpg', 139 ),
( 'HIMA BABY CREM SOFGE 200ML', 'productPool/1.jpg', 181 ),
( 'HIMAIAYA PAIN BALM MINT 10G', 'productPool/1.jpg', 123 ),
( 'HIMALAYA ACTIVE FRESH GEL80G', 'productPool/1.jpg', 67 ),
( 'HIMALAYA ACTIVE FRESH MOUTHWASH 215ML', 'productPool/1.jpg', 275 ),
( 'HIMALAYA ACTIVE SPOT FACEWASH 100G', 'productPool/1.jpg', 149 ),
( 'HIMALAYA AGE DEFYING HAND CREAM 100ML', 'productPool/1.jpg', 162 ),
( 'HIMALAYA ALMOND and ROSE SOAP 125G', 'productPool/1.jpg', 276 ),
( 'HIMALAYA ALMOND AND ROSE SOAP 75G', 'productPool/1.jpg', 188 ),
( 'HIMALAYA ALO VERA FACIAL WIPES 2*25N COMBO', 'productPool/1.jpg', 268 ),
( 'HIMALAYA ALOE & CUCUMBER BODY LOTION 100ML', 'productPool/1.jpg', 276 ),
( 'HIMALAYA ALOE & CUCUMBER BODY LOTION 200ML', 'productPool/1.jpg', 205 ),
( 'HIMALAYA ALOE VERA FACE WASH 100 ML', 'productPool/1.jpg', 111 ),
( 'HIMALAYA ALOE VERA FACE WASH 100ML+TOOTH PAST', 'productPool/1.jpg', 273 ),
( 'HIMALAYA ALOE VERA FACE WASH 50 ML', 'productPool/1.jpg', 220 ),
( 'HIMALAYA ALOE VERA FACIAL WIPES 10N', 'productPool/1.jpg', 27 ),
( 'HIMALAYA ALOE VERA FACIAL WIPES 25N', 'productPool/1.jpg', 140 ),
( 'HIMALAYA ANTI DANDRUFF CONDI 100ML', 'productPool/1.jpg', 13 ),
( 'HIMALAYA ANTI DANDRUFF CREAM 100ML', 'productPool/1.jpg', 112 ),
( 'HIMALAYA ANTI DANDRUFF SHAMPOO 100ML', 'productPool/1.jpg', 214 ),
( 'HIMALAYA ANTI DANDRUFF SHAMPOO 200ML', 'productPool/1.jpg', 71 ),
( 'HIMALAYA ANTI DANDRUFF SHAMPOO 400ML', 'productPool/1.jpg', 202 ),
( 'HIMALAYA ANTI DANDRUFF SHAMPOO 700ML', 'productPool/1.jpg', 46 ),
( 'HIMALAYA ANTI DANDRUFF SHAMPOO 80ML', 'productPool/1.jpg', 222 ),
( 'HIMALAYA ANTI HAIR FALL CREAM 100ML', 'productPool/1.jpg', 174 ),
( 'HIMALAYA ANTI HAIR FALL HAIR OIL 100ML', 'productPool/1.jpg', 152 ),
( 'HIMALAYA ANTI HAIR FALL SHAMPOO 100 ML', 'productPool/1.jpg', 229 ),
( 'HIMALAYA ANTI HAIR FALL SHAMPOO 200ML', 'productPool/1.jpg', 177 ),
( 'HIMALAYA ANTI HAIR FALL SHAMPOO 700ML', 'productPool/1.jpg', 79 ),
( 'HIMALAYA ANTI HAIR FALL SHAMPOO 80ML', 'productPool/1.jpg', 19 ),
( 'HIMALAYA ANTI HAIRFALL CONDITIONER 100ML', 'productPool/1.jpg', 155 ),
( 'HIMALAYA ANTI RASH CREAM20G', 'productPool/1.jpg', 138 ),
( 'HIMALAYA APRICOT FACE WASH 100ML', 'productPool/1.jpg', 6 ),
( 'HIMALAYA APRICOT FACE WASH 50ML', 'productPool/1.jpg', 232 ),
( 'HIMALAYA APRICOT SCRUB 50GM', 'productPool/1.jpg', 250 ),
( 'HIMALAYA AYURVEDA CLEAR SKIN SOAP 125G', 'productPool/1.jpg', 212 ),
( 'HIMALAYA AYURVEDA CLEAR SKIN SOAP 75G', 'productPool/1.jpg', 88 ),
( 'HIMALAYA BABY CREAM 100ML', 'productPool/1.jpg', 278 ),
( 'HIMALAYA BABY CREAM EXTRA CREAM and GENTLE 50ML', 'productPool/1.jpg', 136 ),
( 'HIMALAYA BABY DIAPERS LARGE 9', 'productPool/1.jpg', 34 ),
( 'HIMALAYA BABY DIAPERS SMALL 9', 'productPool/1.jpg', 52 ),
( 'HIMALAYA BABY GIFT 275 G', 'productPool/1.jpg', 73 ),
( 'HIMALAYA BABY GIFT PACK', 'productPool/1.jpg', 26 ),
( 'HIMALAYA BABY GIFT PACK 20CM*21CM', 'productPool/1.jpg', 20 ),
( 'HIMALAYA BABY LOTION 200ML', 'productPool/1.jpg', 147 ),
( 'HIMALAYA BABY LOTION 400ML', 'productPool/1.jpg', 248 ),
( 'HIMALAYA BABY LOTION 40ML', 'productPool/1.jpg', 107 ),
( 'HIMALAYA BABY LOTION ALMOND LOTION 100ML', 'productPool/1.jpg', 163 ),
( 'HIMALAYA BABY MASSAGE OIL', 'productPool/1.jpg', 1 ),
( 'HIMALAYA BABY MASSAGE OIL 100ML', 'productPool/1.jpg', 55 ),
( 'HIMALAYA BABY MASSAGE OIL 200ML', 'productPool/1.jpg', 4 ),
( 'HIMALAYA BABY PANTS LARGE 28', 'productPool/1.jpg', 157 ),
( 'HIMALAYA BABY PANTS LARGE 54', 'productPool/1.jpg', 92 ),
( 'HIMALAYA BABY PANTS MEDIUM 28', 'productPool/1.jpg', 35 ),
( 'HIMALAYA BABY PANTS MEDIUM 54', 'productPool/1.jpg', 233 ),
( 'HIMALAYA BABY PANTS SMALL 28', 'productPool/1.jpg', 98 ),
( 'HIMALAYA BABY PANTS XL28', 'productPool/1.jpg', 34 ),
( 'HIMALAYA BABY POWDER 100GMS', 'productPool/1.jpg', 150 ),
( 'HIMALAYA BABY POWDER 200GMS', 'productPool/1.jpg', 1 ),
( 'HIMALAYA BABY POWDER 400GMS', 'productPool/1.jpg', 13 ),
( 'HIMALAYA BABY POWDER 50GM', 'productPool/1.jpg', 273 ),
( 'HIMALAYA BABY SHAMPOO 200ML', 'productPool/1.jpg', 78 ),
( 'HIMALAYA BABY WIPE 24', 'productPool/1.jpg', 256 ),
( 'HIMALAYA BABY WIPES 12N', 'productPool/1.jpg', 32 ),
( 'HIMALAYA BABY WIPES 24s', 'productPool/1.jpg', 14 ),
( 'HIMALAYA BABYCARE BABY GIFT PACK', 'productPool/1.jpg', 138 ),
( 'HIMALAYA BABYGIFTPACK MRP 116', 'productPool/1.jpg', 176 ),
( 'HIMALAYA BODY BUTTER ROSE100ML', 'productPool/1.jpg', 61 ),
( 'HIMALAYA CALAMINE BABY LOTION 200ML', 'productPool/1.jpg', 110 ),
( 'HIMALAYA CALAMINE BABY LOTION 50ML', 'productPool/1.jpg', 94 ),
( 'HIMALAYA CALMINE BABY LOTION 100ML', 'productPool/1.jpg', 256 ),
( 'HIMALAYA CLEAR WHITENING FACEWASH 50G', 'productPool/1.jpg', 255 ),
( 'HIMALAYA COCOA BUTTER INTENSIVE BODY LOTION 100ML', 'productPool/1.jpg', 195 ),
( 'HIMALAYA COCOA BUTTER LIP BLAM', 'productPool/1.jpg', 23 ),
( 'HIMALAYA COCOA BUTTER LIP BLAM 10G', 'productPool/1.jpg', 234 ),
( 'HIMALAYA COID BALM 10G', 'productPool/1.jpg', 139 ),
( 'HIMALAYA COMPLETE CARE 40G', 'productPool/1.jpg', 161 ),
( 'HIMALAYA COMPLETE CARE MOUTH WASH 215ML', 'productPool/1.jpg', 275 ),
( 'HIMALAYA COMPLETE CARE TOOTH PASTE 80G', 'productPool/1.jpg', 225 ),
( 'HIMALAYA COMPLETE CARE TOOTH PASTE150G', 'productPool/1.jpg', 167 ),
( 'HIMALAYA CUCUMBER AND COCONUT SOAP 75G', 'productPool/1.jpg', 9 ),
( 'HIMALAYA CUCUMBER PEEL OFF MASK 100G', 'productPool/1.jpg', 218 ),
( 'HIMALAYA CUCUMBER PEEL OFF MASK 50G', 'productPool/1.jpg', 162 ),
( 'HIMALAYA DAILY CARE PROTEIN CONDITIONER 200ML', 'productPool/1.jpg', 89 ),
( 'HIMALAYA DAIPER RASH CREAM 20G', 'productPool/1.jpg', 161 ),
( 'HIMALAYA DAMAGE REPAIR CONDITIONER 100ML', 'productPool/1.jpg', 54 ),
( 'HIMALAYA DAMAGE REPAIR CONDITIONER 200ML', 'productPool/1.jpg', 31 ),
( 'HIMALAYA DAMAGE REPAIR PROTEIN SHAMPOO 400ML', 'productPool/1.jpg', 141 ),
( 'HIMALAYA DAMAGE REPAIR SHAMPOO 200ML', 'productPool/1.jpg', 178 ),
( 'HIMALAYA DAMAGE REPAIR SHAMPOO 80ML', 'productPool/1.jpg', 92 ),
( 'HIMALAYA DAMAGE REPAR SHAMPOO 100 ML', 'productPool/1.jpg', 158 ),
( 'HIMALAYA DENTAL CREAM 200G', 'productPool/1.jpg', 119 ),
( 'HIMALAYA DIAPER RASH CREAM 50G', 'productPool/1.jpg', 40 ),
( 'HIMALAYA DRY DEFENSE CONDITIONER 200ML', 'productPool/1.jpg', 219 ),
( 'HIMALAYA DRY DEFENSE SHAMPOO 200ML', 'productPool/1.jpg', 189 ),
( 'HIMALAYA DRYNESS DEFENSE CONDITIONER 100ML', 'productPool/1.jpg', 30 ),
( 'HIMALAYA DRYNESS DEFENSE PROTEIN SHAMPOO 400ML', 'productPool/1.jpg', 34 ),
( 'HIMALAYA DRYNESS DEFENSE SHAMPOO 100ML', 'productPool/1.jpg', 136 ),
( 'HIMALAYA DRYNESS DEFENSE SHAMPOO 80ML', 'productPool/1.jpg', 116 ),
( 'HIMALAYA ERINA EP DOG SHAMPOO 200ML', 'productPool/1.jpg', 84 ),
( 'HIMALAYA EYE CREAM 15ML', 'productPool/1.jpg', 186 ),
( 'HIMALAYA FAIRNESS CREAM 10G', 'productPool/1.jpg', 26 ),
( 'HIMALAYA FAIRNESS KESAR FACE PACK 50G', 'productPool/1.jpg', 220 ),
( 'HIMALAYA FAIRNESS KESAR FACE WASH 50 ML', 'productPool/1.jpg', 137 ),
( 'HIMALAYA FOAMING OIL CLEAR LEMON FACEWASH 150ML', 'productPool/1.jpg', 254 ),
( 'HIMALAYA FOOT CARE CREAM 20G', 'productPool/1.jpg', 88 ),
( 'HIMALAYA FRESH START BLUEBERRY FACE WASH 100ML', 'productPool/1.jpg', 227 ),
( 'HIMALAYA FRESH START BLUEBERRY FACEWASH 50ML', 'productPool/1.jpg', 178 ),
( 'HIMALAYA FRESH START LEMON FACE WASH 100ML', 'productPool/1.jpg', 48 ),
( 'HIMALAYA FRESH START LEMON FACE WASH 50ML', 'productPool/1.jpg', 245 ),
( 'HIMALAYA FRESH START PEACH FACE WASH 100ML', 'productPool/1.jpg', 142 ),
( 'HIMALAYA FRESH START PEACH FACEWASH 50ML', 'productPool/1.jpg', 26 ),
( 'HIMALAYA FRESH START STRAWERRY FACE WASH 100ML', 'productPool/1.jpg', 185 ),
( 'HIMALAYA FRESH START STRAWERRY FACE WASH 50ML', 'productPool/1.jpg', 241 ),
( 'HIMALAYA FRUIT PACK 50G', 'productPool/1.jpg', 251 ),
( 'HIMALAYA GENTLE BABY BATH 100ML', 'productPool/1.jpg', 31 ),
( 'HIMALAYA GENTLE BABY BATH 200ML', 'productPool/1.jpg', 135 ),
( 'HIMALAYA GENTLE BABY LAUNDRY WASH 1L', 'productPool/1.jpg', 161 ),
( 'HIMALAYA GENTLE BABY LAUNDRY WASH 500ML', 'productPool/1.jpg', 57 ),
( 'HIMALAYA GENTLE BABY SHAMPOO 100ML', 'productPool/1.jpg', 65 ),
( 'HIMALAYA GENTLE BABY SHAMPOO 200ML', 'productPool/1.jpg', 107 ),
( 'HIMALAYA GENTLE BABY SOAP 100G', 'productPool/1.jpg', 60 ),
( 'HIMALAYA GENTLE BABY SOAP 125G', 'productPool/1.jpg', 264 ),
( 'HIMALAYA GENTLE BABY SOAP 3+1 300G', 'productPool/1.jpg', 160 ),
( 'HIMALAYA GENTLE BABY SOAP 300G', 'productPool/1.jpg', 115 ),
( 'HIMALAYA GENTLE BABY SOAP 75G', 'productPool/1.jpg', 238 ),
( 'HIMALAYA GENTLE DAILY CARE 100 ML', 'productPool/1.jpg', 137 ),
( 'HIMALAYA GENTLE DAILY CARE PROTEIN CONDITIONR 100 ML', 'productPool/1.jpg', 157 ),
( 'HIMALAYA GENTLE DAILY CARE PROTEIN SHAMPOO200ML', 'productPool/1.jpg', 227 ),
( 'HIMALAYA GENTLE DAILY CARE SHAMPOO 80ML', 'productPool/1.jpg', 101 ),
( 'HIMALAYA GENTLE EXFOLIATING APRICOT SCRUB 100GMS', 'productPool/1.jpg', 102 ),
( 'HIMALAYA GENTLE REFRESHING CLARF TONER 100ML', 'productPool/1.jpg', 28 ),
( 'HIMALAYA HAPPY BABY GIFT PACK', 'productPool/1.jpg', 108 ),
( 'HIMALAYA HAPPY BABY GIFT PACK MRP 201', 'productPool/1.jpg', 216 ),
( 'HIMALAYA HAPPY BABY GIFT PACK SINCE 1930', 'productPool/1.jpg', 158 ),
( 'HIMALAYA HEAT BABY POWDER 100G', 'productPool/1.jpg', 33 ),
( 'HIMALAYA HERBALS ORANGE PEEL 50G', 'productPool/1.jpg', 195 ),
( 'HIMALAYA HONEY CREAM SOAP 125G', 'productPool/1.jpg', 33 ),
( 'HIMALAYA HONEY CREAM SOAP 75G', 'productPool/1.jpg', 130 ),
( 'HIMALAYA INTENCE LEMON FACE WASH 100ML', 'productPool/1.jpg', 253 ),
( 'HIMALAYA INTIMATE WASH FOR MOMS 100ML', 'productPool/1.jpg', 36 ),
( 'HIMALAYA INTIMATE WASH FOR MOMS 200ML', 'productPool/1.jpg', 149 ),
( 'HIMALAYA INTIMATE WIPES FOR MOMS 10N', 'productPool/1.jpg', 7 ),
( 'HIMALAYA INTIMATE WIPES FOR MOMS 24N', 'productPool/1.jpg', 202 ),
( 'HIMALAYA INTSEV MOISTRUTION LOTION 100ML', 'productPool/1.jpg', 46 ),
( 'HIMALAYA JASMINE BODY BUTTER 50ML', 'productPool/1.jpg', 33 ),
( 'HIMALAYA KAJAL 2 7GM', 'productPool/1.jpg', 150 ),
( 'HIMALAYA KAJAL 2G', 'productPool/1.jpg', 252 ),
( 'HIMALAYA KESAR FACE WASH 100 ML', 'productPool/1.jpg', 83 ),
( 'HIMALAYA KESAR PACK 100G', 'productPool/1.jpg', 223 ),
( 'HIMALAYA LIP BALM 10G', 'productPool/1.jpg', 12 ),
( 'HIMALAYA LITCHI SHINE LIP CARE 4.5G', 'productPool/1.jpg', 235 ),
( 'HIMALAYA MEN A D STYLING GEL 100ML', 'productPool/1.jpg', 179 ),
( 'HIMALAYA MEN ACTIVE SPORT FACE WASH 50ML', 'productPool/1.jpg', 152 ),
( 'HIMALAYA MEN ANTI DANDRUFF GEL NORMAL 50ML', 'productPool/1.jpg', 41 ),
( 'HIMALAYA MEN ANTI DANDRUFF GEL STRONG 100ML', 'productPool/1.jpg', 247 ),
( 'HIMALAYA MEN ANTI DANDRUFF GEL STRONG 50ML', 'productPool/1.jpg', 186 ),
( 'HIMALAYA MEN ANTI DANDRUFF HAIR CREAM 100G', 'productPool/1.jpg', 160 ),
( 'HIMALAYA MEN ANTI HAIR FALL GEL STRONG 100ML', 'productPool/1.jpg', 110 ),
( 'HIMALAYA MEN ANTI HAIR FALL HAIR CREAM 100G', 'productPool/1.jpg', 10 ),
( 'HIMALAYA MEN ANTI HAIRFALL GEL NORMAL 50ML', 'productPool/1.jpg', 4 ),
( 'HIMALAYA MEN ANTI HAIRFALL GEL STRONG 50ML', 'productPool/1.jpg', 217 ),
( 'HIMALAYA MEN DAILY NOURISH GEL NORMAL 50ML', 'productPool/1.jpg', 75 ),
( 'HIMALAYA MEN DAILY NOURISH GEL STRONG 100ML', 'productPool/1.jpg', 51 ),
( 'HIMALAYA MEN DAILY NOURISH GEL STRONG 50ML', 'productPool/1.jpg', 270 ),
( 'HIMALAYA MEN DAILY NOURISH HAIR CREAM 100G', 'productPool/1.jpg', 270 ),
( 'HIMALAYA MEN FACE AND BEARD WASH 40ML', 'productPool/1.jpg', 157 ),
( 'HIMALAYA MEN FACE AND BEARD WASH 80ML', 'productPool/1.jpg', 234 ),
( 'HIMALAYA MEN NATURAL BRIGHT CREAM 25G', 'productPool/1.jpg', 27 ),
( 'HIMALAYA MEN NOURISH STYLING GEL 100ML', 'productPool/1.jpg', 39 ),
( 'HIMALAYA MEN PIMPLE CLEAR FACEWASH 100ML', 'productPool/1.jpg', 223 ),
( 'HIMALAYA MEN TNTENSE LEMON FACE WASH 50 ML', 'productPool/1.jpg', 66 ),
( 'HIMALAYA MINI BILSTER KAJAL 1 GM', 'productPool/1.jpg', 150 ),
( 'HIMALAYA MOISTURISING BABY SOAP 75G', 'productPool/1.jpg', 52 ),
( 'HIMALAYA MOISTURIZING BABY SOAP 100G', 'productPool/1.jpg', 127 ),
( 'HIMALAYA MOISTURIZING BABY SOAP 125G', 'productPool/1.jpg', 257 ),
( 'HIMALAYA MOISTURIZING BABY SOAP 300G', 'productPool/1.jpg', 182 ),
( 'HIMALAYA MOISTURIZING BABY WASH 100ML', 'productPool/1.jpg', 160 ),
( 'HIMALAYA MOISTURIZING BABY WASH 200ML', 'productPool/1.jpg', 175 ),
( 'HIMALAYA MOSTURE RICH JASMINE SOAP 75G', 'productPool/1.jpg', 234 ),
( 'HIMALAYA MOSTURE RICH ROSE SOAP 75G', 'productPool/1.jpg', 185 ),
( 'HIMALAYA NATURAL GLOW FAIRNESS CREAM 50GMS', 'productPool/1.jpg', 226 ),
( 'HIMALAYA NATURAL GLOW FAIRNESS CREAM25 GMS', 'productPool/1.jpg', 46 ),
( 'HIMALAYA NATURAL GLOW KESAR FACE CREAM 7G', 'productPool/1.jpg', 242 ),
( 'HIMALAYA NEEM FACE WASH 100ML', 'productPool/1.jpg', 202 ),
( 'HIMALAYA NEEM FACE WASH 200ML', 'productPool/1.jpg', 118 ),
( 'HIMALAYA NEEM FACE WASH 50ML', 'productPool/1.jpg', 34 ),
( 'HIMALAYA NEEM FACE WASH300ML', 'productPool/1.jpg', 32 ),
( 'HIMALAYA NEEM FOAMING FACE WASH 150ML', 'productPool/1.jpg', 259 ),
( 'HIMALAYA NEEM FOAMING FACE WASH 50ML', 'productPool/1.jpg', 88 ),
( 'HIMALAYA NEEM PEEL OF MASK 100G', 'productPool/1.jpg', 18 ),
( 'HIMALAYA NEEM PEEL OF MASK 50G', 'productPool/1.jpg', 69 ),
( 'HIMALAYA NEEM SCRUB 150G', 'productPool/1.jpg', 46 ),
( 'HIMALAYA NEEM TURMERIC 75G', 'productPool/1.jpg', 205 ),
( 'HIMALAYA NEEM&TURMERIC SOAP 150GM', 'productPool/1.jpg', 247 ),
( 'HIMALAYA NIPPLE CARE BUTTER20G', 'productPool/1.jpg', 217 ),
( 'HIMALAYA NOURIS SKIN CREAM 50ML', 'productPool/1.jpg', 138 ),
( 'HIMALAYA NOURISHING BABY SOAP 100G', 'productPool/1.jpg', 75 ),
( 'HIMALAYA NOURISHING BABY SOAP 125G', 'productPool/1.jpg', 237 ),
( 'HIMALAYA NOURISHING BABY SOAP 75G', 'productPool/1.jpg', 111 ),
( 'HIMALAYA NOURISHING F MOISTURISING LOTION 100ML', 'productPool/1.jpg', 85 ),
( 'HIMALAYA NOURISHING LOTION 100 ML', 'productPool/1.jpg', 210 ),
( 'HIMALAYA NOURISHING SKIN CREAM 100ML', 'productPool/1.jpg', 263 ),
( 'HIMALAYA NOURISHING SKIN CREAM 200ML', 'productPool/1.jpg', 201 ),
( 'HIMALAYA OIL CLEAR LEMON FACE WASH 100ML', 'productPool/1.jpg', 183 ),
( 'HIMALAYA OIL CLEAR LEMON FACE WASH 200ML', 'productPool/1.jpg', 82 ),
( 'HIMALAYA OIL CLEAR LEMON FACE WASH 50 ML', 'productPool/1.jpg', 1 ),
( 'HIMALAYA OIL CLEAR LEMON FACEWASH 150ML', 'productPool/1.jpg', 55 ),
( 'HIMALAYA OIL CLEAR MUD FACE PACK 50G', 'productPool/1.jpg', 230 ),
( 'HIMALAYA OIL FREE GELCREAM 50G', 'productPool/1.jpg', 6 ),
( 'HIMALAYA ORANGE FACE WASH 100ML', 'productPool/1.jpg', 63 ),
( 'HIMALAYA ORANGE FACEWASH 50G', 'productPool/1.jpg', 200 ),
( 'HIMALAYA ORANGE SCRUB 100G', 'productPool/1.jpg', 148 ),
( 'HIMALAYA PAIN RELIEF OIL 100ML', 'productPool/1.jpg', 70 ),
( 'HIMALAYA PEACH LIP BALM 4.5G', 'productPool/1.jpg', 89 ),
( 'HIMALAYA PIMPLE CLEAR FACE WASH50ML', 'productPool/1.jpg', 279 ),
( 'HIMALAYA POWER GLOW FACE WASH100ML', 'productPool/1.jpg', 67 ),
( 'HIMALAYA POWER GLOW LICORIE FACE WASH 50ML', 'productPool/1.jpg', 274 ),
( 'HIMALAYA PRICKLY HEAT BABY POWDER 200G', 'productPool/1.jpg', 124 ),
( 'HIMALAYA PRO SUN SCREEN LOTION 50ML', 'productPool/1.jpg', 44 ),
( 'HIMALAYA PROTEIN HAIR CREAM 100G COMBO', 'productPool/1.jpg', 116 ),
( 'HIMALAYA PROTEIN HAIR CREAM100ML', 'productPool/1.jpg', 245 ),
( 'HIMALAYA PROTIEN SUN LOTION 100ML', 'productPool/1.jpg', 137 ),
( 'HIMALAYA PURE EXPRESSION KAJAL 0.30G', 'productPool/1.jpg', 96 ),
( 'HIMALAYA PURE HANDWASH TULSI 250ML', 'productPool/1.jpg', 110 ),
( 'HIMALAYA PURE HANDWASH TULSI ALOE 185ML', 'productPool/1.jpg', 74 ),
( 'HIMALAYA PURE HANDWASH TULSI LEMON 185ML', 'productPool/1.jpg', 114 ),
( 'HIMALAYA PURE HANDWASH TULSI&ALOE 250ML', 'productPool/1.jpg', 33 ),
( 'HIMALAYA PURE HANDWASH TULSI&LEMON 250ML', 'productPool/1.jpg', 52 ),
( 'HIMALAYA PURIF. NEEM FACE WASH 150ML', 'productPool/1.jpg', 177 ),
( 'HIMALAYA PURIFYING NEEM FACE WASH 400ML', 'productPool/1.jpg', 70 ),
( 'HIMALAYA PURIFYING NEEM FACEWASH 15ML', 'productPool/1.jpg', 73 ),
( 'HIMALAYA PURIFYING NEEM FACIAL WIPES 10N', 'productPool/1.jpg', 93 ),
( 'HIMALAYA PURIFYING NEEM FACIAL WIPES 25N', 'productPool/1.jpg', 171 ),
( 'HIMALAYA PURIFYING NEEM PACK 50 G', 'productPool/1.jpg', 146 ),
( 'HIMALAYA PURIFYING NEEM SCRUB 100G', 'productPool/1.jpg', 134 ),
( 'HIMALAYA PURIIFYING NEEM SCRUB 50 G', 'productPool/1.jpg', 180 ),
( 'HIMALAYA REFRESHING BABY SOAP 100G', 'productPool/1.jpg', 5 ),
( 'HIMALAYA REFRESHING BABY SOAP 125G', 'productPool/1.jpg', 1 ),
( 'HIMALAYA REFRESHING BABY SOAP 300G', 'productPool/1.jpg', 41 ),
( 'HIMALAYA REFRESHING BABY SOAP 75G', 'productPool/1.jpg', 84 ),
( 'HIMALAYA REFRESHING BABY WASH 100G', 'productPool/1.jpg', 198 ),
( 'HIMALAYA REFRESHING BABY WASH 200G', 'productPool/1.jpg', 79 ),
( 'HIMALAYA REFRESHING CLEANSING MILK 100ML', 'productPool/1.jpg', 182 ),
( 'HIMALAYA REFRESHING FRUIT PACK 100G', 'productPool/1.jpg', 59 ),
( 'HIMALAYA REVITALIZING NIGHT CREAM 50G', 'productPool/1.jpg', 250 ),
( 'HIMALAYA RICH COCOA BUTTER BODY CREAM 200ML', 'productPool/1.jpg', 3 ),
( 'HIMALAYA SANITIZER APPLE 50ML', 'productPool/1.jpg', 189 ),
( 'HIMALAYA SANITIZER LEMON 50ML', 'productPool/1.jpg', 225 ),
( 'HIMALAYA SANITIZER LICHI 50ML', 'productPool/1.jpg', 203 ),
( 'HIMALAYA SANITIZER ORANGE 50ML', 'productPool/1.jpg', 91 ),
( 'HIMALAYA SANITIZER STRAWBERRY 50ML', 'productPool/1.jpg', 9 ),
( 'HIMALAYA SENSITIVE TOOTH PASTE80G', 'productPool/1.jpg', 254 ),
( 'HIMALAYA SHUBHMUHURAT GIFTPACK', 'productPool/1.jpg', 256 ),
( 'HIMALAYA SMOOTHING BABY WIPES', 'productPool/1.jpg', 82 ),
( 'HIMALAYA SMOOTHING LOTION 100ML', 'productPool/1.jpg', 32 ),
( 'HIMALAYA SOOTHING BABY WIPES 12N', 'productPool/1.jpg', 27 ),
( 'HIMALAYA SOOTHING BODY BUTTER LAVENDER 100ML', 'productPool/1.jpg', 138 ),
( 'HIMALAYA SOOTHING BODY BUTTER LAVENDER 50 ML', 'productPool/1.jpg', 165 ),
( 'HIMALAYA SOOTHING BODY BUTTER ROSE 50ML', 'productPool/1.jpg', 190 ),
( 'HIMALAYA SOOTHING BODY BUTTER ROSE200ML', 'productPool/1.jpg', 37 ),
( 'HIMALAYA SOOTHING BODY BUTTER200ML', 'productPool/1.jpg', 191 ),
( 'HIMALAYA SOOTHING BODY BUTTERJASMINE200ML', 'productPool/1.jpg', 235 ),
( 'HIMALAYA SPARKING WHITE 40G', 'productPool/1.jpg', 260 ),
( 'HIMALAYA SPARKING WHITE TOOTH PASTE 80G', 'productPool/1.jpg', 64 ),
( 'HIMALAYA SPARKLING WHITE FRESH GEL 80G', 'productPool/1.jpg', 45 ),
( 'HIMALAYA SPARKLING WHITE PASTE 150G', 'productPool/1.jpg', 126 ),
( 'HIMALAYA STAIN REMOVAL PASTE 80G', 'productPool/1.jpg', 64 ),
( 'HIMALAYA STRAWBERY LIP BALM 4.5 G', 'productPool/1.jpg', 200 ),
( 'HIMALAYA STRAWERRY LIP BALM 10G', 'productPool/1.jpg', 247 ),
( 'HIMALAYA STRETCH MARK CARE COMBO 200ML', 'productPool/1.jpg', 205 ),
( 'HIMALAYA STRETCH MARK CREAM 50ML', 'productPool/1.jpg', 264 ),
( 'HIMALAYA STRETCH MARK OIL 100ML', 'productPool/1.jpg', 32 ),
( 'HIMALAYA SUN PROTECT ORANGE LIP BALM 4.5G', 'productPool/1.jpg', 250 ),
( 'HIMALAYA TAN REMOVAL ORANGE FACE SCRUB 50G', 'productPool/1.jpg', 248 ),
( 'HIMALAYA TAN REMOVAL ORANGE PEEL OFF MASK100G', 'productPool/1.jpg', 57 ),
( 'HIMALAYA TAN REMOVAL ORANGE SCRUB 100G', 'productPool/1.jpg', 234 ),
( 'HIMALAYA TONING MASSAGE OIL 200ML', 'productPool/1.jpg', 213 ),
( 'HIMALAYA TOTAL CARE BABY PANTS M9', 'productPool/1.jpg', 40 ),
( 'HIMALAYA TOTAL CARE BABY PANTS XL9', 'productPool/1.jpg', 68 ),
( 'HIMALAYA VANILA LIPCARE 4.5G', 'productPool/1.jpg', 143 ),
( 'HIMALAYA WALNUT SCRUB 100G', 'productPool/1.jpg', 154 ),
( 'HIMALAYA WALNUT SCRUB 50G', 'productPool/1.jpg', 41 ),
( 'HIMALAYA WHITENING DAY CREAM 50G', 'productPool/1.jpg', 74 ),
( 'HIMALAYA WHITENING FACE WASH 100 ML', 'productPool/1.jpg', 52 ),
( 'HIMALAYA WHITENING SCRUB 50 ML', 'productPool/1.jpg', 193 ),
( 'HIMALAYA WINTER DEFENSE MOIST CREAM 100ML', 'productPool/1.jpg', 142 ),
( 'HIMALAYA WINTER DEFENSE MOIST CREAM 50ML', 'productPool/1.jpg', 2 ),
( 'HIMALAYA YOUTH ETERNITY DAY CREAM 10ML', 'productPool/1.jpg', 145 ),
( 'HIMALAYA YOUTH ETERNITY DAY CREAM 50ML', 'productPool/1.jpg', 239 ),
( 'HIMALAYA YOUTH ETERNITY NIGHT CREAM 50ML', 'productPool/1.jpg', 128 ),
( 'HIMALAYAANTIDANDRUFFHAIROIL100ML', 'productPool/1.jpg', 182 ),
( 'HIMALAYAANTIWRINKLECREAM50G', 'productPool/1.jpg', 251 ),
( 'HIMALAYACOCOABUTTERINTENSIVEBODYLOTION200ML', 'productPool/1.jpg', 73 ),
( 'HIMALAYACUCUMBER and COCONUTSOAP125G', 'productPool/1.jpg', 154 ),
( 'HIMALAYAGENTBABYWIPES LOTUS 72NOS', 'productPool/1.jpg', 154 ),
( 'HIMALAYAN MINERAL WATER 750ML', 'productPool/1.jpg', 231 ),
( 'HIMALAYAOILCLEARMUDFACEPACK100G', 'productPool/1.jpg', 65 ),
( 'HIMALAYAPURIFYINGNEEMPACK100G', 'productPool/1.jpg', 220 ),
( 'HIMALAYASOOTHING BODY BUTTER JASMINE 100ML', 'productPool/1.jpg', 165 ),
( 'HIMALAYASOOTHINGBODYLOTION200ML', 'productPool/1.jpg', 38 ),
( 'HIMALYA ANTI HAIR FALL SHAMPOO 400ML', 'productPool/1.jpg', 78 ),
( 'HIMALYA GENTLE DAILY CARE SHAMPOO 400ML', 'productPool/1.jpg', 47 ),
( 'HIMALYA NOURISHING BODY LOTION 200ML', 'productPool/1.jpg', 243 ),
( 'HIMALYA WHITENING FACE SCRUB 100G', 'productPool/1.jpg', 107 ),
( 'HIMANI CHAPPATHY', 'productPool/1.jpg', 106 ),
( 'HIT ANTIROACH GEL COCROCH', 'productPool/1.jpg', 12 ),
( 'HIT CHALK KILLS 1NOS', 'productPool/1.jpg', 107 ),
( 'HIT FIK 125ML', 'productPool/1.jpg', 211 ),
( 'HIT FIK 400ML', 'productPool/1.jpg', 39 ),
( 'HIT FIK LIME 625ML', 'productPool/1.jpg', 176 ),
( 'HIT GEL STICK RS30', 'productPool/1.jpg', 66 ),
( 'HIT KILL RAT SCUBE S25G', 'productPool/1.jpg', 126 ),
( 'HM MAYIL SHEET 18*18', 'productPool/1.jpg', 146 ),
( 'HM MAYIL SHEET 18*18 SILKY', 'productPool/1.jpg', 236 ),
( 'HOM BRAND BABY MAT MB09', 'productPool/1.jpg', 204 ),
( 'HOM BRAND BUBBA MAT MB12', 'productPool/1.jpg', 136 ),
( 'HOME BRAND BABY BED SHEET PERFUMED MB13', 'productPool/1.jpg', 109 ),
( 'HOME BRAND BUBBA BABY MAT MB11', 'productPool/1.jpg', 2 ),
( 'HOME BRAND DISNEY BABY SHEET MB16', 'productPool/1.jpg', 29 ),
( 'HOME BRAND FRIDGE HANDLE COVER HBC986', 'productPool/1.jpg', 172 ),
( 'HOME BRAND FRIDGE TOP COVER HBC984', 'productPool/1.jpg', 84 ),
( 'HOME BRAND PURE RUBBER SHEET MB15', 'productPool/1.jpg', 141 ),
( 'HOME BRAND PVC BED SHEET HBC980', 'productPool/1.jpg', 120 ),
( 'HOME BRAND TABLE COVER HBT 107', 'productPool/1.jpg', 66 ),
( 'HOME BRAND TABLE COVER HBT 213', 'productPool/1.jpg', 184 ),
( 'HOME BRAND TABLE COVER HBT 614', 'productPool/1.jpg', 17 ),
( 'HOME BRAND TABLE COVER HBT 706', 'productPool/1.jpg', 73 ),
( 'HOMEBRAND APRON HBC982', 'productPool/1.jpg', 68 ),
( 'HOMEBRAND ROYAL APRON HBC983', 'productPool/1.jpg', 144 ),
( 'HOMEBRAND TABLE COVER HBT114', 'productPool/1.jpg', 167 ),
( 'HOMEBRAND TABLE MAT HBT102', 'productPool/1.jpg', 8 ),
( 'HOMEBRAND TABLE MAT HBT106', 'productPool/1.jpg', 63 ),
( 'HOMEBRAND TABLE MAT HBT113', 'productPool/1.jpg', 246 ),
( 'HOMEBRAND TABLE MAT HBT202', 'productPool/1.jpg', 238 ),
( 'HOMEBRAND TABLE MAT HBT206', 'productPool/1.jpg', 228 ),
( 'HOMEBRAND TABLE MAT HBT302', 'productPool/1.jpg', 226 ),
( 'HOMEBRAND TABLE MAT HBT306', 'productPool/1.jpg', 90 ),
( 'HOMEBRAND TABLE MAT HBT313', 'productPool/1.jpg', 132 ),
( 'HOMEBRAND TABLE MAT HBT602', 'productPool/1.jpg', 27 ),
( 'HOMEBRAND TABLE MAT HBT602803', 'productPool/1.jpg', 247 ),
( 'HOMEBRAND TABLE MAT HBT606', 'productPool/1.jpg', 229 ),
( 'HOMEBRAND TABLE MAT HBT613', 'productPool/1.jpg', 231 ),
( 'HOMEBRAND TABLE MAT HBT801', 'productPool/1.jpg', 66 ),
( 'HOMEBRAND TABLE MAT HBT802', 'productPool/1.jpg', 199 ),
( 'HOMEBRAND TABLE MAT HBT804', 'productPool/1.jpg', 44 ),
( 'HOMEBRAND TABLE MAT HBT904', 'productPool/1.jpg', 238 ),
( 'HOMEBRAND TABLE MAT HBT906', 'productPool/1.jpg', 44 ),
( 'HOMEBRAND TABLE MAT HBT910', 'productPool/1.jpg', 248 ),
( 'HONEY BABY FEEDING BOTTLE 180ML', 'productPool/1.jpg', 199 ),
( 'HONEY BABY FEEDING BOTTLE 250ML', 'productPool/1.jpg', 276 ),
( 'HONEY BOTTLE', 'productPool/1.jpg', 111 ),
( 'HOOK 3PCS RS22.50', 'productPool/1.jpg', 200 ),
( 'HOOK IMP', 'productPool/1.jpg', 184 ),
( 'HOOK IMP 3 PCS', 'productPool/1.jpg', 167 ),
( 'HOOK IMP R15.50', 'productPool/1.jpg', 252 ),
( 'HOOK IMP R16.50', 'productPool/1.jpg', 104 ),
( 'HOOK IMP R24', 'productPool/1.jpg', 96 ),
( 'HOOK IMP RS 39', 'productPool/1.jpg', 145 ),
( 'HOOK IMP RS27', 'productPool/1.jpg', 117 ),
( 'HOOK IMP RS30', 'productPool/1.jpg', 154 ),
( 'HOOK IMP RS42', 'productPool/1.jpg', 179 ),
( 'HOOK IMP RS50', 'productPool/1.jpg', 129 ),
( 'HOOK IMP RS60', 'productPool/1.jpg', 153 ),
( 'HOOK RS 24', 'productPool/1.jpg', 42 ),
( 'HOOK RS 36', 'productPool/1.jpg', 98 ),
( 'HOOK RS 85', 'productPool/1.jpg', 189 ),
( 'HOOK RS48', 'productPool/1.jpg', 34 ),
( 'HORLICKS 200G JAR', 'productPool/1.jpg', 90 ),
( 'HORLICKS BISCUIT 150 G', 'productPool/1.jpg', 155 ),
( 'HORLICKS BISCUITS 300 G', 'productPool/1.jpg', 266 ),
( 'HORLICKS BISCUITS 600 G', 'productPool/1.jpg', 186 ),
( 'HORLICKS BISCUITS 85G', 'productPool/1.jpg', 49 ),
( 'HORLICKS CHOCOLATE 500G REFILL', 'productPool/1.jpg', 90 ),
( 'HORLICKS CHOCOLATE JAR 500G', 'productPool/1.jpg', 50 ),
( 'HORLICKS CHOCOLATE200GJAR', 'productPool/1.jpg', 46 ),
( 'HORLICKS CLASSIC MALT 500G REFILL', 'productPool/1.jpg', 30 ),
( 'HORLICKS GROWTH CHOCOLATE 400G JAR', 'productPool/1.jpg', 72 ),
( 'HORLICKS GROWTH PLUS CHOCOLATE 200G', 'productPool/1.jpg', 225 ),
( 'HORLICKS GROWTH PLUS VANILA 200G', 'productPool/1.jpg', 276 ),
( 'HORLICKS GROWTH VANILLA 400G JAR', 'productPool/1.jpg', 30 ),
( 'HORLICKS JUNIOR STAGE 2 500G JAR', 'productPool/1.jpg', 189 ),
( 'HORLICKS JUNIOR STAGE 2 REFILL GP 500GM', 'productPool/1.jpg', 195 ),
( 'HORLICKS JUNIOR STAGE1 500G JAR', 'productPool/1.jpg', 277 ),
( 'HORLICKS JUNIOR STAGE1 CHOCOLATE 500G JAR', 'productPool/1.jpg', 221 ),
( 'HORLICKS JUNIOR STAGE1 REFILL 500G', 'productPool/1.jpg', 112 ),
( 'HORLICKS KESAR BADAM 400G JAR', 'productPool/1.jpg', 97 ),
( 'HORLICKS LITE BADAM 450G REFILL', 'productPool/1.jpg', 186 ),
( 'HORLICKS LITE REGULAR MALT 450G JAR', 'productPool/1.jpg', 39 ),
( 'HORLICKS MOTHERS 200G REFILL', 'productPool/1.jpg', 102 ),
( 'HORLICKS MOTHERS 450G REFILL', 'productPool/1.jpg', 115 ),
( 'HORLICKS OATS 1.4KG', 'productPool/1.jpg', 111 ),
( 'HORLICKS OATS 500G', 'productPool/1.jpg', 140 ),
( 'HORLICKS OATS1KG PKTS', 'productPool/1.jpg', 208 ),
( 'HORLICKS PROTEIN CHOCOLATE 200G REFILL', 'productPool/1.jpg', 71 ),
( 'HORLICKS PROTEIN VANILA 200G REFILL', 'productPool/1.jpg', 28 ),
( 'HORLICKS PROTEIN VANILA 400G JAR', 'productPool/1.jpg', 230 ),
( 'HORLICKS PROTEN PLUS CHOCOLATE 400G JR', 'productPool/1.jpg', 240 ),
( 'HORLICKS PROTEN PLUS VANILLA 400G', 'productPool/1.jpg', 154 ),
( 'HORLICKS STANDARD 1KG JAR', 'productPool/1.jpg', 59 ),
( 'HORLICKS STANDARD 1KG REFILL', 'productPool/1.jpg', 52 ),
( 'HORLICKS STD 500G JAR', 'productPool/1.jpg', 269 ),
( 'HORLICKS VIVA HEALTH 500G JAR', 'productPool/1.jpg', 115 ),
( 'HOTT AQUA PERFUME SPRAY 135ML', 'productPool/1.jpg', 105 ),
( 'HOTT AQUA PERFUME SPRAY 150ML', 'productPool/1.jpg', 140 ),
( 'HOTT AQUA PERFUME SPRAY 60ML', 'productPool/1.jpg', 147 ),
( 'HOTT CALYPSO DEO SPRAY 135ML', 'productPool/1.jpg', 223 ),
( 'HOTT CALYPSO PERFUME SPRAY 60ML', 'productPool/1.jpg', 70 ),
( 'HOTT DEO SPARY OFFER PACK 3PCS', 'productPool/1.jpg', 106 ),
( 'HOTT INTENSE PERFUME SPRAY 135ML', 'productPool/1.jpg', 232 ),
( 'HOTT INTENSE PERFUME SPRAY 150ML', 'productPool/1.jpg', 109 ),
( 'HOTT INTENSE PERFUME SPRAY 60ML', 'productPool/1.jpg', 217 ),
( 'HOTT MUSK PERFUME SPRAY 135ML', 'productPool/1.jpg', 98 ),
( 'HOTT MUSK PERFUME SPRAY 60ML', 'productPool/1.jpg', 126 ),
( 'HOTT NOIR DEO SPRAY 135ML', 'productPool/1.jpg', 186 ),
( 'HOTT NOIR PERFUME SPRAY 150ML', 'productPool/1.jpg', 253 ),
( 'HOTT NOIR PERFUME SPRAY 60ML', 'productPool/1.jpg', 166 ),
( 'HOTT PERFUME SPRAY MUSK 150ML', 'productPool/1.jpg', 218 ),
( 'HOTT PERFUME SPRAY SPORT 150ML', 'productPool/1.jpg', 88 ),
( 'HOTT SPORT PERFUME SPRAY 60ML', 'productPool/1.jpg', 131 ),
( 'HOTT SWAGGER PERFUME SPRAY 135ML', 'productPool/1.jpg', 137 ),
( 'HOTT SWAGGER PERFUME SPRAY 60ML', 'productPool/1.jpg', 11 ),
( 'HOTWHEELS AQUAMIST HANDWASH 250ML', 'productPool/1.jpg', 269 ),
( 'HT KANNAN DEVAN CLASSIC 1 KG', 'productPool/1.jpg', 245 ),
( 'HUNTER BAT RECHARGEABLE', 'productPool/1.jpg', 98 ),
( 'HUNTER MOSQUITO BAT', 'productPool/1.jpg', 126 ),
( 'HUNTER MOSQUITO BAT MINI', 'productPool/1.jpg', 30 ),
( 'HY-GENIC PLUS WHITE LOTION 1 LTR', 'productPool/1.jpg', 226 ),
( 'HYBRITE A4 SHEET 80GSM', 'productPool/1.jpg', 113 ),
( 'HYGENIC BLEACHING POWDER 250GM', 'productPool/1.jpg', 101 ),
( 'HYGENIC BLEACHING POWDER 500GM', 'productPool/1.jpg', 243 ),
( 'HYGENIC PLUS BLACK PHENYL 500ML', 'productPool/1.jpg', 171 ),
( 'HYSSOP BUCKET COMBO', 'productPool/1.jpg', 173 ),
( 'HYSSOP SAN IT ALL DISINFECTANT LOTION 1L', 'productPool/1.jpg', 268 ),
( 'I BOND TAPE 18MM CLEAR', 'productPool/1.jpg', 43 ),
( 'I BOND TAPE 24MM CLEAR', 'productPool/1.jpg', 201 ),
( 'I BOND TAPE 48MM CLEAR', 'productPool/1.jpg', 214 ),
( 'I STIX MASKING TAPE 24MM*24M', 'productPool/1.jpg', 189 ),
( 'ICE BERG LETTUCE', 'productPool/1.jpg', 150 ),
( 'ICE CREAM CUP 100ML 50P', 'productPool/1.jpg', 279 ),
( 'ICE CREAM WH', 'productPool/1.jpg', 279 ),
( 'ICE DIY EH', 'productPool/1.jpg', 138 ),
( 'ICECREAM MIX BUTTER SCOTCH 100GM', 'productPool/1.jpg', 16 ),
( 'ICECREAM MIX STRAWBERRY', 'productPool/1.jpg', 262 ),
( 'ICECREAM SCOOPER EK', 'productPool/1.jpg', 178 ),
( 'IDALI RICE 1KG', 'productPool/1.jpg', 80 ),
( 'IDEAL MAGIC MOP', 'productPool/1.jpg', 138 ),
( 'IDEAL PISTA SYRUP 700ML', 'productPool/1.jpg', 16 ),
( 'IDHAYAM DOTS APPALAM 100G', 'productPool/1.jpg', 223 ),
( 'IDHAYAM GINGELLY OIL 1L POUCH', 'productPool/1.jpg', 36 ),
( 'IDHAYAM GINGELLY OIL 200ML', 'productPool/1.jpg', 173 ),
( 'IDHAYAM GINGELLY OIL 500ML', 'productPool/1.jpg', 214 ),
( 'IDHAYAM MANTRA GROUNDNUT 500ML', 'productPool/1.jpg', 166 ),
( 'IDHAYAM MANTRA GROUNDNUT OIL 1 LTR', 'productPool/1.jpg', 37 ),
( 'IDHAYAM MANTRA GROUNDNUT OIL 1L', 'productPool/1.jpg', 229 ),
( 'IDHAYAM SEASOME OIL 100 ML BOTTLE', 'productPool/1.jpg', 187 ),
( 'IDHAYAM SESAME OIL 1 LTR BOTTLE', 'productPool/1.jpg', 113 ),
( 'IDLY CHUTNEY POWDER 100G', 'productPool/1.jpg', 253 ),
( 'IDLY TONG', 'productPool/1.jpg', 211 ),
( 'IKON ANTI AGING CREAM 50GM', 'productPool/1.jpg', 229 ),
( 'IKON ANTI STRETCH MARKS CREAM 100GM', 'productPool/1.jpg', 208 ),
( 'IKON DENTOMIST SENSITIVE TOOTH PAST 50G', 'productPool/1.jpg', 85 ),
( 'IKON FEMISOFT INTIMATE WASH 100ML', 'productPool/1.jpg', 231 ),
( 'IKON GOLDEN GLOW FACE WASH 100ML', 'productPool/1.jpg', 220 ),
( 'IKON HERBAL ANTI DANDRUFF SHAMPOO 100ML', 'productPool/1.jpg', 194 ),
( 'IKON HERBAL BABY MASSAGE OIL 100ML', 'productPool/1.jpg', 10 ),
( 'IKON KETODAC ANT DANDRUFF SHAMPOO 100ML', 'productPool/1.jpg', 25 ),
( 'IKON MEDIZEN DEEP CLEANSING FACEWASH 100ML', 'productPool/1.jpg', 16 ),
( 'IKON PEARLDEW ALOE VERA SOAP 150G', 'productPool/1.jpg', 271 ),
( 'IKON PEARLDEW BABY CREAM 50G', 'productPool/1.jpg', 58 ),
( 'IKON PEARLDEW BABY LOTION 100ML', 'productPool/1.jpg', 87 ),
( 'IKON PEARLDEW BABY SHAMPOO 100ML', 'productPool/1.jpg', 14 ),
( 'IKON PEARLDEW BABY SOAP 75G', 'productPool/1.jpg', 277 ),
( 'IKON PEARLDEW GULABJAL SOAP 150G', 'productPool/1.jpg', 91 ),
( 'IKON PEARLDEW HAND SANITIZER 50ML', 'productPool/1.jpg', 136 ),
( 'IKON PEARLDEW HERBAL SHAMPOO 135M', 'productPool/1.jpg', 64 ),
( 'IKON PEARLDEW HONEY GLYCERINE SOAP 150G', 'productPool/1.jpg', 263 ),
( 'IKON PEARLDEW KESAR SOAP 150G', 'productPool/1.jpg', 145 ),
( 'IKON PEARLDEW MOISTURIZING SOAP 75G', 'productPool/1.jpg', 201 ),
( 'IKON PEARLDEW PREMIUM SOAP 150G', 'productPool/1.jpg', 67 ),
( 'IKON PEARLDEW ROYAL KHUS SOAP 150G', 'productPool/1.jpg', 115 ),
( 'IKON PEARLDEW ROYAL SANDAL SOAP 150G', 'productPool/1.jpg', 41 ),
( 'IKON PEARLDEW SKIN LIGHTENING SOAP 75G', 'productPool/1.jpg', 40 ),
( 'IMPORTED PLUMS', 'productPool/1.jpg', 147 ),
( 'INDEX CANVAS FILE IF555', 'productPool/1.jpg', 57 ),
( 'INDIA GATE CLASSIC 1KG', 'productPool/1.jpg', 93 ),
( 'INDIA GATE DUBAR BASMATI 1KG', 'productPool/1.jpg', 156 ),
( 'INDIA GATE GOLDEN SELA 25KG', 'productPool/1.jpg', 92 ),
( 'INDIA GATE GOLDEN SELA BASMATI RICE', 'productPool/1.jpg', 16 ),
( 'INDIA GATE LONG GRAIN 1KG', 'productPool/1.jpg', 179 ),
( 'INDIA GATE REGULAR CHOICE RICE 1KG', 'productPool/1.jpg', 30 ),
( 'INDIA GATE RICE ABSELLA 35 KG', 'productPool/1.jpg', 262 ),
( 'INDIA GATE ROZZANA 1KG', 'productPool/1.jpg', 37 ),
( 'INDIA GATE SUPER BASMATI 1KG', 'productPool/1.jpg', 60 ),
( 'INDIA GATE TIBAR BASMATI 1KG', 'productPool/1.jpg', 259 ),
( 'INDIA GATE WHITE SELA 25KG', 'productPool/1.jpg', 34 ),
( 'INDIAGATE BEMISAL 1 KG', 'productPool/1.jpg', 124 ),
( 'INDIAGATE UNITY BASMATI RICE 1 KG', 'productPool/1.jpg', 73 ),
( 'INDIAGATE WHITE SELLA 10KG', 'productPool/1.jpg', 241 ),
( 'INDIAN CHIEF GREEN CHILLI SAUCE 200 GM', 'productPool/1.jpg', 263 ),
( 'INDIAN CHIEF RED CHILLI SAUCE 200GM', 'productPool/1.jpg', 112 ),
( 'INDIAN CHIEF SOYA SAUCE200GM', 'productPool/1.jpg', 192 ),
( 'INDIAN CHIEF TOMATO SAUCE 200 GM', 'productPool/1.jpg', 226 ),
( 'INDICA 10 HER HAIR CREAM 2 IN 1', 'productPool/1.jpg', 116 ),
( 'INDICA CREME HAIR COLOUR', 'productPool/1.jpg', 5 ),
( 'INDICA EASY HAIR COLOUR 25ML', 'productPool/1.jpg', 2 ),
( 'INDICA EASY HAIR SHAMPOO 12ML', 'productPool/1.jpg', 269 ),
( 'INDICA HAIR COLOUR CREME BLACK 55ML', 'productPool/1.jpg', 173 ),
( 'INDICA HAIR COLOUR DARK BROWN 18ML', 'productPool/1.jpg', 47 ),
( 'INDICA HERBAL HAIR COLOUR 5G', 'productPool/1.jpg', 96 ),
( 'INDULEKHA BRINGA OIL 120ML', 'productPool/1.jpg', 191 ),
( 'INDULEKHA BRINGHA HAIR FALL SHAMPOO 200ML', 'productPool/1.jpg', 58 ),
( 'INDULEKHA BRINGHA SELFI OIL 100ML', 'productPool/1.jpg', 99 ),
( 'INDULEKHA KASTHURI MANJAL 50G', 'productPool/1.jpg', 87 ),
( 'INDUPPU 100GM', 'productPool/1.jpg', 278 ),
( 'INFINITY CONFERENCE FOLDER INF-CF 404', 'productPool/1.jpg', 18 ),
( 'INFINITY CONFERENCE FOLDER INF-CF 405', 'productPool/1.jpg', 178 ),
( 'INFINITY CONFERENCE FOLDER INF-CF 408', 'productPool/1.jpg', 17 ),
( 'INFINITY DISPLAY BOOK FILE DB 30F', 'productPool/1.jpg', 165 ),
( 'INFINITY DOCUMENT CASE FILE DC532F', 'productPool/1.jpg', 266 ),
( 'INFINITY EXPANDING BAG EB 708F', 'productPool/1.jpg', 42 ),
( 'INFINITY GEM CLIP', 'productPool/1.jpg', 129 ),
( 'INFINITY INDEX FILE IF 551', 'productPool/1.jpg', 124 ),
( 'INFINITY MULTI PURPOSE FILE MPF 511 F', 'productPool/1.jpg', 102 ),
( 'INFINITY MY CLEAR BAG MC903F', 'productPool/1.jpg', 157 ),
( 'INFINITY MY CLEAR BAG MC921F', 'productPool/1.jpg', 64 ),
( 'INFINITY NON SHARPENING PENCIL NSP212', 'productPool/1.jpg', 236 ),
( 'INFINITY PAPER CUTTER 304P', 'productPool/1.jpg', 253 ),
( 'INFINITY PAPER CUTTER PC 301 P', 'productPool/1.jpg', 169 ),
( 'INFINITY PAPPER CUTTER PC304 PC', 'productPool/1.jpg', 228 ),
( 'INFINITY PUNCHLESS SHORT CLIP FILE PL501F', 'productPool/1.jpg', 270 ),
( 'INFINITY PUSH PIN PP101', 'productPool/1.jpg', 270 ),
( 'INFINITY REPORT FILE COVER RF 517', 'productPool/1.jpg', 145 ),
( 'INFINITY SCISSORS SC 001', 'productPool/1.jpg', 185 ),
( 'INFINITY SPRING COBRA BOARD CLIP FILE SB 603', 'productPool/1.jpg', 125 ),
( 'INFINITY STICK FILE SF 802', 'productPool/1.jpg', 219 ),
( 'INFINITY STICK FILE SF 810', 'productPool/1.jpg', 27 ),
( 'INFINITY STICK FILESF802C', 'productPool/1.jpg', 162 ),
( 'INFINITY STICKY NOTES SN 33', 'productPool/1.jpg', 162 ),
( 'INFINITY STICKY NOTES SN33C', 'productPool/1.jpg', 113 ),
( 'INNOVA CHEF KNIFE -10', 'productPool/1.jpg', 262 ),
( 'INNOVA CHEF KNIFE -11', 'productPool/1.jpg', 239 ),
( 'INNOVA CHEF KNIFE -12', 'productPool/1.jpg', 228 ),
( 'INSTANT PASTTA CHATPATA TOMATO 65G', 'productPool/1.jpg', 93 ),
( 'INTERNATIONAL CAMAY CHIC SOAP 375G', 'productPool/1.jpg', 111 ),
( 'INTERNATIONAL CAMAY CLASSIC SOAP 125G', 'productPool/1.jpg', 271 ),
( 'INTERNATIONAL CAMAY CLASSIC SOAP SET 375G', 'productPool/1.jpg', 27 ),
( 'INTERNATIONAL CAMAY NATUREL SOAP 125G', 'productPool/1.jpg', 124 ),
( 'INTERNATIONAL CAMAY NATUREL SOAP SET 375G', 'productPool/1.jpg', 60 ),
( 'IODEX BALM 20G', 'productPool/1.jpg', 117 ),
( 'IRAN APPLE', 'productPool/1.jpg', 108 ),
( 'IRAN DATES', 'productPool/1.jpg', 87 ),
( 'IRIS CITRONELLA AGARBATHI 20N', 'productPool/1.jpg', 74 ),
( 'IRIS FRAGRANCE POUCH LAVENDER', 'productPool/1.jpg', 29 ),
( 'IRIS FRAGRANCE POUCH VANILA', 'productPool/1.jpg', 125 ),
( 'IRIS GARDEN INCENSE CITRONELLA 5N', 'productPool/1.jpg', 117 ),
( 'IRIS GARDEN INCENSE LEMON GRASS 5N', 'productPool/1.jpg', 124 ),
( 'IRIS GLASS JAR CANDLE DEWBERRY 40G', 'productPool/1.jpg', 96 ),
( 'IRIS GLASS JAR CANDLE GREEN TEA BAMBOO 40G', 'productPool/1.jpg', 227 ),
( 'IRIS GLASS JAR CANDLE GREEN TEA BAMBOO 85G', 'productPool/1.jpg', 62 ),
( 'IRIS GLASS JAR CANDLE PINA COLADA 40G', 'productPool/1.jpg', 49 ),
( 'IRIS GLASS JAR CANDLE SEA SHORE 40G', 'productPool/1.jpg', 257 ),
( 'IRIS INCENSE STICK EARTH', 'productPool/1.jpg', 203 ),
( 'IRIS INCENSE STICKS AIR', 'productPool/1.jpg', 165 ),
( 'IRIS INCENSE STICKS WATER', 'productPool/1.jpg', 268 ),
( 'IRIS JASMINE AGARBATHI 20N', 'productPool/1.jpg', 42 ),
( 'IRIS LAVENDER AGARBATHI 20N', 'productPool/1.jpg', 73 ),
( 'IRIS LEMON GRASS AGARBATHI 20N', 'productPool/1.jpg', 127 ),
( 'IRIS PET SPRAYER BIG', 'productPool/1.jpg', 87 ),
( 'IRIS PET SPRAYER SMALL', 'productPool/1.jpg', 72 ),
( 'IRIS ROSE AGARBATHI 20N', 'productPool/1.jpg', 231 ),
( 'IRIS SANDAL AGARBATHI 20N', 'productPool/1.jpg', 270 ),
( 'IRIS TEA LIGHT 24N', 'productPool/1.jpg', 277 ),
( 'IRIS TEA LIGHTS 10N', 'productPool/1.jpg', 124 ),
( 'IRON BRUSH CLOTH 4939', 'productPool/1.jpg', 26 ),
( 'IRON BRUSH WITH HANDLE', 'productPool/1.jpg', 24 ),
( 'ITALIA GLASS STAND', 'productPool/1.jpg', 200 ),
( 'ITALY APPLE', 'productPool/1.jpg', 97 ),
( 'ITCH GUARD 15G', 'productPool/1.jpg', 133 ),
( 'ITCH GUARD 25GM', 'productPool/1.jpg', 55 ),
( 'ITCH GUARD CREAM 20G', 'productPool/1.jpg', 256 ),
( 'IVA CHARAM DISH WASH 500G', 'productPool/1.jpg', 126 ),
( 'IVA DISH WASH 500G', 'productPool/1.jpg', 109 ),
( 'IVA DISH WASH ROUND 250G', 'productPool/1.jpg', 223 ),
( 'J & W NATURAL RED GRAPE 750 ML', 'productPool/1.jpg', 117 ),
( 'J.K FOODS ACHAPPAM MEDIUM 10NOS', 'productPool/1.jpg', 247 );