INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'CABBAGE RED', 'productPool/1.jpg', 220 ),
( 'CACAO ESTATE 400G', 'productPool/1.jpg', 106 ),
( 'CADBURRY GOLDEN OREO RS10', 'productPool/1.jpg', 249 ),
( 'CADBURY 5 STAR CRUNCHY 34G', 'productPool/1.jpg', 154 ),
( 'CADBURY 5STAR 20.5G RS10', 'productPool/1.jpg', 50 ),
( 'CADBURY 5STAR FLOWPA', 'productPool/1.jpg', 278 ),
( 'CADBURY 5STAR HOME TREATS 200G', 'productPool/1.jpg', 111 ),
( 'CADBURY 5STAR MRP 10', 'productPool/1.jpg', 189 ),
( 'CADBURY BOURN VITA 5 STAR MAGIC 1KG JAR', 'productPool/1.jpg', 215 ),
( 'CADBURY BOURN VITA 5 STAR MAGIC 500 JAR', 'productPool/1.jpg', 176 ),
( 'CADBURY BOURN VITA 5 STAR MAGIC 500 POUCH', 'productPool/1.jpg', 143 ),
( 'CADBURY BOURN VITA 5 STAR MAGIC 500G', 'productPool/1.jpg', 143 ),
( 'CADBURY BOURN VITA 500G JAR', 'productPool/1.jpg', 248 ),
( 'CADBURY BOURN VITA 500G POUCH', 'productPool/1.jpg', 118 ),
( 'CADBURY BOURN VITA 5STAR MAGIC 500G', 'productPool/1.jpg', 59 ),
( 'CADBURY BOURN VITA BISCUIT 120G', 'productPool/1.jpg', 258 ),
( 'CADBURY BOURN VITA BISCUIT MULTYPACK 250G', 'productPool/1.jpg', 19 ),
( 'CADBURY BOURN VITA BISCUITS MULTY PACK 250G', 'productPool/1.jpg', 92 ),
( 'CADBURY BOURN VITA FIVESTAR', 'productPool/1.jpg', 121 ),
( 'CADBURY BOURN VITA LIL CHAMPS 2-5 500G', 'productPool/1.jpg', 178 ),
( 'CADBURY BOURN VITA LIL CHAMPS 200G', 'productPool/1.jpg', 35 ),
( 'CADBURY BOURN VITA LIL CHAMPS 200G JAR', 'productPool/1.jpg', 229 ),
( 'CADBURY BOURN VITA LIL CHAMPS 200G RF', 'productPool/1.jpg', 278 ),
( 'CADBURY BOURN VITA LIL CHAMPS 500G', 'productPool/1.jpg', 234 ),
( 'CADBURY BOURN VITA SAKTHI 500GM', 'productPool/1.jpg', 136 ),
( 'CADBURY BOURN VITA SHAKTI 1KG', 'productPool/1.jpg', 232 ),
( 'CADBURY BOURN VITA SHAKTI 1KG JAR', 'productPool/1.jpg', 115 ),
( 'CADBURY BOURN VITA SHAKTI 1KG PKT', 'productPool/1.jpg', 222 ),
( 'CADBURY BOURN VITA SHAKTI 200G JAR', 'productPool/1.jpg', 107 ),
( 'CADBURY BOURN VITA SHAKTI 500G', 'productPool/1.jpg', 93 ),
( 'CADBURY BOURN VITA SHAKTI 500G JAR', 'productPool/1.jpg', 122 ),
( 'CADBURY BOURN VITA SHAKTI 500G PKT', 'productPool/1.jpg', 213 ),
( 'CADBURY BOURN VITA SHAKTI 500G RF', 'productPool/1.jpg', 14 ),
( 'CADBURY BOURN VITA SHAKTI 750G PKT', 'productPool/1.jpg', 182 ),
( 'CADBURY BOURN VITA SHAKTI JAR 1KG', 'productPool/1.jpg', 50 ),
( 'CADBURY BOURN VITA SHAKTI JAR 200G', 'productPool/1.jpg', 142 ),
( 'CADBURY BOURN VITA WOMEN 400G', 'productPool/1.jpg', 162 ),
( 'CADBURY BOURN VITTA BISCUITE 250G', 'productPool/1.jpg', 19 ),
( 'CADBURY BOURNVILLE RAISON & NUT 80G', 'productPool/1.jpg', 66 ),
( 'CADBURY BOURNVILLE RICH CHOCO 80G', 'productPool/1.jpg', 145 ),
( 'CADBURY BOURNVITA 1KG GP', 'productPool/1.jpg', 250 ),
( 'CADBURY BOURNVITA 1KG PKT', 'productPool/1.jpg', 88 ),
( 'CADBURY BOURNVITA 500G JAR', 'productPool/1.jpg', 274 ),
( 'CADBURY BOURNVITA 5STAR MAGIC 500G JAR', 'productPool/1.jpg', 158 ),
( 'CADBURY BOURNVITA 5STAR MAGIC GP 500G', 'productPool/1.jpg', 169 ),
( 'CADBURY BOURNVITA BADAM 200G', 'productPool/1.jpg', 230 ),
( 'CADBURY BOURNVITA BISCUIT 120G', 'productPool/1.jpg', 278 ),
( 'CADBURY BOURNVITA BISCUITS 120G', 'productPool/1.jpg', 15 ),
( 'CADBURY BOURNVITA FIVE STAR 1KG JAR', 'productPool/1.jpg', 170 ),
( 'CADBURY BOURNVITA LIL CHAMPS 200G', 'productPool/1.jpg', 25 ),
( 'CADBURY BOURNVITA LIL CHAMPS 500G', 'productPool/1.jpg', 216 ),
( 'CADBURY BOURNVITA LIL CHAMPS 500G JAR', 'productPool/1.jpg', 241 ),
( 'CADBURY BOURNVITA LILCHAMPS 200G JAR', 'productPool/1.jpg', 3 ),
( 'CADBURY BOURNVITA SHAKTI 1KG JAR', 'productPool/1.jpg', 33 ),
( 'CADBURY BOURNVITA SHAKTI 200G JAR', 'productPool/1.jpg', 169 ),
( 'CADBURY BOURNVITA SHAKTI 500G PKT', 'productPool/1.jpg', 135 ),
( 'CADBURY BOURNVITA SHAKTI 750G RFIL', 'productPool/1.jpg', 197 ),
( 'CADBURY BOURNVITA SHAKTI PRO HEALTH 500GRF', 'productPool/1.jpg', 170 ),
( 'CADBURY CELEBRATING FAVOURITES 180G', 'productPool/1.jpg', 136 ),
( 'CADBURY CELEBRATION 120G', 'productPool/1.jpg', 230 ),
( 'CADBURY CELEBRATION 172.6G', 'productPool/1.jpg', 156 ),
( 'CADBURY CELEBRATION 177.8G', 'productPool/1.jpg', 196 ),
( 'CADBURY CELEBRATIONS 126.4G', 'productPool/1.jpg', 86 ),
( 'CADBURY CELEBRATIONS 130G', 'productPool/1.jpg', 72 ),
( 'CADBURY CELEBRATIONS 175G', 'productPool/1.jpg', 64 ),
( 'CADBURY CELEBRATIONS 179.6G', 'productPool/1.jpg', 114 ),
( 'CADBURY CELEBRATIONS 190.3G', 'productPool/1.jpg', 14 ),
( 'CADBURY CELEBRATIONS 250.3G', 'productPool/1.jpg', 78 ),
( 'CADBURY CELEBRATIONS 66.6G', 'productPool/1.jpg', 254 ),
( 'CADBURY CELEBRATIONS BIG 286.3G', 'productPool/1.jpg', 122 ),
( 'CADBURY CELEBRATIONS DRY FRUIT177G', 'productPool/1.jpg', 255 ),
( 'CADBURY CELEBRATIONS PARTY PACK 349G', 'productPool/1.jpg', 78 ),
( 'CADBURY CHOCLAIRS 212.8G POUCH', 'productPool/1.jpg', 206 ),
( 'CADBURY CHOCLAIRS 3.5*115', 'productPool/1.jpg', 251 ),
( 'CADBURY CHOCLAIRS 3.8G', 'productPool/1.jpg', 2 ),
( 'CADBURY CHOCLAIRS 330G', 'productPool/1.jpg', 110 ),
( 'CADBURY CHOCLAIRS 402.5G MRP115', 'productPool/1.jpg', 193 ),
( 'CADBURY CHOCLAIRS 632.5G', 'productPool/1.jpg', 204 ),
( 'CADBURY CHOCLAIRS GOLD 342G POUCH', 'productPool/1.jpg', 165 ),
( 'CADBURY CHOCLAIRS GOLD 378.2 G POUCH', 'productPool/1.jpg', 169 ),
( 'CADBURY CHOCLAIRS GOLD POUCH 655.5G', 'productPool/1.jpg', 188 ),
( 'CADBURY CHOCLAIRS GOLD POUCH 713G', 'productPool/1.jpg', 124 ),
( 'CADBURY CHOCO CREAM OREO 50G', 'productPool/1.jpg', 240 ),
( 'CADBURY CHOCOBAKES COOKIES 150G', 'productPool/1.jpg', 11 ),
( 'CADBURY CHOCOBAKES COOKIES 75G', 'productPool/1.jpg', 265 ),
( 'CADBURY COCOA POWDER 150G', 'productPool/1.jpg', 140 ),
( 'CADBURY DAIRY MILK 12G', 'productPool/1.jpg', 214 ),
( 'CADBURY DAIRY MILK 13.2G', 'productPool/1.jpg', 207 ),
( 'CADBURY DAIRY MILK 13.2G MRP 10', 'productPool/1.jpg', 69 ),
( 'CADBURY DAIRY MILK 13.8G', 'productPool/1.jpg', 239 ),
( 'CADBURY DAIRY MILK 130G', 'productPool/1.jpg', 43 ),
( 'CADBURY DAIRY MILK 24G MRP20', 'productPool/1.jpg', 33 ),
( 'CADBURY DAIRY MILK 25.3G MRP 20', 'productPool/1.jpg', 16 ),
( 'CADBURY DAIRY MILK 25G', 'productPool/1.jpg', 76 ),
( 'CADBURY DAIRY MILK 3 FLAVOURS 114G', 'productPool/1.jpg', 113 ),
( 'CADBURY DAIRY MILK 50G MRP40', 'productPool/1.jpg', 217 ),
( 'CADBURY DAIRY MILK 55G MRP 40', 'productPool/1.jpg', 64 ),
( 'CADBURY DAIRY MILK 5RS', 'productPool/1.jpg', 236 ),
( 'CADBURY DAIRY MILK 6.6G MRP 5', 'productPool/1.jpg', 64 ),
( 'CADBURY DAIRY MILK BLACCK FOREST 165 G', 'productPool/1.jpg', 205 ),
( 'CADBURY DAIRY MILK BUBBLY 50G', 'productPool/1.jpg', 157 ),
( 'CADBURY DAIRY MILK BUTTERSCOTCH 36G', 'productPool/1.jpg', 106 ),
( 'CADBURY DAIRY MILK CARAMELLO 136G', 'productPool/1.jpg', 232 ),
( 'CADBURY DAIRY MILK CARAMELLO 60G', 'productPool/1.jpg', 124 ),
( 'CADBURY DAIRY MILK CELEBRATIONS 168.8G', 'productPool/1.jpg', 42 ),
( 'CADBURY DAIRY MILK CHOCOLATE 145G', 'productPool/1.jpg', 143 ),
( 'CADBURY DAIRY MILK CHOCOLATE 150G', 'productPool/1.jpg', 41 ),
( 'CADBURY DAIRY MILK CHOCOLATE MRP 40', 'productPool/1.jpg', 177 ),
( 'CADBURY DAIRY MILK CHOCOLATE MRP 49', 'productPool/1.jpg', 50 ),
( 'CADBURY DAIRY MILK CHOCOLATE MRP20', 'productPool/1.jpg', 61 ),
( 'CADBURY DAIRY MILK CRACKLE 36G', 'productPool/1.jpg', 190 ),
( 'CADBURY DAIRY MILK CRISPELLO 33G', 'productPool/1.jpg', 118 ),
( 'CADBURY DAIRY MILK CRISPELLO 35G', 'productPool/1.jpg', 65 ),
( 'CADBURY DAIRY MILK FLOW 54G', 'productPool/1.jpg', 136 ),
( 'CADBURY DAIRY MILK FRUIT AND NUT 36G', 'productPool/1.jpg', 186 ),
( 'CADBURY DAIRY MILK FRUIT AND NUT 80G', 'productPool/1.jpg', 257 ),
( 'CADBURY DAIRY MILK FRUIT AND NUT RS-45', 'productPool/1.jpg', 171 ),
( 'CADBURY DAIRY MILK FRUIT-NUT 36G', 'productPool/1.jpg', 202 ),
( 'CADBURY DAIRY MILK HAZEL NUT 165 G', 'productPool/1.jpg', 52 ),
( 'CADBURY DAIRY MILK HOME TREATS 140G', 'productPool/1.jpg', 134 ),
( 'CADBURY DAIRY MILK IMP 165G', 'productPool/1.jpg', 6 ),
( 'CADBURY DAIRY MILK JELLY POPPING 35G', 'productPool/1.jpg', 162 ),
( 'CADBURY DAIRY MILK LESS SUGAR 43G', 'productPool/1.jpg', 188 ),
( 'CADBURY DAIRY MILK LICKABLES 20G', 'productPool/1.jpg', 37 ),
( 'CADBURY DAIRY MILK LICKABLES 25G', 'productPool/1.jpg', 167 ),
( 'CADBURY DAIRY MILK LICKABLES RS 40', 'productPool/1.jpg', 95 ),
( 'CADBURY DAIRY MILK MANGO 36G', 'productPool/1.jpg', 51 ),
( 'CADBURY DAIRY MILK ROAST ALMOND 143G', 'productPool/1.jpg', 149 ),
( 'CADBURY DAIRY MILK ROAST ALMOND 165 G', 'productPool/1.jpg', 130 ),
( 'CADBURY DAIRY MILK ROAST ALMOND 36G', 'productPool/1.jpg', 40 ),
( 'CADBURY DAIRY MILK ROAST ALMOND 55G', 'productPool/1.jpg', 112 ),
( 'CADBURY DAIRY MILK SILK 130G', 'productPool/1.jpg', 256 ),
( 'CADBURY DAIRY MILK SILK 250G', 'productPool/1.jpg', 196 ),
( 'CADBURY DAIRY MILK SILK BUBBLY 120G', 'productPool/1.jpg', 170 ),
( 'CADBURY DAIRY MILK SILK BUBBLY 120G -', 'productPool/1.jpg', 154 ),
( 'CADBURY DAIRY MILK SILK BUBBLY 50G', 'productPool/1.jpg', 271 ),
( 'CADBURY DAIRY MILK SILK CARAMELLO 136G', 'productPool/1.jpg', 185 ),
( 'CADBURY DAIRY MILK SILK CARAMELLO 60G', 'productPool/1.jpg', 60 ),
( 'CADBURY DAIRY MILK SILK CHOCOLATE 60G', 'productPool/1.jpg', 159 ),
( 'CADBURY DAIRY MILK SILK FRUIT & NUT 137G', 'productPool/1.jpg', 210 ),
( 'CADBURY DAIRY MILK SILK FRUIT AND NUT 137G', 'productPool/1.jpg', 41 ),
( 'CADBURY DAIRY MILK SILK FRUIT-NUT 55G', 'productPool/1.jpg', 54 ),
( 'CADBURY DAIRY MILK SILK HAZELNUT 143G', 'productPool/1.jpg', 98 ),
( 'CADBURY DAIRY MILK SILK HEART POP 150G', 'productPool/1.jpg', 154 ),
( 'CADBURY DAIRY MILK SILK HEART POP 250G', 'productPool/1.jpg', 141 ),
( 'CADBURY DAIRY MILK SILK OREO 130G', 'productPool/1.jpg', 29 ),
( 'CADBURY DAIRY MILK SILK OREO 60G', 'productPool/1.jpg', 148 ),
( 'CADBURY DAIRY MILK SILK OREO RED VELVET 130G', 'productPool/1.jpg', 169 ),
( 'CADBURY DAIRY MILK SILK OREO RED VELVET 60G', 'productPool/1.jpg', 142 ),
( 'CADBURY DAIRY MILK SILK PLAIN 150G', 'productPool/1.jpg', 252 ),
( 'CADBURY DAIRY MILK SILK PLAIN 60G', 'productPool/1.jpg', 54 ),
( 'CADBURY DAIRY MILK SILK ROAST ALMOND 137G', 'productPool/1.jpg', 123 ),
( 'CADBURY DAIRY MILK SILK VALENTINES 60G', 'productPool/1.jpg', 196 ),
( 'CADBURY DAIRY MILK SPREADY 200G', 'productPool/1.jpg', 134 ),
( 'CADBURY DAIRYMILK FRUIT & NUT 38G', 'productPool/1.jpg', 191 ),
( 'CADBURY DAIRYMILK FRUIT AND NUT 36G', 'productPool/1.jpg', 204 ),
( 'CADBURY DAIRYMILK ROAST ALMOND 137G', 'productPool/1.jpg', 99 ),
( 'CADBURY DAIRYMILK ROAST ALMOND 58G', 'productPool/1.jpg', 39 ),
( 'CADBURY DAIRYMILK SILK OREO 60G', 'productPool/1.jpg', 260 ),
( 'CADBURY DAIRYMILK SILK PLAIN 150G', 'productPool/1.jpg', 26 ),
( 'CADBURY DARK MILK SALTED CARAMEL 156G', 'productPool/1.jpg', 76 ),
( 'CADBURY DIPPED OREO 50G', 'productPool/1.jpg', 14 ),
( 'CADBURY FIVE STAR 10.1G', 'productPool/1.jpg', 71 ),
( 'CADBURY FIVE STAR 11.1G MRP 5', 'productPool/1.jpg', 102 ),
( 'CADBURY FIVE STAR 22.4G', 'productPool/1.jpg', 115 ),
( 'CADBURY FIVE STAR 25G MRP10', 'productPool/1.jpg', 62 ),
( 'CADBURY FIVE STAR 3D 135G', 'productPool/1.jpg', 255 ),
( 'CADBURY FIVE STAR 3D 45G', 'productPool/1.jpg', 135 ),
( 'CADBURY FIVE STAR 40G', 'productPool/1.jpg', 195 ),
( 'CADBURY FIVE STAR 43G', 'productPool/1.jpg', 51 ),
( 'CADBURY FIVE STAR HOME TREAT 200G', 'productPool/1.jpg', 37 ),
( 'CADBURY FIVE STAR NUTTY 19G', 'productPool/1.jpg', 93 ),
( 'CADBURY FUSE 27.5G', 'productPool/1.jpg', 96 ),
( 'CADBURY FUSE 30G', 'productPool/1.jpg', 115 ),
( 'CADBURY FUSE 45G', 'productPool/1.jpg', 58 ),
( 'CADBURY FUSE 50G', 'productPool/1.jpg', 42 ),
( 'CADBURY FUSE 50G MRP35', 'productPool/1.jpg', 15 ),
( 'CADBURY FUSE VALUE PACK 135G', 'productPool/1.jpg', 74 ),
( 'CADBURY FUSE VALUE PACK 150G', 'productPool/1.jpg', 129 ),
( 'CADBURY GEMS 10.68G', 'productPool/1.jpg', 45 ),
( 'CADBURY GEMS 10.68G MRP5', 'productPool/1.jpg', 201 ),
( 'CADBURY GEMS 17.8G', 'productPool/1.jpg', 274 ),
( 'CADBURY GEMS 17.8G BALL', 'productPool/1.jpg', 187 ),
( 'CADBURY GEMS 21.36G', 'productPool/1.jpg', 95 ),
( 'CADBURY GEMS 21.36G RS10', 'productPool/1.jpg', 198 ),
( 'CADBURY GEMS 44.5G', 'productPool/1.jpg', 188 ),
( 'CADBURY GEMS ANGRY BIRDS 17.8G', 'productPool/1.jpg', 193 ),
( 'CADBURY GEMS SURPRISE BALL 17.8G', 'productPool/1.jpg', 237 ),
( 'CADBURY GOLDEN OREO 51.5G MRP 10', 'productPool/1.jpg', 116 ),
( 'CADBURY HOT CHOCOLATE 200G', 'productPool/1.jpg', 204 ),
( 'CADBURY MONSTER GEMS 39.9G', 'productPool/1.jpg', 93 ),
( 'CADBURY MONSTER GEMS 45.6G', 'productPool/1.jpg', 191 ),
( 'CADBURY OREO CHOCO CREAM 120G', 'productPool/1.jpg', 198 ),
( 'CADBURY OREO CHOCO CREME 120G', 'productPool/1.jpg', 262 ),
( 'CADBURY OREO FAMILY PACK 3*100G', 'productPool/1.jpg', 194 ),
( 'CADBURY OREO GOLD VANILA 120G', 'productPool/1.jpg', 170 ),
( 'CADBURY OREO ORIGINAL 51.5G MRP 10', 'productPool/1.jpg', 161 ),
( 'CADBURY OREO STRAWBERRY 120G', 'productPool/1.jpg', 194 ),
( 'CADBURY OREO VANILLA 120G', 'productPool/1.jpg', 183 ),
( 'CADBURY OREO VANILLA CREAM 50G', 'productPool/1.jpg', 171 ),
( 'CADBURY PERK 13G', 'productPool/1.jpg', 187 ),
( 'CADBURY PERK 14.3G', 'productPool/1.jpg', 155 ),
( 'CADBURY PERK 29G', 'productPool/1.jpg', 156 ),
( 'CADBURY PERK 78G', 'productPool/1.jpg', 69 ),
( 'CADBURY PERK BITES 175.5G', 'productPool/1.jpg', 22 ),
( 'CADBURY PERK HOME TREATS 193G', 'productPool/1.jpg', 164 ),
( 'CADBURY PERK RS10', 'productPool/1.jpg', 214 ),
( 'CADBURY SHOOTS 16.2G', 'productPool/1.jpg', 151 ),
( 'CADBURY SHOTS 1.8G', 'productPool/1.jpg', 72 ),
( 'CADBURY SHOTS 10.8G MRP 5', 'productPool/1.jpg', 58 ),
( 'CADBURY SHOTS 18G MRP10', 'productPool/1.jpg', 274 ),
( 'CADBURY SHOTS 19.8G MRP 10', 'productPool/1.jpg', 175 ),
( 'CADBURY SILK MOCHA CARAMELLO 136G', 'productPool/1.jpg', 38 ),
( 'CADBURY TEMPTATION CASHEW 72G', 'productPool/1.jpg', 267 ),
( 'CADBURY TEMPTATION RUM RAISON 72G', 'productPool/1.jpg', 244 ),
( 'CADBURY TEMPTATIONS ALMOND 72G', 'productPool/1.jpg', 7 ),
( 'CADBURY TEMPTATIONS ALMOND TREAT72G', 'productPool/1.jpg', 61 ),
( 'CADBURY TEMPTATIONS RAISINS 72G', 'productPool/1.jpg', 37 ),
( 'CAKE BAKING TOOL SET KO', 'productPool/1.jpg', 169 ),
( 'CAKE BOX WH', 'productPool/1.jpg', 35 ),
( 'CAKE MARGARINE 1KG', 'productPool/1.jpg', 227 ),
( 'CAKE MARGARINE 500G', 'productPool/1.jpg', 13 ),
( 'CAKE MOULD KS', 'productPool/1.jpg', 258 ),
( 'CAKE MOULD LX', 'productPool/1.jpg', 211 ),
( 'CAKE MOULD OD', 'productPool/1.jpg', 226 ),
( 'CAKE MOULD SAX', 'productPool/1.jpg', 149 ),
( 'CAKE MOULD SXX', 'productPool/1.jpg', 12 ),
( 'CAKE TONG', 'productPool/1.jpg', 154 ),
( 'CAMEL KITCHEN MATCHES 100 STICK', 'productPool/1.jpg', 48 ),
( 'CAMEL MATCHES', 'productPool/1.jpg', 265 ),
( 'CAMEL MATCHES BIG MRP 10', 'productPool/1.jpg', 30 ),
( 'CAMEL WATER COLOR TUBE 12 SHADE', 'productPool/1.jpg', 224 ),
( 'CAMEL WATER COLOR TUBE 6 SHADE RS 50', 'productPool/1.jpg', 54 ),
( 'CAMEL WATER COLOUR CAKES 12C', 'productPool/1.jpg', 92 ),
( 'CAMLIN CARBON PAPER 100S', 'productPool/1.jpg', 168 ),
( 'CAMLIN CATRIDGE PEN', 'productPool/1.jpg', 108 ),
( 'CAMLIN EXAM GEOMATRY BOX', 'productPool/1.jpg', 187 ),
( 'CAMLIN SCHOLAR INSTUMENT BOX', 'productPool/1.jpg', 279 ),
( 'CAMLIN SPEEDY CATRIDGE PEN', 'productPool/1.jpg', 124 ),
( 'CAMLIN WATER COLOUR 24 SHADES', 'productPool/1.jpg', 106 ),
( 'CAMPFIRE MARSHMALLOW 160G', 'productPool/1.jpg', 213 ),
( 'CAMPUS 12 PARTITION CONTAINER', 'productPool/1.jpg', 205 ),
( 'CAMPUS 8 PARTITION CONTAINER', 'productPool/1.jpg', 117 ),
( 'CAMRY LUNCH BOX BIG', 'productPool/1.jpg', 149 ),
( 'CAN 2.5 LTR', 'productPool/1.jpg', 80 ),
( 'CAN 5 LTR', 'productPool/1.jpg', 134 ),
( 'CANDLE RS30', 'productPool/1.jpg', 130 ),
( 'CANDLE RS45', 'productPool/1.jpg', 175 ),
( 'CANDY MAN ECLAIRS 290G', 'productPool/1.jpg', 206 ),
( 'CANDYMAN CHOCO DOUBLE ECLAIRS 814G', 'productPool/1.jpg', 174 ),
( 'CANDYMAN CHOCO ECLAIRS 400', 'productPool/1.jpg', 207 ),
( 'CANDYMAN CREME LACTO 562.5G', 'productPool/1.jpg', 206 ),
( 'CANDYMAN CREME LACTO 900G', 'productPool/1.jpg', 125 ),
( 'CANDYMAN CREME LACTO CHOCOLATE', 'productPool/1.jpg', 183 ),
( 'CANDYMAN FANTASTIK MRP 5', 'productPool/1.jpg', 149 ),
( 'CANDYMAN FRUITEE FUN CANDY JAR 750G', 'productPool/1.jpg', 192 ),
( 'CANDYMAN MILKY ECLAIRS 475G', 'productPool/1.jpg', 203 ),
( 'CANDYMAN PEANUT BUTTER CANDY 640G JAR', 'productPool/1.jpg', 104 ),
( 'CANDYMAN TOFFICHOO STRAWBERRY TOFFEE 290G', 'productPool/1.jpg', 136 ),
( 'CANDYMAN TOFFICHOO STRAWBERRY TOFFEE 725G', 'productPool/1.jpg', 50 ),
( 'CANZ SWEET CORN KERNELS IN BRINE 425G', 'productPool/1.jpg', 14 ),
( 'CAP', 'productPool/1.jpg', 53 ),
( 'CAPSICUM', 'productPool/1.jpg', 273 ),
( 'CAPSICUM COLOUR', 'productPool/1.jpg', 104 ),
( 'CAR FRICTION 21-5-1500', 'productPool/1.jpg', 213 ),
( 'CAR WASH ECO FRIENDLY 250ML', 'productPool/1.jpg', 89 ),
( 'CARBURY BOURN VITA 200G', 'productPool/1.jpg', 218 ),
( 'CARBURY DAIRY MILK SILK OREO 130G', 'productPool/1.jpg', 171 ),
( 'CARDBOURY 5STAR 40G', 'productPool/1.jpg', 32 ),
( 'CARDBOURY DARK MILK ORIGINAL 100G', 'productPool/1.jpg', 136 ),
( 'CARDBOURY DARK MILK ORIGINAL 156G', 'productPool/1.jpg', 99 ),
( 'CARDBOURY LUVIT CHOCO 20G', 'productPool/1.jpg', 269 ),
( 'CARDBURY NUTTIES 30G', 'productPool/1.jpg', 180 ),
( 'CARDIA LIFE VEG OIL 1L', 'productPool/1.jpg', 195 ),
( 'CARDOMOM', 'productPool/1.jpg', 64 ),
( 'CARDOMOM 100G', 'productPool/1.jpg', 96 ),
( 'CARDOMOM 12G', 'productPool/1.jpg', 52 ),
( 'CARDOMOM 250G', 'productPool/1.jpg', 55 ),
( 'CARDOMOM 500G', 'productPool/1.jpg', 54 ),
( 'CARDOMOM 6G', 'productPool/1.jpg', 185 ),
( 'CARDOMOM 6GM', 'productPool/1.jpg', 104 ),
( 'CARPET MAT 2*3', 'productPool/1.jpg', 57 ),
( 'CARPET MAT 5*3', 'productPool/1.jpg', 204 ),
( 'CARPET MAT 5*7', 'productPool/1.jpg', 33 ),
( 'CARROT', 'productPool/1.jpg', 274 ),
( 'CARROT & CHOCOLATE CAKE 500 GMS', 'productPool/1.jpg', 156 ),
( 'CARROT CAKE 500 GMS', 'productPool/1.jpg', 91 ),
( 'CARROT CAKE TIN', 'productPool/1.jpg', 59 ),
( 'CARTOON LOLLIPOP', 'productPool/1.jpg', 141 ),
( 'CASHEW CHILLY', 'productPool/1.jpg', 67 ),
( 'CASHEW NUT 100G', 'productPool/1.jpg', 270 ),
( 'CASHEW NUT 100G SP', 'productPool/1.jpg', 222 ),
( 'CASHEW PLAIN 240', 'productPool/1.jpg', 176 ),
( 'CASHEW RAVA DOSA 200G', 'productPool/1.jpg', 106 ),
( 'CASHEW ROCKS', 'productPool/1.jpg', 134 ),
( 'CASHEW THONDAN', 'productPool/1.jpg', 167 ),
( 'CASHEWNUT 50G SPILT', 'productPool/1.jpg', 65 ),
( 'CASHEWNUT 50G SPLT', 'productPool/1.jpg', 4 ),
( 'CASHEWNUT 50G W320', 'productPool/1.jpg', 88 ),
( 'CASHEWNUT W320 50G', 'productPool/1.jpg', 66 ),
( 'CASHEWS SALTED', 'productPool/1.jpg', 31 ),
( 'CASIO CALCULATOR CB144- MJ12SA', 'productPool/1.jpg', 180 ),
( 'CASIO CALCULATOR HL 100LB', 'productPool/1.jpg', 79 ),
( 'CASIO CALCULATOR HL- 4A', 'productPool/1.jpg', 193 ),
( 'CASIO CALCULATOR HL-815L', 'productPool/1.jpg', 90 ),
( 'CASIO CALCULATOR HL-820LV', 'productPool/1.jpg', 218 ),
( 'CASIO CALCULATOR MJ-120D', 'productPool/1.jpg', 142 ),
( 'CASIO CALCULATOR MJ-120D PLUS', 'productPool/1.jpg', 262 ),
( 'CASIO CALCULATOR MJ-12SB', 'productPool/1.jpg', 254 ),
( 'CASIO CALCULATOR SX-300', 'productPool/1.jpg', 248 ),
( 'CASIO CALCULATOR WJ-120D PLUS', 'productPool/1.jpg', 263 ),
( 'CASIO DESKTOP CB145-MJ 12DA', 'productPool/1.jpg', 65 ),
( 'CASIO DESKTOP CB147-MJ-120DA', 'productPool/1.jpg', 123 ),
( 'CASIOCALCULATOR MZ-12SA', 'productPool/1.jpg', 142 ),
( 'CASTILLO RED GRAPE 1 LTR', 'productPool/1.jpg', 121 ),
( 'CASTTA QUEEN', 'productPool/1.jpg', 128 ),
( 'CAULIFLOWER', 'productPool/1.jpg', 26 ),
( 'CAVINS BANANA MILKSHAKE 180ML', 'productPool/1.jpg', 261 ),
( 'CAVINS COFFEF MILKSHAKE 180ML', 'productPool/1.jpg', 208 ),
( 'CAVINS CURD', 'productPool/1.jpg', 60 ),
( 'CAVINS DIET CURD 500G PKT', 'productPool/1.jpg', 69 ),
( 'CAVINS MANGO MILKSHAKE 180ML', 'productPool/1.jpg', 253 ),
( 'CAVINS MILK PKT', 'productPool/1.jpg', 19 ),
( 'CAVINS MILK SHAKE BUTTERSCOTCH 200 ML', 'productPool/1.jpg', 51 ),
( 'CAVINS MILK SHAKE CHOC 200ML', 'productPool/1.jpg', 203 ),
( 'CAVINS MILK SHAKE STRAWBERRY 200ML', 'productPool/1.jpg', 55 ),
( 'CAVINS MILK SHAKE VANILA 200ML', 'productPool/1.jpg', 14 ),
( 'CAVINS MILKSHAKE BUTTERSCOTCH 180ML', 'productPool/1.jpg', 249 ),
( 'CAVINS MILKSHAKE BUTTERSCOTCH 1L', 'productPool/1.jpg', 10 ),
( 'CAVINS MILKSHAKE CHOCOLATE 180ML', 'productPool/1.jpg', 169 ),
( 'CAVINS MILKSHAKE CHOCOLATE 1L', 'productPool/1.jpg', 43 ),
( 'CAVINS MILKSHAKE LITE STRAWBERRY 180ML', 'productPool/1.jpg', 21 ),
( 'CAVINS MILKSHAKE LITE VANILLA 180 ML', 'productPool/1.jpg', 109 ),
( 'CAVINS MILKSHAKE STRAWBERRY 180ML', 'productPool/1.jpg', 272 ),
( 'CAVINS MILKSHAKE STRAWBERY 1L', 'productPool/1.jpg', 259 ),
( 'CAVINS MILKSHAKE VANILLA 180ML', 'productPool/1.jpg', 162 ),
( 'CD MARKER RED', 'productPool/1.jpg', 145 ),
( 'CDC CASHEW POWDER 100G', 'productPool/1.jpg', 66 ),
( 'CEELO KLEENO CLASSI TWIST MOP 1N', 'productPool/1.jpg', 194 ),
( 'CEELO KLEENO POPULAR WIPER 2N', 'productPool/1.jpg', 178 ),
( 'CELERY', 'productPool/1.jpg', 211 ),
( 'CELL NEON BOLL PEN', 'productPool/1.jpg', 81 ),
( 'CELLO AQUA COOL 600ML', 'productPool/1.jpg', 11 ),
( 'CELLO AQUA COOL BOTTLE 1 LTR', 'productPool/1.jpg', 193 ),
( 'CELLO AVENGERS BALL PEN', 'productPool/1.jpg', 235 ),
( 'CELLO AVIATOR WATER BOTTLE 750ML', 'productPool/1.jpg', 125 ),
( 'CELLO BARBIE KIDS SET 4PCS', 'productPool/1.jpg', 264 ),
( 'CELLO BASIN 14DC', 'productPool/1.jpg', 160 ),
( 'CELLO BASIN 18DC', 'productPool/1.jpg', 8 ),
( 'CELLO BEATLE SS FLASK 700ML', 'productPool/1.jpg', 224 ),
( 'CELLO BEATLE WATER BOTTLE 550ML', 'productPool/1.jpg', 135 ),
( 'CELLO BLING BALL PEN BLACK', 'productPool/1.jpg', 60 ),
( 'CELLO BLING BALL PEN BLUE', 'productPool/1.jpg', 32 ),
( 'CELLO BUTTER GEL PEN', 'productPool/1.jpg', 171 ),
( 'CELLO BUTTERFLOW BALL PEN BLACK', 'productPool/1.jpg', 85 ),
( 'CELLO BUTTERFLOW BALL PEN BLUE', 'productPool/1.jpg', 180 ),
( 'CELLO BUTTERFLOW BALLPEN BLACK MRP 10', 'productPool/1.jpg', 15 ),
( 'CELLO BUTTERFLOW CLIC BALL PEN', 'productPool/1.jpg', 122 ),
( 'CELLO BUTTERFLOW COLOUR 4 PEN', 'productPool/1.jpg', 234 ),
( 'CELLO BUTTERFLOW SIMPLY BLUE PEN MRP 10', 'productPool/1.jpg', 174 ),
( 'CELLO BUTTERFLOW SUPER STAR BALL PEN', 'productPool/1.jpg', 123 ),
( 'CELLO BUTTERFLOW TRENDY BALL PEN', 'productPool/1.jpg', 75 ),
( 'CELLO CD MARKER', 'productPool/1.jpg', 47 ),
( 'CELLO CHECKERS 300ML JAR', 'productPool/1.jpg', 43 ),
( 'CELLO CHECKERS 650ML JAR', 'productPool/1.jpg', 173 ),
( 'CELLO CHECKERS JAR 1200ML', 'productPool/1.jpg', 207 ),
( 'CELLO CLASSIC PEDAL BIN-1', 'productPool/1.jpg', 51 ),
( 'CELLO CLASSIC PEDAL BIN-2', 'productPool/1.jpg', 98 ),
( 'CELLO CONTEMPO WATER BOTTLE 1000ML', 'productPool/1.jpg', 207 ),
( 'CELLO CRUNCH BIG TIFFIN BOX', 'productPool/1.jpg', 230 ),
( 'CELLO CRYSTA SS BOTTLE 1000ML', 'productPool/1.jpg', 71 ),
( 'CELLO CUP STYLE STEEL FLASK 500ML', 'productPool/1.jpg', 157 ),
( 'CELLO CUP STYLE STEEL FLASK 750ML', 'productPool/1.jpg', 89 ),
( 'CELLO CURVY SS BOTTLE 1000ML', 'productPool/1.jpg', 2 ),
( 'CELLO CURVY SS BOTTLE 750ML', 'productPool/1.jpg', 102 ),
( 'CELLO D SIGNER BUCKET NO-16', 'productPool/1.jpg', 106 ),
( 'CELLO D SIGNER BUCKET NO-18', 'productPool/1.jpg', 267 ),
( 'CELLO D SIGNER BUCKET NO-20', 'productPool/1.jpg', 99 ),
( 'CELLO D SIGNER MUG 1.5 LTR', 'productPool/1.jpg', 211 ),
( 'CELLO D SIGNER MUG 1L', 'productPool/1.jpg', 24 ),
( 'CELLO D SIGNER MUG 1LTR', 'productPool/1.jpg', 178 ),
( 'CELLO DELITE 4PCS SET', 'productPool/1.jpg', 237 ),
( 'CELLO DESIGNER BUCKET NO 18', 'productPool/1.jpg', 21 ),
( 'CELLO DIAMOND WATER BOTTLE 1000ML', 'productPool/1.jpg', 143 ),
( 'CELLO DINNER SET COOL LINES', 'productPool/1.jpg', 174 ),
( 'CELLO DINNER SET FLORID VINE', 'productPool/1.jpg', 97 ),
( 'CELLO DINNER SET LIVID LILAC', 'productPool/1.jpg', 172 ),
( 'CELLO DINNER SET MAGICAL STAR', 'productPool/1.jpg', 220 ),
( 'CELLO DINNER SET SCARLETT BLISS', 'productPool/1.jpg', 120 ),
( 'CELLO DURA FRESH PET 500ML', 'productPool/1.jpg', 24 ),
( 'CELLO DURA FRESH1000ML', 'productPool/1.jpg', 252 ),
( 'CELLO EASY STYLE STEELFLASK 750ML', 'productPool/1.jpg', 44 ),
( 'CELLO ENDURA STOOL SMALL', 'productPool/1.jpg', 208 ),
( 'CELLO ENIGMA SMALL LUNCH BOX', 'productPool/1.jpg', 78 ),
( 'CELLO ESTELLA DEEP BOWL 1000ML', 'productPool/1.jpg', 132 ),
( 'CELLO ESTELLA DEEP BOWL 600ML', 'productPool/1.jpg', 108 ),
( 'CELLO EXCEED FOUNTAIN PEN', 'productPool/1.jpg', 15 ),
( 'CELLO EZEE SIP WATER BOTTLE 750ML', 'productPool/1.jpg', 190 ),
( 'CELLO FABBY 3 PCS SET', 'productPool/1.jpg', 122 ),
( 'CELLO FASHION D 1000ML JAR', 'productPool/1.jpg', 168 ),
( 'CELLO FASHION D 1500ML JAR', 'productPool/1.jpg', 143 ),
( 'CELLO FASHION D 3PCS SET', 'productPool/1.jpg', 86 ),
( 'CELLO FASHION D 750ML JAR', 'productPool/1.jpg', 123 ),
( 'CELLO FINEGRIP RS 7', 'productPool/1.jpg', 266 ),
( 'CELLO FINO BOTTLE 1LT', 'productPool/1.jpg', 164 ),
( 'CELLO FINO SS BOTTLE 650ML', 'productPool/1.jpg', 159 ),
( 'CELLO FIT GRIP BOTTLE 850ML', 'productPool/1.jpg', 248 ),
( 'CELLO FLAVIA OIL DISPENSER 1L', 'productPool/1.jpg', 51 ),
( 'CELLO FLO GEL PEN RS 10', 'productPool/1.jpg', 219 ),
( 'CELLO FLOGEL GEL PEN RS10', 'productPool/1.jpg', 92 ),
( 'CELLO FLORINA 102 CONTAINER 3PCS', 'productPool/1.jpg', 8 ),
( 'CELLO FLORINA 106 CONTAINER 2PCS', 'productPool/1.jpg', 210 ),
( 'CELLO FLORINA 111 CONTAINER 2PCS', 'productPool/1.jpg', 223 ),
( 'CELLO FRESCA FILP BOTTLE 600ML', 'productPool/1.jpg', 17 ),
( 'CELLO FRESCA FLIP 1000 ML BOTTLE', 'productPool/1.jpg', 227 ),
( 'CELLO FRESCA WATER BOTTLE 1000ML', 'productPool/1.jpg', 191 ),
( 'CELLO FROSTY BUCKET 181 DLX', 'productPool/1.jpg', 275 ),
( 'CELLO FROSTY BUCKET 201 DLX', 'productPool/1.jpg', 211 ),
( 'CELLO FRUTO WATER BOTTLE 900ML', 'productPool/1.jpg', 278 ),
( 'CELLO FUSHION BUCKET NO.15', 'productPool/1.jpg', 151 ),
( 'CELLO FUSHION BUCKET NO.22', 'productPool/1.jpg', 13 ),
( 'CELLO FUSION BUCKET NO 18', 'productPool/1.jpg', 103 ),
( 'CELLO FUSION BUCKET NO 20', 'productPool/1.jpg', 253 ),
( 'CELLO FUSION MUG 1 LTR', 'productPool/1.jpg', 10 ),
( 'CELLO GEL TEC PEN MICKEY MOUSE MRP 10', 'productPool/1.jpg', 226 ),
( 'CELLO GEL TEC SPIDERMAN PEN MRP 10', 'productPool/1.jpg', 213 ),
( 'CELLO GEL TECH FUN GLITTER PEN', 'productPool/1.jpg', 164 ),
( 'CELLO GEL TECK GEL PEN BLACK', 'productPool/1.jpg', 124 ),
( 'CELLO GLITZ BOTTLE 1LT', 'productPool/1.jpg', 129 ),
( 'CELLO GRIPER PEN', 'productPool/1.jpg', 253 ),
( 'CELLO H2O 1000ML', 'productPool/1.jpg', 105 ),
( 'CELLO H2O SQUAREMATE WATER BOTTLE 500ML', 'productPool/1.jpg', 228 ),
( 'CELLO H2O SS BOTTLE 1000ML', 'productPool/1.jpg', 260 ),
( 'CELLO H2O SS FRIDGE BOTTLE 1000ML', 'productPool/1.jpg', 77 ),
( 'CELLO H2O WATER BOTTLE 750ML', 'productPool/1.jpg', 36 ),
( 'CELLO HI LIGHTER', 'productPool/1.jpg', 140 ),
( 'CELLO HI LUNCH BOX', 'productPool/1.jpg', 95 ),
( 'CELLO HYDRA FLIP BOTTLE 750ML', 'productPool/1.jpg', 42 ),
( 'CELLO ICON WATER BOTTLE 600ML', 'productPool/1.jpg', 18 ),
( 'CELLO IMPRESS CONTAINER 1000ML', 'productPool/1.jpg', 137 ),
( 'CELLO IMPRESS CONTAINER 1500ML', 'productPool/1.jpg', 118 ),
( 'CELLO INK MATE FOUNTAIN PEN', 'productPool/1.jpg', 39 ),
( 'CELLO JET BLACK PENCIL', 'productPool/1.jpg', 83 ),
( 'CELLO JOLLY LUNCH BOX', 'productPool/1.jpg', 119 ),
( 'CELLO JUICY JUG 1.25L', 'productPool/1.jpg', 158 ),
( 'CELLO JUICY JUG GIFT SET', 'productPool/1.jpg', 115 ),
( 'CELLO JUICY JUG SET 5 PCS', 'productPool/1.jpg', 112 ),
( 'CELLO JUICY PLUS 1.8ML', 'productPool/1.jpg', 33 ),
( 'CELLO JUST IN BOTTLE 650ML', 'productPool/1.jpg', 120 ),
( 'CELLO KIDS SET 3 PCS FISHER PRICE', 'productPool/1.jpg', 201 ),
( 'CELLO KIDS SET 5 PCS FISHER PRICE', 'productPool/1.jpg', 163 ),
( 'CELLO KLEENO ANGULAR TOILET BRUSH', 'productPool/1.jpg', 151 ),
( 'CELLO KLEENO BATHROOM WIPER 2N', 'productPool/1.jpg', 48 ),
( 'CELLO KLEENO BOTTLE BRUSH', 'productPool/1.jpg', 241 ),
( 'CELLO KLEENO COB WEB BRUSH', 'productPool/1.jpg', 245 ),
( 'CELLO KLEENO COPPERIZED SCRUBBER 4P', 'productPool/1.jpg', 184 ),
( 'CELLO KLEENO DECK MOP 2N', 'productPool/1.jpg', 49 ),
( 'CELLO KLEENO DUAL ACTION SINK BRUSH', 'productPool/1.jpg', 144 ),
( 'CELLO KLEENO DUAL ACTION TOILET BRUSH', 'productPool/1.jpg', 229 ),
( 'CELLO KLEENO DUAL SPONGE SCRUB HANDLE', 'productPool/1.jpg', 273 ),
( 'CELLO KLEENO ECO HOCKEY TOILET BRUSH', 'productPool/1.jpg', 79 ),
( 'CELLO KLEENO ECO ROUND TOILET BRUSH', 'productPool/1.jpg', 47 ),
( 'CELLO KLEENO EX SPONGE PAD', 'productPool/1.jpg', 251 ),
( 'CELLO KLEENO EZEE CLOTH BRUSH', 'productPool/1.jpg', 161 ),
( 'CELLO KLEENO HEAVY DUTY SCRUB PAD', 'productPool/1.jpg', 169 ),
( 'CELLO KLEENO HI CLEAN SPIN MOP', 'productPool/1.jpg', 194 ),
( 'CELLO KLEENO JET MAX SCRUBBER', 'productPool/1.jpg', 149 ),
( 'CELLO KLEENO JET POWER SCRUBBER', 'productPool/1.jpg', 237 ),
( 'CELLO KLEENO JET SCRUBBER', 'productPool/1.jpg', 115 ),
( 'CELLO KLEENO KITCHEN AND GLASS WIPER', 'productPool/1.jpg', 253 ),
( 'CELLO KLEENO MAGIC SCRUB PAD', 'productPool/1.jpg', 87 ),
( 'CELLO KLEENO NO DUST BROOM XL', 'productPool/1.jpg', 63 ),
( 'CELLO KLEENO PLUNGER 1N', 'productPool/1.jpg', 276 ),
( 'CELLO KLEENO POPULAR JUMBO WIPER', 'productPool/1.jpg', 152 ),
( 'CELLO KLEENO POPULAR NANO WIPER', 'productPool/1.jpg', 140 ),
( 'CELLO KLEENO POWER SCRUB PAD', 'productPool/1.jpg', 143 ),
( 'CELLO KLEENO PREMIUM KHARATA', 'productPool/1.jpg', 225 ),
( 'CELLO KLEENO PREMIUM KHARATA LARGE', 'productPool/1.jpg', 156 ),
( 'CELLO KLEENO SCRUB PAD WITH SPONGE', 'productPool/1.jpg', 66 ),
( 'CELLO KLEENO SPONGE WIPES 1N', 'productPool/1.jpg', 9 ),
( 'CELLO KLEENO SPONGE WIPES 3N', 'productPool/1.jpg', 51 ),
( 'CELLO KLEENO STAINLESS SCRUB PAD 12G', 'productPool/1.jpg', 273 ),
( 'CELLO KLEENO STANDEE BATHROOM WIPER', 'productPool/1.jpg', 140 ),
( 'CELLO KLEENO STANDEE BROOM BRUSH', 'productPool/1.jpg', 83 ),
( 'CELLO KLEENO STANDEE HARD TILE BRUSH', 'productPool/1.jpg', 139 ),
( 'CELLO KLEENO SUPER CLEAN SPIN MOP', 'productPool/1.jpg', 163 ),
( 'CELLO KLEENO SWACHH BROOM', 'productPool/1.jpg', 143 ),
( 'CELLO KLEENO TILE SCRUBBER', 'productPool/1.jpg', 134 ),
( 'CELLO KLEENO UNIVERSAL FLOOR WIPER', 'productPool/1.jpg', 227 ),
( 'CELLO KNIT STYLE BASKET-20', 'productPool/1.jpg', 186 ),
( 'CELLO KNIT STYLE BASKET-30', 'productPool/1.jpg', 13 ),
( 'CELLO KNIT STYLE BASKET-40', 'productPool/1.jpg', 245 ),
( 'CELLO KNIT STYLE BASKET-50', 'productPool/1.jpg', 176 ),
( 'CELLO KNIT STYLE BASKET-60', 'productPool/1.jpg', 127 ),
( 'CELLO KNIT STYLE BASKET-70', 'productPool/1.jpg', 13 ),
( 'CELLO KUBIX ICE TRAY 2PC', 'productPool/1.jpg', 186 ),
( 'CELLO LEISURE HOT POT LUNCH BOX 500ML', 'productPool/1.jpg', 99 ),
( 'CELLO LEISURE LUNCH BOX 800ML', 'productPool/1.jpg', 109 ),
( 'CELLO LIFESTYLE SS FLASK 500ML', 'productPool/1.jpg', 221 ),
( 'CELLO LIFESTYLE SS FLASK 750ML', 'productPool/1.jpg', 140 ),
( 'CELLO MAGNA ROUND JAR 1000ML', 'productPool/1.jpg', 102 ),
( 'CELLO MAGNA ROUND JAR 500ML', 'productPool/1.jpg', 246 ),
( 'CELLO MAGNA ROUND JAR 750ML', 'productPool/1.jpg', 146 ),
( 'CELLO MAPLE CANISTER 1L 2PC', 'productPool/1.jpg', 101 ),
( 'CELLO MAPLE CANISTER 500ML 2PC', 'productPool/1.jpg', 272 ),
( 'CELLO MAPLE CANISTER 750ML 2PC', 'productPool/1.jpg', 174 ),
( 'CELLO MAPLE FRIDGE BOTTLE 1L', 'productPool/1.jpg', 76 ),
( 'CELLO MARVEL FOUNTAIN PEN', 'productPool/1.jpg', 95 ),
( 'CELLO MAX FRESH COMPACT LUNCH BOX 2', 'productPool/1.jpg', 147 ),
( 'CELLO MAX FRESH COUNTAINER 100ML', 'productPool/1.jpg', 75 ),
( 'CELLO MAX FRESH ESTELLA 150ML', 'productPool/1.jpg', 270 ),
( 'CELLO MAX FRESH ESTELLA 500ML', 'productPool/1.jpg', 93 ),
( 'CELLO MAX FRESH ESTELLA 800ML', 'productPool/1.jpg', 176 ),
( 'CELLO MAX FRESH HAPPY MEAL', 'productPool/1.jpg', 73 ),
( 'CELLO MAX FRESH OIL DISPENSER 650ML', 'productPool/1.jpg', 35 ),
( 'CELLO MAX FRESH OIL DISPENSER 900ML', 'productPool/1.jpg', 175 ),
( 'CELLO MAX FRESH RECTANGULAR 175ML', 'productPool/1.jpg', 255 ),
( 'CELLO MAX FRESH ROUND 250ML', 'productPool/1.jpg', 211 ),
( 'CELLO MAX FRESH SALAD BOWL', 'productPool/1.jpg', 266 ),
( 'CELLO MAX FRESH SANDWICH BOX', 'productPool/1.jpg', 77 ),
( 'CELLO MAX FRESH SQUARE CONTAINER 550ML', 'productPool/1.jpg', 166 ),
( 'CELLO MAX FRESH THERMI PACK BIG', 'productPool/1.jpg', 270 ),
( 'CELLO MAXFRESH RECTANGULAR CONTAINER 175ML', 'productPool/1.jpg', 196 ),
( 'CELLO MAXFRESH SQUARE CONTAINER 350ML', 'productPool/1.jpg', 119 ),
( 'CELLO MAXFRESH SQUARE CONTAINER 550ML', 'productPool/1.jpg', 203 ),
( 'CELLO MAXFRESH SUPER CLICK 3000ML', 'productPool/1.jpg', 75 ),
( 'CELLO MAXFRESH SUPER CLICK 5000ML', 'productPool/1.jpg', 228 ),
( 'CELLO MAXRITER PEN', 'productPool/1.jpg', 122 ),
( 'CELLO MEDICO BOX', 'productPool/1.jpg', 198 ),
( 'CELLO MINI BIN', 'productPool/1.jpg', 272 ),
( 'CELLO MUNCH BIG LUNCH BOX', 'productPool/1.jpg', 205 ),
( 'CELLO MY GEL PEN', 'productPool/1.jpg', 105 ),
( 'CELLO MY GEL PEN RS 5', 'productPool/1.jpg', 75 ),
( 'CELLO NILE FRIDGE BOTTLE 1LT', 'productPool/1.jpg', 87 ),
( 'CELLO NOVEL 2200ML', 'productPool/1.jpg', 183 ),
( 'CELLO OLIVIA OIL DISPENSER 500ML', 'productPool/1.jpg', 144 ),
( 'CELLO OXY BOTTLE 1LT', 'productPool/1.jpg', 146 ),
( 'CELLO OZONE WATER BOTTLE 1L', 'productPool/1.jpg', 173 ),
( 'CELLO OZONE WATER BOTTLE 1LT', 'productPool/1.jpg', 55 ),
( 'CELLO PAPER SOFT RS 20', 'productPool/1.jpg', 186 ),
( 'CELLO PAPERSOFT BLUE BLACK PEN', 'productPool/1.jpg', 279 ),
( 'CELLO PERMALINE CD MARKER', 'productPool/1.jpg', 19 ),
( 'CELLO PERMALINE CD MARKER RED', 'productPool/1.jpg', 44 ),
( 'CELLO PERMANENT MARKER BLACK', 'productPool/1.jpg', 276 ),
( 'CELLO PERMANENT MARKER BLUE', 'productPool/1.jpg', 231 ),
( 'CELLO PIN POINT BLUE BLACK PEN', 'productPool/1.jpg', 11 ),
( 'CELLO PINPOINT BLACK PEN RS 10', 'productPool/1.jpg', 243 ),
( 'CELLO PINPOINT BLUE RS 10', 'productPool/1.jpg', 35 ),
( 'CELLO PINPOINT XS BLACK RS 10', 'productPool/1.jpg', 263 ),
( 'CELLO PINPOINT XS BLUE RS 10', 'productPool/1.jpg', 244 ),
( 'CELLO POINTEC GEL BLU BLA 20 MRP', 'productPool/1.jpg', 275 ),
( 'CELLO POINTEC GEL BLUE', 'productPool/1.jpg', 202 ),
( 'CELLO POWER FINE BLACK', 'productPool/1.jpg', 223 ),
( 'CELLO PRISM BOTTLE 1LT', 'productPool/1.jpg', 218 ),
( 'CELLO PRISM SS BOTTLE 1000ML', 'productPool/1.jpg', 113 ),
( 'CELLO PRO JUNIOR BOTTLE 600ML', 'productPool/1.jpg', 61 ),
( 'CELLO PURO CURVE WATER BOTTLE 600ML', 'productPool/1.jpg', 114 ),
( 'CELLO PURO JUNIOR 400 BOTTLE', 'productPool/1.jpg', 105 ),
( 'CELLO PURO JUNIOR 600 BOTTLE', 'productPool/1.jpg', 29 ),
( 'CELLO PURO JUNIOR BOTTLE 400ML', 'productPool/1.jpg', 251 ),
( 'CELLO PURO SPORTS WATER BOTTLE 600ML', 'productPool/1.jpg', 161 ),
( 'CELLO PURO STEEL X LEXUS 900ML', 'productPool/1.jpg', 230 ),
( 'CELLO PURO STEEL X LEXUS BOTTLE 600ML', 'productPool/1.jpg', 124 ),
( 'CELLO PURO STEEL X ZEN 900ML', 'productPool/1.jpg', 161 ),
( 'CELLO PURO STEEL X ZEN BOTTLE 600ML', 'productPool/1.jpg', 223 ),
( 'CELLO QUBE BIG', 'productPool/1.jpg', 36 ),
( 'CELLO QUBE FRESH GLASS JAR 1000ML', 'productPool/1.jpg', 57 ),
( 'CELLO QUBE FRESH GLASS JAR 1800ML', 'productPool/1.jpg', 169 ),
( 'CELLO QUBE FRESH GLASS JAR 580ML', 'productPool/1.jpg', 34 ),
( 'CELLO QUBE FRESH JAR 800ML', 'productPool/1.jpg', 82 ),
( 'CELLO QUICK LUNCH BOX BIG', 'productPool/1.jpg', 106 ),
( 'CELLO QUICK LUNCH BOX MEDIUM', 'productPool/1.jpg', 118 ),
( 'CELLO QUICK LUNCH BOX SMALL', 'productPool/1.jpg', 5 ),
( 'CELLO REFRESH WATER BOTTLE 500ML', 'productPool/1.jpg', 136 ),
( 'CELLO RITZ SOAP CASE', 'productPool/1.jpg', 224 ),
( 'CELLO ROTI PLUS 2000ML', 'productPool/1.jpg', 4 ),
( 'CELLO RUGBY FILIP WATER BOTTLE 1000ML', 'productPool/1.jpg', 214 ),
( 'CELLO RUGBY FLIP WATER BOTTLE 600ML', 'productPool/1.jpg', 213 ),
( 'CELLO RUGBY FRIDGE BOTTLE 1LT', 'productPool/1.jpg', 134 ),
( 'CELLO SEAL FRESH JAR 150ML', 'productPool/1.jpg', 181 ),
( 'CELLO SEAL FRESH JAR 300ML', 'productPool/1.jpg', 111 ),
( 'CELLO SEAL O FRESH JAR 1000ML', 'productPool/1.jpg', 38 ),
( 'CELLO SEAL O FRESH JAR 100ML', 'productPool/1.jpg', 268 ),
( 'CELLO SEAL O FRESH JAR 250ML', 'productPool/1.jpg', 111 ),
( 'CELLO SEAL O FRESH JAR 50ML', 'productPool/1.jpg', 16 ),
( 'CELLO SEAL O FRESH JAR 750ML', 'productPool/1.jpg', 193 ),
( 'CELLO SIPWELL MINI BOTTLE 500ML', 'productPool/1.jpg', 223 ),
( 'CELLO SIZZLER 2800ML', 'productPool/1.jpg', 107 ),
( 'CELLO SPEED BLUE RS 6', 'productPool/1.jpg', 107 ),
( 'CELLO SPLASH FLIP 1000ML', 'productPool/1.jpg', 38 ),
( 'CELLO SPLASH FLIP 600ML BOTTLE', 'productPool/1.jpg', 272 ),
( 'CELLO SS DABBA 200ML', 'productPool/1.jpg', 205 ),
( 'CELLO SS DABBA 350ML', 'productPool/1.jpg', 261 ),
( 'CELLO SS DABBA 500ML', 'productPool/1.jpg', 35 ),
( 'CELLO SUMO STOOL BIG', 'productPool/1.jpg', 198 ),
( 'CELLO SUPER B1100 BOTTLE', 'productPool/1.jpg', 167 ),
( 'CELLO SUPER B800 BOTTLE', 'productPool/1.jpg', 50 ),
( 'CELLO SWAG BOTTLE 850 ML', 'productPool/1.jpg', 272 ),
( 'CELLO TECHNO TIP BLACK BLUE PEN', 'productPool/1.jpg', 22 ),
( 'CELLO TECHNO TIP BLACK PEN MRP 10', 'productPool/1.jpg', 272 );