INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'TASTY PLUS GUAVA PULP 3.1 KG', 'productPool/1.jpg', 14 ),
( 'TASTY PLUS PINEAPPLE PULP 3KG', 'productPool/1.jpg', 66 ),
( 'TASTY SAFFOLA TASTY 1L', 'productPool/1.jpg', 46 ),
( 'TATA COFEE GRAND FILTER 50G', 'productPool/1.jpg', 65 ),
( 'TATA COFFEE GRAND 200G', 'productPool/1.jpg', 38 ),
( 'TATA COFFEE GRAND FILTER 100G', 'productPool/1.jpg', 140 ),
( 'TATA GLUCO ENERGY DRINK LEMON 200ML', 'productPool/1.jpg', 141 ),
( 'TATA GLUCO ENERGY DRINK ORANGE 200ML', 'productPool/1.jpg', 277 ),
( 'TATA GLUCO ENERGY DRINKMANGO 200ML', 'productPool/1.jpg', 275 ),
( 'TATA GLUCO PLUS LEMONY ZING DRINK 350ML', 'productPool/1.jpg', 123 ),
( 'TATA GLUCO PLUS ORANGY BURST DRINK 350ML', 'productPool/1.jpg', 158 ),
( 'TATA GOLD TEA 250G', 'productPool/1.jpg', 239 ),
( 'TATA GRAND FILTER COFFEE 500G', 'productPool/1.jpg', 157 ),
( 'TATA I SHAKTI SALT 1KG', 'productPool/1.jpg', 76 ),
( 'TATA KANNAN DEVAN CLASSIC 250G', 'productPool/1.jpg', 174 ),
( 'TATA KANNAN DEVAN CLASSIC 500G', 'productPool/1.jpg', 120 ),
( 'TATA KANNAN DEVAN CLASSIC TEA 1 KG', 'productPool/1.jpg', 104 ),
( 'TATA KANNAN DEVAN GOLDEN LEAF TEA 250G', 'productPool/1.jpg', 125 ),
( 'TATA KANNAN DEVAN GOLDEN LEAF TEA 500G', 'productPool/1.jpg', 96 ),
( 'TATA KANNAN DEVAN STRONG 1KG', 'productPool/1.jpg', 196 ),
( 'TATA KANNAN DEVAN STRONG TEA 250G', 'productPool/1.jpg', 246 ),
( 'TATA KANNAN DEVAN STRONG TEA 500G', 'productPool/1.jpg', 254 ),
( 'TATA KANNAN DEVAN TEA BAG 50', 'productPool/1.jpg', 102 ),
( 'TATA KANNAN DEVAN TEA CLASSIC 100G', 'productPool/1.jpg', 216 ),
( 'TATA SALT 1KG', 'productPool/1.jpg', 198 ),
( 'TATA SALT LITE 1KG', 'productPool/1.jpg', 169 ),
( 'TATA TEA GOLD LEAF 250G', 'productPool/1.jpg', 250 ),
( 'TATAGLUCO GRAPES 200ML', 'productPool/1.jpg', 206 ),
( 'TATTVA ORGANIC SUGAR1KG', 'productPool/1.jpg', 17 ),
( 'TAVETHA NO.1', 'productPool/1.jpg', 121 ),
( 'TAVETHA NO.3', 'productPool/1.jpg', 95 ),
( 'TAYAS GIFT ROUND JESS CHOCOLATE 300G', 'productPool/1.jpg', 86 ),
( 'TAYAS HAMLET 300G', 'productPool/1.jpg', 175 ),
( 'TAYAS LEMONPIE BISCUITS 500G', 'productPool/1.jpg', 169 ),
( 'TAYAS LOVE SPECIAL CHOCOLATE 400G', 'productPool/1.jpg', 25 ),
( 'TAYAS ORANGE 450G', 'productPool/1.jpg', 73 ),
( 'TAYAS ORANGEPIE BISCUITS 500G', 'productPool/1.jpg', 98 ),
( 'TAYAS ORIENT CAPPUCCINO 450GM', 'productPool/1.jpg', 117 ),
( 'TAYAS ORIENT LUXURY 450G', 'productPool/1.jpg', 191 ),
( 'TAYAS ORIENT MANGO 450GM', 'productPool/1.jpg', 89 ),
( 'TAYAS ORIENT STRAWBERRY 300G', 'productPool/1.jpg', 253 ),
( 'TAYAS SHADOW SPECIAL 300G', 'productPool/1.jpg', 175 ),
( 'TAYAS TOFFEE GIFT ROUND SHADOW 300G', 'productPool/1.jpg', 102 ),
( 'TAYAS TOFFEE GIFT SQUARE CARAMEL 300G', 'productPool/1.jpg', 176 ),
( 'TAYAS TOFFEE GIFT SQUARE HAZELNUT 300G', 'productPool/1.jpg', 13 ),
( 'TAYAS TOFFEE GIFT SQUARE ORANGE 300G', 'productPool/1.jpg', 265 ),
( 'TAYAS TOFFEE GIFT SQUARE STRAWBERRY 300G', 'productPool/1.jpg', 204 ),
( 'TAYS ORIENT ORANGE 300G', 'productPool/1.jpg', 94 ),
( 'TE ROASTED MIX SEEDS CHILLI GINGER 125G', 'productPool/1.jpg', 214 ),
( 'TE ROASTED QUINOA MIX SPICY MASALA 100G', 'productPool/1.jpg', 45 ),
( 'TE ROASTED SUNFLOWER CHILLI GARLIC 125G', 'productPool/1.jpg', 248 ),
( 'TE SEEDS GRANOLA HONEY CLUSTERS 125G', 'productPool/1.jpg', 169 ),
( 'TEA DUST 1KG', 'productPool/1.jpg', 205 ),
( 'TEA DUST 250G', 'productPool/1.jpg', 140 ),
( 'TEA DUST 500G', 'productPool/1.jpg', 138 ),
( 'TEA FILTER NO.3', 'productPool/1.jpg', 151 ),
( 'TEA FILTER NO.4', 'productPool/1.jpg', 147 ),
( 'TEA STRAINER NO 2 STEEL NET', 'productPool/1.jpg', 16 ),
( 'TEA STRAINER NO 3', 'productPool/1.jpg', 175 ),
( 'TEA STRAINER NO 3 RUBY', 'productPool/1.jpg', 8 ),
( 'TEA STRAINER RS 85', 'productPool/1.jpg', 125 ),
( 'TEA STRAINER RS90', 'productPool/1.jpg', 200 ),
( 'TEAK BELAN', 'productPool/1.jpg', 7 ),
( 'TEMPTATIONS RUM RAISINS', 'productPool/1.jpg', 133 ),
( 'TERMINOL ANT KILLER 150GM', 'productPool/1.jpg', 184 ),
( 'TERMOCOL 4 INCH TRAY 100PCS', 'productPool/1.jpg', 254 ),
( 'TERMOCOL 4CP TRAY 25P', 'productPool/1.jpg', 245 ),
( 'TERMOCOL PLATE 10 INCH ROUND', 'productPool/1.jpg', 235 ),
( 'TERMOCOL PLATE 10 INCH ROUND 25P', 'productPool/1.jpg', 125 ),
( 'TERMOCOL PLATE 4 INCH DONA 100P', 'productPool/1.jpg', 119 ),
( 'TERMOCOL PLATE 6 INCH ROUND 50P', 'productPool/1.jpg', 248 ),
( 'TERMOCOL PLATE 7 INCH ROUND 50P', 'productPool/1.jpg', 219 ),
( 'TETLEY GREEN TEA 10G', 'productPool/1.jpg', 216 ),
( 'TETLEY GREEN TEA 125G', 'productPool/1.jpg', 17 ),
( 'TETLEY LONG LEAF GREEN TEA 100G', 'productPool/1.jpg', 59 ),
( 'TEXMA DOCTORS BLACK PHENYL 500ML', 'productPool/1.jpg', 96 ),
( 'TEXMA FLOOR CLEANER SANDAL 1LTR', 'productPool/1.jpg', 197 ),
( 'TEXMA GLASS CLEANER 650ML', 'productPool/1.jpg', 206 ),
( 'TEXMA LEMONGRASS WHITE FLOOR CLEANER 1L', 'productPool/1.jpg', 194 ),
( 'TEXMA PREMIUM QUTICURA 1 LT', 'productPool/1.jpg', 177 ),
( 'TEXMA PREMIUM QUTICURA 1LTR', 'productPool/1.jpg', 265 ),
( 'TEXMA PREMIUM ROSE 1LTR', 'productPool/1.jpg', 191 ),
( 'TEXMA PREMIUM ROSE LOTION 1LT', 'productPool/1.jpg', 144 ),
( 'TEXMA PREMIUM SANDAL LOTION 1L', 'productPool/1.jpg', 209 ),
( 'TEXMA PREMIUM YELLOW 1LTR', 'productPool/1.jpg', 115 ),
( 'TEXMA TOILET CLEANER 650ML', 'productPool/1.jpg', 161 ),
( 'TEXMA WHITE FLOOR CLEANER 1L', 'productPool/1.jpg', 199 ),
( 'TEXMA WHITE FLOOR CLEANER SANDAL 1L', 'productPool/1.jpg', 279 ),
( 'TEXMA WHITE JASMINE CLEANER 1L', 'productPool/1.jpg', 229 ),
( 'THADIYAN', 'productPool/1.jpg', 56 ),
( 'THAKKOLAM 17G', 'productPool/1.jpg', 125 ),
( 'THANIMA HONEY BALL 180G', 'productPool/1.jpg', 161 ),
( 'THE HAPPYGROVE EXTRA VIRGINCOCO OIL', 'productPool/1.jpg', 179 ),
( 'THEERAMYTHRI DRIED ANCHOVY 100G', 'productPool/1.jpg', 192 ),
( 'THEERAMYTHRI DRIED LIZARD FISH 100G', 'productPool/1.jpg', 200 ),
( 'THEERAMYTHRI DRIED SHARK 100G', 'productPool/1.jpg', 120 ),
( 'THEERAMYTHRI DRIED SILVER BELLY 100G', 'productPool/1.jpg', 70 ),
( 'THEERAMYTHRI DRIED SOLE 100G', 'productPool/1.jpg', 221 ),
( 'THEERAMYTHRI DRY PRAWNS 50G', 'productPool/1.jpg', 85 ),
( 'THEJAS PAPPDAM 175G PKT', 'productPool/1.jpg', 69 ),
( 'THEJAS PAPPDAM 220G PKT', 'productPool/1.jpg', 242 ),
( 'THEJAS PUNJABI MASALA PAPPADAM 220G', 'productPool/1.jpg', 240 ),
( 'THINA 500G', 'productPool/1.jpg', 99 ),
( 'THINAI 500G', 'productPool/1.jpg', 54 ),
( 'THREAD', 'productPool/1.jpg', 32 ),
( 'THREAD CUTTER', 'productPool/1.jpg', 234 ),
( 'THREAD CUTTER RS16', 'productPool/1.jpg', 15 ),
( 'THUMS UP 300ML', 'productPool/1.jpg', 42 ),
( 'THYME LEAF 25G', 'productPool/1.jpg', 55 ),
( 'TIC TAC APPLE', 'productPool/1.jpg', 236 ),
( 'TIC TAC COCA COLA 7.7G', 'productPool/1.jpg', 24 ),
( 'TIC TAC FEN MINIT MRP10', 'productPool/1.jpg', 129 ),
( 'TIC TAC FEN MINT SAUNF FLAVOUR', 'productPool/1.jpg', 9 ),
( 'TIC TAC INTENSER MILD MINT 15.5G', 'productPool/1.jpg', 165 ),
( 'TIC TAC MELON WATERMELON', 'productPool/1.jpg', 250 ),
( 'TIC TAC MINT', 'productPool/1.jpg', 274 ),
( 'TIC TAC MINT 7.7G', 'productPool/1.jpg', 163 ),
( 'TIC TAC MINT REFILLS', 'productPool/1.jpg', 244 ),
( 'TIC TAC ORANGE 7.7G', 'productPool/1.jpg', 148 ),
( 'TIC TAC ORANGE RS 10', 'productPool/1.jpg', 24 ),
( 'TIC TAC RAW MANGO 7.7G', 'productPool/1.jpg', 277 ),
( 'TIC TAC RED APPLE 7.7G', 'productPool/1.jpg', 154 ),
( 'TIC TAC SAUNF FLAVOUR 7.7 G', 'productPool/1.jpg', 35 ),
( 'TIC TAC STAWBERRY MIX 15.5G', 'productPool/1.jpg', 155 ),
( 'TIC TAC STRAWBERRY 15', 'productPool/1.jpg', 260 ),
( 'TICTAC CARDAMOM RS 10', 'productPool/1.jpg', 155 ),
( 'TIDE BAR 170G', 'productPool/1.jpg', 133 ),
( 'TIDE BAR 75G', 'productPool/1.jpg', 231 ),
( 'TIDE JAMINE ROSE 6KG-2KG', 'productPool/1.jpg', 219 ),
( 'TIDE JASMINE & ROSE 2KG', 'productPool/1.jpg', 128 ),
( 'TIDE JASMINE ROSE 1KG', 'productPool/1.jpg', 100 ),
( 'TIDE JASMINE ROSE 2KG', 'productPool/1.jpg', 103 ),
( 'TIDE JASMINE ROSE 4+1KG', 'productPool/1.jpg', 123 ),
( 'TIDE JASMINE ROSE 4KG+1KG', 'productPool/1.jpg', 63 ),
( 'TIDE JASMINE ROSE 500G', 'productPool/1.jpg', 135 ),
( 'TIDE JASMINE ROSE 5KG', 'productPool/1.jpg', 267 ),
( 'TIDE JASMINE ROSE 6+2 KG', 'productPool/1.jpg', 94 ),
( 'TIDE JASMINE ROSE 6KG + 2KG', 'productPool/1.jpg', 51 ),
( 'TIDE JASMINE ROSE 8KG', 'productPool/1.jpg', 84 ),
( 'TIDE LADUNDRY BAR 200GM', 'productPool/1.jpg', 189 ),
( 'TIDE LAUNDRY BAR 150G', 'productPool/1.jpg', 244 ),
( 'TIDE LAUNDRY BAR 250G', 'productPool/1.jpg', 49 ),
( 'TIDE LAUNDRY BAR 5*200G', 'productPool/1.jpg', 56 ),
( 'TIDE LEMON 5KG BUCKET FREE', 'productPool/1.jpg', 237 ),
( 'TIDE LEMON MINT 1KG', 'productPool/1.jpg', 89 ),
( 'TIDE LEMON MINT 2KG', 'productPool/1.jpg', 68 ),
( 'TIDE LEMON MINT 4-1KG', 'productPool/1.jpg', 254 ),
( 'TIDE LEMON MINT 4KG+1KG', 'productPool/1.jpg', 34 ),
( 'TIDE LEMON MINT 500G', 'productPool/1.jpg', 158 ),
( 'TIDE LEMON MINT 6 + 2 KG', 'productPool/1.jpg', 17 ),
( 'TIDE LEMON MINT 6KG +2KG', 'productPool/1.jpg', 46 ),
( 'TIDE NATURALS 500G', 'productPool/1.jpg', 270 ),
( 'TIDE NATURALS 800G', 'productPool/1.jpg', 225 ),
( 'TIDE PLUS 6KG', 'productPool/1.jpg', 109 ),
( 'TIDE PLUS JASMINE ROSE 500G', 'productPool/1.jpg', 59 ),
( 'TIDE PLUS JASMINE ROSE 6KG', 'productPool/1.jpg', 82 ),
( 'TIDE PLUS JASMINE- ROSE 1KG', 'productPool/1.jpg', 259 ),
( 'TIDE PLUS LEMON MINT 1KG', 'productPool/1.jpg', 177 ),
( 'TIDE PLUS LEMON MINT 4+1 KG', 'productPool/1.jpg', 131 ),
( 'TIDE ULTRA 3 IN 1 CLEAN 1KG', 'productPool/1.jpg', 22 ),
( 'TIDE ULTRA 3 IN 1 CLEAN 2KG', 'productPool/1.jpg', 103 ),
( 'TIDE ULTRA 3 IN 1 CLEAN 4KG', 'productPool/1.jpg', 120 ),
( 'TIDE ULTRA 3 IN 1 CLEAN 500G', 'productPool/1.jpg', 200 ),
( 'TIDE ULTRA MATIC 1KG', 'productPool/1.jpg', 186 ),
( 'TIDE ULTRA MATIC 2KG', 'productPool/1.jpg', 221 ),
( 'TIDE ULTRA MATIC 4KG', 'productPool/1.jpg', 241 ),
( 'TIERRA KAPPO CHIPS TANGY TOMATO 36G', 'productPool/1.jpg', 110 ),
( 'TIFFANY BUTTER TOFFEE 700G', 'productPool/1.jpg', 176 ),
( 'TIFFANY CREAM 350G', 'productPool/1.jpg', 23 ),
( 'TIFFANY CREAM 700G', 'productPool/1.jpg', 31 ),
( 'TIFFANY CREAM ORANGE 150G', 'productPool/1.jpg', 232 ),
( 'TIFFANY CRUNCH CHOCOLATE', 'productPool/1.jpg', 32 ),
( 'TIFFANY CRUNCH N CREAM 150G', 'productPool/1.jpg', 173 ),
( 'TIFFANY DEL TOFEE 300G', 'productPool/1.jpg', 133 ),
( 'TIFFANY DELUXE 350G IMP', 'productPool/1.jpg', 181 ),
( 'TIFFANY DELUXE 700G IMP', 'productPool/1.jpg', 219 ),
( 'TIFFANY DELUXE IMP350G', 'productPool/1.jpg', 249 ),
( 'TIFFANY DELUXE TOFFEE 350G', 'productPool/1.jpg', 92 ),
( 'TIFFANY ECLAIRS 300G', 'productPool/1.jpg', 242 ),
( 'TIFFANY ECLAIRS 700G', 'productPool/1.jpg', 188 ),
( 'TIFFANY ECLAIRS IMP 350G', 'productPool/1.jpg', 84 ),
( 'TIFFANY ECLAIRS IMP 600G', 'productPool/1.jpg', 219 ),
( 'TIFFANY FRUITEES TOFFEE 700G', 'productPool/1.jpg', 12 ),
( 'TIFFANY FUDGE 600GM', 'productPool/1.jpg', 13 ),
( 'TIFFANY STRBERY CREAM 150G', 'productPool/1.jpg', 158 ),
( 'TIFFANY VANILA CREAM WAFFERS 150G', 'productPool/1.jpg', 234 ),
( 'TIFFANY WAFFER HAZELNUT 75G', 'productPool/1.jpg', 223 ),
( 'TIFFANY WAFFER ORANGE 75GM', 'productPool/1.jpg', 5 ),
( 'TIFFANY ZOOM FRUIT CANDY 700G', 'productPool/1.jpg', 188 ),
( 'TIGER APPLE GREEN FOOD COLOUR 10G', 'productPool/1.jpg', 114 ),
( 'TIGER BALM 21ML WHITE', 'productPool/1.jpg', 227 ),
( 'TIGER BALM 9ML WHITE', 'productPool/1.jpg', 63 ),
( 'TIGER BIRIYANI ESSENCE', 'productPool/1.jpg', 168 ),
( 'TIGER BLAM 21ML RED', 'productPool/1.jpg', 245 ),
( 'TIGER BLAM 9ML RED', 'productPool/1.jpg', 86 ),
( 'TIGER KREEMZ CHOCO 100G', 'productPool/1.jpg', 234 ),
( 'TIGER KREEMZ ELAICHI 100G', 'productPool/1.jpg', 236 ),
( 'TIGER KREEMZ PINEAPPLE 100G', 'productPool/1.jpg', 197 ),
( 'TIGER LEMON YELLOW COLOUR 10G', 'productPool/1.jpg', 231 ),
( 'TIGER LEMON YELOW 10G', 'productPool/1.jpg', 275 ),
( 'TIGER ORANGE FOOD COLOUR 10G', 'productPool/1.jpg', 66 ),
( 'TIGER PINEAPPLE ESSENCE 20ML', 'productPool/1.jpg', 257 ),
( 'TIGER PISTA ELACHI MIX 20ML', 'productPool/1.jpg', 272 ),
( 'TIGER ROSE MIX CONCENTRATE 20ML', 'productPool/1.jpg', 66 ),
( 'TIGER STRAWBERRY 20ML', 'productPool/1.jpg', 259 ),
( 'TIGER TRIGER KRUNCH CHOCO 70G FP', 'productPool/1.jpg', 67 ),
( 'TILDA EXTRA LONG BASMATI 1KG', 'productPool/1.jpg', 19 ),
( 'TILDA HIMSHALI LONG BASMATI 1KG', 'productPool/1.jpg', 197 ),
( 'TILDA KHUSH BASMATI RICE 1KG', 'productPool/1.jpg', 271 ),
( 'TILDA NAZARANA BASMATI RICE 1KG', 'productPool/1.jpg', 42 ),
( 'TILDA PURE BASMATI RICE 1KG', 'productPool/1.jpg', 136 ),
( 'TILDA RICE BRAN OIL 1L', 'productPool/1.jpg', 55 ),
( 'TILDA WANDAFUL PREMIUM BASMATI1KG', 'productPool/1.jpg', 81 ),
( 'TIME PASS SNACKS', 'productPool/1.jpg', 111 ),
( 'TIMOTEI SHINE RECHARGE SHAMPOO 400ML', 'productPool/1.jpg', 137 ),
( 'TIMOTEI STENGTH & SHINE SHAMPOO 400ML', 'productPool/1.jpg', 7 ),
( 'TIN CUTTER EX', 'productPool/1.jpg', 40 ),
( 'TNPL COPIER A4 PAPER 70GSM', 'productPool/1.jpg', 121 ),
( 'TNPL COPIER PAPER 80GSM', 'productPool/1.jpg', 109 ),
( 'TOBLERONE 100G', 'productPool/1.jpg', 7 ),
( 'TOBLERONE CHOCLATE ALMOND 100G', 'productPool/1.jpg', 133 ),
( 'TOBLERONE CHOCLATE FRUIT AND NUT 100G', 'productPool/1.jpg', 43 ),
( 'TOFEEMAN PINEAPPLE CHOCLATE 400G', 'productPool/1.jpg', 165 ),
( 'TOFFEEMAN BUTTER TOFFEE 500G', 'productPool/1.jpg', 23 ),
( 'TOFFEEMAN BUTTER TOFFEES 350G', 'productPool/1.jpg', 147 ),
( 'TOFFEEMAN COCONUT BITE RS 100', 'productPool/1.jpg', 274 ),
( 'TOFFEEMAN MILKY MUNCH 400G', 'productPool/1.jpg', 243 ),
( 'TOILET BRUSH ROUND', 'productPool/1.jpg', 220 ),
( 'TOILET BRUSH RS 40', 'productPool/1.jpg', 253 ),
( 'TOILET BRUSH RS120', 'productPool/1.jpg', 246 ),
( 'TOILET BRUSH RS75', 'productPool/1.jpg', 229 ),
( 'TOM WHITE', 'productPool/1.jpg', 171 ),
( 'TOMATO', 'productPool/1.jpg', 226 ),
( 'TOMATO KETCH UP 200G', 'productPool/1.jpg', 41 ),
( 'TOMATO KICTCHENUP900G', 'productPool/1.jpg', 143 ),
( 'TOMATO SAUCE 200G', 'productPool/1.jpg', 214 ),
( 'TONGUE CLEANER', 'productPool/1.jpg', 248 ),
( 'TONGUE CLEANER PLASTIC', 'productPool/1.jpg', 199 ),
( 'TONGUE CLEANER RS18', 'productPool/1.jpg', 200 ),
( 'TONGUE CLEANER RS27', 'productPool/1.jpg', 154 ),
( 'TONGUE CLEANER RS4', 'productPool/1.jpg', 142 ),
( 'TONGUE CLEANER RS83', 'productPool/1.jpg', 97 ),
( 'TONKITA ARIX CLOTH WASHING BRUSH', 'productPool/1.jpg', 30 ),
( 'TONKITA MINI DUST PAN WITH BRUSH', 'productPool/1.jpg', 33 ),
( 'TOOL KNIFE', 'productPool/1.jpg', 117 ),
( 'TOOL KNIFE RS12', 'productPool/1.jpg', 122 ),
( 'TOOTH BRUSH HOLDER 2P', 'productPool/1.jpg', 122 ),
( 'TOOTH BRUSH HOLDER 3P', 'productPool/1.jpg', 128 ),
( 'TOOTH PICK', 'productPool/1.jpg', 102 ),
( 'TOOTH PICK RS 12', 'productPool/1.jpg', 169 ),
( 'TOOTH PICK RS 13', 'productPool/1.jpg', 63 ),
( 'TOOTH PICK RS 16', 'productPool/1.jpg', 202 ),
( 'TOOTH PICK RS 7', 'productPool/1.jpg', 64 ),
( 'TOOTH PICK RS 9.50', 'productPool/1.jpg', 242 ),
( 'TOOTH PICK RS11', 'productPool/1.jpg', 90 ),
( 'TOOTH PICK RS24', 'productPool/1.jpg', 158 ),
( 'TOOTH PICK RS27', 'productPool/1.jpg', 127 ),
( 'TOOTH PICK RS5', 'productPool/1.jpg', 54 ),
( 'TOOTH PICK RS5.50', 'productPool/1.jpg', 256 ),
( 'TOP RAMEN CHICKEN CURRY NOODLES 280G', 'productPool/1.jpg', 223 ),
( 'TOP RAMEN CHICKEN NOODLES 280G', 'productPool/1.jpg', 140 ),
( 'TOP RAMEN CHILLY NOODLES 280GM', 'productPool/1.jpg', 102 ),
( 'TOP RAMEN CUP NOODLES PANEER BUTTER 70G', 'productPool/1.jpg', 103 ),
( 'TOP RAMEN CUP NOODLES TANGY TOMATO 70G', 'productPool/1.jpg', 7 ),
( 'TOP RAMEN FIERY CHILLI NOODLES 70G', 'productPool/1.jpg', 1 ),
( 'TOP RAMEN MASALA NOODLES 30G', 'productPool/1.jpg', 261 ),
( 'TOP RAMEN MASALA NOODLES 560G', 'productPool/1.jpg', 170 ),
( 'TOP RAMEN MASALA NOODLES 70G', 'productPool/1.jpg', 227 ),
( 'TOP RAMEN NOODLES 280GM FAMILY MASLA', 'productPool/1.jpg', 184 ),
( 'TOP RAMEN NOODLES CHICKEN 70GM', 'productPool/1.jpg', 123 ),
( 'TOP RAMEN NOODLES CURRY VEG 280G', 'productPool/1.jpg', 202 ),
( 'TOP RAMEN NOODLES MASALA 140G', 'productPool/1.jpg', 146 ),
( 'TOPRAMEN STUFFD MASALA 30G', 'productPool/1.jpg', 244 ),
( 'TORTO MAGIC STICK CHOCO CEREAM 40G', 'productPool/1.jpg', 42 ),
( 'TORTO MAGIC STICK HAZELNUT CEREAM 40G', 'productPool/1.jpg', 54 ),
( 'TORTO MAGIC STICK STRAWBERRY CEREAM 40G', 'productPool/1.jpg', 45 ),
( 'TORTO MAGIC STICK VANILLA CEREAM 40G', 'productPool/1.jpg', 131 ),
( 'TOTEM BALL PEN BLACK', 'productPool/1.jpg', 180 ),
( 'TOTEM SKETCH PEN', 'productPool/1.jpg', 50 ),
( 'TOTEM SKETCHPEN RS15', 'productPool/1.jpg', 210 ),
( 'TOTEM ZXI SKETCH PEN', 'productPool/1.jpg', 133 ),
( 'TOWEL 12*18', 'productPool/1.jpg', 30 ),
( 'TOWEL 18*18', 'productPool/1.jpg', 128 ),
( 'TOWEL 18*28', 'productPool/1.jpg', 105 ),
( 'TOWEL PLAIN 12*12', 'productPool/1.jpg', 105 ),
( 'TOWEL PLAIN 9*9', 'productPool/1.jpg', 212 ),
( 'TOY CANDY IMP', 'productPool/1.jpg', 217 ),
( 'TRAIN B/O138-1', 'productPool/1.jpg', 21 ),
( 'TRANSPARENT MOULD MUG 1500ML', 'productPool/1.jpg', 235 ),
( 'TRANSPARENT MUG MOULD 1000ML', 'productPool/1.jpg', 34 ),
( 'TRAY BIG', 'productPool/1.jpg', 276 ),
( 'TRAY SMALL', 'productPool/1.jpg', 251 ),
( 'TREAT BURST CHOCO 60G', 'productPool/1.jpg', 249 ),
( 'TREAT CHOCOLATE 64G', 'productPool/1.jpg', 212 ),
( 'TREAT STRAWBERRY 64G', 'productPool/1.jpg', 268 ),
( 'TRESEMME CLIMATE CONTROL CONDITIONER 80ML', 'productPool/1.jpg', 95 ),
( 'TRESEMME CLIMATE CONTROL SHAMPOO 85ML', 'productPool/1.jpg', 29 ),
( 'TRESEMME CLIMATE PROTECTION SHAMPOO 200ML', 'productPool/1.jpg', 265 ),
( 'TRESEMME HAIR FALL 85ML', 'productPool/1.jpg', 21 ),
( 'TRESEMME HAIR FALL DEFENCE CONDITIONER 90ML', 'productPool/1.jpg', 88 ),
( 'TRESEMME HAIR FALL DEFENSE190ML', 'productPool/1.jpg', 173 ),
( 'TRESEMME HAIRFALL DEFENCE CONDITIONER 80ML', 'productPool/1.jpg', 252 ),
( 'TRESEMME KERATIN SMOOTH SHAMPOO', 'productPool/1.jpg', 148 ),
( 'TRESEMME KERATIN SMOOTH SHAMPOO 580ML', 'productPool/1.jpg', 139 ),
( 'TRESEMME NOURISH REPLENISH 190ML', 'productPool/1.jpg', 255 ),
( 'TRESEMME NOURISH REPLENISH 80ML', 'productPool/1.jpg', 8 ),
( 'TRESEMME SMOOTH & SHINE SHAMPOO 190ML', 'productPool/1.jpg', 272 ),
( 'TRESEMME SMOOTH AND SHINE 80ML', 'productPool/1.jpg', 79 ),
( 'TRESEMME SMOOTH&SHIBNE CONDITIONER 85ML', 'productPool/1.jpg', 261 ),
( 'TRESEMME SMOOTH&SHINE CONDITONER 80ML', 'productPool/1.jpg', 104 ),
( 'TRESEMME SPA REJUVENATION SHAMPOO 200ML', 'productPool/1.jpg', 26 ),
( 'TRESMME HAIRFALL DEFENSE SHAMPOO 580ML', 'productPool/1.jpg', 240 ),
( 'TROP FRUTZ LYCHEE 350ML', 'productPool/1.jpg', 279 ),
( 'TROPICANA APPLE DELIGHT 1LTR', 'productPool/1.jpg', 256 ),
( 'TROPICANA APPLE DELIGHT 200ML', 'productPool/1.jpg', 34 ),
( 'TROPICANA CRANBERY 1LTR', 'productPool/1.jpg', 160 ),
( 'TROPICANA DELIGHT ORANGE JUICE 200ML', 'productPool/1.jpg', 6 ),
( 'TROPICANA ESSENTIALS FRUIT AND VEGG 1L', 'productPool/1.jpg', 135 ),
( 'TROPICANA ESSENTIALS FRUIT AND VEGG 200ML', 'productPool/1.jpg', 222 ),
( 'TROPICANA ESSENTIALS IRON 200ML', 'productPool/1.jpg', 149 ),
( 'TROPICANA FRUITS APPLE 350ML', 'productPool/1.jpg', 62 ),
( 'TROPICANA FRUITZ ORANGE 250ML PET', 'productPool/1.jpg', 232 ),
( 'TROPICANA FRUTZ APPLE 250ML', 'productPool/1.jpg', 47 ),
( 'TROPICANA FRUTZ MANGO 250ML', 'productPool/1.jpg', 227 ),
( 'TROPICANA GOLD APPLE JUICE 1LTR', 'productPool/1.jpg', 207 ),
( 'TROPICANA GOLD MIXEDFRUIT JUIICE 1LTR', 'productPool/1.jpg', 24 ),
( 'TROPICANA GOLD ORANGE 1LTR TET', 'productPool/1.jpg', 171 ),
( 'TROPICANA GRAPE JUICE 1LTR', 'productPool/1.jpg', 209 ),
( 'TROPICANA GUAVA 200ML', 'productPool/1.jpg', 277 ),
( 'TROPICANA GUAVA 200ML PET', 'productPool/1.jpg', 190 ),
( 'TROPICANA GUAVA DELIGHT 1LTR', 'productPool/1.jpg', 217 ),
( 'TROPICANA LITCHI 200ML PET', 'productPool/1.jpg', 225 ),
( 'TROPICANA LYCHEE 200ML', 'productPool/1.jpg', 260 ),
( 'TROPICANA LYCHEE TET 1LTR', 'productPool/1.jpg', 240 ),
( 'TROPICANA MANGO 1LTR PET', 'productPool/1.jpg', 90 ),
( 'TROPICANA MANGO 200 ML', 'productPool/1.jpg', 64 ),
( 'TROPICANA MIXED FRUIT 1 L', 'productPool/1.jpg', 112 ),
( 'TROPICANA MIXFRUIT 200ML', 'productPool/1.jpg', 249 ),
( 'TROPICANA ORANGE 200ML', 'productPool/1.jpg', 237 ),
( 'TROPICANA ORANGE 200ML PET', 'productPool/1.jpg', 215 ),
( 'TROPICANA ORANGE DELIGHT 1LTR', 'productPool/1.jpg', 189 ),
( 'TROPICANA PINEAPPLE DELIGHT 200ML', 'productPool/1.jpg', 42 ),
( 'TROPICANA PINEAPPLE JUICE 1LTR', 'productPool/1.jpg', 90 ),
( 'TROPICANA POMEGRANAT 1LTR', 'productPool/1.jpg', 271 ),
( 'TROPICANA POMEGRANATE 200ML', 'productPool/1.jpg', 25 ),
( 'TROPICANA SLICE 1.75LTR', 'productPool/1.jpg', 26 ),
( 'TROPICANA SLICE 200ML', 'productPool/1.jpg', 108 ),
( 'TROPICANA SLICE 250ML PET', 'productPool/1.jpg', 100 ),
( 'TRUBIO ORGANIC BLACK PEPPER POWDER 75G', 'productPool/1.jpg', 81 ),
( 'TRUBIO ORGANIC CLOVE 40G', 'productPool/1.jpg', 74 ),
( 'TRUBIO ORGANIC CLOVE 50G', 'productPool/1.jpg', 47 ),
( 'TRUBIO ORGANIC GREEN TEA 200G', 'productPool/1.jpg', 42 ),
( 'TRUCK 27-4-290', 'productPool/1.jpg', 17 ),
( 'TRUE ELEMENTS ANTIOXIDANT MIX 125G', 'productPool/1.jpg', 97 ),
( 'TRUE ELEMENTS APPLE CIDER VINEGAR 500ML', 'productPool/1.jpg', 147 ),
( 'TRUE ELEMENTS CHIA BASIL RAW SEEDS 150G', 'productPool/1.jpg', 244 ),
( 'TRUE ELEMENTS CHIA RAW SEEDS 150G', 'productPool/1.jpg', 193 ),
( 'TRUE ELEMENTS DRIED BLUEBERRIES 125G', 'productPool/1.jpg', 105 ),
( 'TRUE ELEMENTS DRIED WHOLE CRANBERRIES 125G', 'productPool/1.jpg', 22 ),
( 'TRUE ELEMENTS DRIED WHOLE CRANBERRIES 30G', 'productPool/1.jpg', 159 ),
( 'TRUE ELEMENTS FLAX RAW SEEDS 250G', 'productPool/1.jpg', 204 ),
( 'TRUE ELEMENTS MUESLI CRANBERRY BLUBERRY 400G', 'productPool/1.jpg', 159 ),
( 'TRUE ELEMENTS MUESLI FRUIT AND NUT 400G', 'productPool/1.jpg', 101 ),
( 'TRUE ELEMENTS MUESLI NO ADDED SUGAR 400G', 'productPool/1.jpg', 192 ),
( 'TRUE ELEMENTS MUESLI SEEDS AND BERRIES 400G', 'productPool/1.jpg', 93 ),
( 'TRUE ELEMENTS MUESLI STRAWBERRY 400G', 'productPool/1.jpg', 20 ),
( 'TRUE ELEMENTS PROTEIN MIX 125G', 'productPool/1.jpg', 207 ),
( 'TRUE ELEMENTS PUMPKIN HONEY CLUSTERS 125G', 'productPool/1.jpg', 86 ),
( 'TRUE ELEMENTS PUMPKIN RAW SEEDS 150G', 'productPool/1.jpg', 115 ),
( 'TRUE ELEMENTS RAW HONEY 350G', 'productPool/1.jpg', 169 ),
( 'TRUE ELEMENTS ROASTED CHIA 145G', 'productPool/1.jpg', 85 ),
( 'TRUE ELEMENTS ROASTED FLAX SEEDS 125G', 'productPool/1.jpg', 153 ),
( 'TRUE ELEMENTS ROASTED PUMPKIN SEEDS 125G', 'productPool/1.jpg', 181 ),
( 'TRUE ELEMENTS ROASTED SUNFLOWER 125G', 'productPool/1.jpg', 191 ),
( 'TRUE ELEMENTS ROASTED WATERMELON 125G', 'productPool/1.jpg', 274 ),
( 'TRUE ELEMENTS ROLLED OATS 500G', 'productPool/1.jpg', 118 ),
( 'TRUE ELEMENTS STEEL CUT OATS 500G', 'productPool/1.jpg', 21 ),
( 'TRUE ELEMENTS SUNFLOWER RAW SEEDS 150G', 'productPool/1.jpg', 180 ),
( 'TRUE LONG VERMICELLI 400G', 'productPool/1.jpg', 145 ),
( 'TRUE NORTH GINGER BEER 330ML', 'productPool/1.jpg', 100 ),
( 'TRUFFLE COCONUT CHOCOLATE 300G', 'productPool/1.jpg', 263 ),
( 'TRUFFLE IMP 500G', 'productPool/1.jpg', 163 ),
( 'TRUFFLE MANGO CHOCOLATE 600G', 'productPool/1.jpg', 120 ),
( 'TRUTONE HAIR DYE 7.5G', 'productPool/1.jpg', 189 ),
( 'TUBIFEX WORMS 12G TIN', 'productPool/1.jpg', 62 ),
( 'TUFA ALFA WATER BOTTLE 500ML', 'productPool/1.jpg', 192 ),
( 'TUFF ALFA FLASK 750ML', 'productPool/1.jpg', 53 ),
( 'TUFF FLASK 350ML', 'productPool/1.jpg', 174 ),
( 'TULIPS COTTON BUDS', 'productPool/1.jpg', 272 ),
( 'TULIPS EAR BUDS JAR', 'productPool/1.jpg', 263 ),
( 'TULSI ALMOND', 'productPool/1.jpg', 246 ),
( 'TUNA CHUNKS WATER&SALT 185G', 'productPool/1.jpg', 232 ),
( 'TUNA CROCKET', 'productPool/1.jpg', 177 ),
( 'TUNA ROLL', 'productPool/1.jpg', 153 ),
( 'TURBO JEEP', 'productPool/1.jpg', 271 ),
( 'TURKEL DRIED APRICOTS 200G', 'productPool/1.jpg', 32 ),
( 'TURKEY MILK CHOCOLATE 340G', 'productPool/1.jpg', 101 ),
( 'TURKY PURE OLIVE OIL 100ML RED', 'productPool/1.jpg', 251 ),
( 'TUTIFRUITY RED BOX', 'productPool/1.jpg', 160 ),
( 'TUTY FROOTY', 'productPool/1.jpg', 116 ),
( 'TUTYFRUITY GREEN BOX', 'productPool/1.jpg', 107 ),
( 'TUTYFRUITY YELLOW BOX', 'productPool/1.jpg', 86 ),
( 'TVS SEWING NEEDLE', 'productPool/1.jpg', 263 ),
( 'TWEETY BANK', 'productPool/1.jpg', 48 ),
( 'TWIST STAR BIG WATER BOTTLE', 'productPool/1.jpg', 191 ),
( 'TWISTED CANDLE', 'productPool/1.jpg', 137 ),
( 'TWISTER CHOCA 320 G', 'productPool/1.jpg', 256 ),
( 'TWISTER GIFT PACK CHOCOLATERS 200', 'productPool/1.jpg', 158 ),
( 'TWIX CHOCOLATE50G', 'productPool/1.jpg', 178 ),
( 'U.S.PEANUT BUTTER IMP', 'productPool/1.jpg', 227 ),
( 'UDUPPY POORI', 'productPool/1.jpg', 194 ),
( 'UDUPY CHAPPATHY', 'productPool/1.jpg', 20 ),
( 'UJALA CRISP & SHINE 100G', 'productPool/1.jpg', 199 ),
( 'UJALA CRISP & SHINE JASMINE 100ML', 'productPool/1.jpg', 194 ),
( 'UJALA CRISP & SHINE JASMINE 200ML', 'productPool/1.jpg', 108 ),
( 'UJALA CRISP AND SHINE 15G', 'productPool/1.jpg', 200 ),
( 'UJALA CRISP AND SHINE 1L', 'productPool/1.jpg', 238 ),
( 'UJALA CRISP BLOSSOM 500G', 'productPool/1.jpg', 22 ),
( 'UJALA CRISP SHINE JASMINE 500ML', 'productPool/1.jpg', 208 ),
( 'UJALA CRISP& SHINE FRESH BLOSSOM 200G', 'productPool/1.jpg', 7 ),
( 'UJALA CRISP&SHINE FRESH BLOSSOM 100GM', 'productPool/1.jpg', 26 ),
( 'UJALA CRUST&SHINE 500ML', 'productPool/1.jpg', 158 ),
( 'UJALA DETERGENT POWDER 115ML', 'productPool/1.jpg', 155 ),
( 'UJALA DETERGENT WASHING POWDER 1 KG', 'productPool/1.jpg', 14 ),
( 'UJALA DETERGENT WASHING POWDER 4KG', 'productPool/1.jpg', 5 ),
( 'UJALA DETERGENT WASHING POWDER 500GMS', 'productPool/1.jpg', 273 ),
( 'UJALA FAST WASH LAUNDRY SOAP 150G', 'productPool/1.jpg', 41 ),
( 'UJALA POWDER 575G', 'productPool/1.jpg', 10 ),
( 'UJALA SOAP 150G', 'productPool/1.jpg', 241 ),
( 'UJALA SUPREME 250ML', 'productPool/1.jpg', 274 ),
( 'UJALA SUPREME 30 ML', 'productPool/1.jpg', 170 ),
( 'UJALA SUPREME 75ML', 'productPool/1.jpg', 54 ),
( 'ULLI PAKKODA', 'productPool/1.jpg', 162 ),
( 'ULLI POOVU', 'productPool/1.jpg', 72 ),
( 'ULTIMATE POWER DETERGENT CAKE 200G', 'productPool/1.jpg', 271 ),
( 'ULTIMATE POWER DETERGENT CAKE 250G', 'productPool/1.jpg', 6 ),
( 'ULUVA 100 GMS', 'productPool/1.jpg', 81 ),
( 'ULUVA 200G', 'productPool/1.jpg', 124 ),
( 'UMBRELLA', 'productPool/1.jpg', 116 ),
( 'UMIKKARI 30G', 'productPool/1.jpg', 164 ),
( 'UMIKKARI 30GM', 'productPool/1.jpg', 84 ),
( 'UNAKKALARI 500G', 'productPool/1.jpg', 221 ),
( 'UNDA MULAKU', 'productPool/1.jpg', 5 ),
( 'UNDA SARKARA RED 1KG', 'productPool/1.jpg', 60 ),
( 'UNIBIC BUTTER COOKIES 150GM', 'productPool/1.jpg', 226 ),
( 'UNIBIC BUTTER COOKIES 75G', 'productPool/1.jpg', 132 ),
( 'UNIBIC BUTTERLY COOKIES 120G', 'productPool/1.jpg', 18 ),
( 'UNIBIC CASHEW COOKIES 150G', 'productPool/1.jpg', 133 ),
( 'UNIBIC CASHEW COOKIES 75G', 'productPool/1.jpg', 33 ),
( 'UNIBIC CHCO RIPPLE COOKIES 120G', 'productPool/1.jpg', 89 ),
( 'UNIBIC CHILLI COOKES150G', 'productPool/1.jpg', 218 ),
( 'UNIBIC CHOCO CHIP 75G', 'productPool/1.jpg', 209 ),
( 'UNIBIC CHOCO CHIP COOKIES MRP:10', 'productPool/1.jpg', 15 ),
( 'UNIBIC CHOCO HAZELNUT COOKIES 200G', 'productPool/1.jpg', 274 ),
( 'UNIBIC CHOCO KISS 75G', 'productPool/1.jpg', 124 ),
( 'UNIBIC CHOCO NUT 150G', 'productPool/1.jpg', 247 ),
( 'UNIBIC CHOCOCHIP COOKIES 150G', 'productPool/1.jpg', 29 ),
( 'UNIBIC CHOCONUT COOKIES I75G', 'productPool/1.jpg', 97 ),
( 'UNIBIC FRUIT & NUT COOKIES 150G', 'productPool/1.jpg', 105 ),
( 'UNIBIC FRUIT & NUT COOKIES 37.5G', 'productPool/1.jpg', 99 ),
( 'UNIBIC FRUIT AND NUT COOKIES 75G', 'productPool/1.jpg', 95 ),
( 'UNIBIC MILK COOKIES 120G', 'productPool/1.jpg', 194 ),
( 'UNIBIC MILK COOKIES 200G', 'productPool/1.jpg', 201 ),
( 'UNIBIC MILK COOKIES 62.5G', 'productPool/1.jpg', 205 ),
( 'UNIBIC PISTA BADAM COKIES 150GM', 'productPool/1.jpg', 51 ),
( 'UNIBIC PISTA BADAM COOKIES 75G', 'productPool/1.jpg', 109 ),
( 'UNIBIC RICE AND CORN COOKIES 75G', 'productPool/1.jpg', 130 ),
( 'UNIBIC RIPPLE COOKIES200G', 'productPool/1.jpg', 23 ),
( 'UNIBIC SCOTCH FINGER COOKIES 100G', 'productPool/1.jpg', 97 ),
( 'UNIBIC SUGAR FREE CASHEW', 'productPool/1.jpg', 43 ),
( 'UNIBIC SUGAR FREE CASHEW COOKIES 150G', 'productPool/1.jpg', 173 ),
( 'UNIBIC SUGAR FREE MULTI GRAIN BAKF COOKIES 75G', 'productPool/1.jpg', 258 ),
( 'UNIBIC SUGAR FREE OATMEAL COOKIES 150G', 'productPool/1.jpg', 212 ),
( 'UNIBIC SUGARFREE BUTTER COOKIES', 'productPool/1.jpg', 93 ),
( 'UNIBIC SUGARFREE CHOCO SWIRL COOKIES 75G', 'productPool/1.jpg', 276 ),
( 'UNIBIC SUGARFREE OTAMEAL COOKIES 75G', 'productPool/1.jpg', 143 ),
( 'UNIROSE RECHARGEABIE BATTERIES 2*HR6/AA', 'productPool/1.jpg', 234 ),
( 'UNIROSS ALKALINE AA', 'productPool/1.jpg', 172 ),
( 'UNIROSS RECHARGEABLE 1000', 'productPool/1.jpg', 276 ),
( 'UNIROSS RECHARGEABLE BATTERIES 800AAA', 'productPool/1.jpg', 196 ),
( 'UNNI APPAM', 'productPool/1.jpg', 120 ),
( 'UNUBIC CHOCONUT COOKIES 37.5G RS10', 'productPool/1.jpg', 198 ),
( 'URAD WHOLE 500G', 'productPool/1.jpg', 251 ),
( 'URBANAS CASHEW ROASTED 250G', 'productPool/1.jpg', 197 ),
( 'URBANS BARBEQUE BLEND CASHEW 80G', 'productPool/1.jpg', 266 ),
( 'URBANS CASHEW BLACK PEPPER 80G', 'productPool/1.jpg', 111 ),
( 'URBANS GREEN CHILLY CASHEW 80G', 'productPool/1.jpg', 56 ),
( 'URBANS ROASTED CASHEW 500G', 'productPool/1.jpg', 155 ),
( 'URBANS W240 PLAIN CASHEW 250G', 'productPool/1.jpg', 192 ),
( 'URBANS W240 PLAIN CASHEW 500G', 'productPool/1.jpg', 141 ),
( 'URO PLAST BATH STOOL', 'productPool/1.jpg', 31 ),
( 'USA GREEN PEAR', 'productPool/1.jpg', 267 ),
( 'UTTAM WHITE SUGAR CUBES 500G', 'productPool/1.jpg', 104 ),
( 'UZHUNNU (WEIGHTED)', 'productPool/1.jpg', 198 ),
( 'UZHUNNU 500G', 'productPool/1.jpg', 194 ),
( 'UZHUNNU BALL 500G', 'productPool/1.jpg', 98 ),
( 'UZHUNNU BALL WHITE1 PREMIUM 500GMS', 'productPool/1.jpg', 41 ),
( 'UZHUNNU DAL 500G', 'productPool/1.jpg', 23 ),
( 'V I P COCOA CREAM CHOCLATE 25G', 'productPool/1.jpg', 200 ),
( 'V NUT PASSION FRUIT 330ML CAN', 'productPool/1.jpg', 79 ),
( 'V NUT STRAWBERRY 330ML CAN', 'productPool/1.jpg', 74 ),
( 'V WASH HYGIENE TRAVEL PACK3.5', 'productPool/1.jpg', 235 ),
( 'V WASH PLUS 100ML', 'productPool/1.jpg', 186 ),
( 'V WASH PLUS 200ML', 'productPool/1.jpg', 16 ),
( 'V WASH PLUS 20ML RS-45', 'productPool/1.jpg', 243 ),
( 'VAGA HAIR BRUSH R2-RBB', 'productPool/1.jpg', 66 ),
( 'VAGA NAIL CLIPPER BIG', 'productPool/1.jpg', 156 ),
( 'VALARIPAYAR', 'productPool/1.jpg', 80 ),
( 'VALENTINO RED GRAPE DRINK 750ML', 'productPool/1.jpg', 156 ),
( 'VALENTINO WHITE GRAPE DRINK 750ML', 'productPool/1.jpg', 246 ),
( 'VANISH BAR SOAP 75GM', 'productPool/1.jpg', 41 ),
( 'VANISH LIQUID 180ML', 'productPool/1.jpg', 99 ),
( 'VANISH OXI ACTION 100G', 'productPool/1.jpg', 57 ),
( 'VANISH OXI ACTION 400G', 'productPool/1.jpg', 216 ),
( 'VANISH OXI ACTION 400ML', 'productPool/1.jpg', 248 ),
( 'VANISH OXI ACTION 800ML', 'productPool/1.jpg', 275 ),
( 'VANISH OXI ACTION LIQUID 180ML', 'productPool/1.jpg', 270 ),
( 'VANISH OXI ACTION LIQUID 400ML', 'productPool/1.jpg', 85 ),
( 'VANISH OXI ACTION POWDER 200G', 'productPool/1.jpg', 124 ),
( 'VANISH POWDER 100G', 'productPool/1.jpg', 71 ),
( 'VANISH POWDER 30G PKT', 'productPool/1.jpg', 152 ),
( 'VANISH SHAKTHI 240G', 'productPool/1.jpg', 81 ),
( 'VANLEER DARK CONFECTION 500G', 'productPool/1.jpg', 96 ),
( 'VANLEER MILK COLLECTION 375G', 'productPool/1.jpg', 226 ),
( 'VANLEER WHITE CONFECTION 375G', 'productPool/1.jpg', 107 ),
( 'VANPAYAR BIG 500G', 'productPool/1.jpg', 263 ),
( 'VANPAYAR PREMIUM 500GMS', 'productPool/1.jpg', 65 ),
( 'VANPAYAR WHITE 500G', 'productPool/1.jpg', 277 ),
( 'VARIETH CHAMMANTHIPODI 200GM', 'productPool/1.jpg', 160 ),
( 'VARIETH CHAMMANTHIPODI 500GM', 'productPool/1.jpg', 239 ),
( 'VARIETH CHAMMANTHPODI 100GM', 'productPool/1.jpg', 172 ),
( 'VASELINE ADVANCED REPAIR LOTION 400ML', 'productPool/1.jpg', 109 ),
( 'VASELINE ALOE SMOTH 100ML', 'productPool/1.jpg', 95 ),
( 'VASELINE ALOE SOOTHE LTN 200ML', 'productPool/1.jpg', 174 ),
( 'VASELINE ALOE SOOTHE LTN 300ML', 'productPool/1.jpg', 63 ),
( 'VASELINE COCOA GLOW 100ML', 'productPool/1.jpg', 227 ),
( 'VASELINE COCOA GLOW 300ML', 'productPool/1.jpg', 48 ),
( 'VASELINE COCOA GLOW BUTTER 300ML', 'productPool/1.jpg', 236 ),
( 'VASELINE COCOAGLOW BODYLOTION 100ML', 'productPool/1.jpg', 125 ),
( 'VASELINE DEEP RESTORE DRYLOTION 400ML', 'productPool/1.jpg', 146 ),
( 'VASELINE DEEP RESTORE100ML', 'productPool/1.jpg', 246 ),
( 'VASELINE GEL (B) IMP', 'productPool/1.jpg', 220 ),
( 'VASELINE GEL (M) IMP', 'productPool/1.jpg', 119 ),
( 'VASELINE GEL (S) IMP', 'productPool/1.jpg', 37 ),
( 'VASELINE GEL IMP (M)', 'productPool/1.jpg', 237 ),
( 'VASELINE HAIR TONIC 100 IMP', 'productPool/1.jpg', 258 ),
( 'VASELINE HAIR TONIC 200', 'productPool/1.jpg', 210 ),
( 'VASELINE HAIR TONIC 300 IMP', 'productPool/1.jpg', 157 ),
( 'VASELINE HEALTHY WHITE 100ML', 'productPool/1.jpg', 273 ),
( 'VASELINE HEALTHY WHITE COMPLETE 100ML', 'productPool/1.jpg', 43 ),
( 'VASELINE HEALTHY WHITE LIGHT 100ML', 'productPool/1.jpg', 27 ),
( 'VASELINE HEALTHY WHITE LIGHTENING 200 ML', 'productPool/1.jpg', 83 ),
( 'VASELINE HEALTHY WHITE LIGHTENING LOTION 100ML', 'productPool/1.jpg', 128 ),
( 'VASELINE HEALTHY WHITE LOTION 300ML', 'productPool/1.jpg', 59 ),
( 'VASELINE INTENSIVE CARE 100ML', 'productPool/1.jpg', 32 ),
( 'VASELINE INTENSIVE CARE ALOE 100ML', 'productPool/1.jpg', 162 ),
( 'VASELINE INTENSIVE CARE DEEP RESTORE LOTION', 'productPool/1.jpg', 113 ),
( 'VASELINE ORGINAL CREAM 20G', 'productPool/1.jpg', 251 ),
( 'VASELINE ORIGINAL 50ML', 'productPool/1.jpg', 76 ),
( 'VASELISKIN LOTION 300ML', 'productPool/1.jpg', 118 ),
( 'VASMALMON HAIR OIL 100ML', 'productPool/1.jpg', 178 ),
( 'VASMALMON HAIR OIL 200ML', 'productPool/1.jpg', 208 ),
( 'VASMOL 33 KESHKALA 100ML', 'productPool/1.jpg', 13 ),
( 'VASMOL ALMONDOIL50ML', 'productPool/1.jpg', 265 ),
( 'VASMOL AMLA HAIRDYE', 'productPool/1.jpg', 87 ),
( 'VASMOL AMLA SHAKTI NATURAL BLACK', 'productPool/1.jpg', 9 ),
( 'VASMOL BLACK HAIR OIL 100ML', 'productPool/1.jpg', 118 ),
( 'VASMOL BLACK HENNA 10GM', 'productPool/1.jpg', 130 ),
( 'VASMOL HENNA 10G', 'productPool/1.jpg', 275 ),
( 'VASMOL JASMINE COCONUT HAIR OIL 100ML', 'productPool/1.jpg', 186 ),
( 'VASMOL JASMINE HAIR OIL 300ML', 'productPool/1.jpg', 176 ),
( 'VASMOL JASMINE HAIR OIL 90ML', 'productPool/1.jpg', 156 ),
( 'VASMOL JASMINE OIL 200ML', 'productPool/1.jpg', 139 ),
( 'VASMOL KESHKALA 50ML', 'productPool/1.jpg', 49 ),
( 'VASMOL PROTEIN SHAMPOO 1 LTR', 'productPool/1.jpg', 256 ),
( 'VASMOL SHEHNAI HENNA 150G', 'productPool/1.jpg', 46 ),
( 'VASMOL SHEL HENNA 500G', 'productPool/1.jpg', 31 ),
( 'VASMOL SILKISS HERBAL SHAMPOO 1025 ML', 'productPool/1.jpg', 246 ),
( 'VASMOL SILKISS SHAMPOO+CONDITIONER HERBAL 1 LTR', 'productPool/1.jpg', 97 ),
( 'VASMOLJASMINE HAIR OIL 50ML', 'productPool/1.jpg', 50 ),
( 'VASU BANSURI 126G', 'productPool/1.jpg', 209 ),
( 'VASU VASU 100 MRP 10', 'productPool/1.jpg', 12 ),
( 'VATHIKA OIL BALANCE SPLIT SHAMPOO 50ML', 'productPool/1.jpg', 222 ),
( 'VATHIKA OLIVE OIL 100ML', 'productPool/1.jpg', 132 ),
( 'VATIKA ANTI DANDRUFF SHAMPOO 80ML', 'productPool/1.jpg', 37 ),
( 'VATIKA BLACK SHAMPOO 5ML', 'productPool/1.jpg', 126 ),
( 'VATIKA HEALTH SHAMPOO 180ML', 'productPool/1.jpg', 8 ),
( 'VATIKA HEALTH SHAMPOO 5.6ML', 'productPool/1.jpg', 83 ),
( 'VATIKA HENNA SHAMPOO80 ML', 'productPool/1.jpg', 253 ),
( 'VED RASAA KESA MARJANA SHAMPOO 125ML', 'productPool/1.jpg', 169 ),
( 'VED RASAA KESA ROGANA HAIR OIL 100ML', 'productPool/1.jpg', 246 ),
( 'VED RASAA KESA ROGANA HAIR OIL 200ML', 'productPool/1.jpg', 64 ),
( 'VED RASAA NOURISHING SHAMPOO 200ML', 'productPool/1.jpg', 108 ),
( 'VED RASAA UBTAN 25G', 'productPool/1.jpg', 251 ),
( 'VED RASAA UBTAN 50G', 'productPool/1.jpg', 190 ),
( 'VEDHAS GOLD GROUNDNUT OIL 1L', 'productPool/1.jpg', 161 ),
( 'VEEBA CLASSIC MAYONNAISE 250G', 'productPool/1.jpg', 236 ),
( 'VEEBA CLASSIC MAYONNAISE 275G', 'productPool/1.jpg', 33 ),
( 'VEEBA EGGLESS MAYONNAISE 275G', 'productPool/1.jpg', 16 ),
( 'VEEBA HONEY MUSTARD DRESSING 300G', 'productPool/1.jpg', 84 );