INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'KISSAN MEXICAN SALSA SAUCE 200G', 'productPool/1.jpg', 279 ),
( 'KISSAN MIX FRUIT JAM 200G', 'productPool/1.jpg', 209 ),
( 'KISSAN MIX FRUIT JAM 500G', 'productPool/1.jpg', 21 ),
( 'KISSAN MIXED FRUIT JAM 100G', 'productPool/1.jpg', 189 ),
( 'KISSAN MIXED FRUIT JAM 500G', 'productPool/1.jpg', 62 ),
( 'KISSAN MIXED FRUIT JAM 700G', 'productPool/1.jpg', 197 ),
( 'KISSAN MIXED FRUIT SQUASH 750ML', 'productPool/1.jpg', 183 ),
( 'KISSAN MIXED JAM100G', 'productPool/1.jpg', 214 ),
( 'KISSAN NOONINO GARLIC 500G', 'productPool/1.jpg', 254 ),
( 'KISSAN ONION GARLIC 200G', 'productPool/1.jpg', 184 ),
( 'KISSAN ORANGE BLAST 320GM', 'productPool/1.jpg', 1 ),
( 'KISSAN ORANGE JAM 500G', 'productPool/1.jpg', 169 ),
( 'KISSAN ORANGE SQUASH 750ML', 'productPool/1.jpg', 43 ),
( 'KISSAN PINEAPPLE JAM 500G', 'productPool/1.jpg', 127 ),
( 'KISSAN PINEAPPLE SQUASH 750ML', 'productPool/1.jpg', 103 ),
( 'KISSAN PINEPPLE JAM 200G', 'productPool/1.jpg', 121 ),
( 'KISSAN PIZZA & PASTA SAUCE 200G', 'productPool/1.jpg', 132 ),
( 'KISSAN SCHEZWAN SAUCE 200G', 'productPool/1.jpg', 45 ),
( 'KISSAN STRAW BERRY BLAST 320GM', 'productPool/1.jpg', 142 ),
( 'KISSAN SWEET & SPICY SAUCE 450G', 'productPool/1.jpg', 226 ),
( 'KISSAN SWEET SPICY SAUCE 200G', 'productPool/1.jpg', 169 ),
( 'KISSAN TOMATO CHILLI 200G', 'productPool/1.jpg', 127 ),
( 'KISSAN TOMATO KETCHUP 500G', 'productPool/1.jpg', 48 ),
( 'KISSAN TROPICAL BLAST JAM 320G', 'productPool/1.jpg', 256 ),
( 'KISSAN TWIST CHILLI TOMATO 500G', 'productPool/1.jpg', 21 ),
( 'KISSAN TWIST CHILLI TOMATO KETCHUP 200G', 'productPool/1.jpg', 43 ),
( 'KISSAN TWIST SWEET & SPICY 500G', 'productPool/1.jpg', 199 ),
( 'KISSAN TWIST SWEET-SPICY SAUCE 90G', 'productPool/1.jpg', 156 ),
( 'KIT KAT BROWNLE KUBES 50G', 'productPool/1.jpg', 9 ),
( 'KITCHEN CORIENDER POWDER 100G', 'productPool/1.jpg', 157 ),
( 'KITCHEN BRUSH HX', 'productPool/1.jpg', 206 ),
( 'KITCHEN CHILLI POWDER 100G', 'productPool/1.jpg', 31 ),
( 'KITCHEN GARAM MASALA 50GM', 'productPool/1.jpg', 82 ),
( 'KITCHEN SCALE SKX', 'productPool/1.jpg', 45 ),
( 'KITCHEN TOWEL 16*16', 'productPool/1.jpg', 104 ),
( 'KITCHEN TOWEL RS12.50', 'productPool/1.jpg', 26 ),
( 'KITCHEN TOWEL RS66', 'productPool/1.jpg', 87 ),
( 'KITCHEN TREASURES ASAFETIDA 100G', 'productPool/1.jpg', 12 ),
( 'KITCHEN TREASURES ASAFOETIDA CAKE 100G', 'productPool/1.jpg', 39 ),
( 'KITCHEN TREASURES BEEF ULARTHU MASALA 100G', 'productPool/1.jpg', 206 ),
( 'KITCHEN TREASURES BIRYANI MASALA 100G', 'productPool/1.jpg', 266 ),
( 'KITCHEN TREASURES BIRYANI MASALA 50G', 'productPool/1.jpg', 39 ),
( 'KITCHEN TREASURES BLACK PEPPER POWDER 100G', 'productPool/1.jpg', 95 ),
( 'KITCHEN TREASURES BLACK PEPPERPOWDER 50G', 'productPool/1.jpg', 156 ),
( 'KITCHEN TREASURES BRAHMIN SAMBAR POWDER 100G', 'productPool/1.jpg', 263 ),
( 'KITCHEN TREASURES CHEMBA PUTTU PODI 500G', 'productPool/1.jpg', 268 ),
( 'KITCHEN TREASURES CHICKEN FRY MASALA 100G', 'productPool/1.jpg', 14 ),
( 'KITCHEN TREASURES CHICKEN KEBAB MASALA 100G', 'productPool/1.jpg', 15 ),
( 'KITCHEN TREASURES CHICKEN MASALA 100G', 'productPool/1.jpg', 260 ),
( 'KITCHEN TREASURES CHILLI CHICKEN MASALA 100G', 'productPool/1.jpg', 90 ),
( 'KITCHEN TREASURES CHILLI POWDER 1KG', 'productPool/1.jpg', 146 ),
( 'KITCHEN TREASURES CHILLI POWDER 250G*40', 'productPool/1.jpg', 251 ),
( 'KITCHEN TREASURES CHILLI POWDER 500GM*20', 'productPool/1.jpg', 33 ),
( 'KITCHEN TREASURES CHUTNEY POWDER 100G', 'productPool/1.jpg', 208 ),
( 'KITCHEN TREASURES CORIANDAR POWDER 250GM', 'productPool/1.jpg', 11 ),
( 'KITCHEN TREASURES CORIANDER POWDER 1KG', 'productPool/1.jpg', 89 ),
( 'KITCHEN TREASURES CORIANDER POWDER 500G', 'productPool/1.jpg', 271 ),
( 'KITCHEN TREASURES CUMIN POWDER 100G', 'productPool/1.jpg', 241 ),
( 'KITCHEN TREASURES CUT MANGO PICKLE 150G', 'productPool/1.jpg', 220 ),
( 'KITCHEN TREASURES CUT MANGO PICKLE 1KG', 'productPool/1.jpg', 62 ),
( 'KITCHEN TREASURES CUT MANGO PICKLE 200G', 'productPool/1.jpg', 87 ),
( 'KITCHEN TREASURES DATES PICKLE 400G', 'productPool/1.jpg', 125 ),
( 'KITCHEN TREASURES DOUBLE ROASTED RAVA 1KG', 'productPool/1.jpg', 133 ),
( 'KITCHEN TREASURES DOUBLE ROASTED RAVA 500G', 'productPool/1.jpg', 261 ),
( 'KITCHEN TREASURES EGG MASALA 100GM*1000', 'productPool/1.jpg', 234 ),
( 'KITCHEN TREASURES FENUGREEK 100G', 'productPool/1.jpg', 185 ),
( 'KITCHEN TREASURES FISH FRY MASALA 100G', 'productPool/1.jpg', 193 ),
( 'KITCHEN TREASURES FISH MASALA 100G', 'productPool/1.jpg', 15 ),
( 'KITCHEN TREASURES FISH PICKEL 150GM*24', 'productPool/1.jpg', 90 ),
( 'KITCHEN TREASURES FISH PICKLE 400G', 'productPool/1.jpg', 131 ),
( 'KITCHEN TREASURES GARLIC PASTE 100GM', 'productPool/1.jpg', 152 ),
( 'KITCHEN TREASURES GARLIC PICKLE 150G', 'productPool/1.jpg', 32 ),
( 'KITCHEN TREASURES GARLIC PICKLE 400G', 'productPool/1.jpg', 163 ),
( 'KITCHEN TREASURES GINGER GARLIC PASTE 100G', 'productPool/1.jpg', 162 ),
( 'KITCHEN TREASURES GINGER PASTE 100G', 'productPool/1.jpg', 241 ),
( 'KITCHEN TREASURES GINGER PICKLE 400G', 'productPool/1.jpg', 120 ),
( 'KITCHEN TREASURES GOOSEBRRRY PICKLE 400G', 'productPool/1.jpg', 64 ),
( 'KITCHEN TREASURES HOT & SWEET PICKLE 400G', 'productPool/1.jpg', 108 ),
( 'KITCHEN TREASURES HOT SWEET PICKLE', 'productPool/1.jpg', 152 ),
( 'KITCHEN TREASURES KADUKU MANGO PICKLE 150G', 'productPool/1.jpg', 195 ),
( 'KITCHEN TREASURES KADUKU MANGO PICKLE 400G', 'productPool/1.jpg', 79 ),
( 'KITCHEN TREASURES KASHMIRI CHILLI POWDER 1KG', 'productPool/1.jpg', 162 ),
( 'KITCHEN TREASURES KASHMIRI CHILLI POWDER 250G', 'productPool/1.jpg', 75 ),
( 'KITCHEN TREASURES KASHMIRI CHILLI POWDER 500G*20', 'productPool/1.jpg', 167 ),
( 'KITCHEN TREASURES KASMIRI CHILLI POWDER 100GM', 'productPool/1.jpg', 66 ),
( 'KITCHEN TREASURES LIME PICKLE 150G', 'productPool/1.jpg', 269 ),
( 'KITCHEN TREASURES LIME PICKLE 1KG', 'productPool/1.jpg', 147 ),
( 'KITCHEN TREASURES LIME PICKLE 400G', 'productPool/1.jpg', 252 ),
( 'KITCHEN TREASURES MANGO PICKLE 400G', 'productPool/1.jpg', 79 ),
( 'KITCHEN TREASURES MEAT MASALA 100G', 'productPool/1.jpg', 205 ),
( 'KITCHEN TREASURES MIX VEG PICKLE 400G', 'productPool/1.jpg', 51 ),
( 'KITCHEN TREASURES MUTTON MASALA 100G', 'productPool/1.jpg', 223 ),
( 'KITCHEN TREASURES PICKLE POWDER 100G', 'productPool/1.jpg', 194 ),
( 'KITCHEN TREASURES PRAWN 400G', 'productPool/1.jpg', 259 ),
( 'KITCHEN TREASURES PRWAN PICKEL150G*24', 'productPool/1.jpg', 30 ),
( 'KITCHEN TREASURES PUTTU PODI 1KG', 'productPool/1.jpg', 229 ),
( 'KITCHEN TREASURES PUTTUPODI 500G', 'productPool/1.jpg', 196 ),
( 'KITCHEN TREASURES RASAM POWDER 100G', 'productPool/1.jpg', 152 ),
( 'KITCHEN TREASURES RED CHILLI PASTE 100G', 'productPool/1.jpg', 167 ),
( 'KITCHEN TREASURES RICE PALADA MIX 300G', 'productPool/1.jpg', 264 ),
( 'KITCHEN TREASURES RICE POWDER 1KG', 'productPool/1.jpg', 152 ),
( 'KITCHEN TREASURES RICE POWDER 500G', 'productPool/1.jpg', 53 ),
( 'KITCHEN TREASURES SAMBAR POWDER 100G', 'productPool/1.jpg', 9 ),
( 'KITCHEN TREASURES SAMBAR POWDER 250G', 'productPool/1.jpg', 74 ),
( 'KITCHEN TREASURES SPICY CHICKEN MASALA 100G', 'productPool/1.jpg', 139 ),
( 'KITCHEN TREASURES TAMARIND 200G', 'productPool/1.jpg', 162 ),
( 'KITCHEN TREASURES TENDER MANGO PICKLE 150G', 'productPool/1.jpg', 50 ),
( 'KITCHEN TREASURES TENDER MANGO PICKLE 400G', 'productPool/1.jpg', 142 ),
( 'KITCHEN TREASURES VEGETABLE MASALA 100G', 'productPool/1.jpg', 263 ),
( 'KITCHEN TREASURES WHITE LIME PICKLE 400G', 'productPool/1.jpg', 164 ),
( 'KITCHEN TREASURES ASAFOETIDA 50G', 'productPool/1.jpg', 175 ),
( 'KITCHEN TREASURES PALADA MIX 300G', 'productPool/1.jpg', 122 ),
( 'KITCHEN TREASURES VERMICELLI MIX 300G', 'productPool/1.jpg', 152 ),
( 'KITCHEN TREEASURES CUT MANGO PICKLE 65G', 'productPool/1.jpg', 260 ),
( 'KITCHEN TREEASURES KASHMIRI CHILLY 5KG', 'productPool/1.jpg', 64 ),
( 'KITCHEN TREEASURES ROASTEDRICE POWDER 1KG', 'productPool/1.jpg', 220 ),
( 'KITCHEN TURMERIC POWDER 100GM', 'productPool/1.jpg', 39 ),
( 'KITCHEN TURMERIC POWDER 250GM', 'productPool/1.jpg', 41 ),
( 'KITCHENTREASURESH RICE PALADA MIX 300G', 'productPool/1.jpg', 245 ),
( 'KITKAT 2 FINGER MINI 12.8G 36 PCS', 'productPool/1.jpg', 262 ),
( 'KITKAT 76.8G', 'productPool/1.jpg', 99 ),
( 'KITKAT FAMILY PACK 74G', 'productPool/1.jpg', 30 ),
( 'KITKAT NESTLE FAMILY PACK', 'productPool/1.jpg', 50 ),
( 'KIWI 4PCS', 'productPool/1.jpg', 9 ),
( 'KIWI DRIED 100G', 'productPool/1.jpg', 145 ),
( 'KIWI DRIED 1KG', 'productPool/1.jpg', 86 ),
( 'KIWI EXPRESS SHINE BLACK 7ML', 'productPool/1.jpg', 35 ),
( 'KIWI FRUIT', 'productPool/1.jpg', 186 ),
( 'KIWI INSTANT SHOE POLISH BLACK 75ML', 'productPool/1.jpg', 279 ),
( 'KIWI MOOSE', 'productPool/1.jpg', 130 ),
( 'KIWI SHOE POLISH BLACK 40G', 'productPool/1.jpg', 183 ),
( 'KIWI SHOE POLISH BLACK 40ML', 'productPool/1.jpg', 245 ),
( 'KIWI SHINE WAX RICH SHINE PROTECT 75ML', 'productPool/1.jpg', 77 ),
( 'KIWI SLICE 1KG', 'productPool/1.jpg', 178 ),
( 'KLEEN KOUNTRY BAG SMALL 48CM', 'productPool/1.jpg', 253 ),
( 'KLEENO MICROFIBER TWIST MOP SET', 'productPool/1.jpg', 270 ),
( 'KLEENO POPULAR JUMBO WIPR WITH ROD', 'productPool/1.jpg', 135 ),
( 'KLEENO ROUND TELESCOPIC MICROFIBER MOP', 'productPool/1.jpg', 176 ),
( 'KLEENO TWIST PLUS MOP', 'productPool/1.jpg', 245 ),
( 'KLF COCODAILY OIL BOTTLE 1L', 'productPool/1.jpg', 202 ),
( 'KLF COCODAILY OIL POUCH 1L', 'productPool/1.jpg', 57 ),
( 'KLF COCONAD COCONUT MILK 400G', 'productPool/1.jpg', 76 ),
( 'KLF COCONAD COCONUT OIL 1LTR BOTTLE', 'productPool/1.jpg', 165 ),
( 'KLF COCONAD PURE COCONUT OIL 1LTR POUCH', 'productPool/1.jpg', 15 ),
( 'KLF COCONUT CHUTNEY POWDER 100G', 'productPool/1.jpg', 205 ),
( 'KLF COCONUT OIL 500ML BOTTLE', 'productPool/1.jpg', 121 ),
( 'KLF COCONUT OIL 500ML POUCH', 'productPool/1.jpg', 94 ),
( 'KLF COCONUT SUGAR 100G', 'productPool/1.jpg', 179 ),
( 'KLF COCONUT MILK POWDER 25G', 'productPool/1.jpg', 164 ),
( 'KLF NIRMAL PURE COCONUT OIL 100ML', 'productPool/1.jpg', 174 ),
( 'KLF NIRMAL PURE COCONUT OIL 250ML', 'productPool/1.jpg', 189 ),
( 'KLF NIRMAL PURE COCONUT OIL 500ML', 'productPool/1.jpg', 116 ),
( 'KLF NIRMAL PURE COCONUT OIL 50ML', 'productPool/1.jpg', 275 ),
( 'KLF PRAWNS CHUTNEY POWDER 50G', 'productPool/1.jpg', 226 ),
( 'KLF RICENAD RICE BRAN OIL 1L POUCH', 'productPool/1.jpg', 152 ),
( 'KLF RICENAD RICEBRAN OIL 1LTR PET', 'productPool/1.jpg', 207 ),
( 'KLF ROASTED COCONUT MASALA 50G', 'productPool/1.jpg', 202 ),
( 'KLF ROASTED RICE BALL MIX 500G', 'productPool/1.jpg', 19 ),
( 'KLF SUN NAD REFINED SUNFLOWER OIL 1L', 'productPool/1.jpg', 105 ),
( 'KLF VIRGIN COCONUT OIL 500ML', 'productPool/1.jpg', 120 ),
( 'KLF VIRGIN COCONUT OIL 750ML', 'productPool/1.jpg', 141 ),
( 'KLIN WRAP FOOD CLING FILM 85', 'productPool/1.jpg', 257 ),
( 'KLINWRAP CLING FILM 30*500 MTR', 'productPool/1.jpg', 139 ),
( 'KM BLACK DRIED RAISINS 200G', 'productPool/1.jpg', 230 ),
( 'KM DRIED FRUITS JUNIOR 200G', 'productPool/1.jpg', 173 ),
( 'KM DRIED KIWI FRUIT 300G', 'productPool/1.jpg', 29 ),
( 'KM DRY FRUIT CELEBRATIONS 350G', 'productPool/1.jpg', 110 ),
( 'KM JUMBO BLACK RAISINS 300G', 'productPool/1.jpg', 277 ),
( 'KM MINI DRIED NUTS 170G', 'productPool/1.jpg', 119 ),
( 'KM REGENCY DRIED FRUIT 200G', 'productPool/1.jpg', 110 ),
( 'KM REGENCY DRIED FRUIT 400G', 'productPool/1.jpg', 14 ),
( 'KM REGENCY DRIED FRUITS 200G', 'productPool/1.jpg', 119 ),
( 'KM REGENCY DRIED FRUITS 350G', 'productPool/1.jpg', 90 ),
( 'KM REGENCY MINI DRIED NUTS 200G', 'productPool/1.jpg', 75 ),
( 'KNIFE AHK', 'productPool/1.jpg', 218 ),
( 'KNIFE EO', 'productPool/1.jpg', 210 ),
( 'KNIFE RS 150', 'productPool/1.jpg', 85 ),
( 'KNIFE RS 39', 'productPool/1.jpg', 213 ),
( 'KNIFE RS 85', 'productPool/1.jpg', 229 ),
( 'KNIFE RS55', 'productPool/1.jpg', 81 ),
( 'KNIFE RS75', 'productPool/1.jpg', 212 ),
( 'KNIFE SHARPENER', 'productPool/1.jpg', 159 ),
( 'KNORR HOT VEG SOUP 43G', 'productPool/1.jpg', 5 ),
( 'KNORR THICK TOMATO SOUP 61G', 'productPool/1.jpg', 173 ),
( 'KNORR CHICKEN DELITE SOUP', 'productPool/1.jpg', 240 ),
( 'KNORR CHINESE NOODLES HOT-SPICY 68G', 'productPool/1.jpg', 70 ),
( 'KNORR CHINESE SWEET CORN SOUP 44G', 'productPool/1.jpg', 10 ),
( 'KNORR CUP SOUP 16G', 'productPool/1.jpg', 266 ),
( 'KNORR ITALIAN MUSHROOM SOUP 48G', 'productPool/1.jpg', 271 ),
( 'KNORR MIXED VEGETABLE SOUP 53G', 'productPool/1.jpg', 66 ),
( 'KNORR SCHEZWAN CHINESE NOODLES 68G', 'productPool/1.jpg', 261 ),
( 'KNORR SOUPY NOODLES MAST MASALA 75G', 'productPool/1.jpg', 232 ),
( 'KNORR SWEET CORN CHICKEN SOUP 42G', 'productPool/1.jpg', 247 ),
( 'KNORR THICK TOMATO SOUP 150G', 'productPool/1.jpg', 261 ),
( 'KNORR VEGETABLE SOUP 150G', 'productPool/1.jpg', 52 ),
( 'KNR FOOD BANANA CHIPS 200G', 'productPool/1.jpg', 37 ),
( 'KODIYANS AMLA 750ML', 'productPool/1.jpg', 126 ),
( 'KODIYANS DRAKSHA GRAPE 750ML', 'productPool/1.jpg', 42 ),
( 'KODIYANS GINGER ARISHTAM 750ML', 'productPool/1.jpg', 46 ),
( 'KODIYANS MATHALAM ARISHTAM 750ML', 'productPool/1.jpg', 231 ),
( 'KODIYANS PASSION FRUIT ARISHTAM 750ML', 'productPool/1.jpg', 10 ),
( 'KOHINOOR GOLD EXTRA LONG 1 KG BASMATI RICE', 'productPool/1.jpg', 179 ),
( 'KOHINOOR PLATINUM 1KG BASMATI RICE', 'productPool/1.jpg', 98 ),
( 'KOHINOOR SILVER 1KG BASMATI RICE', 'productPool/1.jpg', 88 ),
( 'KOHINOOR SILVER TIBAR PKT 1KG', 'productPool/1.jpg', 158 ),
( 'KOHINOOR TROPHY 1KG ROYALE BASMATI RICE', 'productPool/1.jpg', 155 ),
( 'KOKOZO GRAPE JUICE 300 ML', 'productPool/1.jpg', 43 ),
( 'KOKOZO LYCHEE JUICE 300ML', 'productPool/1.jpg', 245 ),
( 'KOKOZO MANGO JUICE 300 ML', 'productPool/1.jpg', 144 ),
( 'KOKOZO MELON JUICE 320 ML', 'productPool/1.jpg', 84 ),
( 'KOKOZO MIXED FRUIT JUICE 300ML', 'productPool/1.jpg', 176 ),
( 'KOKOZO ORANGE JUICE 300 ML', 'productPool/1.jpg', 232 ),
( 'KOKOZO PINEAPPLE JUICE 320 ML', 'productPool/1.jpg', 96 ),
( 'KOKOZO POMEGRANATE JUICE 320 ML', 'productPool/1.jpg', 109 ),
( 'KOKOZO STRAWBERRY JUICE 300 ML', 'productPool/1.jpg', 249 ),
( 'Koorka', 'productPool/1.jpg', 92 ),
( 'KOPIKO CAPPUCCINO 161G', 'productPool/1.jpg', 66 ),
( 'KOPIKO CAPPUCCINO 190G', 'productPool/1.jpg', 66 ),
( 'KOPIKO CAPPUCCINO 402.5G', 'productPool/1.jpg', 167 ),
( 'KOPIKO CAPPUCCINO 418G', 'productPool/1.jpg', 125 ),
( 'KORES FEATHER TOUCH INK PAD', 'productPool/1.jpg', 75 ),
( 'KORES GLUE STICK 8G', 'productPool/1.jpg', 202 ),
( 'KORES SMART CORRECTION PEN 7ML', 'productPool/1.jpg', 13 ),
( 'KORES WHITE BOARD MARKER', 'productPool/1.jpg', 42 ),
( 'KOTEX SOFT&SMOOTH RS 26 8S', 'productPool/1.jpg', 160 ),
( 'KOTEX STYLE 8PADS', 'productPool/1.jpg', 132 ),
( 'KOVAKKA', 'productPool/1.jpg', 70 ),
( 'KOYA MAYA SUPREME AGARBATHI 18G', 'productPool/1.jpg', 76 ),
( 'KOYA PAKKANAR 3 IN 1 AGARBATHI', 'productPool/1.jpg', 106 ),
( 'KOYAMAYA SUPRME 100G', 'productPool/1.jpg', 199 ),
( 'KOYAS ROSE AGARBATTI 20G', 'productPool/1.jpg', 237 ),
( 'KOYAS VISHNU LEELA RS10', 'productPool/1.jpg', 198 ),
( 'KOZHUKATTA', 'productPool/1.jpg', 96 ),
( 'KP NAMBOODIRIS ANTI DANDRUFF SHAMPOO 220ML', 'productPool/1.jpg', 60 ),
( 'KPL SUDHI 1LT BOTTLE', 'productPool/1.jpg', 101 ),
( 'KPL SUDHI 500ML', 'productPool/1.jpg', 4 ),
( 'KPL SUDHI OIL 1L POUCH', 'productPool/1.jpg', 261 ),
( 'KPL SUDHI OIL 500ML POUCH', 'productPool/1.jpg', 134 ),
( 'KP NAMBOODIRIS AEDA CLASSIC HANDWASH 180ML POUCH', 'productPool/1.jpg', 160 ),
( 'KP NAMBOODIRIS AEDA CLEAR SOFT SHOWER GEL 200ML', 'productPool/1.jpg', 5 ),
( 'KP NAMBOODIRIS AEDA NATURAL SOAP 75G', 'productPool/1.jpg', 27 ),
( 'KP NAMBOODIRIS AEDA NATURE HANDWASH 180ML POUCH', 'productPool/1.jpg', 190 ),
( 'KP NAMBOODIRIS AEDA RAMACHAM SOAP 75G', 'productPool/1.jpg', 4 ),
( 'KP NAMBOODIRIS AEDA TURMERIC SOAP 75G', 'productPool/1.jpg', 111 ),
( 'KP NAMBOODIRIS ALOE VERA TOOTH PASTE 100G', 'productPool/1.jpg', 220 ),
( 'KP NAMBOODIRIS ALOE VERA TOOTH PASTE 50G', 'productPool/1.jpg', 62 ),
( 'KP NAMBOODIRIS AYURVEDIC TOOTH POWDER 80G', 'productPool/1.jpg', 23 ),
( 'KP NAMBOODIRIS DAHAMUKTHI 100G', 'productPool/1.jpg', 98 ),
( 'KP NAMBOODIRIS HAIR OIL 100 ML', 'productPool/1.jpg', 193 ),
( 'KP NAMBOODIRIS SANDAL SOAP 75G', 'productPool/1.jpg', 24 ),
( 'KP NAMBOODIRIS DAHAMUKTHI 25G', 'productPool/1.jpg', 209 ),
( 'KP NAMBOODIRIS CHEMPARATHI 220ML', 'productPool/1.jpg', 183 ),
( 'KPP CASHEW ROASTED &SALTED 100G', 'productPool/1.jpg', 240 ),
( 'KPP CASHEW ROASTED &SALTED 200G', 'productPool/1.jpg', 264 ),
( 'KPP CASHEW ROASTED &SALTED 500G', 'productPool/1.jpg', 247 ),
( 'KRACK HEEL REPAIR', 'productPool/1.jpg', 77 ),
( 'KRAFT PAPER KAKKI 13*7 m', 'productPool/1.jpg', 197 ),
( 'KRAFT PAPER KAKKI 13*7m', 'productPool/1.jpg', 219 ),
( 'KRAFT PAPER KAKKI 16*7m', 'productPool/1.jpg', 262 ),
( 'KRAFT PAPER KAKKI 22*7m', 'productPool/1.jpg', 247 ),
( 'KRAFT PAPER RED 13*5m', 'productPool/1.jpg', 201 ),
( 'KRAFT PAPER RED 16*5m', 'productPool/1.jpg', 22 ),
( 'KRAFT PAPER RED 22*5m', 'productPool/1.jpg', 80 ),
( 'KRAFT PAPER RED 22*7m', 'productPool/1.jpg', 128 ),
( 'KRAFT TUNISIAN DATES 500GM', 'productPool/1.jpg', 142 ),
( 'KRAVOUR CANDIFUN ROSE CANDY 920G', 'productPool/1.jpg', 65 ),
( 'KRAVOUR CHATKA FUN 680G', 'productPool/1.jpg', 230 ),
( 'KRAVOUR DELICIOUS CHOCO FLAVOURED BISCUITS 150G', 'productPool/1.jpg', 254 ),
( 'KRAVOUR DELICIOUS CHOCO FLAVOURED BISCUITS 75G', 'productPool/1.jpg', 269 ),
( 'KRAVOUR DELICIOUS ORANGE FLAVOURED BISCUITS 150G', 'productPool/1.jpg', 206 ),
( 'KRAVOUR DELICIOUS ORANGE FLAVOURED BISCUITS 75G', 'productPool/1.jpg', 227 ),
( 'KRAVOUR DELICIOUS STRAWBERRY FLAVOURED BISCUITS 150G', 'productPool/1.jpg', 91 ),
( 'KRAVOUR DELICIOUS STRAWBERRY FLAVOURED BISCUITS 75G', 'productPool/1.jpg', 161 ),
( 'KRAVOUR DELICIOUS VANILA FLAVOURED BISCUITS 150G', 'productPool/1.jpg', 2 ),
( 'KRAVOUR DELICIOUS VANILLA FLAVOURED BISCUITS 75G', 'productPool/1.jpg', 171 ),
( 'KRAZY DBL SIDE COMB', 'productPool/1.jpg', 152 ),
( 'KRAZY RATMAAR 25G', 'productPool/1.jpg', 198 ),
( 'KRAZY RATMAAR 50G', 'productPool/1.jpg', 65 ),
( 'KRAZY SINGLE SIDE COMB', 'productPool/1.jpg', 177 ),
( 'KREITENS QUALITY SWEETS ALMOMD TOFFEE 250G', 'productPool/1.jpg', 256 ),
( 'KREMETTOS CHOCOLATES 750G', 'productPool/1.jpg', 255 ),
( 'KRISHNA CURD CHILLI VATHAL 100G', 'productPool/1.jpg', 241 ),
( 'KRISH GOLD WALNUT KERNELS 250G', 'productPool/1.jpg', 144 ),
( 'KRISH GOLD WALNUT KERNELS L H 250G', 'productPool/1.jpg', 211 ),
( 'KRISHNA 3D FRYAMS 100G', 'productPool/1.jpg', 277 ),
( 'KRISHNA ACTIVE DRIED YEAST 50G', 'productPool/1.jpg', 222 ),
( 'KRISHNA ADAI MIX 200G', 'productPool/1.jpg', 38 ),
( 'KRISHNA APPALAM 140G', 'productPool/1.jpg', 270 ),
( 'KRISHNA APPALAM 160G', 'productPool/1.jpg', 163 ),
( 'KRISHNA APPALAM 200G', 'productPool/1.jpg', 118 ),
( 'KRISHNA APPALAM 250G', 'productPool/1.jpg', 109 ),
( 'KRISHNA APPALAM 300G', 'productPool/1.jpg', 156 ),
( 'KRISHNA ASAFOETIDA IDLY CHILLY POWDER 100G', 'productPool/1.jpg', 260 ),
( 'KRISHNA BADAM BEVERAGE 200G', 'productPool/1.jpg', 271 ),
( 'KRISHNA BADAM BEVERAGE JAR 400G', 'productPool/1.jpg', 279 ),
( 'KRISHNA BAJJI & BONDA FLOUR 500G', 'productPool/1.jpg', 6 ),
( 'KRISHNA BAJJI & BONDA FLOUR 200G', 'productPool/1.jpg', 222 ),
( 'KRISHNA BAJRA DOSAI MIX 500G', 'productPool/1.jpg', 154 ),
( 'KRISHNA BAJRA PUTTU PODI 500G', 'productPool/1.jpg', 99 ),
( 'KRISHNA BIG POTATO COIN 100G', 'productPool/1.jpg', 256 ),
( 'KRISHNA BITTER GUARD VATHAL 50G', 'productPool/1.jpg', 106 ),
( 'KRISHNA BITTER GURAD VATHAL 100G', 'productPool/1.jpg', 1 ),
( 'KRISHNA BROKEN YELLOW CORN 500G', 'productPool/1.jpg', 217 ),
( 'KRISHNA CHAT MASALA MIX 100G', 'productPool/1.jpg', 45 ),
( 'KRISHNA CHILLY FLAKES 100G', 'productPool/1.jpg', 79 ),
( 'KRISHNA CHILLY MURUKKU FLOUR 500G', 'productPool/1.jpg', 90 ),
( 'KRISHNA CHILLY SAGO APPALAM 200G', 'productPool/1.jpg', 227 ),
( 'KRISHNA CHIPS TYPE FRAYAMS 100G', 'productPool/1.jpg', 271 ),
( 'KRISHNA CHOLE MASALA 100G', 'productPool/1.jpg', 130 ),
( 'KRISHNA CHUKKU KAPPI MIX 50G', 'productPool/1.jpg', 46 ),
( 'KRISHNA CITRON VATHAL 100G', 'productPool/1.jpg', 62 ),
( 'KRISHNA CLUSTER BEANS 100G', 'productPool/1.jpg', 204 ),
( 'KRISHNA CORN FLOUR 100G', 'productPool/1.jpg', 176 ),
( 'KRISHNA CORN PUTTU PODI 500G', 'productPool/1.jpg', 172 ),
( 'KRISHNA CURD CHILLI VATHAL LONG 100G', 'productPool/1.jpg', 165 ),
( 'KRISHNA CURRY LEAF IDLY CHILLY POWDER 100G', 'productPool/1.jpg', 250 ),
( 'KRISHNA DRY MANGO POWDER 100G', 'productPool/1.jpg', 122 ),
( 'KRISHNA FRYAMS 100G', 'productPool/1.jpg', 10 ),
( 'KRISHNA GARLIC RING FRYAMS 100G', 'productPool/1.jpg', 10 ),
( 'KRISHNA GOBI/65 MASALA 100G', 'productPool/1.jpg', 17 ),
( 'KRISHNA GRAM FLOUR 500G', 'productPool/1.jpg', 263 ),
( 'KRISHNA GREEN MOONG FLOUR 200G', 'productPool/1.jpg', 162 ),
( 'KRISHNA GULAB JAMOON MIX 200G', 'productPool/1.jpg', 210 ),
( 'KRISHNA HEALTH FLOUR 200G', 'productPool/1.jpg', 181 ),
( 'KRISHNA ICE CREAM MIX 100G', 'productPool/1.jpg', 8 ),
( 'KRISHNA ICING SUGAR MIX 200G', 'productPool/1.jpg', 240 ),
( 'KRISHNA IDLY CHILLY POWDER 100G', 'productPool/1.jpg', 7 ),
( 'KRISHNA INSTANT RASAM POWDER 100G', 'productPool/1.jpg', 261 ),
( 'KRISHNA JELLY MIX ORANGE & STRAWBERRY 100G', 'productPool/1.jpg', 210 ),
( 'KRISHNA KESARI MIX 200G', 'productPool/1.jpg', 198 ),
( 'KRISHNA KULFI KESAR BADAM MIX 100G', 'productPool/1.jpg', 180 ),
( 'KRISHNA LEMON RICE POWDER 100G', 'productPool/1.jpg', 177 ),
( 'KRISHNA LEMON SALT 50G', 'productPool/1.jpg', 258 ),
( 'KRISHNA MANATHAKKALI VATHAL 50G', 'productPool/1.jpg', 119 ),
( 'KRISHNA MANGO VATHAL 100G', 'productPool/1.jpg', 208 ),
( 'KRISHNA MASAL VADAI MIX 200G', 'productPool/1.jpg', 220 ),
( 'KRISHNA MIDHUKKU VATHAL 100G', 'productPool/1.jpg', 53 ),
( 'KRISHNA MURUKKU MAAVU 500G', 'productPool/1.jpg', 91 ),
( 'KRISHNA NOODLES MASALA 100G', 'productPool/1.jpg', 21 ),
( 'KRISHNA OATS IDLY MIX 200G', 'productPool/1.jpg', 182 ),
( 'KRISHNA ONION RING FRYAMS 100G', 'productPool/1.jpg', 174 ),
( 'KRISHNA PANI POORI FRYUMS 100G', 'productPool/1.jpg', 52 ),
( 'KRISHNA PANI PURI MASALA 100G', 'productPool/1.jpg', 245 ),
( 'KRISHNA PAV BHAJI MASALA 100G', 'productPool/1.jpg', 96 ),
( 'KRISHNA PISTA MILK SHAKE 100G', 'productPool/1.jpg', 218 ),
( 'KRISHNA PONGAL MIX 200G', 'productPool/1.jpg', 7 ),
( 'KRISHNA PREMIUM CORN FLOUR 400G', 'productPool/1.jpg', 276 ),
( 'KRISHNA PULIYOGARE MIX 100G', 'productPool/1.jpg', 11 ),
( 'KRISHNA RAGI DOSA MAVU 500G', 'productPool/1.jpg', 7 ),
( 'KRISHNA RAVA DOSA MIX 200G', 'productPool/1.jpg', 91 ),
( 'KRISHNA RICE VADAGAM 100G', 'productPool/1.jpg', 13 ),
( 'KRISHNA ROSE MILK MIX 100G', 'productPool/1.jpg', 147 ),
( 'KRISHNA ROSE MILK POWDER 200G', 'productPool/1.jpg', 35 ),
( 'KRISHNA SESAME IDLY CHILLY POWDER 100G', 'productPool/1.jpg', 212 ),
( 'KRISHNA SPECIAL IDLY CHILLY POWDER 100G', 'productPool/1.jpg', 60 ),
( 'KRISHNA SPL RICE KILLU ONION VADAGAM 100G', 'productPool/1.jpg', 114 ),
( 'KRISHNA SPECIAL FRYUMS 100G', 'productPool/1.jpg', 218 ),
( 'KRISHNA SUNDAI VATHAL 100G', 'productPool/1.jpg', 125 ),
( 'KRISHNA THIRUNELVELI IDLY CHILLY POWDER 100G', 'productPool/1.jpg', 251 ),
( 'KRISHNA THULSI 100 ML', 'productPool/1.jpg', 177 ),
( 'KRISHNA THULSI HAIR TONIC 100ML', 'productPool/1.jpg', 175 ),
( 'KRISHNA URID DHAL FLOUR 200G', 'productPool/1.jpg', 28 ),
( 'KRISHNA VADAI MIX 200G', 'productPool/1.jpg', 34 ),
( 'KRISHNA VATHAL KULAMBU MIX 100G', 'productPool/1.jpg', 249 ),
( 'KRISHNA VEGETABLE KURUMA MASALA 100G', 'productPool/1.jpg', 80 ),
( 'KRISHNA YELLOW CORN FLOUR 500G', 'productPool/1.jpg', 101 ),
( 'KRISHNA YELLOW CORN MURUKKU FLOUR 500G', 'productPool/1.jpg', 184 ),
( 'KRISMA DR AAPALM 100G', 'productPool/1.jpg', 57 ),
( 'KRONA MUG 2 L PRINT', 'productPool/1.jpg', 112 ),
( 'KRONA MURAM SQUARE', 'productPool/1.jpg', 176 ),
( 'KRONA WHITE PRINT BUCKET 16L WITH LID', 'productPool/1.jpg', 229 ),
( 'KRONA WHITE PRINT MUG 1L', 'productPool/1.jpg', 93 ),
( 'KRONA WHITE PRINT MUG 750ML', 'productPool/1.jpg', 33 ),
( 'KRUPA STEEL MUG WITH LID', 'productPool/1.jpg', 191 ),
( 'KUDAJADRI HAIR CARE OIL 100ML', 'productPool/1.jpg', 182 ),
( 'KUDAM PULI 100G', 'productPool/1.jpg', 91 ),
( 'KUDAM PULI 200G', 'productPool/1.jpg', 211 ),
( 'KUM KUM 15G', 'productPool/1.jpg', 37 ),
( 'KUM KUM DABBI 8G', 'productPool/1.jpg', 222 ),
( 'KUMARI KALPAM 400G', 'productPool/1.jpg', 56 ),
( 'KUMBALANGA', 'productPool/1.jpg', 211 ),
( 'KUMKUM POWDER 2.5G', 'productPool/1.jpg', 205 ),
( 'KUMKUMADI FAIR OIL 10ML', 'productPool/1.jpg', 47 ),
( 'KUMKUMADI LEPAM 15 G', 'productPool/1.jpg', 71 ),
( 'KUMKUMADI TAILAM 10 ML', 'productPool/1.jpg', 109 ),
( 'KUNDIRIKAM STICKS MRP 20', 'productPool/1.jpg', 123 ),
( 'KURKURE CHILLI CHATKA RS 10', 'productPool/1.jpg', 253 ),
( 'KURKURE CHILLI CHATKA', 'productPool/1.jpg', 8 ),
( 'KURKURE GREEN CHUTNEY', 'productPool/1.jpg', 83 ),
( 'KURKURE GREEN CHUTNEY RS 10', 'productPool/1.jpg', 58 ),
( 'KURKURE HYDERABADI HUNGAMA', 'productPool/1.jpg', 91 ),
( 'KURKURE HYDERABADI HUNGMA RS 10', 'productPool/1.jpg', 143 ),
( 'KURKURE MASALA MNCH', 'productPool/1.jpg', 249 ),
( 'KURKURE MASALA MUNCH 50G', 'productPool/1.jpg', 137 ),
( 'KURKURE MASALA TRANGLES 90G RS20', 'productPool/1.jpg', 254 ),
( 'KURKURE MULTIGRAIN 85G', 'productPool/1.jpg', 260 ),
( 'KURKURE NATURAL TOMATO 47G', 'productPool/1.jpg', 157 ),
( 'KURKURE NAUGHTY TOMATO', 'productPool/1.jpg', 209 ),
( 'KURKURE NAUGHTY TOMOTO', 'productPool/1.jpg', 87 ),
( 'KURKURE PUFF CORN', 'productPool/1.jpg', 222 ),
( 'KURKURE PUFFCORN', 'productPool/1.jpg', 43 ),
( 'KURKURE TRANGLES MASALA 45G', 'productPool/1.jpg', 112 ),
( 'KUTHU VILAKKU ATTA 1KG', 'productPool/1.jpg', 109 ),
( 'KUTHU VILAKKU ATTA 500G', 'productPool/1.jpg', 156 ),
( 'KUTHU VILAKKU ATTA 5KG', 'productPool/1.jpg', 126 ),
( 'KUTHUVILAKKU ATTA 1KG', 'productPool/1.jpg', 51 ),
( 'KUTHUVILAKKU ATTA 5KG', 'productPool/1.jpg', 190 ),
( 'KUTTANADAN UNDA RICE 10KG', 'productPool/1.jpg', 131 ),
( 'KUTTANADAN UNDA RICE 5KG', 'productPool/1.jpg', 47 ),
( 'KUTTANADAN VADI RICE 10 KG', 'productPool/1.jpg', 195 ),
( 'KUTTANADAN VADI RICE 5KG', 'productPool/1.jpg', 135 ),
( 'KUZHALAPPAM BIG(10 NOS)', 'productPool/1.jpg', 60 ),
( 'KWALITY STRAWBERRY CHEASE CAKE TUB 700ML', 'productPool/1.jpg', 178 ),
( 'KWALITY BAKING SODA 100G', 'productPool/1.jpg', 247 ),
( 'KWALITY BASIN 315', 'productPool/1.jpg', 45 ),
( 'KWALITY BASIN 318', 'productPool/1.jpg', 272 ),
( 'KWALITY BERRY DELIGHT 250G', 'productPool/1.jpg', 135 ),
( 'KWALITY BUCKET 107', 'productPool/1.jpg', 173 ),
( 'KWALITY BUCKET 110', 'productPool/1.jpg', 49 ),
( 'KWALITY CHOCO DELIGHT 250G', 'productPool/1.jpg', 103 ),
( 'KWALITY DELUXE WASTE DISH', 'productPool/1.jpg', 145 ),
( 'KWALITY FRUITOOS 375G', 'productPool/1.jpg', 82 ),
( 'KWALITY NOODLES MASALA 50G', 'productPool/1.jpg', 23 ),
( 'KWALITY PASTA MASALA 50G', 'productPool/1.jpg', 185 ),
( 'KWALITY WASTE BASKET NET BIG', 'productPool/1.jpg', 213 ),
( 'KWALITY WASTE BASKET NET SMALL', 'productPool/1.jpg', 173 ),
( 'KWIKNIC NICOTINE GUM MINT 2MG', 'productPool/1.jpg', 130 ),
( 'KWIKNIC NICOTINE GUM PAAN 2MG', 'productPool/1.jpg', 72 ),
( 'L G KAYAM KATTA 50G', 'productPool/1.jpg', 218 ),
( 'L G KAYAM POWDER 50G', 'productPool/1.jpg', 216 ),
( 'L.P DUMPER', 'productPool/1.jpg', 143 ),
( 'LA TORRENTE PEELED TOMATOES 400G', 'productPool/1.jpg', 13 ),
( 'LACTO CALAMINE SKIN LOTION 30ML', 'productPool/1.jpg', 81 ),
( 'LACTO CALAMINE GLYCERIN 60ML', 'productPool/1.jpg', 171 ),
( 'LACTO CALAMINE HYDRATION 120ML', 'productPool/1.jpg', 87 ),
( 'LACTO CALAMINE HYDRATION 60ML', 'productPool/1.jpg', 63 ),
( 'LACTO CALAMINE OIL CONTROL 120 ML', 'productPool/1.jpg', 242 ),
( 'LACTO CALAMINE OIL CONTROL 120ML', 'productPool/1.jpg', 112 ),
( 'LACTO CALAMINE OIL CONTROL 30ML', 'productPool/1.jpg', 97 ),
( 'LACTO HYDRATION 60ML', 'productPool/1.jpg', 264 ),
( 'LADIES COMB', 'productPool/1.jpg', 267 ),
( 'LADIES FINGER', 'productPool/1.jpg', 113 ),
( 'LAKEROL CAR SHAMPOO 200ML', 'productPool/1.jpg', 84 ),
( 'LAKEROL CAR SHAMPOO 400ml', 'productPool/1.jpg', 250 ),
( 'LAKME 9 TO 5 FOUNDATION 29G', 'productPool/1.jpg', 89 ),
( 'LAKME 9TO5 CC COMPLEXION CARE CREAM', 'productPool/1.jpg', 191 ),
( 'LAKME BLUSH GLOW CREME FACE WASH 100G', 'productPool/1.jpg', 271 ),
( 'LAKME BLUSH GLOW CREME FACE WASH 50G', 'productPool/1.jpg', 166 ),
( 'LAKME BLUSH GLOW FACE WASH 100G', 'productPool/1.jpg', 119 ),
( 'LAKME BLUSH GLOW FACE WASH 50G', 'productPool/1.jpg', 14 ),
( 'LAKME COMPACT CORAL', 'productPool/1.jpg', 94 ),
( 'LAKME COMPACT MARBLE', 'productPool/1.jpg', 49 ),
( 'LAKME COMPACT PEARL', 'productPool/1.jpg', 174 ),
( 'LAKME COMPACT SHELL', 'productPool/1.jpg', 123 ),
( 'LAKME DUAL SHARPENER', 'productPool/1.jpg', 275 ),
( 'LAKME DUSKY LIQUID FOUNDATION 27ML', 'productPool/1.jpg', 251 ),
( 'LAKME EYEBROW PENCIL', 'productPool/1.jpg', 228 ),
( 'LAKME EYE CONIC BLACK MASCARA 9ML', 'productPool/1.jpg', 87 ),
( 'LAKME FAIR SKIN FOUNDATION LIQUID 27ML', 'productPool/1.jpg', 38 ),
( 'LAKME FAIR TO WHEATISH LIQUID FOUNDATION', 'productPool/1.jpg', 85 ),
( 'LAKME INSTA LINER 9ML', 'productPool/1.jpg', 276 ),
( 'LAKME INSTA LINER G1 9ML', 'productPool/1.jpg', 66 ),
( 'LAKME INSTA LINER S1 9ML', 'productPool/1.jpg', 91 ),
( 'LAKME KAJAL2G', 'productPool/1.jpg', 181 ),
( 'LAKME LIP LOVE CHERRY 3.8G', 'productPool/1.jpg', 47 ),
( 'LAKME MOISTURISER PEACH MILK 120ML', 'productPool/1.jpg', 4 ),
( 'LAKME MOISTURISER PEACH MILK 60ML', 'productPool/1.jpg', 1 ),
( 'LAKME MOISTURISER WINTER INTENSE 120ML', 'productPool/1.jpg', 41 ),
( 'LAKME NAIL COLOR REMOVER 27ML', 'productPool/1.jpg', 90 ),
( 'LAKME NAIL COLOUR', 'productPool/1.jpg', 54 ),
( 'LAKME PEACH GEL FACEWASH 50G', 'productPool/1.jpg', 89 ),
( 'LAKME PEACH GELFACEWASH 100G', 'productPool/1.jpg', 197 ),
( 'LAKME PEACH MILK SOFT CREAM 250G', 'productPool/1.jpg', 153 ),
( 'LAKME PERFECT RADIANCE DAY CREAM 15G', 'productPool/1.jpg', 66 ),
( 'LAKME SUN EXPERT FAIRNESS LOTION60ML', 'productPool/1.jpg', 113 ),
( 'LAKME SUN EXPERT SPF LOTION 120ML', 'productPool/1.jpg', 242 ),
( 'LAKME WHEATISH LIQUID FOUNDATION 27 ML', 'productPool/1.jpg', 205 ),
( 'LAKSHMITHARU DAHASAMANI KIZHI 6NOS', 'productPool/1.jpg', 269 ),
( 'LAMP WICK 50GM RS 25', 'productPool/1.jpg', 257 ),
( 'LANBO BROWN PAPER 55CM', 'productPool/1.jpg', 248 ),
( 'LAPIZ LAZULI ASSOTED OVAL CHOCOLATE 200G', 'productPool/1.jpg', 24 ),
( 'LAPIZ LAZULI ASSOTED SQUARE CHOCOLATE 200G', 'productPool/1.jpg', 60 ),
( 'LAPIZ LAZULI CHOCOLATE ASSORTED 200G', 'productPool/1.jpg', 135 ),
( 'LAPIZ LAZULI CHOCOLATE ASSORTED 220G', 'productPool/1.jpg', 79 ),
( 'LAPIZ LAZULI CHOCOLATE ASSORTED 240G', 'productPool/1.jpg', 141 ),
( 'LAPIZ LAZULI CHOCOLATE ASSORTED SQUARE 200G', 'productPool/1.jpg', 72 ),
( 'LAPIZ LAZULI CHOCOLATE COCONUT 220G', 'productPool/1.jpg', 28 ),
( 'LAPIZ LAZULI CHOCOLATE HAZELNUT 240G', 'productPool/1.jpg', 143 ),
( 'LAPIZ LAZULI CHOCOLATE MANGO 200G', 'productPool/1.jpg', 54 ),
( 'LAPIZ LAZULI CHOCOLATE ORANGE 220G', 'productPool/1.jpg', 79 ),
( 'LAPIZ LAZULI CHOCOLATE ORANGE 240G', 'productPool/1.jpg', 167 ),
( 'LAPIZ LAZULI CHOCOLATE ROUND STRAWBERRY 220G', 'productPool/1.jpg', 22 ),
( 'LAPIZ LAZULI CHOCOLATE STRAWBERRY 200G', 'productPool/1.jpg', 99 ),
( 'LAPIZ LAZULI COCONUT 200G', 'productPool/1.jpg', 3 ),
( 'LAPIZ LAZULI CURVED SQUARE HAZLENUT200G', 'productPool/1.jpg', 96 ),
( 'LAPIZ LAZULI MANGO OVAL CHOCOLATE 200G', 'productPool/1.jpg', 188 ),
( 'LAPIZ LAZULI MANGO SQUARE CHOCOLATE 200G', 'productPool/1.jpg', 130 ),
( 'LAPIZ LAZULI OCTAGON HAZLENUT 200G', 'productPool/1.jpg', 268 ),
( 'LAPIZ LAZULI ORANGE OVAL CHOCOLATE 200G', 'productPool/1.jpg', 116 ),
( 'LAPIZ LAZULI ORANGE SQUARE CHOCOLATE 200G', 'productPool/1.jpg', 54 ),
( 'LAPIZ LAZULI ORUNG 200G', 'productPool/1.jpg', 152 ),
( 'LAPIZ LAZULI SMALL ROUND MANGO 240G', 'productPool/1.jpg', 235 ),
( 'LAPIZ LAZULI SMALL STRWBERY 240 G', 'productPool/1.jpg', 35 ),
( 'LAPIZ LAZULI STRAWBERRY200 G', 'productPool/1.jpg', 277 ),
( 'LAPIZ LAZULI STRAWBERY OVAL CHOCOLATE 200G', 'productPool/1.jpg', 96 ),
( 'LAPIZ LAZULI STRAWBERY SQUARE CHOCOLATE 200G', 'productPool/1.jpg', 192 ),
( 'LAROME BODY SPARY AMOUR150ML', 'productPool/1.jpg', 208 ),
( 'LAROME BODY SPARY FIRST LOVE 150ML', 'productPool/1.jpg', 241 ),
( 'LAROME BODY SPARY REBEL MEN 150ML', 'productPool/1.jpg', 218 ),
( 'LAVANDER LIQUID 975 ML', 'productPool/1.jpg', 24 ),
( 'LAVANYA IDIYAPPAM MURUKKU 200 GMS', 'productPool/1.jpg', 78 ),
( 'LAVANYA MURUKKU 10NOS', 'productPool/1.jpg', 18 ),
( 'LAVANYA PIECE MURUKKU 200G', 'productPool/1.jpg', 254 ),
( 'LAVIAN BLACK FOREST CHOCOLATE 412.5G', 'productPool/1.jpg', 198 ),
( 'LAVIAN CHOKITO CARAMELL CHOCOLATE 168G', 'productPool/1.jpg', 203 ),
( 'LAVIAN CHOKITO HAZELNUT CHOCOLATE 168G', 'productPool/1.jpg', 214 ),
( 'LAVIAN CHOKITO MILK CHOCOLATE 168G', 'productPool/1.jpg', 202 ),
( 'LAXMAN REKHA COCKE ROCH KILLER', 'productPool/1.jpg', 3 ),
( 'LAXMAN REKHA SPRAY 300ML', 'productPool/1.jpg', 98 ),
( 'LAYS AMERICAN CREAM ONION28G', 'productPool/1.jpg', 99 ),
( 'LAYS AMERICAN ONION FIAVOUR', 'productPool/1.jpg', 116 ),
( 'LAYS AMERICAN STYLE CREAM AND ONION 95G', 'productPool/1.jpg', 246 ),
( 'LAYS CLASSIC SALT 25G', 'productPool/1.jpg', 182 ),
( 'LAYS CLASSIC SALT 95G', 'productPool/1.jpg', 49 ),
( 'LAYS CLASSIC SALTED 28G', 'productPool/1.jpg', 139 ),
( 'LAYS HOT N SWEET CHILLI 28G', 'productPool/1.jpg', 35 ),
( 'LAYS HOT N SWEET CHILLI 29.5G', 'productPool/1.jpg', 41 ),
( 'LAYS HOT SWEET CHILY 25G', 'productPool/1.jpg', 252 ),
( 'LAYS INDIA MAGIC MASALA 25G', 'productPool/1.jpg', 62 ),
( 'LAYS INDIA MAGIC MASALA 52 G', 'productPool/1.jpg', 157 ),
( 'LAYS MAGIC MASALA 90G', 'productPool/1.jpg', 75 ),
( 'LAYS MAX CHILLI', 'productPool/1.jpg', 201 ),
( 'LAYS MAX HOT N SOUR', 'productPool/1.jpg', 146 ),
( 'LAYS MAXX BARBEQUE', 'productPool/1.jpg', 71 ),
( 'LAYS MAXX MACHO CHILLI 25G', 'productPool/1.jpg', 82 ),
( 'LAYS MAXX POTATO CHIPS63GM', 'productPool/1.jpg', 106 ),
( 'LAYS SALTED', 'productPool/1.jpg', 81 ),
( 'LAYS SPAINISH TOMATO 25G', 'productPool/1.jpg', 89 ),
( 'LAYS SPANISH TOMATO 28G', 'productPool/1.jpg', 189 ),
( 'LAYS SPANISH TOMATO TANGO 90G', 'productPool/1.jpg', 244 ),
( 'LAYS SPNISH TOMATO TAGO 52G', 'productPool/1.jpg', 94 ),
( 'LAYS WAFER STYLE SUNDRIED CHILLI 28G', 'productPool/1.jpg', 120 ),
( 'LAYS WAFER STYLE WITH PEPPER 28G', 'productPool/1.jpg', 2 ),
( 'LAZZA BUTTER SCOTCH CARAMEL 1L', 'productPool/1.jpg', 87 ),
( 'LAZZA BUTTER SCOTCH CARAMEL 500ML', 'productPool/1.jpg', 48 ),
( 'LAZZA CHOCOBAR POUCH BIG', 'productPool/1.jpg', 106 ),
( 'LAZZA CONE CUP BUTTERSCOTCH 120ML', 'productPool/1.jpg', 97 ),
( 'LAZZA CONE CUP CHOCOLATE 120ML', 'productPool/1.jpg', 168 ),
( 'LAZZA DESSERT MIST STRAWBERRY 100ML', 'productPool/1.jpg', 217 ),
( 'LAZZA FUNDAE CHOCOLATE PASSION 100ML', 'productPool/1.jpg', 124 ),
( 'LAZZA ICE CREAM CHOCOLATE 500ML', 'productPool/1.jpg', 164 ),
( 'LAZZA ICE CREAM GUD BUD 150ML', 'productPool/1.jpg', 148 ),
( 'LAZZA ICE CREAM PISTA GREEN 1L', 'productPool/1.jpg', 49 ),
( 'LAZZA ICE CREAM PISTA GREEN 500ML', 'productPool/1.jpg', 187 ),
( 'LAZZA ICE CREAM STRAWBERRY 1L', 'productPool/1.jpg', 153 ),
( 'LAZZA ICE CREAM STRAWBERRY 500ML', 'productPool/1.jpg', 21 ),
( 'LAZZA ICE CREAM VANILLA 1L', 'productPool/1.jpg', 44 ),
( 'LAZZA ICE CREAM VANILLA 500ML', 'productPool/1.jpg', 225 ),
( 'LAZZA ITALIAN DELITE 500ML', 'productPool/1.jpg', 176 ),
( 'LAZZA MAGNUM MANGO POUCH', 'productPool/1.jpg', 251 ),
( 'LAZZA MANGO ALPHONSO 500ML', 'productPool/1.jpg', 158 ),
( 'LAZZA TENDER COCONUT 500ML', 'productPool/1.jpg', 210 ),
( 'LAZZA TENDER COCONUT ICE CREAM 1L', 'productPool/1.jpg', 83 ),
( 'LAZZA VANILLA BALL 100ML', 'productPool/1.jpg', 174 ),
( 'LEAF AND RELIEF ARROWROOT POWDER 50G', 'productPool/1.jpg', 134 ),
( 'LEAF BROOM', 'productPool/1.jpg', 78 ),
( 'LEAF N RELIEF ALMOND OIL 50ML', 'productPool/1.jpg', 12 ),
( 'LEAF N RELIEF ALOEVERA GEL 50G', 'productPool/1.jpg', 6 ),
( 'LEAF N RELIEF AMUKKURAM POWDER 100G', 'productPool/1.jpg', 206 ),
( 'LEAF N RELIEF BLACK SEED OIL 60ML', 'productPool/1.jpg', 39 ),
( 'LEAF N RELIEF CARDOMOM POWDER 8GM', 'productPool/1.jpg', 117 ),
( 'LEAF N RELIEF CASTAR OIL 100ML', 'productPool/1.jpg', 93 ),
( 'LEAF N RELIEF CASTOR OIL 60ML', 'productPool/1.jpg', 147 ),
( 'LEAF N RELIEF CHUKKU KAPPI', 'productPool/1.jpg', 17 ),
( 'LEAF N RELIEF FLAX SEED 300G', 'productPool/1.jpg', 239 ),
( 'LEAF N RELIEF HENNA POWDER 35G', 'productPool/1.jpg', 115 ),
( 'LEAF N RELIEF INDUPP 200G', 'productPool/1.jpg', 185 ),
( 'LEAF N RELIEF KUNTHIRIKKAM 50G', 'productPool/1.jpg', 143 ),
( 'LEAF N RELIEF NEELAYAMARI POWDER 35G', 'productPool/1.jpg', 27 ),
( 'LEAF N RELIEF NEEM LEAF POWDER 35G', 'productPool/1.jpg', 168 ),
( 'LEAF N RELIEF NEEM OIL 100ML', 'productPool/1.jpg', 134 ),
( 'LEAF N RELIEF NEEM OIL 60ML', 'productPool/1.jpg', 65 ),
( 'LEAF N RELIEF OLIVE OIL 100ML', 'productPool/1.jpg', 59 ),
( 'LEAF N RELIEF ORANGE POWDER 35G', 'productPool/1.jpg', 81 ),
( 'LEAF N RELIEF PALKAYAM 10G', 'productPool/1.jpg', 203 ),
( 'LEAF N RELIEF PALKAYAM 10GM', 'productPool/1.jpg', 117 ),
( 'LEAF N RELIEF PANAMKALKANDAM 100G', 'productPool/1.jpg', 143 ),
( 'LEAF N RELIEF SHIKAKAI POWDER', 'productPool/1.jpg', 116 ),
( 'LEAF N RELIIEF CASTOR OIL 100ML', 'productPool/1.jpg', 164 ),
( 'LEAF N RELIIEF EUCALYPTUS OIL 25ML', 'productPool/1.jpg', 32 ),
( 'LEAF N RELIIEF SAMBRANI 50GM', 'productPool/1.jpg', 121 ),
( 'LEAF TEA 250G RIPPLE', 'productPool/1.jpg', 217 ),
( 'LEAF TEA 500G RIPPLE', 'productPool/1.jpg', 164 ),
( 'LEAF&RELIEF GREEN GRAM POWDER 35GMS', 'productPool/1.jpg', 168 ),
( 'LEAF&RELIEF KASTHOORI POWDER 35GMS', 'productPool/1.jpg', 12 ),
( 'LEAF&RELIEF MULTANIMITTI PLUS 35GMS', 'productPool/1.jpg', 146 ),
( 'LEAF&RELIEF PACHAMANJAL 20G', 'productPool/1.jpg', 238 ),
( 'LEEKS', 'productPool/1.jpg', 235 ),
( 'LEHAR EVERVESS SODA 2000ML', 'productPool/1.jpg', 78 ),
( 'LEHAR EVERVESS SODA 750ML', 'productPool/1.jpg', 93 );