INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'MAYBELLINE BABY LIPS HIGHLINE WINE 8G', 'productPool/1.jpg', 98 ),
( 'MAYBELLINE BABY LIPS MH 8G', 'productPool/1.jpg', 13 ),
( 'MAYBELLINE BABY LIPS PINK LOLITA', 'productPool/1.jpg', 205 ),
( 'MAYBELLINE BABY LIPSPINK LOLITA 8G', 'productPool/1.jpg', 47 ),
( 'MAYBELLINE BABYLIPS BB 4G+9ML', 'productPool/1.jpg', 11 ),
( 'MAYBELLINE FIT ME COMPACT POWDER 8G', 'productPool/1.jpg', 119 ),
( 'MAYBELLINE PINK ALERT LIP BALM 1.9G', 'productPool/1.jpg', 69 ),
( 'MAYOR WASHING BRUSH', 'productPool/1.jpg', 193 ),
( 'MB BABY LIP COLOUR PEACH BLOOM 1.7G', 'productPool/1.jpg', 72 ),
( 'MB BABY LIP COLOUR STRIKING ORANGE 1.7G', 'productPool/1.jpg', 85 ),
( 'MB BABY LIPS COLOUR PINK', 'productPool/1.jpg', 223 ),
( 'MB COMPACT 109 LIGHT IVORY', 'productPool/1.jpg', 64 ),
( 'MB EXPORT RICE 50KG', 'productPool/1.jpg', 143 ),
( 'MB WHITE SUPERFRESH CORAL 8G', 'productPool/1.jpg', 32 ),
( 'MB WHITE SUPERFRESH PEARL 8G', 'productPool/1.jpg', 217 ),
( 'MB WHITE SUPERFRESH SHELL8G', 'productPool/1.jpg', 16 ),
( 'MBBABY LIP COLOUR VIVID PEACH 1.7G', 'productPool/1.jpg', 25 ),
( 'MC VITIES DIGEST 500G', 'productPool/1.jpg', 249 ),
( 'MC VITIES DIGEST LIG250G', 'productPool/1.jpg', 58 ),
( 'MC VITIES DIGESTIVE BISCUITS ORGINAL 500G', 'productPool/1.jpg', 33 ),
( 'MC VITIES DIGESTIVE250G', 'productPool/1.jpg', 263 ),
( 'MC VITIES DIGESTLIGH400G', 'productPool/1.jpg', 146 ),
( 'MCCAIN FRENCH FRIES 200G', 'productPool/1.jpg', 194 ),
( 'MCCAIN FRENCH FRIES 420G', 'productPool/1.jpg', 173 ),
( 'MCCAIN SMILES 415G', 'productPool/1.jpg', 209 ),
( 'MCCAIN SUPER WEDGES 400G', 'productPool/1.jpg', 114 ),
( 'MCCAIN VEGGIE FINGERS 400G', 'productPool/1.jpg', 37 ),
( 'MCDOWELLS SODA 1.5L', 'productPool/1.jpg', 20 ),
( 'MCDOWELLS SODA 600ML', 'productPool/1.jpg', 119 ),
( 'MCV DIGESTIVE MILK CHOCOLATE 200G', 'productPool/1.jpg', 161 ),
( 'MCVITIES BUTTER COOKIES 200G', 'productPool/1.jpg', 127 ),
( 'MCVITIES DIGESTIVE DARK CHOCOLATE 200G', 'productPool/1.jpg', 2 ),
( 'MCVITIES FRUIT SHORTCAKE', 'productPool/1.jpg', 36 ),
( 'MCVITIES HOBNOBS MILK CHOCOLATE 300G', 'productPool/1.jpg', 81 ),
( 'MCVITIES HOBNOBS OAT BISCUIT 300G', 'productPool/1.jpg', 160 ),
( 'ME TOO THIRUNELVELI HALWA 200G', 'productPool/1.jpg', 3 ),
( 'MEASUREMENT CUP SSU', 'productPool/1.jpg', 135 ),
( 'MEASUREMENT SCOOP', 'productPool/1.jpg', 126 ),
( 'MEAT BURGER', 'productPool/1.jpg', 110 ),
( 'MEAT MASALA 100G', 'productPool/1.jpg', 277 ),
( 'MEDELY PKT IMP', 'productPool/1.jpg', 202 ),
( 'MEDI GLOW WASHING SOAP 200G', 'productPool/1.jpg', 93 ),
( 'MEDIKER OIL 50ML', 'productPool/1.jpg', 24 ),
( 'MEDIKER TREAT 50 ML', 'productPool/1.jpg', 266 ),
( 'MEDILICE 30G', 'productPool/1.jpg', 216 ),
( 'MEDILOGY LAVENDER TALC 125G', 'productPool/1.jpg', 203 ),
( 'MEDILOGY LOGITICK POWDER', 'productPool/1.jpg', 196 ),
( 'MEDILOGY MEDIBATH SOAP', 'productPool/1.jpg', 250 ),
( 'MEDILOGY ROSE & SANDAL TALC 125G', 'productPool/1.jpg', 47 ),
( 'MEDIMIX AYURVEDIC SOAP 4*75G', 'productPool/1.jpg', 7 ),
( 'MEDIMIX AYURVEDIC SOAP MULTIPACK RS-100', 'productPool/1.jpg', 119 ),
( 'MEDIMIX CLASSIC SOAP 125G', 'productPool/1.jpg', 125 ),
( 'MEDIMIX CLASSIC SOAP 75G', 'productPool/1.jpg', 126 ),
( 'MEDIMIX CLEAR GLYCERINE FACE WASH 50G', 'productPool/1.jpg', 115 ),
( 'MEDIMIX CLEAR GLYCERINE GREEN 100G', 'productPool/1.jpg', 245 ),
( 'MEDIMIX FACEWASH OIL BALANCE 50G', 'productPool/1.jpg', 237 ),
( 'MEDIMIX GLYCERINE OIL BALANCE 100G', 'productPool/1.jpg', 262 ),
( 'MEDIMIX HERBAL HANAWASH 1LITRE', 'productPool/1.jpg', 108 ),
( 'MEDIMIX HERBAL HANDWASH 250ML', 'productPool/1.jpg', 79 ),
( 'MEDIMIX HERBEL HANDWASH200ML', 'productPool/1.jpg', 89 ),
( 'MEDIMIX MULTI GREEN SOAP 4*100G', 'productPool/1.jpg', 104 ),
( 'MEDIMIX NATURAL TONING HONEY SOAP 4*100G', 'productPool/1.jpg', 24 ),
( 'MEDIMIX NATURAL TONING SOAP 100G', 'productPool/1.jpg', 246 ),
( 'MEDIMIX OIL BALANCE SOAP 4*100G', 'productPool/1.jpg', 66 ),
( 'MEDIMIX SANDAL 125G MULTI PACK', 'productPool/1.jpg', 254 ),
( 'MEDIMIX SANDAL HANAWASH 1LITRE', 'productPool/1.jpg', 69 ),
( 'MEDIMIX SANDAL HANDWASH 200ML POUCH', 'productPool/1.jpg', 140 ),
( 'MEDIMIX SANDAL HANDWASH 250ML', 'productPool/1.jpg', 91 ),
( 'MEDIMIX SANDAL SOAP 125G', 'productPool/1.jpg', 56 ),
( 'MEDIMIX SANDAL SOAP 4*125G', 'productPool/1.jpg', 126 ),
( 'MEDIMIX SANDAL SOAP 75GM', 'productPool/1.jpg', 139 ),
( 'MEDIMIX TRANSPARENT 75GM', 'productPool/1.jpg', 139 ),
( 'MEDIMIX TRANSPARENT SOAP 125G', 'productPool/1.jpg', 74 ),
( 'MEDIMIX TRANSPARENT SOAP 125G*3', 'productPool/1.jpg', 14 ),
( 'MEDIMIX TRANSPARENT SOAP 4*125G', 'productPool/1.jpg', 76 ),
( 'MEDIVILA NEEM ALOEVERA DOG SHAMPOO 200ML', 'productPool/1.jpg', 144 ),
( 'MEDLEY PREMIUM CHOCOLATE 102.6G', 'productPool/1.jpg', 224 ),
( 'MEERA AGRA PEDA 1KG', 'productPool/1.jpg', 237 ),
( 'MEERA ALMOND DATES 250G', 'productPool/1.jpg', 209 ),
( 'MEERA ORIGINAL DATES GREEN 250G', 'productPool/1.jpg', 270 ),
( 'MEERA ORIGINAL DATES GREEN 500G', 'productPool/1.jpg', 258 ),
( 'MEERA RAISINS POUCH 200G', 'productPool/1.jpg', 269 ),
( 'MEGA PIXEL HOOK 6', 'productPool/1.jpg', 58 ),
( 'MELAM APPAM IDIAPPAM PODI 1KG', 'productPool/1.jpg', 1 ),
( 'MELAM BLACK PEPPER 100G', 'productPool/1.jpg', 236 ),
( 'MELAM BLACK PEPPER POWDER 50G', 'productPool/1.jpg', 179 ),
( 'MELAM CHICKEN MASALA 100GM', 'productPool/1.jpg', 258 ),
( 'MELAM CORIANDER POWDER 100GM', 'productPool/1.jpg', 241 ),
( 'MELAM CORIANDER POWDER 250G', 'productPool/1.jpg', 239 ),
( 'MELAM CUMIN POWDER 100G', 'productPool/1.jpg', 15 ),
( 'MELAM EASY PALADA MIX 200G', 'productPool/1.jpg', 61 ),
( 'MELAM EGG CURRY ROAST MASALA 100G', 'productPool/1.jpg', 162 ),
( 'MELAM FISH FRY MASALA 100G', 'productPool/1.jpg', 157 ),
( 'MELAM FISH MASALA 100G', 'productPool/1.jpg', 152 ),
( 'MELAM GARAM MASALA 100GM', 'productPool/1.jpg', 16 ),
( 'MELAM GINGER POWDER 100G', 'productPool/1.jpg', 148 ),
( 'MELAM KASHMIRI CHILLI POWDER 100G', 'productPool/1.jpg', 28 ),
( 'MELAM KASHMIRI CHILLI POWDER 250G', 'productPool/1.jpg', 12 ),
( 'MELAM KERALA SAMBAR 100G', 'productPool/1.jpg', 110 ),
( 'MELAM MEAT MASALA 100G', 'productPool/1.jpg', 241 ),
( 'MELAM PUTTUPODI 1KG', 'productPool/1.jpg', 129 ),
( 'MELAM PUTTUPODI 500G', 'productPool/1.jpg', 176 ),
( 'MELAM RICE POWDER 500G', 'productPool/1.jpg', 183 ),
( 'MELAM ROASTED RAVA 1KG', 'productPool/1.jpg', 69 ),
( 'MELAM ROASTED RAVA 500G', 'productPool/1.jpg', 218 ),
( 'MELAM TURMERIC POWDER 100G', 'productPool/1.jpg', 159 ),
( 'MELAM TURMERIC POWDER 250G', 'productPool/1.jpg', 139 ),
( 'MELAM VARUTHARACHA KOZHI CURRY 100G', 'productPool/1.jpg', 124 ),
( 'MELAM VEGETABLE MASALA 100G', 'productPool/1.jpg', 252 ),
( 'MENTOS ASSORTED FLAVOURS', 'productPool/1.jpg', 101 ),
( 'MENTOS MARBLES', 'productPool/1.jpg', 25 ),
( 'MERA ALMOND DATES 350 GMS', 'productPool/1.jpg', 27 ),
( 'MERA CASHEW DATES 350GMS', 'productPool/1.jpg', 121 ),
( 'MERA MIXED DRY FRUIT', 'productPool/1.jpg', 204 ),
( 'MERA PERSIAN DATES RED 250G', 'productPool/1.jpg', 212 ),
( 'MERA PREMIUM DATES 250 GMS', 'productPool/1.jpg', 27 ),
( 'MERA PREMIUM DATES 350 GMS', 'productPool/1.jpg', 54 ),
( 'MERA PREMIUM DATES 500GMS', 'productPool/1.jpg', 120 ),
( 'MERA PREMIUM DATES RED 500G', 'productPool/1.jpg', 157 ),
( 'MERA RAISINS 300G', 'productPool/1.jpg', 38 ),
( 'MERIBOY PINEAPPLE BAR', 'productPool/1.jpg', 119 ),
( 'MERRIBOY BLUEBERRY PREMIUM', 'productPool/1.jpg', 23 ),
( 'MERRIBOY FRUBA STRAWBERRY 60ML', 'productPool/1.jpg', 161 ),
( 'MERRIBOY ICE CREAM BLACK CURRANT 1L', 'productPool/1.jpg', 51 ),
( 'MERRIBOY ICE CREAM BLACKCURRANT 500ML', 'productPool/1.jpg', 94 ),
( 'MERRIBOY ICE CREAM BLUEBERRY 1L', 'productPool/1.jpg', 46 ),
( 'MERRIBOY ICE CREAM JACK FRUIT 500ML', 'productPool/1.jpg', 138 ),
( 'MERRIBOY ICE CREAM KIWI 1L', 'productPool/1.jpg', 122 ),
( 'Merriboy ice Cream Passion fruit', 'productPool/1.jpg', 31 ),
( 'MERRIBOY ICE CREAM SPANISH DELIGHT 500ML', 'productPool/1.jpg', 192 ),
( 'MERRIBOY ICE CREAM TENDER COCONUT 500ML', 'productPool/1.jpg', 17 ),
( 'MERRIBOY JACK FRUIT ICE CREAM 500 ML', 'productPool/1.jpg', 174 ),
( 'MERRIBOY MANGO MILK LOLLY 40G', 'productPool/1.jpg', 75 ),
( 'MERRIBOY MANGO SHOPE', 'productPool/1.jpg', 246 ),
( 'MERRIBOY PASSION FRUIT 1 LTR', 'productPool/1.jpg', 144 ),
( 'MERRIBOY PINEAPPLE PREMIUM 1 LTR', 'productPool/1.jpg', 261 ),
( 'MERRIBOY POPYCONE VANNILA', 'productPool/1.jpg', 158 ),
( 'MERRIIBOY ALPHNSO MANGO 500ML', 'productPool/1.jpg', 163 ),
( 'MERRIIBOY CHOCOLATE 500ML', 'productPool/1.jpg', 76 ),
( 'MERRIIBOY CHOCOLATE TUB 1 LTR', 'productPool/1.jpg', 136 ),
( 'MERRIIBOY STRAWBERRY 500ML', 'productPool/1.jpg', 203 ),
( 'MERRIIBOY VANNILA BALL', 'productPool/1.jpg', 244 ),
( 'MERRYBOY ALPHONSO MANGO 1000ML', 'productPool/1.jpg', 57 ),
( 'MERRYBOY BABY RICHY 84ML', 'productPool/1.jpg', 62 ),
( 'MERRYBOY BUTTER SCOTCH 1000ML', 'productPool/1.jpg', 149 ),
( 'MERRYBOY BUTTERSCOTCH 500ML', 'productPool/1.jpg', 221 ),
( 'MERRYBOY CHOCOBAR 45 GM', 'productPool/1.jpg', 8 ),
( 'MERRYBOY CHOCOLATE ICECREAM 1000ML', 'productPool/1.jpg', 123 ),
( 'MERRYBOY CONEFETTI BUTTERSCOTCH', 'productPool/1.jpg', 54 ),
( 'MERRYBOY CONEFETTI VANNILLA', 'productPool/1.jpg', 121 ),
( 'MERRYBOY CONFETTI CHOCO', 'productPool/1.jpg', 93 ),
( 'MERRYBOY CUP STRAWBERRY 125 ML', 'productPool/1.jpg', 224 ),
( 'MERRYBOY FRUBA GRAPE BAR', 'productPool/1.jpg', 208 ),
( 'MERRYBOY FRUBA MANGO 60 ML', 'productPool/1.jpg', 227 ),
( 'MERRYBOY JACKFRUIT ICECREAM 1000ML', 'productPool/1.jpg', 63 ),
( 'MERRYBOY MILK LOLLY MANGO', 'productPool/1.jpg', 61 ),
( 'MERRYBOY MILK LOLLY STRAWBERRY', 'productPool/1.jpg', 232 ),
( 'MERRYBOY PISTA 1000 ML', 'productPool/1.jpg', 168 ),
( 'MERRYBOY PISTA SIPUP', 'productPool/1.jpg', 194 ),
( 'MERRYBOY SPECIAL SUNDAY PISTA', 'productPool/1.jpg', 138 ),
( 'MERRYBOY SPECIAL SUNDAY STRAWBERRY', 'productPool/1.jpg', 117 ),
( 'MERRYBOY STRAWBERRY 1000ML', 'productPool/1.jpg', 209 ),
( 'MERRYBOY STRAWBERRY 500ML', 'productPool/1.jpg', 209 ),
( 'MERRYBOY SUNDAE PISTA', 'productPool/1.jpg', 30 ),
( 'MERRYBOY TENDER COCONUT 1000ML', 'productPool/1.jpg', 155 ),
( 'MERRYBOY TUB CHIKOO 1 LTR', 'productPool/1.jpg', 87 ),
( 'MERRYBOY VANILLA 1000 ML', 'productPool/1.jpg', 231 ),
( 'MERRYBOY VANILLA 500ML', 'productPool/1.jpg', 209 ),
( 'MERRYBOY VANILLA CUP', 'productPool/1.jpg', 202 ),
( 'MERRYS ANNAM KALIYODAKKA 180G', 'productPool/1.jpg', 209 ),
( 'MERRYS AVLOSE UNDA 12N', 'productPool/1.jpg', 179 ),
( 'MERRYS BLACK SEASAME BALL 100G', 'productPool/1.jpg', 237 ),
( 'MERRYS HEALTH MIX 500G', 'productPool/1.jpg', 143 ),
( 'MERRYS HEALTH MIX POWDER 400G', 'productPool/1.jpg', 250 ),
( 'MERRYS RICE FLAKES BALL', 'productPool/1.jpg', 150 ),
( 'MERRYS WHITE SEASAME BALL 100G', 'productPool/1.jpg', 2 ),
( 'METHRAN KAYAL RICE 10KG', 'productPool/1.jpg', 88 ),
( 'METHRAN KAYAL RICE 5KG', 'productPool/1.jpg', 182 ),
( 'MICKEY BAG', 'productPool/1.jpg', 239 ),
( 'MICKEY ROUND COMB', 'productPool/1.jpg', 211 ),
( 'MICKY SUMMER COMB', 'productPool/1.jpg', 220 ),
( 'MIDO CHOCOLATE ECLAIRS 750G', 'productPool/1.jpg', 201 ),
( 'MIDO HONEY ECLAIRS 750G', 'productPool/1.jpg', 158 ),
( 'MIDO MILK ECLAIRS 750G', 'productPool/1.jpg', 53 ),
( 'MIGHTY BITE THATTA 210G', 'productPool/1.jpg', 72 ),
( 'MIGHTY BITE THATTA 225G', 'productPool/1.jpg', 23 ),
( 'MIKYMIST CHEESE CUBE 120G', 'productPool/1.jpg', 149 ),
( 'MIKYMIST FRUIT YOGURT GUAVA', 'productPool/1.jpg', 96 ),
( 'MILACO 10 INCH ROUND PLATE 25PCS', 'productPool/1.jpg', 121 ),
( 'MILANO CENTRE FILLED COMBO 225G', 'productPool/1.jpg', 232 ),
( 'MILANO CHOCCOLATECHIP75G', 'productPool/1.jpg', 267 ),
( 'MILANO CHOCOLATE CHIP 120G', 'productPool/1.jpg', 233 ),
( 'MILANO DARK COOKIES CHOCO FILLING 75G', 'productPool/1.jpg', 107 ),
( 'MILANO MIX BERRIES 75 GM', 'productPool/1.jpg', 269 ),
( 'MILES MULTI PURPOSE 18MM', 'productPool/1.jpg', 134 ),
( 'MILI CANDY 100G POUCH', 'productPool/1.jpg', 219 ),
( 'MILI GINGER CANDY 200G', 'productPool/1.jpg', 5 ),
( 'MILK NADAN 500ML', 'productPool/1.jpg', 211 ),
( 'MILK SHAKE CHOCOLATE POWDER 300G', 'productPool/1.jpg', 259 ),
( 'MILKA ARROW ROOT BISCUITS 150G', 'productPool/1.jpg', 70 ),
( 'MILKA COCO BITS 150G', 'productPool/1.jpg', 51 ),
( 'MILKA NICE DAY ORIGINA L175G', 'productPool/1.jpg', 164 ),
( 'MILKA SOVEREIGN BISCUITS', 'productPool/1.jpg', 115 ),
( 'MILKA TOP TUCKER ZOO BISCUIT 150G', 'productPool/1.jpg', 57 ),
( 'MILKA WONDAY CASHEW BISCUITS', 'productPool/1.jpg', 20 ),
( 'MILKA WONDER CAKE ORANGE', 'productPool/1.jpg', 91 ),
( 'MILKA WONDER CHOCLATA CAKE 150G', 'productPool/1.jpg', 147 ),
( 'MILKA WONDER FRUIT CAKE 150G', 'productPool/1.jpg', 213 ),
( 'MILKA WONDER ORANGE CHOCOLATE CAKE 150G', 'productPool/1.jpg', 192 ),
( 'MILKA WONDER PINEAPPLE CAKE 150G', 'productPool/1.jpg', 175 ),
( 'MILKA WONDER STRAWBERY 150G', 'productPool/1.jpg', 186 ),
( 'MILKA WONDER VANILLA CAKE150G', 'productPool/1.jpg', 267 ),
( 'MILKOSE CHOCO MALT 200G', 'productPool/1.jpg', 91 ),
( 'MILKOSE MALTOVITA 500G REFILL', 'productPool/1.jpg', 253 ),
( 'MILKSHAKE VANILLA MIX POWDER 150G', 'productPool/1.jpg', 268 ),
( 'MILKSHAKESTRAWBERRY300G', 'productPool/1.jpg', 33 ),
( 'MILKY BAR 42G MRP 40', 'productPool/1.jpg', 36 ),
( 'MILKY BAR 6.5 G', 'productPool/1.jpg', 10 ),
( 'MILKY BAR MULTIPACK 66G', 'productPool/1.jpg', 234 ),
( 'MILKY BAR MULTIPACK 79.2G', 'productPool/1.jpg', 234 ),
( 'MILKY LAND CHOCLATE POUCH 325G', 'productPool/1.jpg', 107 ),
( 'MILKY LOLLY', 'productPool/1.jpg', 270 ),
( 'MILKY MIST BUTTER SALTED 100G', 'productPool/1.jpg', 250 ),
( 'MILKY MIST BUTTER SALTED 500G', 'productPool/1.jpg', 211 ),
( 'MILKY MIST BUTTER UNSALTED 100G', 'productPool/1.jpg', 95 ),
( 'MILKY MIST BUTTER UNSALTED 200G', 'productPool/1.jpg', 187 ),
( 'MILKY MIST BUTTER UNSALTED 500G', 'productPool/1.jpg', 37 ),
( 'Milky Mist Cheese Block 200Gms', 'productPool/1.jpg', 247 ),
( 'MILKY MIST CHEESE CUBES 200GM', 'productPool/1.jpg', 44 ),
( 'MILKY MIST CHEESE SLICE 200G', 'productPool/1.jpg', 257 ),
( 'MILKY MIST CHEESE SLICES 100G', 'productPool/1.jpg', 130 ),
( 'Milky Mist Cheese Spread', 'productPool/1.jpg', 70 ),
( 'MILKY MIST CHEESE SPREAD CHILLI CAPSICUM 200G', 'productPool/1.jpg', 97 ),
( 'MILKY MIST CURD 200G', 'productPool/1.jpg', 166 ),
( 'MILKY MIST CURD POUCH 500GM', 'productPool/1.jpg', 107 ),
( 'MILKY MIST FRESH CREAM 200ML', 'productPool/1.jpg', 237 ),
( 'MILKY MIST LASSI BLUEBERRY 150ML', 'productPool/1.jpg', 102 ),
( 'MILKY MIST LASSI MANGO 150ML', 'productPool/1.jpg', 224 ),
( 'MILKY MIST LASSI PLAIN 150ML', 'productPool/1.jpg', 8 ),
( 'MILKY MIST PANEER 200G', 'productPool/1.jpg', 133 ),
( 'MILKY MIST PANEER CUBES 200G', 'productPool/1.jpg', 143 ),
( 'MILKY MIST SET CURD 400G', 'productPool/1.jpg', 248 ),
( 'MILKY MIST SET CURD1KG', 'productPool/1.jpg', 166 ),
( 'MILKY MIST SHRIKHAND ELAICHI 400GM', 'productPool/1.jpg', 107 ),
( 'Milky Mist Shrikhand Mango 400G', 'productPool/1.jpg', 20 ),
( 'MILKY MIST SWEET LASSI STRAWBERRY 150ML', 'productPool/1.jpg', 48 ),
( 'MILKY mIST YOGHURT', 'productPool/1.jpg', 245 ),
( 'MILKY MIST YOGHURT MANGO 100G', 'productPool/1.jpg', 134 ),
( 'MILKY MIST YOGHURT Strawberry', 'productPool/1.jpg', 211 ),
( 'MILKYBAR CHOO MIX FRUIT', 'productPool/1.jpg', 17 ),
( 'MILKYMIST BUTTER CUBE 500G', 'productPool/1.jpg', 126 ),
( 'MILKYMIST CHEDDAR CHEESE 200G', 'productPool/1.jpg', 208 ),
( 'MILKYMIST CHEESE SLICE 476G', 'productPool/1.jpg', 30 ),
( 'MILKYMIST CHEESE SPREAD NATURAL 200G', 'productPool/1.jpg', 246 ),
( 'MILKYMIST CHEESE SPREAD PEPPER 200G', 'productPool/1.jpg', 85 ),
( 'MILKYMIST CHEESE SPREAD TOMATO 200G', 'productPool/1.jpg', 33 ),
( 'MILKYMIST GULAB JAMUIN MIX B1G1', 'productPool/1.jpg', 223 ),
( 'MILKYMIST MILK CREAM 200ML', 'productPool/1.jpg', 148 ),
( 'MILKYMIST MILK SHAKE CHOCOLATE', 'productPool/1.jpg', 69 ),
( 'MILKYMIST MILK SHAKE STRAWBERY', 'productPool/1.jpg', 260 ),
( 'MILKYMIST MILK SHAKE VANILA', 'productPool/1.jpg', 218 ),
( 'MILKYMIST MOZERALLA CHEESE 200G', 'productPool/1.jpg', 25 ),
( 'MILKYMIST PANEER 500GM', 'productPool/1.jpg', 123 ),
( 'MILKYMIST SHRIKHAND ELAICHI 100G', 'productPool/1.jpg', 3 ),
( 'MILKYMIST YOGURT BANANA', 'productPool/1.jpg', 100 ),
( 'MILKYMIST YOGURT MANGO', 'productPool/1.jpg', 178 ),
( 'MILKYMIST YOGURT RASBERY', 'productPool/1.jpg', 246 ),
( 'MILKYMIST YOUGHRT PINEAPPLE 100G', 'productPool/1.jpg', 278 ),
( 'MILMA GHEE 1L', 'productPool/1.jpg', 129 ),
( 'MILMA GHEE 200ML', 'productPool/1.jpg', 270 ),
( 'MILMA GHEE 500ML', 'productPool/1.jpg', 100 ),
( 'MILMA GHEE 50ML', 'productPool/1.jpg', 217 ),
( 'MILMA GHEE JAR 100ML', 'productPool/1.jpg', 217 ),
( 'MILMA GHEE JAR 1LT', 'productPool/1.jpg', 233 ),
( 'MILMA GHEE JAR 200ML', 'productPool/1.jpg', 19 ),
( 'MILMA GHEE JAR 500ML', 'productPool/1.jpg', 10 ),
( 'MILMA INSTANT SEMIYA PAYASAM MIX 250G', 'productPool/1.jpg', 79 ),
( 'Milma MILK 500ml', 'productPool/1.jpg', 237 ),
( 'MILMA MILK PEDA 200G', 'productPool/1.jpg', 240 ),
( 'MILMA PALADA MIX 200G', 'productPool/1.jpg', 235 ),
( 'MILMA PURE MILK PEDA', 'productPool/1.jpg', 232 ),
( 'MILMA WHEAT ADAPAYASAM MIX 250G', 'productPool/1.jpg', 99 ),
( 'MILTO CHAKKAVARATTY 500G', 'productPool/1.jpg', 85 ),
( 'MILTO PEDA 5 NOS', 'productPool/1.jpg', 275 ),
( 'MILTO PEDA RS 5', 'productPool/1.jpg', 125 ),
( 'MILTYON SPOTZERO MUG 1500ML', 'productPool/1.jpg', 221 ),
( 'MILYMIST YOGURT BLUEBERY', 'productPool/1.jpg', 206 ),
( 'MINI APPLE', 'productPool/1.jpg', 242 ),
( 'MINI CHICKEN', 'productPool/1.jpg', 196 ),
( 'MINI MULTI SOCKET', 'productPool/1.jpg', 51 ),
( 'MINI ORANGE', 'productPool/1.jpg', 32 ),
( 'MINI OREO CHOCOLATE 67G', 'productPool/1.jpg', 233 ),
( 'MINI OREO STRAWBERRY 67G', 'productPool/1.jpg', 187 ),
( 'MINI OREO VANILLA 67G', 'productPool/1.jpg', 264 ),
( 'MINI SAMBAR DAL 500G', 'productPool/1.jpg', 11 ),
( 'MINT CANDY 140G', 'productPool/1.jpg', 97 ),
( 'MINT CANDY 70G', 'productPool/1.jpg', 142 ),
( 'MINTO FRESH CANDY JAR 630G', 'productPool/1.jpg', 191 ),
( 'MINUTE MAID ANAR 1LTR', 'productPool/1.jpg', 228 ),
( 'MINUTE MAID APPLE 150ML', 'productPool/1.jpg', 35 ),
( 'MINUTE MAID APPLE 240ML', 'productPool/1.jpg', 106 ),
( 'MINUTE MAID APPLE 250ML', 'productPool/1.jpg', 87 ),
( 'MINUTE MAID APPLE 400ML', 'productPool/1.jpg', 51 ),
( 'MINUTE MAID APPLE JUICE 1L', 'productPool/1.jpg', 83 ),
( 'MINUTE MAID GUAVA 1LTR', 'productPool/1.jpg', 67 ),
( 'MINUTE MAID GUAVA 250ML', 'productPool/1.jpg', 77 ),
( 'MINUTE MAID LITCHI 1LTR', 'productPool/1.jpg', 3 ),
( 'MINUTE MAID MANGO 150ML', 'productPool/1.jpg', 155 ),
( 'MINUTE MAID MANGO 1LT', 'productPool/1.jpg', 61 ),
( 'MINUTE MAID MANGO 250ML', 'productPool/1.jpg', 120 ),
( 'MINUTE MAID MANGO 400ML JUICE', 'productPool/1.jpg', 72 ),
( 'MINUTE MAID MIXED FRUIT 150ML', 'productPool/1.jpg', 100 ),
( 'MINUTE MAID MIXED FRUIT 240ML', 'productPool/1.jpg', 5 ),
( 'MINUTE MAID MIXED FRUIT 250ML', 'productPool/1.jpg', 3 ),
( 'MINUTE MAID MIXED FRUIT ILT', 'productPool/1.jpg', 115 ),
( 'MINUTE MAID NIMBU FRESH 250ML', 'productPool/1.jpg', 215 ),
( 'MINUTE MAID NIMBU FRESH JUICE 400ML', 'productPool/1.jpg', 47 ),
( 'MINUTE MAID ORANGE 1L TETRA', 'productPool/1.jpg', 15 ),
( 'MINUTE MAID ORANGE 1LTR', 'productPool/1.jpg', 63 ),
( 'MINUTE MAID PULPY MOSAMBI 250ML', 'productPool/1.jpg', 50 ),
( 'MINUTE MAID PULPY MOSAMBI 400ML', 'productPool/1.jpg', 210 ),
( 'MINUTE MAID PULPY ORANGE 1LIT', 'productPool/1.jpg', 258 ),
( 'MINUTE MAID PULPY ORANGE 240ML', 'productPool/1.jpg', 152 ),
( 'MINUTE MAID PULPY ORANGE 400ML', 'productPool/1.jpg', 119 ),
( 'MINUTE MAIDMIXED FRUIT 400ML', 'productPool/1.jpg', 72 ),
( 'MINUTE PULPY ORANGE 250ML JUICE', 'productPool/1.jpg', 166 ),
( 'MIP CHILLY MURUKKU 150G', 'productPool/1.jpg', 163 ),
( 'MIP FOODS MURUKKU 150G', 'productPool/1.jpg', 28 ),
( 'MIP GARLIC MURUKKU 150G', 'productPool/1.jpg', 253 ),
( 'MIP GHEE MURUKKU 150G', 'productPool/1.jpg', 197 ),
( 'MIP KAIRALY MURUKKU 150G', 'productPool/1.jpg', 100 ),
( 'MIP KAPPA MURUKKU 150G', 'productPool/1.jpg', 89 ),
( 'MIP PIDI MURUKKU 150G', 'productPool/1.jpg', 231 ),
( 'MIRINDA ORANG EFLV 2LTR', 'productPool/1.jpg', 204 ),
( 'MIRINDA ORANGE 250ML PET', 'productPool/1.jpg', 255 ),
( 'MIRINDA ORANGE CAN 150ML', 'productPool/1.jpg', 88 ),
( 'MIRINDA ORANGE PET 600ML', 'productPool/1.jpg', 161 ),
( 'MIRINDA ORANGE SLIM CAN 250ML', 'productPool/1.jpg', 262 ),
( 'MIRINDA PET FULL 1250ML', 'productPool/1.jpg', 219 ),
( 'MIRROR (B) SR65', 'productPool/1.jpg', 198 ),
( 'MIRROR (S) IMP', 'productPool/1.jpg', 261 ),
( 'MIRROR 12*8', 'productPool/1.jpg', 57 ),
( 'MIRROR 7*5', 'productPool/1.jpg', 102 ),
( 'MIRROR 7*5 RS19', 'productPool/1.jpg', 238 ),
( 'MIRROR 8*6', 'productPool/1.jpg', 14 ),
( 'MIRROR RS 14.50', 'productPool/1.jpg', 124 ),
( 'MIRROR RS24', 'productPool/1.jpg', 243 ),
( 'MIRROR RS33', 'productPool/1.jpg', 7 ),
( 'MIRROR RS60', 'productPool/1.jpg', 186 ),
( 'MITO ADULT CAT FOOD 1KG', 'productPool/1.jpg', 47 ),
( 'MIX CHILLY POWDER 500G', 'productPool/1.jpg', 81 ),
( 'MIX CHILLY POWDER200G', 'productPool/1.jpg', 46 ),
( 'MIX GRAPES', 'productPool/1.jpg', 199 ),
( 'MIXED VEGETABLE PICKLE 400G', 'productPool/1.jpg', 80 ),
( 'MMS MILK POWDER FORMULA1 400G TIN', 'productPool/1.jpg', 1 ),
( 'MODELLING TOOL SET SK', 'productPool/1.jpg', 133 ),
( 'MODERN ATTA SHAKTI BREAD 400G', 'productPool/1.jpg', 48 ),
( 'MODERN BROWN BREAD 400G', 'productPool/1.jpg', 130 ),
( 'MODERN BULDOZER', 'productPool/1.jpg', 156 ),
( 'MODERN CREME BITE CHOCO 36G', 'productPool/1.jpg', 261 ),
( 'MODERN CREME BITE MIXED FRUIT 36G', 'productPool/1.jpg', 205 ),
( 'MODERN DUMPER', 'productPool/1.jpg', 97 ),
( 'MODERN ENRICHED SWEET BREAD 500 Gms', 'productPool/1.jpg', 127 ),
( 'MODERN ENRICHED SWEET BREAD400G', 'productPool/1.jpg', 64 ),
( 'MODERN ENRICHED SWEET BUN', 'productPool/1.jpg', 56 ),
( 'MODERN FAMILY SPECIAL', 'productPool/1.jpg', 247 ),
( 'MODERN FAMILY SPECIAL BREAD', 'productPool/1.jpg', 188 ),
( 'MODERN FRUITY RUSK', 'productPool/1.jpg', 193 ),
( 'MODERN JCB', 'productPool/1.jpg', 102 ),
( 'MODERN MILK RUSK 200 GM', 'productPool/1.jpg', 258 ),
( 'MODERN SWEET RUSK 200 GMS', 'productPool/1.jpg', 96 ),
( 'MODERN WHOLE WHEAT BREAD 400G', 'productPool/1.jpg', 245 ),
( 'MODERN WHOLE WHEAT CHAPATHI 450G', 'productPool/1.jpg', 269 ),
( 'MODY BANANA CHIPS SWEET 200G', 'productPool/1.jpg', 30 ),
( 'MODY KAPPA STICK CHILLY 200G', 'productPool/1.jpg', 32 ),
( 'MODY KAPPA STICK PLAIN 200G', 'productPool/1.jpg', 245 ),
( 'MODY PAZHAM CHIPS SLICE 200G', 'productPool/1.jpg', 274 ),
( 'MOGU APPLE JUICE DRINK 300 ML', 'productPool/1.jpg', 258 ),
( 'MOGU GRAPE JUICE DRINK 300 ML', 'productPool/1.jpg', 138 ),
( 'MOGU MOGU GRAPE JUICE 1L', 'productPool/1.jpg', 86 ),
( 'MOGU MOGU LYCHEE DRINK 300 ML', 'productPool/1.jpg', 96 ),
( 'MOGU MOGU LYCHEE JUICE 1L', 'productPool/1.jpg', 205 ),
( 'MOGU MOGU MANGO DRINK 300ML', 'productPool/1.jpg', 277 ),
( 'MOGU MOGU STRAWBERRY JUICE 1L', 'productPool/1.jpg', 14 ),
( 'MOGU MOGU STRAWBERRY JUICE DRINK', 'productPool/1.jpg', 144 ),
( 'MOGU ORANGE JUICE DRINK 300 ML', 'productPool/1.jpg', 121 ),
( 'MOGU PINEAPPLE JUICE DRINK 300 ML', 'productPool/1.jpg', 56 ),
( 'MOHANA ACHAPPAM 10NOS', 'productPool/1.jpg', 222 ),
( 'MOHANA ACHAPPAM 27NOS', 'productPool/1.jpg', 221 ),
( 'MOHANA CHILLI MURUKKU 200G', 'productPool/1.jpg', 23 ),
( 'MOHANA COCONUT MURUKKU 200G', 'productPool/1.jpg', 58 ),
( 'MOHANA KARIVEPPILA MURUKKU 200G', 'productPool/1.jpg', 118 ),
( 'MOHANA RICE MURUKKU 200G', 'productPool/1.jpg', 69 ),
( 'MOHANA SQUARE ACHAPPAM 10NOS', 'productPool/1.jpg', 235 ),
( 'MOKSH 3IN 1 AGARBATTI 20G', 'productPool/1.jpg', 173 ),
( 'MOKSH HIGH LIFE AGARBATTI 20G', 'productPool/1.jpg', 38 ),
( 'MOKSH SWARNA GANESH AGARBATTI 20G', 'productPool/1.jpg', 147 ),
( 'MOKSH SWARNA LAVENDER AGARBATHI', 'productPool/1.jpg', 183 ),
( 'MONACO SIXER SALTED 200G', 'productPool/1.jpg', 205 ),
( 'MONETTA CREAM WAFERS CHOCOLATE 300G', 'productPool/1.jpg', 203 ),
( 'MONETTA CREAM WAFERS COOKIE CREAM 300G', 'productPool/1.jpg', 39 ),
( 'MONETTA LUXURY CREAM WAFEAR300G', 'productPool/1.jpg', 160 ),
( 'MONGINIS MANGO SWISS ROLL 100G', 'productPool/1.jpg', 12 ),
( 'MONGINIS SWISS ROLL STRAWBERRY CAKE 100G', 'productPool/1.jpg', 182 ),
( 'MONGINIS SWISSROLL CHOCOLATE 100G', 'productPool/1.jpg', 98 ),
( 'MONIC 2 PIN TOP', 'productPool/1.jpg', 101 ),
( 'MONTANA CUT MANGO PICKLE 1KG', 'productPool/1.jpg', 98 ),
( 'MONTANA LIME PICKLE 1KG', 'productPool/1.jpg', 91 ),
( 'MONTAVO AMAZON CAKE SERVER NO.2', 'productPool/1.jpg', 135 ),
( 'MONTAVO AMAZON CEREAL SCOOP 2 SMALL', 'productPool/1.jpg', 182 ),
( 'MONTAVO FLAIR DESSERT FORK 6PC', 'productPool/1.jpg', 254 ),
( 'MONTAVO FLAIR DESSERT KNIFE 2PC', 'productPool/1.jpg', 22 ),
( 'MONTAVO TRENDZ BABY FORK 6 PC', 'productPool/1.jpg', 198 ),
( 'MONTEX ALUMINIUM FOIL 9M', 'productPool/1.jpg', 99 ),
( 'MONTEX FOIL 290MM', 'productPool/1.jpg', 55 ),
( 'MONTEX FOIL ALUMINIUM FOIL 9 MTR', 'productPool/1.jpg', 271 ),
( 'MONTTASTRAWBERRY CREAM WAFERS 300G', 'productPool/1.jpg', 5 ),
( 'MOODS CONDOMS 3 NOS', 'productPool/1.jpg', 33 ),
( 'MOODS DOTTED 12S', 'productPool/1.jpg', 249 ),
( 'MOODS DOTTED CONDOM', 'productPool/1.jpg', 204 ),
( 'MOODS MEN IGNYTE 200ML', 'productPool/1.jpg', 68 ),
( 'MOODS MEN SEDUXN 200ML', 'productPool/1.jpg', 90 ),
( 'MOODS MEN WYLD 200ML', 'productPool/1.jpg', 190 ),
( 'MOODS ULTRA THIN 12S', 'productPool/1.jpg', 172 ),
( 'MOOV 30G', 'productPool/1.jpg', 211 ),
( 'MOOV ADVANCE 40G', 'productPool/1.jpg', 45 ),
( 'MOOV PAIN RELIEF 15G', 'productPool/1.jpg', 172 ),
( 'MOOV PAIN RELIEF 25G', 'productPool/1.jpg', 116 ),
( 'MOOV PAIN RELIEF 50G', 'productPool/1.jpg', 147 ),
( 'MOOV SPARY 80ML', 'productPool/1.jpg', 272 ),
( 'MOOV SPRAY 35G', 'productPool/1.jpg', 167 ),
( 'MORARKA ORGANIC BROWN BASMATI SUPERFINE', 'productPool/1.jpg', 91 ),
( 'MORARKA ORGANIC MASOOR WHOLE 500G', 'productPool/1.jpg', 99 ),
( 'MORARKA ORGANIC MOONG DAL MOGAR 500G', 'productPool/1.jpg', 203 ),
( 'MORARKA ORGANIC NATURAL HONEY 500G', 'productPool/1.jpg', 138 ),
( 'MORARKA ORGANIC RAJMA RED500G', 'productPool/1.jpg', 177 ),
( 'MORARKA ORGANIC SUGAR 1KG', 'productPool/1.jpg', 168 ),
( 'MORARKA ORGANIC SUGAR 500G', 'productPool/1.jpg', 211 ),
( 'MORDE MILK COMPOUND 400G', 'productPool/1.jpg', 211 ),
( 'MORE LIGHT DETERGENT POWDER 150G', 'productPool/1.jpg', 72 ),
( 'MORE LIGHT DETERGENT POWDER 1KG', 'productPool/1.jpg', 74 ),
( 'MORE LIGHT DETERGENT POWDER 4KG', 'productPool/1.jpg', 176 ),
( 'MORE LIGHT DETERGENT POWDER 500G', 'productPool/1.jpg', 124 ),
( 'MORE LIGHT SOAP 100GM', 'productPool/1.jpg', 172 ),
( 'MORELIGHT DETERNT CAKE 225G', 'productPool/1.jpg', 50 ),
( 'MORISON ANTI COLIC NIPPLE', 'productPool/1.jpg', 52 ),
( 'MORISON BABY COMB', 'productPool/1.jpg', 130 ),
( 'MORISON BABY DREAMS DESIGNER FEEDING BOTTLE 125ML', 'productPool/1.jpg', 22 ),
( 'MORISON BABY DREAMS FEEDING BOTTLE 125ML', 'productPool/1.jpg', 173 ),
( 'MORISON BABY FEEDING BOTTLE 250ML', 'productPool/1.jpg', 63 ),
( 'MORISON BABY NAIL CLIPPER', 'productPool/1.jpg', 19 ),
( 'MORISON BABY POWDER PUFF', 'productPool/1.jpg', 44 ),
( 'MORISON BABY REGULAR FEEDING BOTTLE 125ML', 'productPool/1.jpg', 3 ),
( 'MORISON BOTTLE & NIPPLE CLEAN BRUSH', 'productPool/1.jpg', 118 ),
( 'MORISON CUTIE FEEDING CUP 240ML', 'productPool/1.jpg', 117 ),
( 'MORISON FEEDING BOTTLE WITH SPOON 250ML', 'productPool/1.jpg', 145 ),
( 'MORISON FORK&SPOON SET', 'productPool/1.jpg', 125 ),
( 'MORISON JL COTTON BUDS(100)', 'productPool/1.jpg', 90 ),
( 'MORISON JL FINGER BRUSH WITH HC', 'productPool/1.jpg', 27 ),
( 'MORISON POOCHIE CUP', 'productPool/1.jpg', 163 ),
( 'MORISON POWDER PUFF', 'productPool/1.jpg', 40 ),
( 'MORISON REGULAR FEEDING BOTTLE 85R', 'productPool/1.jpg', 146 ),
( 'MORISON ROYAL FEEDING BOTTLE 250ML', 'productPool/1.jpg', 183 ),
( 'MORISON ROYAL FEEDING CUP 125ML', 'productPool/1.jpg', 179 ),
( 'MORISON SIPPIE FEEDING CUP 180ML', 'productPool/1.jpg', 240 ),
( 'MORISON SOOTHER NIPPLE', 'productPool/1.jpg', 19 ),
( 'MORISONS BABY HAND MOUTH 20 WIPES 30S', 'productPool/1.jpg', 245 ),
( 'MORISONS BABY HAND MOUTH WIPES 30S', 'productPool/1.jpg', 234 ),
( 'MORISONS BABY MAT LARGE 56*88CM', 'productPool/1.jpg', 215 ),
( 'MORISONS CLASSIC POWDER PUFF 1N', 'productPool/1.jpg', 250 ),
( 'MORISONS CLOTH BOTTLE COVER 10CM', 'productPool/1.jpg', 7 ),
( 'MORISONS POOCHIE CUP 180ML', 'productPool/1.jpg', 8 ),
( 'MORISONS SOFT BABY WIPES 72 W', 'productPool/1.jpg', 252 ),
( 'MORNING GLORY 120G', 'productPool/1.jpg', 241 ),
( 'MORNING GLORY AGARBATHI 16N', 'productPool/1.jpg', 255 ),
( 'MORNING NECTAR FLAWLESS LOTION SKIN MOISTURIZER 120ML', 'productPool/1.jpg', 8 ),
( 'MORTEIN AIK 225ML', 'productPool/1.jpg', 116 ),
( 'MORTEIN AIK 400ML', 'productPool/1.jpg', 84 ),
( 'MORTEIN AIK 600ML', 'productPool/1.jpg', 81 ),
( 'MORTEIN ALL INSECT INSTA KIILS 200ML', 'productPool/1.jpg', 122 ),
( 'MORTEIN ALL INSECT KILLER 400ML', 'productPool/1.jpg', 261 ),
( 'MORTEIN ALL INSECT KILLER 600ML', 'productPool/1.jpg', 266 ),
( 'MORTEIN COCKROACH 425ML', 'productPool/1.jpg', 116 ),
( 'MORTEIN COMBI INSTA5', 'productPool/1.jpg', 183 ),
( 'MORTEIN INSECT KILLER 250ML', 'productPool/1.jpg', 189 ),
( 'MORTEIN INSTA5 REFIL 35ML', 'productPool/1.jpg', 57 ),
( 'MORTEIN LIQUID CHOTU 25ML', 'productPool/1.jpg', 190 ),
( 'MORTEIN MOSQUITO KILLER 500ML', 'productPool/1.jpg', 18 ),
( 'MORTIN 2 IN 1 INSECT KILLER 425ML', 'productPool/1.jpg', 107 ),
( 'MORTIN GREEN MOSQUITO COIL', 'productPool/1.jpg', 82 ),
( 'MORTON MUSHROOM IN BRINE', 'productPool/1.jpg', 271 ),
( 'MORTON SWEET CORN 400GM', 'productPool/1.jpg', 14 ),
( 'MORTON SWEET CORN 450G', 'productPool/1.jpg', 254 ),
( 'MOSKITO SAFE 100ML', 'productPool/1.jpg', 48 ),
( 'MOSKITO SAFE SCARE AWAY PATCHES 12N', 'productPool/1.jpg', 97 ),
( 'MOSQUITO BAT', 'productPool/1.jpg', 175 ),
( 'MOSQUITO BAT IMP RS 145', 'productPool/1.jpg', 91 ),
( 'MOSQUITO BAT RS175', 'productPool/1.jpg', 148 ),
( 'MOTHER BRAND PAPER SHEET 90', 'productPool/1.jpg', 130 ),
( 'MOUNTAIN DEW 1.25L', 'productPool/1.jpg', 18 ),
( 'MOUNTAIN DEW 150ML CAN', 'productPool/1.jpg', 13 ),
( 'MOUNTAIN DEW 2.25L', 'productPool/1.jpg', 2 ),
( 'MOUNTAIN DEW 250ML', 'productPool/1.jpg', 63 ),
( 'MOUNTAIN DEW 600ML', 'productPool/1.jpg', 18 ),
( 'MOUNTAIN EBONY VITALIZING SERUM 120ML', 'productPool/1.jpg', 232 ),
( 'MOUNTING TAPE', 'productPool/1.jpg', 210 ),
( 'MOUSE GLUE TRAP PAD RS20', 'productPool/1.jpg', 213 ),
( 'MOUSE GLUE TRAP PAD RS24', 'productPool/1.jpg', 226 ),
( 'MOUTH SP IMP', 'productPool/1.jpg', 226 ),
( 'MOVENPICK ESPRESSO COFFEE 100G', 'productPool/1.jpg', 14 ),
( 'MOVENPICK HEAVENLY COFFEE 100G', 'productPool/1.jpg', 142 ),
( 'MPI BACON RASHERS 200GMS', 'productPool/1.jpg', 174 ),
( 'MPI BEEF ACHAR 200 GMS', 'productPool/1.jpg', 19 ),
( 'MPI BEEF BITS 1KG', 'productPool/1.jpg', 204 ),
( 'MPI BEEF CUTLITES', 'productPool/1.jpg', 182 ),
( 'MPI BEEF SAUSAGE 200GMS', 'productPool/1.jpg', 234 ),
( 'MPI BEEF SAUSAGE 500G', 'productPool/1.jpg', 120 ),
( 'MPI BROILER CHICKEN', 'productPool/1.jpg', 66 ),
( 'MPI BUFFOLA BITS1 KG', 'productPool/1.jpg', 118 ),
( 'MPI CHICKEN BONELESS 500 GMS', 'productPool/1.jpg', 170 ),
( 'MPI CHICKEN CURRY CUTS 500GMS', 'productPool/1.jpg', 82 ),
( 'MPI CHICKEN DRUMSTICK 500G', 'productPool/1.jpg', 101 ),
( 'MPI CHICKEN N HAM SLICED 200GMS', 'productPool/1.jpg', 65 ),
( 'MPI CHICKEN SAUSAGE 200G', 'productPool/1.jpg', 98 ),
( 'MPI COCKTAIL SAUSAGE 200GMS', 'productPool/1.jpg', 98 ),
( 'MPI COCKTAIL SAUSAGE 500G', 'productPool/1.jpg', 49 ),
( 'MPI DRIED BEEF', 'productPool/1.jpg', 254 ),
( 'MPI DUCK MEAT 500 GMS', 'productPool/1.jpg', 164 ),
( 'MPI JANATHA CHICKEN 500GMS', 'productPool/1.jpg', 267 ),
( 'MPI MUTTON BITS 500GM', 'productPool/1.jpg', 171 ),
( 'MPI PORK BITS 500GMS', 'productPool/1.jpg', 19 ),
( 'MPI PORK CHOPS', 'productPool/1.jpg', 8 ),
( 'MPI PORK CURRY CUTS 500GMS', 'productPool/1.jpg', 41 ),
( 'MPI PORK SAUSAGE 200G', 'productPool/1.jpg', 195 ),
( 'MPI PORK SAUSAGE 500G', 'productPool/1.jpg', 210 ),
( 'MPI PREMIUM BEEF BITS', 'productPool/1.jpg', 214 ),
( 'MPI PREMIUM MALE BUFFALO 1KG', 'productPool/1.jpg', 253 ),
( 'MPI SALAMI SLICE 200 GMS', 'productPool/1.jpg', 187 ),
( 'MPI VEAL BITS 1KG', 'productPool/1.jpg', 264 ),
( 'MR BUTLER GREEN CHILLI SAUCE 200GM', 'productPool/1.jpg', 138 ),
( 'MR BUTLER MANGO SQUASH 700ML', 'productPool/1.jpg', 97 ),
( 'MR BUTLER MIXED FRUIT JAM 500G', 'productPool/1.jpg', 275 ),
( 'MR BUTLER ORANGE SQUASH 700ML', 'productPool/1.jpg', 242 ),
( 'MR BUTLER RED CHILLI SAUCE 200G', 'productPool/1.jpg', 84 ),
( 'MR BUTLER SOYA SAUCE 200GM', 'productPool/1.jpg', 35 ),
( 'MR FUN UMBRELLA CANDY', 'productPool/1.jpg', 32 ),
( 'MR WHITE ACTIVE POWER WASHING POWDER 1.2KG', 'productPool/1.jpg', 214 ),
( 'MR WHITE ACTIVE POWER WASHING POWDER 500G', 'productPool/1.jpg', 159 ),
( 'MR WHITE DETERGENT POWDER 1KG', 'productPool/1.jpg', 164 ),
( 'MR WHITEACTIVE POWER 125 G', 'productPool/1.jpg', 69 ),
( 'MR. BUTLERS MANGO PULP 3.1KG', 'productPool/1.jpg', 195 ),
( 'MR. BUTLERS MIXED FRUIT JAM 200G', 'productPool/1.jpg', 146 ),
( 'MR. WHITE ACTIVE POWER 500G', 'productPool/1.jpg', 201 ),
( 'MR.BUTLER MIXED JAM 100G', 'productPool/1.jpg', 186 ),
( 'MR.BUTLER PINE APPLE JAM 500G', 'productPool/1.jpg', 73 ),
( 'MR.BUTLER PINEAPLE JAM 200G', 'productPool/1.jpg', 274 ),
( 'MR.BUTLER PINEAPPLE JAM 100G', 'productPool/1.jpg', 15 ),
( 'MR.BUTLERS RED CHILLI SAUCE 200G', 'productPool/1.jpg', 177 ),
( 'MR.BUTLERS TOMATO SAUCE 1KG', 'productPool/1.jpg', 33 ),
( 'MR.BUTLERS TOMATO SAUCE 200G', 'productPool/1.jpg', 41 ),
( 'MR.WHITE POWDER 5KG', 'productPool/1.jpg', 177 ),
( 'MS FEMME DEO 135ML', 'productPool/1.jpg', 5 ),
( 'MS JUST HOME DEO 200ML', 'productPool/1.jpg', 170 ),
( 'MS JUST NOIR DEO 200ML', 'productPool/1.jpg', 191 ),
( 'MS JUST SPORT FEMME DEO 200ML', 'productPool/1.jpg', 43 ),
( 'MS MUSK DEO 135ML', 'productPool/1.jpg', 264 ),
( 'MS SOLDIER DEO 200ML', 'productPool/1.jpg', 89 ),
( 'MS SPORT DEO 135ML', 'productPool/1.jpg', 114 ),
( 'MS STRIKE HOMME DEO 200ML', 'productPool/1.jpg', 90 ),
( 'MS SUMMER DEO 135ML', 'productPool/1.jpg', 156 ),
( 'MSEAL 1KG', 'productPool/1.jpg', 27 ),
( 'MUG', 'productPool/1.jpg', 136 ),
( 'MUG MOULD 1500ML', 'productPool/1.jpg', 235 ),
( 'MUG MOULD 500ML', 'productPool/1.jpg', 175 ),
( 'MULTANI PAPAYA 100G', 'productPool/1.jpg', 171 ),
( 'MULTI COLOUR KNIFE RS 115', 'productPool/1.jpg', 82 ),
( 'MULTI FRUIT CUTTER', 'productPool/1.jpg', 263 ),
( 'MULTI GRAIN PUTTU PODI500G', 'productPool/1.jpg', 125 ),
( 'MULTI PURPOSE CUTLARY STAND FAMILY', 'productPool/1.jpg', 264 ),
( 'MULTIPURPOSE TONG ASE', 'productPool/1.jpg', 1 ),
( 'MUMS CARE BABY CEREAL RAGI MOONG DAL 300G', 'productPool/1.jpg', 275 ),
( 'MUMS CARE BABY CEREAL RICE MOONG DAL 300G', 'productPool/1.jpg', 137 ),
( 'MUMS CARE BABY CEREAL RICE MOONG DAL 300G JAR', 'productPool/1.jpg', 27 ),
( 'MUMS CARE BABY CEREAL WHEAT APPLE 300G', 'productPool/1.jpg', 161 ),
( 'MUMS CARE BABY CEREAL WHEAT APPLE 300G JAR', 'productPool/1.jpg', 83 ),
( 'MUNCH MAHA 10.1G 24 PCS', 'productPool/1.jpg', 268 ),
( 'MUNCHOS DOG CHEW STICK', 'productPool/1.jpg', 197 ),
( 'MUNGYO POINT STICK BLUE', 'productPool/1.jpg', 79 ),
( 'MUNGYO POINT STICK GREEN', 'productPool/1.jpg', 99 ),
( 'MUNGYO POINT STICK ORANGE', 'productPool/1.jpg', 49 ),
( 'MUNGYO POINT STICK PINK', 'productPool/1.jpg', 224 ),
( 'MUNGYO POINT STICK VIOLET', 'productPool/1.jpg', 226 ),
( 'MUNGYO POINT STICK YELLOW', 'productPool/1.jpg', 85 ),
( 'MUNIX KANGARO PUNCH DP 22Y', 'productPool/1.jpg', 9 ),
( 'MUNIX SCISSOR SL-1173N', 'productPool/1.jpg', 14 ),
( 'MUNIX SCISSOR SL1143', 'productPool/1.jpg', 231 ),
( 'MUNIX SCISSOR SL1150', 'productPool/1.jpg', 271 ),
( 'MUNIX SCISSOR SL1150C', 'productPool/1.jpg', 279 ),
( 'MUNIX SCISSOR SL1160', 'productPool/1.jpg', 139 ),
( 'MUNIX SCISSOR SL1173', 'productPool/1.jpg', 26 );