INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'COLGATE MAX FRESH RED 48G', 'productPool/1.jpg', 187 ),
( 'COLGATE MAX FRESH RED 50G', 'productPool/1.jpg', 228 ),
( 'COLGATE MAX FRESH RED 54G', 'productPool/1.jpg', 183 ),
( 'COLGATE MAX FRESH RED 600G', 'productPool/1.jpg', 208 ),
( 'COLGATE MAX FRESH RED 70G', 'productPool/1.jpg', 47 ),
( 'COLGATE MAX FRESH RED TOOTH PASTE 150G', 'productPool/1.jpg', 249 ),
( 'COLGATE MAX FRESH RED TOOTH PASTE 300G WITH TOOTH BRUSH', 'productPool/1.jpg', 176 ),
( 'COLGATE MAX FRESH RED TOOTH PASTE 80G', 'productPool/1.jpg', 249 ),
( 'COLGATE MAXFRESH RED TOOTH PASTE 150G', 'productPool/1.jpg', 163 ),
( 'COLGATE NEO TOOTH BRUSH', 'productPool/1.jpg', 120 ),
( 'COLGATE NEO TOOTH BRUSH ULTRA SOFT', 'productPool/1.jpg', 125 ),
( 'COLGATE PAIN OUT GEL 10G', 'productPool/1.jpg', 156 ),
( 'COLGATE PAIN OUT TUBE 10G', 'productPool/1.jpg', 209 ),
( 'COLGATE PLAX ACTIVE SALT 250ML', 'productPool/1.jpg', 83 ),
( 'COLGATE PLAX COMPLETE CARE MOUTH WASH 250 ML', 'productPool/1.jpg', 234 ),
( 'COLGATE PLAX FRESH MINT 100ML', 'productPool/1.jpg', 175 ),
( 'COLGATE PLAX FRESH MINT 500 ML', 'productPool/1.jpg', 236 ),
( 'COLGATE PLAX FRESH MINT MOUTH WASH 250 ML', 'productPool/1.jpg', 232 ),
( 'COLGATE PLAX FRESH TEA MOUTH WASH 60ML', 'productPool/1.jpg', 8 ),
( 'COLGATE PLAX FRESH TEETH 250ML', 'productPool/1.jpg', 189 ),
( 'COLGATE PLAX FRESH TEETH 500 ML', 'productPool/1.jpg', 250 ),
( 'COLGATE PLAX GENTLE CARE MOUTH WASH250 ML', 'productPool/1.jpg', 159 ),
( 'COLGATE PLAX PEPPER MINT FRESH 250 ML', 'productPool/1.jpg', 33 ),
( 'COLGATE PLAX PEPPERMINT 250ML', 'productPool/1.jpg', 263 ),
( 'COLGATE PLAX PEPPERMINT FRESH 60ML', 'productPool/1.jpg', 202 ),
( 'COLGATE PLAX PEPPERMINT MOUTH WASH500ML', 'productPool/1.jpg', 170 ),
( 'COLGATE PLAX SPICY FRESH 250ML', 'productPool/1.jpg', 88 ),
( 'COLGATE SENSITIVE 2*80G', 'productPool/1.jpg', 126 ),
( 'COLGATE SENSITIVE 4 PACK BRUSH', 'productPool/1.jpg', 155 ),
( 'COLGATE SENSITIVE 40G', 'productPool/1.jpg', 67 ),
( 'COLGATE SENSITIVE 80G B1G1', 'productPool/1.jpg', 265 ),
( 'COLGATE SENSITIVE BUY 2 GET 1 FREE', 'productPool/1.jpg', 130 ),
( 'COLGATE SENSITIVE CLOVE 160G', 'productPool/1.jpg', 126 ),
( 'COLGATE SENSITIVE CLOVE 80G', 'productPool/1.jpg', 208 ),
( 'COLGATE SENSITIVE CLOVE ESSENCE 80G', 'productPool/1.jpg', 10 ),
( 'COLGATE SENSITIVE ORGINAL 80GMS', 'productPool/1.jpg', 186 ),
( 'COLGATE SENSITIVE ORIGINAL 80G', 'productPool/1.jpg', 59 ),
( 'COLGATE SENSITIVE PRO GEL70G', 'productPool/1.jpg', 147 ),
( 'COLGATE SENSITIVE PRO RELIEF 30GMS', 'productPool/1.jpg', 71 ),
( 'COLGATE SENSITIVE ULTRA SOFT', 'productPool/1.jpg', 86 ),
( 'COLGATE SENSITIVE ULTRA SOFT TOOTH BRUSH', 'productPool/1.jpg', 98 ),
( 'COLGATE SENSPROREL70G', 'productPool/1.jpg', 129 ),
( 'COLGATE SLIM SOFT BRUSH B2G1', 'productPool/1.jpg', 34 ),
( 'COLGATE SLIM SOFT CARCOAL B2G1', 'productPool/1.jpg', 105 ),
( 'COLGATE SLIM SOFT CHARCOAL SOFT BRUSH', 'productPool/1.jpg', 44 ),
( 'COLGATE SLIM SOFT CHARCOAL TOOTH BRUSH SOFT', 'productPool/1.jpg', 124 ),
( 'COLGATE SLIM SOFT SENSITIVE 2N+2N', 'productPool/1.jpg', 217 ),
( 'COLGATE SLIM SOFT SENSITIVE BUY 2GET 1 FREE', 'productPool/1.jpg', 174 ),
( 'COLGATE SLIM SOFT SENSITIVE SINGLE BRUSH', 'productPool/1.jpg', 149 ),
( 'COLGATE SLIM SOFT SINGLE BRUSH', 'productPool/1.jpg', 164 ),
( 'COLGATE SLIM SOFT SINGLE TOOTH BRUSH SOFT', 'productPool/1.jpg', 168 ),
( 'COLGATE SLIM SOFT TRI TIP BRUSH B2G1', 'productPool/1.jpg', 263 ),
( 'COLGATE SLIM SOFT TRITIP SINGLE BRUSH', 'productPool/1.jpg', 228 ),
( 'COLGATE SLIMSOFT CHARCOAL SINGLE BRUSH', 'productPool/1.jpg', 187 ),
( 'COLGATE SLIMSOFT SENSITIVE TOOTH BRUSH', 'productPool/1.jpg', 194 ),
( 'COLGATE SLIMSOFT TRITIP SINGLE BRUSH', 'productPool/1.jpg', 202 ),
( 'COLGATE SPIDERMAN TOOTH PASTE 80 G', 'productPool/1.jpg', 144 ),
( 'COLGATE STRONG TEETH 150G', 'productPool/1.jpg', 89 ),
( 'COLGATE STRONG TEETH 200+100G SAVER PACK', 'productPool/1.jpg', 245 ),
( 'COLGATE STRONG TEETH 4X200G', 'productPool/1.jpg', 28 ),
( 'COLGATE STRONG TEETH 500G', 'productPool/1.jpg', 76 ),
( 'COLGATE STRONG TEETH 54G', 'productPool/1.jpg', 30 ),
( 'COLGATE SUPER FLEXI BACK MEDIUM', 'productPool/1.jpg', 23 ),
( 'COLGATE SUPER FLEXI BLACK MEDIUM BRUSH', 'productPool/1.jpg', 93 ),
( 'COLGATE SUPER FLEXI BRUSH', 'productPool/1.jpg', 230 ),
( 'COLGATE SUPER FLEXI MEDIUM', 'productPool/1.jpg', 29 ),
( 'COLGATE SUPER FLEXI MEDIUM 12+2', 'productPool/1.jpg', 86 ),
( 'COLGATE SUPER FLEXI SENSITIVE BRUSH', 'productPool/1.jpg', 263 ),
( 'COLGATE SUPER FLEXI SUPER CLEN', 'productPool/1.jpg', 52 ),
( 'COLGATE SUPER JUNIOR BRUSH', 'productPool/1.jpg', 1 ),
( 'COLGATE SUPER JUNIOR TOOTH BRUSH', 'productPool/1.jpg', 96 ),
( 'COLGATE SUPER JUNIOR TOOTH BRUSH EXTRA SOFT', 'productPool/1.jpg', 154 ),
( 'COLGATE SUPER SHINE BRUSH MEDIUM', 'productPool/1.jpg', 224 ),
( 'COLGATE SUPER SHINE MEDIUM BRUSH', 'productPool/1.jpg', 184 ),
( 'COLGATE SUPER SHINE RS 22', 'productPool/1.jpg', 10 ),
( 'COLGATE SUPER SHINE TOOTH BRUSH MEDIUM', 'productPool/1.jpg', 178 ),
( 'COLGATE SUPERFLEXI CHARCOAL BRUSH', 'productPool/1.jpg', 25 ),
( 'COLGATE SUPERFLEXI TOOTH BRUSH MEDIUM', 'productPool/1.jpg', 256 ),
( 'COLGATE SWARNA VEDSHAKTHI 300G', 'productPool/1.jpg', 142 ),
( 'COLGATE SWARNA VEDSHAKTHI 40G', 'productPool/1.jpg', 139 ),
( 'COLGATE SWARNA VEDSHAKTI 100G', 'productPool/1.jpg', 167 ),
( 'COLGATE SWARNA VEDSHAKTI 110G', 'productPool/1.jpg', 258 ),
( 'COLGATE SWARNA VEDSHAKTI 200G', 'productPool/1.jpg', 46 ),
( 'COLGATE TOOTH BRUSH 360 CLEAN SOFT', 'productPool/1.jpg', 89 ),
( 'COLGATE TOOTH PASTE 100G', 'productPool/1.jpg', 135 ),
( 'COLGATE TOOTH PASTE 105G+5G', 'productPool/1.jpg', 59 ),
( 'COLGATE TOOTH PASTE 200G', 'productPool/1.jpg', 116 ),
( 'COLGATE TOOTH PASTE 48G', 'productPool/1.jpg', 140 ),
( 'COLGATE TOOTH PASTE MRP 7', 'productPool/1.jpg', 114 ),
( 'COLGATE TOOTH POWDER 100G', 'productPool/1.jpg', 157 ),
( 'COLGATE TOOTH POWDER 200G', 'productPool/1.jpg', 157 ),
( 'COLGATE TOOTHPOWDER 100G', 'productPool/1.jpg', 199 ),
( 'COLGATE TOTAL ADVANCED HEALTH 120G', 'productPool/1.jpg', 94 ),
( 'COLGATE TOTAL ADVANCED HEALTH 120G B2G1', 'productPool/1.jpg', 217 ),
( 'COLGATE TOTAL ADVANCED HEALTH 120G+120G', 'productPool/1.jpg', 95 ),
( 'COLGATE TOTAL ADVANCED HEALTH 185G', 'productPool/1.jpg', 177 ),
( 'COLGATE TOTAL ADVANED HEALTH 120G', 'productPool/1.jpg', 116 ),
( 'COLGATE TOTAL CHARCOAL 120G', 'productPool/1.jpg', 120 ),
( 'COLGATE TOTAL CHARCOAL 185G', 'productPool/1.jpg', 207 ),
( 'COLGATE TOTAL CHARCOAL 2*120G', 'productPool/1.jpg', 32 ),
( 'COLGATE TOTAL DENTAL FLOSS', 'productPool/1.jpg', 23 ),
( 'COLGATE VISIBLE WHITE 100G', 'productPool/1.jpg', 262 ),
( 'COLGATE VISIBLE WHITE 250ML', 'productPool/1.jpg', 265 ),
( 'COLGATE VISIBLE WHITE 50G', 'productPool/1.jpg', 258 ),
( 'COLGATE ZIG ZAG BLACK 4 PACK BRUSH', 'productPool/1.jpg', 73 ),
( 'COLGATE ZIG ZAG BLACK 5 PACK BRUSH', 'productPool/1.jpg', 12 ),
( 'COLGATE ZIG ZAG BLACK BRUSH B2G1', 'productPool/1.jpg', 57 ),
( 'COLGATE ZIG ZAG BLACK MEDIUM BRUSH', 'productPool/1.jpg', 150 ),
( 'COLGATE ZIG ZAG BLACK MEDIUM TOOTH BRUSH', 'productPool/1.jpg', 218 ),
( 'COLGATE ZIG ZAG BLACK MEDIUM TOOTHBRUSH', 'productPool/1.jpg', 61 ),
( 'COLGATE ZIG ZAG CHARCOAL MEDIUM', 'productPool/1.jpg', 256 ),
( 'COLGATE ZIG ZAG CHARCOAL SOFT BRUSH', 'productPool/1.jpg', 201 ),
( 'COLGATE ZIG ZAG MEDIUM 6 PACK BRUSH', 'productPool/1.jpg', 227 ),
( 'COLGATE ZIG ZAG MEDIUM BRUSH', 'productPool/1.jpg', 225 ),
( 'COLGATE ZIG ZAG MEDIUM BRUSH B2G1', 'productPool/1.jpg', 101 ),
( 'COLGATE ZIG ZAG SINGLE MEDIUM BRUSH', 'productPool/1.jpg', 183 ),
( 'COLGATE ZIG ZAG SOFT BRUSH B2G1', 'productPool/1.jpg', 11 ),
( 'COLGATE ZIGZAG B2G1 TOOTH BRUSH MEDIUM', 'productPool/1.jpg', 181 ),
( 'COLGATE ZIGZAG NEEM BRUSH MEDIUM', 'productPool/1.jpg', 30 ),
( 'COLGATTE 360 FLOSS-TIP ASOFT B2G1', 'productPool/1.jpg', 265 ),
( 'COLGATTE ACTIVE SALT NEEM TOOTH PASTE 100G', 'productPool/1.jpg', 261 ),
( 'COLIN GLASS CLEANER 500ML', 'productPool/1.jpg', 136 ),
( 'COLIN GLASS CLEANER 500ML SOAP FREE', 'productPool/1.jpg', 186 ),
( 'COLLIN GLASS CLEANER 250ML', 'productPool/1.jpg', 259 ),
( 'COLOESSENCE SEMI MATTE LIP GLOSS LGM-10', 'productPool/1.jpg', 91 ),
( 'COLOR ESSENCE LIP BALM ORANGE', 'productPool/1.jpg', 100 ),
( 'COLOR ESSENCE LIP BLAM STRAWBERRY', 'productPool/1.jpg', 269 ),
( 'COLOR ESSENCE LIP COLOR 62', 'productPool/1.jpg', 215 ),
( 'COLOR ESSENCE PERFECT REMOVER 50ML', 'productPool/1.jpg', 48 ),
( 'COLOR ESSENCE PREMIA LIP COLOR COMBO', 'productPool/1.jpg', 113 ),
( 'COLOREEEENCE LIPLICIOUS GLOSS 6ML LLG-1', 'productPool/1.jpg', 113 ),
( 'COLOREEEENCE LIPLICIOUS GLOSS 6ML LLG-4', 'productPool/1.jpg', 59 ),
( 'COLOREEEENCE LIPLICIOUS GLOSS 6ML LLG-5', 'productPool/1.jpg', 134 ),
( 'COLOREEEENCE LIPLICIOUS GLOSS 6ML LLG-6', 'productPool/1.jpg', 14 ),
( 'COLOREEEENCE LIPLICIOUS GLOSS 6ML LLG-7', 'productPool/1.jpg', 153 ),
( 'COLOREEEENCE LIPLICIOUS GLOSS 6ML LLG-8', 'productPool/1.jpg', 170 ),
( 'COLOREESENCE HD PANCKAE PC-04', 'productPool/1.jpg', 198 ),
( 'COLORESENCE GLOSSY LIP COLOUR LCG-07', 'productPool/1.jpg', 42 ),
( 'COLORESENCE MESMERISING LIP COLOUR 4G', 'productPool/1.jpg', 141 ),
( 'COLORESSENCE AQUA MAKEUP BASE 35ML', 'productPool/1.jpg', 239 ),
( 'COLORESSENCE AQUA MAKEUP BASE 35ML LF4', 'productPool/1.jpg', 154 ),
( 'COLORESSENCE AQUA MAKEUP BASE LF-1 35ML', 'productPool/1.jpg', 162 ),
( 'COLORESSENCE AQUA MAKEUP BASE LF-2', 'productPool/1.jpg', 260 ),
( 'COLORESSENCE AQUA MAKEUP BASE LF-3', 'productPool/1.jpg', 70 ),
( 'COLORESSENCE AQUA MAKEUP BASE LF2 35ML', 'productPool/1.jpg', 67 ),
( 'COLORESSENCE AQUA SINDOOR SD-M 6ML', 'productPool/1.jpg', 185 ),
( 'COLORESSENCE AQUA SINDOOR SD-R 6ML', 'productPool/1.jpg', 34 ),
( 'COLORESSENCE BLUSHER 5G SH-02', 'productPool/1.jpg', 63 ),
( 'COLORESSENCE BLUSHER 5G SH-04', 'productPool/1.jpg', 29 ),
( 'COLORESSENCE BLUSHER 5G SH-05', 'productPool/1.jpg', 200 ),
( 'COLORESSENCE BLUSHER 5G SH09', 'productPool/1.jpg', 116 ),
( 'COLORESSENCE BLUSHER 5G SH6', 'productPool/1.jpg', 189 ),
( 'COLORESSENCE BLUSHER SH 07 5G', 'productPool/1.jpg', 100 ),
( 'COLORESSENCE BLUSHER SH 08 5G', 'productPool/1.jpg', 89 ),
( 'COLORESSENCE BLUSHER SH-01', 'productPool/1.jpg', 86 ),
( 'COLORESSENCE BLUSHER SH-03', 'productPool/1.jpg', 60 ),
( 'COLORESSENCE BLUSHER SH5', 'productPool/1.jpg', 145 ),
( 'COLORESSENCE BRIDAL KAJAL 2.5G', 'productPool/1.jpg', 248 ),
( 'COLORESSENCE BROW STYLER BLACK .72G', 'productPool/1.jpg', 190 ),
( 'COLORESSENCE BROW STYLER DARK BROWN .72G', 'productPool/1.jpg', 270 ),
( 'COLORESSENCE CAMERA REDY EYELINER EL BLACK', 'productPool/1.jpg', 83 ),
( 'COLORESSENCE CAMERA REDY MASCARA MSC-01', 'productPool/1.jpg', 235 ),
( 'COLORESSENCE COMPACT POWDER CP-1 10G', 'productPool/1.jpg', 212 ),
( 'COLORESSENCE COMPACT POWDER CP-2 10G', 'productPool/1.jpg', 250 ),
( 'COLORESSENCE COMPACT POWDER CP-3 10G', 'productPool/1.jpg', 10 ),
( 'COLORESSENCE COMPACT POWDER CP4', 'productPool/1.jpg', 267 ),
( 'COLORESSENCE EYE LINER GEL 3G', 'productPool/1.jpg', 147 ),
( 'COLORESSENCE EYE LINER PEN 1NOS', 'productPool/1.jpg', 197 ),
( 'COLORESSENCE EYE SHADE ES-03', 'productPool/1.jpg', 7 ),
( 'COLORESSENCE EYE SHADE MES-1', 'productPool/1.jpg', 87 ),
( 'COLORESSENCE EYE SHADE MES-1', 'productPool/1.jpg', 150 ),
( 'COLORESSENCE EYE SHADE MES-4', 'productPool/1.jpg', 5 ),
( 'COLORESSENCE EYE SHADE MES-5', 'productPool/1.jpg', 118 ),
( 'COLORESSENCE EYE SHADOW PENCIL 2.25G', 'productPool/1.jpg', 172 ),
( 'COLORESSENCE EYE SHADOW PENCIL PINK', 'productPool/1.jpg', 185 ),
( 'COLORESSENCE EYELINER GEL BLACK 3G', 'productPool/1.jpg', 133 ),
( 'COLORESSENCE EYELINER PE-3 DUKE BLUE 6ML', 'productPool/1.jpg', 47 ),
( 'COLORESSENCE FACE BODY ILLUMINATOR FB12 35ML', 'productPool/1.jpg', 7 ),
( 'COLORESSENCE FACE BODY ILLUMINATOR LOTION 35ML', 'productPool/1.jpg', 229 ),
( 'COLORESSENCE FACE&BODY ILLUMINATOR FB-1', 'productPool/1.jpg', 121 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-01', 'productPool/1.jpg', 230 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-02', 'productPool/1.jpg', 184 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-03', 'productPool/1.jpg', 44 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-04', 'productPool/1.jpg', 59 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-05', 'productPool/1.jpg', 93 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-06', 'productPool/1.jpg', 243 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-08', 'productPool/1.jpg', 109 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-09', 'productPool/1.jpg', 73 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-10', 'productPool/1.jpg', 35 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-11', 'productPool/1.jpg', 168 ),
( 'COLORESSENCE GLOSSY LIP COLOUR LCG-12', 'productPool/1.jpg', 239 ),
( 'COLORESSENCE HD BB CREAM GRAPE 40G', 'productPool/1.jpg', 228 ),
( 'COLORESSENCE HD BB CREAM PAPAYA 40G', 'productPool/1.jpg', 122 ),
( 'COLORESSENCE HD EYE DEFINER 1.2G', 'productPool/1.jpg', 169 ),
( 'COLORESSENCE HD FOUNDATION 30ML', 'productPool/1.jpg', 24 ),
( 'COLORESSENCE HD FOUNDATION 30ML HDF3', 'productPool/1.jpg', 135 ),
( 'COLORESSENCE HD FOUNDATION 30ML HDF4', 'productPool/1.jpg', 232 ),
( 'COLORESSENCE HD FOUNDATION 30ML HDF5', 'productPool/1.jpg', 37 ),
( 'COLORESSENCE HD FOUNDATION FP-2 30ML', 'productPool/1.jpg', 181 ),
( 'COLORESSENCE HD FOUNDATION HDF-1 30ML', 'productPool/1.jpg', 57 ),
( 'COLORESSENCE HD FOUNDATION HDF2 30ML', 'productPool/1.jpg', 155 ),
( 'COLORESSENCE HD FOUNDATION STICK 14G FS1', 'productPool/1.jpg', 275 ),
( 'COLORESSENCE HD FOUNDATION STICK 14G FS4', 'productPool/1.jpg', 245 ),
( 'COLORESSENCE HD FOUNDATION STICK 14G FS5', 'productPool/1.jpg', 238 ),
( 'COLORESSENCE HD PANCAKAE PC-03', 'productPool/1.jpg', 126 ),
( 'COLORESSENCE HD PANCAKE PC-01', 'productPool/1.jpg', 105 ),
( 'COLORESSENCE HD PANCAKE PC-05', 'productPool/1.jpg', 252 ),
( 'COLORESSENCE HD PANCAKE PC-2', 'productPool/1.jpg', 274 ),
( 'COLORESSENCE HD POWDER FP1 10G', 'productPool/1.jpg', 8 ),
( 'COLORESSENCE HD POWDER FP2 10G', 'productPool/1.jpg', 147 ),
( 'COLORESSENCE HIGH DEFINITION POWDER FP 2', 'productPool/1.jpg', 271 ),
( 'COLORESSENCE HIGHLIGHTER 2.25G', 'productPool/1.jpg', 47 ),
( 'COLORESSENCE ILLUMINATING SKIN ENHANCER 15ML S1', 'productPool/1.jpg', 164 ),
( 'COLORESSENCE ILLUMINATING SKIN ENHANCER 15ML S2', 'productPool/1.jpg', 207 ),
( 'COLORESSENCE ILLUMINATING SKIN ENHANCER 15ML S3', 'productPool/1.jpg', 253 ),
( 'COLORESSENCE INTENSE LIP COLOUR LCM-01', 'productPool/1.jpg', 264 ),
( 'COLORESSENCE INTENSE LIP COLOUR LCM-02', 'productPool/1.jpg', 265 ),
( 'COLORESSENCE INTENSE LIP COLOUR LCM-03', 'productPool/1.jpg', 17 ),
( 'COLORESSENCE INTENSE LIP COLOUR LCM-05', 'productPool/1.jpg', 276 ),
( 'COLORESSENCE INTENSE LIP COLOUR LCM-06', 'productPool/1.jpg', 92 ),
( 'COLORESSENCE INTENSE LIP COLOUR LCM-07', 'productPool/1.jpg', 156 ),
( 'COLORESSENCE INTENSE LIP COLOUR LCM-08', 'productPool/1.jpg', 208 ),
( 'COLORESSENCE INTENSE LIP COLOUR LCM-10', 'productPool/1.jpg', 20 ),
( 'COLORESSENCE INTENSE LIP COLOUR LCM-11', 'productPool/1.jpg', 98 ),
( 'COLORESSENCE INTENSE LIP COLOUR LCM-12', 'productPool/1.jpg', 136 ),
( 'COLORESSENCE INTENSE LONG WEAR LIP COLOR LW 10', 'productPool/1.jpg', 49 ),
( 'COLORESSENCE INTENSE LONG WEAR LIP COLOR LW 11', 'productPool/1.jpg', 111 ),
( 'COLORESSENCE INTENSE LONG WEAR LIP COLOR LW12', 'productPool/1.jpg', 111 ),
( 'COLORESSENCE INTENSE LONG WEAR LIP COLOR LW4', 'productPool/1.jpg', 52 ),
( 'COLORESSENCE INTENSE LONG WEAR LIP COLOR LW6', 'productPool/1.jpg', 37 ),
( 'COLORESSENCE INTENSE LONG WEAR LIP COLOR LW8', 'productPool/1.jpg', 250 ),
( 'COLORESSENCE KAJAL PENCIL COMBO 0.5G', 'productPool/1.jpg', 158 ),
( 'COLORESSENCE KAJAL PENCIL0.25G', 'productPool/1.jpg', 98 ),
( 'COLORESSENCE LIP AND EYE PENCIL 1.76G LE 02', 'productPool/1.jpg', 194 ),
( 'COLORESSENCE LIP AND EYE PENCIL 1.76G LE 21', 'productPool/1.jpg', 231 ),
( 'COLORESSENCE LIP AND EYE PENCIL 1.76G LE-13', 'productPool/1.jpg', 114 ),
( 'COLORESSENCE LIP AND EYE PENCIL 1.76G LE-17', 'productPool/1.jpg', 40 ),
( 'COLORESSENCE LIP BLAM MIXED FRUIT', 'productPool/1.jpg', 52 ),
( 'COLORESSENCE LIP COLOR 20', 'productPool/1.jpg', 76 ),
( 'COLORESSENCE LIP COLOR 33', 'productPool/1.jpg', 230 ),
( 'COLORESSENCE LIP COLOR 34', 'productPool/1.jpg', 94 ),
( 'COLORESSENCE LIP COLOR 4G 11', 'productPool/1.jpg', 103 ),
( 'COLORESSENCE LIP COLOR 4G 40', 'productPool/1.jpg', 277 ),
( 'COLORESSENCE LIP COLOR 4G 45', 'productPool/1.jpg', 144 ),
( 'COLORESSENCE LIP COLOR 4G 52', 'productPool/1.jpg', 206 ),
( 'COLORESSENCE LIP COLOR 4G 60', 'productPool/1.jpg', 266 ),
( 'COLORESSENCE LIP COLOR 4G 67', 'productPool/1.jpg', 57 ),
( 'COLORESSENCE LIP COLOR 4G 68', 'productPool/1.jpg', 180 ),
( 'COLORESSENCE LIP COLOR 4G 74', 'productPool/1.jpg', 242 ),
( 'COLORESSENCE LIP COLOR 4G 76', 'productPool/1.jpg', 103 ),
( 'COLORESSENCE LIP COLOR 4G M1', 'productPool/1.jpg', 221 ),
( 'COLORESSENCE LIP COLOR 50', 'productPool/1.jpg', 73 ),
( 'COLORESSENCE LIP COLOR 63', 'productPool/1.jpg', 11 ),
( 'COLORESSENCE LIP COLOR 66', 'productPool/1.jpg', 18 ),
( 'COLORESSENCE LIP COLOR 7', 'productPool/1.jpg', 199 ),
( 'COLORESSENCE LIP COLOR 70', 'productPool/1.jpg', 25 ),
( 'COLORESSENCE LIP COLOR 71 4G', 'productPool/1.jpg', 78 ),
( 'COLORESSENCE LIP COLOR 73', 'productPool/1.jpg', 36 ),
( 'COLORESSENCE LIP COLOR 75 4G', 'productPool/1.jpg', 75 ),
( 'COLORESSENCE LIP COLOR 77 4G', 'productPool/1.jpg', 3 ),
( 'COLORESSENCE LIP COLOR 8', 'productPool/1.jpg', 71 ),
( 'COLORESSENCE LIP COLOR9 4G', 'productPool/1.jpg', 243 ),
( 'COLORESSENCE LIP COLOUR 4G 72', 'productPool/1.jpg', 252 ),
( 'COLORESSENCE LIP LINER PENCIL', 'productPool/1.jpg', 154 ),
( 'COLORESSENCE LIP LINER PENCIL .25G RUST', 'productPool/1.jpg', 187 ),
( 'COLORESSENCE LIP LINER PENCIL BRICK RED .25G', 'productPool/1.jpg', 165 ),
( 'COLORESSENCE LIP LINER PENCIL BROWN', 'productPool/1.jpg', 124 ),
( 'COLORESSENCE LIPBALM GREEN APPLE', 'productPool/1.jpg', 142 ),
( 'COLORESSENCE LIPBALM LEMON', 'productPool/1.jpg', 79 ),
( 'COLORESSENCE LIPLICIOUS GLOSS 6ML LLG-10', 'productPool/1.jpg', 26 ),
( 'COLORESSENCE LIPLICIOUS GLOSS 6ML LLG-12', 'productPool/1.jpg', 3 ),
( 'COLORESSENCE LIPLICIOUS GLOSS 6ML LLG-2', 'productPool/1.jpg', 138 ),
( 'COLORESSENCE LIPLICIOUS GLOSS 6ML LLG-5', 'productPool/1.jpg', 81 ),
( 'COLORESSENCE LIPLICIOUS GLOSS 6ML LLG-9', 'productPool/1.jpg', 46 ),
( 'COLORESSENCE LIPLICIOUS GLOSS LLG-11', 'productPool/1.jpg', 19 ),
( 'COLORESSENCE LIQUID LIP CLOUR LLP18', 'productPool/1.jpg', 45 ),
( 'COLORESSENCE LONG WEAR LIP COLOR LW2', 'productPool/1.jpg', 271 ),
( 'COLORESSENCE LONG WEAR LIP COLOR LW3', 'productPool/1.jpg', 225 ),
( 'COLORESSENCE LONG WEAR LIP COLOR LW7', 'productPool/1.jpg', 7 ),
( 'COLORESSENCE MAKEUP BASE 20ML', 'productPool/1.jpg', 72 ),
( 'COLORESSENCE MATTE LIP GLOSS LGM-01', 'productPool/1.jpg', 268 ),
( 'COLORESSENCE NAIL COLOR 10ML', 'productPool/1.jpg', 107 ),
( 'COLORESSENCE NAIL COLOR 5ML', 'productPool/1.jpg', 190 ),
( 'COLORESSENCE NAIL COLOR 9ML', 'productPool/1.jpg', 41 ),
( 'COLORESSENCE NAIL COLOR MINI 5ML', 'productPool/1.jpg', 161 ),
( 'COLORESSENCE NAIL COLOR REMOVER 30ML', 'productPool/1.jpg', 98 ),
( 'COLORESSENCE NAIL COLOR REMOVER 50ML', 'productPool/1.jpg', 214 ),
( 'COLORESSENCE NAIL COLOUR GEL AMETHYST 10ML', 'productPool/1.jpg', 221 ),
( 'COLORESSENCE NAIL COLOUR GEL AURA 10ML', 'productPool/1.jpg', 92 ),
( 'COLORESSENCE NAIL COLOUR GEL CHAMPAGNE 10ML', 'productPool/1.jpg', 268 ),
( 'COLORESSENCE NAIL COLOUR GEL COFFEE 10ML', 'productPool/1.jpg', 260 ),
( 'COLORESSENCE NAIL COLOUR GEL EGYPTION 10ML', 'productPool/1.jpg', 176 ),
( 'COLORESSENCE NAIL COLOUR GEL FLAMINGO 10ML', 'productPool/1.jpg', 213 ),
( 'COLORESSENCE NAIL COLOUR GEL HONEY GOLD 10ML', 'productPool/1.jpg', 244 ),
( 'COLORESSENCE NAIL COLOUR GEL INDEPENDENCE 10ML', 'productPool/1.jpg', 73 ),
( 'COLORESSENCE NAIL COLOUR GEL KESARI 10ML', 'productPool/1.jpg', 127 ),
( 'COLORESSENCE NAIL COLOUR GEL KUNZITE 10ML', 'productPool/1.jpg', 202 ),
( 'COLORESSENCE NAIL COLOUR GEL MIDNIGHT 10ML', 'productPool/1.jpg', 233 ),
( 'COLORESSENCE NAIL COLOUR GEL MIRAGE 10ML', 'productPool/1.jpg', 126 ),
( 'COLORESSENCE NAIL COLOUR GEL MYSTERY 10ML', 'productPool/1.jpg', 140 ),
( 'COLORESSENCE NAIL COLOUR GEL NUDE 10ML', 'productPool/1.jpg', 153 ),
( 'COLORESSENCE NAIL COLOUR GEL PERIWINKLE 10ML', 'productPool/1.jpg', 255 ),
( 'COLORESSENCE NAIL COLOUR GEL TOURMALINE 10ML', 'productPool/1.jpg', 1 ),
( 'COLORESSENCE NAIL COLOUR GEL ULTRA MARINE 10ML', 'productPool/1.jpg', 176 ),
( 'COLORESSENCE NAIL COLOUR GEL WHITE GOLD 10ML', 'productPool/1.jpg', 53 ),
( 'COLORESSENCE NAIL COLOUR GEL WINE 10ML', 'productPool/1.jpg', 178 ),
( 'COLORESSENCE NAIL COLOUR GEL ZIRCON10ML', 'productPool/1.jpg', 222 ),
( 'COLORESSENCE NAIL POLISH LARGE', 'productPool/1.jpg', 145 ),
( 'COLORESSENCE NAIL POLISH SMALL', 'productPool/1.jpg', 266 ),
( 'COLORESSENCE PANSTICK COLORS FS-4 12.5G', 'productPool/1.jpg', 17 ),
( 'COLORESSENCE PANSTICK FS-1 12.5G', 'productPool/1.jpg', 71 ),
( 'COLORESSENCE PANSTICK FS-5 12.5G', 'productPool/1.jpg', 134 ),
( 'COLORESSENCE PEARL EYE SHADE ES-2', 'productPool/1.jpg', 185 ),
( 'COLORESSENCE PEARL EYELINER 6ML', 'productPool/1.jpg', 158 ),
( 'COLORESSENCE PIGMENT MATTE PENCIL 3G HP-1', 'productPool/1.jpg', 236 ),
( 'COLORESSENCE PIGMENT MATTE PENCIL 3G HP-2', 'productPool/1.jpg', 114 ),
( 'COLORESSENCE PIGMENT MATTE PENCIL 3G HP-3', 'productPool/1.jpg', 40 ),
( 'COLORESSENCE PIGMENT MATTE PENCIL 3G HP-4', 'productPool/1.jpg', 61 ),
( 'COLORESSENCE PIGMENT MATTE PENCIL 3G HP-5', 'productPool/1.jpg', 31 ),
( 'COLORESSENCE PIGMENT MATTE PENCIL 3G HP-6', 'productPool/1.jpg', 7 ),
( 'COLORESSENCE PORE REFINER BASE PMB-01', 'productPool/1.jpg', 186 ),
( 'COLORESSENCE PRE MAKE UP BASE 30G', 'productPool/1.jpg', 15 ),
( 'COLORESSENCE PREMIA LIP COLOR 4G 107', 'productPool/1.jpg', 157 ),
( 'COLORESSENCE PREMIA LIP COLOR 4G 114', 'productPool/1.jpg', 233 ),
( 'COLORESSENCE PREMIA LIP COLOR 4G 115', 'productPool/1.jpg', 274 ),
( 'COLORESSENCE PREMIA LIP COLOR 4G 117', 'productPool/1.jpg', 231 ),
( 'COLORESSENCE PREMIA LIP COLOR 4G 206', 'productPool/1.jpg', 17 ),
( 'COLORESSENCE PREMIA LIP COLOR 4G 207', 'productPool/1.jpg', 45 ),
( 'COLORESSENCE PREMIA LIP COLOR 4G 209', 'productPool/1.jpg', 72 ),
( 'COLORESSENCE PREMIA LIP COLOR 4G 210', 'productPool/1.jpg', 232 ),
( 'COLORESSENCE PREMIA LIP COLOR 4G 216', 'productPool/1.jpg', 210 ),
( 'COLORESSENCE PREMIA LIP COLOR 4G 218', 'productPool/1.jpg', 65 ),
( 'COLORESSENCE PREMIA LIP COLOUR 107', 'productPool/1.jpg', 61 ),
( 'COLORESSENCE PREMIA LIP COLOUR 109 4G', 'productPool/1.jpg', 153 ),
( 'COLORESSENCE PREMIA LIP COLOUR 110', 'productPool/1.jpg', 20 ),
( 'COLORESSENCE PREMIA LIP COLOUR 113 4G', 'productPool/1.jpg', 255 ),
( 'COLORESSENCE PREMIA LIP COLOUR 201 4G', 'productPool/1.jpg', 24 ),
( 'COLORESSENCE PREMIA LIP COLOUR 211', 'productPool/1.jpg', 111 ),
( 'COLORESSENCE PREMIA LIP COLOUR 213', 'productPool/1.jpg', 55 ),
( 'COLORESSENCE PREMIA LIP COLOUR 220 4G', 'productPool/1.jpg', 97 ),
( 'COLORESSENCE PREMIA LIP COLOUR 4G 105', 'productPool/1.jpg', 108 ),
( 'COLORESSENCE PREMIA LIP COLOUR 4G 203', 'productPool/1.jpg', 237 ),
( 'COLORESSENCE PREMIA LIP COLOUR 4G 212', 'productPool/1.jpg', 158 ),
( 'COLORESSENCE PREMIA LIP COLOUR 4G 217', 'productPool/1.jpg', 279 ),
( 'COLORESSENCE PREMIA LIPCOLOUR 104 4G', 'productPool/1.jpg', 204 ),
( 'COLORESSENCE SATIN EYE SHADES BE BRIDE 2.5G', 'productPool/1.jpg', 72 ),
( 'COLORESSENCE SATIN EYE SHADES EARTHLY TONES 2.5G', 'productPool/1.jpg', 228 ),
( 'COLORESSENCE SATIN EYE SHADES FIRE DESIRE 2.5G', 'productPool/1.jpg', 55 ),
( 'COLORESSENCE SATIN EYE SHADES SES1 3*2.5G', 'productPool/1.jpg', 137 ),
( 'COLORESSENCE SATIN EYE SHADES SES13 3*2.5G', 'productPool/1.jpg', 249 ),
( 'COLORESSENCE SEMI MATTE LIP GLOSS LGM-03', 'productPool/1.jpg', 223 ),
( 'COLORESSENCE SEMI MATTE LIP GLOSS LGM-05', 'productPool/1.jpg', 115 ),
( 'COLORESSENCE SEMI MATTE LIP GLOSS LGM-07', 'productPool/1.jpg', 68 ),
( 'COLORESSENCE SEMI MATTE LIP GLOSS LGM-08', 'productPool/1.jpg', 13 ),
( 'COLORESSENCE SEMI MATTE LIP GLOSS LGM-09', 'productPool/1.jpg', 51 ),
( 'COLORESSENCE SEMI MATTE LIP GLOSS LGM-11', 'productPool/1.jpg', 128 ),
( 'COLORESSENCE SUPREME EYE LINER 6ML', 'productPool/1.jpg', 10 ),
( 'COLORESSENCE SUPREME EYELINER 6ML', 'productPool/1.jpg', 63 ),
( 'COLORESSENCE TRUE TONE COMPACT CMP-01', 'productPool/1.jpg', 262 ),
( 'COLORESSENCE TRUE TONE COMPACT CMP-03', 'productPool/1.jpg', 70 ),
( 'COLORESSENCE TRUE TONE COMPACT CMP-04', 'productPool/1.jpg', 54 ),
( 'COLORESSENCE TRUE TONE COMPACT CMP-05', 'productPool/1.jpg', 33 ),
( 'COLORESSENCE TRUE TONE COMPACT CMP-06', 'productPool/1.jpg', 102 ),
( 'COLORESSENCE TRUE TONE COMPACT CMP-2', 'productPool/1.jpg', 210 ),
( 'COLORESSENCE TRUE TONE FOUNDATION 30ML', 'productPool/1.jpg', 34 ),
( 'COLORESSENCE TRUE TONE FOUNDATION FND-01', 'productPool/1.jpg', 52 ),
( 'COLORESSENCE TRUE TONE FOUNDATION FND-04', 'productPool/1.jpg', 50 ),
( 'COLORESSENCE ULTRA LASH MASCARA 10ML', 'productPool/1.jpg', 134 ),
( 'COLORESSENCE WATER PROOF EYE + LIP LINER', 'productPool/1.jpg', 227 ),
( 'COLOROX CLEANER+BLEACH ORIGINAL 948ML', 'productPool/1.jpg', 53 ),
( 'COLORPIK HIGHLIGHTERS', 'productPool/1.jpg', 91 ),
( 'COLOURESSENCE MATTE LIP GLOSS LGM -04', 'productPool/1.jpg', 195 ),
( 'COLOURING BOOK', 'productPool/1.jpg', 231 ),
( 'COLRE AQUA SINDOOR 6ML', 'productPool/1.jpg', 166 ),
( 'COLRE DUAL COLHD EYE PEN 2.8G', 'productPool/1.jpg', 225 ),
( 'COLRE HIGDEFAN FACE POWDER FP-3 10G', 'productPool/1.jpg', 225 ),
( 'COLRE MASKARA WATPR 15ML', 'productPool/1.jpg', 182 ),
( 'COLRESSENCE STAI EYE SHADE 5G', 'productPool/1.jpg', 256 ),
( 'COMB 22.50', 'productPool/1.jpg', 257 ),
( 'COMB 5001 6PCS SET', 'productPool/1.jpg', 262 ),
( 'COMB 5004 6PCS', 'productPool/1.jpg', 9 ),
( 'COMB 7 INCH', 'productPool/1.jpg', 38 ),
( 'COMB IMP RS 3', 'productPool/1.jpg', 31 ),
( 'COMB IMP RS 5.25', 'productPool/1.jpg', 175 ),
( 'COMB RS 10.50', 'productPool/1.jpg', 255 ),
( 'COMB RS 14.50', 'productPool/1.jpg', 163 ),
( 'COMB RS 19.50', 'productPool/1.jpg', 110 ),
( 'COMB RS 2', 'productPool/1.jpg', 23 ),
( 'COMB RS 24', 'productPool/1.jpg', 167 ),
( 'COMB RS 3.50', 'productPool/1.jpg', 279 ),
( 'COMB RS 4', 'productPool/1.jpg', 107 ),
( 'COMB RS 4.75', 'productPool/1.jpg', 13 ),
( 'COMB RS 5.50', 'productPool/1.jpg', 161 ),
( 'COMB RS 5.75', 'productPool/1.jpg', 202 ),
( 'COMB RS 6', 'productPool/1.jpg', 212 ),
( 'COMB RS 6.50', 'productPool/1.jpg', 135 ),
( 'COMB RS 7', 'productPool/1.jpg', 99 ),
( 'COMB RS 7.50', 'productPool/1.jpg', 257 ),
( 'COMB RS1.75', 'productPool/1.jpg', 123 ),
( 'COMB RS10', 'productPool/1.jpg', 44 ),
( 'COMB RS105', 'productPool/1.jpg', 78 ),
( 'COMB RS110', 'productPool/1.jpg', 214 ),
( 'COMB RS125', 'productPool/1.jpg', 107 ),
( 'COMB RS16', 'productPool/1.jpg', 231 ),
( 'COMB RS18', 'productPool/1.jpg', 270 ),
( 'COMB Rs2', 'productPool/1.jpg', 40 ),
( 'COMB RS20.50', 'productPool/1.jpg', 234 ),
( 'COMB RS21', 'productPool/1.jpg', 233 ),
( 'COMB RS22.50', 'productPool/1.jpg', 216 ),
( 'COMB RS33', 'productPool/1.jpg', 77 ),
( 'COMB RS37', 'productPool/1.jpg', 165 ),
( 'COMB RS55', 'productPool/1.jpg', 238 ),
( 'COMB RS6.25', 'productPool/1.jpg', 19 ),
( 'COMB RS8.25', 'productPool/1.jpg', 46 ),
( 'COMB RS9', 'productPool/1.jpg', 250 ),
( 'COMFORT 2L IMP', 'productPool/1.jpg', 279 ),
( 'COMFORT BLUE FABRIC CONDITIONER 860ML', 'productPool/1.jpg', 202 ),
( 'COMFORT CLEAN TONGUE CLEANER', 'productPool/1.jpg', 209 ),
( 'COMFORT FAB BLUE 200ML', 'productPool/1.jpg', 148 ),
( 'COMFORT FAB COND BLUE 400ML', 'productPool/1.jpg', 129 ),
( 'COMFORT FAB COND BLUE 800ML', 'productPool/1.jpg', 116 ),
( 'COMFORT FAB COND GREEN 200ML', 'productPool/1.jpg', 176 ),
( 'COMFORT FAB COND GREEN 800ML', 'productPool/1.jpg', 104 ),
( 'COMFORT FAB COND PINK 200ML', 'productPool/1.jpg', 107 ),
( 'COMFORT FAB CONDITIONER BLUE 430ML', 'productPool/1.jpg', 251 ),
( 'COMFORT FABRIC CONDITIONER 5L', 'productPool/1.jpg', 50 ),
( 'COMFORT FABRIC CONDITIONER BLUE 200ML', 'productPool/1.jpg', 76 ),
( 'COMFORT FABRIC CONDITIONER BLUE 220ML', 'productPool/1.jpg', 98 ),
( 'COMFORT FABRIC CONDITIONER BLUE 400ML', 'productPool/1.jpg', 205 ),
( 'COMFORT FABRIC CONDITIONER GREEN 860ML', 'productPool/1.jpg', 63 ),
( 'COMFORT FABRIC CONDITIONER LIQUID 1.5L', 'productPool/1.jpg', 97 ),
( 'COMFORT FABRIC CONDITIONER LIQUID BLUE 1.5L', 'productPool/1.jpg', 252 ),
( 'COMFORT FABRIC CONDITIONER PINK 200ML', 'productPool/1.jpg', 49 ),
( 'COMFORT FABRIC CONDITIONER PINK 220ML', 'productPool/1.jpg', 67 ),
( 'COMFORT FABRIC CONDITIONER PINK 800ML', 'productPool/1.jpg', 191 ),
( 'COMFORT FABRIC CONDITIONER PINK 860ML', 'productPool/1.jpg', 234 ),
( 'COMPANION BASKET WITH LID FAMILY', 'productPool/1.jpg', 235 ),
( 'COMPLAN CHOCLATE 500 REFILL', 'productPool/1.jpg', 130 ),
( 'COMPLAN CHOCO 200G RFILL', 'productPool/1.jpg', 67 ),
( 'COMPLAN CHOCOLATE 200GM JAR', 'productPool/1.jpg', 145 ),
( 'COMPLAN CHOCOLATE 450G JAR', 'productPool/1.jpg', 52 ),
( 'COMPLAN CHOCOLATE FLAVOUR500G', 'productPool/1.jpg', 133 ),
( 'COMPLAN CREAMY CLASSIC 200G RF', 'productPool/1.jpg', 32 ),
( 'COMPLAN CREAMY CLASSIC 450G JR', 'productPool/1.jpg', 274 ),
( 'COMPLAN CREAMY CLASSIC 500 RF', 'productPool/1.jpg', 4 ),
( 'COMPLAN CREAMY CLASSIC 500G', 'productPool/1.jpg', 152 ),
( 'COMPLAN CREAMY CLASSIC 500G RF', 'productPool/1.jpg', 189 ),
( 'COMPLAN KESAR BADAM 200G JAR', 'productPool/1.jpg', 28 ),
( 'COMPLAN KESAR BADAM 200G RF', 'productPool/1.jpg', 31 ),
( 'COMPLAN KESAR BADAM 500G', 'productPool/1.jpg', 109 ),
( 'COMPLAN KESAR BADAM 500G JAR', 'productPool/1.jpg', 68 ),
( 'COMPLAN KESAR BADAM 500G RF', 'productPool/1.jpg', 21 ),
( 'COMPLAN MAGIC CHOCOLATE FLAVOUR 500G', 'productPool/1.jpg', 164 ),
( 'COMPLAN MAGIC COOKIE FLAVOUR 500G', 'productPool/1.jpg', 113 ),
( 'COMPLAN MEMORY 400G JAR', 'productPool/1.jpg', 8 ),
( 'COMPLAN MEMORY BADAM CHOCOLATE 450G JR', 'productPool/1.jpg', 267 ),
( 'COMPLAN NUTRI GRO BADAM KHEER 400G', 'productPool/1.jpg', 10 ),
( 'COMPLAN NUTRIGO CHOCLA FLV 400G', 'productPool/1.jpg', 12 ),
( 'COMPLAN NUTRIGRO BADAM KHEER 400G RF', 'productPool/1.jpg', 273 ),
( 'COMPLAN NUTRIGRO DELICIOUS CHOCOLATE 400G RF', 'productPool/1.jpg', 272 ),
( 'COMPLAN PISTA BADAM 500GM REFILL', 'productPool/1.jpg', 97 ),
( 'COMPLAN PISTA BADAM FLAVOUR 500G RF', 'productPool/1.jpg', 273 ),
( 'COMPLAN PLAIN 200G REFIL', 'productPool/1.jpg', 22 ),
( 'COMPLAN PLAIN 500G JAR', 'productPool/1.jpg', 83 ),
( 'COMPLAN PLAIN 500G REF', 'productPool/1.jpg', 213 ),
( 'COMPLAN ROYAL CHOCOLATE 500G RF', 'productPool/1.jpg', 212 ),
( 'COMPLAN ROYAL CHOCOLATE FLAVOUR 200G JAR', 'productPool/1.jpg', 94 ),
( 'COMPLAN ROYALE CHOCOLATE 200G RF', 'productPool/1.jpg', 199 ),
( 'COMPLAN ROYALE CHOCOLATE 450G JAR', 'productPool/1.jpg', 114 ),
( 'COMPLAN ROYALE CHOCOLATE 450G JR', 'productPool/1.jpg', 40 ),
( 'COMPLAN ROYALE CHOCOLATE 500G', 'productPool/1.jpg', 20 ),
( 'COMPLAN ROYALE CHOCOLATE 500G JR', 'productPool/1.jpg', 184 ),
( 'COMPLAN ROYALE CHOCOLATE 500G RF', 'productPool/1.jpg', 164 ),
( 'COMPLAN STRAWBERRY 500G REFILL', 'productPool/1.jpg', 274 ),
( 'COOKIES BISCUIT', 'productPool/1.jpg', 263 ),
( 'COOKING CUTTER AKX', 'productPool/1.jpg', 246 ),
( 'COOL AND COOL ACTIVE PRO BLUE REFRESHING WIPES', 'productPool/1.jpg', 272 ),
( 'COOL AND COOL ACTIVE PRO REFRESHING WIPES', 'productPool/1.jpg', 204 ),
( 'COOL AND COOL ALOE REFRESHING WIPES', 'productPool/1.jpg', 227 ),
( 'COOL AND COOL COTTON BUDS 100PIECES', 'productPool/1.jpg', 152 ),
( 'COOL AND COOL FLORAL REFRESHING WIPES', 'productPool/1.jpg', 270 ),
( 'COOL AND COOL LEMON REFRESHING WIPES', 'productPool/1.jpg', 107 ),
( 'COOL COOL TRAVELING WIPES 10WIPES', 'productPool/1.jpg', 254 ),
( 'COOL GULABJAL ROSE PETALS 150G', 'productPool/1.jpg', 115 ),
( 'COOL MINT CHEWING GUM IMP', 'productPool/1.jpg', 92 ),
( 'COPY GOLD 75 GSM PAPER', 'productPool/1.jpg', 200 ),
( 'CORAL BIRIYANI ESSANCES 20ML', 'productPool/1.jpg', 248 ),
( 'CORAL BUTTER FLAVOUR 100ML', 'productPool/1.jpg', 248 ),
( 'CORAL BUTTER FLAVOUR 20ML', 'productPool/1.jpg', 251 ),
( 'CORAL CARDAMOM ESSANCE 20ML', 'productPool/1.jpg', 192 ),
( 'CORAL CHOCOLATE FLAVOUR 20ML', 'productPool/1.jpg', 78 ),
( 'CORAL CORN FLOUR 1KG', 'productPool/1.jpg', 217 ),
( 'CORAL COROVIN ESSENCE', 'productPool/1.jpg', 161 ),
( 'CORAL CUSTARD POWDER 1KG', 'productPool/1.jpg', 14 ),
( 'CORAL ESSENCE VANILLA 20ML', 'productPool/1.jpg', 187 ),
( 'CORAL ICE CREAM ESSANCE 20ML', 'productPool/1.jpg', 190 ),
( 'CORAL LEMON ESSANCE 20ML', 'productPool/1.jpg', 74 ),
( 'CORAL MANGO ESSENCE', 'productPool/1.jpg', 138 ),
( 'CORAL MIXED FRUIT FLAVOUR 20ML', 'productPool/1.jpg', 77 ),
( 'CORAL ORANGE ESSENCE 20ML', 'productPool/1.jpg', 216 ),
( 'CORAL PINEAPPLE ESSENCE 20ML', 'productPool/1.jpg', 103 ),
( 'CORAL PISTA FLAVOUR 20ML', 'productPool/1.jpg', 135 ),
( 'CORAL ROSE WHITE ESSENCE 20ML', 'productPool/1.jpg', 75 ),
( 'CORAL STRAWBERRY ESSANCE 20ML', 'productPool/1.jpg', 175 ),
( 'CORIANDER POWDER 200G', 'productPool/1.jpg', 29 ),
( 'CORIANDER POWDER 500G', 'productPool/1.jpg', 59 ),
( 'CORN', 'productPool/1.jpg', 63 ),
( 'CORN FLOUR 1 KG', 'productPool/1.jpg', 227 ),
( 'CORNER RACK LEMON', 'productPool/1.jpg', 251 ),
( 'CORRECTION PEN', 'productPool/1.jpg', 107 ),
( 'COTON THIRI RS12', 'productPool/1.jpg', 51 ),
( 'COTTON BAG', 'productPool/1.jpg', 15 ),
( 'COTTON BUDS', 'productPool/1.jpg', 51 ),
( 'COTTON BUDS JAR RS20', 'productPool/1.jpg', 133 ),
( 'COTTON BUDS RS 11', 'productPool/1.jpg', 54 ),
( 'COTTON BUDS RS10', 'productPool/1.jpg', 25 ),
( 'COTTON BUDS RS20', 'productPool/1.jpg', 278 ),
( 'COTTON BUDS RS42', 'productPool/1.jpg', 168 ),
( 'COTTON BUDS WHITE JAR', 'productPool/1.jpg', 261 ),
( 'COTTON ROLL 25G', 'productPool/1.jpg', 249 ),
( 'COTTON ROLL50G', 'productPool/1.jpg', 216 ),
( 'COTTON ROPE', 'productPool/1.jpg', 59 ),
( 'COTTON THITRI', 'productPool/1.jpg', 56 ),
( 'COTTON THREAD', 'productPool/1.jpg', 132 ),
( 'COTTON WICK RS24', 'productPool/1.jpg', 220 ),
( 'COTTON WICK RS45', 'productPool/1.jpg', 31 ),
( 'COW GHEE 500ML', 'productPool/1.jpg', 270 ),
( 'COWPEA RED WHOLE 500G', 'productPool/1.jpg', 137 ),
( 'COWPEA WHITE WHOLE 500G', 'productPool/1.jpg', 79 ),
( 'CR LIP & EYE PENCIL LE-03 1.76G', 'productPool/1.jpg', 229 ),
( 'CR LIP & EYE PENCIL LE-06 1.76G', 'productPool/1.jpg', 16 ),
( 'CR LIP & EYE PENCIL LE-07 1.76G', 'productPool/1.jpg', 267 ),
( 'CR LIP & EYE PENCIL LE-11 1.76G', 'productPool/1.jpg', 44 ),
( 'CR LIP & EYE PENCIL LE-14 1.76G', 'productPool/1.jpg', 40 ),
( 'CR LIP & EYE PENCIL LE-22 1.76G', 'productPool/1.jpg', 83 ),
( 'CR LIP LINER PENCIL .25G BROWN', 'productPool/1.jpg', 210 ),
( 'CR LIP LINER PENCIL .25G MAUVE', 'productPool/1.jpg', 208 ),
( 'CR LIP LINER PENCIL MAROON 0.25G', 'productPool/1.jpg', 264 ),
( 'CREAME 21 (B) IMP', 'productPool/1.jpg', 14 ),
( 'CREAME 21 IMP (S)', 'productPool/1.jpg', 72 ),
( 'CREAME 21 IMP(M)', 'productPool/1.jpg', 246 ),
( 'CREATIONS CONTEST SHARPENER MRP 3', 'productPool/1.jpg', 34 ),
( 'CREATIONS FUNCLAY 150G 12SHADE', 'productPool/1.jpg', 18 ),
( 'CREATIONS FUNCLAY 225G 8COLOURS', 'productPool/1.jpg', 133 ),
( 'CREATIONS HIFI DUST OFF ERASERS MRP 3', 'productPool/1.jpg', 186 ),
( 'CREATIONS KRAZEE DOUGH 240G', 'productPool/1.jpg', 163 ),
( 'CREATIONS LONG POINT SHARPENER', 'productPool/1.jpg', 246 ),
( 'CREATIONS OIL PASTELS 16SHADES', 'productPool/1.jpg', 127 ),
( 'CREATIONS SHARPENER', 'productPool/1.jpg', 35 ),
( 'CREATIONS WOW WAX CRAYONS CJC 13N', 'productPool/1.jpg', 6 ),
( 'CREATIONS WOW WAX CRAYONS MCC 12S', 'productPool/1.jpg', 25 ),
( 'CREATIONS YOYO KOOL PENCIL', 'productPool/1.jpg', 11 ),
( 'CREME 21 (M)', 'productPool/1.jpg', 167 ),
( 'CREMICA EGG MAYONISE 275G', 'productPool/1.jpg', 107 ),
( 'CREMICA EGG MAYONISE 450GM', 'productPool/1.jpg', 227 ),
( 'CREMICA MAYONISE CHEESE 300G', 'productPool/1.jpg', 14 ),
( 'CREMICA MAYONISE CLASSIC 300G', 'productPool/1.jpg', 65 ),
( 'CREMICA VEG MAYONAISE 275G', 'productPool/1.jpg', 103 ),
( 'CREMICA VEG MAYONISE 450GM', 'productPool/1.jpg', 202 ),
( 'CRESS 1LTR DREAMS', 'productPool/1.jpg', 184 ),
( 'CRESS 1LTR FLORAL', 'productPool/1.jpg', 87 ),
( 'CRESS 1LTR LAVENDER', 'productPool/1.jpg', 54 ),
( 'CRESS 1LTR LEMON', 'productPool/1.jpg', 241 ),
( 'CRESS 1LTR ORANGE', 'productPool/1.jpg', 5 ),
( 'CRESS 500 ML DREAMS', 'productPool/1.jpg', 67 ),
( 'CRESS 500 ML FLORAL', 'productPool/1.jpg', 37 ),
( 'CRESS 500 ML LEMON', 'productPool/1.jpg', 247 ),
( 'CRESS 500 ML ORANGE', 'productPool/1.jpg', 15 ),
( 'CRESS LAVENDER 500ML', 'productPool/1.jpg', 79 ),
( 'CRISHLEYS CHOCOLATE 800G', 'productPool/1.jpg', 19 ),
( 'CRUST & CRUMB BAKING POWDER 100G', 'productPool/1.jpg', 15 ),
( 'CRUST & CRUMB BLACK FOREST CAKE MIX 300G', 'productPool/1.jpg', 135 ),
( 'CRUST & CRUMB BROWNIE MIX 200G', 'productPool/1.jpg', 228 ),
( 'CRUST & CRUMB CHOCOLATE CAKE MIX 300G', 'productPool/1.jpg', 53 ),
( 'CRUST & CRUMB CORN FLOUR 100G', 'productPool/1.jpg', 65 ),
( 'CRUST & CRUMB CRISPY CHICKEN MIX ORIGINAL FLAVOUR 200GMS', 'productPool/1.jpg', 193 ),
( 'CRUST & CRUMB CUSTARD POWDER 100G', 'productPool/1.jpg', 275 ),
( 'CRUST & CRUMB CUTLET MIX COATING 200G', 'productPool/1.jpg', 136 ),
( 'CRUST & CRUMB FALUDA MIX', 'productPool/1.jpg', 40 ),
( 'CRUST & CRUMB ICE CREAM MIX BUTTERSCOTCH 100G', 'productPool/1.jpg', 218 ),
( 'CRUST & CRUMB ICE CREAM MIX CHOCOLATE 100G', 'productPool/1.jpg', 182 ),
( 'CRUST & CRUMB ICE CREAM MIX PISTA FLAVOUR 100GMS', 'productPool/1.jpg', 245 ),
( 'CRUST & CRUMB ICE CREAM MIX STRAWBERRY 100 GMS', 'productPool/1.jpg', 206 ),
( 'CRUST & CRUMB ICE CREAM MIX VANILA FLAVOUR 100GMS', 'productPool/1.jpg', 246 ),
( 'CRUST & CRUMB ICECREAM MIX MANGO100G', 'productPool/1.jpg', 66 ),
( 'CRUST & CRUMB ICECREAM MIX PINAPPLE 100G', 'productPool/1.jpg', 22 ),
( 'CRUST & CRUMB INSTANT CHICKEN MIX PEPPER & SPICY 200GMS', 'productPool/1.jpg', 210 ),
( 'CRUST & CRUMB KASURI METHI 25G', 'productPool/1.jpg', 4 ),
( 'CRUST & CRUMB MILK SHAKE BUTTERSCOTCH 125G', 'productPool/1.jpg', 254 ),
( 'CRUST & CRUMB MILK SHAKE VANILA 300G', 'productPool/1.jpg', 41 ),
( 'CRUST & CRUMB PAN CAKE MIX 300G', 'productPool/1.jpg', 201 ),
( 'CRUST & CRUMB PLUM CAKE MIX 300G', 'productPool/1.jpg', 114 ),
( 'CRUST & CRUMB RED VELVET CAKE MIX 300G', 'productPool/1.jpg', 7 ),
( 'CRUST & CRUMB SPICY CHIKEN MIX 200G', 'productPool/1.jpg', 199 ),
( 'CRUST & CRUMB WHIPPING CREAM POWDER 50G', 'productPool/1.jpg', 134 ),
( 'CRUST & CRUMB WHIPPING POWDER 100G', 'productPool/1.jpg', 23 ),
( 'CRUST &CRUMB MILK SHAKE POWDER CAPP125G', 'productPool/1.jpg', 239 ),
( 'CRUST AND CRUMB CHOCOLATE DRINK MIX 100G', 'productPool/1.jpg', 144 ),
( 'CRUST AND CRUMB MERA ALMOND DATES 350G', 'productPool/1.jpg', 211 ),
( 'CRUST AND CRUMB MERA CASHEW DATES 350G', 'productPool/1.jpg', 57 );