INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'PAMPERS ACTIVE BABY MD 62S', 'productPool/1.jpg', 277 ),
( 'PAMPERS ACTIVE BABY MEDIUM 20S', 'productPool/1.jpg', 245 ),
( 'PAMPERS ACTIVE BABY MEDIUM 90', 'productPool/1.jpg', 219 ),
( 'PAMPERS ACTIVE BABY MEDIUM 90S', 'productPool/1.jpg', 9 ),
( 'PAMPERS ACTIVE BABY NEW BABY 72S', 'productPool/1.jpg', 190 ),
( 'PAMPERS ACTIVE BABY SMALL 22S', 'productPool/1.jpg', 250 ),
( 'PAMPERS ACTIVE BABY SMALL 46', 'productPool/1.jpg', 83 ),
( 'PAMPERS ACTIVE BABY SMALL 46S', 'productPool/1.jpg', 54 ),
( 'PAMPERS ACTIVE BABY XL 32', 'productPool/1.jpg', 175 ),
( 'PAMPERS ACTIVE BABY XL 32S', 'productPool/1.jpg', 226 ),
( 'PAMPERS ACTIVE BABY XL 56', 'productPool/1.jpg', 270 ),
( 'PAMPERS ACTIVE BABY XL 56S', 'productPool/1.jpg', 183 ),
( 'PAMPERS BABY DRY LARGE 20', 'productPool/1.jpg', 196 ),
( 'PAMPERS BABY DRY MEDIUM 20', 'productPool/1.jpg', 210 ),
( 'PAMPERS BABY DRY MEDIUM 76', 'productPool/1.jpg', 135 ),
( 'PAMPERS BABY DRY PANTS M56S', 'productPool/1.jpg', 152 ),
( 'PAMPERS BABY DRY XL 56', 'productPool/1.jpg', 210 ),
( 'PAMPERS BABY DRY-PANTS SMALL 60', 'productPool/1.jpg', 188 ),
( 'PAMPERS BABY PANTS SMALL 24S', 'productPool/1.jpg', 206 ),
( 'PAMPERS BABY PANTS XL 44N', 'productPool/1.jpg', 79 ),
( 'PAMPERS BABY WIPES 64NOS', 'productPool/1.jpg', 265 ),
( 'PAMPERS BABY WIPES 64S', 'productPool/1.jpg', 98 ),
( 'PAMPERS BABY WIPES 8S', 'productPool/1.jpg', 220 ),
( 'PAMPERS FRESH CLEAN WIPES B3G1', 'productPool/1.jpg', 19 ),
( 'PAMPERS IMAX LARGE 18S', 'productPool/1.jpg', 131 ),
( 'PAMPERS IMAX LARGE 60S', 'productPool/1.jpg', 183 ),
( 'PAMPERS IMAX MD 20S', 'productPool/1.jpg', 117 ),
( 'PAMPERS IMAX MEDIUM 20S', 'productPool/1.jpg', 240 ),
( 'PAMPERS IMAX MEDIUM 66S', 'productPool/1.jpg', 169 ),
( 'PAMPERS IMAX SM 46S', 'productPool/1.jpg', 55 ),
( 'PAMPERS IMAX SMALL 46S', 'productPool/1.jpg', 157 ),
( 'PAMPERS NEW BABY 24S', 'productPool/1.jpg', 264 ),
( 'PAMPERS NEW BABY 72S', 'productPool/1.jpg', 146 ),
( 'PAMPERS NEW BABY SMALL 11S', 'productPool/1.jpg', 44 ),
( 'PAMPERS NEW BABY SMALL 20S', 'productPool/1.jpg', 240 ),
( 'PAMPERS NEW BABY SMALL 60S', 'productPool/1.jpg', 111 ),
( 'PAMPERS NEW BABY XS 60S', 'productPool/1.jpg', 251 ),
( 'PAMPERS NEWBABY SMALL 11S', 'productPool/1.jpg', 121 ),
( 'PAMPERS PANTAS LARGE 96S MAEGA PACK', 'productPool/1.jpg', 146 ),
( 'PAMPERS PANTS LARGE 20S', 'productPool/1.jpg', 173 ),
( 'PAMPERS PANTS LARGE 24S', 'productPool/1.jpg', 80 ),
( 'PAMPERS PANTS LARGE 2S', 'productPool/1.jpg', 116 ),
( 'PAMPERS PANTS LARGE 30', 'productPool/1.jpg', 264 ),
( 'PAMPERS PANTS LARGE 30S', 'productPool/1.jpg', 264 ),
( 'PAMPERS PANTS LARGE 44S', 'productPool/1.jpg', 17 ),
( 'PAMPERS PANTS LARGE 46S', 'productPool/1.jpg', 183 ),
( 'PAMPERS PANTS LARGE 48N', 'productPool/1.jpg', 159 ),
( 'PAMPERS PANTS LARGE 64S', 'productPool/1.jpg', 155 ),
( 'PAMPERS PANTS LARGE 64S SUPER JUMBO', 'productPool/1.jpg', 56 ),
( 'PAMPERS PANTS LARGE 7S', 'productPool/1.jpg', 232 ),
( 'PAMPERS PANTS LARGE 8S', 'productPool/1.jpg', 140 ),
( 'PAMPERS PANTS LG 20S', 'productPool/1.jpg', 97 ),
( 'PAMPERS PANTS LG 64S', 'productPool/1.jpg', 243 ),
( 'PAMPERS PANTS MEDIUM 112S MEGA PACK', 'productPool/1.jpg', 276 ),
( 'PAMPERS PANTS MEDIUM 14S', 'productPool/1.jpg', 59 ),
( 'PAMPERS PANTS MEDIUM 20S', 'productPool/1.jpg', 13 ),
( 'PAMPERS PANTS MEDIUM 28S', 'productPool/1.jpg', 222 ),
( 'PAMPERS PANTS MEDIUM 2S', 'productPool/1.jpg', 82 ),
( 'PAMPERS PANTS MEDIUM 38S', 'productPool/1.jpg', 170 ),
( 'PAMPERS PANTS MEDIUM 4S', 'productPool/1.jpg', 199 ),
( 'PAMPERS PANTS MEDIUM 54S', 'productPool/1.jpg', 259 ),
( 'PAMPERS PANTS MEDIUM 76S', 'productPool/1.jpg', 247 ),
( 'PAMPERS PANTS MEDIUM 80S', 'productPool/1.jpg', 256 ),
( 'PAMPERS PANTS MEDIUM 8S', 'productPool/1.jpg', 192 ),
( 'PAMPERS PANTS NB S 22S', 'productPool/1.jpg', 188 ),
( 'PAMPERS PANTS NB SMALL 10S', 'productPool/1.jpg', 107 ),
( 'PAMPERS PANTS NB SMALL 20S', 'productPool/1.jpg', 268 ),
( 'PAMPERS PANTS NB XS 10S', 'productPool/1.jpg', 17 ),
( 'PAMPERS PANTS NB XS 20S', 'productPool/1.jpg', 188 ),
( 'PAMPERS PANTS NEW BABY 10S', 'productPool/1.jpg', 45 ),
( 'PAMPERS PANTS NEW BABY 86S', 'productPool/1.jpg', 15 ),
( 'PAMPERS PANTS PREMIUM CARE SMALL 50S', 'productPool/1.jpg', 107 ),
( 'PAMPERS PANTS SM 8', 'productPool/1.jpg', 231 ),
( 'PAMPERS PANTS SMALL 144S MEGA PACK', 'productPool/1.jpg', 174 ),
( 'PAMPERS PANTS SMALL 20S', 'productPool/1.jpg', 60 ),
( 'PAMPERS PANTS SMALL 2S', 'productPool/1.jpg', 203 ),
( 'PAMPERS PANTS SMALL 36S', 'productPool/1.jpg', 66 ),
( 'PAMPERS PANTS SMALL 40S', 'productPool/1.jpg', 278 ),
( 'PAMPERS PANTS SMALL 58S', 'productPool/1.jpg', 269 ),
( 'PAMPERS PANTS SMALL 60S', 'productPool/1.jpg', 163 ),
( 'PAMPERS PANTS SMALL 60S SUPER JUMBO', 'productPool/1.jpg', 201 ),
( 'PAMPERS PANTS SMALL 86S', 'productPool/1.jpg', 46 ),
( 'PAMPERS PANTS SMALL 86S SJ', 'productPool/1.jpg', 198 ),
( 'PAMPERS PANTS SMALL 86S SUPER JUMBO', 'productPool/1.jpg', 190 ),
( 'PAMPERS PANTS SMALL 8S', 'productPool/1.jpg', 102 ),
( 'PAMPERS PANTS SMALL 9S', 'productPool/1.jpg', 227 ),
( 'PAMPERS PANTS XL 19S', 'productPool/1.jpg', 180 ),
( 'PAMPERS PANTS XL 20S', 'productPool/1.jpg', 85 ),
( 'PAMPERS PANTS XL 21S', 'productPool/1.jpg', 213 ),
( 'PAMPERS PANTS XL 26', 'productPool/1.jpg', 58 ),
( 'PAMPERS PANTS XL 26S', 'productPool/1.jpg', 15 ),
( 'PAMPERS PANTS XL 36S', 'productPool/1.jpg', 93 ),
( 'PAMPERS PANTS XL 38S', 'productPool/1.jpg', 206 ),
( 'PAMPERS PANTS XL 56 S SUPER JUMBO', 'productPool/1.jpg', 65 ),
( 'PAMPERS PANTS XL 56S', 'productPool/1.jpg', 55 ),
( 'PAMPERS PANTS XL 7S', 'productPool/1.jpg', 36 ),
( 'PAMPERS PANTS XL56', 'productPool/1.jpg', 90 ),
( 'PAMPERS PANTS XL7 PADS', 'productPool/1.jpg', 104 ),
( 'PAMPERS PANTS XXL 10S', 'productPool/1.jpg', 130 ),
( 'PAMPERS PANTS XXL 20S', 'productPool/1.jpg', 270 ),
( 'PAMPERS PANTS XXL 22S', 'productPool/1.jpg', 107 ),
( 'PAMPERS PANTS XXL 28S', 'productPool/1.jpg', 11 ),
( 'PAMPERS PANTS XXL 32S', 'productPool/1.jpg', 157 ),
( 'PAMPERS PANTS XXXL 23S', 'productPool/1.jpg', 126 ),
( 'PAMPERS PANTS XXXL 7', 'productPool/1.jpg', 151 ),
( 'PAMPERS PREMIUM CARE LARGE 44', 'productPool/1.jpg', 35 ),
( 'PAMPERS PREMIUM CARE PANT MEDIUM 54S', 'productPool/1.jpg', 240 ),
( 'PAMPERS PREMIUM CARE PANTS NEW BABY 24S', 'productPool/1.jpg', 16 ),
( 'PAMPERS PREMIUM CARE PANTS NEW BABY 54S', 'productPool/1.jpg', 157 ),
( 'PAMPERS PREMIUM CARE PANTS XL 36S', 'productPool/1.jpg', 220 ),
( 'PAMPERS PREMIUM PANT LARGE 44S', 'productPool/1.jpg', 82 ),
( 'PAMPERS PREMIUM PANT MEDIUM 20S', 'productPool/1.jpg', 224 ),
( 'PAMPERS PREMIUM PANT SMALL 9S', 'productPool/1.jpg', 93 ),
( 'PAMPERS PREMIUM PANT XL 16', 'productPool/1.jpg', 165 ),
( 'PAMPERS PREMIUM PANT XL 28S', 'productPool/1.jpg', 262 ),
( 'PAMPERS PREMIUM PANT XS 8S', 'productPool/1.jpg', 1 ),
( 'PAMPERS PREMIUM PANTS LARGE 20', 'productPool/1.jpg', 279 ),
( 'PAMPERS PREMIUM PANTS LARGE 20S', 'productPool/1.jpg', 186 ),
( 'PAMPERS PREMIUM PANTS LARGE 30S', 'productPool/1.jpg', 106 ),
( 'PAMPERS PREMIUM PANTS MEDIUM 22S', 'productPool/1.jpg', 180 ),
( 'PAMPERS PREMIUM PANTS MEDIUM 54S', 'productPool/1.jpg', 118 ),
( 'PAMPERS PREMIUM PANTS MEDIUM 64S', 'productPool/1.jpg', 217 ),
( 'PAMPERS PREMIUM PANTS NB 24S', 'productPool/1.jpg', 227 ),
( 'PAMPERS PREMIUM PANTS S 24S', 'productPool/1.jpg', 278 ),
( 'PAMPERS PREMIUM PANTS SMALL 28S', 'productPool/1.jpg', 225 ),
( 'PAMPERS PREMIUM PANTS SMALL 50S', 'productPool/1.jpg', 261 ),
( 'PAMPERS PREMIUM PANTS XL 19S', 'productPool/1.jpg', 6 ),
( 'PAMPERS PREMIUM PANTS XL 24S', 'productPool/1.jpg', 63 ),
( 'PAMPERS PREMIUM PANTS XL 36S', 'productPool/1.jpg', 153 ),
( 'PAMPERS PREMIUM PANTS XS 24S', 'productPool/1.jpg', 211 ),
( 'PAMPERS PREMIUN PANTS MEDIUM 38S', 'productPool/1.jpg', 206 ),
( 'PAMPERS PREMIUN PANTS SMALL 72S', 'productPool/1.jpg', 62 ),
( 'PANAMKALKANDAM 100G', 'productPool/1.jpg', 204 ),
( 'PANASONIC 1050 HYPER BATTERY', 'productPool/1.jpg', 39 ),
( 'PANASONIC AA BATTERY', 'productPool/1.jpg', 150 ),
( 'PANASONIC AAA BATTERY', 'productPool/1.jpg', 59 ),
( 'PANASONIC ALKALINE AA BATTERY', 'productPool/1.jpg', 46 ),
( 'PANASONIC ALKALINE AAA BATTERY', 'productPool/1.jpg', 168 ),
( 'PANASONIC GOLD 1050', 'productPool/1.jpg', 214 ),
( 'PANASONIC HYPER 1035 BATTERY', 'productPool/1.jpg', 250 ),
( 'PANASONIC ZINC BATTERY 9V', 'productPool/1.jpg', 244 ),
( 'PANDI CHILLI 100G', 'productPool/1.jpg', 154 ),
( 'PANDI CHILLI 250G', 'productPool/1.jpg', 241 ),
( 'PANDI CHILLI 500G', 'productPool/1.jpg', 214 ),
( 'PANDI CHILLY 100G', 'productPool/1.jpg', 31 ),
( 'PANEER PUFFS', 'productPool/1.jpg', 261 ),
( 'PANJABI PAPAD 200G', 'productPool/1.jpg', 261 ),
( 'PANKAJ KASTHURI BREATH EAZY 200G', 'productPool/1.jpg', 223 ),
( 'PANKAJAKASTHURI BABY OIL 100ML', 'productPool/1.jpg', 61 ),
( 'PANKAJAKASTHURI BREATHEAZY 400G', 'productPool/1.jpg', 253 ),
( 'PANKAJAKASTHURI BREATHEAZY SYRUP 200ML', 'productPool/1.jpg', 150 ),
( 'PANKAJAKASTHURI CLEAR FOOT 25G', 'productPool/1.jpg', 49 ),
( 'PANKAJAKASTHURI COUGH SYRUP 100ML', 'productPool/1.jpg', 278 ),
( 'PANKAJAKASTHURI COUGH TULASI SYRUP 100ML', 'productPool/1.jpg', 204 ),
( 'PANKAJAKASTHURI DANDRUFF OIL 100ML', 'productPool/1.jpg', 55 ),
( 'PANKAJAKASTHURI KASTHURI HERBALSOAP 75G', 'productPool/1.jpg', 107 ),
( 'PANKAJAKASTHURI KASTHURI HERBALSOAP 75G*4', 'productPool/1.jpg', 26 ),
( 'PANKAJAKASTHURI KAVERI PURE HERBAL SOAP 90', 'productPool/1.jpg', 123 ),
( 'PANKAJAKASTHURI MAYUKHI HAIR OIL 100ML', 'productPool/1.jpg', 74 ),
( 'PANKAJAKASTHURI ORTHOHERB OIL PAIN RELIEF 100ML', 'productPool/1.jpg', 182 ),
( ' ', 'productPool/1.jpg', 196 ),
( 'PANTENE ADS LONG BLACK SHAMPOO 180ML', 'productPool/1.jpg', 199 ),
( 'PANTENE AHF LONG BLACK SHAMPOO 75ML', 'productPool/1.jpg', 268 ),
( 'PANTENE AHS ANTI DANDRUFF SHAMPOO 180ML', 'productPool/1.jpg', 190 ),
( 'PANTENE AHS HAIRFALL CONTROL SHAMPOO 180ML', 'productPool/1.jpg', 13 ),
( 'PANTENE AHS HAIRFALL CONTROL SHAMPOO 340ML', 'productPool/1.jpg', 4 ),
( 'PANTENE AHS HAIRFALL CONTROL SHAMPOO 650ML', 'productPool/1.jpg', 76 ),
( 'PANTENE AHS HAIRFALL CONTROL SHAMPOO 75ML', 'productPool/1.jpg', 26 ),
( 'PANTENE AHS HFC CONDITIONER 180ML', 'productPool/1.jpg', 10 ),
( 'PANTENE AHS HFC CONDITIONER 80ML', 'productPool/1.jpg', 268 ),
( 'PANTENE AHS LIVELY CLEAN SHAMPOO 200ML', 'productPool/1.jpg', 7 ),
( 'PANTENE AHS LIVELY CLEAN SHAMPOO 400ML', 'productPool/1.jpg', 256 ),
( 'PANTENE AHS LIVELY CLEAN SHAMPOO 650ML', 'productPool/1.jpg', 158 ),
( 'PANTENE AHS LONG BLACK SHAMPOO 340ML', 'productPool/1.jpg', 50 ),
( 'PANTENE AHS SILKY SMOOTH CARE CONDITIONER80ML', 'productPool/1.jpg', 228 ),
( 'PANTENE AHS SILKY SMOOTH CARE SHAMPOO 180ML', 'productPool/1.jpg', 210 ),
( 'PANTENE AHS SILKY SMOOTH CARE SHAMPOO 340ML', 'productPool/1.jpg', 192 ),
( 'PANTENE AHS SILKY SMOOTH CARE SHAMPOO 650ML', 'productPool/1.jpg', 257 ),
( 'PANTENE AHS SILKY SMOOTH CARE SHAMPOO 75ML', 'productPool/1.jpg', 269 ),
( 'PANTENE AHS TOTAL DAMAGE CARE CONDITIONER 180ML', 'productPool/1.jpg', 79 ),
( 'PANTENE AHS TOTAL DAMAGE CARE CONDITIONER 80ML', 'productPool/1.jpg', 220 ),
( 'PANTENE AHS TOTAL DAMAGE SHAMPOO 340ML', 'productPool/1.jpg', 156 ),
( 'PANTENE ANTI DANDRUFF SHAMPOO 180ML', 'productPool/1.jpg', 236 ),
( 'PANTENE CONDITIONER 8ML', 'productPool/1.jpg', 140 ),
( 'PANTENE CONDITIONER HAIR FALL CONTROL 175ML', 'productPool/1.jpg', 263 ),
( 'PANTENE CONDITIONER HFC 75ML', 'productPool/1.jpg', 145 ),
( 'PANTENE CONDITIONER SILKY SMOOTH 175ML', 'productPool/1.jpg', 269 ),
( 'PANTENE CONDITIONER SILKY SMOOTH SHAMPOO 75ML', 'productPool/1.jpg', 55 ),
( 'PANTENE CONDITIONER TOTAL DAMAGE CARE 75ML', 'productPool/1.jpg', 24 ),
( 'PANTENE CONDITIONERSSC 75ML', 'productPool/1.jpg', 4 ),
( 'PANTENE DAILY MOISTURE RENEWAL 75ML', 'productPool/1.jpg', 122 ),
( 'PANTENE DAILY MOISTURE RENEWAL SHAMPOO 180ML', 'productPool/1.jpg', 158 ),
( 'PANTENE DAILY MOISTURE RENEWAL SHAMPOO 360ML', 'productPool/1.jpg', 263 ),
( 'PANTENE HAIR FALL CONTORL SHAMPOO 675ML', 'productPool/1.jpg', 31 ),
( 'PANTENE HAIR FALL CONTROL 180ML', 'productPool/1.jpg', 26 ),
( 'PANTENE HAIR FALL CONTROL SHAMPOO 340ML', 'productPool/1.jpg', 52 ),
( 'PANTENE HAIR FULL SHAMPOO 340ML', 'productPool/1.jpg', 178 ),
( 'PANTENE HAIR SHAMPOO 80ML', 'productPool/1.jpg', 117 ),
( 'PANTENE HAIRFALL CONTROL SHAMPOO 675ML', 'productPool/1.jpg', 93 ),
( 'PANTENE HAIRFALL SHAMPOO 180ML', 'productPool/1.jpg', 43 ),
( 'PANTENE LIVELY CLEAN AHS SHAMPOO 90ML', 'productPool/1.jpg', 45 ),
( 'PANTENE LIVELY CLEAN SHAMPOO 200ML', 'productPool/1.jpg', 126 ),
( 'PANTENE LIVELY CLEAN SHAMPOO 400ML', 'productPool/1.jpg', 17 ),
( 'PANTENE LIVELY CLEAN SHAMPOO 675ML', 'productPool/1.jpg', 87 ),
( 'PANTENE LONG BLACK SHAMPOO 180ML', 'productPool/1.jpg', 86 ),
( 'PANTENE LONG BLACK SHAMPOO 72ML', 'productPool/1.jpg', 225 ),
( 'PANTENE LONG BLACK SHAMPOO 80ML', 'productPool/1.jpg', 211 ),
( 'PANTENE OIL REPLACEMENT 180ML', 'productPool/1.jpg', 211 ),
( 'PANTENE OIL REPLACEMENT 80ML', 'productPool/1.jpg', 195 ),
( 'PANTENE PRO-V SMOOTH CARE CONDITIONER 180ML', 'productPool/1.jpg', 167 ),
( 'PANTENE PRO-V TOTAL DAMAGE CARE SHAMPOO75ML', 'productPool/1.jpg', 213 ),
( 'PANTENE SHAMPOO HAIR FALL CONTROL 180ML', 'productPool/1.jpg', 260 ),
( 'PANTENE SHAMPOO HAIR FALL CONTROL 360ML', 'productPool/1.jpg', 205 ),
( 'PANTENE SHAMPOO HAIR FALL CONTROL 72ML', 'productPool/1.jpg', 243 ),
( 'PANTENE SHAMPOO LIVELY CLEAN 90ML', 'productPool/1.jpg', 121 ),
( 'PANTENE SHAMPOO LIVELY CLN 200ML', 'productPool/1.jpg', 137 ),
( 'PANTENE SHAMPOO LIVELY CLN 400ML', 'productPool/1.jpg', 266 ),
( 'PANTENE SHAMPOO LONG BLACK 180ML', 'productPool/1.jpg', 207 ),
( 'PANTENE SHAMPOO LONG BLACK 360ML', 'productPool/1.jpg', 239 ),
( 'PANTENE SHAMPOO SILKY SMOOTH CARE 72ML', 'productPool/1.jpg', 157 ),
( 'PANTENE SHAMPOO SSC 80ML', 'productPool/1.jpg', 107 ),
( 'PANTENE SHAMPOO TDC 180ML', 'productPool/1.jpg', 134 ),
( 'PANTENE SHAMPOO TDC 80ML', 'productPool/1.jpg', 168 ),
( 'PANTENE SHAMPOO TOTAL DAMAGE CARE 180ML', 'productPool/1.jpg', 60 ),
( 'PANTENE SILKY SMOOTH CARE 180ML', 'productPool/1.jpg', 208 ),
( 'PANTENE SILKY SMOOTH CARE 72ML', 'productPool/1.jpg', 111 ),
( 'PANTENE SILKY SMOOTH CARE SHAMPOO 340 ML', 'productPool/1.jpg', 139 ),
( 'PANTENE SILKY SMOOTH CARE SHAMPOO 360ML', 'productPool/1.jpg', 47 ),
( 'PANTENE SILKY SMOOTH CARE SHAMPOO 675ML', 'productPool/1.jpg', 271 ),
( 'PANTENE SILKY SMOOTH SHAMPOO CARE 675ML', 'productPool/1.jpg', 22 ),
( 'PANTENE SLIKY SMOOTH CARE SHAMPOO 360ML', 'productPool/1.jpg', 2 ),
( 'PANTENE SMOOTH SHAMPOO SSC 180ML', 'productPool/1.jpg', 247 ),
( 'PANTENE TDC CONDITIONER 175ML', 'productPool/1.jpg', 274 ),
( 'PANTENE TDC CONDITIONER 75ML', 'productPool/1.jpg', 103 ),
( 'PANTENE TDC SHAMPOO 360ML', 'productPool/1.jpg', 146 ),
( 'PANTENE THICKER STRONGER 675ML', 'productPool/1.jpg', 211 ),
( 'PANTENE TOTAL DAMAGE CARE 675ML', 'productPool/1.jpg', 176 ),
( 'PANTENE TOTAL DAMAGE CARE AHS SHAMPOO 180ML', 'productPool/1.jpg', 9 ),
( 'PANTENE TOTAL DAMAGE CARE SHAMPOO 180ML', 'productPool/1.jpg', 45 ),
( 'PANTENE TOTAL DAMAGE CARE SHAMPOO 340 ML', 'productPool/1.jpg', 14 ),
( 'PANTENE TOTAL DAMAGE CARE SHAMPOO 360ML', 'productPool/1.jpg', 220 ),
( 'PANTENE TOTAL DAMAGE CARE SHAMPOO 72ML', 'productPool/1.jpg', 162 ),
( 'PAPAER BOAT ANAR 180ML', 'productPool/1.jpg', 114 ),
( 'PAPAER BOAT SANTRA 180ML', 'productPool/1.jpg', 28 ),
( 'PAPAYA', 'productPool/1.jpg', 94 ),
( 'PAPAYA GREEN', 'productPool/1.jpg', 227 ),
( 'PAPER BOAT AAMRAS 180ML', 'productPool/1.jpg', 242 ),
( 'PAPER BOAT ALPHONSO AAM 150ML', 'productPool/1.jpg', 221 ),
( 'PAPER BOAT APPLE 180ML', 'productPool/1.jpg', 88 ),
( 'PAPER BOAT CHILLI GUAVA 180ML', 'productPool/1.jpg', 12 ),
( 'PAPER BOAT LYCHEE RAS 180ML', 'productPool/1.jpg', 225 ),
( 'PAPER BOAT MIXED FRUIT 180ML', 'productPool/1.jpg', 235 ),
( 'PAPER BOAT MIXED FRUIT 1L', 'productPool/1.jpg', 125 ),
( 'PAPER BOAT SANTRA 1L', 'productPool/1.jpg', 84 ),
( 'PAPER CUP 150ML', 'productPool/1.jpg', 26 ),
( 'PAPER CUP 250ML PRINT 200PCS', 'productPool/1.jpg', 191 ),
( 'PAPER PLATE 10*12 100P', 'productPool/1.jpg', 135 ),
( 'PAPER PLATE 10*12 50P', 'productPool/1.jpg', 170 ),
( 'PAPER PLATE 9*10 50P', 'productPool/1.jpg', 148 ),
( 'PAPER PLATE F 6', 'productPool/1.jpg', 159 ),
( 'PAPER PLATE F8', 'productPool/1.jpg', 79 ),
( 'PAPER POAT ANAR 1L', 'productPool/1.jpg', 265 ),
( 'PAPER ROLL SP', 'productPool/1.jpg', 236 ),
( 'PAPER ROLL UB', 'productPool/1.jpg', 177 ),
( 'PAPERBOAT AAMRAS 1L', 'productPool/1.jpg', 268 ),
( 'PAPERBOAT BANANA CHIPS 21G', 'productPool/1.jpg', 259 ),
( 'PAPERGEID INTERLEAF BOOK 160PAGES', 'productPool/1.jpg', 174 ),
( 'PAPERGRID 5 SUBJECT SINGLE RULE 300P', 'productPool/1.jpg', 60 ),
( 'PAPERGRID A7 SINGLE RULED RS20/1', 'productPool/1.jpg', 71 ),
( 'PAPERGRID BOOK 4A RULED 071', 'productPool/1.jpg', 2 ),
( 'PAPERGRID BOOK 4A UNRULED 072', 'productPool/1.jpg', 2 ),
( 'PAPERGRID BOOK FOUR LINE 088', 'productPool/1.jpg', 197 ),
( 'PAPERGRID BOOK MATHS 091', 'productPool/1.jpg', 164 ),
( 'PAPERGRID BOOK RULED 943', 'productPool/1.jpg', 58 ),
( 'PAPERGRID BOOK SUB-5', 'productPool/1.jpg', 116 ),
( 'PAPERGRID BOOK TWO LINE 089', 'productPool/1.jpg', 138 ),
( 'PAPERGRID BOOK TWO LINE 953', 'productPool/1.jpg', 262 ),
( 'PAPERGRID BOOK UN RULED 944', 'productPool/1.jpg', 185 ),
( 'PAPERGRID DRAWING NOTEBOOK 40PGS 097', 'productPool/1.jpg', 172 ),
( 'PAPERGRID GRAPH BOOK MRP 20', 'productPool/1.jpg', 133 ),
( 'PAPERGRID NOTEBOOK 160PGS UNRUL 087', 'productPool/1.jpg', 145 ),
( 'PAPERGRID NOTEBOOK DL 72PAGES 082', 'productPool/1.jpg', 247 ),
( 'PAPERGRID NOTEBOOK RUL 160PGS 086', 'productPool/1.jpg', 135 ),
( 'PAPERGRID PRACTICAL BIOLOGY BOOK', 'productPool/1.jpg', 223 ),
( 'PAPERGRID PRACTICAL CHEMISTRY BOOK 963', 'productPool/1.jpg', 11 ),
( 'PAPERGRID PRACTICAL PHYSICS BOOK 961', 'productPool/1.jpg', 54 ),
( 'PAPERGRID PRACTICAL SCIENCE BOOK', 'productPool/1.jpg', 64 ),
( 'PAPERGRID SHORT BOOK 951', 'productPool/1.jpg', 199 ),
( 'PAPERGRID SHORT BOOK FOUR LINE 952', 'productPool/1.jpg', 71 ),
( 'PAPERGRID SHORT BOOK FOURLINE 945', 'productPool/1.jpg', 9 ),
( 'PAPERGRID SHORT BOOK MATHS 954', 'productPool/1.jpg', 40 ),
( 'PAPERGRID SHORT BOOK RULED 950', 'productPool/1.jpg', 134 ),
( 'PAPERGRID SHORT BOOK TWO LINE 946', 'productPool/1.jpg', 197 ),
( 'PAPERGRID SINGLE LINE NOTBOOK 053 MRP 95', 'productPool/1.jpg', 91 ),
( 'PAPERGRID SPIRAL BOOK SUB-1', 'productPool/1.jpg', 115 ),
( 'PAPERGRID SPIRAL BOOK UN RULED', 'productPool/1.jpg', 133 ),
( 'PAPERGRID SPIRAL BOOK UNRULED', 'productPool/1.jpg', 186 ),
( 'PAPERGRID SPRIAL BOOK SUB-5', 'productPool/1.jpg', 140 ),
( 'PAPERGRID UNRULED SPIRAL NOTE BOOK 072', 'productPool/1.jpg', 163 ),
( 'PAPERGRID UNRULED SPIRAL NOTE BOOK 073', 'productPool/1.jpg', 169 ),
( 'PAPERGRID WIRO BOOK RULED', 'productPool/1.jpg', 220 ),
( 'PAPERGRID WIRO BOOK SUB-1', 'productPool/1.jpg', 154 ),
( 'PAPERGRID WIRO SPIRAL BOOK', 'productPool/1.jpg', 153 ),
( 'PAPERGRIDE MATHS SQUARE NOTEBOOK 090', 'productPool/1.jpg', 133 ),
( 'PAPERGRIDSHORT MATHS BOOK 172PGS 955', 'productPool/1.jpg', 75 ),
( 'PAPERLINE A4 SHEET 75GSM', 'productPool/1.jpg', 74 ),
( 'PAPPAD STICK', 'productPool/1.jpg', 124 ),
( 'PAPPADA BOLLY', 'productPool/1.jpg', 67 ),
( 'PAPPAI ALFONSA MANGO 500ML TUB', 'productPool/1.jpg', 141 ),
( 'PAPPAI ALPHONSO MANGO 500ML', 'productPool/1.jpg', 185 ),
( 'pappai black current ppl ice cream', 'productPool/1.jpg', 207 ),
( 'PAPPAI BOURBON VANILA 1L TUB', 'productPool/1.jpg', 70 ),
( 'PAPPAI BOURBON VANILA 500ML TUB', 'productPool/1.jpg', 33 ),
( 'PAPPAI BOURBORN VANILA CUP', 'productPool/1.jpg', 126 ),
( 'PAPPAI BUTTER SCOATCH 500ML TUB', 'productPool/1.jpg', 31 ),
( 'PAPPAI BUTTER SCOTCH I LTR', 'productPool/1.jpg', 152 ),
( 'pappai butterscotch ppl ice cream', 'productPool/1.jpg', 178 ),
( 'PAPPAI CASSATTA PREMIUM IC 100ML', 'productPool/1.jpg', 170 ),
( 'PAPPAI CHOCODEN', 'productPool/1.jpg', 228 ),
( 'PAPPAI CHOCODEN ICE CREAM 50G', 'productPool/1.jpg', 202 ),
( 'pappai chocolate fp ice cream', 'productPool/1.jpg', 154 ),
( 'pappai chocolate ppl ice cream', 'productPool/1.jpg', 169 ),
( 'pappai cornada chocolate', 'productPool/1.jpg', 264 ),
( 'PAPPAI CORNADO BUTTER SCOTCH BAR', 'productPool/1.jpg', 213 ),
( 'PAPPAI ENG ROSE STRAWBERY 1L TUB', 'productPool/1.jpg', 180 ),
( 'pappai english strawberry fp ice cream', 'productPool/1.jpg', 257 ),
( 'PAPPAI GUAVA 1LTR ICECREAM', 'productPool/1.jpg', 267 ),
( 'PAPPAI HOLIDAY CHOCOLATE SIP UP', 'productPool/1.jpg', 53 ),
( 'PAPPAI HOLIDAY PISTA SIPUP', 'productPool/1.jpg', 162 ),
( 'PAPPAI ICE CREAM TENDER COCONUT 1000ML', 'productPool/1.jpg', 196 ),
( 'PAPPAI ICECREAM CUP VANILA', 'productPool/1.jpg', 73 ),
( 'PAPPAI ITALIAN KIWI ICE CREAM 1000ML', 'productPool/1.jpg', 159 ),
( 'PAPPAI JACKFRUIT FP ICECREAM', 'productPool/1.jpg', 68 ),
( 'PAPPAI LOLLIPOP PINEAPPLE 25G', 'productPool/1.jpg', 95 ),
( 'PAPPAI MANGO BAR', 'productPool/1.jpg', 127 ),
( 'pappai mango ppl ice cream', 'productPool/1.jpg', 269 ),
( 'PAPPAI MANGO RIME', 'productPool/1.jpg', 117 ),
( 'PAPPAI MANGO RIME 30G', 'productPool/1.jpg', 106 ),
( 'PAPPAI MILKY DEN BAR', 'productPool/1.jpg', 69 ),
( 'pappai pista green fp ice cream', 'productPool/1.jpg', 26 ),
( 'pappai pista green ppl ice cream', 'productPool/1.jpg', 198 ),
( 'PAPPAI PLEASURE PACKED MANGO 500G', 'productPool/1.jpg', 129 ),
( 'PAPPAI PREMIO PISTA GREEN 1000ML', 'productPool/1.jpg', 27 ),
( 'PAPPAI PREMIO STRAWBERRY 500ML', 'productPool/1.jpg', 271 ),
( 'PAPPAI PREMO VANILLA 1LTR ICECREAM', 'productPool/1.jpg', 264 ),
( 'PAPPAI RICH BUTTER SCOTCH 80G', 'productPool/1.jpg', 123 ),
( 'PAPPAI RICH CORNADO CHOCOLATE', 'productPool/1.jpg', 215 ),
( 'PAPPAI SILK CHOCOLATE 500ML TUB', 'productPool/1.jpg', 32 ),
( 'PAPPAI SILK CHOCOLATE ICE CREAM 1000ML', 'productPool/1.jpg', 72 ),
( 'PAPPAI SPANISH DELIGHT 1000ML', 'productPool/1.jpg', 31 ),
( 'pappai spanish delight ppl ice cream', 'productPool/1.jpg', 225 ),
( 'PAPPAI SPANISHDELIGHT 500G', 'productPool/1.jpg', 95 ),
( 'pappai strawberry ppl ice cream', 'productPool/1.jpg', 238 ),
( 'pappai sundae rich', 'productPool/1.jpg', 131 ),
( 'PAPPAI SUNDE RICH 60G', 'productPool/1.jpg', 105 ),
( 'pappai vanila fp ice cream', 'productPool/1.jpg', 180 ),
( 'pappai vanila ppl ice cream', 'productPool/1.jpg', 115 ),
( 'PAPPAYA ICE CREAM ALPHONSA MANGO 500 ML', 'productPool/1.jpg', 213 ),
( 'PAPPAYA ICE CREAM ENGLISH STRAWBERRY 100 ML', 'productPool/1.jpg', 10 ),
( 'PAPPAYA ICE CREAM ENGLISH STRAWBERRY 500 ML', 'productPool/1.jpg', 151 ),
( 'PAPPAYA ICE CREAM SPANISH DELIGHT 1 LTR', 'productPool/1.jpg', 54 ),
( 'PAPPAYA ICE CREAM TENDER COCONUT', 'productPool/1.jpg', 277 ),
( 'PARACHUTE 1LTR POUCH', 'productPool/1.jpg', 22 ),
( 'PARACHUTE ADVANCED AYURVEDIC HAIR OIL 95ML', 'productPool/1.jpg', 135 ),
( 'PARACHUTE ADVANCED AYURVEDIC HOT OIL 300ML', 'productPool/1.jpg', 207 ),
( 'PARACHUTE ADVANCED AYURVEDIC HOT OIL 90ML', 'productPool/1.jpg', 28 ),
( 'PARACHUTE ADVANCED COCONUT OIL 300ML', 'productPool/1.jpg', 235 ),
( 'PARACHUTE ADVANCED HAIR OIL 175ML', 'productPool/1.jpg', 229 ),
( 'PARACHUTE ADVANCED JASMINE COCONUT HAIR OIL 300 ML', 'productPool/1.jpg', 189 ),
( 'PARACHUTE ADVANCED JASMINE HAIR OIL500ML', 'productPool/1.jpg', 250 ),
( 'PARACHUTE ADVANCED JASMINE OIL 45ML', 'productPool/1.jpg', 182 ),
( 'PARACHUTE ADVANSED HAIR OIL 75 ML', 'productPool/1.jpg', 140 ),
( 'PARACHUTE ADVANSED JASMINE 190ML', 'productPool/1.jpg', 189 ),
( 'PARACHUTE ADVANSED JASMINE 300ML', 'productPool/1.jpg', 272 ),
( 'PARACHUTE ADVASED GOLD 170ML', 'productPool/1.jpg', 218 ),
( 'PARACHUTE ADVASED GOLD 275.ML', 'productPool/1.jpg', 181 ),
( 'PARACHUTE ADVASED JASMINE 500ML', 'productPool/1.jpg', 130 ),
( 'PARACHUTE AFTER SHOWER ANT IDANDRUF 100G', 'productPool/1.jpg', 93 ),
( 'PARACHUTE AFTER SHOWER DANDRUF 50G', 'productPool/1.jpg', 89 ),
( 'PARACHUTE AFTER SHOWER HAIR CREAM 50G', 'productPool/1.jpg', 174 ),
( 'PARACHUTE AFTER SHOWER HAIR CREAM100G', 'productPool/1.jpg', 27 ),
( 'PARACHUTE ALOE VERA HAIR OIL 150ML', 'productPool/1.jpg', 279 ),
( 'PARACHUTE ALOE VERA HAIR OIL 250ML', 'productPool/1.jpg', 24 ),
( 'PARACHUTE ALOE VERA HAIR OIL 75ML', 'productPool/1.jpg', 147 ),
( 'PARACHUTE ANTI HAIRFALL CREAM 50G', 'productPool/1.jpg', 75 ),
( 'PARACHUTE ANTI HAIRFALL WITH ALMOND 100G', 'productPool/1.jpg', 178 ),
( 'PARACHUTE AYURVEDIC HAIR OIL 190ML', 'productPool/1.jpg', 129 ),
( 'PARACHUTE AYURVEDIC HAIR OIL 45ML', 'productPool/1.jpg', 115 ),
( 'PARACHUTE AYURVEDIC HAIR OIL300 ML', 'productPool/1.jpg', 113 ),
( 'PARACHUTE BOTTLE 1 LTR', 'productPool/1.jpg', 158 ),
( 'PARACHUTE COCO SOUL VIRGIN OIL 250ML', 'productPool/1.jpg', 124 ),
( 'PARACHUTE COCO SOUL VIRGIN OIL 500ML', 'productPool/1.jpg', 54 ),
( 'PARACHUTE COCOLIPID BODY LOTION 250ML', 'productPool/1.jpg', 199 ),
( 'PARACHUTE COCONUT 100ML', 'productPool/1.jpg', 29 ),
( 'PARACHUTE COCONUT MILK BODY LOTION 100ML SOFT', 'productPool/1.jpg', 206 ),
( 'PARACHUTE COCONUT OIL 175ML', 'productPool/1.jpg', 175 ),
( 'PARACHUTE COCONUT OIL 1LTR BOTTLE', 'productPool/1.jpg', 24 ),
( 'PARACHUTE COCONUT OIL 25ML', 'productPool/1.jpg', 246 ),
( 'PARACHUTE COCONUT OIL 500ML', 'productPool/1.jpg', 202 ),
( 'PARACHUTE COCONUT OIL 50ML', 'productPool/1.jpg', 267 ),
( 'PARACHUTE COCONUT OIL250ML', 'productPool/1.jpg', 262 ),
( 'PARACHUTE COCONUT OIL500ML', 'productPool/1.jpg', 244 ),
( 'PARACHUTE COCOUNT BUTTER BODY LOTION 100ML', 'productPool/1.jpg', 271 ),
( 'PARACHUTE DEEP NOURISH BODY LOTION 100 ML', 'productPool/1.jpg', 253 ),
( 'PARACHUTE DEEP NOURISH BODY LOTION 250ML', 'productPool/1.jpg', 133 ),
( 'PARACHUTE GOLD COCONUT HAIR OIL 450ML', 'productPool/1.jpg', 40 ),
( 'PARACHUTE GOLD COCONUT HAIR OIL 90ML', 'productPool/1.jpg', 152 ),
( 'PARACHUTE GOLD IMP', 'productPool/1.jpg', 57 ),
( 'PARACHUTE HOT OIL 190 ML', 'productPool/1.jpg', 214 ),
( 'PARACHUTE JASMINE HAIR OIL 200ML', 'productPool/1.jpg', 39 ),
( 'PARACHUTE JASMINE HAIR OIL 45 ML', 'productPool/1.jpg', 42 ),
( 'PARACHUTE JASMINE HAIR OIL 90ML', 'productPool/1.jpg', 116 ),
( 'PARACHUTE JASMINE OIL 90ML', 'productPool/1.jpg', 237 ),
( 'PARASOL PLATE 6 INCH 100P', 'productPool/1.jpg', 182 ),
( 'PARIE- G GOLD', 'productPool/1.jpg', 275 ),
( 'PARIPPUVADA KUTTANADAN 90 GM', 'productPool/1.jpg', 75 ),
( 'PARK AVE BOUNCE 135ML', 'productPool/1.jpg', 4 ),
( 'PARK AVENUE ALEXANDER BODY FRAGRANCE 150ML', 'productPool/1.jpg', 42 ),
( 'PARK AVENUE ALTEREGO DEO 100G', 'productPool/1.jpg', 226 ),
( 'PARK AVENUE BEER NORMAL SHAMPOO 200ML', 'productPool/1.jpg', 79 ),
( 'PARK AVENUE BEER OIL SHAMPOO 200ML', 'productPool/1.jpg', 220 ),
( 'PARK AVENUE BEER SHAMPOO 180ML', 'productPool/1.jpg', 274 ),
( 'PARK AVENUE CLASSIC SHAVING CREAM 84G', 'productPool/1.jpg', 170 ),
( 'PARK AVENUE CONQUER 50ML', 'productPool/1.jpg', 177 ),
( 'PARK AVENUE COOL BLUE 150ML', 'productPool/1.jpg', 214 ),
( 'PARK AVENUE COOL BLUE SHAVING CREAM 70G', 'productPool/1.jpg', 52 ),
( 'PARK AVENUE COOL BLUE SOAP', 'productPool/1.jpg', 233 ),
( 'PARK AVENUE COOL BLUE SOAP 75G', 'productPool/1.jpg', 237 ),
( 'PARK AVENUE DEO SPARY TRANCE 135ML', 'productPool/1.jpg', 129 ),
( 'PARK AVENUE DEO SPARY ZOUK 135ML', 'productPool/1.jpg', 82 ),
( 'PARK AVENUE DEO TALC STORM 100G', 'productPool/1.jpg', 3 ),
( 'PARK AVENUE ECLECTIC SPRAY 130ML', 'productPool/1.jpg', 215 ),
( 'PARK AVENUE ELEVATE 25G', 'productPool/1.jpg', 13 ),
( 'PARK AVENUE ELEVATE 50G', 'productPool/1.jpg', 25 ),
( 'PARK AVENUE EPIC BODY FRAGRANCE 150ML', 'productPool/1.jpg', 250 ),
( 'PARK AVENUE ESSENTIAL GROOMING KIT', 'productPool/1.jpg', 124 ),
( 'PARK AVENUE EUPHORIA PARFUM 50ML', 'productPool/1.jpg', 16 ),
( 'PARK AVENUE EXPLORE DEO SPARY 100G', 'productPool/1.jpg', 130 ),
( 'PARK AVENUE FIESTA DEO 135ML', 'productPool/1.jpg', 223 ),
( 'PARK AVENUE GOOD MONI 50ML', 'productPool/1.jpg', 272 ),
( 'PARK AVENUE GOOD MORNING 100G', 'productPool/1.jpg', 269 ),
( 'PARK AVENUE GOOD MORNING DEO 150ML', 'productPool/1.jpg', 149 ),
( 'PARK AVENUE GOOD MORNING DEO TALC 100G', 'productPool/1.jpg', 168 ),
( 'PARK AVENUE GOOD MORNING DEO TALC 200G', 'productPool/1.jpg', 182 ),
( 'PARK AVENUE GOOD MORNING ELECTRIC DEO 135ML', 'productPool/1.jpg', 64 ),
( 'PARK AVENUE GOOD MORNING INTENSE DEO 150ML', 'productPool/1.jpg', 192 ),
( 'PARK AVENUE GOOD MORNING SHAVE LOTION 100ML', 'productPool/1.jpg', 163 ),
( 'PARK AVENUE GOOD MORNING SOAP 125G', 'productPool/1.jpg', 45 ),
( 'PARK AVENUE GOOD MORNING ULTIMATE DEO 150ML', 'productPool/1.jpg', 254 ),
( 'PARK AVENUE HARMONY PARFUM 50ML', 'productPool/1.jpg', 96 ),
( 'PARK AVENUE HERO 130ML', 'productPool/1.jpg', 75 ),
( 'PARK AVENUE HORIZON DEO 150ML', 'productPool/1.jpg', 181 ),
( 'PARK AVENUE ICON DEO 120ML', 'productPool/1.jpg', 46 ),
( 'PARK AVENUE LUXURY SOAP 125G', 'productPool/1.jpg', 238 ),
( 'PARK AVENUE MAGNIFICO 120ML', 'productPool/1.jpg', 15 ),
( 'PARK AVENUE MARCUS BODY FRAGRANCE 150ML', 'productPool/1.jpg', 193 ),
( 'PARK AVENUE NEO SPRAY 130ML', 'productPool/1.jpg', 212 ),
( 'PARK AVENUE PARK AVENUE FACE WASH 50ML', 'productPool/1.jpg', 253 ),
( 'PARK AVENUE PERFUME GRAVITAS 150ML', 'productPool/1.jpg', 186 ),
( 'PARK AVENUE PERFUME MAESTRO 150ML', 'productPool/1.jpg', 24 ),
( 'PARK AVENUE PREMIUM DE COLOGNE 200ML', 'productPool/1.jpg', 60 ),
( 'PARK AVENUE PREMIUM EAU DE COLOGNE 100ML', 'productPool/1.jpg', 85 ),
( 'PARK AVENUE PREMIUM EAUDE COLOUR 50ML', 'productPool/1.jpg', 189 ),
( 'PARK AVENUE PREMIUM HAND WASH LIME 250ML', 'productPool/1.jpg', 32 ),
( 'PARK AVENUE PREMIUM HAND WASH ROSE 250ML', 'productPool/1.jpg', 275 ),
( 'PARK AVENUE REGAL DEO 120ML', 'productPool/1.jpg', 114 ),
( 'PARK AVENUE REGEN FOAM 300G', 'productPool/1.jpg', 156 ),
( 'PARK AVENUE SHAVING CREAM CLASSIC 30G', 'productPool/1.jpg', 186 ),
( 'PARK AVENUE SHAVING CREAM COOL BLUE 30G', 'productPool/1.jpg', 213 ),
( 'PARK AVENUE SHAVING CREAM GOOD MORNING 30G', 'productPool/1.jpg', 160 ),
( 'PARK AVENUE SHAVING CREAM GOOD MORNING 70G', 'productPool/1.jpg', 84 ),
( 'PARK AVENUE SHAVING CREAM GOOD MORNING 84G', 'productPool/1.jpg', 213 ),
( 'PARK AVENUE SHAVING CREAM LEMON 30G', 'productPool/1.jpg', 181 ),
( 'PARK AVENUE SLIVER SHAVING BRUSH', 'productPool/1.jpg', 91 ),
( 'PARK AVENUE SOFT HOLD 100G', 'productPool/1.jpg', 197 ),
( 'PARK AVENUE STORM 100G', 'productPool/1.jpg', 187 ),
( 'PARK AVENUE STORM SOAP 125GM', 'productPool/1.jpg', 97 ),
( 'PARK AVENUE STORM SPRY 150ML', 'productPool/1.jpg', 115 ),
( 'PARK AVENUE TRANQUIL 150ML', 'productPool/1.jpg', 31 ),
( 'PARK AVENUE VOYAGE DEO 100G', 'productPool/1.jpg', 25 ),
( 'PARK AVENUE WET LOOK 100G', 'productPool/1.jpg', 149 ),
( 'PARK NVENUE ALTER EGO BODY SPRAY150ML', 'productPool/1.jpg', 174 ),
( 'PARK NVENUE BEER SHAMPOO 70ML', 'productPool/1.jpg', 275 ),
( 'PARK NVENUE HERCULES 120ML', 'productPool/1.jpg', 223 ),
( 'PARK NVENUE NEO BODY SPRAY 116G', 'productPool/1.jpg', 92 ),
( 'PARK NVENUE VOYAGE 120ML', 'productPool/1.jpg', 61 ),
( 'PARK NVENUE VOYAGE BODY SPRAY 150ML', 'productPool/1.jpg', 47 ),
( 'PARK RUGGED HOLD 100G', 'productPool/1.jpg', 103 ),
( 'PARK SHAVING BRUSH 1NOS', 'productPool/1.jpg', 236 ),
( 'PARK VENUE BEER SHAMPOO 70ML', 'productPool/1.jpg', 209 ),
( 'PARK VENUE OPTIMUS 120ML', 'productPool/1.jpg', 278 ),
( 'PARK VENUE STORMFRAGRANCEDEO TALC 200G', 'productPool/1.jpg', 21 ),
( 'PARKAVANU COOL BLUESKIE 250M', 'productPool/1.jpg', 135 ),
( 'PARKER BETA PERMIUM GOLD PEN', 'productPool/1.jpg', 270 ),
( 'PARKER BETA PREMIUM GOLD PEN', 'productPool/1.jpg', 62 ),
( 'PARKER BETA PREMIUM SILVER FOUNTAIN PEN', 'productPool/1.jpg', 50 ),
( 'PARKER BETA PREMIUM SILVER PEN', 'productPool/1.jpg', 95 ),
( 'PARKER BETA SPECIAL EDITION BALL PEN', 'productPool/1.jpg', 197 ),
( 'PARKER BETA STANDARD BALL PEN', 'productPool/1.jpg', 70 ),
( 'PARKER BETA STANDARD FOUNTAIN PEN', 'productPool/1.jpg', 31 ),
( 'PARKER BETA STANDARD ROLLER BALL PEN', 'productPool/1.jpg', 181 ),
( 'PARKER FASHION VR PEN', 'productPool/1.jpg', 206 ),
( 'PARKER JOTTER BALL PEN', 'productPool/1.jpg', 57 ),
( 'PARKER JOTTER LONDEN PEN', 'productPool/1.jpg', 157 ),
( 'PARKER JOTTER LONDEN STEEL PEN', 'productPool/1.jpg', 178 ),
( 'PARKER JOTTER STANDARD BALL PEN', 'productPool/1.jpg', 12 ),
( 'PARKER JOTTER STANDARD PEN', 'productPool/1.jpg', 15 ),
( 'PARKER METALLIX QUINK FREE', 'productPool/1.jpg', 31 ),
( 'PARKER MIX AND MATCH BETA BALL PEN', 'productPool/1.jpg', 202 ),
( 'PARKER VECTOR STANDARD ROLLER BALL PEN', 'productPool/1.jpg', 134 ),
( 'PARLA KRACK JACK 75G', 'productPool/1.jpg', 148 ),
( 'PARLE 2 IN 1 ECLAIRS 277G', 'productPool/1.jpg', 271 ),
( 'PARLE 20 20 NICE BISCUITS 150G', 'productPool/1.jpg', 114 ),
( 'PARLE 20 20 NICE BISCUITS 75G', 'productPool/1.jpg', 115 ),
( 'PARLE 20-20 BUTTER COOKIES 200g', 'productPool/1.jpg', 214 ),
( 'PARLE 20-20 BUTTER COOKIES 80G', 'productPool/1.jpg', 233 ),
( 'PARLE 20-20 BUTTER COOKIES 90G MRP10', 'productPool/1.jpg', 209 ),
( 'PARLE 20-20 BUTTER COOKIES 96G', 'productPool/1.jpg', 92 ),
( 'PARLE 20-20 BUTTER JEERA COOKIES 200G', 'productPool/1.jpg', 94 ),
( 'PARLE 20-20 CASHEW COOKIES 150G', 'productPool/1.jpg', 256 ),
( 'PARLE 20-20 CASHEW COOKIES 200G', 'productPool/1.jpg', 219 ),
( 'PARLE 20-20 CASHEW COOKIES 70G', 'productPool/1.jpg', 221 ),
( 'PARLE 20-20 CASHEW COOKIES 84G', 'productPool/1.jpg', 266 ),
( 'PARLE 20-20 GOLD CASHEW COOKIES 200G', 'productPool/1.jpg', 65 ),
( 'PARLE 20-20 NICE BISCUIT 150G', 'productPool/1.jpg', 85 ),
( 'PARLE 20/20 BUTTER COOKIES 200G', 'productPool/1.jpg', 110 ),
( 'PARLE 20/20 CASHEW BUTTER 90G', 'productPool/1.jpg', 206 ),
( 'PARLE AGRO FROOTI 300ML', 'productPool/1.jpg', 166 ),
( 'PARLE APPY 160ML EDGE', 'productPool/1.jpg', 38 ),
( 'PARLE APPY 250ML EDGE PACK', 'productPool/1.jpg', 166 ),
( 'PARLE APPY FIZZ 250ML BOTTLE', 'productPool/1.jpg', 9 ),
( 'PARLE APPY FIZZ 500ML', 'productPool/1.jpg', 90 ),
( 'PARLE APPY FIZZ APPLE DRINK 250ML', 'productPool/1.jpg', 86 ),
( 'PARLE AROVITA THIN ARROWROOT 150G', 'productPool/1.jpg', 98 ),
( 'PARLE AROVITA THIN ARROWROOT 300g', 'productPool/1.jpg', 207 ),
( 'PARLE BAKE SMITH MARIE 250G', 'productPool/1.jpg', 79 ),
( 'PARLE BAKE SMITH MULTIVTA MARIE 150G', 'productPool/1.jpg', 210 ),
( 'PARLE BAKESMITH 250G', 'productPool/1.jpg', 7 ),
( 'PARLE BAKESMITH AROVITA ARROWROOT 300G', 'productPool/1.jpg', 143 ),
( 'PARLE BAKESMITH AROVITA THIN ARROWROOT 150G', 'productPool/1.jpg', 87 ),
( 'PARLE BAKESMITH MARIE 90G', 'productPool/1.jpg', 229 ),
( 'PARLE BAKESMITH MULTIVITA 300G', 'productPool/1.jpg', 217 ),
( 'PARLE BLACK BOURBON CHOCO 100G', 'productPool/1.jpg', 199 ),
( 'PARLE BLACK BOURBON COMBO 300G', 'productPool/1.jpg', 96 ),
( 'PARLE BLACK BOURBON VANILA 100G', 'productPool/1.jpg', 142 ),
( 'PARLE COCONUT COOKIES 100G', 'productPool/1.jpg', 207 ),
( 'PARLE COCONUT COOKIES 200GM', 'productPool/1.jpg', 6 ),
( 'PARLE COCONUT CRUNCHY BISCUIT 108G', 'productPool/1.jpg', 160 ),
( 'PARLE FAB BOURBON 150G', 'productPool/1.jpg', 209 ),
( 'PARLE FAB BOURBON 75G', 'productPool/1.jpg', 15 ),
( 'PARLE FAB BOURBON CHOCOLATE SANDWICH 150G', 'productPool/1.jpg', 169 ),
( 'PARLE FAB CHOCOLATE 100GM', 'productPool/1.jpg', 172 ),
( 'PARLE FAB JAM IN CREAM 150G', 'productPool/1.jpg', 78 ),
( 'PARLE FAB JAM-IM 150G', 'productPool/1.jpg', 230 ),
( 'PARLE FAB JAM-IN 150G', 'productPool/1.jpg', 187 ),
( 'PARLE FAB MILK SHAKTHI 300G', 'productPool/1.jpg', 224 ),
( 'PARLE FAB MILKY SANDWICH 60G', 'productPool/1.jpg', 169 ),
( 'PARLE FAB STRAWBERRY 100GM', 'productPool/1.jpg', 138 ),
( 'PARLE FAB VANILA 100G', 'productPool/1.jpg', 15 ),
( 'PARLE FROOTI 500ML', 'productPool/1.jpg', 242 ),
( 'PARLE FROOTI 600ML', 'productPool/1.jpg', 83 ),
( 'PARLE FROOTI MANGO 160ML', 'productPool/1.jpg', 34 ),
( 'PARLE FROOTI MANGO PUL 250ML', 'productPool/1.jpg', 197 ),
( 'PARLE G MILK SHAKTI 92G', 'productPool/1.jpg', 213 ),
( 'PARLE G800G', 'productPool/1.jpg', 199 ),
( 'PARLE GOLD 1KG', 'productPool/1.jpg', 207 ),
( 'PARLE GOLD 250 G', 'productPool/1.jpg', 90 ),
( 'PARLE HAPPY HAPPY CAKES CHOCOLATE 140G', 'productPool/1.jpg', 19 ),
( 'PARLE HAPPY HAPPY CAKES CHOCOLATE 60G', 'productPool/1.jpg', 88 ),
( 'PARLE HAPPY HAPPY CAKES TUTTI FRUITY 140G', 'productPool/1.jpg', 34 ),
( 'PARLE HAPPY HAPPY CAKES TUTTI FRUITY 40G', 'productPool/1.jpg', 278 ),
( 'PARLE HAPPY HAPPY CAKES VANILLA 140G', 'productPool/1.jpg', 215 ),
( 'PARLE HAPPY HAPPY CAKES VEG 65G', 'productPool/1.jpg', 174 ),
( 'PARLE HAPPY HAPPY CHOCO CHIP COOKIES 75G', 'productPool/1.jpg', 169 ),
( 'PARLE HAPPY HAPPY COOKIES 200G', 'productPool/1.jpg', 12 ),
( 'PARLE HAPPY HAPPY JAM-IN BISCUITS 150G', 'productPool/1.jpg', 213 ),
( 'PARLE HIDE & SEEK 400G COMBO', 'productPool/1.jpg', 108 ),
( 'PARLE HIDE & SEEK CHOCOCHIP 100G', 'productPool/1.jpg', 222 ),
( 'PARLE HIDE & SEEK FAB ORANGE 100GM', 'productPool/1.jpg', 56 ),
( 'PARLE HIDE & SEEK ORANGE 100G', 'productPool/1.jpg', 40 ),
( 'PARLE HIDE & SEEK STRAWBERY 100G', 'productPool/1.jpg', 81 ),
( 'PARLE HIDE &SEEK CHOCO COOKIES 350G', 'productPool/1.jpg', 91 ),
( 'PARLE HIDE &SEEK CHOCO VANILLA 120G', 'productPool/1.jpg', 264 ),
( 'PARLE HIDE AND SEEK AMERICAN STYLE 200G', 'productPool/1.jpg', 247 ),
( 'PARLE HIDE AND SEEK AMERICAN STYLE CASHEW 200G', 'productPool/1.jpg', 28 ),
( 'PARLE HIDE AND SEEK COFFEE 200G', 'productPool/1.jpg', 111 ),
( 'PARLE HIDE AND SEEK COOKIES 1KG', 'productPool/1.jpg', 115 ),
( 'PARLE HIDE AND SEEK VANILLA CREAM SANDWICH 100G', 'productPool/1.jpg', 82 ),
( 'PARLE HIDE&SEEK 120G', 'productPool/1.jpg', 185 ),
( 'PARLE HIDE&SEEK CHOCLATE 200G', 'productPool/1.jpg', 56 ),
( 'PARLE KACCHA MANGO BITE 316G', 'productPool/1.jpg', 2 ),
( 'PARLE KRACK JACK 200G', 'productPool/1.jpg', 192 ),
( 'PARLE KRACK JACK 400G', 'productPool/1.jpg', 38 ),
( 'PARLE KRACK JACK 75.6G', 'productPool/1.jpg', 99 ),
( 'PARLE KRACK JACK BUTTER MASALA 120G', 'productPool/1.jpg', 249 ),
( 'PARLE LONDON DIARY 296G', 'productPool/1.jpg', 191 ),
( 'PARLE LONDONDERRY 396G', 'productPool/1.jpg', 65 ),
( 'PARLE MAGI X KREAMS CHOCOLAT', 'productPool/1.jpg', 43 ),
( 'PARLE MAGIX CREAM ELACHI 100G', 'productPool/1.jpg', 66 ),
( 'PARLE MANGO BITE 320G', 'productPool/1.jpg', 113 );