INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'GAIA CRUNCHY MUESLI FRUIT&NUT 400GM', 'productPool/1.jpg', 64 ),
( 'GAIA CRUNCHY MUESLI MIXED FRUIT 1KG', 'productPool/1.jpg', 247 ),
( 'GAIA CRUNCHY MUESLI NUTTY DELIGHT 1KG', 'productPool/1.jpg', 210 ),
( 'GAIA CRUNCHY MUESLI REAL FRUIT 1KG', 'productPool/1.jpg', 207 ),
( 'GAIA CRUNCHY MUESLI REAL FRUIT 400GM', 'productPool/1.jpg', 194 ),
( 'GAIA CRUNCHY MUSELL STRAWBERRY 400GM', 'productPool/1.jpg', 58 ),
( 'GAIA DIGESTIVE COOKIES 200G', 'productPool/1.jpg', 182 ),
( 'GAIA EXTRA LIGHT OLIVE OIL 1 LTR', 'productPool/1.jpg', 107 ),
( 'GAIA EXTRA LIGHT OLIVE OIL 500ML', 'productPool/1.jpg', 39 ),
( 'GAIA EXTRA VIRGIN OLIVE OIL 250ML', 'productPool/1.jpg', 77 ),
( 'GAIA GREEN TEA + ELAICHI', 'productPool/1.jpg', 40 ),
( 'GAIA GREEN TEA + TULSI', 'productPool/1.jpg', 72 ),
( 'GAIA GREEN TEA GIN 25BAG', 'productPool/1.jpg', 244 ),
( 'GAIA GREEN TEA HONEY& LIME 25BAG', 'productPool/1.jpg', 196 ),
( 'GAIA LEAF GREEN TEA LEMON 100G', 'productPool/1.jpg', 59 ),
( 'GAIA LEAF GREEN TEA TUISI 100G', 'productPool/1.jpg', 30 ),
( 'GAIA LITE SUGFRE BITE 200GM', 'productPool/1.jpg', 65 ),
( 'GAIA MUITI GRAIN COOKI 200G', 'productPool/1.jpg', 176 ),
( 'GAIA MULTIGRAIN OATS 500G', 'productPool/1.jpg', 130 ),
( 'GAIA NUTTY DELIGHT 400G', 'productPool/1.jpg', 179 ),
( 'GAIA OAT COOKIES 200G', 'productPool/1.jpg', 263 ),
( 'GAIA OATS ORIGINAL 500G', 'productPool/1.jpg', 88 ),
( 'GAIA SPORT GRANOLA BAR', 'productPool/1.jpg', 12 ),
( 'GAIA SPORT GRANOLA BAR ALMOND &RASIN30G', 'productPool/1.jpg', 70 ),
( 'GAIA TRAIL MIX 100G', 'productPool/1.jpg', 168 ),
( 'GAJA GREEN TEA MINT 25 TEA BAG', 'productPool/1.jpg', 41 ),
( 'GALA 2IN 1DOUBLE HOCKEY', 'productPool/1.jpg', 278 ),
( 'GALA ADVANCED FLOOR CLOTH', 'productPool/1.jpg', 130 ),
( 'GALA ANGLE WIPER', 'productPool/1.jpg', 20 ),
( 'GALA APPLE', 'productPool/1.jpg', 42 ),
( 'GALA APPLE(U.S.A)', 'productPool/1.jpg', 224 ),
( 'GALA BRUSHLITE HARDY BRUSH', 'productPool/1.jpg', 69 ),
( 'GALA BRUSHTILE HARD MRP 99', 'productPool/1.jpg', 98 ),
( 'GALA CHANDRA IRON SCRUBBING BRUSH', 'productPool/1.jpg', 64 ),
( 'GALA CHANDRA KITCHEN MOPPY RS 75', 'productPool/1.jpg', 14 ),
( 'GALA CHANDRA PATLA RS75', 'productPool/1.jpg', 169 ),
( 'GALA CHANDRA PLASTIC BROOM KHARATA 79', 'productPool/1.jpg', 3 ),
( 'GALA CLIP N FIT MOP', 'productPool/1.jpg', 117 ),
( 'GALA CLIP N FIT REFILL MRP 179', 'productPool/1.jpg', 229 ),
( 'GALA CLOTH BRUSH CLOTHEY', 'productPool/1.jpg', 178 ),
( 'GALA CLOTH BRUSH GOLD', 'productPool/1.jpg', 131 ),
( 'GALA COMMANDO SCRUBPAD 10CM', 'productPool/1.jpg', 189 ),
( 'GALA DECK MOP MRP 160', 'productPool/1.jpg', 262 ),
( 'GALA DIGESTIVE COOKIES 100G', 'productPool/1.jpg', 53 ),
( 'GALA DOUBLE HOCKEY CLEANER', 'productPool/1.jpg', 65 ),
( 'GALA DOUBLE LIP BATHROOM WIPER', 'productPool/1.jpg', 32 ),
( 'GALA DUAL FLOOR CLOTH POCHHA', 'productPool/1.jpg', 146 ),
( 'GALA DUST CONTROL MOP', 'productPool/1.jpg', 45 ),
( 'GALA DUST CONTROL MOP 18 REFIL', 'productPool/1.jpg', 222 ),
( 'GALA DUST GO SET DUST PAN', 'productPool/1.jpg', 71 ),
( 'GALA DUSTPAN MRP 60', 'productPool/1.jpg', 46 ),
( 'GALA EZEE SQUEEZEE TABLE WIPER', 'productPool/1.jpg', 51 ),
( 'GALA FLOOR BRUSH IRON BULL', 'productPool/1.jpg', 196 ),
( 'GALA FLOOR WIPER', 'productPool/1.jpg', 40 ),
( 'GALA FLOOR WIPER LEADER', 'productPool/1.jpg', 147 ),
( 'GALA FRIDGE JAR CLEANER', 'productPool/1.jpg', 277 ),
( 'GALA GARBAGE BAG THICK', 'productPool/1.jpg', 168 ),
( 'GALA KING KONG BROOM', 'productPool/1.jpg', 67 ),
( 'GALA KITCHEN SCRUBBER GREEN 2N', 'productPool/1.jpg', 109 ),
( 'GALA LAXMI BROOM', 'productPool/1.jpg', 251 ),
( 'GALA LITE SUGAR FREE COOKIES 100G', 'productPool/1.jpg', 111 ),
( 'GALA LONG HANDLE FLOOR SCRUBBER', 'productPool/1.jpg', 39 ),
( 'GALA LOOPED COTTON MOP', 'productPool/1.jpg', 156 ),
( 'GALA MICROFIBER DUSTER', 'productPool/1.jpg', 218 ),
( 'GALA MICROFIBER TWIST MOP', 'productPool/1.jpg', 71 ),
( 'GALA MOPKING COTTON', 'productPool/1.jpg', 127 ),
( 'GALA MR.TALL BRUSH', 'productPool/1.jpg', 156 ),
( 'GALA MULTI GRAIN COOKIES TIGR100G', 'productPool/1.jpg', 65 ),
( 'GALA NO DUST BROOM REGULAER RS180', 'productPool/1.jpg', 277 ),
( 'GALA NO DUST BROOM XL', 'productPool/1.jpg', 23 ),
( 'GALA OATMEAL COOKIES 100G', 'productPool/1.jpg', 229 ),
( 'GALA PLASTIC BROOM 150', 'productPool/1.jpg', 259 ),
( 'GALA POWER MOP MRP 999', 'productPool/1.jpg', 210 ),
( 'GALA PVA MOP', 'productPool/1.jpg', 254 ),
( 'GALA SCRUB PAD BIG', 'productPool/1.jpg', 122 ),
( 'GALA SCRUB PAD CLEANERR RS42', 'productPool/1.jpg', 264 ),
( 'GALA SHERGRIP SINK BRUSH', 'productPool/1.jpg', 207 ),
( 'GALA SPIN MOP PREMIUM', 'productPool/1.jpg', 64 ),
( 'GALA SPIN MOP SMARTY', 'productPool/1.jpg', 85 ),
( 'GALA SPONGE SCRUB CLEANER 1PIECE', 'productPool/1.jpg', 262 ),
( 'GALA SPONGE WIPE MRP 41', 'productPool/1.jpg', 51 ),
( 'GALA SPONGE WIPES 3PCS', 'productPool/1.jpg', 146 ),
( 'GALA SPONGE WIPES 5PCS', 'productPool/1.jpg', 238 ),
( 'GALA STEEL SCRUB PAD MRP 30', 'productPool/1.jpg', 207 ),
( 'GALA SUPER HOCKEY MRP 65', 'productPool/1.jpg', 30 ),
( 'GALA SUPER SCRUB', 'productPool/1.jpg', 91 ),
( 'GALA SUPER SCRUB SOFT MRP35', 'productPool/1.jpg', 256 ),
( 'GALA SURUBBER GREEN 1PIECE', 'productPool/1.jpg', 237 ),
( 'GALA TMOP RS 199', 'productPool/1.jpg', 203 ),
( 'GALA TOILEAN BRUSH MRP109', 'productPool/1.jpg', 140 ),
( 'GALA TOILEAN STANDEE 169', 'productPool/1.jpg', 187 ),
( 'GALA TOILEX BRUSH LASTS LONGER', 'productPool/1.jpg', 253 ),
( 'GALA TOILEX ROUNDY', 'productPool/1.jpg', 149 ),
( 'GALA TOILEX SQUARE', 'productPool/1.jpg', 55 ),
( 'GALA TROPHY BRUSH', 'productPool/1.jpg', 219 ),
( 'GALA V BROOM CEILING BROOM', 'productPool/1.jpg', 105 ),
( 'GALA WINDOW WASHER 110', 'productPool/1.jpg', 237 ),
( 'GALAXY CRISPY 36G', 'productPool/1.jpg', 278 ),
( 'GALAXY DOUBLE HOCKEY BRUSH', 'productPool/1.jpg', 101 ),
( 'GALAXY FRUIT & NUT 36G', 'productPool/1.jpg', 126 ),
( 'GALAXY FRUIT & NUT 40G', 'productPool/1.jpg', 192 ),
( 'GALAXY JEWELS 383G', 'productPool/1.jpg', 170 ),
( 'GALAXY JEWELS GIFT PACK 200G', 'productPool/1.jpg', 252 ),
( 'GALAXY MILK CHOCOLATE 40G', 'productPool/1.jpg', 94 ),
( 'GALAXY SMOOTH MILK 30G', 'productPool/1.jpg', 44 ),
( 'GALAXY SMOOTH MILK 40G', 'productPool/1.jpg', 71 ),
( 'GALAXY SMOOTH MILK 56G', 'productPool/1.jpg', 69 ),
( 'GALAXY SMOOTHMILK 19.1G', 'productPool/1.jpg', 54 ),
( 'GANG OF 5 BADAM STICKS 100G', 'productPool/1.jpg', 64 ),
( 'GANG OF 5 CHOCO STCICKS 100G', 'productPool/1.jpg', 1 ),
( 'GANG OF 5 COFFEE STCICKS 100G', 'productPool/1.jpg', 22 ),
( 'GARAM MASALA 100G', 'productPool/1.jpg', 217 ),
( 'GARBAGE BAG SMALL ME05', 'productPool/1.jpg', 176 ),
( 'GARLIC', 'productPool/1.jpg', 15 ),
( 'GARLIC CHILLY POWDER100G', 'productPool/1.jpg', 196 ),
( 'GARLIC ORDINARY', 'productPool/1.jpg', 82 ),
( 'GARLIC SAGO APPALAM 200G', 'productPool/1.jpg', 82 ),
( 'GARNIER 5 HERBS CONDITIONER 175ML', 'productPool/1.jpg', 268 ),
( 'GARNIER 5 HERBS SHAMPOO 175ML', 'productPool/1.jpg', 106 ),
( 'GARNIER B B CREAM 9G', 'productPool/1.jpg', 20 ),
( 'GARNIER B.B CREAM 18G', 'productPool/1.jpg', 183 ),
( 'GARNIER BALACK NATURALS BROWN20G', 'productPool/1.jpg', 118 ),
( 'GARNIER BLACK NATURAL BROWN 4.0 20ML', 'productPool/1.jpg', 187 ),
( 'GARNIER BLACK NATURALS 1.0 DEEP BLACK', 'productPool/1.jpg', 263 ),
( 'GARNIER BLACK NATURALS 2.0 ORGINAL BLACK', 'productPool/1.jpg', 259 ),
( 'GARNIER BLACK NATURALS 3.16 BURGUNDY', 'productPool/1.jpg', 52 ),
( 'GARNIER BLACKBERRY CONDITIONER 175ML', 'productPool/1.jpg', 222 ),
( 'GARNIER BLACKBERRY CONDITIONER 75ML', 'productPool/1.jpg', 251 ),
( 'GARNIER BLACKBERRY SHAMPOO 175ML', 'productPool/1.jpg', 43 ),
( 'GARNIER BN BROWN BLACK 3.0', 'productPool/1.jpg', 33 ),
( 'GARNIER BN DEEP BLACK 1.0', 'productPool/1.jpg', 23 ),
( 'GARNIER BN NATURAL BURGUNDY 3.16', 'productPool/1.jpg', 72 ),
( 'GARNIER BN ORIGINAL BLACK 2.0', 'productPool/1.jpg', 15 ),
( 'GARNIER CN INTENCE RED 6.6', 'productPool/1.jpg', 112 ),
( 'GARNIER CN LIGHT BROWN 5', 'productPool/1.jpg', 199 ),
( 'GARNIER CN WINE BURGUNDY 4.20', 'productPool/1.jpg', 86 ),
( 'GARNIER COLOR BLACK NO.1', 'productPool/1.jpg', 233 ),
( 'GARNIER COLOR BLACK SHADE 1', 'productPool/1.jpg', 189 ),
( 'GARNIER COLOR NATURAL BROWN 4', 'productPool/1.jpg', 178 ),
( 'GARNIER COLOR NATURAL BURGUNDY 24ML', 'productPool/1.jpg', 85 ),
( 'GARNIER COLOR NATURAL DARKEST BROWN NO.3', 'productPool/1.jpg', 97 ),
( 'GARNIER COLOR NATURALS CARAMEL BROWN 5.32', 'productPool/1.jpg', 89 ),
( 'GARNIER COLOR NATURALS DARKEST BROWN NO.3', 'productPool/1.jpg', 232 ),
( 'GARNIER COLOR NATURALS MEN BURGUNDY NO.3.16', 'productPool/1.jpg', 173 ),
( 'GARNIER COLOR NATURALS MEN DARK BROWN NO.3', 'productPool/1.jpg', 196 ),
( 'GARNIER COLOR NATURALSCARAMEL BROWN 5.32', 'productPool/1.jpg', 40 ),
( 'GARNIER COLOUR BROWN BLACK 3.0', 'productPool/1.jpg', 48 ),
( 'GARNIER COLOUR MEN BLACK 1', 'productPool/1.jpg', 60 ),
( 'GARNIER COLOUR NATURA LBROWN4 70ML+60G', 'productPool/1.jpg', 84 ),
( 'GARNIER GENTLE FACE WASH 100G', 'productPool/1.jpg', 198 ),
( 'GARNIER GENTLE SOOTHING FACEWASH 50G', 'productPool/1.jpg', 46 ),
( 'GARNIER HERBS CONDITIONER HERBS 75ML', 'productPool/1.jpg', 58 ),
( 'GARNIER LIGHT COMPLETE 18.G', 'productPool/1.jpg', 194 ),
( 'GARNIER LIGHT COMPLETE 18GM', 'productPool/1.jpg', 71 ),
( 'GARNIER LIGHT COMPLETE CREAM 23G', 'productPool/1.jpg', 172 ),
( 'GARNIER LIGHT COMPLETE CREAM 40G', 'productPool/1.jpg', 246 ),
( 'GARNIER LIGHT COMPLETE DAY NIGHT CREAM 40G', 'productPool/1.jpg', 98 ),
( 'GARNIER LIGHT COMPLETE FACE WASH 100G', 'productPool/1.jpg', 26 ),
( 'GARNIER LIGHT COMPLETE FACE WASH 50G', 'productPool/1.jpg', 52 ),
( 'GARNIER LIGHT COMPLETE FACEWASH 50G', 'productPool/1.jpg', 22 ),
( 'GARNIER LIGHT COMPLETE NIGHT CREAM 40G', 'productPool/1.jpg', 251 ),
( 'GARNIER LIGHT COMPLETE SERUM 45G', 'productPool/1.jpg', 85 ),
( 'GARNIER LIGHT COMPLETE UV 23G', 'productPool/1.jpg', 35 ),
( 'GARNIER LONG & STRONG SERUM 100ML', 'productPool/1.jpg', 250 ),
( 'GARNIER MEN ACNO FIGHT CREAM 20G', 'productPool/1.jpg', 71 ),
( 'GARNIER MEN ACNO FIGHT CREAM 45G', 'productPool/1.jpg', 274 ),
( 'GARNIER MEN ACNO FIGHT FACE WASH 100G', 'productPool/1.jpg', 182 ),
( 'GARNIER MEN ACNO FIGHT FACE WASH 50G', 'productPool/1.jpg', 170 ),
( 'GARNIER MEN ACNO FIGHT GEL PEN 10ML', 'productPool/1.jpg', 203 ),
( 'GARNIER MEN INTENSE FRESH FACE WASH 50G', 'productPool/1.jpg', 169 ),
( 'GARNIER MEN INTENSE FRESH FACEWASH 100G', 'productPool/1.jpg', 116 ),
( 'GARNIER MEN OIL CLEAR CLAY FACE WASH 50G', 'productPool/1.jpg', 62 ),
( 'GARNIER MEN OIL CLEAR FACE WASH 100GMS', 'productPool/1.jpg', 115 ),
( 'GARNIER MEN OIL CLEAR MATCHA GELFACEWASH 50G', 'productPool/1.jpg', 128 ),
( 'GARNIER MEN OILCLEAR 100G', 'productPool/1.jpg', 67 ),
( 'GARNIER MEN P W SPF 15 MOISTURISER 45G', 'productPool/1.jpg', 225 ),
( 'GARNIER MEN POWER WHITE DOUBLE ACTION 50 G', 'productPool/1.jpg', 71 ),
( 'GARNIER MEN POWER WHITE DOUBLE ACTION FACE WASH 100G', 'productPool/1.jpg', 270 ),
( 'GARNIER MEN POWER WHITE FACE WASH 100GMS', 'productPool/1.jpg', 48 ),
( 'GARNIER MEN POWER WHITE FACE WASH 50G', 'productPool/1.jpg', 274 ),
( 'GARNIER MEN POWER WHITE MOISTURISER 20G', 'productPool/1.jpg', 32 ),
( 'GARNIER MEN POWER WHITE MOISTURSER 40G', 'productPool/1.jpg', 271 ),
( 'GARNIER MEN POWERLIGHT SPF 15 MOISTURISER', 'productPool/1.jpg', 96 ),
( 'GARNIER MICELLAR CLEANSING WATER 125ML', 'productPool/1.jpg', 21 ),
( 'GARNIER MOISTURISING CREAM40G', 'productPool/1.jpg', 5 ),
( 'GARNIER PURACT NEEM FACE WASH 100G', 'productPool/1.jpg', 245 ),
( 'GARNIER PURE ACTIVE FOAMING FACEWASH 50ML', 'productPool/1.jpg', 147 ),
( 'GARNIER PURE ACTIVE FOAMING FACEWASH100GM', 'productPool/1.jpg', 242 ),
( 'GARNIER PURE ACTIVE NEEM FACEWASH 50G', 'productPool/1.jpg', 226 ),
( 'GARNIER ROYAL JELLY & LAVENDER SHAMPOO 175ML', 'productPool/1.jpg', 222 ),
( 'GARNIER ROYAL JELLY CONDITIONER 75ML', 'productPool/1.jpg', 56 ),
( 'GARNIER ROYAL JELLY LAVENDER CONDITIONER 175ML', 'productPool/1.jpg', 63 ),
( 'GARNIER ROYAL JELLY LAVENDER SHAMPOO 75ML', 'productPool/1.jpg', 10 ),
( 'GARNIER SERUM MASK LIGHT COMPLETE 32G', 'productPool/1.jpg', 195 ),
( 'GARNIER SHAMPOO HERBS 75ML', 'productPool/1.jpg', 133 ),
( 'GARNIER SOY MILK CONDITIONER 175ML', 'productPool/1.jpg', 45 ),
( 'GARNIER SOY MILK CONDITIONER 75ML', 'productPool/1.jpg', 27 ),
( 'GARNIER SOY MILK SHAMPOO 75ML', 'productPool/1.jpg', 69 ),
( 'GARNIER SOYA MILK SHAMPOO 175 ML', 'productPool/1.jpg', 268 ),
( 'GARNIER SUN CONTROL MOISTURISER+INR', 'productPool/1.jpg', 114 ),
( 'GARNIER SUN CONTROL50ML', 'productPool/1.jpg', 264 ),
( 'GARNIER U.B ROYAL JELLY LAVENDER SHAMPOO 175+75ML', 'productPool/1.jpg', 44 ),
( 'GARNIER UB 5 PRECIOUS HERBS SHAMPOO 340ML', 'productPool/1.jpg', 269 ),
( 'GARNIER UB HENNABLACKBERRY SHAMPOO 360ML', 'productPool/1.jpg', 222 ),
( 'GARNIER UB ROYAL JELLY LAVENDER 175ML B1G1', 'productPool/1.jpg', 155 ),
( 'GARNIER ULTRA BLENDS HENNA BLACKBERRY SHAMPOO 60ML', 'productPool/1.jpg', 153 ),
( 'GARNIER ULTRA BLENDS MYTHIC OLIVE 175ML', 'productPool/1.jpg', 96 ),
( 'GARNIER ULTRA BLENDS MYTHIC OLIVE SHAMPOO 180ML', 'productPool/1.jpg', 260 ),
( 'GARNIER WH COMPUR LEM FACEWASH 100G', 'productPool/1.jpg', 20 ),
( 'GARNIER WHITE COMPLETE DOUBLE ACTION 100ML', 'productPool/1.jpg', 99 ),
( 'GARNIER WHITE COMPLETE DOUBLE ACTION 50ML', 'productPool/1.jpg', 137 ),
( 'GARNIER WHITE COMPLETE FAIRNESS FACE WASH 100G', 'productPool/1.jpg', 182 ),
( 'GARNIER WHITE COMPLETE M A F CREAM 18G', 'productPool/1.jpg', 266 ),
( 'GARNIER WINTER CARE CREAM 18G', 'productPool/1.jpg', 188 ),
( 'GARNIER WRINKLE LIFT 18G', 'productPool/1.jpg', 84 ),
( 'GARNIER WRINKLE LIFT 40G', 'productPool/1.jpg', 29 ),
( 'GARNIERB.B CREAM 30G', 'productPool/1.jpg', 250 ),
( 'GARNIIER COLOUR NATURAL BURGUNDY 40G', 'productPool/1.jpg', 221 ),
( 'GAS CANDY 60G', 'productPool/1.jpg', 67 ),
( 'GAS LIGHTER', 'productPool/1.jpg', 70 ),
( 'GAS LIGHTER RS 39', 'productPool/1.jpg', 57 ),
( 'GAS LIGHTER RS35', 'productPool/1.jpg', 124 ),
( 'GATORAD LEMON FLV 500ML', 'productPool/1.jpg', 217 ),
( 'GATORADE BLUE BOLT 500ML DRINKING WATER', 'productPool/1.jpg', 12 ),
( 'GATORADE ORANGE FLA 500ML', 'productPool/1.jpg', 145 ),
( 'GATSBY AARAA BAKHOUR PERFUME 6ML', 'productPool/1.jpg', 273 ),
( 'GATSBY AARAA MUKHALAT AROOSAH PERFUME 6ML', 'productPool/1.jpg', 223 ),
( 'GATSBY AARAA OPEN CLASSIC PERFUME 6ML', 'productPool/1.jpg', 173 ),
( 'GATSBY BARBIE CONDITIONING SHAMPOO 200ML', 'productPool/1.jpg', 61 ),
( 'GATSBY BARBIE FACEWASH 100G', 'productPool/1.jpg', 260 ),
( 'GATSBY BARBIE HANDWASH 250ML', 'productPool/1.jpg', 219 ),
( 'GATSBY BARBIE LONG & BOUNCY SHAMPOO 100ML', 'productPool/1.jpg', 243 ),
( 'GATSBY BARBIE MUSKMELON HAND SANITIZER 50ML', 'productPool/1.jpg', 101 ),
( 'GATSBY BARBIE NOURISH & PROTECH SHAMPOO 100ML', 'productPool/1.jpg', 58 ),
( 'GATSBY BARBIE ORANGE HAND SANITIZER 50ML', 'productPool/1.jpg', 102 ),
( 'GATSBY BARBIE RASBERRY HAND SANITIZER 50ML', 'productPool/1.jpg', 123 ),
( 'GATSBY BARBIE SOFT & SILKY SHAMPOO 100ML', 'productPool/1.jpg', 33 ),
( 'GATSBY BLACK POWER FACEWASH 50G', 'productPool/1.jpg', 250 ),
( 'GATSBY EXTREME HOLD HAIR SPARY 66ML', 'productPool/1.jpg', 52 ),
( 'GATSBY FIBER WAX HIGH QUIFF 75G', 'productPool/1.jpg', 25 ),
( 'GATSBY HAIR CREAM ANTI DANDRUFF 28G', 'productPool/1.jpg', 264 ),
( 'GATSBY HAIR CREAM ANTI DANDRUFF 70G', 'productPool/1.jpg', 53 ),
( 'GATSBY HAIR CREAM NORMAL 28G', 'productPool/1.jpg', 33 ),
( 'GATSBY HAIR CREAM NORMAL 70G', 'productPool/1.jpg', 75 ),
( 'GATSBY HAIR SPARY ULTRA HARD 250ML', 'productPool/1.jpg', 93 ),
( 'GATSBY HAIR SPRAY EXTREME HOLD 250ML', 'productPool/1.jpg', 53 ),
( 'GATSBY HAIR SPRAY SUPER HARD 250ML', 'productPool/1.jpg', 38 ),
( 'GATSBY HAIR STYLING MAX 25G EXTREME&FIRM', 'productPool/1.jpg', 222 ),
( 'GATSBY HAIR STYLING MAX 25G HARD&FREE', 'productPool/1.jpg', 80 ),
( 'GATSBY HAIR STYLING MAX 25G MAT&HARD', 'productPool/1.jpg', 258 ),
( 'GATSBY HAIR STYLING MAX 25G POWER & SPIKE', 'productPool/1.jpg', 160 ),
( 'GATSBY HAIR STYLING MAX 75G EXTREME&FIRM', 'productPool/1.jpg', 170 ),
( 'GATSBY HAIR STYLING MAX 75G LOOSE&FLOW', 'productPool/1.jpg', 30 ),
( 'GATSBY HAIR STYLING MAX 75G MAT&HARD', 'productPool/1.jpg', 6 ),
( 'GATSBY HAIR STYLING MAX 75G POWER&SPIKE', 'productPool/1.jpg', 131 ),
( 'GATSBY HIR STYING WAX HARD AND FREE', 'productPool/1.jpg', 267 ),
( 'GATSBY HIR STYING WAX TOUCH AND SHINE', 'productPool/1.jpg', 232 ),
( 'GATSBY ICE SHOCK FACEWASH 50G', 'productPool/1.jpg', 265 ),
( 'GATSBY OIL CONTROL FACEWASH 50G', 'productPool/1.jpg', 12 ),
( 'GATSBY PERFECT CLEAN FACEWASH 100G', 'productPool/1.jpg', 187 ),
( 'GATSBY SHAVING GEL N COOL 205G', 'productPool/1.jpg', 227 ),
( 'GATSBY SHOWER GEL 600ML', 'productPool/1.jpg', 197 ),
( 'GATSBY SILVANA HANDWASH 450ML', 'productPool/1.jpg', 200 ),
( 'GATSBY SPEEDY BRIGHT FACEWASH 50G', 'productPool/1.jpg', 153 ),
( 'GATSBY STYLING POMADE PERFECT RAISE 30G', 'productPool/1.jpg', 110 ),
( 'GATSBY STYLING POMADE PERFECT RAISE 75G', 'productPool/1.jpg', 265 ),
( 'GATSBY STYLING POMADE SUPREME GREASE 30G', 'productPool/1.jpg', 2 ),
( 'GATSBY STYLING POMADE SUPREME GREASE 75G', 'productPool/1.jpg', 206 ),
( 'GATSBY STYLING POMADE SUPREME HOLD 30G', 'productPool/1.jpg', 114 ),
( 'GATSBY STYLING POMADE SUPREME HOLD 75G', 'productPool/1.jpg', 122 ),
( 'GATSBY STYLING POMADE URBAN DRY 30G', 'productPool/1.jpg', 4 ),
( 'GATSBY STYLING POMADE URBAN DRY 75G', 'productPool/1.jpg', 256 ),
( 'GATSBY WATER GLOSS 100 G', 'productPool/1.jpg', 267 ),
( 'GATSBY WATER GLOSS 150G', 'productPool/1.jpg', 132 ),
( 'GATSBY WATER GLOSS 30G', 'productPool/1.jpg', 69 ),
( 'GATSBY WATER GLOSS 30G HARD', 'productPool/1.jpg', 188 ),
( 'GATSBY WATER GLOSS 30G HYPER SOLID', 'productPool/1.jpg', 119 ),
( 'GATSBY WATER GLOSS 30G SOFT', 'productPool/1.jpg', 58 ),
( 'GATSBY WATER GLOSS 50G HARD', 'productPool/1.jpg', 273 ),
( 'GATSBY WATER GLOSS 50G HYPER SOLID', 'productPool/1.jpg', 228 ),
( 'GATSBY WATER GLOSS 50G SOFT', 'productPool/1.jpg', 18 ),
( 'GATSBY WATER GLOSS 50G SUPER HARD', 'productPool/1.jpg', 257 ),
( 'GATSBY WATER GLOSS HARD 150G', 'productPool/1.jpg', 205 ),
( 'GATSBY WATER GLOSS HARD 300G', 'productPool/1.jpg', 36 ),
( 'GATSBY WATER GLOSS HYPER SOLID 300G', 'productPool/1.jpg', 210 ),
( 'GATSBY WATER GLOSS HYPER SOLID100G', 'productPool/1.jpg', 60 ),
( 'GATSBY WATER GLOSS SOFT 100G', 'productPool/1.jpg', 181 ),
( 'GATSBY WATER GLOSS SOFT 150G', 'productPool/1.jpg', 152 ),
( 'GATSBY WATER GLOSS SOFT 300G', 'productPool/1.jpg', 75 ),
( 'GATSBY WATER GLOSS SUPER HARD 100G', 'productPool/1.jpg', 144 ),
( 'GATSBY WATER GLOSS SUPER HARD 150G', 'productPool/1.jpg', 13 ),
( 'GATSBY WATER GLOSS SUPER HARD 300G', 'productPool/1.jpg', 101 ),
( 'GAURAV 450ML SILVER LINE JAR', 'productPool/1.jpg', 63 ),
( 'GAURAV PET JAR 1000ML', 'productPool/1.jpg', 191 ),
( 'GAURAV SILVER LINE CONTAINER 50ML JAR', 'productPool/1.jpg', 199 ),
( 'GAURAV SILVER LINE CONTAINER 750ML JAR', 'productPool/1.jpg', 21 ),
( 'GAURAV SILVER LINE JAR 2200ML', 'productPool/1.jpg', 253 ),
( 'GEBI 10METER WIRE ROPE WIL', 'productPool/1.jpg', 130 ),
( 'GEBI CLIP MOP 350', 'productPool/1.jpg', 222 ),
( 'GEBI CUTE BRUSH', 'productPool/1.jpg', 167 ),
( 'GEBI DELUXE MULTI BROOM 6FT', 'productPool/1.jpg', 179 ),
( 'GEBI DIAMKOND CARPET AND SOFA BRUSH', 'productPool/1.jpg', 114 ),
( 'GEBI DOLPHIN DUSTPAN', 'productPool/1.jpg', 71 ),
( 'GEBI GENIUS MOP-350', 'productPool/1.jpg', 275 ),
( 'GEBI HOCKEY TOILET BRUSH', 'productPool/1.jpg', 247 ),
( 'GEBI KAREENA SPRAYER 500ML', 'productPool/1.jpg', 178 ),
( 'GEBI KING KONG FLOOR BRUSH', 'productPool/1.jpg', 277 ),
( 'GEBI MAHALAKSHMI GRASS BROOM', 'productPool/1.jpg', 248 ),
( 'GEBI PUSH BROOM 1N', 'productPool/1.jpg', 210 ),
( 'GEBI REAL KHARATA REGULAR 60 STICKS', 'productPool/1.jpg', 64 ),
( 'GEBI ROPE 20METER', 'productPool/1.jpg', 278 ),
( 'GEBI ROYAL GLASS CLEANER', 'productPool/1.jpg', 273 ),
( 'GEBI ROYAL TOUCH BODY BRUSH', 'productPool/1.jpg', 271 ),
( 'GEBI SCRATCHY BRUSH', 'productPool/1.jpg', 134 ),
( 'GEBI SHOE BRUSH SINGLE SIDED', 'productPool/1.jpg', 231 ),
( 'GEBI SUPER CLEAN SET 1U', 'productPool/1.jpg', 40 ),
( 'GEBI T MOP METAL HANDLE', 'productPool/1.jpg', 160 ),
( 'GEBI UNIQUE TOILET BRUSH', 'productPool/1.jpg', 218 ),
( 'GEBI UTILITY BRUSH', 'productPool/1.jpg', 204 ),
( 'GEEVAMS RAGITONE 500G', 'productPool/1.jpg', 204 ),
( 'GEMINI FOOD COVER', 'productPool/1.jpg', 130 ),
( 'GEMINI FOOD COVER JUMBO', 'productPool/1.jpg', 219 ),
( 'GEMS SURPRISE ANGRY BIRDS 17.8GM', 'productPool/1.jpg', 236 ),
( 'GERY COCONUT CRACKERS 110G', 'productPool/1.jpg', 273 ),
( 'GERY SUGAR CHEESE CRACKERS 110G', 'productPool/1.jpg', 142 ),
( 'GET OUT BLEACHING POWDER 500G', 'productPool/1.jpg', 225 ),
( 'GET OUT PER CLEALOTI 1LTR', 'productPool/1.jpg', 31 ),
( 'GIFFY ACTIVE SALT DISH WASH GEL GREEN LIME 250ML', 'productPool/1.jpg', 126 ),
( 'GIFFY ACTIVE SALT DISH WASH GEL GREEN LIME 500ML', 'productPool/1.jpg', 95 ),
( 'GIFFY ACTIVE SALT DISH WASH GEL LEMON 250ML', 'productPool/1.jpg', 156 ),
( 'GIFFY ACTIVE SALT DISH WASH GEL LEMON 500ML', 'productPool/1.jpg', 137 ),
( 'GIFT BOX ASSOTED 158.2G', 'productPool/1.jpg', 12 ),
( 'GIFT PACK', 'productPool/1.jpg', 176 ),
( 'GIFT PAPER', 'productPool/1.jpg', 54 ),
( 'GIFT PAPER RS120', 'productPool/1.jpg', 219 ),
( 'GIFT RIBBON', 'productPool/1.jpg', 76 ),
( 'GIFTPACK MIXED 150G MRP 200', 'productPool/1.jpg', 146 ),
( 'GILLEETTE AFTER SHAVE SPLASH 100ML', 'productPool/1.jpg', 39 ),
( 'GILLET 7O CLOCK BLADE', 'productPool/1.jpg', 205 ),
( 'GILLET SHAVING CREAM REGULAR 30G', 'productPool/1.jpg', 69 ),
( 'GILLET WILKINSONS SWORD', 'productPool/1.jpg', 57 ),
( 'GILLETE 7CLK RAZOR', 'productPool/1.jpg', 203 ),
( 'GILLETE 7O CLOCK SUPER PLATINUM RAZOR', 'productPool/1.jpg', 69 ),
( 'GILLETE FOAM SENSTIVE 418Gm', 'productPool/1.jpg', 119 ),
( 'GILLETE SHAVING BRUSH 54', 'productPool/1.jpg', 182 ),
( 'GILLETE VECTOR 3 CART 2S', 'productPool/1.jpg', 15 ),
( 'GILLETE WILKINSON SWORD BLADE', 'productPool/1.jpg', 61 ),
( 'GILLETT SENSOR EXCEL', 'productPool/1.jpg', 183 ),
( 'GILLETTE 7 CLOCK READY II', 'productPool/1.jpg', 212 ),
( 'GILLETTE 7 O CLOCK PERMA SHARP', 'productPool/1.jpg', 142 ),
( 'GILLETTE 7 O CLOCK PERMASHARP STAINLESS', 'productPool/1.jpg', 114 ),
( 'GILLETTE 7 O CLOCK PII RAZOR', 'productPool/1.jpg', 168 ),
( 'GILLETTE 7 O CLOCK STERLING RAZOR', 'productPool/1.jpg', 249 ),
( 'GILLETTE 7 OCLOCK PII', 'productPool/1.jpg', 240 ),
( 'GILLETTE 7 OCLOCK PII 5S', 'productPool/1.jpg', 10 ),
( 'GILLETTE 7O CLOCK SUPER PLATINUM BLADE', 'productPool/1.jpg', 32 ),
( 'GILLETTE AFTER SHAVE SPLASH COOL WAVE 50ML', 'productPool/1.jpg', 26 ),
( 'GILLETTE AFTER SHAVER SPIASH COOL 50ML', 'productPool/1.jpg', 71 ),
( 'GILLETTE ARCTIC ICE BOLD', 'productPool/1.jpg', 89 ),
( 'GILLETTE FOAM LEMON LIME 196G', 'productPool/1.jpg', 105 ),
( 'GILLETTE FOAM MENTHOL 196G', 'productPool/1.jpg', 234 ),
( 'GILLETTE FOAM REGULAR 196G', 'productPool/1.jpg', 68 ),
( 'GILLETTE FOAM REGULAR 418G', 'productPool/1.jpg', 139 ),
( 'GILLETTE FOAM REGULAR 50G', 'productPool/1.jpg', 226 ),
( 'GILLETTE FUSION CART 2S', 'productPool/1.jpg', 47 ),
( 'GILLETTE FUSION CART 4S', 'productPool/1.jpg', 9 ),
( 'GILLETTE FUSION CART 8S', 'productPool/1.jpg', 158 ),
( 'GILLETTE FUSION CARTIDGE 4S', 'productPool/1.jpg', 214 ),
( 'GILLETTE FUSION CARTIDGE 8S', 'productPool/1.jpg', 259 ),
( 'GILLETTE FUSION HYDRA GEL 75ML', 'productPool/1.jpg', 107 ),
( 'GILLETTE FUSION POWER 2 S', 'productPool/1.jpg', 248 ),
( 'GILLETTE FUSION POWER CART 4S', 'productPool/1.jpg', 116 ),
( 'GILLETTE FUSION POWER RAZOR', 'productPool/1.jpg', 146 ),
( 'GILLETTE FUSION PROGLIDE 2S', 'productPool/1.jpg', 131 ),
( 'GILLETTE FUSION PROGLIDE 4', 'productPool/1.jpg', 44 ),
( 'GILLETTE FUSION PROGLIDE FLEXBALL RAZOR', 'productPool/1.jpg', 206 ),
( 'GILLETTE FUSION PROGLIDE RAZOR', 'productPool/1.jpg', 245 ),
( 'GILLETTE FUSION PROGLIDE STYLER', 'productPool/1.jpg', 266 ),
( 'GILLETTE FUSION RAZOR', 'productPool/1.jpg', 119 ),
( 'GILLETTE FUSION SENSETIVE SKIN SHAVE GEL 200ML', 'productPool/1.jpg', 84 ),
( 'GILLETTE GUARD 1S', 'productPool/1.jpg', 12 ),
( 'GILLETTE GUARD BASE 3S', 'productPool/1.jpg', 191 ),
( 'GILLETTE GUARD BASE 6S', 'productPool/1.jpg', 227 ),
( 'GILLETTE GUARD CART 3S', 'productPool/1.jpg', 144 ),
( 'GILLETTE GUARD CART 6S', 'productPool/1.jpg', 51 ),
( 'GILLETTE GUARD CART1S', 'productPool/1.jpg', 272 ),
( 'GILLETTE GUARD RAZOR + 6 CART OFFER', 'productPool/1.jpg', 76 ),
( 'GILLETTE GUARD RAZOR 1S', 'productPool/1.jpg', 129 ),
( 'GILLETTE GUARD SHAVING GEL 80G', 'productPool/1.jpg', 206 ),
( 'GILLETTE LIME SHAVING CREAM 30G', 'productPool/1.jpg', 260 ),
( 'GILLETTE LIME SHAVING CREAM 93.1G', 'productPool/1.jpg', 180 ),
( 'GILLETTE MACH 3 12S', 'productPool/1.jpg', 259 ),
( 'GILLETTE MACH3 CART 12S', 'productPool/1.jpg', 127 ),
( 'GILLETTE MACH3 CART 2S', 'productPool/1.jpg', 276 ),
( 'GILLETTE MACH3 CART 4S', 'productPool/1.jpg', 159 ),
( 'GILLETTE MACH3 CART 8S', 'productPool/1.jpg', 57 ),
( 'GILLETTE MACH3 CATRIDGE 12S', 'productPool/1.jpg', 163 ),
( 'GILLETTE MACH3 GEL EXTRA COMFORT 70G', 'productPool/1.jpg', 80 ),
( 'GILLETTE MACH3 GEL SMOOTH 195G', 'productPool/1.jpg', 16 ),
( 'GILLETTE MACH3 RAZOR', 'productPool/1.jpg', 22 ),
( 'GILLETTE MACH3 RAZOR TURBO', 'productPool/1.jpg', 161 ),
( 'GILLETTE MACH3 START CART 2S', 'productPool/1.jpg', 138 ),
( 'GILLETTE MACH3 START CART 4S', 'productPool/1.jpg', 179 ),
( 'GILLETTE MACH3 START CART 8S', 'productPool/1.jpg', 77 ),
( 'GILLETTE MACH3 START RAZOR', 'productPool/1.jpg', 91 ),
( 'GILLETTE MACH3 TURBO 4S', 'productPool/1.jpg', 205 ),
( 'GILLETTE MACH3 TURBO CART 2S', 'productPool/1.jpg', 52 ),
( 'GILLETTE MACH3 TURBO CART 4S', 'productPool/1.jpg', 149 ),
( 'GILLETTE MACH3 TURBO CART 8S', 'productPool/1.jpg', 205 ),
( 'GILLETTE MACH3 TURBO RAZOR', 'productPool/1.jpg', 199 ),
( 'GILLETTE MACH3 TURBO SENSITIVE 4S', 'productPool/1.jpg', 251 ),
( 'GILLETTE MATCH 3 SENSITIVE SHAVE GEL 195G', 'productPool/1.jpg', 181 ),
( 'GILLETTE MATCH 3 TURBO SENSITIVE CART 2S', 'productPool/1.jpg', 54 ),
( 'GILLETTE MATCH3 CART 8S', 'productPool/1.jpg', 27 ),
( 'GILLETTE MATCH3 TURBO 4S', 'productPool/1.jpg', 136 ),
( 'GILLETTE PRESTO 3 1S', 'productPool/1.jpg', 203 ),
( 'GILLETTE PRESTO B3G1', 'productPool/1.jpg', 58 ),
( 'GILLETTE PRESTO RAZOR 5S', 'productPool/1.jpg', 109 ),
( 'GILLETTE REGULAR SHAVING CREAM 30G', 'productPool/1.jpg', 259 ),
( 'GILLETTE REGULAR SHAVING CREAM 93.1G', 'productPool/1.jpg', 82 ),
( 'GILLETTE SATIN CARE SHAVE GEL 195G', 'productPool/1.jpg', 200 ),
( 'GILLETTE SAVING CREAM REGULAR 70G', 'productPool/1.jpg', 26 ),
( 'GILLETTE SENSITIVE SHAVE GEL 25G', 'productPool/1.jpg', 120 ),
( 'GILLETTE SENSITIVE SHAVE GEL 60G', 'productPool/1.jpg', 20 ),
( 'GILLETTE SERIES 3X SENSITIVE 70G', 'productPool/1.jpg', 259 ),
( 'GILLETTE SERIES FOAM CONDITIONING 245G', 'productPool/1.jpg', 133 ),
( 'GILLETTE SERIES GEL PURE SENSITIVE 195G', 'productPool/1.jpg', 108 ),
( 'GILLETTE SERIES GEL PURE&SENSITIVE 195 G', 'productPool/1.jpg', 45 ),
( 'GILLETTE SERIES SENSITIVE 245G', 'productPool/1.jpg', 81 ),
( 'GILLETTE SERIES SENSITIVE SHAVE GEL 195G', 'productPool/1.jpg', 47 ),
( 'GILLETTE SERIES SHAVE GEL 60G', 'productPool/1.jpg', 41 ),
( 'GILLETTE SHAVE BRUSH', 'productPool/1.jpg', 209 ),
( 'GILLETTE SHAVE GEL MOISTURIZING 60G', 'productPool/1.jpg', 153 ),
( 'GILLETTE SHAVE SPLASH ARCTIC ICE 50ML', 'productPool/1.jpg', 194 ),
( 'GILLETTE SHAVE SPLASH COOL WAVE 100ML', 'productPool/1.jpg', 77 ),
( 'GILLETTE SHAVING CREAM LIME 30G', 'productPool/1.jpg', 215 ),
( 'GILLETTE SHAVING CREAM LIME 70GM', 'productPool/1.jpg', 184 ),
( 'GILLETTE SHAVING FOAM 196G', 'productPool/1.jpg', 26 ),
( 'GILLETTE SKIN GUARD SENSITIVE 4S', 'productPool/1.jpg', 204 ),
( 'GILLETTE SKINGUARD SENSITIVE 2S', 'productPool/1.jpg', 190 ),
( 'GILLETTE SKINGUARD SENSITIVE 8S', 'productPool/1.jpg', 19 ),
( 'GILLETTE SKINGUARD SENSITIVE RAZOR', 'productPool/1.jpg', 229 ),
( 'GILLETTE TUBE SHAVE GEL ULTRA COMFORT60G', 'productPool/1.jpg', 212 ),
( 'GILLETTE VECTOR 6S', 'productPool/1.jpg', 115 ),
( 'GILLETTE VECTOR CART 2S', 'productPool/1.jpg', 162 ),
( 'GILLETTE VECTOR CART 4S', 'productPool/1.jpg', 53 ),
( 'GILLETTE VECTOR CART 6', 'productPool/1.jpg', 149 ),
( 'GILLETTE VECTOR CART 6S', 'productPool/1.jpg', 104 ),
( 'GILLETTE VECTOR RAZOR GREY', 'productPool/1.jpg', 72 ),
( 'GILLETTE VECTOR3 CART 4SX12X6', 'productPool/1.jpg', 144 ),
( 'GILLETTE VECTOR3 RAZOR', 'productPool/1.jpg', 219 ),
( 'GILLETTE VENUS 3 BLADES', 'productPool/1.jpg', 151 ),
( 'GILLETTE VENUS 4 CART', 'productPool/1.jpg', 202 ),
( 'GILLETTE VENUS BREEZE CART 2S', 'productPool/1.jpg', 3 ),
( 'GILLETTE VENUS BREEZE RAZOR', 'productPool/1.jpg', 13 ),
( 'GILLETTE VENUS BREEZE RAZOR 3S', 'productPool/1.jpg', 52 ),
( 'GILLETTE VENUS CART 2S', 'productPool/1.jpg', 155 ),
( 'GILLETTE VENUS CART 4S', 'productPool/1.jpg', 222 ),
( 'GILLETTE VENUS RAZOR', 'productPool/1.jpg', 254 ),
( 'GILLETTE WILKINSON SWORD BLADE RS14', 'productPool/1.jpg', 9 ),
( 'GILLETTE WILKKINSON SWORD BLADE', 'productPool/1.jpg', 162 ),
( 'GILLETTE WILMAN CART 5S', 'productPool/1.jpg', 18 ),
( 'GILLETTE WILMAN II CART 5N', 'productPool/1.jpg', 141 ),
( 'GILLETTE WINNER PLATINUM BLADE 50+5', 'productPool/1.jpg', 32 ),
( 'GINGER', 'productPool/1.jpg', 65 ),
( 'GINGER CANDY', 'productPool/1.jpg', 150 ),
( 'GINGER CANDY 100G', 'productPool/1.jpg', 24 ),
( 'GINGER CANDY 50G', 'productPool/1.jpg', 202 ),
( 'GINGER CUBES 100G', 'productPool/1.jpg', 231 ),
( 'GINGER GARLIC PASTE', 'productPool/1.jpg', 83 ),
( 'GINGER HONEY DRIED 100G', 'productPool/1.jpg', 266 ),
( 'GINGER NUTS COOKIES 250G', 'productPool/1.jpg', 244 ),
( 'GINGER PASTE 100G PKT', 'productPool/1.jpg', 141 ),
( 'GINGER PEEL 100G', 'productPool/1.jpg', 256 ),
( 'GIO POWER DISH WASH BAR', 'productPool/1.jpg', 15 ),
( 'GITS BADAM AND PISTA FALOODA MIX 200G', 'productPool/1.jpg', 237 ),
( 'GITS BROWN RICE IDILI WITH FLAX SEEDS MIX 200G', 'productPool/1.jpg', 237 ),
( 'GITS DAL MAKHANI 300G', 'productPool/1.jpg', 12 ),
( 'GITS GULABJAMUN MIX 250G', 'productPool/1.jpg', 49 ),
( 'GITS JILEBI MIX 100G', 'productPool/1.jpg', 171 ),
( 'GITS KESAR KULFI MIX 100G', 'productPool/1.jpg', 10 ),
( 'GITS MEDU VADAI MIX 200G', 'productPool/1.jpg', 139 ),
( 'GITS MOONG DAL VADA MIX 200G', 'productPool/1.jpg', 181 ),
( 'GITS OATS IDILI MIX 200G', 'productPool/1.jpg', 79 ),
( 'GITS PUNJABI CHHOLE 300G', 'productPool/1.jpg', 234 ),
( 'GITS RAVA IDLI MIX 200G', 'productPool/1.jpg', 236 ),
( 'GITS READY MEALS MATAR PANEER 285G', 'productPool/1.jpg', 179 ),
( 'GITS READY MEALS PALAK PANEER 285G', 'productPool/1.jpg', 193 ),
( 'GITS READY MEALS PANEER MAKHANI 285G', 'productPool/1.jpg', 47 ),
( 'GITS READY MEALS PANEER TIKKA MASALA 285G', 'productPool/1.jpg', 87 ),
( 'GITS READY MEALS PAU BHAJI 300G', 'productPool/1.jpg', 148 ),
( 'GITS READY MEALS VEG. BIRYANI 265G', 'productPool/1.jpg', 112 ),
( 'GITS ROSE FALOODA MIX 200G', 'productPool/1.jpg', 261 ),
( 'GLAD CLING WRAP 100 SQ FT', 'productPool/1.jpg', 256 ),
( 'GLAD CONGELATEUR ZIPPER BAGS 30N', 'productPool/1.jpg', 161 ),
( 'GLAD GALLON ZIPPER BAGS 15N', 'productPool/1.jpg', 244 ),
( 'GLAD PRESS N SEAL WRAP 70 SR FT', 'productPool/1.jpg', 102 ),
( 'GLAD STORAGE ZIPPER BAGS 50N', 'productPool/1.jpg', 111 ),
( 'GLADE GEL FRESHENER CLEAN LINEN 70G', 'productPool/1.jpg', 11 ),
( 'GLADE GEL FRESHENER LAUGH WILDLY 70G', 'productPool/1.jpg', 186 ),
( 'GLADE GEL FRESHENER LEMON FRESH 70G', 'productPool/1.jpg', 96 ),
( 'GLADE GEL FRESHENER LIVE FULLY 70G', 'productPool/1.jpg', 170 ),
( 'GLAM UP GLOMATIC CREAM 34G', 'productPool/1.jpg', 146 ),
( 'GLAM UP POWDER CREAM 25GM', 'productPool/1.jpg', 49 ),
( 'GLASS CLEANER ECO FRIENDLY 250ML', 'productPool/1.jpg', 128 ),
( 'GLASS HOOK RS45', 'productPool/1.jpg', 91 ),
( 'GLASS STAND FAMILY', 'productPool/1.jpg', 279 ),
( 'GLASS WIPPER RS52', 'productPool/1.jpg', 171 ),
( 'GLATT CREAM', 'productPool/1.jpg', 49 ),
( 'GLATT IMP', 'productPool/1.jpg', 243 ),
( 'GLIZOL FLOOR SHINE 500ML', 'productPool/1.jpg', 269 ),
( 'GLOBAL EHS ARROWROOT POWDER 100G', 'productPool/1.jpg', 149 ),
( 'GLOBAL EHS ARROWROOT POWDER 250G', 'productPool/1.jpg', 226 ),
( 'GLORIA DATES 400G', 'productPool/1.jpg', 109 ),
( 'GLOVES', 'productPool/1.jpg', 124 ),
( 'GLOVES RS 70', 'productPool/1.jpg', 72 ),
( 'GLUCERNA VANILA 400GM TIN', 'productPool/1.jpg', 165 ),
( 'GLUCO VITA GLUCOVITAGLUCOSED100G', 'productPool/1.jpg', 194 ),
( 'GLUCOVITA 200 + 40 GMS JAR', 'productPool/1.jpg', 76 ),
( 'GLUCOVITA BOLTS 18G STRAWBERRY', 'productPool/1.jpg', 135 ),
( 'GLUCOVITA BOLTS COLA FLAVOUR 18G', 'productPool/1.jpg', 179 ),
( 'GLUCOVITA BOTTLE MANGO 18G', 'productPool/1.jpg', 35 ),
( 'GLUCOVITA BOTTLE ORANGE', 'productPool/1.jpg', 115 ),
( 'GLUCOVITA BOTTLE STRAWBERY', 'productPool/1.jpg', 39 ),
( 'GLYCERIN ROSE 100ML', 'productPool/1.jpg', 191 ),
( 'GLYCERIN ROSE 50G', 'productPool/1.jpg', 65 ),
( 'GO FRESH MILK CREAM CHOCLATE 25G', 'productPool/1.jpg', 85 ),
( 'GO WALNUT 250G', 'productPool/1.jpg', 262 ),
( 'GOAL CHOCOLATE BOX 550G', 'productPool/1.jpg', 250 ),
( 'GOAL CHOCOLATE CHATTY 650G', 'productPool/1.jpg', 224 ),
( 'GOAL CHOCOLATE DOVE 280G', 'productPool/1.jpg', 159 ),
( 'GOAL CHOCOLATE OVAL 300G', 'productPool/1.jpg', 215 ),
( 'GOAL CHOCOLATE ROUND 250G', 'productPool/1.jpg', 274 ),
( 'GODERAJ SHAVING CREAM', 'productPool/1.jpg', 116 ),
( 'GODREI NO. 1 SAFFRON & MILK SOAP 400G', 'productPool/1.jpg', 224 ),
( 'GODREJ 3277 LOCK', 'productPool/1.jpg', 38 ),
( 'GODREJ 3285 LOCK MRP 218', 'productPool/1.jpg', 25 ),
( 'GODREJ 3286LOCK MRP241.00', 'productPool/1.jpg', 266 ),
( 'GODREJ 3287 7L LOCK MRP310', 'productPool/1.jpg', 91 ),
( 'GODREJ 7672 40MM LOCK', 'productPool/1.jpg', 206 ),
( 'GODREJ 8148 ROUND PADLOCK', 'productPool/1.jpg', 67 ),
( 'GODREJ AER CLICK GEL PETAL PINK 10G', 'productPool/1.jpg', 276 ),
( 'GODREJ AER CLICK GEL RICH IRISH', 'productPool/1.jpg', 213 ),
( 'GODREJ AER CLICKGEL MUSK', 'productPool/1.jpg', 264 ),
( 'GODREJ AER FRESH CLICK GEL GREEN', 'productPool/1.jpg', 217 ),
( 'GODREJ AER MORNING POCKET 10G', 'productPool/1.jpg', 10 ),
( 'GODREJ AER PETAL PINK POCKET 10G', 'productPool/1.jpg', 27 ),
( 'GODREJ AER SPARY COOL 300ML', 'productPool/1.jpg', 87 ),
( 'GODREJ AER SPARY MUSK 300ML', 'productPool/1.jpg', 24 ),
( 'GODREJ AER SPARY PETAL 300ML', 'productPool/1.jpg', 34 ),
( 'GODREJ AER SPRAY FRESH 300ML', 'productPool/1.jpg', 150 ),
( 'GODREJ AER SPRAY MORNING 300ML', 'productPool/1.jpg', 34 ),
( 'GODREJ AER SPRAY VIOLET 300ML', 'productPool/1.jpg', 178 ),
( 'GODREJ AER TWIST GEL COOL 45G', 'productPool/1.jpg', 257 ),
( 'GODREJ AER TWIST GEL FRESH', 'productPool/1.jpg', 92 ),
( 'GODREJ AER TWIST GEL MUSK 45G', 'productPool/1.jpg', 219 ),
( 'GODREJ AER TWIST GEL PETAL', 'productPool/1.jpg', 186 ),
( 'GODREJ AIR POCKET BRIGHT 10G', 'productPool/1.jpg', 116 ),
( 'GODREJ AIR POCKET VIOLET 10G', 'productPool/1.jpg', 133 ),
( 'GODREJ BLACK BROWN CREME HAIR COLOUR', 'productPool/1.jpg', 152 ),
( 'GODREJ CARTINI ALL PURPOSE SCISSORS 7131', 'productPool/1.jpg', 25 ),
( 'GODREJ CARTINI BAMBOO CHOPPING BOARD 7252', 'productPool/1.jpg', 23 ),
( 'GODREJ CARTINI CARVING KNIFE GREEN 7157', 'productPool/1.jpg', 180 ),
( 'GODREJ CARTINI CARVING KNIFE RED 7159', 'productPool/1.jpg', 128 ),
( 'GODREJ CARTINI CHEF KNIFE 7244', 'productPool/1.jpg', 136 ),
( 'GODREJ CARTINI CLASSIC BREAD KNIFE 4654', 'productPool/1.jpg', 46 ),
( 'GODREJ CARTINI CLASSIC PARING KNIFE 6266', 'productPool/1.jpg', 162 ),
( 'GODREJ CARTINI CLASSIC SLICING KNIFE 6268', 'productPool/1.jpg', 84 ),
( 'GODREJ CARTINI CLASSIC VEGETABLE KNIFE 6267', 'productPool/1.jpg', 121 ),
( 'GODREJ CARTINI COMFORT SCISSORS LARGE 5947', 'productPool/1.jpg', 205 ),
( 'GODREJ CARTINI COMFORT SCISSORS SMALL 5948', 'productPool/1.jpg', 238 ),
( 'GODREJ CARTINI EASY CHOPPING KNIFE 6256', 'productPool/1.jpg', 238 ),
( 'GODREJ CARTINI EASY KNIFE 6272', 'productPool/1.jpg', 227 ),
( 'GODREJ CARTINI EVERYDAY SCISSORS 7133', 'productPool/1.jpg', 85 ),
( 'GODREJ CARTINI FINE CUT SCISSORS 7124', 'productPool/1.jpg', 118 ),
( 'GODREJ CARTINI FINE DICING KNIFE 7139', 'productPool/1.jpg', 241 ),
( 'GODREJ CARTINI FINE DICING KNIFE 7154', 'productPool/1.jpg', 262 ),
( 'GODREJ CARTINI HANDY KNIFE 6273', 'productPool/1.jpg', 273 ),
( 'GODREJ CARTINI HANDY KNIFE 7144', 'productPool/1.jpg', 183 ),
( 'GODREJ CARTINI KIDS CRAFT SCISSORS 6274', 'productPool/1.jpg', 164 ),
( 'GODREJ CARTINI LITTLE SCISSORS 7135', 'productPool/1.jpg', 161 ),
( 'GODREJ CARTINI PARING KNIFE 7145', 'productPool/1.jpg', 218 ),
( 'GODREJ CARTINI PERSONAL SCISSORS 7134', 'productPool/1.jpg', 108 ),
( 'GODREJ CARTINI QUICK CUT SCISSORS 7123', 'productPool/1.jpg', 65 ),
( 'GODREJ CARTINI RUBBERWOOD CHOPPING BOARD 7250', 'productPool/1.jpg', 131 ),
( 'GODREJ CARTINI SLICING KNIFE 7147', 'productPool/1.jpg', 267 ),
( 'GODREJ CARTINI SUPER SLICING KNIFE 7140', 'productPool/1.jpg', 217 ),
( 'GODREJ CARTINI SWIFT CUTTING KNIFE 7138', 'productPool/1.jpg', 2 ),
( 'GODREJ CARTINI TIP CUT SCISSORS 7130', 'productPool/1.jpg', 189 ),
( 'GODREJ CARTINI TOMATO KNIFE 7148', 'productPool/1.jpg', 242 ),
( 'GODREJ CARTINI TRIM CUT SCISSORS 7128', 'productPool/1.jpg', 161 ),
( 'GODREJ CINTHOL COOL SOAP SET 450G', 'productPool/1.jpg', 266 ),
( 'GODREJ CINTHOL COOL SOAP SET 500G', 'productPool/1.jpg', 148 ),
( 'GODREJ CINTHOL DEO DIVE 150ML', 'productPool/1.jpg', 231 ),
( 'GODREJ CINTHOL DEOSHOT CHARGE 25ML', 'productPool/1.jpg', 157 ),
( 'GODREJ CINTHOL LIME SOAP 50G', 'productPool/1.jpg', 181 ),
( 'GODREJ CINTHOL LIME SOAP SET 500G', 'productPool/1.jpg', 211 ),
( 'GODREJ CLICK GEL COOL BLUE 10G', 'productPool/1.jpg', 94 ),
( 'GODREJ EXPE LIQUID HADY 20ML', 'productPool/1.jpg', 38 ),
( 'GODREJ EXPE LIQUID HADYE 40ML', 'productPool/1.jpg', 140 );