INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'MUNIX SCISSOR SL1183', 'productPool/1.jpg', 214 ),
( 'MUNIX SCISSORS FL 1243', 'productPool/1.jpg', 196 ),
( 'MUNIX SCISSORS GL-2185', 'productPool/1.jpg', 57 ),
( 'MUNIX SCISSORS GS-4136', 'productPool/1.jpg', 204 ),
( 'MUNIX SCISSORS GS-4236', 'productPool/1.jpg', 208 ),
( 'MUNIX SCISSORS KIDS KR-9153', 'productPool/1.jpg', 210 ),
( 'MUNIX SCISSORS KIDS SL-1145', 'productPool/1.jpg', 63 ),
( 'MUNIX SCISSORS SL-1140', 'productPool/1.jpg', 157 ),
( 'MUNNAR CARDAMOM POWDER 20G', 'productPool/1.jpg', 128 ),
( 'MUNNAR CARDAMOM TEA100G', 'productPool/1.jpg', 126 ),
( 'MUNNAR CARDOMOM TEA 250G', 'productPool/1.jpg', 154 ),
( 'MUNTHIRI 1KG', 'productPool/1.jpg', 89 ),
( 'MURAM BIG', 'productPool/1.jpg', 162 ),
( 'MURAM SMALL MOULD', 'productPool/1.jpg', 206 ),
( 'MURIVENNA 100ML', 'productPool/1.jpg', 267 ),
( 'MUSK BLACK DARK 60ML', 'productPool/1.jpg', 179 ),
( 'MUSK BLACK DK SPARY 15ML', 'productPool/1.jpg', 253 ),
( 'MUSK BODY GUARD 50ML', 'productPool/1.jpg', 100 ),
( 'MUSK BOSS 60ML', 'productPool/1.jpg', 263 ),
( 'MUSK BOSS ROLL 3ML', 'productPool/1.jpg', 169 ),
( 'MUSK BOSS ROLL 8ML', 'productPool/1.jpg', 39 ),
( 'MUSK BOSS SPARY 15ML', 'productPool/1.jpg', 146 ),
( 'MUSK BRUTE ROLL 3ML', 'productPool/1.jpg', 140 ),
( 'MUSK BRUTE ROLL 8ML', 'productPool/1.jpg', 228 ),
( 'MUSK BRUTE SPRAY 60ML', 'productPool/1.jpg', 100 ),
( 'MUSK ENEMI ROLL 3ML', 'productPool/1.jpg', 41 ),
( 'MUSK ENEMI ROLL 8ML', 'productPool/1.jpg', 239 ),
( 'MUSK ENEMI SPARY 60ML', 'productPool/1.jpg', 223 ),
( 'MUSK FEELINGS SPARY 50ML', 'productPool/1.jpg', 18 ),
( 'MUSK LADY GUARD SPARY 50ML', 'productPool/1.jpg', 168 ),
( 'MUSK MARI GOLD SPARY 60ML', 'productPool/1.jpg', 120 ),
( 'MUSK OUDH 50ML', 'productPool/1.jpg', 262 ),
( 'MUSK OUDH LOVEZY PARFUM 50ML', 'productPool/1.jpg', 271 ),
( 'MUSK OUDH LOVEZY ROLL ON 6ML', 'productPool/1.jpg', 219 ),
( 'MUSK PKT PERFUME 101 FOLLOW 20ML', 'productPool/1.jpg', 31 ),
( 'MUSK PKT PERFUME 202 SWEETY 20ML', 'productPool/1.jpg', 50 ),
( 'MUSK PKT PERFUME 303 SHABA 20ML', 'productPool/1.jpg', 217 ),
( 'MUSK PKT PERFUME 404 RICH 20ML', 'productPool/1.jpg', 76 ),
( 'MUSK POOMULLA ROLL 3ML', 'productPool/1.jpg', 24 ),
( 'MUSK POOMULLA ROLL 8ML', 'productPool/1.jpg', 168 ),
( 'MUSK POOMULLA SPARY 50ML', 'productPool/1.jpg', 97 ),
( 'MUSK SANDAL 3ML', 'productPool/1.jpg', 25 ),
( 'MUSK SANDAL DEO 50ML', 'productPool/1.jpg', 35 ),
( 'MUSK SANDAL ROLL 3ML', 'productPool/1.jpg', 54 ),
( 'MUSK SANDAL ROLL 8M', 'productPool/1.jpg', 62 ),
( 'MUSK SHAIMA SPRAY 15ML', 'productPool/1.jpg', 234 ),
( 'MUSK SHAIMA SPRAY 50ML', 'productPool/1.jpg', 226 ),
( 'MUSK SIMRA ROLL ON 3ML', 'productPool/1.jpg', 273 ),
( 'MUSK SIMRA SPARY 50ML', 'productPool/1.jpg', 10 ),
( 'MUSK SOLUTIONS 50ML', 'productPool/1.jpg', 146 ),
( 'MUSKAAN BODY SPONGE FLOWER SMALL', 'productPool/1.jpg', 59 ),
( 'MUSKAAN FLOUR SIEVES 4 STEEL PLATE', 'productPool/1.jpg', 5 ),
( 'MUSKAAN FLOUR STRAINER FIX', 'productPool/1.jpg', 278 ),
( 'MUSKAAN GAS SS TROLLY SADA', 'productPool/1.jpg', 162 ),
( 'MUSKAAN SS GAS TROLLY', 'productPool/1.jpg', 85 ),
( 'MUSKAAN TEA STRAINER NO.3 WHITE', 'productPool/1.jpg', 175 ),
( 'MUSKAAN TEA STRAINER NO.4 WHITE', 'productPool/1.jpg', 273 ),
( 'MUSKAAN TEA STRAINER NO.5 WHITE', 'productPool/1.jpg', 116 ),
( 'MUSKAAN TEA STRAINER NO.6 WHITE', 'productPool/1.jpg', 129 ),
( 'MUSKAAN WONDER HANGER', 'productPool/1.jpg', 256 ),
( 'MUSTARD BLACK', 'productPool/1.jpg', 149 ),
( 'MUSTARD OIL 1LTR', 'productPool/1.jpg', 94 ),
( 'MUSTARD OIL 200 ML', 'productPool/1.jpg', 76 ),
( 'MUSTARD OIL 500ML', 'productPool/1.jpg', 159 ),
( 'MUTHIRA 500G', 'productPool/1.jpg', 61 ),
( 'MUTHIRA PREMIUM 500GMS', 'productPool/1.jpg', 33 ),
( 'MXIED FRUIT JAM 1KG', 'productPool/1.jpg', 94 ),
( 'MY CLEAR BAG DP932F', 'productPool/1.jpg', 57 ),
( 'MY CLEAR BAG DP935F', 'productPool/1.jpg', 107 ),
( 'MY CLEAR BAG MC908F', 'productPool/1.jpg', 142 ),
( 'MY CLEAR BAG MC916F', 'productPool/1.jpg', 132 ),
( 'MY CLEAR BAG MC919F', 'productPool/1.jpg', 58 ),
( 'MY CLEAR BAG MC923F', 'productPool/1.jpg', 211 ),
( 'MY CLEAR BAG MC926F', 'productPool/1.jpg', 182 ),
( 'MY CLEAR BAG MC936F', 'productPool/1.jpg', 278 ),
( 'MYCLEAR BAG DP928F', 'productPool/1.jpg', 133 ),
( 'MYLANJI RS15', 'productPool/1.jpg', 257 ),
( 'MYLANJI RS20', 'productPool/1.jpg', 93 ),
( 'MYSOAP JASMINE MILK 100G*5', 'productPool/1.jpg', 238 ),
( 'MYSOAP ROSE MILK 100G*5', 'productPool/1.jpg', 80 ),
( 'MYSORE CARBOLIC HYG 150G', 'productPool/1.jpg', 145 ),
( 'MYSORE SAND BABY SOAP 75G', 'productPool/1.jpg', 93 ),
( 'MYSORE SANDAL 125GM', 'productPool/1.jpg', 83 ),
( 'MYSORE SANDAL 150G', 'productPool/1.jpg', 252 ),
( 'MYSORE SANDAL 75GM', 'productPool/1.jpg', 154 ),
( 'MYSORE SANDAL GOLD 125G', 'productPool/1.jpg', 187 ),
( 'MYSORE SANDAL SIR M V AGARBATHIES 100 GMS', 'productPool/1.jpg', 202 ),
( 'MYSORE SANDAL SOAP 3*150G', 'productPool/1.jpg', 249 ),
( 'MYSORE SANDLE JASMINE SOAP 450G', 'productPool/1.jpg', 74 ),
( 'MYTHRI RICE 5KG', 'productPool/1.jpg', 271 ),
( 'N S ADA 200G', 'productPool/1.jpg', 65 ),
( 'N S KAYAM KATTA 100G', 'productPool/1.jpg', 90 ),
( 'N S KAYAM KATTA 50G', 'productPool/1.jpg', 60 ),
( 'N S KAYAM PODI 100G', 'productPool/1.jpg', 151 ),
( 'N.K GOLD JUICE STRAINER NO.4', 'productPool/1.jpg', 9 ),
( 'N.K GOLD JUICE STRAINER NO.8', 'productPool/1.jpg', 27 ),
( 'N.N FOOD DIAMON CUTS 200G', 'productPool/1.jpg', 236 ),
( 'N.N FOOD KUZHALAPPAM 500G', 'productPool/1.jpg', 111 ),
( 'N.N KUZHALAPPAM 200GM', 'productPool/1.jpg', 117 ),
( 'N.S KAYAM PODI 20GM', 'productPool/1.jpg', 126 ),
( 'N.S KAYAM PODI 50G', 'productPool/1.jpg', 24 ),
( 'N2H APPLE CIDER VINEGAR AMLA HONEY 500ML', 'productPool/1.jpg', 104 ),
( 'N2H APPLE CIDER VINEGAR FILTERED 500ML', 'productPool/1.jpg', 208 ),
( 'N2H APPLE CIDER VINEGAR STONE BREAKER 500ML', 'productPool/1.jpg', 105 ),
( 'N2H APPLE CIDER VINEGAR UNFILTERED 500ML', 'productPool/1.jpg', 229 ),
( 'N2H FLAX SEED OIL 100G', 'productPool/1.jpg', 94 ),
( 'N2H PREMIUM FLAX SEED 100G', 'productPool/1.jpg', 126 ),
( 'N2H PREMIUM FLAX SEED 250G', 'productPool/1.jpg', 173 ),
( 'N2H PUMPKIN SEEDS 100G', 'productPool/1.jpg', 199 ),
( 'N2H SUNFLOWER SEEDS 100G', 'productPool/1.jpg', 131 ),
( 'NADA', 'productPool/1.jpg', 57 ),
( 'NADAN EGG', 'productPool/1.jpg', 274 ),
( 'NADAN PAYAR', 'productPool/1.jpg', 52 ),
( 'NADARAJ ALLGRIP PENS', 'productPool/1.jpg', 224 ),
( 'NAFTHALINE BALL', 'productPool/1.jpg', 166 ),
( 'NAGARJUNA RAKTHA CHANDANA SOAP 75G', 'productPool/1.jpg', 144 ),
( 'NAGENDHRA BLACK ELLUNDA 20PCS', 'productPool/1.jpg', 156 ),
( 'NAGENDHRA WHITE ELLUNDA 20PCS', 'productPool/1.jpg', 114 ),
( 'NAGENDRA MIXTURE BAR', 'productPool/1.jpg', 79 ),
( 'NAGENDRA MIXTURE UNDA', 'productPool/1.jpg', 267 ),
( 'NAIL CUTTER IMP', 'productPool/1.jpg', 46 ),
( 'NAIL CUTTER IMP RS 22.50', 'productPool/1.jpg', 159 ),
( 'NAIL CUTTER IMP RS 24', 'productPool/1.jpg', 198 ),
( 'NAIL CUTTER RS 36', 'productPool/1.jpg', 268 ),
( 'NAIL CUTTER RS 65', 'productPool/1.jpg', 89 ),
( 'NAIL CUTTER RS 80', 'productPool/1.jpg', 118 ),
( 'NAIL CUTTER RS18', 'productPool/1.jpg', 53 ),
( 'NAIL CUTTER RS27', 'productPool/1.jpg', 266 ),
( 'NAIL CUTTER RS30', 'productPool/1.jpg', 35 ),
( 'NAIL CUTTER RS88', 'productPool/1.jpg', 197 ),
( 'NAIVEDYA SAMBRANI 12 N', 'productPool/1.jpg', 64 ),
( 'NAMBEESHANS GHEE 50ML', 'productPool/1.jpg', 119 ),
( 'NAMBISAN AGMARK GHEE 1000ML', 'productPool/1.jpg', 231 ),
( 'NAMBISAN GHEE 200Ml', 'productPool/1.jpg', 185 ),
( 'NAMBISAN GHEE 500ML', 'productPool/1.jpg', 277 ),
( 'NAMBISAN GHEE100ML', 'productPool/1.jpg', 252 ),
( 'NAME SLIP', 'productPool/1.jpg', 16 ),
( 'NANDHI INSTANT DHOOP', 'productPool/1.jpg', 249 ),
( 'NANDHINI GOODLIFE 200ML PKT', 'productPool/1.jpg', 15 ),
( 'NANDI CAMPHOR 25 TAB', 'productPool/1.jpg', 120 ),
( 'NANDI CAMPHOR 25 TAB MRP 18', 'productPool/1.jpg', 8 ),
( 'NANDI CAMPHOR 25G', 'productPool/1.jpg', 73 ),
( 'NANDI CAMPHOR 30 TAB', 'productPool/1.jpg', 140 ),
( 'NANDI CAMPHOR 30G', 'productPool/1.jpg', 68 ),
( 'NANDI CAMPHOR 30TAB MRP 35', 'productPool/1.jpg', 137 ),
( 'NANDI CAMPHOR 40 VILLA TAB', 'productPool/1.jpg', 65 ),
( 'NANDI CAMPHOR 40G MRP 35', 'productPool/1.jpg', 109 ),
( 'NANDI CAMPHOR 50 TAB', 'productPool/1.jpg', 109 ),
( 'NANDI CAMPHOR 60 TAB', 'productPool/1.jpg', 135 ),
( 'NANDI SAMBRANI STEM RS 24', 'productPool/1.jpg', 250 ),
( 'NANDINI GOODLIFE 200ML PKT', 'productPool/1.jpg', 133 ),
( 'NANDOS PERI PERI SAUCE HOT 125G', 'productPool/1.jpg', 228 ),
( 'NANDOS PERI PERI SAUCE MEDIUM 125G', 'productPool/1.jpg', 129 ),
( 'NANDOS PERI PERI XX SAUCE HOT 125G', 'productPool/1.jpg', 69 ),
( 'NAPHTHALENEBALLS', 'productPool/1.jpg', 208 ),
( 'NARIYAL PANI COCONUT CANDY', 'productPool/1.jpg', 32 ),
( 'NASCAFE CLASSIC JAR', 'productPool/1.jpg', 248 ),
( 'NATARAJ 10 COLOUR PENCIL', 'productPool/1.jpg', 27 ),
( 'NATARAJ 12 COLOUR PENCILS', 'productPool/1.jpg', 82 ),
( 'NATARAJ 15 CM SCALE', 'productPool/1.jpg', 213 ),
( 'NATARAJ ALL ROUNDER PEN', 'productPool/1.jpg', 191 ),
( 'NATARAJ ALL SPARK PEN', 'productPool/1.jpg', 82 ),
( 'NATARAJ BEST OF LUCK KIT', 'productPool/1.jpg', 176 ),
( 'NATARAJ CLASSIC BLACK PEN', 'productPool/1.jpg', 143 ),
( 'NATARAJ CLASSIC BLUE', 'productPool/1.jpg', 143 ),
( 'NATARAJ COLOUR PENCILE', 'productPool/1.jpg', 113 ),
( 'NATARAJ DEW PEN MRP 5', 'productPool/1.jpg', 196 ),
( 'NATARAJ GEOMETRY BOX MRP 100', 'productPool/1.jpg', 70 ),
( 'NATARAJ GLOW PEN BLUE', 'productPool/1.jpg', 168 ),
( 'NATARAJ HANDY CUTTER', 'productPool/1.jpg', 15 ),
( 'NATARAJ HANDY CUTTER MINI', 'productPool/1.jpg', 88 ),
( 'NATARAJ HANDY CUTTERS', 'productPool/1.jpg', 81 ),
( 'NATARAJ LARGE CUTTER MRP 20', 'productPool/1.jpg', 60 ),
( 'NATARAJ LARGE CUTTER RS 20', 'productPool/1.jpg', 212 ),
( 'NATARAJ MIST PEN 20 NOS', 'productPool/1.jpg', 1 ),
( 'NATARAJ PENCIL40R', 'productPool/1.jpg', 54 ),
( 'NATARAJ PENS BOTTLE 100 PCS', 'productPool/1.jpg', 219 ),
( 'NATARAJ PLASTO ERASER 621', 'productPool/1.jpg', 101 ),
( 'NATARAJ RUBBER TIPPED WRITING PENCILS', 'productPool/1.jpg', 72 ),
( 'NATARAJ SCALE 15 CM', 'productPool/1.jpg', 129 ),
( 'NATARAJ SCALE 30 CM', 'productPool/1.jpg', 135 ),
( 'NATARAJ SUPERX PEN', 'productPool/1.jpg', 26 ),
( 'NATARAJ SURFER PEN BLUE', 'productPool/1.jpg', 247 ),
( 'NATU ALO VERA MOIS GEL 150G', 'productPool/1.jpg', 94 ),
( 'NATU GOLD CLEAN SCRUB 50G', 'productPool/1.jpg', 17 ),
( 'NATU MINI GOLD FC KIT 52G', 'productPool/1.jpg', 106 ),
( 'NATURA DIET SUGAR FREE 80G', 'productPool/1.jpg', 132 ),
( 'NATURA SUGAR FREE GOLD SACHET 100X0.75G', 'productPool/1.jpg', 175 ),
( 'NATURAA COCOM FRUIT SARBATH 500ML', 'productPool/1.jpg', 130 ),
( 'NATURAA GINGER SARBATH 500ML', 'productPool/1.jpg', 41 ),
( 'NATURAA GRAPE SARBATH 500ML', 'productPool/1.jpg', 251 ),
( 'NATURAA NANNRI SARBATH 500ML', 'productPool/1.jpg', 168 ),
( 'NATURAL LEMON GRASS OIL 30ML', 'productPool/1.jpg', 221 ),
( 'NATURAL LIME PICKLE 250G', 'productPool/1.jpg', 236 ),
( 'NATURAL MIX MASALA', 'productPool/1.jpg', 67 ),
( 'NATURE POWER BEAUTY SOAP 125G', 'productPool/1.jpg', 150 ),
( 'NATURE POWER BEAUTY SOAP LIME 100G', 'productPool/1.jpg', 49 ),
( 'NATURE POWER BEAUTY SOAP SANDAL 125G', 'productPool/1.jpg', 129 ),
( 'NATURE POWER PAPAYA SOAP', 'productPool/1.jpg', 31 ),
( 'NATURE POWER ROSE SOAP 100G', 'productPool/1.jpg', 19 ),
( 'NATURE POWER SANDAL BATH SOAP 200G', 'productPool/1.jpg', 52 ),
( 'NATURE POWER SANDAL SOAP 100G', 'productPool/1.jpg', 126 ),
( 'NATURES ACNE MAGIC CREAM 30G', 'productPool/1.jpg', 122 ),
( 'NATURES ACNE MAGIC FACE WASH 60ML', 'productPool/1.jpg', 24 ),
( 'NATURES ACT OXY GEL FACE CREAM 50G', 'productPool/1.jpg', 98 ),
( 'NATURES ACTIVE CHARCOAL FACE PACK 175G', 'productPool/1.jpg', 57 ),
( 'NATURES ACTIVE CHARCOAL FACE PACK 75G', 'productPool/1.jpg', 269 ),
( 'NATURES ACTIVE CHARCOAL FACE SCRUB 150ML', 'productPool/1.jpg', 74 ),
( 'NATURES ACTIVE CHARCOAL FACE SCRUB 60G', 'productPool/1.jpg', 28 ),
( 'NATURES ACTIVE CHARCOAL FACE WASH 150ML', 'productPool/1.jpg', 198 ),
( 'NATURES ACTIVE CHARCOAL PEEL OFF MASK 60ML', 'productPool/1.jpg', 160 ),
( 'NATURES AGE DEFENSE CREAM', 'productPool/1.jpg', 151 ),
( 'NATURES ALMOND & HONEY BODY LOTION 200ML', 'productPool/1.jpg', 255 ),
( 'NATURES ALMOND & HONEYBODY LOTION 100ML', 'productPool/1.jpg', 22 ),
( 'NATURES ALMOND &HONEY BODY LOTION 100ML', 'productPool/1.jpg', 46 ),
( 'NATURES ALMOND &HONEY BODY LOTION 400ML', 'productPool/1.jpg', 119 ),
( 'NATURES ALMOND HONEY BODY LOTION 200ML', 'productPool/1.jpg', 265 ),
( 'NATURES ALMOND HONEY CREAM 100G', 'productPool/1.jpg', 223 ),
( 'NATURES ALMOND HONEY CREAM 200G', 'productPool/1.jpg', 94 ),
( 'NATURES ALMOND HONEY CREAM 80G', 'productPool/1.jpg', 62 ),
( 'NATURES ALMONDS HONEY BODY LOTION 400ML', 'productPool/1.jpg', 210 ),
( 'NATURES ALOE VERA GEL100G', 'productPool/1.jpg', 6 ),
( 'NATURES ALOE VERA GEL150G', 'productPool/1.jpg', 40 ),
( 'NATURES ALOEVERA BATH SOAP 75G', 'productPool/1.jpg', 189 ),
( 'NATURES ALOEVERA MOISTURISING BAR75G', 'productPool/1.jpg', 130 ),
( 'NATURES ALOEVERA MOISTURISING GEL 50G', 'productPool/1.jpg', 155 ),
( 'NATURES ALOEVERA MOISTURISING GEL100G', 'productPool/1.jpg', 54 ),
( 'NATURES ANCE FACE WASH 60ML', 'productPool/1.jpg', 98 ),
( 'NATURES APPLE FACE PACK 60G', 'productPool/1.jpg', 161 ),
( 'NATURES APPLE PACK 60G', 'productPool/1.jpg', 155 ),
( 'NATURES APRICOT & PEACH SCRUB 60G', 'productPool/1.jpg', 82 ),
( 'NATURES APRICOT SCRUB 120G', 'productPool/1.jpg', 94 ),
( 'NATURES BRIDAL PACK 60G', 'productPool/1.jpg', 62 ),
( 'NATURES CARTENE HAIR OIL 100G', 'productPool/1.jpg', 276 ),
( 'NATURES CHARCOAL FACE WASH 60ML', 'productPool/1.jpg', 186 ),
( 'NATURES CHARCOAL FACEWASH 150ML', 'productPool/1.jpg', 76 ),
( 'NATURES CHARCOAL SCRUB 150G', 'productPool/1.jpg', 21 ),
( 'NATURES CONDITIONER ORANGE LIME 200ML', 'productPool/1.jpg', 265 ),
( 'NATURES CUTIE BUTIE CHOCOLATE 4G', 'productPool/1.jpg', 166 ),
( 'NATURES CUTIE BUTIE LIP BALM VANILA', 'productPool/1.jpg', 169 ),
( 'NATURES DARK CIRCLE EYE CREAM', 'productPool/1.jpg', 137 ),
( 'NATURES DARK CIRCLE EYE CREAM 50G', 'productPool/1.jpg', 83 ),
( 'NATURES DIAMND BLEACH 43G', 'productPool/1.jpg', 76 ),
( 'NATURES DIAMOND BLEACH 43G', 'productPool/1.jpg', 36 ),
( 'NATURES DIAMOND FACIAL KIT 60ML', 'productPool/1.jpg', 43 ),
( 'NATURES FRUIT BLEACH 30G', 'productPool/1.jpg', 61 ),
( 'NATURES FRUIT BLEACH 43G', 'productPool/1.jpg', 205 ),
( 'NATURES FRUIT BLEACH 50G', 'productPool/1.jpg', 110 ),
( 'NATURES FRUIT BLEACH CREAM 20G', 'productPool/1.jpg', 151 ),
( 'NATURES FRUIT FACIAL KIT', 'productPool/1.jpg', 190 ),
( 'NATURES GOLD BLEACH 20G', 'productPool/1.jpg', 154 ),
( 'NATURES GOLD BLEACH 43G', 'productPool/1.jpg', 49 ),
( 'NATURES GOLD BLEACH 85G', 'productPool/1.jpg', 18 ),
( 'NATURES GOLD BLEACH CREAM 85G', 'productPool/1.jpg', 232 ),
( 'NATURES GOLD BLEACH20G', 'productPool/1.jpg', 269 ),
( 'NATURES GOLD FACE WASH 100ML', 'productPool/1.jpg', 90 ),
( 'NATURES GOLD ILLUMINATING FACE WASH 60ML', 'productPool/1.jpg', 211 ),
( 'NATURES GOLD ILLUMINATING FACEWASH 100ML', 'productPool/1.jpg', 144 ),
( 'NATURES GOLD MASSAGE GEL RS 200', 'productPool/1.jpg', 69 ),
( 'NATURES GOLD PACK', 'productPool/1.jpg', 147 ),
( 'NATURES GOLDEN AGE DEFENSE CREAM 50G', 'productPool/1.jpg', 42 ),
( 'NATURES HAIR COLOR BLACK 15G', 'productPool/1.jpg', 174 ),
( 'NATURES HAIR COLOR BURGUNDY 15G', 'productPool/1.jpg', 265 ),
( 'NATURES HAIR HENNA CARE 15G', 'productPool/1.jpg', 276 ),
( 'NATURES HAIR SHINE SERUM 50ML', 'productPool/1.jpg', 193 ),
( 'NATURES HENNA HAIR COLOR BLACK 15G', 'productPool/1.jpg', 94 ),
( 'NATURES HENNA PLUS 100G', 'productPool/1.jpg', 226 ),
( 'NATURES INTENSIVE EYE TREATMENT RS 399', 'productPool/1.jpg', 21 ),
( 'NATURES KESH VISHESH HERBAL OIL 100ML', 'productPool/1.jpg', 81 ),
( 'NATURES LACTO BLEACH', 'productPool/1.jpg', 99 ),
( 'NATURES LACTO BLEACH MILK&HONEY 50G', 'productPool/1.jpg', 146 ),
( 'NATURES LACTO TAN CLEAR 100G', 'productPool/1.jpg', 57 ),
( 'NATURES LACTO TAN CLEAR 50G', 'productPool/1.jpg', 59 ),
( 'NATURES MAGIC AYACNE POWFP 15G', 'productPool/1.jpg', 59 ),
( 'NATURES MAGIC HENNA CARE 15G', 'productPool/1.jpg', 65 ),
( 'NATURES MASSAGE OIL ORANGE LIME 200ML', 'productPool/1.jpg', 144 ),
( 'NATURES MATT IFYING DAY CREAM', 'productPool/1.jpg', 121 ),
( 'NATURES MATTIFYING DAY CREAM 50G', 'productPool/1.jpg', 271 ),
( 'NATURES MINI DIAMOND FACIAL KIT', 'productPool/1.jpg', 100 ),
( 'NATURES MINI DIAMOND FACIAL KIT 52G+60ML', 'productPool/1.jpg', 240 ),
( 'NATURES MINI GOLD KIT', 'productPool/1.jpg', 71 ),
( 'NATURES MINT CLEANSER 100G', 'productPool/1.jpg', 226 ),
( 'NATURES MINT CLEANSER 40G', 'productPool/1.jpg', 95 ),
( 'NATURES NEEM & ALOEVERA FACE WASH 65ML', 'productPool/1.jpg', 24 ),
( 'NATURES NEEM & ALOEVERA SHAMPOO 80ML', 'productPool/1.jpg', 105 ),
( 'NATURES NEEM ALO VERA CONDIONER 60ML', 'productPool/1.jpg', 216 ),
( 'NATURES NEEM ALOE VERA FACE WASH 65ML', 'productPool/1.jpg', 50 ),
( 'NATURES NEEM ALOEVERA MOIST LOTION 300ML', 'productPool/1.jpg', 109 ),
( 'NATURES NEEM AND ALOEVERA FACE WASH 65ML', 'productPool/1.jpg', 209 ),
( 'NATURES NEEM AND ALOEVERA LOTION 100ML', 'productPool/1.jpg', 156 ),
( 'NATURES NEEM AND ALOEVERA SHAMPOO 150ML', 'productPool/1.jpg', 212 ),
( 'NATURES ORANGE BODY BUTTER 200G', 'productPool/1.jpg', 237 ),
( 'NATURES ORANGE D TAN FACE WASH 60ML', 'productPool/1.jpg', 130 ),
( 'NATURES ORANGE D TAN SCRUB 60G', 'productPool/1.jpg', 117 ),
( 'NATURES ORANGE LIME FACEWASH 150ML', 'productPool/1.jpg', 213 ),
( 'NATURES ORANGE LIME YOGURT HAIR SMOOTHIE 200G', 'productPool/1.jpg', 193 ),
( 'NATURES ORANGE N LIME BODY LOTION 200ML', 'productPool/1.jpg', 160 ),
( 'NATURES ORANGE N LIME BODYWASH 200ML', 'productPool/1.jpg', 122 ),
( 'NATURES ORANGE N LIME D TAN SCRUB 150G', 'productPool/1.jpg', 42 ),
( 'NATURES ORANGE N LIME FOOT CREAM 60G', 'productPool/1.jpg', 253 ),
( 'NATURES ORANGE N LIME MOIST 200ML', 'productPool/1.jpg', 1 ),
( 'NATURES ORIENTAL ORANGE HAND CREAM 60G', 'productPool/1.jpg', 209 ),
( 'NATURES OXY BLEACH', 'productPool/1.jpg', 9 ),
( 'NATURES PAPAYA CREAM', 'productPool/1.jpg', 189 ),
( 'NATURES PAPAYA CREAM 50G', 'productPool/1.jpg', 237 ),
( 'NATURES PAPAYA FACIAL KIT', 'productPool/1.jpg', 3 ),
( 'NATURES PAPAYA FACIAL KIT MINI 52G+65ML', 'productPool/1.jpg', 221 ),
( 'NATURES PAPAYA PACK', 'productPool/1.jpg', 58 ),
( 'NATURES PAPAYA PACK 60G', 'productPool/1.jpg', 204 ),
( 'NATURES PEARL KIT MINI 52G', 'productPool/1.jpg', 216 ),
( 'NATURES PERAL BLEACH 85G', 'productPool/1.jpg', 140 ),
( 'NATURES PERFECT PAPAYA FACE WASH 65ML', 'productPool/1.jpg', 191 ),
( 'NATURES PIGMENTATION PAPAYA FACEWASH 65ML', 'productPool/1.jpg', 14 ),
( 'NATURES PINK FLOWER LOTION 125ML', 'productPool/1.jpg', 26 ),
( 'NATURES RAVISHING GOLD MASSAGE CREAM 50G', 'productPool/1.jpg', 8 ),
( 'NATURES RAVISHING GOLD SCRUB 50G', 'productPool/1.jpg', 190 ),
( 'NATURES REGENERATING FIRMING CREAM 50G', 'productPool/1.jpg', 126 ),
( 'NATURES SAFFRON CARE CREAM 50G', 'productPool/1.jpg', 277 ),
( 'NATURES SAFFRON SOAP 75G', 'productPool/1.jpg', 161 ),
( 'NATURES SEN GOLD ILLU FACE WASH 60ML', 'productPool/1.jpg', 92 ),
( 'NATURES SHAMPOO ORANGE LIME 200ML', 'productPool/1.jpg', 68 ),
( 'NATURES SNOW WHITE SALSA LOTION 100ML', 'productPool/1.jpg', 165 ),
( 'NATURES SOFT TOUCH DIAMOND 50G', 'productPool/1.jpg', 132 ),
( 'NATURES SOFT TOUCH GOLD 50G', 'productPool/1.jpg', 139 ),
( 'NATURES SOFT TOUCH LEMON 50G', 'productPool/1.jpg', 157 ),
( 'NATURES SOFT TOUCH ROSE', 'productPool/1.jpg', 138 ),
( 'NATURES SPOT REDUCTION BRIGHTNESS CREAM', 'productPool/1.jpg', 272 ),
( 'NATURES SPOT REDUCTION BRIGHTNESS CREAM 50G', 'productPool/1.jpg', 19 ),
( 'NATURES STRAWBERRY FACE WASH 100ML', 'productPool/1.jpg', 251 ),
( 'NATURES STRAWBERRY SKIN TONER 200ML', 'productPool/1.jpg', 223 ),
( 'NATURES STRAWBERY CLEANSING LOTION 200ML', 'productPool/1.jpg', 158 ),
( 'NATURES STRAWBERY LIP BALM', 'productPool/1.jpg', 163 ),
( 'NATURES STY LON HARD GEL', 'productPool/1.jpg', 161 ),
( 'NATURES STY LON WET LOOK GEL', 'productPool/1.jpg', 141 ),
( 'NATURES SUN BAN INTENSE SPF 60 60G', 'productPool/1.jpg', 207 ),
( 'NATURES SUN BAN LOTION SPF 40 60ML', 'productPool/1.jpg', 254 ),
( 'NATURES SUN BAN SPF 40 120ML', 'productPool/1.jpg', 39 ),
( 'NATURES SUN BAN SUNCREAM 40G', 'productPool/1.jpg', 268 ),
( 'NATURES SUN BAN SUNSCREEN CREAM 40G', 'productPool/1.jpg', 268 ),
( 'NATURES SUN BANS PROTECTION FACE 30 60ML', 'productPool/1.jpg', 65 ),
( 'NATURES SUNBAN SPF 30 LOTION 120ML', 'productPool/1.jpg', 151 ),
( 'NATURES SUNBAN SPF 60 60ML', 'productPool/1.jpg', 252 ),
( 'NATURES SUNBAN SUNSCREEN LOTION 60ML', 'productPool/1.jpg', 144 ),
( 'NATURES SUNBANSPF40 120ML', 'productPool/1.jpg', 127 ),
( 'NATURES SUNBNSU CR LOTNSPF30 120ML', 'productPool/1.jpg', 76 ),
( 'NATURES SWISS ANTI RASH CREAM 60G', 'productPool/1.jpg', 26 ),
( 'NATURES SWISS STRAWBERRY SKIN TONER 200ML', 'productPool/1.jpg', 114 ),
( 'NATURES SWISS STRAWBERY ANTI TAN CREAM PACK 150G', 'productPool/1.jpg', 70 ),
( 'NATURES SWISS STRAWBERY FACE SERUM 25ML', 'productPool/1.jpg', 77 ),
( 'NATURES SWISS STRAWBERY FACEWASH 150ML', 'productPool/1.jpg', 228 ),
( 'NATURES SWISS STRAWBERY MOIST LOTION 200ML', 'productPool/1.jpg', 146 ),
( 'NATURES SWISS STRAWBERY SERUM 25ML', 'productPool/1.jpg', 197 ),
( 'NATURES SWISS STRAWBERY SUGAR SCRUB 60G', 'productPool/1.jpg', 220 ),
( 'NATURES WONDER PAPAYA SOAP 75G', 'productPool/1.jpg', 138 ),
( 'NATURTES ACTIVE CHARCOAL PEEL OFF MASK 150G', 'productPool/1.jpg', 246 ),
( 'NAUGHTY GIRL CHARM PERFUME SPRAY 135ML', 'productPool/1.jpg', 150 ),
( 'NAUGHTY GIRL CHARM PERFUME SPRAY 150ML', 'productPool/1.jpg', 98 ),
( 'NAUGHTY GIRL CHARM PERFUME SPRAY 60ML', 'productPool/1.jpg', 198 ),
( 'NAUGHTY GIRL CRYSTAL PERFUME SPRAY 150ML', 'productPool/1.jpg', 201 ),
( 'NAUGHTY GIRL CRYSTAL PERFUME SPRAY 60ML', 'productPool/1.jpg', 205 ),
( 'NAUGHTY GIRL DEO CRYSTAL 135ML', 'productPool/1.jpg', 145 ),
( 'NAUGHTY GIRL DEO OFFER PACK 3PCS', 'productPool/1.jpg', 241 ),
( 'NAUGHTY GIRL DEO TOUCH135ML', 'productPool/1.jpg', 215 ),
( 'NAUGHTY GIRL ECHO PERFUME SPRAY 135ML', 'productPool/1.jpg', 185 ),
( 'NAUGHTY GIRL ECHO PERFUME SPRAY 150ML', 'productPool/1.jpg', 183 ),
( 'NAUGHTY GIRL ECHO PERFUME SPRAY 60ML', 'productPool/1.jpg', 58 ),
( 'NAUGHTY GIRL FASHION PERFUME SPRAY 135ML', 'productPool/1.jpg', 93 ),
( 'NAUGHTY GIRL FASHION PERFUME SPRAY 150ML', 'productPool/1.jpg', 231 ),
( 'NAUGHTY GIRL FASHION PERFUME SPRAY 60ML', 'productPool/1.jpg', 61 ),
( 'NAUGHTY GIRL FEMME PERFUME SPRAY 135ML', 'productPool/1.jpg', 155 ),
( 'NAUGHTY GIRL FEMME PERFUME SPRAY 150ML', 'productPool/1.jpg', 20 ),
( 'NAUGHTY GIRL FEMME PERFUME SPRAY 60ML', 'productPool/1.jpg', 155 ),
( 'NAUGHTY GIRL SUMMER PERFUME SPRAY 135ML', 'productPool/1.jpg', 225 ),
( 'NAUGHTY GIRL SUMMER PERFUME SPRAY 150ML', 'productPool/1.jpg', 32 ),
( 'NAUGHTY GIRL SUMMER PERFUME SPRAY 60ML', 'productPool/1.jpg', 213 ),
( 'NAUGHTY GIRL TOUCH PERFUME SPRAY 150ML', 'productPool/1.jpg', 170 ),
( 'NAUGHTY GIRL TOUCH PERFUME SPRAY 60ML', 'productPool/1.jpg', 262 ),
( 'NAVANAKISTRA BLEND TEA', 'productPool/1.jpg', 157 ),
( 'NAVARA RICE 500G', 'productPool/1.jpg', 279 ),
( 'NAVARATNA COOL TALC MINT FRESH 100G', 'productPool/1.jpg', 166 ),
( 'NAVARATNA OIL 300 ML', 'productPool/1.jpg', 90 ),
( 'NAVARATNA OIL 500 ML', 'productPool/1.jpg', 38 ),
( 'NAVIGATOR BRUSH', 'productPool/1.jpg', 121 ),
( 'NAVJYOTI LPG HOSE', 'productPool/1.jpg', 46 ),
( 'NAVRATHA COOL ORANGE 100G', 'productPool/1.jpg', 250 ),
( 'NAVRATNA ALMOND OIL 100ML', 'productPool/1.jpg', 98 ),
( 'NAVRATNA COOL TALC FLORAL FREEZE 100G', 'productPool/1.jpg', 204 ),
( 'NAVRATNA COOL TALC MINT & CAMPHOR', 'productPool/1.jpg', 204 ),
( 'NAVRATNA I COOL TALC 100G', 'productPool/1.jpg', 31 ),
( 'NAYANAAM BEETROOT MURUKKU 170 G', 'productPool/1.jpg', 26 ),
( 'NAYANAM ACHAPPAM 100G', 'productPool/1.jpg', 98 ),
( 'NAYANAM BEETROOT PAKKAVADA 130 G', 'productPool/1.jpg', 96 ),
( 'NAYANAM CARROT PAKKAVADA 130G', 'productPool/1.jpg', 222 ),
( 'NAYANAM KANTHARI MIXTURE 170 G', 'productPool/1.jpg', 238 ),
( 'NAYANAM KANTHARI PAKKAVADA 130G', 'productPool/1.jpg', 266 ),
( 'NAYANAM MULLU MURUKKU170G', 'productPool/1.jpg', 229 ),
( 'NAYANAM MUTHIRA MURUKKU 160G', 'productPool/1.jpg', 182 ),
( 'NAYANAM ONION PAKKAVADA 170 G', 'productPool/1.jpg', 22 ),
( 'NAYANANM SPRILL MURUKKU 160 G', 'productPool/1.jpg', 153 ),
( 'NC DIGESTIVE ZERO PP 100G', 'productPool/1.jpg', 2 ),
( 'NEEDLE', 'productPool/1.jpg', 17 ),
( 'NEEDLE COMPACT', 'productPool/1.jpg', 250 ),
( 'NEEDLE RS 7', 'productPool/1.jpg', 242 ),
( 'NEELI BHRINGADI 450ML', 'productPool/1.jpg', 238 ),
( 'NEELI BHRINGADI OIL 100ML', 'productPool/1.jpg', 255 ),
( 'NEELI COCONUT OIL 200 ML', 'productPool/1.jpg', 201 ),
( 'NEELIBHRINGADHI COCOUNT OIL 450 ML', 'productPool/1.jpg', 2 ),
( 'NEELU BOTTLE OPENER', 'productPool/1.jpg', 224 ),
( 'NEELU LEMON SQEEZER', 'productPool/1.jpg', 18 ),
( 'NEEM ACTIVE TOOTH PASTE 125G', 'productPool/1.jpg', 215 ),
( 'NEEM ACTIVE TOOTHPASTE 200G', 'productPool/1.jpg', 58 ),
( 'NEEM FACE WASH 50ML', 'productPool/1.jpg', 184 ),
( 'NEEM SKINTONER100ML', 'productPool/1.jpg', 138 ),
( 'NEEMACT DOG SHAMPOO 100ML', 'productPool/1.jpg', 108 ),
( 'NEERAJA KODI COLOR LIQUID 100G', 'productPool/1.jpg', 60 ),
( 'NEERAJA LIQUID KHADI WHITENER 500G', 'productPool/1.jpg', 82 ),
( 'NEERAJA LIQUID STIFFNER 500G', 'productPool/1.jpg', 102 ),
( 'NEERMARUTHUVA TEA 20G', 'productPool/1.jpg', 95 ),
( 'NEHA COOK N SAVE', 'productPool/1.jpg', 197 ),
( 'NESCAFE CHILLED LATTE 180ML', 'productPool/1.jpg', 35 ),
( 'NESCAFE CLASSIC 100G', 'productPool/1.jpg', 266 ),
( 'NESCAFE CLASSIC 100G IMP', 'productPool/1.jpg', 159 ),
( 'NESCAFE CLASSIC 200G', 'productPool/1.jpg', 198 ),
( 'NESCAFE CLASSIC 25G JAR', 'productPool/1.jpg', 59 ),
( 'NESCAFE CLASSIC 50G IMP', 'productPool/1.jpg', 20 ),
( 'NESCAFE CLASSIC 50G SACHET', 'productPool/1.jpg', 29 ),
( 'NESCAFE CLASSIC COFFEE KIT 50G', 'productPool/1.jpg', 22 ),
( 'NESCAFE CLASSIC JAR 200g', 'productPool/1.jpg', 170 ),
( 'NESCAFE CLASSIC JAR 50G', 'productPool/1.jpg', 129 ),
( 'NESCAFE GOLD 150G PKT', 'productPool/1.jpg', 120 ),
( 'NESCAFE GOLD DECAF 100G', 'productPool/1.jpg', 233 ),
( 'NESCAFE HAZELNUT180ML', 'productPool/1.jpg', 201 ),
( 'NESCAFE INTENSE CAFE180ML', 'productPool/1.jpg', 46 ),
( 'NESCAFE LATTE CUP 25G', 'productPool/1.jpg', 20 ),
( 'NESCAFE MATINAL 200G', 'productPool/1.jpg', 270 ),
( 'NESCAFE SUNRISE 100G MUG FREE', 'productPool/1.jpg', 66 ),
( 'NESCAFE SUNRISE 200G', 'productPool/1.jpg', 224 ),
( 'NESCAFE SUNRISE 50G JAR', 'productPool/1.jpg', 116 ),
( 'NESCAFE SUNRISE EXTRA 5*200G', 'productPool/1.jpg', 190 ),
( 'NESCAFE SUNRISE JAR 100G', 'productPool/1.jpg', 4 ),
( 'NESCAFE SUNRISE SACHET 50G', 'productPool/1.jpg', 243 ),
( 'NESTEL KITKAT 7GM RS5', 'productPool/1.jpg', 236 ),
( 'NESTLE ALPINO BITTER SWEET CHOCOLATE 90G', 'productPool/1.jpg', 171 ),
( 'NESTLE ALPINO CHOCOLATE 23G', 'productPool/1.jpg', 43 ),
( 'NESTLE ALPINO DARK CHOCOLATE 90G', 'productPool/1.jpg', 22 ),
( 'NESTLE ALPINO VERY MILKY CHOCOLATE 90G', 'productPool/1.jpg', 244 ),
( 'NESTLE BAR ONE 15G', 'productPool/1.jpg', 201 ),
( 'NESTLE BAR ONE 22G', 'productPool/1.jpg', 68 ),
( 'NESTLE BAR ONE 40G', 'productPool/1.jpg', 173 ),
( 'NESTLE BAR ONE CHOCLATE 24.2G', 'productPool/1.jpg', 273 ),
( 'NESTLE BAR ONE CHOCLATE 40G', 'productPool/1.jpg', 165 ),
( 'NESTLE BAR ONE CHOCOLATE 27.5G', 'productPool/1.jpg', 274 ),
( 'NESTLE BAR ONE DUBLE 40G', 'productPool/1.jpg', 3 ),
( 'NESTLE BAR ONE NOUGAT-CARAMEL 24.2G', 'productPool/1.jpg', 63 ),
( 'NESTLE BARONE 27.5GM', 'productPool/1.jpg', 184 ),
( 'NESTLE BARONE CHOCOLATE 27.5G', 'productPool/1.jpg', 192 ),
( 'NESTLE CERCLAC WHEAT HONEY DATES 300G', 'productPool/1.jpg', 54 ),
( 'NESTLE CEREGROW 2-5 YEARS', 'productPool/1.jpg', 159 ),
( 'NESTLE CEREGROW 300G', 'productPool/1.jpg', 276 ),
( 'NESTLE CEREGROW 300G BOWL FREE', 'productPool/1.jpg', 116 ),
( 'NESTLE CERELAC 5 GRAINS AND FRUITS 300G', 'productPool/1.jpg', 48 ),
( 'NESTLE CERELAC MULTIGRAIN DAL VEG', 'productPool/1.jpg', 95 ),
( 'NESTLE CERELAC MULTIGRAIN FRUITS 300G', 'productPool/1.jpg', 176 ),
( 'NESTLE CERELAC RAGI APPLE STAGE2 300G', 'productPool/1.jpg', 69 ),
( 'NESTLE CERELAC RICE 300G', 'productPool/1.jpg', 219 ),
( 'NESTLE CERELAC RICE VEGETABLES 300G', 'productPool/1.jpg', 269 ),
( 'NESTLE CERELAC STAGE2 WHEAT APPLE CHERY 300G', 'productPool/1.jpg', 211 ),
( 'NESTLE CERELAC WHEAT 300G', 'productPool/1.jpg', 17 ),
( 'NESTLE CERELAC WHEAT APPLE 300G', 'productPool/1.jpg', 182 ),
( 'NESTLE CERELAC WHEAT APPLE CHERRY STAGE 2', 'productPool/1.jpg', 255 ),
( 'NESTLE CERELAC WHEAT APPLE STAGE 1', 'productPool/1.jpg', 166 ),
( 'NESTLE CERELAC WHEAT HONEY DATES 300G', 'productPool/1.jpg', 241 ),
( 'NESTLE CERELAC WHEAT ORANGE 300G', 'productPool/1.jpg', 28 ),
( 'NESTLE CERELAC WHEAT ORANGE STAGE 2', 'productPool/1.jpg', 196 ),
( 'NESTLE CERELAC WHEAT RICE MIXED FRUIT 300G', 'productPool/1.jpg', 242 ),
( 'NESTLE CERELAC WHEAT RICE MIXED VEG', 'productPool/1.jpg', 138 ),
( 'NESTLE CERELACK FRUITS STAGE 4', 'productPool/1.jpg', 59 ),
( 'NESTLE CERELACK WHEAT STAGE 1', 'productPool/1.jpg', 33 ),
( 'NESTLE CLASSIC 34G', 'productPool/1.jpg', 225 ),
( 'NESTLE CLASSIC CHOCLATE 37.4G', 'productPool/1.jpg', 210 ),
( 'NESTLE CLASSIC10 CHOCLATE', 'productPool/1.jpg', 158 ),
( 'NESTLE COFFEE MATE 400G PKT', 'productPool/1.jpg', 70 ),
( 'NESTLE EVERY DAY 200G', 'productPool/1.jpg', 267 ),
( 'NESTLE EVERYDAY 100G', 'productPool/1.jpg', 102 ),
( 'NESTLE EVERYDAY 1KG', 'productPool/1.jpg', 269 ),
( 'NESTLE EVERYDAY 200G', 'productPool/1.jpg', 194 ),
( 'NESTLE EVERYDAY 400G', 'productPool/1.jpg', 82 ),
( 'NESTLE EVERYDAY MILK POWDER 200G', 'productPool/1.jpg', 131 ),
( 'NESTLE EVERYDAY MILKPOWDER 1KG', 'productPool/1.jpg', 54 ),
( 'NESTLE EVERYDAY MILKPOWDER 400g', 'productPool/1.jpg', 213 ),
( 'NESTLE EVERYDAY POWDER 1KG', 'productPool/1.jpg', 13 ),
( 'NESTLE FOX FRUIT CHOCOLATE TIN 180G', 'productPool/1.jpg', 213 ),
( 'NESTLE FOXS APPLE CHOCOLATE POUCH 125G POUCH', 'productPool/1.jpg', 170 ),
( 'NESTLE FOXS CRYSTAL MINTS 90G', 'productPool/1.jpg', 212 ),
( 'NESTLE FOXS LEMON CHOCOLATE POUCH 125G', 'productPool/1.jpg', 237 ),
( 'NESTLE GOLD PREIMUM COFE 100G', 'productPool/1.jpg', 239 ),
( 'NESTLE KIT KAT 28.3G MRP 20', 'productPool/1.jpg', 62 ),
( 'NESTLE KIT KAT 4 FINGER', 'productPool/1.jpg', 73 ),
( 'NESTLE KIT KAT 55G MRP40', 'productPool/1.jpg', 38 ),
( 'NESTLE KIT KAT DUO STRAWBERY', 'productPool/1.jpg', 87 ),
( 'NESTLE KIT KAT PARTY PACK', 'productPool/1.jpg', 201 ),
( 'NESTLE KITKAT 13.2G MRP:10', 'productPool/1.jpg', 208 ),
( 'NESTLE KITKAT 18.5G MRP:10', 'productPool/1.jpg', 217 ),
( 'NESTLE KITKAT 18.5G MRP:15', 'productPool/1.jpg', 278 ),
( 'NESTLE KITKAT 18G', 'productPool/1.jpg', 171 ),
( 'NESTLE KITKAT 27.5G 24 PCS', 'productPool/1.jpg', 35 ),
( 'NESTLE KITKAT 28.3G MRP:20', 'productPool/1.jpg', 51 ),
( 'NESTLE KITKAT 37.3G 18 PCS', 'productPool/1.jpg', 236 ),
( 'NESTLE KITKAT 37.3G MRP25', 'productPool/1.jpg', 105 ),
( 'NESTLE KITKAT 37G', 'productPool/1.jpg', 111 ),
( 'NESTLE KITKAT 38.3G', 'productPool/1.jpg', 214 ),
( 'NESTLE KITKAT 7G', 'productPool/1.jpg', 42 ),
( 'NESTLE KITKAT 8.6G', 'productPool/1.jpg', 82 ),
( 'NESTLE KITKAT 8.6G MRP:5', 'productPool/1.jpg', 197 ),
( 'NESTLE KITKAT CHUNKY 40G', 'productPool/1.jpg', 61 ),
( 'NESTLE KITKAT DESERT CHOCO PUDDING 50G', 'productPool/1.jpg', 7 ),
( 'NESTLE KITKAT DESSERT BROWNIE KUBES 50G', 'productPool/1.jpg', 84 ),
( 'NESTLE KITKAT DESSERT CHOCO PUDDING 50G', 'productPool/1.jpg', 268 ),
( 'NESTLE KITKAT DESSERT COMBO 150G', 'productPool/1.jpg', 166 ),
( 'NESTLE KITKAT DESSERT TRUFFLE 50G', 'productPool/1.jpg', 11 ),
( 'NESTLE KITKAT DUO COFFEE 12.8G', 'productPool/1.jpg', 57 ),
( 'NESTLE KITKAT I FINGER MINI', 'productPool/1.jpg', 265 ),
( 'NESTLE KITKAT KOOKIE CREAM PARTY PACK 79.2G', 'productPool/1.jpg', 179 ),
( 'NESTLE KITKAT PARTY PACK 72G', 'productPool/1.jpg', 191 ),
( 'NESTLE KITKAT PARTY PACK 79.2G', 'productPool/1.jpg', 13 ),
( 'NESTLE KITKAT PARTY PACK 92.5G', 'productPool/1.jpg', 56 ),
( 'NESTLE KITKAT WHITE CHUNKY 40G', 'productPool/1.jpg', 31 ),
( 'NESTLE LACTOGEN 1 400G TIN', 'productPool/1.jpg', 80 ),
( 'NESTLE LACTOGEN 1 INFANT FORMULA', 'productPool/1.jpg', 37 ),
( 'NESTLE LACTOGEN 2 400G', 'productPool/1.jpg', 186 ),
( 'NESTLE LACTOGEN 3', 'productPool/1.jpg', 116 ),
( 'NESTLE LACTOGEN 3 400G RF', 'productPool/1.jpg', 98 ),
( 'NESTLE LACTOGEN 4 400G', 'productPool/1.jpg', 212 ),
( 'NESTLE LACTOGEN 4 400G RF', 'productPool/1.jpg', 27 ),
( 'NESTLE LACTOGEN PRO1 400G', 'productPool/1.jpg', 57 ),
( 'NESTLE LACTOGEN PRO1 TIN 400G', 'productPool/1.jpg', 5 ),
( 'NESTLE LACTOGEN STAGE 4', 'productPool/1.jpg', 206 ),
( 'NESTLE MAGGI ATTA NOODLES 290G', 'productPool/1.jpg', 279 ),
( 'NESTLE MAGGI ATTA NOODLES 300G', 'productPool/1.jpg', 273 ),
( 'NESTLE MAGGI CHICKEN CUBES 40G', 'productPool/1.jpg', 34 ),
( 'NESTLE MAGGI CHICKEN CUPPA NOODLES 67G', 'productPool/1.jpg', 101 ),
( 'NESTLE MAGGI CHICKEN NOODLES 284G', 'productPool/1.jpg', 16 ),
( 'NESTLE MAGGI HOT & SWEET SAUCE 500G', 'productPool/1.jpg', 92 ),
( 'NESTLE MAGGI HOT AND SWEET SAUCE 500G', 'productPool/1.jpg', 274 ),
( 'NESTLE MAGGI MASALA NOODLES 420G', 'productPool/1.jpg', 218 ),
( 'NESTLE MAGGI NOODLES MASALA 280G', 'productPool/1.jpg', 1 ),
( 'NESTLE MAGGI PAZZTA CHEESY MACARONI 65G', 'productPool/1.jpg', 129 ),
( 'NESTLE MAGGI PAZZTA CHEESY TOMATO 65G', 'productPool/1.jpg', 87 ),
( 'NESTLE MAGGI PAZZTA MASALA 65G', 'productPool/1.jpg', 168 ),
( 'NESTLE MAGGI PERI PERI CUPPA NOODLES 70G', 'productPool/1.jpg', 70 ),
( 'NESTLE MAGGI TOMATO KETCHUP 500G', 'productPool/1.jpg', 189 ),
( 'NESTLE MAGGI VEG ATTA NOODLES 290G', 'productPool/1.jpg', 21 ),
( 'NESTLE MILK MAID 400G', 'productPool/1.jpg', 46 ),
( 'NESTLE MILKMAID 400G', 'productPool/1.jpg', 248 ),
( 'NESTLE MILKY BAR', 'productPool/1.jpg', 252 ),
( 'NESTLE MILKY BAR 110G WITH PENCIL BOX', 'productPool/1.jpg', 222 ),
( 'NESTLE MILKY BAR CHOO 10G', 'productPool/1.jpg', 241 ),
( 'NESTLE MILKY BAR CHOO MIX FRUIT 11G', 'productPool/1.jpg', 197 ),
( 'NESTLE MILKY BAR ECLAIRS 340G', 'productPool/1.jpg', 26 ),
( 'NESTLE MILKY BAR ECLAIRS 360G', 'productPool/1.jpg', 169 ),
( 'NESTLE MILKY BAR MOOSHA 24G', 'productPool/1.jpg', 59 ),
( 'NESTLE MILKY BAR MOOSHA 40G', 'productPool/1.jpg', 231 ),
( 'NESTLE MILKY BAR MOULD 13.2G', 'productPool/1.jpg', 74 ),
( 'NESTLE MILKY BAR MOULD 13G', 'productPool/1.jpg', 74 ),
( 'NESTLE MILKY BAR MOULD 25G', 'productPool/1.jpg', 43 ),
( 'NESTLE MILKY BAR MULTIPACK 66G', 'productPool/1.jpg', 255 ),
( 'NESTLE MILKYBAR 11G MRP 10', 'productPool/1.jpg', 36 ),
( 'NESTLE MILKYBAR 12.1G', 'productPool/1.jpg', 161 ),
( 'NESTLE MILKYBAR 24 PCS', 'productPool/1.jpg', 163 ),
( 'NESTLE MILKYBAR 25G MRP 20', 'productPool/1.jpg', 261 ),
( 'NESTLE MILKYBAR 27.5G', 'productPool/1.jpg', 200 ),
( 'NESTLE MILKYBAR 6*25G', 'productPool/1.jpg', 23 ),
( 'NESTLE MILKYBAR CHOCO STRAWBEERY 10GM', 'productPool/1.jpg', 190 ),
( 'NESTLE MILKYBAR CHOO 10G', 'productPool/1.jpg', 118 ),
( 'NESTLE MILKYBAR CHOO CHOCOLATE10G', 'productPool/1.jpg', 185 ),
( 'NESTLE MILKYBAR CHOO MIXED FRUIT 10G', 'productPool/1.jpg', 86 ),
( 'NESTLE MILKYBAR CHOO STRAWBERRY 10G', 'productPool/1.jpg', 179 ),
( 'NESTLE MILKYBAR CHOO STRAWBERRY 11G', 'productPool/1.jpg', 38 ),
( 'NESTLE MILKYBAR ECLAIRS 3.04KG JAR', 'productPool/1.jpg', 125 ),
( 'NESTLE MILKYBAR ECLAIRS 320G', 'productPool/1.jpg', 90 ),
( 'NESTLE MILKYBAR ECLAIRS 340G', 'productPool/1.jpg', 98 ),
( 'NESTLE MILKYBAR ECLAIRS 352G', 'productPool/1.jpg', 109 ),
( 'NESTLE MILKYBAR ECLAIRS 360G', 'productPool/1.jpg', 24 ),
( 'NESTLE MILKYBAR ECLAIRS 374G', 'productPool/1.jpg', 28 ),
( 'NESTLE MILKYBAR ECLAIRS 396G', 'productPool/1.jpg', 218 ),
( 'NESTLE MILKYBAR ECLAIRS 414G', 'productPool/1.jpg', 83 ),
( 'NESTLE MILKYBAR FRUITY ECLAIRS JAR 544G', 'productPool/1.jpg', 167 ),
( 'NESTLE MILKYBAR MOOSHA 20G', 'productPool/1.jpg', 55 ),
( 'NESTLE MILKYBAR MOOSHA 40G', 'productPool/1.jpg', 199 ),
( 'NESTLE MILKYBAR MOOSHA 45G', 'productPool/1.jpg', 175 ),
( 'NESTLE MILKYBAR MOULD 14G', 'productPool/1.jpg', 57 ),
( 'NESTLE MILKYBAR MULIT PACK 79.2G', 'productPool/1.jpg', 157 ),
( 'NESTLE MILKYBAR MULTIPACK 84G', 'productPool/1.jpg', 61 ),
( 'NESTLE MILKYBAR MULTY PACK 66G', 'productPool/1.jpg', 56 ),
( 'NESTLE MILKYBAR MULTY PACK 79.2G', 'productPool/1.jpg', 174 ),
( 'NESTLE MILO 250G', 'productPool/1.jpg', 218 ),
( 'NESTLE MILO 400G', 'productPool/1.jpg', 51 ),
( 'NESTLE MILO DRINK', 'productPool/1.jpg', 133 ),
( 'NESTLE MUNCH 10.1G', 'productPool/1.jpg', 278 ),
( 'NESTLE MUNCH 12.1G', 'productPool/1.jpg', 86 );