INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'ARVEE UZHUNNU VADA', 'productPool/1.jpg', 61 ),
( 'ARVEE VANCHO TRUFFLE CAKE', 'productPool/1.jpg', 113 ),
( 'ARVEE VANCHO TRUFFLE CAKE 500 GMS', 'productPool/1.jpg', 219 ),
( 'ARVEE VANILA CAKE', 'productPool/1.jpg', 164 ),
( 'ARVEE VANILA CUTTING BISCUIT', 'productPool/1.jpg', 168 ),
( 'ARVEE VANILA PEDA', 'productPool/1.jpg', 202 ),
( 'ARVEE VATTAYAPPAM 400GM', 'productPool/1.jpg', 66 ),
( 'ARVEE VEG CUTLET', 'productPool/1.jpg', 215 ),
( 'ARVEE VEG PUFFS', 'productPool/1.jpg', 215 ),
( 'ARVEE VEG ROLL', 'productPool/1.jpg', 121 ),
( 'ARVEE VETTU CAKE', 'productPool/1.jpg', 229 ),
( 'ARVEE VSANDWICH', 'productPool/1.jpg', 215 ),
( 'ARVEE WHEAT HALWA 500G', 'productPool/1.jpg', 85 ),
( 'ARVEE WHEAT PUTTU PODI 1KG', 'productPool/1.jpg', 150 ),
( 'ARVEE WHITE CHOCOLATE TRUFFLE CAKE', 'productPool/1.jpg', 12 ),
( 'ARVEE WHITE FOREST', 'productPool/1.jpg', 245 ),
( 'ARVEE WHITE FOREST CAKE', 'productPool/1.jpg', 83 ),
( 'ARVEE WHITE FOREST CAKE 500 GMS', 'productPool/1.jpg', 218 ),
( 'ARVEE WHITE PLUM CAKE 800GMS', 'productPool/1.jpg', 114 ),
( 'ARVEE WHITE PUTTU PODI 1KG', 'productPool/1.jpg', 200 ),
( 'ARVEE WHITE TRIFFLE CAKE', 'productPool/1.jpg', 168 ),
( 'ARVEE WHOLE WHEAT FLOUR 1KG', 'productPool/1.jpg', 12 ),
( 'ARVEE ZEA FOOD POPCORN CHEESELICKS', 'productPool/1.jpg', 188 ),
( 'ARVEE ZEA FOOD PUFFED RICE CARAMEL 50GMS', 'productPool/1.jpg', 178 ),
( 'ARVEE ZEA PUFFED RICE CHEESE 50GMS', 'productPool/1.jpg', 76 ),
( 'ARVEE ZEA PUFFED RICE TOMATO 50GMS', 'productPool/1.jpg', 200 ),
( 'ARYAS ARI PAPPADAM 80G', 'productPool/1.jpg', 123 ),
( 'ARYAS KAPPA PAPPADAM 80G', 'productPool/1.jpg', 141 ),
( 'ASHIRVAD ATTA MULGRAIN 5KG', 'productPool/1.jpg', 132 ),
( 'ASHTAGANDHAM', 'productPool/1.jpg', 72 ),
( 'ASHTAPATHY DEVA THALI 25G MRP 10', 'productPool/1.jpg', 137 ),
( 'ASHTAPATHY DEVA THALI SHAMPOO 100ML', 'productPool/1.jpg', 59 ),
( 'ASHTAPATHY DEVATHALI SOAP 100G', 'productPool/1.jpg', 225 ),
( 'ASHTAPATHY DEVATHALI SOAP 25G', 'productPool/1.jpg', 258 ),
( 'ASHTAPATHY MUD SHAMPOO 100ML', 'productPool/1.jpg', 138 ),
( 'ASHTAPATHY MUD SOAP 100G', 'productPool/1.jpg', 240 ),
( 'ASHTAPATHY NEEM AND TULSI SOAP 75G', 'productPool/1.jpg', 230 ),
( 'ASHTAPATHY OLIVE SOAP 100G', 'productPool/1.jpg', 161 ),
( 'ASHTAPATHY PAPAYA BEAUTY SOAP 75G', 'productPool/1.jpg', 264 ),
( 'ASHTAPATHY PAPAYA BEAUTY SOAP75G', 'productPool/1.jpg', 96 ),
( 'ASHTAPATHY PAPAYA SOAP SET 4*75G B4G1', 'productPool/1.jpg', 119 ),
( 'ASHTAPATHY SOAP 4+1 SET 5*75G', 'productPool/1.jpg', 117 ),
( 'ASHTAPATHY THALI SHAMPOO 100ML', 'productPool/1.jpg', 157 ),
( 'ASHTAPATHY TURMERIC SOAP 75G', 'productPool/1.jpg', 23 ),
( 'ASHTAVAIDYA CASTOR OIL 100ML', 'productPool/1.jpg', 159 ),
( 'ASHTAVAIDYA JOTHISH BRAHMI 400GM', 'productPool/1.jpg', 113 ),
( 'ASSHIRVAD SALT 1 KG', 'productPool/1.jpg', 93 ),
( 'ATHIPAZHAM 50G', 'productPool/1.jpg', 113 ),
( 'AVAL RED 500G', 'productPool/1.jpg', 221 ),
( 'AVAL RED 500GM', 'productPool/1.jpg', 35 ),
( 'AVAL VILAYICHATHU 200GM', 'productPool/1.jpg', 124 ),
( 'AVAL VILAYICHATHU 500GMS', 'productPool/1.jpg', 119 ),
( 'AVAL WHITE 500G', 'productPool/1.jpg', 80 ),
( 'AVAL WHITE PREMIUM 500GM', 'productPool/1.jpg', 21 ),
( 'AVEES FRIED WHEAT PUTTU PODI 1 KG', 'productPool/1.jpg', 35 ),
( 'AVEES IDIYAPPAM PODI 1KG', 'productPool/1.jpg', 136 ),
( 'AVEES IDLI DOSA MAVU', 'productPool/1.jpg', 200 ),
( 'Avees Instant Idiyappam', 'productPool/1.jpg', 278 ),
( 'AVEES INSTANT IDLI', 'productPool/1.jpg', 194 ),
( 'AVEES PALAPPAM 500G', 'productPool/1.jpg', 117 ),
( 'AVEES PALAPPAM BATTER', 'productPool/1.jpg', 205 ),
( 'AVEES PATHIRI /IDIAPAM PODI 500G', 'productPool/1.jpg', 56 ),
( 'AVEES PUNCHA IDIYAPPA 1KG', 'productPool/1.jpg', 91 ),
( 'AVEES PUNCHA PUTTUPODI 1 KG', 'productPool/1.jpg', 260 ),
( 'AVEES PUNCHA PUTTUPODI 500G', 'productPool/1.jpg', 32 ),
( 'AVEES PUTTU PODI 500G', 'productPool/1.jpg', 84 ),
( 'AVEES PUTTUPODI DOUBLE ROASTED 1KG', 'productPool/1.jpg', 36 ),
( 'AVEES PUTTUPODI STEAMED 500G', 'productPool/1.jpg', 170 ),
( 'AVEES UPPUMA RAVA 1KG', 'productPool/1.jpg', 157 ),
( 'AVEES UPPUMA RAVA 500G', 'productPool/1.jpg', 106 ),
( 'AVEES VELLAYAPPAM BATTER', 'productPool/1.jpg', 217 ),
( 'AVIO 250 ML LEMON', 'productPool/1.jpg', 263 ),
( 'AVIO 250 ML ORANGE', 'productPool/1.jpg', 168 ),
( 'AVIO 500 ML CITRUS', 'productPool/1.jpg', 10 ),
( 'AVIO 500 ML LEMON', 'productPool/1.jpg', 20 ),
( 'AVIO 500 ML ORANGE', 'productPool/1.jpg', 76 ),
( 'AVM ASAFORTIDA', 'productPool/1.jpg', 229 ),
( 'AVT DAIRY SURE GHEE 200ML', 'productPool/1.jpg', 228 ),
( 'AVT DAIRY SURE GHEE 500ML', 'productPool/1.jpg', 15 ),
( 'AVT DAIRY WHITENER 200G', 'productPool/1.jpg', 85 ),
( 'AVT DAIRY WHITENER 400G', 'productPool/1.jpg', 139 ),
( 'AVT GARDEN FRESH DUST TEA 100G', 'productPool/1.jpg', 69 ),
( 'AVT GARDEN FRESH DUST TEA 1KG', 'productPool/1.jpg', 61 ),
( 'AVT GARDEN FRESH DUST TEA 250G', 'productPool/1.jpg', 41 ),
( 'AVT GLD CUP PREMIUM 500G', 'productPool/1.jpg', 11 ),
( 'AVT GREEN TEA BAG 20G', 'productPool/1.jpg', 156 ),
( 'AVT GREEN TEA100G', 'productPool/1.jpg', 66 ),
( 'AVT PRE COFECHICO 500G', 'productPool/1.jpg', 30 ),
( 'AVT PREMIUM COFFE CHICORY 100G', 'productPool/1.jpg', 83 ),
( 'AVT PREMIUM COFFEE 200G', 'productPool/1.jpg', 233 ),
( 'AVT PREMIUM LEAF TEA 250G', 'productPool/1.jpg', 246 ),
( 'AVT PREMIUM LEAF TEA 500G', 'productPool/1.jpg', 4 ),
( 'AVT PREMIUM LEAF TEA JAR 500G', 'productPool/1.jpg', 120 ),
( 'AVT PREMIUM SELECT 500G', 'productPool/1.jpg', 167 ),
( 'AVT PREMIUM SELECT DUST TEA 250G', 'productPool/1.jpg', 46 ),
( 'AVT PREMIUM TEA 1KG', 'productPool/1.jpg', 21 ),
( 'AVT PREMIUM TEA 1KG CATERING BLEND', 'productPool/1.jpg', 176 ),
( 'AVT PREMIUM TEA 250GMS', 'productPool/1.jpg', 212 ),
( 'AVT PREMIUM TEA 35G', 'productPool/1.jpg', 205 ),
( 'AVT PREMIUM TEA 500 JAR', 'productPool/1.jpg', 188 ),
( 'AVT PREMIUM TEA 500GMS', 'productPool/1.jpg', 59 ),
( 'AVT PREMIUM TEA BAG 100NOS', 'productPool/1.jpg', 232 ),
( 'AVT RAJAH DUST TEA 1KG', 'productPool/1.jpg', 271 ),
( 'AVT RAJAH DUST TEA2 50G', 'productPool/1.jpg', 95 ),
( 'AVT SUPREME CTC DUST TEA 500GM', 'productPool/1.jpg', 134 ),
( 'AVT SUPREME TEA 250G', 'productPool/1.jpg', 74 ),
( 'AVT TEA 100G', 'productPool/1.jpg', 76 ),
( 'AVT TEA 250G JAR', 'productPool/1.jpg', 196 ),
( 'AXE BLAST DEODORANT BODYSPRAY 150ML', 'productPool/1.jpg', 102 ),
( 'AXE DARK TEMPTATION BODY SPRAY 150ML', 'productPool/1.jpg', 78 ),
( 'AXE DARK TEMTATION CHOCLATE TALC 100G', 'productPool/1.jpg', 95 ),
( 'AXE GOLD TEMPTATION BODY SPRAY 150ML', 'productPool/1.jpg', 95 ),
( 'AXE MARINE SPLASH BODY SPRAY 150ML', 'productPool/1.jpg', 244 ),
( 'AXE OCEAN BREEZE BODY SPRAY 150ML', 'productPool/1.jpg', 100 ),
( 'AXE OIL (B)', 'productPool/1.jpg', 131 ),
( 'AXE OIL (M) IMP', 'productPool/1.jpg', 15 ),
( 'AXE OIL (S) IMP', 'productPool/1.jpg', 149 ),
( 'AXE OIL IMP RS310', 'productPool/1.jpg', 17 ),
( 'AXE RECHARGE 24X7 DEO', 'productPool/1.jpg', 202 ),
( 'AXE RECHARGE GAMEFACE DEO', 'productPool/1.jpg', 66 ),
( 'AXE RECHARGE MIDNIGHT DEO 150ML', 'productPool/1.jpg', 195 ),
( 'AXE SIGNATURE COLLECTION CHAMPION', 'productPool/1.jpg', 184 ),
( 'AXE SIGNATURE CORPORATE 122ML', 'productPool/1.jpg', 154 ),
( 'AXE SIGNATURE DENIM TALC 100G', 'productPool/1.jpg', 39 ),
( 'AXE SIGNATURE DENIM TALC 300G', 'productPool/1.jpg', 219 ),
( 'AXE SIGNATURE INTENSE DEO 122ML', 'productPool/1.jpg', 215 ),
( 'AXE SIGNATURE MYSTERIOUS DEO', 'productPool/1.jpg', 275 ),
( 'AXE SIGNATURE PULSE 100G', 'productPool/1.jpg', 138 ),
( 'AXE SIGNATURE PULSE 300G', 'productPool/1.jpg', 122 ),
( 'AXE SIGNATURE SPORT 122ML', 'productPool/1.jpg', 183 ),
( 'AXE SIGNATURE SUAVE BODY PERFUME 122ML', 'productPool/1.jpg', 179 ),
( 'AXE SIGNATURE TEMPTATION TALC 100G', 'productPool/1.jpg', 151 ),
( 'AXE SIGNATURECOLLECTION MAVERICK', 'productPool/1.jpg', 3 ),
( 'AXE SIGNATURECOLLECTION ROGUE PERFUME', 'productPool/1.jpg', 263 ),
( 'AXE APOLLO SPRY 150ML', 'productPool/1.jpg', 216 ),
( 'AYAMOTHAKAM 50GM', 'productPool/1.jpg', 90 ),
( 'AYUR ALMOND NOU CRE 80ML', 'productPool/1.jpg', 127 ),
( 'AYUR ASTRINGENT 100ML', 'productPool/1.jpg', 135 ),
( 'AYUR BODY CARE LOTION COCOA BUTTER 200ML', 'productPool/1.jpg', 132 ),
( 'AYUR BODY LOTION COCOA BUTTER 100ML', 'productPool/1.jpg', 74 ),
( 'AYUR CLEANSING MILK LOTION 100ML', 'productPool/1.jpg', 233 ),
( 'AYUR COLD CREAM 25ML', 'productPool/1.jpg', 123 ),
( 'AYUR COLD CREAM 80G', 'productPool/1.jpg', 169 ),
( 'AYUR COLD WAX 150G', 'productPool/1.jpg', 55 ),
( 'AYUR HENNA DARK BROWN 500GM', 'productPool/1.jpg', 184 ),
( 'AYUR HERBAL COLD CREAM 25ML', 'productPool/1.jpg', 107 ),
( 'AYUR HOT WAX 150G', 'productPool/1.jpg', 183 ),
( 'AYUR MOISTURIZER LOTION100ML', 'productPool/1.jpg', 260 ),
( 'AYUR NATURAL HENNA 100G', 'productPool/1.jpg', 111 ),
( 'AYUR NATURAL HENNA 200G', 'productPool/1.jpg', 111 ),
( 'AYUR NEEM FACE WASH 50ML', 'productPool/1.jpg', 135 ),
( 'AYUR SKIN TONER 100ML', 'productPool/1.jpg', 255 ),
( 'AYUR SUN SCREEN SPF-15 LOTION', 'productPool/1.jpg', 247 ),
( 'AYUR SUN SCREEN SPF-30 100ML', 'productPool/1.jpg', 160 ),
( 'AYURVEDAMIX KASHAYA SOAP COMBO PACK', 'productPool/1.jpg', 99 ),
( 'AYURVEDAMIX MANJAL SOAP', 'productPool/1.jpg', 168 ),
( 'AYURVEDAMIX PAPPAYA SOAP 75G', 'productPool/1.jpg', 182 ),
( 'AYUSH ANTI CAVITY TOOTH PASTE 40G', 'productPool/1.jpg', 257 ),
( 'AYUSH ANTI CAVITY TOOTH PASTE 80G', 'productPool/1.jpg', 269 ),
( 'AYUSH ANTI CAVITY TOOTHPASTE 150G', 'productPool/1.jpg', 251 ),
( 'AYUSH ANTI DANDRUFF FENUGREEK SHAMPOO 175ML', 'productPool/1.jpg', 124 ),
( 'AYUSH ANTI DANDRUFF NEEM SHAMPOO 175ML', 'productPool/1.jpg', 24 ),
( 'AYUSH ANTI PIMPLE TURMERIC FACEWASH 40G', 'productPool/1.jpg', 230 ),
( 'AYUSH ANTI PIMPLE TURMERIC FACEWASH 80G', 'productPool/1.jpg', 145 ),
( 'AYUSH CARDAMOM TOOTH PASTE 80G', 'productPool/1.jpg', 232 ),
( 'AYUSH COW GHEE SOAP 100G', 'productPool/1.jpg', 98 ),
( 'AYUSH FRESHNESS GEL CARDAMOM 150G', 'productPool/1.jpg', 70 ),
( 'AYUSH SAFFRON FACEWASH 80G', 'productPool/1.jpg', 218 ),
( 'AYUSH SAFFRON FAIRNESS CREAM 50G', 'productPool/1.jpg', 227 ),
( 'AYUSH SAFFRON SOAP 100G', 'productPool/1.jpg', 12 ),
( 'AYUSH TURMERIC FACE CREAM 25G', 'productPool/1.jpg', 158 ),
( 'AYUSH TURMERIC FACE CREAM 50G', 'productPool/1.jpg', 10 ),
( 'AYUSH TURMERIC SOAP100G', 'productPool/1.jpg', 166 ),
( 'AYUSH WHITENING TOOTH PASTE 150G', 'productPool/1.jpg', 41 ),
( 'AYUSH WHITENING TOOTH PASTE 80G', 'productPool/1.jpg', 109 ),
( 'AYYAPPA RICE MURUKKU 10NOS', 'productPool/1.jpg', 25 ),
( 'AYYAPPAS SWEET BONDA 10 NOS', 'productPool/1.jpg', 69 ),
( 'AZISTA TASTE GOOD KARELA BISCUITES 100G', 'productPool/1.jpg', 65 ),
( 'B NATURAL CLOUDY APPLE 200ML', 'productPool/1.jpg', 266 ),
( 'B NATURAL GUAVA 200ML', 'productPool/1.jpg', 140 ),
( 'B NATURAL LITCHI 200ML', 'productPool/1.jpg', 122 ),
( 'B NATURAL MIXED FRUIT 200ML', 'productPool/1.jpg', 127 ),
( 'B NATURAL ORANGE 200ML', 'productPool/1.jpg', 172 ),
( 'B PROTIN CHOCOLATE 200G', 'productPool/1.jpg', 209 ),
( 'B PROTIN CHOCOLATE 500G', 'productPool/1.jpg', 78 ),
( 'BABILA BATHA BRUSH BA BO24', 'productPool/1.jpg', 147 ),
( 'BABILA BATHA BRUSH BA V24', 'productPool/1.jpg', 255 ),
( 'BABILA BLACK HEAD REMOVER BHR-V01', 'productPool/1.jpg', 258 ),
( 'BABILA BLACK HEAD REMOVER BHR-V02', 'productPool/1.jpg', 117 ),
( 'BABILA BODY SPONGE BA-V22', 'productPool/1.jpg', 207 ),
( 'BABILA BODY SPONGE BA-V23', 'productPool/1.jpg', 9 ),
( 'BABILA COMB HC-V04', 'productPool/1.jpg', 143 ),
( 'BABILA COMB HC-V05', 'productPool/1.jpg', 21 ),
( 'BABILA COMB HC-V08', 'productPool/1.jpg', 76 ),
( 'BABILA COMB HC-V10', 'productPool/1.jpg', 208 ),
( 'BABILA COMB HC-V14', 'productPool/1.jpg', 188 ),
( 'BABILA COMB HC-V15', 'productPool/1.jpg', 271 ),
( 'BABILA COMB WC-V07', 'productPool/1.jpg', 106 ),
( 'BABILA DYE BRUSH BB-V06', 'productPool/1.jpg', 33 ),
( 'BABILA DYE BRUSH DB-V02', 'productPool/1.jpg', 174 ),
( 'BABILA DYE BRUSH DB-V05', 'productPool/1.jpg', 77 ),
( 'BABILA DYE BRUSH DBC-V01TC', 'productPool/1.jpg', 135 ),
( 'BABILA FOOT SCRAPER PC-V01', 'productPool/1.jpg', 110 ),
( 'BABILA FOOT SCRUBBER PC VO1B 1N', 'productPool/1.jpg', 73 ),
( 'BABILA HAIR BRUSH HB-V012', 'productPool/1.jpg', 46 ),
( 'BABILA HAIR BRUSH HB-V440', 'productPool/1.jpg', 239 ),
( 'BABILA HAIR BRUSH HB-V620', 'productPool/1.jpg', 160 ),
( 'BABILA HAIR BRUSH HB-V630', 'productPool/1.jpg', 52 ),
( 'BABILA HAIR BRUSH HBC - V01', 'productPool/1.jpg', 37 ),
( 'BABILA HAIR BRUSH HBC-V02', 'productPool/1.jpg', 141 ),
( 'BABILA HAIR BRUSH HBC-V03', 'productPool/1.jpg', 43 ),
( 'BABILA HAIR CARE COMB HC V06', 'productPool/1.jpg', 202 ),
( 'BABILA LOOFHA BA V36 1N', 'productPool/1.jpg', 264 ),
( 'BABILA NAIL CLIPPER NC VO1', 'productPool/1.jpg', 264 ),
( 'BABILA NAIL CLIPPER NC VO7', 'productPool/1.jpg', 6 ),
( 'BABILA NAIL CLIPPER NC-V01', 'productPool/1.jpg', 219 ),
( 'BABILA NAIL CLIPPER NC-V02', 'productPool/1.jpg', 6 ),
( 'BABILA NAIL CLIPPER NC-V09', 'productPool/1.jpg', 119 ),
( 'BABILA NAILBRUSH PUMIC STONE PC V07 1N', 'productPool/1.jpg', 108 ),
( 'BABILA SCISSOR CS-V013', 'productPool/1.jpg', 149 ),
( 'BABILA SCISSOR CS-V014', 'productPool/1.jpg', 99 ),
( 'BABILA SCISSOR CS-V017', 'productPool/1.jpg', 231 ),
( 'BABILA SCISSOR CS-V020', 'productPool/1.jpg', 221 ),
( 'BABILA SCISSOR CS-V09', 'productPool/1.jpg', 62 ),
( 'BABILA SCISSOR SC-V05', 'productPool/1.jpg', 129 ),
( 'BABY & NIPPLE BIGCLE', 'productPool/1.jpg', 190 ),
( 'BABY CARE GIFT PACK', 'productPool/1.jpg', 187 ),
( 'BABY CORN', 'productPool/1.jpg', 94 ),
( 'BABY DIAPERS MD 9', 'productPool/1.jpg', 279 ),
( 'BABY DOVE BATHING SOAP 75G', 'productPool/1.jpg', 96 ),
( 'BABY DOVE RICH MOISTURE 75G', 'productPool/1.jpg', 237 ),
( 'BABY DOVE RICH MOISTURE 75G*3 SET SOAP', 'productPool/1.jpg', 67 ),
( 'BABY GIFT BASKET', 'productPool/1.jpg', 17 ),
( 'BABY GIFT PACK 50 7G', 'productPool/1.jpg', 223 ),
( 'BABY ITEM', 'productPool/1.jpg', 198 ),
( 'BABY JOY BIG WATER BOTTLE', 'productPool/1.jpg', 182 ),
( 'BABY LIPS COLOR CANDY RUSH COTTON CANDY 4G', 'productPool/1.jpg', 20 ),
( 'BABY POTATO', 'productPool/1.jpg', 114 ),
( 'BABY SAFFRON 1G', 'productPool/1.jpg', 220 ),
( 'BABY SAFFRON 500MG', 'productPool/1.jpg', 274 ),
( 'BABY SAFFRON 50MG', 'productPool/1.jpg', 106 ),
( 'BABY SAFRON 250MG', 'productPool/1.jpg', 106 ),
( 'BABY SEBAMED BABY CREAM 50ML', 'productPool/1.jpg', 60 ),
( 'BABY SHAMPOO 50ML', 'productPool/1.jpg', 116 ),
( 'BABY VITA BARLEY POWDER 100G', 'productPool/1.jpg', 172 ),
( 'BABY VITA FAMILY HEALTH MIX POWDER 400G', 'productPool/1.jpg', 58 ),
( 'BABY VITA OUR KIDS HEALTH MIX POWDER 400G', 'productPool/1.jpg', 187 ),
( 'BABY VITA RICE BANANA POWDER MIX 300G', 'productPool/1.jpg', 102 ),
( 'BABYSEBAMEDBABYWASH EXTRASOFT50ML', 'productPool/1.jpg', 109 ),
( 'BABYSEBAMEDCHILDRENS SHAMPOO50ML', 'productPool/1.jpg', 238 ),
( 'BABYVITA BANANA POWDER 200G PKT', 'productPool/1.jpg', 122 ),
( 'BABYVITA BANANA POWDER 300G JAR', 'productPool/1.jpg', 108 ),
( 'BABYVITA BANANA POWDER 300G PKT', 'productPool/1.jpg', 151 ),
( 'BABYVITA BANANA POWDER 400G', 'productPool/1.jpg', 25 ),
( 'BABYVITA KANNANKAYA POWDER 200GRFL', 'productPool/1.jpg', 123 ),
( 'BABYVITA KANNANKAYA POWDER 300G JAR', 'productPool/1.jpg', 261 ),
( 'BABYVITA KANNANKAYA POWDER300G', 'productPool/1.jpg', 94 ),
( 'BABYVITA RAGI POWDER 200G PKT', 'productPool/1.jpg', 193 ),
( 'BABYVITA RAGI POWDER 300G JAR', 'productPool/1.jpg', 74 ),
( 'BABYVITA RAGI POWDER MIX 300G PKT', 'productPool/1.jpg', 92 ),
( 'BABYVITA RICE BANANA 300G JAR', 'productPool/1.jpg', 123 ),
( 'BABYVITA RICE BANANA POWDER 200G REFIL', 'productPool/1.jpg', 267 ),
( 'BABYVITA RICE BANANA POWDER 300G PKT', 'productPool/1.jpg', 262 ),
( 'BABYVITA WHEAT BANANA 300G JAR', 'productPool/1.jpg', 195 ),
( 'BABYVITA WHEAT BANANA POWDER 300G REFIL', 'productPool/1.jpg', 240 ),
( 'BABYVITA WHEAT BANANA POWDER MIX 200G', 'productPool/1.jpg', 258 ),
( 'BABYVITA WHEAT BANANA POWDER MIX 300G JAR', 'productPool/1.jpg', 198 ),
( 'BACTO ZAPPER DISHWASHING LIQUID ALOE VERA 1KG', 'productPool/1.jpg', 216 ),
( 'BACTO ZAPPER DISHWASHING LIQUID LEMON 1KG', 'productPool/1.jpg', 167 ),
( 'BADAM', 'productPool/1.jpg', 76 ),
( 'BADAM 100 GMS', 'productPool/1.jpg', 67 ),
( 'BADAM 100G', 'productPool/1.jpg', 188 ),
( 'BADAM 200G', 'productPool/1.jpg', 241 ),
( 'BADAM 200GMS', 'productPool/1.jpg', 11 ),
( 'BADAM 500G', 'productPool/1.jpg', 33 ),
( 'BADAM 500GMS', 'productPool/1.jpg', 185 ),
( 'BADAM LEHYAM 400G', 'productPool/1.jpg', 278 ),
( 'BAG NEEDLE', 'productPool/1.jpg', 128 ),
( 'BAGGRYS W OATS 1KG', 'productPool/1.jpg', 201 ),
( 'BAGGRYS W OATS 500GM', 'productPool/1.jpg', 57 ),
( 'BAGGRYS WHITE OATS 500G', 'productPool/1.jpg', 273 ),
( 'BAHAR FABRIC CONDITIONER 500ML', 'productPool/1.jpg', 108 ),
( 'BAHAR FABRIC CONDITIONER PINK 500ML', 'productPool/1.jpg', 110 ),
( 'BAHAR PREMIUM LEMON 400ML', 'productPool/1.jpg', 62 ),
( 'BAHAR ULTRA DISH WASH LIQUID 1 LI', 'productPool/1.jpg', 135 ),
( 'BAJAJ AL MOND DROPS 200 ML', 'productPool/1.jpg', 196 ),
( 'BAJAJ ALMOND DROPS 100ML', 'productPool/1.jpg', 223 ),
( 'BAJAJ ALMOND DROPS 300 ML', 'productPool/1.jpg', 152 ),
( 'BAJAJ ALMOND DROPS HAIR OIL 50 ML', 'productPool/1.jpg', 224 ),
( 'BAJAJ NOMARKS AYURVEDA 25G', 'productPool/1.jpg', 261 ),
( 'BAJI MULAKU', 'productPool/1.jpg', 195 ),
( 'BAKE SMITH MARIE 90GM', 'productPool/1.jpg', 136 ),
( 'BAKER CORN FLOUR 100G', 'productPool/1.jpg', 259 ),
( 'BAKER CUSTARD POWD 150G', 'productPool/1.jpg', 244 ),
( 'BAKER PLAICHINA GRASS 10G', 'productPool/1.jpg', 183 ),
( 'BAKERS BADAM DRINK 200G', 'productPool/1.jpg', 32 ),
( 'BAKERS BADAM MILKSHAKE POWDER 100G', 'productPool/1.jpg', 271 ),
( 'BAKERS BAKING POWDER 50G', 'productPool/1.jpg', 2 ),
( 'BAKERS BAKING SODA 100GM', 'productPool/1.jpg', 133 ),
( 'BAKERS BIRIYANI ESSENCE 20ML', 'productPool/1.jpg', 149 ),
( 'BAKERS BLACK SALT 100G', 'productPool/1.jpg', 81 ),
( 'BAKERS BUTTER CHICKEN MASALA 100G', 'productPool/1.jpg', 30 ),
( 'BAKERS BUTTERSCOTCH MILKSHAKE 100GM', 'productPool/1.jpg', 124 ),
( 'BAKERS CARMEL PUDDING MIX POWDER 65G', 'productPool/1.jpg', 8 ),
( 'BAKERS CHAAT MASALA 100G', 'productPool/1.jpg', 113 ),
( 'BAKERS CHANNA MASALA 100G', 'productPool/1.jpg', 217 ),
( 'BAKERS CHILLY CHICKEN MASALA MIX 100G', 'productPool/1.jpg', 80 ),
( 'BAKERS CHILLY GOBIMIX 100G', 'productPool/1.jpg', 238 ),
( 'BAKERS CHOCOLATE PUDDING MIX POWDER 80G', 'productPool/1.jpg', 53 ),
( 'BAKERS CITRIC ACID 50GM', 'productPool/1.jpg', 123 ),
( 'BAKERS COCOA POWDER50G', 'productPool/1.jpg', 25 ),
( 'BAKERS CORN FLAKES 500G', 'productPool/1.jpg', 2 ),
( 'BAKERS CORN FLOUR 500GM', 'productPool/1.jpg', 178 ),
( 'BAKERS CUSTARD POWDER 100G', 'productPool/1.jpg', 40 ),
( 'BAKERS CUSTARD POWDER 50G', 'productPool/1.jpg', 206 ),
( 'BAKERS CUSTARD POWDER VANILLA 500G', 'productPool/1.jpg', 96 ),
( 'BAKERS DRIED YEAST 25G', 'productPool/1.jpg', 17 ),
( 'BAKERS DRINKING CHOCOLATE100G', 'productPool/1.jpg', 270 ),
( 'BAKERS DRY GINGER POWDER 100G', 'productPool/1.jpg', 278 ),
( 'BAKERS DRY MANGO POWDER', 'productPool/1.jpg', 276 ),
( 'BAKERS GELATIN 50GM', 'productPool/1.jpg', 41 ),
( 'BAKERS GOBI MANCHURIAN 125G', 'productPool/1.jpg', 251 ),
( 'BAKERS ICE CREAM MIX PINEAPPLE', 'productPool/1.jpg', 274 ),
( 'BAKERS ICE CREAM POWDER CHOCOLATE', 'productPool/1.jpg', 53 ),
( 'BAKERS ICECREAM MIX PISTA 100GM', 'productPool/1.jpg', 15 ),
( 'BAKERS ICECREAM MIX VANILLA', 'productPool/1.jpg', 160 ),
( 'BAKERS ICING SUGAR 100G', 'productPool/1.jpg', 226 ),
( 'BAKERS JELLY CRYSTALS ORANGE 85GM', 'productPool/1.jpg', 259 ),
( 'BAKERS KABAB MASALA 100G', 'productPool/1.jpg', 144 ),
( 'BAKERS KASURI METHI 100G', 'productPool/1.jpg', 94 ),
( 'BAKERS KASURI METHI 25G', 'productPool/1.jpg', 146 ),
( 'BAKERS KITCHEN KING MASALA 100G', 'productPool/1.jpg', 172 ),
( 'BAKERS MILK SHAKE PISTA 100GM', 'productPool/1.jpg', 12 ),
( 'BAKERS MILK SHAKE STRAWBERRY 100GM', 'productPool/1.jpg', 203 ),
( 'BAKERS MILKSHAKE CHOCOLATE 150G', 'productPool/1.jpg', 210 ),
( 'BAKERS MILKSHAKE MANGO 100GM', 'productPool/1.jpg', 160 ),
( 'BAKERS MON SODIUM GLUTAMATE 25G', 'productPool/1.jpg', 254 ),
( 'BAKERS NOODLES SNACK MIX 50G', 'productPool/1.jpg', 108 ),
( 'BAKERS PANEER BUTTER MASALA 100G', 'productPool/1.jpg', 271 ),
( 'BAKERS PANEER BUTTER MASALA 50G', 'productPool/1.jpg', 153 ),
( 'BAKERS PANIPURI MASALA 50G', 'productPool/1.jpg', 138 ),
( 'BAKERS PINEAPPLE ESSENCE 20ML', 'productPool/1.jpg', 42 ),
( 'BAKERS PISTA PUDDING MIX POWDER 80G', 'productPool/1.jpg', 9 ),
( 'BAKERS PUDDING MIX MANGO', 'productPool/1.jpg', 104 ),
( 'BAKERS PUDDING MIX PINEAPPLE', 'productPool/1.jpg', 270 ),
( 'BAKERS ROSE MIX POWDER 100G', 'productPool/1.jpg', 31 ),
( 'BAKERS SWEET SAUNF 500G', 'productPool/1.jpg', 16 ),
( 'BAKERS TANDOORI CHICKEN 100G', 'productPool/1.jpg', 93 ),
( 'BAKERS TEA MASALA 40G', 'productPool/1.jpg', 224 ),
( 'BAKERS VANILA ESSENCE 20ML', 'productPool/1.jpg', 274 ),
( 'BAKERS VANILLA PUDDING MIX POWDER 80G', 'productPool/1.jpg', 265 ),
( 'BAKERS WHIPPING CREAM 50G', 'productPool/1.jpg', 129 ),
( 'BAKERS WHITE PEPPER POWDER 50G', 'productPool/1.jpg', 7 ),
( 'BAKESMITH MARIE 200GM', 'productPool/1.jpg', 266 ),
( 'BAKING POWDER 100GM', 'productPool/1.jpg', 24 ),
( 'BAKING SODA 100G', 'productPool/1.jpg', 236 ),
( 'BALARAMA DIGEST RS 10', 'productPool/1.jpg', 71 ),
( 'BALCK ROSE HAIR COLOR SHMPOO 25 ML', 'productPool/1.jpg', 243 ),
( 'BALL PINS SMALL 25G MRP10', 'productPool/1.jpg', 126 ),
( 'BALOON', 'productPool/1.jpg', 61 ),
( 'BALOON 5PCS', 'productPool/1.jpg', 188 ),
( 'BALOON IMP RS27', 'productPool/1.jpg', 158 ),
( 'BALOON RS 80', 'productPool/1.jpg', 218 ),
( 'BALOON RS12', 'productPool/1.jpg', 135 ),
( 'BALOON RS35', 'productPool/1.jpg', 206 ),
( 'BALOON RS36', 'productPool/1.jpg', 39 ),
( 'BALOON RS65', 'productPool/1.jpg', 98 ),
( 'BALOON RS70', 'productPool/1.jpg', 27 ),
( 'BALOONS 5PCS', 'productPool/1.jpg', 255 ),
( 'BALTIKA BEER 450ML', 'productPool/1.jpg', 18 ),
( 'BAMBIND RASMATI RICE ADA 200G', 'productPool/1.jpg', 175 ),
( 'BAMBINO ADA 200G', 'productPool/1.jpg', 252 ),
( 'BAMBINO ADA 450GM', 'productPool/1.jpg', 44 ),
( 'BAMBINO ADA ADA 475.G', 'productPool/1.jpg', 165 ),
( 'BAMBINO BADAM DRINK MIX 500G', 'productPool/1.jpg', 90 ),
( 'BAMBINO CELEBRATIONS 1.13KG', 'productPool/1.jpg', 240 ),
( 'BAMBINO CELEBRATIONS 300G', 'productPool/1.jpg', 92 ),
( 'BAMBINO CELEBRATIONS 600G', 'productPool/1.jpg', 170 ),
( 'BAMBINO CELEBRATIONS 930G', 'productPool/1.jpg', 42 ),
( 'BAMBINO GINGER GARLIC PASTE 90G', 'productPool/1.jpg', 242 ),
( 'BAMBINO GULAB JAMUN 1KG', 'productPool/1.jpg', 115 ),
( 'BAMBINO GULAB JAMUN 500G', 'productPool/1.jpg', 91 ),
( 'BAMBINO GULAB JAMUN MIX 100G', 'productPool/1.jpg', 248 ),
( 'BAMBINO GULAB JAMUN MIX 300G', 'productPool/1.jpg', 84 ),
( 'BAMBINO GULAB JAMUN MIX 200G', 'productPool/1.jpg', 65 ),
( 'BAMBINO HEALTHY DIETT WHEAT RICE 400G', 'productPool/1.jpg', 189 ),
( 'BAMBINO HEALTHY OATS VERMICELLI 180G', 'productPool/1.jpg', 7 ),
( 'BAMBINO HOT SOUR VEG SOUP 47G', 'productPool/1.jpg', 204 ),
( 'BAMBINO INSTANT BADAM DRINK MIX', 'productPool/1.jpg', 112 ),
( 'BAMBINO INSTANT CUP PASTTA CHEESE 62G', 'productPool/1.jpg', 149 ),
( 'BAMBINO INSTANT CUP PASTTA MASALA 62G', 'productPool/1.jpg', 195 ),
( 'BAMBINO INSTANT CUP PASTTA TOMATO 62G', 'productPool/1.jpg', 190 ),
( 'BAMBINO KAYAM 20G', 'productPool/1.jpg', 102 ),
( 'BAMBINO KAYAM 45GM', 'productPool/1.jpg', 77 ),
( 'BAMBINO LONG VERMICELLI 350G', 'productPool/1.jpg', 274 ),
( 'BAMBINO MACARONI 200GM', 'productPool/1.jpg', 156 ),
( 'BAMBINO MACARONI 50G', 'productPool/1.jpg', 101 ),
( 'BAMBINO MACARONI MASALA VEG 13G', 'productPool/1.jpg', 166 ),
( 'BAMBINO MACRONI 450GM', 'productPool/1.jpg', 236 ),
( 'BAMBINO MACRONI 925GMS', 'productPool/1.jpg', 273 ),
( 'BAMBINO MANGO SOAN PAPDI 250G', 'productPool/1.jpg', 226 ),
( 'BAMBINO MIXED VEGTABLE SOUP POWDER47G', 'productPool/1.jpg', 82 ),
( 'BAMBINO MOONG DAL 15G', 'productPool/1.jpg', 222 ),
( 'BAMBINO MUSHROOM SOUP 50GM', 'productPool/1.jpg', 245 ),
( 'BAMBINO OATS VERMICELLI 160G', 'productPool/1.jpg', 127 );