INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'CELLO TECHNO TIP BLUE RS 10', 'productPool/1.jpg', 207 ),
( 'CELLO TECHNO TIP XS SERIES PEN BLACK', 'productPool/1.jpg', 122 ),
( 'CELLO TECHNO TIP XS SERIES PEN BLUE', 'productPool/1.jpg', 92 ),
( 'CELLO TECNOTIP CLIK BLUE PEN', 'productPool/1.jpg', 69 ),
( 'CELLO TEXAS 1 LTR BOTTLE', 'productPool/1.jpg', 162 ),
( 'CELLO THERMI PACK BIG CONTAINER', 'productPool/1.jpg', 63 ),
( 'CELLO THERMI PACK MEDIUM CONTAINER', 'productPool/1.jpg', 235 ),
( 'CELLO TIVOLI 3 PCS SET', 'productPool/1.jpg', 105 ),
( 'CELLO TIVOLI 4 PCS SET', 'productPool/1.jpg', 3 ),
( 'CELLO TOPBALL CLICK PEN', 'productPool/1.jpg', 191 ),
( 'CELLO TRACK BOTTLE 700ML', 'productPool/1.jpg', 198 ),
( 'CELLO TRIMATE 10 INK COLOR PEN', 'productPool/1.jpg', 200 ),
( 'CELLO TULIP WATER BOTTLE 1000ML', 'productPool/1.jpg', 46 ),
( 'CELLO VELVET O WRITING PEN', 'productPool/1.jpg', 158 ),
( 'CELLO VELVET-O BALL PEN', 'productPool/1.jpg', 195 ),
( 'CELLO WINNER BALL PEN BLUE', 'productPool/1.jpg', 185 ),
( 'CELLO WINNER BLUE BLACK PEN', 'productPool/1.jpg', 213 ),
( 'CELLP MAXRITER RS 10', 'productPool/1.jpg', 243 ),
( 'CERELAC STAGE 2 RICE VEGETABLE', 'productPool/1.jpg', 91 ),
( 'CERELAC STAGE 4 MULTIGRAIN DAL VEG', 'productPool/1.jpg', 8 ),
( 'CERELAC WHEAT HONEY STAGE 2', 'productPool/1.jpg', 180 ),
( 'CERLAC STAGE 1 RICE', 'productPool/1.jpg', 203 ),
( 'CERLAC STAGE 3 RICE MIXED VEG', 'productPool/1.jpg', 159 ),
( 'CERLAC STAGE 3 WHEAT RICE MIXED FRUIT', 'productPool/1.jpg', 103 ),
( 'CERLAC STAGE5 5 GRAINS AND FRUIT', 'productPool/1.jpg', 187 ),
( 'CHACHOOS CHAPPATHY', 'productPool/1.jpg', 144 ),
( 'CHAIRMAN WASHING BRUSH', 'productPool/1.jpg', 214 ),
( 'CHAITHARAM FOOD CHACHOOS POORI', 'productPool/1.jpg', 35 ),
( 'CHAKKA CHIPS 200 GMS', 'productPool/1.jpg', 141 ),
( 'CHAKKA CHIPS 200G', 'productPool/1.jpg', 149 ),
( 'CHAKKA CHIPS 500 GMS', 'productPool/1.jpg', 234 ),
( 'CHAKKA CHIPS 500G', 'productPool/1.jpg', 33 ),
( 'CHAKKA HALWA 1KG', 'productPool/1.jpg', 166 ),
( 'CHAKKA HALWA 500G', 'productPool/1.jpg', 7 ),
( 'CHAKKAVARATTY 1KG', 'productPool/1.jpg', 206 ),
( 'CHAKRA SPONGE MOPE 200R', 'productPool/1.jpg', 254 ),
( 'CHALK', 'productPool/1.jpg', 213 ),
( 'CHALK PENCIL', 'productPool/1.jpg', 3 ),
( 'CHAMP STAR 10N', 'productPool/1.jpg', 177 ),
( 'CHANA DAL 500G', 'productPool/1.jpg', 29 ),
( 'CHANA WHOLE 1 KG', 'productPool/1.jpg', 180 ),
( 'CHANDRA HANDWASH BOTTLE + POUCH', 'productPool/1.jpg', 188 ),
( 'CHANDRIKA 75GM GLOW', 'productPool/1.jpg', 32 ),
( 'CHANDRIKA AYURVEDIC HAIR OIL 200ML', 'productPool/1.jpg', 234 ),
( 'CHANDRIKA AYURVEDIC HAIR OIL 45ML', 'productPool/1.jpg', 251 ),
( 'CHANDRIKA AYURVEDIC SOAP 125G', 'productPool/1.jpg', 167 ),
( 'CHANDRIKA AYURVEDIC SOAP 3*75G SET', 'productPool/1.jpg', 106 ),
( 'CHANDRIKA AYURVEDIC SOAP 75G', 'productPool/1.jpg', 255 ),
( 'CHANDRIKA AYURVEDIC SOAP Buy 3 Get 2', 'productPool/1.jpg', 17 ),
( 'CHANDRIKA BUY 3 GET 1 GLY OFFER', 'productPool/1.jpg', 55 ),
( 'CHANDRIKA GLOW SOAP 300G', 'productPool/1.jpg', 160 ),
( 'CHANDRIKA GLYCERINE 100GM', 'productPool/1.jpg', 178 ),
( 'CHANDRIKA GLYCERINE SOAP 125G', 'productPool/1.jpg', 209 ),
( 'CHANDRIKA HAND WASH 180ML 2+1', 'productPool/1.jpg', 60 ),
( 'CHANDRIKA HANDWASH 7 ESSENTIAL HERBS', 'productPool/1.jpg', 8 ),
( 'CHANDRIKA HANDWASH180ML 3+1', 'productPool/1.jpg', 193 ),
( 'CHANDRIKA NEEM FACE WASH 100G', 'productPool/1.jpg', 188 ),
( 'CHANDRIKA NEEM FACEWASH 50G', 'productPool/1.jpg', 2 ),
( 'CHANDRIKA PAPAYA FACE WASH 50G', 'productPool/1.jpg', 137 ),
( 'CHANDRIKA REVITALIZING FACE WASH', 'productPool/1.jpg', 98 ),
( 'CHANDRIKA SOAP125G', 'productPool/1.jpg', 138 ),
( 'CHANDRIKA SUPER SAVER', 'productPool/1.jpg', 262 ),
( 'CHAPPATHI MALAYALI', 'productPool/1.jpg', 269 ),
( 'CHARCOL MASK +FW+ALOEVERA200G+100G', 'productPool/1.jpg', 97 ),
( 'CHECK POWDER 1KG ORANGE FRESH', 'productPool/1.jpg', 2 ),
( 'CHEEMA CHAKKA', 'productPool/1.jpg', 92 ),
( 'CHEEPAPPAM', 'productPool/1.jpg', 261 ),
( 'CHEERY LIQUID SHOE POLISH BLAck', 'productPool/1.jpg', 145 ),
( 'CHEESE HOT DOG', 'productPool/1.jpg', 47 ),
( 'CHEETOS CHEESE BALLS 30G', 'productPool/1.jpg', 21 ),
( 'CHEETOS CHEEZ PUFFS', 'productPool/1.jpg', 246 ),
( 'CHEETOS MASALA BALLS', 'productPool/1.jpg', 146 ),
( 'CHEETOS OCEAN SAFARI 30 GM', 'productPool/1.jpg', 163 ),
( 'CHEETOS TANGY LOOPS', 'productPool/1.jpg', 29 ),
( 'CHEK BAR 100GM', 'productPool/1.jpg', 120 ),
( 'CHEK BAR 200GMS', 'productPool/1.jpg', 206 ),
( 'CHEKOVETO UMBRELLA IMP', 'productPool/1.jpg', 193 ),
( 'CHELSEA ASSORTED TOFFEES 800G', 'productPool/1.jpg', 49 ),
( 'CHEMBU BIG', 'productPool/1.jpg', 273 ),
( 'CHEMBU SMALL', 'productPool/1.jpg', 176 ),
( 'CHERRY', 'productPool/1.jpg', 88 ),
( 'CHERRY 100G', 'productPool/1.jpg', 206 ),
( 'CHERRY BERRY PLUM CAKE 650G', 'productPool/1.jpg', 193 ),
( 'CHERRY BLACK 40G', 'productPool/1.jpg', 229 ),
( 'CHERRY BLACK HANDY SHINE', 'productPool/1.jpg', 30 ),
( 'CHERRY BLOSSOM BLACK 15G', 'productPool/1.jpg', 14 ),
( 'CHERRY BLOSSOM BLACK 40G', 'productPool/1.jpg', 218 ),
( 'CHERRY BLOSSOM DARK TAN 15G', 'productPool/1.jpg', 154 ),
( 'CHERRY BLOSSOM NEUTRAL HANDY SHINE 1N', 'productPool/1.jpg', 42 ),
( 'CHERRY DARK TAN LIQUID SHOE POLISH 75ML', 'productPool/1.jpg', 94 ),
( 'CHERRY DUMBER', 'productPool/1.jpg', 196 ),
( 'CHERRY HANDY SHINE', 'productPool/1.jpg', 133 ),
( 'CHERRY LIQUID DARKTAN 75ML', 'productPool/1.jpg', 225 ),
( 'CHERRY LIQUID SHOE POLISH BLACK', 'productPool/1.jpg', 249 ),
( 'CHERRY RED TIN', 'productPool/1.jpg', 252 ),
( 'CHERRY SHOES POLISH DARK TAN 40G', 'productPool/1.jpg', 3 ),
( 'CHERRY WHITE CLENER', 'productPool/1.jpg', 179 ),
( 'CHERUPAYAR 500G', 'productPool/1.jpg', 113 ),
( 'CHERUPAYAR DAL 500G', 'productPool/1.jpg', 136 ),
( 'CHEWING GUM 5STICK', 'productPool/1.jpg', 156 ),
( 'CHICKEN HOT DOG', 'productPool/1.jpg', 178 ),
( 'CHICKEN LUNCHEON 340GM IMP', 'productPool/1.jpg', 133 ),
( 'CHICKEN MASALA 100G', 'productPool/1.jpg', 80 ),
( 'CHICKEN MAYONNAISE', 'productPool/1.jpg', 122 ),
( 'CHICKEN TIKKA ROLL', 'productPool/1.jpg', 269 ),
( 'CHICKPEA DESHI SMALL 500G', 'productPool/1.jpg', 79 ),
( 'CHICKPEA KABULI DOLLAR 1 KG', 'productPool/1.jpg', 167 ),
( 'CHICKPEA KABULI DOLLAR 500G', 'productPool/1.jpg', 181 ),
( 'CHIEF MINISTER WASHING BRUSH', 'productPool/1.jpg', 53 ),
( 'CHIINU FOODS MADAKKU BOLLY 1P', 'productPool/1.jpg', 183 ),
( 'CHIKO ASSORTED TOFFEE 365G', 'productPool/1.jpg', 190 ),
( 'CHIKO BUTTER TOPS 800G', 'productPool/1.jpg', 54 ),
( 'CHIKO CHOCOLATE 750G', 'productPool/1.jpg', 250 ),
( 'CHIKO CHOCOLATE ECLAIRS 800G', 'productPool/1.jpg', 119 ),
( 'CHIKO ECLAIRS 350GM', 'productPool/1.jpg', 175 ),
( 'CHIKO ECLAIRS 825G SQUARE', 'productPool/1.jpg', 157 ),
( 'CHIKO ECLAIRS ASSORTED 325G', 'productPool/1.jpg', 132 ),
( 'CHIKO ECLAIRS CHOCOLATE400G', 'productPool/1.jpg', 180 ),
( 'CHIKO ECLAIRS HAZELNUT 400G', 'productPool/1.jpg', 271 ),
( 'CHIKO ECLAIRS HAZELNUT 750G', 'productPool/1.jpg', 279 ),
( 'CHIKO ECLAIRS HONEY 750G', 'productPool/1.jpg', 44 ),
( 'CHIKO ECLAIRS HONEY IMP 400G', 'productPool/1.jpg', 64 ),
( 'CHIKO ECLAIRS IMP 415G', 'productPool/1.jpg', 255 ),
( 'CHIKO ECLAIRS IMP 450GM', 'productPool/1.jpg', 13 ),
( 'CHIKO ECLAIRS MILK IMP 400G', 'productPool/1.jpg', 245 ),
( 'CHIKO ECLAIRS OVAL 365G', 'productPool/1.jpg', 24 ),
( 'CHIKO KOFFY 750G', 'productPool/1.jpg', 247 ),
( 'CHIKO KOKONATE COCONUT CARAMELS800G', 'productPool/1.jpg', 86 ),
( 'CHIKO MILK ECLAIR 750G', 'productPool/1.jpg', 186 ),
( 'CHIKO MILK ECLAIRS 415G', 'productPool/1.jpg', 121 ),
( 'CHIKO MILKIES ASSSORTED 800G', 'productPool/1.jpg', 246 ),
( 'CHIKO ROYALE CARAMELS 800GM', 'productPool/1.jpg', 25 ),
( 'CHIKO ROYALE CARDAMOM TOFFEE 800GM', 'productPool/1.jpg', 158 ),
( 'CHILLY PANDI PREMIUM 500GMS', 'productPool/1.jpg', 17 ),
( 'CHILLY PIRIYAN 500G', 'productPool/1.jpg', 50 ),
( 'CHILLY SAUCE 200G', 'productPool/1.jpg', 122 ),
( 'CHINGS CHOWMEIN HAKKA NOODLES MASALA 50G', 'productPool/1.jpg', 266 ),
( 'CHINGS GREEN CHILLI SAUCE 200', 'productPool/1.jpg', 89 ),
( 'CHINGS HOT GARLIC NOODILES 240G', 'productPool/1.jpg', 209 ),
( 'CHINGS MANCHURIAN NOODLES 300', 'productPool/1.jpg', 204 ),
( 'CHINGS MANCHURIAN NOODLES 60G', 'productPool/1.jpg', 116 ),
( 'CHINGS SCHEZWAN NOODLES 240G', 'productPool/1.jpg', 45 ),
( 'CHINGS SCHEZWAN NOODLES 60G', 'productPool/1.jpg', 145 ),
( 'CHINGS SINGAPORE CURRY NOODLES 240G', 'productPool/1.jpg', 18 ),
( 'CHINGS SOYA SAUCE 200G', 'productPool/1.jpg', 36 ),
( 'CHINGS TOMATTO KETCHUP 90G', 'productPool/1.jpg', 26 ),
( 'CHIRSTMAS LIGHT 108 LED', 'productPool/1.jpg', 181 ),
( 'CHIRSTMAS LIGHT 160 LED', 'productPool/1.jpg', 40 ),
( 'CHIRSTMAS LIGHT 24 LED', 'productPool/1.jpg', 20 ),
( 'CHIRSTMAS LIGHT 36 LED', 'productPool/1.jpg', 237 ),
( 'CHITRA CAMPHOR 10G', 'productPool/1.jpg', 194 ),
( 'CHITRA CAMPHOR 35G SQUARE', 'productPool/1.jpg', 224 ),
( 'CHITRA CAMPHOR 50G JAR', 'productPool/1.jpg', 230 ),
( 'CHITRA CAMPHOR 6G', 'productPool/1.jpg', 210 ),
( 'CHITRA PURE CAMPHOOR SQUARE 35G', 'productPool/1.jpg', 215 ),
( 'CHITRA PURE CAMPHOR 30G PKT', 'productPool/1.jpg', 92 ),
( 'CHITRA PURE CAMPHOR 50G', 'productPool/1.jpg', 123 ),
( 'CHITRA PURE CAMPHORE 10G', 'productPool/1.jpg', 266 ),
( 'CHNA BESAN 500G', 'productPool/1.jpg', 23 ),
( 'CHOCLAIRS 196G', 'productPool/1.jpg', 218 ),
( 'CHOCO FUNDOO BALL', 'productPool/1.jpg', 117 ),
( 'CHOCO ROYALE FRUIT BAR CARAMEL25G', 'productPool/1.jpg', 19 ),
( 'CHOCO ROYALE FRUIT BAR ENGLISH TOFFEE 25G', 'productPool/1.jpg', 59 ),
( 'CHOCO ROYALE FRUIT BAR HAZELNUT 25G', 'productPool/1.jpg', 34 ),
( 'CHOCO ROYALE FRUIT BAR HONEY 25G', 'productPool/1.jpg', 184 ),
( 'CHOCO ROYALE FRUIT BAR ORANGE 25G', 'productPool/1.jpg', 63 ),
( 'CHOCO ROYALE FRUIT BAR STRAWBERRY 25G', 'productPool/1.jpg', 131 ),
( 'CHOCO SYRUP GENUINE 600G', 'productPool/1.jpg', 119 ),
( 'CHOCOLATE 1KG', 'productPool/1.jpg', 51 ),
( 'CHOCOLATE 500G', 'productPool/1.jpg', 126 ),
( 'CHOCOLATE DILKUSH', 'productPool/1.jpg', 164 ),
( 'CHOCOLATE GIFT BASKET 1150G', 'productPool/1.jpg', 272 ),
( 'CHOCOLATE GIFT BOX BIG 1050G', 'productPool/1.jpg', 164 ),
( 'CHOCOLATE GIFT BOX MEDIUM 740G', 'productPool/1.jpg', 10 ),
( 'CHOCOLATE GIFT BOX SMALL 530G', 'productPool/1.jpg', 204 ),
( 'CHOCOLATE MOOSE', 'productPool/1.jpg', 279 ),
( 'CHOCOLATE SKORE CONDOMS80R', 'productPool/1.jpg', 68 ),
( 'CHOCOLATE TRUFFLE PASTRY', 'productPool/1.jpg', 152 ),
( 'CHOCOS 27G', 'productPool/1.jpg', 93 ),
( 'CHOKORETO IMP', 'productPool/1.jpg', 163 ),
( 'CHOW CHOW', 'productPool/1.jpg', 211 ),
( 'CHOWARI 100G', 'productPool/1.jpg', 20 ),
( 'CHOWARI 1KG', 'productPool/1.jpg', 16 ),
( 'CHOWARI 200G', 'productPool/1.jpg', 101 ),
( 'CHOWARI 500G', 'productPool/1.jpg', 160 ),
( 'CHRISTMAS LIGHT 48 LED', 'productPool/1.jpg', 279 ),
( 'CHRISTMAS LIGHT 58 LED', 'productPool/1.jpg', 200 ),
( 'CHRISTMAS LIGHT 60 LED', 'productPool/1.jpg', 43 ),
( 'CHRISTMAS LIGHT 68 LED', 'productPool/1.jpg', 207 ),
( 'CHRISTMAS LIGHT RS100', 'productPool/1.jpg', 277 ),
( 'CHRISTMAS LIGHT RS175', 'productPool/1.jpg', 90 ),
( 'CHRISTMAS LIGHT RS190', 'productPool/1.jpg', 160 ),
( 'CHRISTMAS LIGHT RS275', 'productPool/1.jpg', 224 ),
( 'CHRISTMAS LIGHT RS460', 'productPool/1.jpg', 99 ),
( 'CHRISTMAS LIGHT RS550', 'productPool/1.jpg', 78 ),
( 'CHRISTMAS LIGHT RS65', 'productPool/1.jpg', 89 ),
( 'CHRISTMAS LIGHT RS75', 'productPool/1.jpg', 62 ),
( 'CHRISTMAS LIGHT RS90', 'productPool/1.jpg', 167 ),
( 'CHRISTMAS LIGHT RS95', 'productPool/1.jpg', 5 ),
( 'CHUKKU KARUPPOTTI 200G', 'productPool/1.jpg', 271 ),
( 'CHURCH CANDLE RS 40', 'productPool/1.jpg', 61 ),
( 'CIF ALL PURPOSE CLEANER 5L', 'productPool/1.jpg', 259 ),
( 'CIF FLIOOR CLEANER CAMOMILE 1L', 'productPool/1.jpg', 136 ),
( 'CIF FLIOOR CLEANER OCEAN 1L', 'productPool/1.jpg', 168 ),
( 'CIF FLIOOR CLEANER WILD ORCHID 1L', 'productPool/1.jpg', 16 ),
( 'CIF FLOOR CLEANER 5L', 'productPool/1.jpg', 93 ),
( 'CIGARTTE LIGHTER', 'productPool/1.jpg', 145 ),
( 'CIGARTTE LIGHTER RS7.50', 'productPool/1.jpg', 132 ),
( 'CINTHOL COFIDENCE 225G', 'productPool/1.jpg', 93 ),
( 'CINTHOL CONFIDENCE 100GM SINGLE', 'productPool/1.jpg', 22 ),
( 'CINTHOL CONFIDENCE SOAP 50G', 'productPool/1.jpg', 32 ),
( 'CINTHOL CONFIDENCE TALC 300G', 'productPool/1.jpg', 136 ),
( 'CINTHOL COOL 100GM SINGLE', 'productPool/1.jpg', 21 ),
( 'CINTHOL COOL SOAP 50G HANGER', 'productPool/1.jpg', 274 ),
( 'CINTHOL COOLTAL 300G', 'productPool/1.jpg', 227 ),
( 'CINTHOL DEO 100G', 'productPool/1.jpg', 11 ),
( 'CINTHOL DEO SHOT DIVE 25ML', 'productPool/1.jpg', 94 ),
( 'CINTHOL DEO SHOT ENERGY 25ML', 'productPool/1.jpg', 80 ),
( 'CINTHOL DEO SHOT RUSH 25ML', 'productPool/1.jpg', 271 ),
( 'CINTHOL DEO SPRAY 150ML', 'productPool/1.jpg', 224 ),
( 'CINTHOL DEO STICK 3 X RUSH', 'productPool/1.jpg', 209 ),
( 'CINTHOL DEO TALC 300G', 'productPool/1.jpg', 104 ),
( 'CINTHOL DEOSTICK 3X INTENSE MEN', 'productPool/1.jpg', 66 ),
( 'CINTHOL DEOSTICK 3X SPARK WOMEN', 'productPool/1.jpg', 175 ),
( 'CINTHOL ENERGY SPRAY 100G', 'productPool/1.jpg', 5 ),
( 'CINTHOL EXTREME DEO SPARY 150ML', 'productPool/1.jpg', 192 ),
( 'CINTHOL INTENSE DEO SPRAY 150ML', 'productPool/1.jpg', 182 ),
( 'CINTHOL LIME DEO SOAP 30 GMS', 'productPool/1.jpg', 188 ),
( 'CINTHOL LIME FRESH 75G (P04)', 'productPool/1.jpg', 81 ),
( 'CINTHOL LIME FRESH SINGEL 100G', 'productPool/1.jpg', 64 ),
( 'CINTHOL LIME TALC 100G', 'productPool/1.jpg', 33 ),
( 'CINTHOL LIME TALC 300G', 'productPool/1.jpg', 210 ),
( 'CINTHOL ORGINAL TALC 100G', 'productPool/1.jpg', 40 ),
( 'CINTHOL ORGINAL TALC 300G', 'productPool/1.jpg', 38 ),
( 'CINTHOL ORIGINAL 3*1 400G', 'productPool/1.jpg', 27 ),
( 'CINTHOL ORIGINAL SOAP 675G B4G1', 'productPool/1.jpg', 172 ),
( 'CINTHOL ORIGINAL SOAP100GM', 'productPool/1.jpg', 24 ),
( 'CINTHOL PLAY SPRY 100G', 'productPool/1.jpg', 21 ),
( 'CINTHOL WOMAN JIVE SKIN SAFE 150 ML', 'productPool/1.jpg', 173 ),
( 'CINTHOL WOMAN SPARK SKIN SAFE 150 ML', 'productPool/1.jpg', 147 ),
( 'CINTHOL WOMAN SPIN SAFE 150 ML', 'productPool/1.jpg', 113 ),
( 'CINTHOL WOMEN DEO STICK INSPIRE 40G', 'productPool/1.jpg', 113 ),
( 'CINTHOL WOMEN DEOSTICK 3 X', 'productPool/1.jpg', 8 ),
( 'CINTHOLCOOL TALC 100G', 'productPool/1.jpg', 94 ),
( 'CINTL COOL SET SOAP 225G', 'productPool/1.jpg', 264 ),
( 'CINTOL DEO SET SOAP 225G', 'productPool/1.jpg', 48 ),
( 'CINTU MANGO CANDY', 'productPool/1.jpg', 71 ),
( 'CINTU STAR POP LOLLIPOPS', 'productPool/1.jpg', 260 ),
( 'CITRUS ORANGE', 'productPool/1.jpg', 270 ),
( 'CK APRICOT SCRUB 250G', 'productPool/1.jpg', 95 ),
( 'CLASS MATE STICK BEETHOVAN BLCK PEN', 'productPool/1.jpg', 92 ),
( 'CLASSMATE 1142 MATHS RULED', 'productPool/1.jpg', 7 ),
( 'CLASSMATE ARCHIMEDES INSTRUMENT BOX', 'productPool/1.jpg', 31 ),
( 'CLASSMATE CARBON BLACK PENCIL 20003NP', 'productPool/1.jpg', 156 ),
( 'CLASSMATE CLUTCH MECHANICAL PENCIL 20022', 'productPool/1.jpg', 185 ),
( 'CLASSMATE CRIPTOZIP BLACK PEN 30146', 'productPool/1.jpg', 30 ),
( 'CLASSMATE CRIPTOZIP BLUE PEN 30145', 'productPool/1.jpg', 276 ),
( 'CLASSMATE DRAWING BOOK 193 40PAGES', 'productPool/1.jpg', 209 ),
( 'CLASSMATE DRAWING BOOK 194', 'productPool/1.jpg', 102 ),
( 'CLASSMATE DRAWING BOOK 195', 'productPool/1.jpg', 266 ),
( 'CLASSMATE FINE SCRIPT PENCIL 20006', 'productPool/1.jpg', 213 ),
( 'CLASSMATE GRAPH BOOK 245', 'productPool/1.jpg', 124 ),
( 'CLASSMATE GRAPH BOOK 246', 'productPool/1.jpg', 202 ),
( 'CLASSMATE INVENTO BOX', 'productPool/1.jpg', 182 ),
( 'CLASSMATE INVENTO INSTRUMENT BOX', 'productPool/1.jpg', 255 ),
( 'CLASSMATE LONG NOTE BOOK RULED 984', 'productPool/1.jpg', 279 ),
( 'CLASSMATE LONG NOTEBOOK UNRULED 985', 'productPool/1.jpg', 20 ),
( 'CLASSMATE MATHS BOOK 1202', 'productPool/1.jpg', 264 ),
( 'CLASSMATE MATHS RULED 593', 'productPool/1.jpg', 41 ),
( 'CLASSMATE MECHANICAL PENCIL 20017', 'productPool/1.jpg', 47 ),
( 'CLASSMATE MECHANICAL PENCIL 20019', 'productPool/1.jpg', 7 ),
( 'CLASSMATE MECHANICAL PENCIL 20024', 'productPool/1.jpg', 213 ),
( 'CLASSMATE MECHANICAL PENCIL 20032', 'productPool/1.jpg', 192 ),
( 'CLASSMATE NOTE BOOK 946QU 240*180 PAGE', 'productPool/1.jpg', 79 ),
( 'CLASSMATE NOTE BOOK FOUR LINE 1006', 'productPool/1.jpg', 232 ),
( 'CLASSMATE NOTE BOOK FOUR LINE 226', 'productPool/1.jpg', 206 ),
( 'CLASSMATE NOTE BOOK FOUR LINE 239', 'productPool/1.jpg', 10 ),
( 'CLASSMATE NOTE BOOK FOUR LINE 257', 'productPool/1.jpg', 184 ),
( 'CLASSMATE NOTE BOOK FOUR LINE 967', 'productPool/1.jpg', 48 ),
( 'CLASSMATE NOTE BOOK FOURLINE 92PAGES 1003', 'productPool/1.jpg', 36 ),
( 'CLASSMATE NOTE BOOK MATHS 597', 'productPool/1.jpg', 247 ),
( 'CLASSMATE NOTE BOOK RULED 1100', 'productPool/1.jpg', 67 ),
( 'CLASSMATE NOTE BOOK RULED 199', 'productPool/1.jpg', 48 ),
( 'CLASSMATE NOTE BOOK RULED 205', 'productPool/1.jpg', 43 ),
( 'CLASSMATE NOTE BOOK RULED 211', 'productPool/1.jpg', 83 ),
( 'CLASSMATE NOTE BOOK RULED 238', 'productPool/1.jpg', 245 ),
( 'CLASSMATE NOTE BOOK RULED 240', 'productPool/1.jpg', 210 ),
( 'CLASSMATE NOTE BOOK RULED 256', 'productPool/1.jpg', 49 ),
( 'CLASSMATE NOTE BOOK RULED 261', 'productPool/1.jpg', 27 ),
( 'CLASSMATE NOTE BOOK SINGLE LINE 1132', 'productPool/1.jpg', 80 ),
( 'CLASSMATE NOTE BOOK SINGLE LINE 207', 'productPool/1.jpg', 110 ),
( 'CLASSMATE NOTE BOOK SQUARE 224', 'productPool/1.jpg', 136 ),
( 'CLASSMATE NOTE BOOK SQUIRE 1008', 'productPool/1.jpg', 23 ),
( 'CLASSMATE NOTE BOOK SUARE 242', 'productPool/1.jpg', 220 ),
( 'CLASSMATE NOTE BOOK TWO LINE 1007', 'productPool/1.jpg', 193 ),
( 'CLASSMATE NOTE BOOK TWO LINE 223', 'productPool/1.jpg', 99 ),
( 'CLASSMATE NOTE BOOK TWO LINE 258', 'productPool/1.jpg', 29 ),
( 'CLASSMATE NOTE BOOK TWO LINE 92PAGES1004', 'productPool/1.jpg', 106 ),
( 'CLASSMATE NOTE BOOK TWO LINE BIG 120PAGES', 'productPool/1.jpg', 199 ),
( 'CLASSMATE NOTE BOOK UNRULED 1101', 'productPool/1.jpg', 261 ),
( 'CLASSMATE NOTE BOOK UNRULED 1133', 'productPool/1.jpg', 68 ),
( 'CLASSMATE NOTE BOOK UNRULED 140PAGES200', 'productPool/1.jpg', 271 ),
( 'CLASSMATE NOTE BOOK UNRULED 206', 'productPool/1.jpg', 258 ),
( 'CLASSMATE NOTE BOOK UNRULED 212', 'productPool/1.jpg', 255 ),
( 'CLASSMATE NOTE BOOK UNRULED 222', 'productPool/1.jpg', 88 ),
( 'CLASSMATE NOTE BOOK UNRULED 243', 'productPool/1.jpg', 238 ),
( 'CLASSMATE NOTE BOOK UNRULED 92PAGES 208', 'productPool/1.jpg', 73 ),
( 'CLASSMATE NOTE BOOKS MATHS 1141', 'productPool/1.jpg', 4 ),
( 'CLASSMATE NOTEBOOK 240P ONE RULED', 'productPool/1.jpg', 182 ),
( 'CLASSMATE NOTEBOOK MATHS UNRULED 1041', 'productPool/1.jpg', 234 ),
( 'CLASSMATE NOTEBOOK RULED 986', 'productPool/1.jpg', 30 ),
( 'CLASSMATE NOTEBOOK UNRULED 260', 'productPool/1.jpg', 148 ),
( 'CLASSMATE OCTAEN GEL BLACK PEN 403011', 'productPool/1.jpg', 241 ),
( 'CLASSMATE OCTANE GEL PEN RED', 'productPool/1.jpg', 256 ),
( 'CLASSMATE OCTO GLIDE GEL PEN 30143Y', 'productPool/1.jpg', 45 ),
( 'CLASSMATE OIL PASTELS 15 SHDES', 'productPool/1.jpg', 35 ),
( 'CLASSMATE OIL PASTELS 30005 12 COLOUR', 'productPool/1.jpg', 195 ),
( 'CLASSMATE OILPASTE CRAYONS', 'productPool/1.jpg', 99 ),
( 'CLASSMATE PLASTIC CRAYONS 16SHADES', 'productPool/1.jpg', 142 ),
( 'CLASSMATE PLASTIC CRAYONS 26 SHADES', 'productPool/1.jpg', 255 ),
( 'CLASSMATE POCKET MEMO', 'productPool/1.jpg', 104 ),
( 'CLASSMATE RULED LONG BOOK 330', 'productPool/1.jpg', 22 ),
( 'CLASSMATE SCRAP BOOK 1229', 'productPool/1.jpg', 225 ),
( 'CLASSMATE SINGLE LINE BOOK 1005', 'productPool/1.jpg', 39 ),
( 'CLASSMATE SMOOTHIE FOUNTAIN INK PEN', 'productPool/1.jpg', 104 ),
( 'CLASSMATE SOFT UNRULED 299 120 PAGES', 'productPool/1.jpg', 23 ),
( 'CLASSMATE STICK BEETHOVAN BLUE', 'productPool/1.jpg', 271 ),
( 'CLASSMATE UNRULEDLONG BOOK 197', 'productPool/1.jpg', 48 ),
( 'CLASSMATE VICTOR INSTRUMENT BOX', 'productPool/1.jpg', 205 ),
( 'CLASSMATE WAX CRAYONS 500010', 'productPool/1.jpg', 62 ),
( 'CLASSMATE WAX CRAYONS 50002NP', 'productPool/1.jpg', 129 ),
( 'CLASSMATE WAX CRAYONS 50003', 'productPool/1.jpg', 24 ),
( 'CLASSMATE WAX CRAYONS 500041', 'productPool/1.jpg', 25 ),
( 'CLASSMATE WAX CRAYONS 50005', 'productPool/1.jpg', 198 ),
( 'CLASSMATES HB PENCIL 20048', 'productPool/1.jpg', 151 ),
( 'CLASSMATES NOTE BOOK RULED 221', 'productPool/1.jpg', 92 ),
( 'CLASSMATES SKETCH PEN 2001', 'productPool/1.jpg', 8 ),
( 'CLASSY CRUNCHY COCONUT CANDY JAR', 'productPool/1.jpg', 117 ),
( 'CLASSY PEANUT CHIKKY CANDY JAR', 'productPool/1.jpg', 72 ),
( 'CLEAN & CLEAR APPLE FACEWASH 100ML', 'productPool/1.jpg', 189 ),
( 'CLEAN & CLEAR BERRY FACE WASH 100ML', 'productPool/1.jpg', 120 ),
( 'CLEAN & CLEAR ORIGINAL FACE WASH 50ML', 'productPool/1.jpg', 277 ),
( 'CLEAN & CLEAR ORIGINAL FOAMING FACEWASH 100ML', 'productPool/1.jpg', 138 ),
( 'CLEAN &CLEAR AQUA SPLASH FACE WASH 100ML', 'productPool/1.jpg', 91 ),
( 'CLEAN &CLEAR LEMON FRESH 100ML', 'productPool/1.jpg', 116 ),
( 'CLEAN &CLEAR LEMON FRESH 50ML', 'productPool/1.jpg', 142 ),
( 'CLEAN &CLEAR MORNING ENERGY BERRY 100ML', 'productPool/1.jpg', 251 ),
( 'CLEAN AND CLEAR AQUA SPLASH FACE WASH 50ML', 'productPool/1.jpg', 72 ),
( 'CLEAN AND CLEAR BERRY BLAST FACEWASH 50ML', 'productPool/1.jpg', 59 ),
( 'CLEAN AND CLEAR FAIRNESS CREAM 40G', 'productPool/1.jpg', 273 ),
( 'CLEAN AND CLEAR FOAMING FACE WASH 100ML', 'productPool/1.jpg', 116 ),
( 'CLEAN AND CLEAR FOAMING FACE WASH 50ML', 'productPool/1.jpg', 55 ),
( 'CLEAN CLEAR FACEWASH BERRY 50ML', 'productPool/1.jpg', 128 ),
( 'CLEAN&CLEAR FAIRNESS FACE WASH 40G', 'productPool/1.jpg', 218 ),
( 'CLEANING CLOTH', 'productPool/1.jpg', 221 ),
( 'CLEANO HERBAL CLEANING CON. 1LTR', 'productPool/1.jpg', 240 ),
( 'CLEANO HERBAL CLEANING CON. 500G', 'productPool/1.jpg', 179 ),
( 'CLEAR & CLEAR LEMON 100ML', 'productPool/1.jpg', 104 ),
( 'CLEAR ANTI DANDRUFF COMPLETE ACTIVE CARE 170ML', 'productPool/1.jpg', 1 ),
( 'CLEAR ANTI DANDRUFF HAIR OIL 150ML', 'productPool/1.jpg', 152 ),
( 'CLEAR ANTI HAIR FALL SHAMPOO', 'productPool/1.jpg', 183 ),
( 'CLEAR COMPLETE ACTIVE CARE 80ML', 'productPool/1.jpg', 241 ),
( 'CLEAR MORNING LEMON FW 50ML', 'productPool/1.jpg', 278 ),
( 'CLEAR&CLEAR FACE WASH APPLE 50ML', 'productPool/1.jpg', 94 ),
( 'CLEARANTI-DANDRFF SHAMPOO170ML', 'productPool/1.jpg', 31 ),
( 'CLENZ U CHARCOAL NOSE STRIP 3STRIP', 'productPool/1.jpg', 204 ),
( 'CLENZ U CLEANSING GREEN TEA NOSE STRIPS', 'productPool/1.jpg', 164 ),
( 'CLENZ U CLEANSING ROSE NOSE STRIPS', 'productPool/1.jpg', 115 ),
( 'CLENZ U COSMETIC COTTON BALLS 100PC', 'productPool/1.jpg', 78 ),
( 'CLENZ U COSMETIC COTTON PADS 50N', 'productPool/1.jpg', 22 ),
( 'CLENZ U COTTON BUDS 100 PIECES', 'productPool/1.jpg', 144 ),
( 'CLENZ U COTTON BUDS 200 PIECES', 'productPool/1.jpg', 41 ),
( 'CLENZ U MINI TISSUES 10N', 'productPool/1.jpg', 206 ),
( 'CLENZ U NOSE STRIPES 1S', 'productPool/1.jpg', 71 ),
( 'CLENZ U NOSE STRIPES 3S', 'productPool/1.jpg', 277 ),
( 'CLENZ U NOSE STRIPS CHARCOAL 1S', 'productPool/1.jpg', 71 ),
( 'CLENZ UDEEP CLEANSING GREEN TEA 3STRIP', 'productPool/1.jpg', 263 ),
( 'CLING FOIL 100MT', 'productPool/1.jpg', 185 ),
( 'CLINIC PLUS ANTI DANDRUFF 80ML', 'productPool/1.jpg', 273 ),
( 'CLINIC PLUS ANTI DANDRUFF SHAMPOO 175ML', 'productPool/1.jpg', 50 ),
( 'CLINIC PLUS AYURVEDA CARE SHAMPOO 650ML', 'productPool/1.jpg', 9 ),
( 'CLINIC PLUS AYURVEDACARE SHAMPOO 175ML', 'productPool/1.jpg', 193 ),
( 'CLINIC PLUS AYURVEDACARE SHAMPOO 80ML', 'productPool/1.jpg', 119 ),
( 'CLINIC PLUS CONDITIONER 80ML', 'productPool/1.jpg', 217 ),
( 'CLINIC PLUS HEALTH SHAMPOO30ML', 'productPool/1.jpg', 157 ),
( 'CLINIC PLUS HELTH SHAMPOO 80ML', 'productPool/1.jpg', 157 ),
( 'CLINIC PLUS NATUARALLY HEALTH SHAMPOO175ML', 'productPool/1.jpg', 17 ),
( 'CLINIC PLUS NATURAL STRONG HEALTH SHAMPOO 80ML', 'productPool/1.jpg', 145 ),
( 'CLINIC PLUS NATURALS SHAMPOO 175ML', 'productPool/1.jpg', 174 ),
( 'CLINIC PLUS STRONG & LONG SHAMPOO 340ML', 'productPool/1.jpg', 153 ),
( 'CLINIC PLUS STRONG & LONG SHAMPOO 650ML', 'productPool/1.jpg', 58 ),
( 'CLINIC PLUS STRONG and LONG SHAMPOO80ML', 'productPool/1.jpg', 19 ),
( 'CLINIC PLUS STRONG LONG HELTH SHAMPOO 175ML', 'productPool/1.jpg', 264 ),
( 'CLINIC PLUS STRONG LONG SHAMPOO 175ML', 'productPool/1.jpg', 170 ),
( 'CLINIC PLUS STRONG LONG SHAMPOO 80ML', 'productPool/1.jpg', 47 ),
( 'CLINIC PLUS STRONG SCALP 175ML', 'productPool/1.jpg', 171 ),
( 'CLINIC PLUS STRONG THICK 175ML SHAMPOO', 'productPool/1.jpg', 243 ),
( 'CLINIC PLUS STRONG THICK SHAMPOO 340ML', 'productPool/1.jpg', 54 ),
( 'CLIP BOARD', 'productPool/1.jpg', 127 ),
( 'CLIP BOARD 66', 'productPool/1.jpg', 161 ),
( 'CLIPPER LIGHTER', 'productPool/1.jpg', 37 ),
( 'CLORESSENCE INTENSE LIP COLOUR LCM-04', 'productPool/1.jpg', 201 ),
( 'CLOROX 500ML LEMON', 'productPool/1.jpg', 24 ),
( 'CLOROX ALL PURPOSE CLEANER 500ML', 'productPool/1.jpg', 72 ),
( 'CLOROX ANYWHERE HARD SURFACE 650ML', 'productPool/1.jpg', 111 ),
( 'CLOROX BATHROOM CLEANER SPARY 887ML', 'productPool/1.jpg', 122 ),
( 'CLOROX BLEACH ORIGINAL 4L', 'productPool/1.jpg', 186 ),
( 'CLOROX BLEACH PEN 56G', 'productPool/1.jpg', 168 ),
( 'CLOROX CLEAN UP 2L', 'productPool/1.jpg', 102 ),
( 'CLOROX CLINGING BLEACH GEL LEMON 709ML', 'productPool/1.jpg', 258 ),
( 'CLOROX CLINGING GEL BLEACH FRESH SCENT 709ML', 'productPool/1.jpg', 34 ),
( 'CLOROX CLINGING GEL BLEACH RAIN CLEAN 709ML', 'productPool/1.jpg', 163 ),
( 'CLOROX DISINFECTING WIPES FRESH SCENT35N', 'productPool/1.jpg', 8 ),
( 'CLOROX DISINFECTING WIPES LAVENDER 35N', 'productPool/1.jpg', 154 ),
( 'CLOROX DISINFECTING WIPES LEMON 35N', 'productPool/1.jpg', 224 ),
( 'CLOROX DISINFECTING WIPES ORANGE35N', 'productPool/1.jpg', 122 ),
( 'CLOROX IMP 470ML', 'productPool/1.jpg', 98 ),
( 'CLOROX KITCHEN CLEANER 500ML', 'productPool/1.jpg', 165 ),
( 'CLOROX LIQUID BLEACH 1L LAVENDER', 'productPool/1.jpg', 208 ),
( 'CLOROX LIQUID BLEACH LAVENDER 500ML', 'productPool/1.jpg', 208 ),
( 'CLOROX LIQUID BLEACH LEMON 1L', 'productPool/1.jpg', 5 ),
( 'CLOROX LIQUID BLEACH ORIGINAL 1L', 'productPool/1.jpg', 90 ),
( 'CLOROX LIQUID BLEACH ORIGINAL 2L', 'productPool/1.jpg', 252 ),
( 'CLOROX LIQUID BLEACH ORIGINAL 500ML', 'productPool/1.jpg', 110 ),
( 'CLOROX MOLD & MILDDEW REMOVER 500ML', 'productPool/1.jpg', 259 ),
( 'CLOROX TOILET BOWL STAIN REMOVER709ML', 'productPool/1.jpg', 18 ),
( 'CLOSE UP DEEPACT 150G MENTHOL', 'productPool/1.jpg', 246 ),
( 'CLOSE UP DEEPACTION PASTE80G', 'productPool/1.jpg', 152 ),
( 'CLOSE UP DEEPACTION RED PASTE150G', 'productPool/1.jpg', 73 ),
( 'CLOSE UP DI AMATRA 100G', 'productPool/1.jpg', 183 ),
( 'CLOSE UP FIFE FREEZE TP 150G', 'productPool/1.jpg', 23 ),
( 'CLOSE UP FIRE FREE 80G', 'productPool/1.jpg', 43 ),
( 'CLOSE UP PEPPERMINT SPLASH 150G', 'productPool/1.jpg', 115 ),
( 'CLOSEUP DIAMOND ATTRACTION 50G', 'productPool/1.jpg', 42 ),
( 'CLOSEUP EVER FRESH RED HOT 150G', 'productPool/1.jpg', 167 ),
( 'CLOSEUP EVER FRESH RED TOOTH PASTE 300G', 'productPool/1.jpg', 18 ),
( 'CLOSEUP EVER FRESH40G', 'productPool/1.jpg', 176 ),
( 'CLOSEUP LEMON MINT ACTIVE GEL 150G', 'productPool/1.jpg', 255 ),
( 'CLOSEUP PEPPERMINT SPLASH 80G', 'productPool/1.jpg', 17 ),
( 'CLOSEUP TOOTHPASTE 40G REDHOT', 'productPool/1.jpg', 242 ),
( 'CLOTH BRUSH RS 14', 'productPool/1.jpg', 23 ),
( 'CLOTH BRUSH RS 16.50', 'productPool/1.jpg', 11 ),
( 'CLOTH BRUSH RS 25.50', 'productPool/1.jpg', 90 ),
( 'CLOTH BRUSH RS 33', 'productPool/1.jpg', 167 ),
( 'CLOTH BRUSH RS 35', 'productPool/1.jpg', 269 ),
( 'CLOTH BRUSH RS 45', 'productPool/1.jpg', 29 ),
( 'CLOTH BRUSH RS11', 'productPool/1.jpg', 131 ),
( 'CLOTH BRUSH RS18', 'productPool/1.jpg', 136 ),
( 'CLOTH BRUSH RS22', 'productPool/1.jpg', 131 ),
( 'CLOTH BRUSH RS25', 'productPool/1.jpg', 150 ),
( 'CLOTH BRUSH RS30', 'productPool/1.jpg', 248 ),
( 'CLOTH BRUSH RS48', 'productPool/1.jpg', 235 ),
( 'CLOTH BRUSH RS52', 'productPool/1.jpg', 206 ),
( 'CLOTH CLIP 2 FAMILY', 'productPool/1.jpg', 194 ),
( 'CLOTH CLIP IMP RS 36', 'productPool/1.jpg', 72 ),
( 'CLOTH CLIP IMP RS 37.50', 'productPool/1.jpg', 103 ),
( 'CLOTH CLIP IMP RS 42', 'productPool/1.jpg', 168 ),
( 'CLOTH CLIP IMP RS 48', 'productPool/1.jpg', 14 ),
( 'CLOTH CLIP IMP RS39', 'productPool/1.jpg', 167 ),
( 'CLOTH CLIP NO 1 12P SET', 'productPool/1.jpg', 51 ),
( 'CLOTH CLIP RS 18', 'productPool/1.jpg', 195 ),
( 'CLOTH CLIP RS 30', 'productPool/1.jpg', 133 ),
( 'CLOTH CLIP RS 33', 'productPool/1.jpg', 178 ),
( 'CLOTH CLIP RS 45', 'productPool/1.jpg', 32 ),
( 'CLOTH CLIP RS 54', 'productPool/1.jpg', 18 ),
( 'CLOTH CLIP RS 60', 'productPool/1.jpg', 119 ),
( 'CLOTH CLIP RS 63', 'productPool/1.jpg', 78 ),
( 'CLOTH CLIP RS14.50', 'productPool/1.jpg', 123 ),
( 'CLOTH CLIP RS18', 'productPool/1.jpg', 29 ),
( 'CLOTH CLIP RS33', 'productPool/1.jpg', 119 ),
( 'CLOTH CLIP RS35', 'productPool/1.jpg', 54 ),
( 'CLOTH CLIP RS48', 'productPool/1.jpg', 97 ),
( 'CLOTH CLIP RS57', 'productPool/1.jpg', 55 ),
( 'CLOTH ROPE (B)', 'productPool/1.jpg', 251 ),
( 'CLOTH ROPE 20M', 'productPool/1.jpg', 241 ),
( 'CLOTH ROPE RS19.50', 'productPool/1.jpg', 27 ),
( 'CLOTH ROPE RS39', 'productPool/1.jpg', 167 ),
( 'CLOVE OIL 2ML', 'productPool/1.jpg', 167 ),
( 'CNA BACK SCRATCHER PIPE', 'productPool/1.jpg', 222 ),
( 'CNA BASIN BRUSH BIG', 'productPool/1.jpg', 111 ),
( 'CNA BASIN BRUSH SMALL', 'productPool/1.jpg', 84 ),
( 'CNA BOTTLE BRUSH (MOON SHIP)', 'productPool/1.jpg', 125 ),
( 'CNA BOTTLE BRUSH ORD(SMALL)', 'productPool/1.jpg', 39 ),
( 'CNA CAKE DECORATER', 'productPool/1.jpg', 238 ),
( 'CNA CAKE DECORATER AND KNIFE', 'productPool/1.jpg', 251 ),
( 'CNA CAKE DECORATER WF', 'productPool/1.jpg', 173 ),
( 'CNA HOOK 3PCS NEW', 'productPool/1.jpg', 215 ),
( 'CNA HOOK STEEL (4PCS)', 'productPool/1.jpg', 133 ),
( 'CNA LANDRY BASKET SMALL', 'productPool/1.jpg', 100 ),
( 'CNA SCORING PAD 4PCS', 'productPool/1.jpg', 157 ),
( 'CNA SCRUBBER COLOR (LIGHT) 4PCS', 'productPool/1.jpg', 250 ),
( 'CNA SS PEELER', 'productPool/1.jpg', 40 ),
( 'CNA.SCORING PAD JUMBO', 'productPool/1.jpg', 38 ),
( 'COCA COLA 330ML', 'productPool/1.jpg', 274 ),
( 'COCA-COLA 300ML', 'productPool/1.jpg', 143 ),
( 'COCA-COLA ZERO 300ML', 'productPool/1.jpg', 98 ),
( 'COCCO POWDER 100 GMS', 'productPool/1.jpg', 276 ),
( 'COCKER BONE 2-1', 'productPool/1.jpg', 231 ),
( 'COCKER BONE SINGLE QTY -1', 'productPool/1.jpg', 84 ),
( 'COCKER CHEW STICK RS40', 'productPool/1.jpg', 13 ),
( 'COCKER CHEW STICK RS70', 'productPool/1.jpg', 118 ),
( 'COCKER LONG CHAIN 135', 'productPool/1.jpg', 213 ),
( 'COCKER LONG CHAIN 150', 'productPool/1.jpg', 27 ),
( 'COCKER LONG CHAIN 180', 'productPool/1.jpg', 19 ),
( 'COCKER LONG CHAIN 190', 'productPool/1.jpg', 65 ),
( 'COCKER LONG CHAIN 250', 'productPool/1.jpg', 260 ),
( 'COCKER LONG CHAIN 370', 'productPool/1.jpg', 60 ),
( 'COCKER LONG CHAIN 430', 'productPool/1.jpg', 116 ),
( 'COCKER LONG CHAIN 450', 'productPool/1.jpg', 55 ),
( 'COCKER PADDED COLLAR 125', 'productPool/1.jpg', 160 ),
( 'COCKER PADDED COLLAR 150', 'productPool/1.jpg', 131 ),
( 'COCKER PADDED COLLAR 185', 'productPool/1.jpg', 46 ),
( 'COCKER PADDED COLLAR 55', 'productPool/1.jpg', 56 ),
( 'COCKER PADDED COLLAR 70', 'productPool/1.jpg', 204 ),
( 'COCKER PADDED COLLAR 90', 'productPool/1.jpg', 247 ),
( 'COCO VINEGAR 480ML', 'productPool/1.jpg', 205 ),
( 'COCOA POWDER 50G', 'productPool/1.jpg', 137 ),
( 'COCON JELLY 118G', 'productPool/1.jpg', 225 ),
( 'COCON JELLY JAR 1500G', 'productPool/1.jpg', 161 ),
( 'COCON PUDDING 3 CUP', 'productPool/1.jpg', 7 ),
( 'COCON PUDDING 6 PCS', 'productPool/1.jpg', 279 ),
( 'COCON PUDDING 80GM 6CUP', 'productPool/1.jpg', 220 ),
( 'COCONAD NATURAL COCONUT SUGAR 250G', 'productPool/1.jpg', 274 ),
( 'COCONAD REAL COCONUT MILK POWDER 100G', 'productPool/1.jpg', 158 ),
( 'COCONUT', 'productPool/1.jpg', 197 ),
( 'COCONUT BITE TOFFEES', 'productPool/1.jpg', 98 ),
( 'COCONUT CANDY 70G', 'productPool/1.jpg', 113 ),
( 'COCONUT LADDU', 'productPool/1.jpg', 229 ),
( 'COCONUT MILK POWDER 300G', 'productPool/1.jpg', 267 ),
( 'COCONUT NEERA JAGGERY 250G', 'productPool/1.jpg', 114 ),
( 'COCONUT NEERA PEANUT CHIKKI 180GM', 'productPool/1.jpg', 218 ),
( 'COCONUT NEERA SESAME BALLS JAR 200G', 'productPool/1.jpg', 269 ),
( 'COCONUT NEERA SESAME BALLS JAR 300G', 'productPool/1.jpg', 112 ),
( 'COCONUT NEERA SESAME CHIKKI 90G', 'productPool/1.jpg', 15 ),
( 'COCOON JELLY 15G', 'productPool/1.jpg', 141 ),
( 'COFFEE MATE IMP', 'productPool/1.jpg', 32 ),
( 'COLGATE 2-5 YEARS BUBBLE FRUIT', 'productPool/1.jpg', 3 ),
( 'COLGATE 360 CHARCOAL GOLD B2G1', 'productPool/1.jpg', 136 ),
( 'COLGATE 360 CHARCOAL GOLD TOOTH BRUSH', 'productPool/1.jpg', 192 ),
( 'COLGATE 360 CLEAN SOFT BRUSH B2G1', 'productPool/1.jpg', 202 ),
( 'COLGATE 360 VISIBLE WHITE MEDIUM BRUSH', 'productPool/1.jpg', 231 ),
( 'COLGATE 360 VISIBLE WHITE MEDIUM BRUSH B2G1', 'productPool/1.jpg', 81 ),
( 'COLGATE A1 HANGER RS 22', 'productPool/1.jpg', 197 ),
( 'COLGATE ACTI SALT NEEM 200G', 'productPool/1.jpg', 248 ),
( 'COLGATE ACTIVE SALT 100G', 'productPool/1.jpg', 277 ),
( 'COLGATE ACTIVE SALT 100G+200G', 'productPool/1.jpg', 105 ),
( 'COLGATE ACTIVE SALT 200G', 'productPool/1.jpg', 175 ),
( 'COLGATE ACTIVE SALT 48G', 'productPool/1.jpg', 200 ),
( 'COLGATE ACTIVE SALT 50GMS', 'productPool/1.jpg', 190 ),
( 'COLGATE ACTIVE SALT 54G', 'productPool/1.jpg', 158 ),
( 'COLGATE ACTIVE SALT TOOTH PASTE 100G', 'productPool/1.jpg', 104 ),
( 'COLGATE BARBIE 80G', 'productPool/1.jpg', 94 ),
( 'COLGATE BARBIE5+YRS', 'productPool/1.jpg', 275 ),
( 'COLGATE CHARCOAL CLEAN 120G', 'productPool/1.jpg', 13 ),
( 'COLGATE CIBACA 123 BRUSH', 'productPool/1.jpg', 101 ),
( 'COLGATE CIBACA 123 BRUSH SOFT', 'productPool/1.jpg', 181 ),
( 'COLGATE CIBACA 123 SOFT BRUSH', 'productPool/1.jpg', 193 ),
( 'COLGATE CIBACA 123 TOOTH PASTE 28G', 'productPool/1.jpg', 170 ),
( 'COLGATE CIBACA 175G', 'productPool/1.jpg', 170 ),
( 'COLGATE CIBACA 26G', 'productPool/1.jpg', 79 ),
( 'COLGATE CIBACA 30G', 'productPool/1.jpg', 194 ),
( 'COLGATE CIBACA 80G', 'productPool/1.jpg', 183 ),
( 'COLGATE CIBACA VEDSHAKTI 175G', 'productPool/1.jpg', 139 ),
( 'COLGATE CIBACCA SUPREME TOOTH BRUSH HARD', 'productPool/1.jpg', 143 ),
( 'COLGATE COLSPIDMAN5+YERS', 'productPool/1.jpg', 227 ),
( 'COLGATE COMFORT SENSITIVE BRUSH', 'productPool/1.jpg', 5 ),
( 'COLGATE DENTAL CREAM 200G', 'productPool/1.jpg', 249 ),
( 'COLGATE DENTAL CREAM 500G', 'productPool/1.jpg', 190 ),
( 'COLGATE DENTAL CREAM TOOTH PASTE 100G', 'productPool/1.jpg', 249 ),
( 'COLGATE DENTAL CREAM TOOTH PASTE 200GMS', 'productPool/1.jpg', 135 ),
( 'COLGATE DENTAL CREAM TOOTH PASTE 50G', 'productPool/1.jpg', 185 ),
( 'COLGATE DENTAL CRM TOOTH PASTE 100 GMS', 'productPool/1.jpg', 160 ),
( 'COLGATE DENTALCREAM TOOTH PASTE 150G', 'productPool/1.jpg', 75 ),
( 'COLGATE EXTRA CLEAN MEDIUM BRUSH', 'productPool/1.jpg', 65 ),
( 'COLGATE FLOSS TIP MEDIUM', 'productPool/1.jpg', 172 ),
( 'COLGATE FRESHMINT SPLASH 250G', 'productPool/1.jpg', 224 ),
( 'COLGATE HERBAL TOOTH PASTE 100G', 'productPool/1.jpg', 227 ),
( 'COLGATE HERBAL TOOTH PASTE 200G', 'productPool/1.jpg', 101 ),
( 'COLGATE JUNIOR 2 + YEARS', 'productPool/1.jpg', 254 ),
( 'COLGATE KIDS 0-2 TOOTH BRUSH', 'productPool/1.jpg', 36 ),
( 'COLGATE KIDS 2-5 BUBBLE FRUIT FLAVOUR 40G', 'productPool/1.jpg', 139 ),
( 'COLGATE KIDS 2-5 STRAWBERY FLAVOUR 40G', 'productPool/1.jpg', 20 ),
( 'COLGATE KIDS 2-5 YEARS 40G', 'productPool/1.jpg', 59 ),
( 'COLGATE KIDS 2+ B2G1 TOOTH BRUSH', 'productPool/1.jpg', 9 ),
( 'COLGATE KIDS 2+ TOOTH BRUSH', 'productPool/1.jpg', 234 ),
( 'COLGATE KIDS 2+ TOOTHBRUSH', 'productPool/1.jpg', 147 ),
( 'COLGATE KIDS 6+ BUBBLE FRUIT 80G', 'productPool/1.jpg', 272 ),
( 'COLGATE KIDS BARBIE PASTE + BRUSH', 'productPool/1.jpg', 42 ),
( 'COLGATE KIDS BARBIE STRAWBERRY FLAVOUR 80G', 'productPool/1.jpg', 140 ),
( 'COLGATE KIDS MINIONS 80G', 'productPool/1.jpg', 184 ),
( 'COLGATE KIDS SPIDERMAN BUBBLE FRUIT 80G+TOY', 'productPool/1.jpg', 142 ),
( 'COLGATE KIDS2+ TB WITH COLOR PENCIL', 'productPool/1.jpg', 246 ),
( 'COLGATE KIDS2+ TOOTH BRUSH', 'productPool/1.jpg', 94 ),
( 'COLGATE MAX FRESH 24G', 'productPool/1.jpg', 266 ),
( 'COLGATE MAX FRESH BLUE 150G', 'productPool/1.jpg', 230 ),
( 'COLGATE MAX FRESH BLUE 80 G', 'productPool/1.jpg', 175 ),
( 'COLGATE MAX FRESH BLUE TOOTH PASTE 150 G', 'productPool/1.jpg', 161 ),
( 'COLGATE MAX FRESH RED 20G', 'productPool/1.jpg', 155 ),
( 'COLGATE MAX FRESH RED 300G', 'productPool/1.jpg', 208 ),
( 'COLGATE MAX FRESH RED 450G', 'productPool/1.jpg', 175 );