INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'CRUST AND CRUMB MILKSHAKE POWDER VANILLA 125G', 'productPool/1.jpg', 199 ),
( 'CRUST&CRUMB HOT SPICY 200G', 'productPool/1.jpg', 149 ),
( 'CRUST&CRUMB MEXICAN 200GM', 'productPool/1.jpg', 241 ),
( 'CRUST&CRUMB MILK SHAKE BUTTER 300G', 'productPool/1.jpg', 279 ),
( 'CRUST&CRUMBCHICKEN MIX GINGER', 'productPool/1.jpg', 107 ),
( 'CRUSTY CRUMB VANILLA CAKE MIX 225G', 'productPool/1.jpg', 32 ),
( 'CRYSTAL BERRYBUNCH TOFFEE 750G', 'productPool/1.jpg', 131 ),
( 'CRYSTAL DATES TOFFEE 750G', 'productPool/1.jpg', 124 ),
( 'CRYSTAL HOUSEHOLD GLOVES', 'productPool/1.jpg', 67 ),
( 'CRYSTAL HOUSEHOLD GLOVES SMALL', 'productPool/1.jpg', 199 ),
( 'CRYSTAL MILK ECLAIRS 750G', 'productPool/1.jpg', 141 ),
( 'CUCUMBER', 'productPool/1.jpg', 176 ),
( 'CUCUMBER BABY', 'productPool/1.jpg', 28 ),
( 'CUMIN WHOLE', 'productPool/1.jpg', 110 ),
( 'CUP CANDLE', 'productPool/1.jpg', 260 ),
( 'CUP NOODLES IIALIAND 70G', 'productPool/1.jpg', 84 ),
( 'CUP NOODLES MASALA 70G', 'productPool/1.jpg', 154 ),
( 'CUP NOODLES ROGANJOSH 70GM', 'productPool/1.jpg', 166 ),
( 'CUP NOODLES SPICED CHICKEN 70G', 'productPool/1.jpg', 136 ),
( 'CUP NOODLES VEGGI MANCHOW 70G', 'productPool/1.jpg', 216 ),
( 'CUP NOODLES VEGMASALA 55G', 'productPool/1.jpg', 227 ),
( 'CURRY LEAVES', 'productPool/1.jpg', 183 ),
( 'CURRY NARANGA', 'productPool/1.jpg', 214 ),
( 'CUSTARD POWDER 100G', 'productPool/1.jpg', 228 ),
( 'CUTEE GULFEE OUDH SOAP 100G', 'productPool/1.jpg', 80 ),
( 'CUTEE HERBOW 120G', 'productPool/1.jpg', 6 ),
( 'CUTEE LAVENDER BLOOM 120G', 'productPool/1.jpg', 30 ),
( 'CUTEE MANJAL SOAP 100G', 'productPool/1.jpg', 235 ),
( 'CUTEE MILKY ALMOND SOAP 125GM', 'productPool/1.jpg', 244 ),
( 'CUTEE OLIVE SONA 100G', 'productPool/1.jpg', 249 ),
( 'CUTEE PAPPAYA FRUIT MIX SOAP', 'productPool/1.jpg', 138 ),
( 'CUTEE SANDAL SOAP 100G', 'productPool/1.jpg', 102 ),
( 'CUTEE SILKY SKIN 120G', 'productPool/1.jpg', 16 ),
( 'CUTEE WHITE ZAFFRON SOAP 100G', 'productPool/1.jpg', 89 ),
( 'CUTICURA CLEAR SANDAL 100G', 'productPool/1.jpg', 252 ),
( 'CUTICURA GLYCERINE SOAP 100G', 'productPool/1.jpg', 32 ),
( 'CUTICURA GLYCERINE SOAP 75G', 'productPool/1.jpg', 252 ),
( 'CUTICURA LAVENDER TALC 100G', 'productPool/1.jpg', 212 ),
( 'CUTICURA LAVENDER TALC 100GM', 'productPool/1.jpg', 279 ),
( 'CUTICURA LAVENDER TALC 400G', 'productPool/1.jpg', 78 ),
( 'CUTICURA LEVENDER TALC 400G', 'productPool/1.jpg', 95 ),
( 'CUTICURA ORIGINAL TALC 100G', 'productPool/1.jpg', 256 ),
( 'CUTICURA ORIGINAL TALC 100GM', 'productPool/1.jpg', 263 ),
( 'CUTICURA ORIGINAL TALC 400G', 'productPool/1.jpg', 103 ),
( 'CUTICURA ORIGINAL TALC400G', 'productPool/1.jpg', 23 ),
( 'CUTICURA PINK PASSION 400g', 'productPool/1.jpg', 257 ),
( 'CUTICURA PINK PASSION TALC 100GM', 'productPool/1.jpg', 257 ),
( 'CUTTING DATES 1KG', 'productPool/1.jpg', 203 ),
( 'CVC RAT REPELLENT SPRAY 100ML', 'productPool/1.jpg', 241 ),
( 'CVC RAT REPELLENT SPRAY 250ML', 'productPool/1.jpg', 225 ),
( 'CVC TYRE SHINE 550ML', 'productPool/1.jpg', 118 ),
( 'CYCLE 3 IN 1 30G', 'productPool/1.jpg', 55 ),
( 'CYCLE 3 IN 1 68G', 'productPool/1.jpg', 208 ),
( 'CYCLE 3 IN 1 BATH 115G', 'productPool/1.jpg', 245 ),
( 'CYCLE 3 IN 1 BATH 240G', 'productPool/1.jpg', 219 ),
( 'CYCLE 3 IN ONE 19G', 'productPool/1.jpg', 158 ),
( 'CYCLE 3 IN ONE 43G', 'productPool/1.jpg', 62 ),
( 'CYCLE AGARBATHI 110G', 'productPool/1.jpg', 256 ),
( 'CYCLE AGARBATHI 16G', 'productPool/1.jpg', 23 ),
( 'CYCLE AGARBATHI 63G', 'productPool/1.jpg', 84 ),
( 'CYCLE AGARBATHIES MRP 20', 'productPool/1.jpg', 149 ),
( 'CYCLE ASLI BAKHOOR AGARBATHIES MRP 60', 'productPool/1.jpg', 86 ),
( 'CYCLE BANSURI AGARBATHI 16G MRP 10', 'productPool/1.jpg', 191 ),
( 'CYCLE BANSURI AGARBATHI 90G ROLL', 'productPool/1.jpg', 258 ),
( 'CYCLE BASURI AGARBATHI MRP 50', 'productPool/1.jpg', 180 ),
( 'CYCLE BIG SANDAL 110G', 'productPool/1.jpg', 203 ),
( 'CYCLE GOLDENFLORA AGARBATHIES', 'productPool/1.jpg', 193 ),
( 'CYCLE GOOD LUCK LOBAN AGARBATHI 68N', 'productPool/1.jpg', 26 ),
( 'CYCLE HERITAGE CHANDANAM MRP 10', 'productPool/1.jpg', 89 ),
( 'CYCLE HERITAGE DIVINE LOTUS MRP 10', 'productPool/1.jpg', 112 ),
( 'CYCLE OM SHANTHI 25G', 'productPool/1.jpg', 161 ),
( 'CYCLE OUDH AGARBATHIES MRP 60', 'productPool/1.jpg', 267 ),
( 'CYCLE POPULAR AGARBATHI 122G', 'productPool/1.jpg', 224 ),
( 'CYCLE POPULARAGARBATHI FLAVARZ RS50', 'productPool/1.jpg', 35 ),
( 'CYCLE POPULARAGARBATHICOSMATIQ RS50', 'productPool/1.jpg', 169 ),
( 'CYCLE RHYTHM AMBER 125G', 'productPool/1.jpg', 27 ),
( 'CYCLE SANDAL 3IN 1', 'productPool/1.jpg', 272 ),
( 'CYCLE SANDAL 65G', 'productPool/1.jpg', 168 ),
( 'CYCLE SANDAL M 140GRAM', 'productPool/1.jpg', 255 ),
( 'CYCLE SANDALUM AGARBATHIE 122G', 'productPool/1.jpg', 8 ),
( 'CYCLE SANDALUM MRP 10', 'productPool/1.jpg', 71 ),
( 'CYCLE SANDALUM MRP 20', 'productPool/1.jpg', 214 ),
( 'CYCLE SUGANDHA MALLIKA RS20', 'productPool/1.jpg', 198 ),
( 'CYCLE THREE IN ONE AGARBATHI 234G', 'productPool/1.jpg', 173 ),
( 'CYCLE THREE IN ONE AGARBATHIES 240G', 'productPool/1.jpg', 235 ),
( 'CYCLE VASU 100 AGARBATHY', 'productPool/1.jpg', 173 ),
( 'CYCLE VASU AGARBATHIES 101G MRP 40', 'productPool/1.jpg', 273 ),
( 'CYCLE VASU ROLL MRP 40', 'productPool/1.jpg', 260 ),
( 'CYCLE YAGNA AGARBHATHIES RS 50', 'productPool/1.jpg', 135 ),
( 'D PROTEIN CHOCOLATE 200G', 'productPool/1.jpg', 73 ),
( 'D PROTIN 500G', 'productPool/1.jpg', 45 ),
( 'DAAWAT BIRIYANI BASMATI RICE 1KG', 'productPool/1.jpg', 26 ),
( 'DAAWAT CREAMY SELLA XXL BASMATI RICE 25KG', 'productPool/1.jpg', 110 ),
( 'DAAWAT DUBAR BASMATI RICE 1KG', 'productPool/1.jpg', 168 ),
( 'DAAWAT ELINA LONG GRAIN RICE 1KG', 'productPool/1.jpg', 73 ),
( 'DAAWAT GOLDEN SELLA XXXL BASMATI RICE 25KG', 'productPool/1.jpg', 54 ),
( 'DAAWAT ROZANA GOLD BASMATI RICE 1KG', 'productPool/1.jpg', 151 ),
( 'DAAWAT SUPER BASMATI RICE 1KG', 'productPool/1.jpg', 75 ),
( 'DAAWAT TRADITIONAL BASMATI RICE 1KG', 'productPool/1.jpg', 23 ),
( 'DABUR ALMOND HAIR OIL 100ML', 'productPool/1.jpg', 227 ),
( 'DABUR ALMOND HAIR OIL 200ML', 'productPool/1.jpg', 192 ),
( 'DABUR ALMOND HAIR OIL 250ML', 'productPool/1.jpg', 233 ),
( 'DABUR ALMOND HAIR OIL 50ML', 'productPool/1.jpg', 216 ),
( 'DABUR ALMOND OIL 100ML', 'productPool/1.jpg', 80 ),
( 'DABUR ALMOND SHAMPOO 200ML', 'productPool/1.jpg', 108 ),
( 'DABUR AMALA HAIR OIL 275ML', 'productPool/1.jpg', 88 ),
( 'DABUR AMLA HAI ROIL 108ML', 'productPool/1.jpg', 33 ),
( 'DABUR AMLA HAIR OIL 180ML', 'productPool/1.jpg', 225 ),
( 'DABUR AMLA HAIR OIL 275ML', 'productPool/1.jpg', 17 ),
( 'DABUR AMLA HAIR OIL 45ML', 'productPool/1.jpg', 212 ),
( 'DABUR AMLA HAIR OIL 70ML', 'productPool/1.jpg', 31 ),
( 'DABUR AMLA HAIR OIL 90ML', 'productPool/1.jpg', 250 ),
( 'DABUR AMLA OIL 450ML', 'productPool/1.jpg', 3 ),
( 'DABUR ANMOL JASMINE 200ML', 'productPool/1.jpg', 97 ),
( 'DABUR ANMOL JASMINE GOLD 100ML', 'productPool/1.jpg', 41 ),
( 'DABUR BABOOL TOOTH PASTE 100G', 'productPool/1.jpg', 77 ),
( 'DABUR BABOOL TOOTH PASTE 175G', 'productPool/1.jpg', 176 ),
( 'DABUR BABOOL TOOTH PASTE 180G', 'productPool/1.jpg', 30 ),
( 'DABUR BABOOL TOOTH PASTE 45G', 'productPool/1.jpg', 45 ),
( 'DABUR BABOOL TOOTH PASTE 50G', 'productPool/1.jpg', 77 ),
( 'DABUR BABOOL TOOTH PASTE 80G', 'productPool/1.jpg', 232 ),
( 'DABUR BABOOL TOOTH PASTE 90G', 'productPool/1.jpg', 232 ),
( 'DABUR BABOOL TOOTHPASTE ( 180+180GM)', 'productPool/1.jpg', 272 ),
( 'DABUR BABOOL TOOTHPASTE 200G', 'productPool/1.jpg', 67 ),
( 'DABUR BABOOL TOOTHPASTE 350G', 'productPool/1.jpg', 55 ),
( 'DABUR BABOOL TOOTHPASTE 40G', 'productPool/1.jpg', 248 ),
( 'DABUR BADAM TAIL 25 ML', 'productPool/1.jpg', 187 ),
( 'DABUR BADAM TAIL 25ML', 'productPool/1.jpg', 248 ),
( 'DABUR BADAM TAIL 50ML', 'productPool/1.jpg', 118 ),
( 'DABUR CHYAWANAPRASAH 1KG', 'productPool/1.jpg', 253 ),
( 'DABUR CHYAWANAPRASAH 500G', 'productPool/1.jpg', 19 ),
( 'DABUR CHYAWANPRASH 1KG', 'productPool/1.jpg', 235 ),
( 'DABUR ERAND TAIL 100ML', 'productPool/1.jpg', 94 ),
( 'DABUR GLUCO PLUS 125G', 'productPool/1.jpg', 220 ),
( 'DABUR GLUCOPLUS - D 125G', 'productPool/1.jpg', 121 ),
( 'DABUR GLUCOPLUS C 75GM', 'productPool/1.jpg', 56 ),
( 'DABUR GLUCOPLUS ORANGE 125G', 'productPool/1.jpg', 167 ),
( 'DABUR GLUCOPLUS-C ORANGE 250G', 'productPool/1.jpg', 94 ),
( 'DABUR GLUCOSE D 125G', 'productPool/1.jpg', 160 ),
( 'DABUR GLUCOSE D 250G', 'productPool/1.jpg', 102 ),
( 'DABUR GLUCOSE D 500G', 'productPool/1.jpg', 121 ),
( 'DABUR GRIPE WATER 125ML', 'productPool/1.jpg', 155 ),
( 'DABUR GULABAR ROSE WATER 30ML', 'productPool/1.jpg', 70 ),
( 'DABUR GULABARI COLD CREAM 30ML', 'productPool/1.jpg', 141 ),
( 'DABUR GULABARI MOIST COLD CREAM 55M', 'productPool/1.jpg', 203 ),
( 'DABUR GULABARI MOISTURING COLD CREAM', 'productPool/1.jpg', 121 ),
( 'DABUR GULABARI ROSE WATER 120ML', 'productPool/1.jpg', 40 ),
( 'DABUR GULABARI ROSE WATER 30ML', 'productPool/1.jpg', 183 ),
( 'DABUR GULABARI ROSE WATER 400ML', 'productPool/1.jpg', 117 ),
( 'DABUR GULABARI ROSE WATER 59ML', 'productPool/1.jpg', 183 ),
( 'DABUR GULABARI ZAIKA ROSE WATER 250ML', 'productPool/1.jpg', 3 ),
( 'DABUR GULABRI ROSE WATEER 250ML', 'productPool/1.jpg', 122 ),
( 'DABUR GULABRI ROSE WATER 120ML', 'productPool/1.jpg', 140 ),
( 'DABUR HAJMOLA IMLI JAR 160N*2.2G', 'productPool/1.jpg', 69 ),
( 'DABUR HAJMOLA REGULAR 120N', 'productPool/1.jpg', 66 ),
( 'DABUR HERBAL TOOTH PASTE 100G', 'productPool/1.jpg', 142 ),
( 'DABUR HERBAL TOOTH PASTE 200G', 'productPool/1.jpg', 22 ),
( 'DABUR HERBAL TOOTH PASTE UB 50G', 'productPool/1.jpg', 250 ),
( 'DABUR HONEY 1.2KG', 'productPool/1.jpg', 147 ),
( 'DABUR HONEY 100G', 'productPool/1.jpg', 154 ),
( 'DABUR HONEY 1KG', 'productPool/1.jpg', 212 ),
( 'DABUR HONEY 20G', 'productPool/1.jpg', 230 ),
( 'DABUR HONEY 250G', 'productPool/1.jpg', 9 ),
( 'DABUR HONEY 400G', 'productPool/1.jpg', 279 ),
( 'DABUR HONEY 500G', 'productPool/1.jpg', 165 ),
( 'DABUR HONEY 50G', 'productPool/1.jpg', 147 ),
( 'DABUR HONEY SQUEEZY 225G B1G1', 'productPool/1.jpg', 28 ),
( 'DABUR JASMIN HAIR OIL 200ML', 'productPool/1.jpg', 276 ),
( 'DABUR JASMINE HAIR OIL 100ML', 'productPool/1.jpg', 114 ),
( 'DABUR LAL TAIL 100ML', 'productPool/1.jpg', 51 ),
( 'DABUR MESWAK ORAL CARE 100G', 'productPool/1.jpg', 126 ),
( 'DABUR MESWAK ORAL CARE 200G', 'productPool/1.jpg', 214 ),
( 'DABUR MESWAK TOOTH PASTE 100G', 'productPool/1.jpg', 217 ),
( 'DABUR MESWAK TOOTH PASTE 200G', 'productPool/1.jpg', 80 ),
( 'DABUR MESWAK TOOTH PASTE 200G+100G', 'productPool/1.jpg', 265 ),
( 'DABUR MESWAK TOOTH PASTE 300G', 'productPool/1.jpg', 174 ),
( 'DABUR MESWAK TOOTH PASTE 50G', 'productPool/1.jpg', 212 ),
( 'DABUR MESWAK TOOTH PICK 300G', 'productPool/1.jpg', 106 ),
( 'DABUR MESWAK TOOTHPASTE 100G', 'productPool/1.jpg', 110 ),
( 'DABUR ODOMOS FABRIC ROLL ON 8ML', 'productPool/1.jpg', 116 ),
( 'DABUR ORAL CARE 200G', 'productPool/1.jpg', 160 ),
( 'DABUR PUDIN HARA 20N', 'productPool/1.jpg', 19 ),
( 'DABUR PUDIN HARA PEARLS 10N', 'productPool/1.jpg', 36 ),
( 'DABUR RED GEIL PAST 22G', 'productPool/1.jpg', 23 ),
( 'DABUR RED GEL TOOTH PASTE 150G', 'productPool/1.jpg', 127 ),
( 'DABUR RED GEL TOOTH PASTE 80G', 'productPool/1.jpg', 157 ),
( 'DABUR RED PASTE 120G', 'productPool/1.jpg', 148 ),
( 'DABUR RED PASTE GUM 100G', 'productPool/1.jpg', 117 ),
( 'DABUR RED PASTE GUM 200G', 'productPool/1.jpg', 215 ),
( 'DABUR RED PASTE GUM 50G', 'productPool/1.jpg', 113 ),
( 'DABUR RED TOOTH PAST 100G', 'productPool/1.jpg', 230 ),
( 'DABUR RED TOOTH PAST 200G', 'productPool/1.jpg', 117 ),
( 'DABUR RED TOOTH PAST 20G', 'productPool/1.jpg', 29 ),
( 'DABUR RED TOOTH PAST 300G', 'productPool/1.jpg', 172 ),
( 'DABUR RED TOOTH PAST 50G', 'productPool/1.jpg', 69 ),
( 'DABUR RED TOOTH PASTE 100G', 'productPool/1.jpg', 35 ),
( 'DABUR RED TOOTH PASTE 200G', 'productPool/1.jpg', 165 ),
( 'DABUR RED TOOTH PASTE 300G', 'productPool/1.jpg', 239 ),
( 'DABUR RED TOOTH PASTE 400G', 'productPool/1.jpg', 190 ),
( 'DABUR RED TOOTH PASTE 50G', 'productPool/1.jpg', 270 ),
( 'DABUR RED TOOTH POWDER 100GM', 'productPool/1.jpg', 78 ),
( 'DABUR RED TOOTH POWDER 60GM', 'productPool/1.jpg', 249 ),
( 'DABUR RED TOOTH POWDER150GM', 'productPool/1.jpg', 52 ),
( 'DABUR RED TOOTHPASTE 300GM', 'productPool/1.jpg', 146 ),
( 'DABUR RED TOOTHPASTE 50G', 'productPool/1.jpg', 256 ),
( 'DABUR SPECIAL OIL 100ML', 'productPool/1.jpg', 273 ),
( 'DABUR VATHIKA OIL VE HAIR OIL 200ML', 'productPool/1.jpg', 202 ),
( 'DABUR VATIKA ANTI DANDRUFF SHAMPOO 5.6ML', 'productPool/1.jpg', 186 ),
( 'DABUR VATIKA BLACK SHINE SHAMPOO 180ML', 'productPool/1.jpg', 208 ),
( 'DABUR VATIKA BLACK SHINE SHAMPOO 80ML', 'productPool/1.jpg', 221 ),
( 'DABUR VATIKA COC HAIR OIL75 ML', 'productPool/1.jpg', 7 ),
( 'DABUR VATIKA COCONUT HAIR OIL 150ML', 'productPool/1.jpg', 31 ),
( 'DABUR VATIKA COCONUT HAIR OIL 300ML', 'productPool/1.jpg', 44 ),
( 'DABUR VATIKA COCONUT IHIBI 150 ML', 'productPool/1.jpg', 47 ),
( 'DABUR VATIKA COCONUT ILHIBI 75ML', 'productPool/1.jpg', 37 ),
( 'DABUR VATIKA COCONUT OIL 300ML HIBISCUS', 'productPool/1.jpg', 62 ),
( 'DABUR VATIKA HAIR OIL 300ML', 'productPool/1.jpg', 8 ),
( 'DABUR VATIKA HEALTH SHAMPOO 80ML', 'productPool/1.jpg', 115 ),
( 'DABUR VATIKA HENNA SHAMPOO 5ML', 'productPool/1.jpg', 52 ),
( 'DABUR VATIKA HENNA SHAMPOO 80ML', 'productPool/1.jpg', 224 ),
( 'DABUR VATIKA JASMINE HAIR OIL 100ML', 'productPool/1.jpg', 3 ),
( 'DABUR VATIKA JASMINE HAIR OIL 200ML', 'productPool/1.jpg', 111 ),
( 'DABUR VATIKA LEMON SHAMPOO 180ML', 'productPool/1.jpg', 124 ),
( 'DABUR VATIKA LEMON SHAMPOO 80ML', 'productPool/1.jpg', 77 ),
( 'DABUR VATIKA NATURAL OIL BALANCE 180ML', 'productPool/1.jpg', 72 ),
( 'DABUR VATIKA NATURALS ANTI DANDRUFF SHAMPOO 180ML', 'productPool/1.jpg', 162 ),
( 'DABUR VATIKA NATURALS SHAMPOO 5.6ML', 'productPool/1.jpg', 122 ),
( 'DABUR VATIKA PURE COCONUT OIL 175ML', 'productPool/1.jpg', 100 ),
( 'DABUR VATIKA SHAMPOO 50ML', 'productPool/1.jpg', 168 ),
( 'DABUR.PROMISE TOOTH PASTE (170+170)GM', 'productPool/1.jpg', 70 ),
( 'DAIR Y HOME BAKING POWDER 100G', 'productPool/1.jpg', 108 ),
( 'DAIRY HOME APRILLO 110G', 'productPool/1.jpg', 178 ),
( 'DAIRY HOME ASSORTMENT 175G', 'productPool/1.jpg', 97 ),
( 'DAIRY HOME ASSORTMENT CHOCO BB 200G', 'productPool/1.jpg', 195 ),
( 'DAIRY HOME ASSORTMENTS 200G', 'productPool/1.jpg', 109 ),
( 'DAIRY HOME ASSORTMENTS 250G', 'productPool/1.jpg', 104 ),
( 'DAIRY HOME ASSORTMENTS 300G', 'productPool/1.jpg', 203 ),
( 'DAIRY HOME CANEDY ORANGE 200G', 'productPool/1.jpg', 273 ),
( 'DAIRY HOME CANEDY STRAWBERRY 200G', 'productPool/1.jpg', 243 ),
( 'DAIRY HOME CELEBRITA CHOCO 350G', 'productPool/1.jpg', 129 ),
( 'DAIRY HOME CHOCO ASSORTMENTS 300G', 'productPool/1.jpg', 195 ),
( 'DAIRY HOME COCOA POWDER 90G', 'productPool/1.jpg', 155 ),
( 'DAIRY HOME CUSTARDPOWDER VANILLA 100G', 'productPool/1.jpg', 25 ),
( 'DAIRY HOME DAIRHOMNUTSIN200G', 'productPool/1.jpg', 28 ),
( 'DAIRY HOME FULL CREAM 175G', 'productPool/1.jpg', 260 ),
( 'DAIRY HOME KOKOO ASSORTMENTS 150GM', 'productPool/1.jpg', 83 ),
( 'DAIRY HOME KOKOO FULL CREAM 150G', 'productPool/1.jpg', 199 ),
( 'DAIRY HOME KRUX 400G', 'productPool/1.jpg', 231 ),
( 'DAIRY HOME KRUX CHOCOLATE 250GM', 'productPool/1.jpg', 243 ),
( 'DAIRY HOME LOVING HEARTS 100G', 'productPool/1.jpg', 9 ),
( 'DAIRY HOME MELANI 200G', 'productPool/1.jpg', 180 ),
( 'DAIRY HOME MELANI 260G', 'productPool/1.jpg', 149 ),
( 'DAIRY HOME MELANI 300G', 'productPool/1.jpg', 220 ),
( 'DAIRY HOME MELANI 400GM', 'productPool/1.jpg', 143 ),
( 'DAIRY HOME MELANI 420G', 'productPool/1.jpg', 110 ),
( 'DAIRY HOME MELANI CHOCLATE 110G', 'productPool/1.jpg', 22 ),
( 'DAIRY HOME NUTS IN CHOCOLATE 200G', 'productPool/1.jpg', 8 ),
( 'DAIRY HOME NUTSIN 300G', 'productPool/1.jpg', 15 ),
( 'DAIRY HOME ROCK STAR STRAWBERY 135G', 'productPool/1.jpg', 76 ),
( 'DAIRY HOME SWEET&BLESSIMNGS 400G', 'productPool/1.jpg', 198 ),
( 'DAIRY HOME SWEETS & BLESSING 250G', 'productPool/1.jpg', 205 ),
( 'DAIRY HOME TOUCHING 250G', 'productPool/1.jpg', 256 ),
( 'DAIRY MILK 54G RS 10', 'productPool/1.jpg', 207 ),
( 'DAIRY MILK CRACKLE 38G', 'productPool/1.jpg', 233 ),
( 'DAIRY MILK FRUIT & NUT 55G', 'productPool/1.jpg', 135 ),
( 'DAIRY MILK FUSE 25G', 'productPool/1.jpg', 56 ),
( 'DAIRY MILK FUSE 45G', 'productPool/1.jpg', 158 ),
( 'DAIRY MILK LICKABLES 20G', 'productPool/1.jpg', 125 ),
( 'DAIRY MILK MARVEELLOUS JELLY POPPINS 75G', 'productPool/1.jpg', 130 ),
( 'DAIRY MILK MC COOKIE NUT CRUNCH 75G', 'productPool/1.jpg', 70 ),
( 'DAIRY MILK MC JELLY POPPING 35G', 'productPool/1.jpg', 121 ),
( 'DAIRY MILK ROAST ALMOND', 'productPool/1.jpg', 47 ),
( 'DAIRY MILK ROAST ALMOND 36G', 'productPool/1.jpg', 236 ),
( 'DAIRY MILK ROAST ALMOND 38 G', 'productPool/1.jpg', 36 ),
( 'DAIRY MILK SILK CARAMELLO 136G', 'productPool/1.jpg', 121 ),
( 'DAIRY MILK SILK CARAMELLO 60G', 'productPool/1.jpg', 72 ),
( 'DAIRY MILK SILK CHOCOLATE PLAIN 60G', 'productPool/1.jpg', 250 ),
( 'DAIRY MILK SILK FRUIT NUT55G', 'productPool/1.jpg', 218 ),
( 'DAIRY MILK SILK ROAST ALMOND 55G', 'productPool/1.jpg', 46 ),
( 'DAIRYHOME TOUCHING 400GM', 'productPool/1.jpg', 89 ),
( 'DAIRYMILK FRUIT&NUT 80G', 'productPool/1.jpg', 74 ),
( 'DAIRYMILK LICKABLES POP 20G', 'productPool/1.jpg', 117 ),
( 'DAIRYMILK MARVELLOUS CREATIONS JELLY POPPING', 'productPool/1.jpg', 184 ),
( 'DAIRYMILK SILK BUBBLY 50G', 'productPool/1.jpg', 101 ),
( 'DALDA VANASP 100ML', 'productPool/1.jpg', 173 ),
( 'DALDA VANASPATHI 1 LIT', 'productPool/1.jpg', 176 ),
( 'DALDA VANASPATHI 500ML', 'productPool/1.jpg', 38 ),
( 'DALDA VANASPATI 200ML', 'productPool/1.jpg', 263 ),
( 'DANA BLACK CURRENT JAM', 'productPool/1.jpg', 179 ),
( 'DANA MIXED FRUIT SPREAD 315G', 'productPool/1.jpg', 78 ),
( 'DANA MORELLO CHERRY JAM', 'productPool/1.jpg', 236 ),
( 'DANISH CASTLE BUTTER COOKIES', 'productPool/1.jpg', 84 ),
( 'DARK FANTASY CHOCO FILLS 75G', 'productPool/1.jpg', 169 ),
( 'DARK FANTASY CHOCO FILLS LUXURIA 150G', 'productPool/1.jpg', 174 ),
( 'DATE CROWN FARD 1KG', 'productPool/1.jpg', 187 ),
( 'DATE CROWN NEGHAL 800G', 'productPool/1.jpg', 32 ),
( 'DATES 500G', 'productPool/1.jpg', 110 ),
( 'DATES CROWN BUMAAN 500GM', 'productPool/1.jpg', 98 ),
( 'DATES CROWN KHALAS 250G', 'productPool/1.jpg', 41 ),
( 'DATES HALWA 1 KG', 'productPool/1.jpg', 5 ),
( 'DATES WITH CASHEW 350G', 'productPool/1.jpg', 119 ),
( 'DAVIDOFF CAFE GRANDE CUVEE ESPRESSO 57', 'productPool/1.jpg', 269 ),
( 'DAVIDOFF CAFE GRANDE FINE AROMA 100G', 'productPool/1.jpg', 234 ),
( 'DAZLER EYEBROW PENCIL BROWN 1.5G', 'productPool/1.jpg', 87 ),
( 'DCC BADAM 80G', 'productPool/1.jpg', 85 ),
( 'DCC CASHEW PLAIN 100GM', 'productPool/1.jpg', 17 ),
( 'DCC CASHEW ROASTED & SALTED 100G', 'productPool/1.jpg', 206 ),
( 'DCC CASHEW SPANISH CHILLI 80GM', 'productPool/1.jpg', 182 ),
( 'DEAR EARTH ARHAR DAL 500G', 'productPool/1.jpg', 199 ),
( 'DEAR EARTH KASHMIRI CHILLI POWDER 100G', 'productPool/1.jpg', 226 ),
( 'DEAR EARTH KASHMIRI CHILLI POWDER 250G', 'productPool/1.jpg', 84 ),
( 'DEAR EARTH MOONG SPLIT WASHED 500G', 'productPool/1.jpg', 163 ),
( 'DEAR EARTH NATURAL ROLLED OATS 450G', 'productPool/1.jpg', 38 ),
( 'DEAR EARTH ORGANIC JAGGERY BLOCK 400G', 'productPool/1.jpg', 279 ),
( 'DEAR EARTH SUGAR WHITE 1KG', 'productPool/1.jpg', 221 ),
( 'DEAR EARTH SUGAR WHITE 500G', 'productPool/1.jpg', 11 ),
( 'DEAR TEDDY BISCUIT TIN 150G', 'productPool/1.jpg', 61 ),
( 'DEAREST GREEN APPLE 18G', 'productPool/1.jpg', 50 ),
( 'DEAREST PINE APPLE 100G', 'productPool/1.jpg', 242 ),
( 'DEARESTR RMC GREEN RAMC STICKS 100', 'productPool/1.jpg', 16 ),
( 'DEARESTR RMC RED STICKS 100', 'productPool/1.jpg', 1 ),
( 'DECENT BRUSH WITH STAND', 'productPool/1.jpg', 178 ),
( 'DECOR TEA STRAINER BT', 'productPool/1.jpg', 139 ),
( 'DEEDHI HAIR SHAMPOO 250ML', 'productPool/1.jpg', 114 ),
( 'DEEDHI LAVENDER SHAMPOO 125ML', 'productPool/1.jpg', 167 ),
( 'DEEDHI LIME SHAMPOO 100 ML', 'productPool/1.jpg', 225 ),
( 'DEEDHI LIME SHAMPOO 250 ML', 'productPool/1.jpg', 24 ),
( 'DEEDHI PROTEIN SHAMPOO', 'productPool/1.jpg', 241 ),
( 'DEEPAM LAMP OIL 1LT', 'productPool/1.jpg', 28 ),
( 'DEEPAM LAMP OIL 250 ML', 'productPool/1.jpg', 233 ),
( 'DEEPAM LAMP OIL 500ML', 'productPool/1.jpg', 90 ),
( 'DEEPIKA CLOTH CLIP 12PCS', 'productPool/1.jpg', 126 ),
( 'DEFENCE MINISTER WASHING BRUSH', 'productPool/1.jpg', 152 ),
( 'DEL MONTE BAKED BEANS IN SAUCE 450G', 'productPool/1.jpg', 169 ),
( 'DEL MONTE BARBEQUE SAUCE 1KG', 'productPool/1.jpg', 238 ),
( 'DEL MONTE BUTTON MUSHROOM 800G', 'productPool/1.jpg', 145 ),
( 'DEL MONTE CHIFFERI RIGATI 500G', 'productPool/1.jpg', 154 ),
( 'DEL MONTE CLASSIC OLIVE OIL 100ML', 'productPool/1.jpg', 204 ),
( 'DEL MONTE CLASSIC OLIVE OIL 200ML', 'productPool/1.jpg', 121 ),
( 'DEL MONTE DRIED CRANBERRIES 130G', 'productPool/1.jpg', 267 ),
( 'DEL MONTE EGGLESS MAYO 500G', 'productPool/1.jpg', 139 ),
( 'DEL MONTE EGGLESS MAYONNAISE 1KG', 'productPool/1.jpg', 83 ),
( 'DEL MONTE GREEN APPLE DRINK 240ML CAN', 'productPool/1.jpg', 116 ),
( 'DEL MONTE GREEN CHILLI SAUCE 190G', 'productPool/1.jpg', 131 ),
( 'DEL MONTE MIXED FRUIT DRINK 240ML CAN', 'productPool/1.jpg', 235 ),
( 'DEL MONTE PINEAPPLE FRUIT DRINK 240ML', 'productPool/1.jpg', 207 ),
( 'DEL MONTE PINEAPPLE ORANGE DRINK 240ML CAN', 'productPool/1.jpg', 147 ),
( 'DEL MONTE PITTED GREEN PLIVES 450G', 'productPool/1.jpg', 248 ),
( 'DEL MONTE PIZZA PASTA SAUCE 400G', 'productPool/1.jpg', 254 ),
( 'DEL MONTE RED CHILLI SAUCE 190G', 'productPool/1.jpg', 115 ),
( 'DEL MONTE SCHEZWAN SAUCE 190G', 'productPool/1.jpg', 152 ),
( 'DEL MONTE SLICED BLACK OLIVES 450G', 'productPool/1.jpg', 179 ),
( 'DEL MONTE SLICED GREEN OLIVES 450G', 'productPool/1.jpg', 80 ),
( 'DEL MONTE SPAGETTI 500G', 'productPool/1.jpg', 191 ),
( 'DEL MONTE SPIRALI 500G', 'productPool/1.jpg', 146 ),
( 'DEL MONTE TOMATO KETCHUP 1KG', 'productPool/1.jpg', 166 ),
( 'DEL MONTE VIRGIN OLIVE OIL 250ML', 'productPool/1.jpg', 61 ),
( 'DEL MONTE WHOLE GREEN OLIVES 450G', 'productPool/1.jpg', 140 ),
( 'DEL MONTE WHOLE KERNEL CORN 420G', 'productPool/1.jpg', 165 ),
( 'DELECIOUS CHILLI GARLIC CASHEWS 100G', 'productPool/1.jpg', 161 ),
( 'DELFI TWISTER CAPPOUCINO 320G', 'productPool/1.jpg', 187 ),
( 'DELFI TWISTER STAWBERRY 320G', 'productPool/1.jpg', 132 ),
( 'DELFI TWISTER VANILLA 320G', 'productPool/1.jpg', 129 ),
( 'DELI NUT DRY ROASTED CASHEW PEPPY PEPPER 80G', 'productPool/1.jpg', 19 ),
( 'DELICIOUS ALMONDS 100G', 'productPool/1.jpg', 60 ),
( 'DELICIOUS PEPPER CASHEWS 100G', 'productPool/1.jpg', 56 ),
( 'DELICIOUS PISTA CHIOS 100G', 'productPool/1.jpg', 5 ),
( 'DELINUT CASHEW GOLDEN BROWN 200G', 'productPool/1.jpg', 13 ),
( 'DELINUT CASHEW GOLDEN BROWN 500G', 'productPool/1.jpg', 244 ),
( 'DELINUT CASHEW GOLDEN BROWN 80G', 'productPool/1.jpg', 47 ),
( 'DELINUT CASHEW MALABAR MASALA 200G', 'productPool/1.jpg', 23 ),
( 'DELINUT CASHEW MALABAR MASALA 500G', 'productPool/1.jpg', 72 ),
( 'DELINUT CASHEW MALABAR MASALA 80G', 'productPool/1.jpg', 40 ),
( 'DELINUT CHILLI GARLIC CASHEW 200G', 'productPool/1.jpg', 197 ),
( 'DELINUT CHILLI GARLIC CASHEW 500G', 'productPool/1.jpg', 201 ),
( 'DELINUT CHILLY CASHEW 500G', 'productPool/1.jpg', 105 ),
( 'DELINUT DRY ROASTED CASHEWS 900G', 'productPool/1.jpg', 262 ),
( 'DELINUT DRY ROASTED CASHEWS PEPPY PEPPR 400G', 'productPool/1.jpg', 138 ),
( 'DELINUT DRY ROASTED CASHEWS SALTY 400G', 'productPool/1.jpg', 39 ),
( 'DELINUT DRY ROASTED CASHEWS SIZZLING CHILLY 400G', 'productPool/1.jpg', 104 ),
( 'DELINUT DRY ROASTED CHILLI GARLIC 20G', 'productPool/1.jpg', 71 ),
( 'DELINUT DRY ROASTED CHILLY CASHEW 200G', 'productPool/1.jpg', 60 ),
( 'DELINUT DRY ROASTED HEAVENLY HONEY 150G', 'productPool/1.jpg', 245 ),
( 'DELINUT DRY ROASTED PEPPER CASHEW 200G', 'productPool/1.jpg', 230 ),
( 'DELINUT DRY ROASTED PEPPER ONION 80G', 'productPool/1.jpg', 130 ),
( 'DELINUT DRY ROASTED PEPPY PEPPER 150G', 'productPool/1.jpg', 51 ),
( 'DELINUT DRY ROASTED PEPPY PEPPER 20G', 'productPool/1.jpg', 92 ),
( 'DELINUT DRY ROASTED SALTY CASHEW 200G', 'productPool/1.jpg', 124 ),
( 'DELINUT DRY ROASTED SALTY CASHEW 500G', 'productPool/1.jpg', 247 ),
( 'DELINUT DRY ROASTED SIMPLY SALTY 20G', 'productPool/1.jpg', 168 ),
( 'DELINUT DRY ROASTED SIMPLY SALTY 80G', 'productPool/1.jpg', 130 ),
( 'DELINUT DRY ROASTED SIMPLY SALTY CASHEW 150G', 'productPool/1.jpg', 26 ),
( 'DELINUT DRY ROASTED SIZZILING CHILLY 20G', 'productPool/1.jpg', 184 ),
( 'DELINUT DRY ROASTED SIZZLING CHILLI 900G', 'productPool/1.jpg', 236 ),
( 'DELINUT DRY ROASTED SIZZLING CHILLY 80G', 'productPool/1.jpg', 10 ),
( 'DELINUT DRY ROASTED TANGY CHILLI GARLIC 150G', 'productPool/1.jpg', 271 ),
( 'DELINUT DRY ROASTED TANGY CHILLY GARLIC 80G', 'productPool/1.jpg', 181 ),
( 'DELINUT GOLDEN BROWN OIL ROASTED CASHEWS 500G', 'productPool/1.jpg', 194 ),
( 'DELINUT GOLDEN BROWN ROASTED SALTED 400G', 'productPool/1.jpg', 18 ),
( 'DELINUT HEAVENLY HONEY CASHEW 500G', 'productPool/1.jpg', 127 ),
( 'DELINUT HEAVENLY HONEY CASHEW 80G', 'productPool/1.jpg', 227 ),
( 'DELINUT MALABAR MASALA CASHEW 500G POUCH', 'productPool/1.jpg', 242 ),
( 'DELINUT MALABAR MASALA OIL ROASTED CASHEW 400G TIN', 'productPool/1.jpg', 85 ),
( 'DELINUT NATURALLY NATURAL CASHEW 150G', 'productPool/1.jpg', 240 ),
( 'DELINUT PEPPER CASHEW 500G', 'productPool/1.jpg', 255 ),
( 'DELINUT PEPPER ONION CASHEW 200G', 'productPool/1.jpg', 81 ),
( 'DELINUT PLAIN CASHEW 200G', 'productPool/1.jpg', 86 ),
( 'DELINUT PLAIN CASHEW 500G', 'productPool/1.jpg', 140 ),
( 'DELINUT PLAIN CASHEW 80G', 'productPool/1.jpg', 188 ),
( 'DELINUT PLAIN CASHEW 900G', 'productPool/1.jpg', 210 ),
( 'DELINUTS ALMOND 200G SALTED', 'productPool/1.jpg', 237 ),
( 'DELINUTS ALMOND 200G SMOKED', 'productPool/1.jpg', 177 ),
( 'DELINUTS ALMOND 80G SALTED', 'productPool/1.jpg', 32 ),
( 'DELINUTS ALMOND 80G SMOKED', 'productPool/1.jpg', 195 ),
( 'DELINUTY SIMPLY SALTY DELINUT DRY ROASTED 150G', 'productPool/1.jpg', 199 ),
( 'DELIS CASHEW GOLDEN BROWN ROASTED SALTED 250G', 'productPool/1.jpg', 254 ),
( 'DELIS CASHEW PLAIN 250G', 'productPool/1.jpg', 69 ),
( 'DELIS CASHEW ROASTED SALTED GOLDEN BROWN 80G', 'productPool/1.jpg', 13 ),
( 'DELIS CASHEWS MALABAR MASALA SALTED 80G', 'productPool/1.jpg', 60 ),
( 'DELIS GOLDEN BROWN ROASTED SALTED 150G', 'productPool/1.jpg', 17 ),
( 'DELIS MALABAR MASALA CASHEW 900G', 'productPool/1.jpg', 166 ),
( 'DELIS MALABAR MASALA ROASTED SALTED 150G', 'productPool/1.jpg', 86 ),
( 'DELIS MALABAR MASALA ROASTED SALTED 250G', 'productPool/1.jpg', 218 ),
( 'DELIS MALBAR MASALA ROASTED CASHEW 80G', 'productPool/1.jpg', 257 ),
( 'DELIS MALBAR MASALA ROASTED SALTED CASHEW 400G', 'productPool/1.jpg', 203 ),
( 'DELITE CHICKEN DOG CHEW STICK', 'productPool/1.jpg', 15 ),
( 'DELITE LONG CHAIN RS245', 'productPool/1.jpg', 137 ),
( 'DELITE LONG CHAIN RS340', 'productPool/1.jpg', 40 ),
( 'DELUX DUST FREE BROOM', 'productPool/1.jpg', 194 ),
( 'DELUXE ROBESTA COFFEE 100GM', 'productPool/1.jpg', 264 ),
( 'DELUXE ROBESTA COFFEE 250GM', 'productPool/1.jpg', 74 ),
( 'DELUXE ROBESTA COFFEE 50GM', 'productPool/1.jpg', 180 ),
( 'DELUXE SOAP BOX', 'productPool/1.jpg', 153 ),
( 'DENTO CLINIC CLASSIC HARD', 'productPool/1.jpg', 159 ),
( 'DENTO CLINIC CLASSIC MEDIUM', 'productPool/1.jpg', 127 ),
( 'DENTO CLINIC INTERDENTAL HARD', 'productPool/1.jpg', 50 ),
( 'DENTO CLINIC INTERDENTAL MEDIUM', 'productPool/1.jpg', 115 ),
( 'DENTO CLINIC INTERDENTAL MEDIUM 2N', 'productPool/1.jpg', 278 ),
( 'DENTO CLINIC INTERDENTAL SOFT', 'productPool/1.jpg', 105 ),
( 'DENTO CLINIC KIDS MONKEY TOOTH BRUSH', 'productPool/1.jpg', 16 ),
( 'DENTO CLINIC KIDS TOOTH BRUSH SOFT', 'productPool/1.jpg', 41 ),
( 'DENTO CLINIC MAX CLEAN HARD', 'productPool/1.jpg', 54 ),
( 'DENTO CLINIC MAX CLEAN MEDIUM', 'productPool/1.jpg', 198 ),
( 'DENTO CLINIC MAX CLEAN SOFT', 'productPool/1.jpg', 211 ),
( 'DENTO CLINIC TOOTH BRUSH CLASSIC PLUS', 'productPool/1.jpg', 59 ),
( 'DENTO CLINIC TOOTH BRUSH JUNIOR MEDIUM', 'productPool/1.jpg', 76 ),
( 'DENTO CLINIC TOOTH BRUSH OMNI MEDIUM', 'productPool/1.jpg', 15 ),
( 'DENTO CLINIC ULTRA CARE', 'productPool/1.jpg', 16 ),
( 'DEO RASASI IMP', 'productPool/1.jpg', 20 ),
( 'DEO RASASI IMP RS 123', 'productPool/1.jpg', 103 ),
( 'DERMI COOL ALOE FRESH 150G', 'productPool/1.jpg', 100 ),
( 'DERMI COOL FRESH ALOE 150G', 'productPool/1.jpg', 142 ),
( 'DERMI COOL LAVENDER 150G', 'productPool/1.jpg', 206 ),
( 'DERMI COOL REGULAR 150G', 'productPool/1.jpg', 94 ),
( 'DERMI COOL SANDAL 150G', 'productPool/1.jpg', 278 ),
( 'DERMI COOL SANDAL TALC', 'productPool/1.jpg', 168 ),
( 'DERMI COOL SANDAL TALC 150G', 'productPool/1.jpg', 154 ),
( 'DERMICOOL HEAT POWDER REGULAR 150G', 'productPool/1.jpg', 40 ),
( 'DESERT CAMEL DATES 200G', 'productPool/1.jpg', 221 ),
( 'DESIGNER COMB', 'productPool/1.jpg', 74 ),
( 'DESIRE DARK COMPOUND', 'productPool/1.jpg', 43 ),
( 'DESIRE MILK COMPOUND 500G', 'productPool/1.jpg', 264 ),
( 'DETRA PLUS WASHING SOAP 150G', 'productPool/1.jpg', 256 ),
( 'DETTOL 125ML', 'productPool/1.jpg', 236 ),
( 'DETTOL 250ML', 'productPool/1.jpg', 213 ),
( 'DETTOL 500ML', 'productPool/1.jpg', 25 ),
( 'DETTOL 60ML', 'productPool/1.jpg', 220 ),
( 'DETTOL ALOE VERA HANDWASH LIQUID 175ML', 'productPool/1.jpg', 205 ),
( 'DETTOL ALOEVERA SOAP 100G', 'productPool/1.jpg', 42 ),
( 'DETTOL ALOEVERA SOAP 60G', 'productPool/1.jpg', 258 ),
( 'DETTOL ALOVERA HANDWASH PUMP 200ML', 'productPool/1.jpg', 231 ),
( 'DETTOL ANTISEPTIC LIQUID 125ML', 'productPool/1.jpg', 84 ),
( 'DETTOL ANTISEPTIC LIQUID 1L', 'productPool/1.jpg', 189 ),
( 'DETTOL ANTISEPTIC LIQUID 250ML', 'productPool/1.jpg', 254 ),
( 'DETTOL ANTISEPTIC LIQUID 500ML', 'productPool/1.jpg', 72 ),
( 'DETTOL ANTISEPTIC LIQUID 550ML', 'productPool/1.jpg', 1 ),
( 'DETTOL ANTISEPTIC LIQUID 5LIT', 'productPool/1.jpg', 174 ),
( 'DETTOL ANTISEPTIC LIQUID 60ML', 'productPool/1.jpg', 147 ),
( 'DETTOL COOL BALANCED HANDWASH 200ML', 'productPool/1.jpg', 166 ),
( 'DETTOL COOL CRISPY MENTHOL SOAP 125 GMS', 'productPool/1.jpg', 63 ),
( 'DETTOL COOL HANDWASH 175ML', 'productPool/1.jpg', 261 ),
( 'DETTOL COOL HANDWASH PUMP 200ML', 'productPool/1.jpg', 180 ),
( 'DETTOL COOL SHAVING 78G', 'productPool/1.jpg', 60 ),
( 'DETTOL COOL SOAP 125G', 'productPool/1.jpg', 216 ),
( 'DETTOL COOL SOAP 70G', 'productPool/1.jpg', 261 ),
( 'DETTOL COOL SOAP 75 G', 'productPool/1.jpg', 72 ),
( 'DETTOL COOL SOAP 75G', 'productPool/1.jpg', 137 ),
( 'DETTOL COOLHAND WASH PUMP 200ML', 'productPool/1.jpg', 227 ),
( 'DETTOL DISINFECTANT SPRAY BLOSSOM 170G', 'productPool/1.jpg', 133 ),
( 'DETTOL DISINFECTANT SPRAY PINE 170G', 'productPool/1.jpg', 193 ),
( 'DETTOL ENEREGIZE BODY WASH 250ML', 'productPool/1.jpg', 149 ),
( 'DETTOL FRESH SHAVING 78G', 'productPool/1.jpg', 54 ),
( 'DETTOL GOLD LIQUID HAND WASH 175ML', 'productPool/1.jpg', 236 ),
( 'DETTOL HAND SANITIZER 200ML', 'productPool/1.jpg', 226 ),
( 'DETTOL HAND SANITIZER FLORAL 50ML', 'productPool/1.jpg', 185 ),
( 'DETTOL HAND SANTIZER ORIGINAL 25ML', 'productPool/1.jpg', 64 ),
( 'DETTOL HAND WASH 175ML', 'productPool/1.jpg', 26 ),
( 'DETTOL HAND WASH 900ML', 'productPool/1.jpg', 82 ),
( 'DETTOL HAND WASH POUCH 800ML', 'productPool/1.jpg', 128 ),
( 'DETTOL HAND WASH PUMP ORIGINAL 250ML', 'productPool/1.jpg', 177 ),
( 'DETTOL HANDWASH ALOEVERA 175ML POUCH COMBI', 'productPool/1.jpg', 266 ),
( 'DETTOL HANDWASH COOL 3*175ML', 'productPool/1.jpg', 260 ),
( 'DETTOL HANDWASH ORANGE POUCH COMBO 525ML', 'productPool/1.jpg', 244 ),
( 'DETTOL HANDWASH ORIGINAL 175ML POUCH COMBO', 'productPool/1.jpg', 54 ),
( 'DETTOL HANDWASH ORIGINAL 750ML POUCH', 'productPool/1.jpg', 262 ),
( 'DETTOL HANDWASH ORIGINAL PUMP 200ML', 'productPool/1.jpg', 233 ),
( 'DETTOL HANDWASH POUCH 750ML', 'productPool/1.jpg', 93 ),
( 'DETTOL HANDWASH POUCH ORIGINAL 175ML COMBI', 'productPool/1.jpg', 95 ),
( 'DETTOL HANDWASH PUMB ORIGINAL 200ML', 'productPool/1.jpg', 2 ),
( 'DETTOL HANDWASH PUMP 900ML', 'productPool/1.jpg', 235 ),
( 'DETTOL HANDWASH PUMP ORIGINAL 100ML', 'productPool/1.jpg', 95 ),
( 'DETTOL HANDWASH SENSITIVE 175ML', 'productPool/1.jpg', 15 ),
( 'DETTOL HANDWASH SENSITIVE POUCH 175ML COMBI', 'productPool/1.jpg', 60 ),
( 'DETTOL HANDWASH SKIN CARE 900ML', 'productPool/1.jpg', 47 ),
( 'DETTOL HANDWASH SKINCARE 175ML POUCH COMBO', 'productPool/1.jpg', 92 ),
( 'DETTOL HANDWASH SKINCARE 750ML POUCH', 'productPool/1.jpg', 44 ),
( 'DETTOL HANDWASH SKINCARE 900ML PUMP', 'productPool/1.jpg', 149 ),
( 'DETTOL HANDWASH SKINCARE POUCH 175ML', 'productPool/1.jpg', 207 ),
( 'DETTOL HANDWASH SKINCARE PUMP 200ML', 'productPool/1.jpg', 165 ),
( 'DETTOL HANDWASH TULSI 200ML', 'productPool/1.jpg', 115 ),
( 'DETTOL HYGENIC LIME FRESH 200ML', 'productPool/1.jpg', 109 ),
( 'DETTOL HYGENIC LIQUID LIME 1L', 'productPool/1.jpg', 91 ),
( 'DETTOL HYGENIC MENTHOL COOL 200ML', 'productPool/1.jpg', 239 ),
( 'DETTOL HYGIENE LIQUID 500ML', 'productPool/1.jpg', 27 ),
( 'DETTOL HYGINIC MENTHOL 500ML', 'productPool/1.jpg', 118 ),
( 'DETTOL INSTANT HAND SANITIZER ORIGINAL 50ML', 'productPool/1.jpg', 220 ),
( 'DETTOL JASMINE SOAP 75G', 'productPool/1.jpg', 170 ),
( 'DETTOL KITCHEN CLEANER 200ML LIME SPLASH', 'productPool/1.jpg', 155 ),
( 'DETTOL KITCHEN CLEANER 400ML LIME SPLASH', 'productPool/1.jpg', 16 ),
( 'DETTOL KITCHEN CLEANER LIME SPLASH 750ML', 'productPool/1.jpg', 77 ),
( 'DETTOL KITCHEN DISH GEL LEMON FRESH 750ML', 'productPool/1.jpg', 90 ),
( 'DETTOL KITCHEN GEL 200ML LEMON FRESH', 'productPool/1.jpg', 271 ),
( 'DETTOL KITCHEN GEL 400ML LEMON FRESH', 'productPool/1.jpg', 79 ),
( 'DETTOL LIQUID HAND WASH 200ML', 'productPool/1.jpg', 10 ),
( 'DETTOL LIQUID HANDWASH 215ML', 'productPool/1.jpg', 274 ),
( 'DETTOL LIQUID HANDWASH 900ML', 'productPool/1.jpg', 146 ),
( 'DETTOL ORGINAL HANDWASH POUCH 175ML', 'productPool/1.jpg', 158 ),
( 'DETTOL ORGINAL HANDWASH PUMB 125ML', 'productPool/1.jpg', 124 ),
( 'DETTOL ORGINAL SOAP 125G', 'productPool/1.jpg', 161 ),
( 'DETTOL ORIGINAL HAND WASH 900 ML', 'productPool/1.jpg', 45 ),
( 'DETTOL ORIGINAL HANDWASH 25ML', 'productPool/1.jpg', 234 ),
( 'DETTOL ORIGINAL SOAP 75G', 'productPool/1.jpg', 152 ),
( 'DETTOL ORIGINAL SOAP 75GMS', 'productPool/1.jpg', 113 ),
( 'DETTOL ORIGINAL SOAP75G', 'productPool/1.jpg', 37 ),
( 'DETTOL PH BALANCED HANDWASH 175ML', 'productPool/1.jpg', 259 ),
( 'DETTOL RE ENERGIZE HAND WASH 200ML', 'productPool/1.jpg', 173 ),
( 'DETTOL RE ENERGIZE HAND WASH POUCH 175ML', 'productPool/1.jpg', 114 ),
( 'DETTOL RE ENERGIZE HAND WASH PUMP 200ML', 'productPool/1.jpg', 152 ),
( 'DETTOL RE ENERGIZE HANDWASH 200ML', 'productPool/1.jpg', 165 ),
( 'DETTOL REFRESH BODY WASH 250ML', 'productPool/1.jpg', 17 ),
( 'DETTOL REVITALIZE BODY WASH 250ML', 'productPool/1.jpg', 154 ),
( 'DETTOL SANITIZER 50ML', 'productPool/1.jpg', 25 ),
( 'DETTOL SENSITIVE HANDWASH 200ML', 'productPool/1.jpg', 92 ),
( 'DETTOL SKIN CARE 75 G', 'productPool/1.jpg', 224 ),
( 'DETTOL SKIN CARE SOAP 125G', 'productPool/1.jpg', 103 ),
( 'DETTOL SKIN CARE SOAP 75 G', 'productPool/1.jpg', 136 ),
( 'DETTOL SKINCARE HAND WASH PUMP 200ML', 'productPool/1.jpg', 161 ),
( 'DETTOL SKINCARE HANDWASH COMPI 3*175ML', 'productPool/1.jpg', 133 ),
( 'DETTOL SKINCARE HANDWASH PUMP 200ML', 'productPool/1.jpg', 123 ),
( 'DETTOL SKINCARE SOAP 125GMS', 'productPool/1.jpg', 105 ),
( 'DETTOL SKINCARE SOAP 75G', 'productPool/1.jpg', 148 ),
( 'DETTOL SOAP ORGINAL 125G', 'productPool/1.jpg', 114 ),
( 'DETTOL SOOTHE BODY WASH 250ML', 'productPool/1.jpg', 266 ),
( 'DETTOL SQUEEZY HAND WASH 100ML', 'productPool/1.jpg', 44 ),
( 'DETTOL SQUEEZY HANDWASH 100ML', 'productPool/1.jpg', 95 ),
( 'DEV ACHAPPAM 10NOS', 'productPool/1.jpg', 198 ),
( 'DEV BUTTER MURUKK 350G', 'productPool/1.jpg', 90 ),
( 'DEV ELLUNDA 90G', 'productPool/1.jpg', 24 ),
( 'DEV GHEE ROAST PEANUT 150GMS', 'productPool/1.jpg', 53 ),
( 'DEV HOME BRAND TABLE MAT HBT905', 'productPool/1.jpg', 15 ),
( 'DEV HOME BRAND TABLE MAT HBT908', 'productPool/1.jpg', 217 ),
( 'DEV HOME BRAND TABLE MAT HBT910', 'productPool/1.jpg', 253 ),
( 'DEV KUZHALAPPAM 175G', 'productPool/1.jpg', 61 ),
( 'DEV MASALA KUZHAL MURUKKU 175G', 'productPool/1.jpg', 122 ),
( 'DEV MULLU MURUKU 175G', 'productPool/1.jpg', 243 ),
( 'DEV PAKKAVADA 175G', 'productPool/1.jpg', 141 ),
( 'DEV PEANUT BALL 125G', 'productPool/1.jpg', 191 ),
( 'DEV POPCORN 50GMS', 'productPool/1.jpg', 262 ),
( 'DEV POTATO CHIPS 100G', 'productPool/1.jpg', 254 ),
( 'DEV PUFFED RICE BALL', 'productPool/1.jpg', 14 ),
( 'DEV RICE MURUKU SMALL 225G', 'productPool/1.jpg', 96 ),
( 'DEV SALT CORN MIXTUE 175G', 'productPool/1.jpg', 135 ),
( 'DEV SALT DIAMOND 175GMS', 'productPool/1.jpg', 27 ),
( 'DEV SARKARAVARATY 150G', 'productPool/1.jpg', 253 ),
( 'DEV SPRING MULLU MURUKKU', 'productPool/1.jpg', 87 ),
( 'DEV SPRING MULLU MURUKKU 400G', 'productPool/1.jpg', 227 ),
( 'DEV SWEET CHIPS 175G', 'productPool/1.jpg', 198 ),
( 'DEV TABLE COVER HBT713', 'productPool/1.jpg', 140 ),
( 'DEV TAPIOCA STICK 175G', 'productPool/1.jpg', 196 ),
( 'DEV TEA TIME 175G', 'productPool/1.jpg', 45 ),
( 'DEV THATTA 150G', 'productPool/1.jpg', 171 ),
( 'DH PINEAPPLE JAM 200G', 'productPool/1.jpg', 138 ),
( 'DH PINEAPPLEJAM 100G', 'productPool/1.jpg', 253 ),
( 'DHADHU FLAXSEED PEANUT CHIKKI 100G', 'productPool/1.jpg', 25 ),
( 'DHADHU MORINGA PEANUT CHIKKI 180G', 'productPool/1.jpg', 57 ),
( 'DHATHRAMDANABALLWITHCOCONUTJAGGERY 75G', 'productPool/1.jpg', 75 ),
( 'DHATHRI ALOE VERA BEAUTY GEL 100G', 'productPool/1.jpg', 157 ),
( 'DHATHRI ANTI-BACTERIAL TURMERIC HW 250ML', 'productPool/1.jpg', 194 ),
( 'DHATHRI ANTI-DANDRUFF OIL 100ML', 'productPool/1.jpg', 119 ),
( 'DHATHRI CEMPARATHI THAALI 100 ML', 'productPool/1.jpg', 158 );