INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'RKG AGMARK GHEE 200ML', 'productPool/1.jpg', 198 ),
( 'RKG BRAND GHEE 5L', 'productPool/1.jpg', 170 ),
( 'RKG GHEE 2L', 'productPool/1.jpg', 164 ),
( 'RKG GHEE 50ML', 'productPool/1.jpg', 143 ),
( 'ROASTED AVALOOSEPODI 250G', 'productPool/1.jpg', 184 ),
( 'ROASTED AVALOOSEPODI 500G', 'productPool/1.jpg', 196 ),
( 'ROBAN RAT KILLER 100G', 'productPool/1.jpg', 241 ),
( 'ROBAN RATS KILLER 100G', 'productPool/1.jpg', 59 ),
( 'ROBAN RATS KILLER 25G', 'productPool/1.jpg', 9 ),
( 'ROBAN THE RAT KILLER 25GM', 'productPool/1.jpg', 267 ),
( 'ROBIN BLUE LIQUID 100 ML', 'productPool/1.jpg', 115 ),
( 'ROBIN CUFFSN COLLAR 200ML', 'productPool/1.jpg', 105 ),
( 'ROBIN DAZZLING WASH 200G', 'productPool/1.jpg', 162 ),
( 'ROBIN LIQUID BLEACH 500ML', 'productPool/1.jpg', 26 ),
( 'ROBIN POWDER BLUE 100 GM', 'productPool/1.jpg', 88 ),
( 'ROBUSTA COFFEE 50G', 'productPool/1.jpg', 277 ),
( 'ROCHER 24 PCS', 'productPool/1.jpg', 92 ),
( 'ROCHER 3 PCS IMP', 'productPool/1.jpg', 107 ),
( 'ROCHER FERRERO 16PCS', 'productPool/1.jpg', 194 ),
( 'ROHINI KUTTI PAPPADAM 60G', 'productPool/1.jpg', 210 ),
( 'ROHINI ONAM SPECIAL PAPPADAM RS 80', 'productPool/1.jpg', 214 ),
( 'ROHINI PAPPAD BIG', 'productPool/1.jpg', 130 ),
( 'ROHINI PAPPAD MRP 21', 'productPool/1.jpg', 19 ),
( 'ROHINI PAPPAD SMALL', 'productPool/1.jpg', 189 ),
( 'ROHINI PAPPADAM 20NOS', 'productPool/1.jpg', 189 ),
( 'ROHINI PAPPADAM MRP 11', 'productPool/1.jpg', 126 ),
( 'ROHINI PAPPADS MRP27', 'productPool/1.jpg', 224 ),
( 'ROHINI SPECIAL PAPPADAM 17N', 'productPool/1.jpg', 74 ),
( 'ROHINI SPECIAL PAPPADAM 50NOS', 'productPool/1.jpg', 60 ),
( 'ROLLON ASHAN', 'productPool/1.jpg', 48 ),
( 'ROLLON BLUE LADY', 'productPool/1.jpg', 255 ),
( 'ROLLON BLUELADY IMP', 'productPool/1.jpg', 99 ),
( 'ROLLON CC (B) IMP', 'productPool/1.jpg', 262 ),
( 'ROLLON CC (S)', 'productPool/1.jpg', 158 ),
( 'ROLLON FA IMP', 'productPool/1.jpg', 162 ),
( 'ROLLON JASMINE', 'productPool/1.jpg', 74 ),
( 'ROLLON JASMINE RS30', 'productPool/1.jpg', 130 ),
( 'ROLLON NIVEA', 'productPool/1.jpg', 218 ),
( 'ROLLON NIVEA IMP', 'productPool/1.jpg', 35 ),
( 'ROOH AFZA SHARBAT 750ML', 'productPool/1.jpg', 150 ),
( 'ROOT BROWN COMB 32A', 'productPool/1.jpg', 129 ),
( 'ROOT BROWN COMB 80', 'productPool/1.jpg', 137 ),
( 'ROOT BRUSH MOD NO 32B', 'productPool/1.jpg', 106 ),
( 'ROOT BRUSH MOD NO 33A', 'productPool/1.jpg', 28 ),
( 'ROOT BRUSH MOD NO 33B', 'productPool/1.jpg', 7 ),
( 'ROOT BRUSH MOD NO 36', 'productPool/1.jpg', 143 ),
( 'ROOT BRUSH MOD NO 42B', 'productPool/1.jpg', 154 ),
( 'ROOT BRUSH MOD NO 50', 'productPool/1.jpg', 171 ),
( 'ROOT BRUSH MOD NO 51', 'productPool/1.jpg', 60 ),
( 'ROOT BRUSH MOD NO 55', 'productPool/1.jpg', 252 ),
( 'ROOT BRUSH MOD NO 9553', 'productPool/1.jpg', 68 ),
( 'ROOT BRUSH MOD NO 9553S', 'productPool/1.jpg', 203 ),
( 'ROOT BRUSH MOD NO 9A', 'productPool/1.jpg', 180 ),
( 'ROOT BRUSH MOD NO RTS 35', 'productPool/1.jpg', 233 ),
( 'ROOT BRUSH MODEL NO 9B', 'productPool/1.jpg', 16 ),
( 'ROOT CONTOUR SERIES COMB C2', 'productPool/1.jpg', 172 ),
( 'ROOT HAIR BRUSH 9886', 'productPool/1.jpg', 264 ),
( 'ROOT HAIR BRUSH RTS 34', 'productPool/1.jpg', 189 ),
( 'ROOT HAIR COMB 26A', 'productPool/1.jpg', 80 ),
( 'ROOT HAIRBRUSH GG06-PL', 'productPool/1.jpg', 266 ),
( 'ROOT HAIRBRUSH RP 01', 'productPool/1.jpg', 36 ),
( 'ROOT HAIRCOMB 72', 'productPool/1.jpg', 66 ),
( 'ROOTS BLACK COMB 101', 'productPool/1.jpg', 142 ),
( 'ROOTS BLACK COMB 102', 'productPool/1.jpg', 156 ),
( 'ROOTS BLACK COMB 110', 'productPool/1.jpg', 107 ),
( 'ROOTS BLACK COMB 202', 'productPool/1.jpg', 7 ),
( 'ROOTS BLACK COMB 203', 'productPool/1.jpg', 88 ),
( 'ROOTS BLACK COMB 303', 'productPool/1.jpg', 276 ),
( 'ROOTS BROWN COMB 1', 'productPool/1.jpg', 195 ),
( 'ROOTS BROWN COMB 11', 'productPool/1.jpg', 14 ),
( 'ROOTS BROWN COMB 120A', 'productPool/1.jpg', 197 ),
( 'ROOTS BROWN COMB 120B', 'productPool/1.jpg', 206 ),
( 'ROOTS BROWN COMB 13B', 'productPool/1.jpg', 206 ),
( 'ROOTS BROWN COMB 14', 'productPool/1.jpg', 231 ),
( 'ROOTS BROWN COMB 27', 'productPool/1.jpg', 234 ),
( 'ROOTS BROWN COMB 37', 'productPool/1.jpg', 258 ),
( 'ROOTS BROWN COMB 39', 'productPool/1.jpg', 206 ),
( 'ROOTS BROWN COMB 4', 'productPool/1.jpg', 7 ),
( 'ROOTS BROWN COMB 41', 'productPool/1.jpg', 136 ),
( 'ROOTS BROWN COMB 42A', 'productPool/1.jpg', 125 ),
( 'ROOTS BROWN COMB 43', 'productPool/1.jpg', 166 ),
( 'ROOTS BROWN COMB 47', 'productPool/1.jpg', 102 ),
( 'ROOTS BROWN COMB 52', 'productPool/1.jpg', 93 ),
( 'ROOTS BROWN COMB 6', 'productPool/1.jpg', 26 ),
( 'ROOTS BROWN COMB 74', 'productPool/1.jpg', 121 ),
( 'ROOTS BROWN COMB 75', 'productPool/1.jpg', 235 ),
( 'ROOTS BROWN COMB 77', 'productPool/1.jpg', 265 ),
( 'ROOTS BROWN COMB MODEL 20', 'productPool/1.jpg', 279 ),
( 'ROOTS BROWN COMB MODEL 29', 'productPool/1.jpg', 173 ),
( 'ROOTS BROWN COMB MODEL 76', 'productPool/1.jpg', 23 ),
( 'ROOTS COMB 19', 'productPool/1.jpg', 251 ),
( 'ROOTS COMB MODEL 2', 'productPool/1.jpg', 99 ),
( 'ROOTS COMB MODEL 5A', 'productPool/1.jpg', 63 ),
( 'ROOTS COMB MODEL3', 'productPool/1.jpg', 70 ),
( 'ROOTS CONTOUR SERIES COMB C1', 'productPool/1.jpg', 199 ),
( 'ROOTS CONTOUR SERIES COMB C3', 'productPool/1.jpg', 220 ),
( 'ROOTS CONTOUR SERIES COMB C4', 'productPool/1.jpg', 217 ),
( 'ROOTS HAIR 21', 'productPool/1.jpg', 180 ),
( 'ROOTS HAIR 49', 'productPool/1.jpg', 205 ),
( 'ROOTS HAIR BRUSH 2011 ROUND', 'productPool/1.jpg', 179 ),
( 'ROOTS HAIR BRUSH 2012', 'productPool/1.jpg', 226 ),
( 'ROOTS HAIR BRUSH 9511S', 'productPool/1.jpg', 139 ),
( 'ROOTS HAIR BRUSH 9543', 'productPool/1.jpg', 33 ),
( 'ROOTS HAIR BRUSH 9611', 'productPool/1.jpg', 1 ),
( 'ROOTS HAIR BRUSH 9613', 'productPool/1.jpg', 160 ),
( 'ROOTS HAIR BRUSH BLU11', 'productPool/1.jpg', 13 ),
( 'ROOTS HAIR BRUSH BLU44', 'productPool/1.jpg', 215 ),
( 'ROOTS HAIR BRUSH CGM06', 'productPool/1.jpg', 137 ),
( 'ROOTS HAIR BRUSH CGM44', 'productPool/1.jpg', 2 ),
( 'ROOTS HAIR BRUSH CLR11', 'productPool/1.jpg', 275 ),
( 'ROOTS HAIR BRUSH EF 42', 'productPool/1.jpg', 132 ),
( 'ROOTS HAIR BRUSH GG06 -GR', 'productPool/1.jpg', 81 ),
( 'ROOTS HAIR BRUSH GG06-BL', 'productPool/1.jpg', 88 ),
( 'ROOTS HAIR BRUSH GG06-GR', 'productPool/1.jpg', 212 ),
( 'ROOTS HAIR BRUSH NE044', 'productPool/1.jpg', 126 ),
( 'ROOTS HAIR BRUSH NEO11', 'productPool/1.jpg', 278 ),
( 'ROOTS HAIR BRUSH PYB11', 'productPool/1.jpg', 149 ),
( 'ROOTS HAIR BRUSH PYB44', 'productPool/1.jpg', 53 ),
( 'ROOTS HAIR BRUSH RJ1', 'productPool/1.jpg', 274 ),
( 'ROOTS HAIR BRUSH RR01', 'productPool/1.jpg', 1 ),
( 'ROOTS HAIR BRUSH RSL02', 'productPool/1.jpg', 193 ),
( 'ROOTS HAIR BRUSH RSL32', 'productPool/1.jpg', 206 ),
( 'ROOTS HAIR BRUSH RTS03', 'productPool/1.jpg', 173 ),
( 'ROOTS HAIR BRUSH STR11', 'productPool/1.jpg', 91 ),
( 'ROOTS HAIR BRUSH STR66', 'productPool/1.jpg', 128 ),
( 'ROOTS HAIR COMB 10', 'productPool/1.jpg', 41 ),
( 'ROOTS HAIR COMB 104', 'productPool/1.jpg', 17 ),
( 'ROOTS HAIR COMB 16', 'productPool/1.jpg', 172 ),
( 'ROOTS HAIR COMB 22', 'productPool/1.jpg', 78 ),
( 'ROOTS HAIR COMB 31', 'productPool/1.jpg', 215 ),
( 'ROOTS HAIR COMB 38', 'productPool/1.jpg', 143 ),
( 'ROOTS HAIR COMB 48', 'productPool/1.jpg', 67 ),
( 'ROOTS HAIR COMB 4C', 'productPool/1.jpg', 255 ),
( 'ROOTS HAIR COMB 53', 'productPool/1.jpg', 76 ),
( 'ROOTS HAIR COMB 9543S', 'productPool/1.jpg', 92 ),
( 'ROOTS HAIRBRUSH GG06-PK', 'productPool/1.jpg', 120 ),
( 'ROOTS PROFESSIONAL TOOLS 109', 'productPool/1.jpg', 267 ),
( 'ROOTS PROFESSIONALTOOL402', 'productPool/1.jpg', 225 ),
( 'ROOTS STARGLAM STR44', 'productPool/1.jpg', 20 ),
( 'ROOTS TRU GLAM MODEL NO RTS03', 'productPool/1.jpg', 32 ),
( 'ROOTS WOTTABRUSH RWO PL', 'productPool/1.jpg', 142 ),
( 'ROOTS106', 'productPool/1.jpg', 260 ),
( 'ROOTS28', 'productPool/1.jpg', 94 ),
( 'ROOTS30A', 'productPool/1.jpg', 19 ),
( 'ROOTS34A', 'productPool/1.jpg', 27 ),
( 'ROOTS35', 'productPool/1.jpg', 200 ),
( 'ROOTS78', 'productPool/1.jpg', 46 ),
( 'ROPE', 'productPool/1.jpg', 108 ),
( 'ROPE 1KG', 'productPool/1.jpg', 99 ),
( 'ROPE BIG', 'productPool/1.jpg', 32 ),
( 'ROPE MEDIUM', 'productPool/1.jpg', 174 ),
( 'ROPE N0.4', 'productPool/1.jpg', 132 ),
( 'ROPE NO.5', 'productPool/1.jpg', 249 ),
( 'ROPE NO.6', 'productPool/1.jpg', 91 ),
( 'ROPE RS 36', 'productPool/1.jpg', 165 ),
( 'ROPE RS18', 'productPool/1.jpg', 84 ),
( 'ROPE RS36', 'productPool/1.jpg', 97 ),
( 'ROPE SMALL', 'productPool/1.jpg', 100 ),
( 'RORITO CORRECTION PEN 5ML', 'productPool/1.jpg', 115 ),
( 'RORITO FACINATE PEN', 'productPool/1.jpg', 204 ),
( 'RORITO FANTA FLO BLACK PEN', 'productPool/1.jpg', 82 ),
( 'RORITO FANTA GLIDE PEN BLACK', 'productPool/1.jpg', 73 ),
( 'RORITO FASTY GEL PEN BLUE', 'productPool/1.jpg', 133 ),
( 'RORITO FLEXIGLO HIGHLIGHTER', 'productPool/1.jpg', 78 ),
( 'RORITO FLYMAX GEL BLACK PEN WATER PROOF INK', 'productPool/1.jpg', 135 ),
( 'RORITO FLYMO FOUNTAIN PEN', 'productPool/1.jpg', 255 ),
( 'RORITO GIFTS GRATZ PEN GOLD', 'productPool/1.jpg', 218 ),
( 'RORITO GOLD FEATHERSOFT RS50', 'productPool/1.jpg', 234 ),
( 'RORITO GREETZ GLAMATIC PEN', 'productPool/1.jpg', 132 ),
( 'RORITO GREETZ GRANDE 522', 'productPool/1.jpg', 19 ),
( 'RORITO GREETZ GRANDE GOLD PEN', 'productPool/1.jpg', 181 ),
( 'RORITO HAPPY HOO FUN DOUGH KIT 12COLOURS', 'productPool/1.jpg', 219 ),
( 'RORITO HAPPY HOO FUN DOUGH KIT 24COLOURS', 'productPool/1.jpg', 229 ),
( 'RORITO HAPPY HOO FUNDOUGH 12 COLOURS', 'productPool/1.jpg', 212 ),
( 'RORITO HAPPY HOO SKETCH PEN', 'productPool/1.jpg', 127 ),
( 'RORITO I SKATE BALL PEN', 'productPool/1.jpg', 249 ),
( 'RORITO INK PEN', 'productPool/1.jpg', 78 ),
( 'RORITO JOSH GEL PEN MRP 6', 'productPool/1.jpg', 27 ),
( 'RORITO JOTTEK CLASSIC PEN MRP-20', 'productPool/1.jpg', 71 ),
( 'RORITO JOTTEK FEATHER SOFT PEN', 'productPool/1.jpg', 36 ),
( 'RORITO JOTTEX AEROGEN PEN', 'productPool/1.jpg', 15 ),
( 'RORITO JOTTEX RAVIA BALL PEN', 'productPool/1.jpg', 139 ),
( 'RORITO MAXTRON PEN', 'productPool/1.jpg', 139 ),
( 'RORITO MYPRO GELPEN RED/BLACKRS 6', 'productPool/1.jpg', 100 ),
( 'RORITO PRIDO FOUNTAIN PEN RS 30', 'productPool/1.jpg', 241 ),
( 'RORITO PRIME FIT PEN', 'productPool/1.jpg', 115 ),
( 'RORITO RACEMAX GEL RED/GREEN', 'productPool/1.jpg', 97 ),
( 'RORITO RACER ERFILL', 'productPool/1.jpg', 59 ),
( 'RORITO TMAX PEN BLUE', 'productPool/1.jpg', 191 ),
( 'RORITO WHITEBOARD MARKER', 'productPool/1.jpg', 247 ),
( 'RORITO ZAPPER BALL PEN', 'productPool/1.jpg', 70 ),
( 'ROSE ACCORD STRAINER -3', 'productPool/1.jpg', 212 ),
( 'ROSE CANDLE RS25', 'productPool/1.jpg', 79 ),
( 'ROSE COCONUT POWDER 1KG', 'productPool/1.jpg', 42 ),
( 'ROSE CUTTER SK', 'productPool/1.jpg', 243 ),
( 'ROSE NOSE STRIPS 1STRIP', 'productPool/1.jpg', 167 ),
( 'ROSE POWER ACTIVE 100 G', 'productPool/1.jpg', 43 ),
( 'ROSE SUMEET CHALNI', 'productPool/1.jpg', 111 ),
( 'ROSE TEA STRAINER NO4', 'productPool/1.jpg', 109 ),
( 'ROSE WATER 200ML', 'productPool/1.jpg', 76 ),
( 'ROSE WATER 60ML', 'productPool/1.jpg', 160 ),
( 'ROSE WATER PANINEER 500ML', 'productPool/1.jpg', 116 ),
( 'ROSE WATER PANINER 100ML', 'productPool/1.jpg', 158 ),
( 'ROSEMARY LEAF 25G', 'productPool/1.jpg', 120 ),
( 'ROSTAA BERRYLICIOUS 200G', 'productPool/1.jpg', 187 ),
( 'ROSTAA BLUBERRIES 150G', 'productPool/1.jpg', 130 ),
( 'ROSTAA CHERRIES 200G', 'productPool/1.jpg', 226 ),
( 'ROSTAA CLASSIC ALMONDS 200G', 'productPool/1.jpg', 49 ),
( 'ROSTAA CRANBERRIES SLICED 200G', 'productPool/1.jpg', 269 ),
( 'ROSTAA CRANBERRY BLUEBERRY 200G', 'productPool/1.jpg', 265 ),
( 'ROSTAA FIGS 200G', 'productPool/1.jpg', 270 ),
( 'ROSTAA FRUIT BERRY 200G', 'productPool/1.jpg', 115 ),
( 'ROSTAA GOLDEN BERRIES 200G', 'productPool/1.jpg', 252 ),
( 'ROSTAA GOURMET APRICOTS 200G', 'productPool/1.jpg', 112 ),
( 'ROSTAA HAZELNUTS 200G', 'productPool/1.jpg', 168 ),
( 'ROSTAA KALMI DATES 680G', 'productPool/1.jpg', 257 ),
( 'ROSTAA MORNING BERRIES 340G', 'productPool/1.jpg', 177 ),
( 'ROSTAA PRUNES 227G', 'productPool/1.jpg', 34 ),
( 'ROSTAA PUMPKIN SEEDS 200G', 'productPool/1.jpg', 178 ),
( 'ROSTAA SUNFLOWER SEEDS 200G', 'productPool/1.jpg', 136 ),
( 'ROSTAA TRAIL MIX 340G', 'productPool/1.jpg', 231 ),
( 'ROSTAAGOURMET OMANI DATES680G', 'productPool/1.jpg', 83 ),
( 'ROSTTA CRANBERRY WHOLE 200G', 'productPool/1.jpg', 12 ),
( 'ROUND COMB RS7.50', 'productPool/1.jpg', 208 ),
( 'ROUND KARASEVA', 'productPool/1.jpg', 57 ),
( 'ROUND MURUKKU', 'productPool/1.jpg', 215 ),
( 'ROUND PAKKAVADA', 'productPool/1.jpg', 84 ),
( 'ROYAL APPLE', 'productPool/1.jpg', 146 ),
( 'ROYAL CANDLE', 'productPool/1.jpg', 63 ),
( 'ROYAL CANDLE 30PCS', 'productPool/1.jpg', 51 ),
( 'ROYAL CANDLES 5G 30N', 'productPool/1.jpg', 132 ),
( 'ROYAL CASHEW BORMA 250G', 'productPool/1.jpg', 130 ),
( 'ROYAL CASHEW BORMA 500G', 'productPool/1.jpg', 171 ),
( 'ROYAL CASHEW W 180 500G', 'productPool/1.jpg', 136 ),
( 'ROYAL CASHEW W 240 1KG', 'productPool/1.jpg', 85 ),
( 'ROYAL CASHEW W 240 500G', 'productPool/1.jpg', 28 ),
( 'ROYAL CASHEW W 320 100G', 'productPool/1.jpg', 236 ),
( 'ROYAL CASHEW W 320 500G', 'productPool/1.jpg', 53 ),
( 'ROYAL CASHEW W240 250GMS', 'productPool/1.jpg', 273 ),
( 'ROYAL CASHEW W320 250G', 'productPool/1.jpg', 268 ),
( 'ROYAL CORN POWDER 500G', 'productPool/1.jpg', 214 ),
( 'ROYAL DANSK CHOCOCHIP COOKIES', 'productPool/1.jpg', 110 ),
( 'ROYAL EXECUTIVE BOND', 'productPool/1.jpg', 115 ),
( 'ROYAL EXECUTIVE BOND 10PCS', 'productPool/1.jpg', 84 ),
( 'ROYAL GALA APPLE', 'productPool/1.jpg', 176 ),
( 'ROYAL HEALTH MIX FOD 1KG', 'productPool/1.jpg', 20 ),
( 'ROYAL HEALTH MIX POW 500G', 'productPool/1.jpg', 155 ),
( 'ROYAL HEALTH MIX POWDER 1 KG JAR', 'productPool/1.jpg', 208 ),
( 'ROYAL HEALTH MIX POWDER 500G JAR', 'productPool/1.jpg', 116 ),
( 'ROYAL HEALTH MIX ROAST 1KG PKT', 'productPool/1.jpg', 8 ),
( 'ROYAL HOOK', 'productPool/1.jpg', 188 ),
( 'ROYAL MUG 1500 TRAN FAMILY', 'productPool/1.jpg', 94 ),
( 'ROYAL NAPKINS 100', 'productPool/1.jpg', 142 ),
( 'ROYAL PALADA MIX 250G', 'productPool/1.jpg', 153 ),
( 'ROYAL PAYASAM MIX 300G', 'productPool/1.jpg', 119 ),
( 'ROYAL RAGI POWDER 500G', 'productPool/1.jpg', 113 ),
( 'ROYAL ROBUSTA COFFEE 100G', 'productPool/1.jpg', 2 ),
( 'ROYAL ROBUSTA COFFEE 250G', 'productPool/1.jpg', 37 ),
( 'ROYAL SOAP BOX PRINT FAMILY', 'productPool/1.jpg', 164 ),
( 'ROYAL SPILT CASHEW 100G', 'productPool/1.jpg', 265 ),
( 'ROYAL SPILT CASHEW 1KG', 'productPool/1.jpg', 86 ),
( 'ROYAL W 320 CASHEWE 1KG', 'productPool/1.jpg', 235 ),
( 'ROYAL Y PEELER', 'productPool/1.jpg', 240 ),
( 'ROYALTY CELEBRATION DRINK MANGO 750ML', 'productPool/1.jpg', 157 ),
( 'ROYALTY CELEBRATION DRINK PEACH 750ML', 'productPool/1.jpg', 272 ),
( 'ROYALTY CELEBRATION DRINK WHITE GRAPE 750ML', 'productPool/1.jpg', 160 ),
( 'ROYALTY GINGER BEER 330ML', 'productPool/1.jpg', 228 ),
( 'RPYAL NAPKIN 100', 'productPool/1.jpg', 62 ),
( 'RR CHALINI 2 IN 1', 'productPool/1.jpg', 149 ),
( 'RR KAPPA STICK 200G', 'productPool/1.jpg', 8 ),
( 'RRKAPPA BLADE CHIPS 200G', 'productPool/1.jpg', 80 ),
( 'RROOTS PROFESSIONAL TOOLS 302', 'productPool/1.jpg', 169 ),
( 'RS70 500G CRYSTL ADA BAMBINO', 'productPool/1.jpg', 198 ),
( 'RUBBER BAND 1KG', 'productPool/1.jpg', 1 ),
( 'RUBCO NUTRI COCO OIL 75M', 'productPool/1.jpg', 220 ),
( 'RUBCO NUTRI COCO OIL175ML', 'productPool/1.jpg', 240 ),
( 'RUBCO NUTRI COCONUT OIL 500ML', 'productPool/1.jpg', 143 ),
( 'RUBCO NUTRI-VIRGIN CONUTOIL1L', 'productPool/1.jpg', 74 ),
( 'RUCHI FOODS PRAWN ROASTED 10GM', 'productPool/1.jpg', 112 ),
( 'RUCHI GOLD PALMOLIN 1LTR', 'productPool/1.jpg', 40 ),
( 'RUCHI GOLD PALMOLIN 500ML', 'productPool/1.jpg', 189 ),
( 'RUCHI GOLD PALMOLIN 5LTR', 'productPool/1.jpg', 202 ),
( 'RUGBY FLIP 1 LTR BOTTLE', 'productPool/1.jpg', 148 ),
( 'RUM BALLS', 'productPool/1.jpg', 15 ),
( 'RYCA CONCHIGLIGLIE ARTISANAL PASTA 500G', 'productPool/1.jpg', 76 ),
( 'RYCA ELBOWS ARTISANAL PASTA 500G', 'productPool/1.jpg', 268 ),
( 'RYCA FUSILLI ARTISANAL PASTA500G', 'productPool/1.jpg', 199 ),
( 'RYCA OLIVE POMACE OIL 1L', 'productPool/1.jpg', 168 ),
( 'RYCA OLIVES GREEN OLIVESWITH PIMIENTO PASTE 200G', 'productPool/1.jpg', 71 ),
( 'RYCA OLIVES PITTED GREEN OLIVES 180G', 'productPool/1.jpg', 60 ),
( 'S J TOMATO KETCHUP 200G', 'productPool/1.jpg', 277 ),
( 'S S FOODS AVAL FRY 125g', 'productPool/1.jpg', 156 ),
( 'S S FOODS AVAL FRY 250G', 'productPool/1.jpg', 10 ),
( 'S S FOODS MAVUNDA', 'productPool/1.jpg', 10 ),
( 'S.R FOODS PAKKAVADA 200G', 'productPool/1.jpg', 179 ),
( 'S.R FOODS TAPIOCA CHIPS 200G', 'productPool/1.jpg', 40 ),
( 'S.R GHEE MURUKKU 200GM', 'productPool/1.jpg', 217 ),
( 'S.R GHEE MURUKKU 500GM', 'productPool/1.jpg', 153 ),
( 'S.R KERALA MIXTURE 500G', 'productPool/1.jpg', 20 ),
( 'S.R MIXTURE 200G', 'productPool/1.jpg', 223 ),
( 'S.R POTATAO CHIPS 100G', 'productPool/1.jpg', 237 ),
( 'SAAGI CHILLY CASHEW 100G', 'productPool/1.jpg', 93 ),
( 'SAAGI CHILLY CASHEW 200G', 'productPool/1.jpg', 188 ),
( 'SAAGI PEPPER CASHEW 100G', 'productPool/1.jpg', 206 ),
( 'SAAGI PEPPER CASHEW 200G', 'productPool/1.jpg', 50 ),
( 'SAAGI SWEET AMLA 100G', 'productPool/1.jpg', 199 ),
( 'SAAGI SWEET GINGER 100G', 'productPool/1.jpg', 180 ),
( 'SAAGI W180 CASHEW 100G', 'productPool/1.jpg', 270 ),
( 'SAAGI W180 CASHEW 200G', 'productPool/1.jpg', 36 ),
( 'SAAGI W240 CASHEW 100G', 'productPool/1.jpg', 220 ),
( 'SAAGI W240 CASHEW 200G', 'productPool/1.jpg', 250 ),
( 'SAAGI W240 CASHEW 400G', 'productPool/1.jpg', 22 ),
( 'SAAGIW180 CASHEW 400G', 'productPool/1.jpg', 174 ),
( 'SABAR JELLY', 'productPool/1.jpg', 111 ),
( 'SABARI DARK SOYA SAUCE 120G', 'productPool/1.jpg', 275 ),
( 'SABARI DARK SOYA SAUCE 200G', 'productPool/1.jpg', 242 ),
( 'SABARI DATES JAM 200G', 'productPool/1.jpg', 193 ),
( 'SABARI GREEN CHILLY SAUCE 120G', 'productPool/1.jpg', 147 ),
( 'SABARI GREEN CHILLY SAUCE 200G', 'productPool/1.jpg', 38 ),
( 'SABARI MIXED FRUIT JAM 100G', 'productPool/1.jpg', 240 ),
( 'SABARI MIXED FRUIT JAM 200G', 'productPool/1.jpg', 245 ),
( 'SABARI PINEAPPLE FRUIT JAM 100G', 'productPool/1.jpg', 128 ),
( 'SABARI PINEAPPLE FRUIT JAM 200G', 'productPool/1.jpg', 215 ),
( 'SABARI TOMATO SAUCE 120G', 'productPool/1.jpg', 125 ),
( 'SABARI TOMATO SAUCE 1KG', 'productPool/1.jpg', 136 ),
( 'SABARI TOMATO SAUCE 200G', 'productPool/1.jpg', 198 ),
( 'SABEENA BAR 125G', 'productPool/1.jpg', 265 ),
( 'SABEENA CLEAN 500G', 'productPool/1.jpg', 55 ),
( 'SABEENA DISH WASH CITRUS PLUS 250G', 'productPool/1.jpg', 205 ),
( 'SABEENA DISH WASH CITRUS PLUS 500GM', 'productPool/1.jpg', 153 ),
( 'SABENA CLEAN 1KG', 'productPool/1.jpg', 63 ),
( 'SADHYA UNDA MATTA RICE 10KG', 'productPool/1.jpg', 128 ),
( 'SADHYA UNDA MATTA RICE 5KG', 'productPool/1.jpg', 88 ),
( 'SADHYA VADI MATTA RICE 10KG', 'productPool/1.jpg', 153 ),
( 'SADHYA VADI MATTA RICE 5KG', 'productPool/1.jpg', 43 ),
( 'SAFARI WASTE BASKET', 'productPool/1.jpg', 173 ),
( 'SAFETY PIN', 'productPool/1.jpg', 161 ),
( 'SAFETY PIN NO4', 'productPool/1.jpg', 107 ),
( 'SAFETY PIN RS 14.25', 'productPool/1.jpg', 229 ),
( 'SAFETY PIN RS 2.25', 'productPool/1.jpg', 46 ),
( 'SAFETY PIN RS10.50', 'productPool/1.jpg', 214 ),
( 'SAFETY PIN RS5.50', 'productPool/1.jpg', 135 ),
( 'SAFFOLA ACTIVE 1L', 'productPool/1.jpg', 194 ),
( 'SAFFOLA ACTIVE LOSORB 1L', 'productPool/1.jpg', 274 ),
( 'SAFFOLA GOLD 1LTR', 'productPool/1.jpg', 266 ),
( 'SAFFOLA GOLD 2 LTR PET', 'productPool/1.jpg', 56 ),
( 'SAFFOLA GOLD 5LTR', 'productPool/1.jpg', 207 ),
( 'SAFFOLA MASALA OATS 35G', 'productPool/1.jpg', 194 ),
( 'SAFFOLA MASALA OATS 400G', 'productPool/1.jpg', 274 ),
( 'SAFFOLA MASALA OATS 500G', 'productPool/1.jpg', 142 ),
( 'SAFFOLA MASALA OATS LEMONY TWIST 39G', 'productPool/1.jpg', 199 ),
( 'SAFFOLA MASALA OATS MASALA CORIANDER 500G', 'productPool/1.jpg', 254 ),
( 'SAFFOLA MASALA OATS MINT CHUTNEY 39G', 'productPool/1.jpg', 96 ),
( 'SAFFOLA MASALA OATS MUMBAI PAV BHAJI 32G', 'productPool/1.jpg', 75 ),
( 'SAFFOLA MASALA OATS PAV BHAJI 120G', 'productPool/1.jpg', 214 ),
( 'SAFFOLA MASALA OATS PEPPY TOMATO 120G', 'productPool/1.jpg', 170 ),
( 'SAFFOLA MASALA OATS VEGGIE TWIST 40G', 'productPool/1.jpg', 119 ),
( 'SAFFOLA OATS 1KG', 'productPool/1.jpg', 170 ),
( 'SAFFOLA OATS 400 G', 'productPool/1.jpg', 5 ),
( 'SAFFOLA OATS 500G FREE JAR', 'productPool/1.jpg', 53 ),
( 'SAFFOLA OATS CURRY & PEPPER 400G', 'productPool/1.jpg', 179 ),
( 'SAFFOLA OATS VEG 400G', 'productPool/1.jpg', 159 ),
( 'SAFFOLA TASTY 5 LTR PET', 'productPool/1.jpg', 239 ),
( 'SAFFOLA TOTAL OIL 5L JAR', 'productPool/1.jpg', 95 ),
( 'SAFT BABY WIPS 80', 'productPool/1.jpg', 117 ),
( 'SAGAR CHOPPING BOARD -1', 'productPool/1.jpg', 276 ),
( 'SAGAR CHOPPING BOARD 2', 'productPool/1.jpg', 242 ),
( 'SAGAR CLIP 6PCS STEEL', 'productPool/1.jpg', 250 ),
( 'SAGAR STEEL HANGER RS166', 'productPool/1.jpg', 236 ),
( 'SAGAR SUPER CLASSIC TEA FILTTER 3', 'productPool/1.jpg', 130 ),
( 'SAGAR TEA COFFEE STRAINERS BIG', 'productPool/1.jpg', 220 ),
( 'SAGAR VEGETABLE GREATER', 'productPool/1.jpg', 159 ),
( 'SAGAR VESSEL LIFTER -BIG', 'productPool/1.jpg', 270 ),
( 'SAGAR WOODEN POLPAT 9 (CHAPATHI PALAKA)', 'productPool/1.jpg', 93 ),
( 'SAGAR YASHENG PLASTIC SPOON 12PC', 'productPool/1.jpg', 266 ),
( 'SAGARA ARISTO BABY SPOON 14G', 'productPool/1.jpg', 227 ),
( 'SAGARA ARISTO COFFEE SPOON 14G', 'productPool/1.jpg', 97 ),
( 'SAGARA ARISTO DESERT SPOON 14G', 'productPool/1.jpg', 114 ),
( 'SAGARA ARISTO LADDLE - 3 INCH', 'productPool/1.jpg', 200 ),
( 'SAGARA ARISTO LADDLE -0', 'productPool/1.jpg', 172 ),
( 'SAGARA ARISTO LADDLE -1 INCH', 'productPool/1.jpg', 11 ),
( 'SAGARA ARISTO LADDLE -2 INCH', 'productPool/1.jpg', 88 ),
( 'SAGARA ARISTO LADDLE -4 INCH', 'productPool/1.jpg', 139 ),
( 'SAGARA ARISTO LADDLE -6 INCH', 'productPool/1.jpg', 121 ),
( 'SAGARA ARISTO PAN -1 INCH', 'productPool/1.jpg', 248 ),
( 'SAGARA ARISTO PAN -3 INCH', 'productPool/1.jpg', 47 ),
( 'SAGARA ARISTO PAN-0', 'productPool/1.jpg', 47 ),
( 'SAGARA ARISTO PAN-2 INCH', 'productPool/1.jpg', 169 ),
( 'SAGARA ARISTO TABLE SPOON 14G', 'productPool/1.jpg', 237 ),
( 'SAGARA ARISTO TEA SPOON 14G', 'productPool/1.jpg', 202 ),
( 'SAGARA BEETER PIPE BIG', 'productPool/1.jpg', 182 ),
( 'SAGARA BEETER PIPE NEW MEDIUM', 'productPool/1.jpg', 256 ),
( 'SAGARA CAKE TONG', 'productPool/1.jpg', 59 ),
( 'SAGARA CHOPPING BOARD 3', 'productPool/1.jpg', 205 ),
( 'SAGARA CLIP JUMBO DLX 6PCS STEEL', 'productPool/1.jpg', 59 ),
( 'SAGARA CLIP LUXURY STEEL 6PCS', 'productPool/1.jpg', 9 ),
( 'SAGARA CNA HOOK STEEL 3PCS', 'productPool/1.jpg', 20 ),
( 'SAGARA CNA HOOK STEEL 6PCS', 'productPool/1.jpg', 82 ),
( 'SAGARA COLANDER STRAINER S 571', 'productPool/1.jpg', 17 ),
( 'SAGARA COLONDER HEAVY 2', 'productPool/1.jpg', 261 ),
( 'SAGARA COLOR CUTTING BOARD-2', 'productPool/1.jpg', 186 ),
( 'SAGARA COLOR CUTTING BOARD-3', 'productPool/1.jpg', 120 ),
( 'SAGARA DOSA TAWA 10', 'productPool/1.jpg', 125 ),
( 'SAGARA DOSA TAWA 11', 'productPool/1.jpg', 268 ),
( 'SAGARA EGG BEETER', 'productPool/1.jpg', 133 ),
( 'SAGARA FRYING STIR (S.S)PIPE 18', 'productPool/1.jpg', 251 ),
( 'SAGARA FRYING STIR(S.S)PIPE 20', 'productPool/1.jpg', 11 ),
( 'SAGARA FRYING STR (S.S)PIPE 16', 'productPool/1.jpg', 148 ),
( 'SAGARA FRYING STRAINER 14', 'productPool/1.jpg', 32 ),
( 'SAGARA JARA NO-2', 'productPool/1.jpg', 78 ),
( 'SAGARA JARA NO.1', 'productPool/1.jpg', 82 ),
( 'SAGARA KETHALA', 'productPool/1.jpg', 132 ),
( 'SAGARA KITCHEN SCISSORS DIAMOND', 'productPool/1.jpg', 216 ),
( 'SAGARA LADDLE NO.1', 'productPool/1.jpg', 72 ),
( 'SAGARA LADDLE NO.2', 'productPool/1.jpg', 117 ),
( 'SAGARA LADDLE NO.3', 'productPool/1.jpg', 74 ),
( 'SAGARA LADDLE NO.4', 'productPool/1.jpg', 136 ),
( 'SAGARA LADDLE NO.5', 'productPool/1.jpg', 142 ),
( 'SAGARA LADDLE NO.6', 'productPool/1.jpg', 173 ),
( 'SAGARA LADDLE NO.7', 'productPool/1.jpg', 192 ),
( 'SAGARA LIFTER JUMBO', 'productPool/1.jpg', 115 ),
( 'SAGARA MK TONG-3', 'productPool/1.jpg', 240 ),
( 'SAGARA MK TONG-4', 'productPool/1.jpg', 86 ),
( 'SAGARA MULTI PURPOSE HOLDER', 'productPool/1.jpg', 241 ),
( 'SAGARA OVAL NO.0', 'productPool/1.jpg', 110 ),
( 'SAGARA OVAL NO.1', 'productPool/1.jpg', 232 ),
( 'SAGARA OVAL NO.2', 'productPool/1.jpg', 23 ),
( 'SAGARA OVAL NO.3', 'productPool/1.jpg', 204 ),
( 'SAGARA OVAL NO.4', 'productPool/1.jpg', 274 ),
( 'SAGARA OVAL NO.5', 'productPool/1.jpg', 140 ),
( 'SAGARA OVAL PICK', 'productPool/1.jpg', 59 ),
( 'SAGARA PLASTIC SPOON 6PCS', 'productPool/1.jpg', 41 ),
( 'SAGARA PLASTIC T.SPOON 12PCS', 'productPool/1.jpg', 63 ),
( 'SAGARA PLATE STAND (8 PLATE)', 'productPool/1.jpg', 58 ),
( 'SAGARA PLUS OVAL NO.1', 'productPool/1.jpg', 24 ),
( 'SAGARA PLUS OVAL NO.2', 'productPool/1.jpg', 55 ),
( 'SAGARA PLUS OVAL NO.3', 'productPool/1.jpg', 174 ),
( 'SAGARA PLUS OVAL NO.4', 'productPool/1.jpg', 228 ),
( 'SAGARA PLUS OVAL NO.5', 'productPool/1.jpg', 178 ),
( 'SAGARA POLPAT', 'productPool/1.jpg', 87 ),
( 'SAGARA POLPAT COLOR 10', 'productPool/1.jpg', 17 ),
( 'SAGARA ROSE ACCORD STRAINER -1', 'productPool/1.jpg', 211 ),
( 'SAGARA ROSE ACCORD STRAINER -2', 'productPool/1.jpg', 4 ),
( 'SAGARA SCISSOR REGULAR', 'productPool/1.jpg', 39 ),
( 'SAGARA SCISSORS CHOICE', 'productPool/1.jpg', 90 ),
( 'SAGARA SERVING TONG MEDIUM', 'productPool/1.jpg', 225 ),
( 'SAGARA SERVING TONG SMALL', 'productPool/1.jpg', 13 ),
( 'SAGARA SERVING TONG X LARGE', 'productPool/1.jpg', 151 ),
( 'SAGARA SINK DRINER MESH-2', 'productPool/1.jpg', 82 ),
( 'SAGARA SINK DRINER MESH-3', 'productPool/1.jpg', 151 ),
( 'SAGARA SUPER CLASSIC TEA STRAINER 1', 'productPool/1.jpg', 67 ),
( 'SAGARA SUPIDI (SQ) 3', 'productPool/1.jpg', 38 ),
( 'SAGARA SUPIDI RND3', 'productPool/1.jpg', 147 ),
( 'SAGARA TAVETTA WH 0', 'productPool/1.jpg', 132 ),
( 'SAGARA TAVETTA WH 1', 'productPool/1.jpg', 222 ),
( 'SAGARA TAVETTA WH 3', 'productPool/1.jpg', 138 ),
( 'SAGARA TAVETTA WH 4', 'productPool/1.jpg', 28 ),
( 'SAGARA TAVETTA WH 5', 'productPool/1.jpg', 73 ),
( 'SAGARA TAVETTA WH-2', 'productPool/1.jpg', 231 ),
( 'SAGARA TEA STRAINER -4', 'productPool/1.jpg', 191 ),
( 'SAGARA TEA STRAINER -5', 'productPool/1.jpg', 139 ),
( 'SAGARA TONG SAG128', 'productPool/1.jpg', 185 ),
( 'SAGARA VESSEL LIFTER SMALL', 'productPool/1.jpg', 137 ),
( 'SAGARA WALL HOOK LX SR421', 'productPool/1.jpg', 111 ),
( 'SAGARA WALL HOOK LX SR422', 'productPool/1.jpg', 114 ),
( 'SAGARA WALL HOOK REGULAR SR904', 'productPool/1.jpg', 118 ),
( 'SAGARA WALL HOOK REGULAR SR905', 'productPool/1.jpg', 12 ),
( 'SAGARA WOODEN BELEN HEAVY', 'productPool/1.jpg', 230 ),
( 'SAGARA WOODEN BELEN(WHITE)', 'productPool/1.jpg', 151 ),
( 'SAGARA WOODEN PAN NO4', 'productPool/1.jpg', 232 ),
( 'SAGARA WOODEN POLPAT 10(CHAPATHI PALAKA)', 'productPool/1.jpg', 193 ),
( 'SAI MORA BATHI', 'productPool/1.jpg', 30 ),
( 'SAJ NATURAL WHEAT SPROUT 500G', 'productPool/1.jpg', 45 ),
( 'SAJEERAKAM 50G', 'productPool/1.jpg', 23 ),
( 'SAKTHI 10A WHITE CANDLES', 'productPool/1.jpg', 65 ),
( 'SAKTHI CAMPHOR 15GM', 'productPool/1.jpg', 229 ),
( 'SAKTHI CAMPHOR 50GM', 'productPool/1.jpg', 87 ),
( 'SAKTHI CANDLE TYPE 12WHITE', 'productPool/1.jpg', 167 ),
( 'SAKTHI CHURCH CANDLE', 'productPool/1.jpg', 180 ),
( 'SAKTHI COLOUR CANDLES TYPE 12', 'productPool/1.jpg', 90 ),
( 'SAKTHI COLOUR CANDLES TYPE 13', 'productPool/1.jpg', 123 ),
( 'SAKTHI COLOUR CANDLES TYPE 4', 'productPool/1.jpg', 235 ),
( 'SAKTHI COTTON LAMP WICK 20G MRP10', 'productPool/1.jpg', 239 ),
( 'SAKTHI COTTON LAMP WICK 300N MRP15', 'productPool/1.jpg', 144 ),
( 'SAKTHI CUP CANDLE BIG', 'productPool/1.jpg', 46 ),
( 'SAKTHI CUP CANDLE SMALL', 'productPool/1.jpg', 176 ),
( 'SAKTHI GHEE 100ML', 'productPool/1.jpg', 16 ),
( 'SAKTHI GHEE 200ML', 'productPool/1.jpg', 92 ),
( 'SAKTHI GHEE 500ML', 'productPool/1.jpg', 250 ),
( 'SAKTHI GHEE 50ML', 'productPool/1.jpg', 109 ),
( 'SAKTHI GOLD AGARBATHI', 'productPool/1.jpg', 144 ),
( 'SAKTHI KUNTHIRIKAM 50G', 'productPool/1.jpg', 242 ),
( 'SAKTHI KUNTHIRIKKAM 100G', 'productPool/1.jpg', 259 ),
( 'SAKTHI LAMP WICK 32', 'productPool/1.jpg', 81 ),
( 'SAKTHI LAMP WICK RS 37.50', 'productPool/1.jpg', 237 ),
( 'SAKTHI LAMP WICK RS15', 'productPool/1.jpg', 31 ),
( 'SAKTHI LAMP WICK RS30', 'productPool/1.jpg', 270 ),
( 'SAKTHI LAMP WICK SMALL 10', 'productPool/1.jpg', 192 ),
( 'SAKTHI LAMP WICKS 600 NOS', 'productPool/1.jpg', 174 ),
( 'SAKTHI N0 20 WHITE CANDLE', 'productPool/1.jpg', 145 ),
( 'SAKTHI SAMBRANI 100G', 'productPool/1.jpg', 104 ),
( 'SAKTHI TEA LIGHT CANDLE 10N', 'productPool/1.jpg', 103 ),
( 'SAKTHI TYPE 10 WHITE CANDLE', 'productPool/1.jpg', 87 ),
( 'SAKTHI TYPE 12 COLOUR CANDLE', 'productPool/1.jpg', 115 ),
( 'SAKTHI TYPE 13 WHITE CANDLE', 'productPool/1.jpg', 238 ),
( 'SAKTHI TYPE 4 COLOUR CANDLE', 'productPool/1.jpg', 133 ),
( 'SAKTHI TYPE 4 WHITE CANDLE', 'productPool/1.jpg', 193 ),
( 'SAKTHI TYPE13 COLOUR CANDLE', 'productPool/1.jpg', 208 ),
( 'SAKTHI WHITE CANDLE 100NOS', 'productPool/1.jpg', 113 ),
( 'SAKTHI WHITE CANDLE TYPE -04 500G', 'productPool/1.jpg', 141 ),
( 'SAKTHI WHITE CANDLE TYPE -12 500G', 'productPool/1.jpg', 66 ),
( 'SAKTHI WHITE CANDLE TYPE -13 500G', 'productPool/1.jpg', 275 ),
( 'SAKTHICAMPHOR 30G', 'productPool/1.jpg', 161 ),
( 'SAMABAR DAL (WEIGHED)', 'productPool/1.jpg', 213 ),
( 'SAMBA WHEAT BROKEN 50KG', 'productPool/1.jpg', 140 ),
( 'SAMBANDHI SESAME SEEDS 100G', 'productPool/1.jpg', 13 ),
( 'SAMBAR DAL 500G', 'productPool/1.jpg', 269 ),
( 'SAMESKY BLUES CHOCO 2K', 'productPool/1.jpg', 95 ),
( 'SAMESKY BLUES ORANGE 2K', 'productPool/1.jpg', 86 ),
( 'SAMESKY SKYLUSH BLUEBERRY JAR 1KG', 'productPool/1.jpg', 246 ),
( 'SAMESKY SKYLUSH LYCHEE JAR 1KG', 'productPool/1.jpg', 51 ),
( 'SAMESKY SKYLUSH ORANGE BIFA 1KG JAR', 'productPool/1.jpg', 105 ),
( 'SAMESKY SKYLUSH PINEAPPLE JAR 1KG', 'productPool/1.jpg', 49 ),
( 'SAMESKY SKYLUSH STRAWBERRY JAR 1KG', 'productPool/1.jpg', 200 ),
( 'SAMESKY TALENT VANILA FLA 2000G', 'productPool/1.jpg', 53 ),
( 'SAMOON BURGER', 'productPool/1.jpg', 34 ),
( 'SAMOON CHICKEN CROISSANT', 'productPool/1.jpg', 234 ),
( 'SAMOON CHUTNEY ROLL', 'productPool/1.jpg', 136 ),
( 'SAMOON MEAT DANISH', 'productPool/1.jpg', 110 ),
( 'SAMOON VEGETABLE ROLL', 'productPool/1.jpg', 115 ),
( 'SANDAL DABBI 150G', 'productPool/1.jpg', 58 ),
( 'SANDAL TALC 300G', 'productPool/1.jpg', 28 ),
( 'SANI FRESH 1.5L', 'productPool/1.jpg', 41 ),
( 'SANI FRESH BATHROOM CLEANER 450ML', 'productPool/1.jpg', 77 ),
( 'SANI FRESH TOILET CLEAN 1000ML', 'productPool/1.jpg', 255 ),
( 'SANI FRESH ULTRA 750ML', 'productPool/1.jpg', 39 ),
( 'SANI FRESH ULTRA SHINE 200ML', 'productPool/1.jpg', 263 ),
( 'SANI FRESH ULTRA SHINE 500ML', 'productPool/1.jpg', 156 ),
( 'SANI FRESH ULTYRA SHINE ODONIAL FREE 500ML', 'productPool/1.jpg', 37 ),
( 'SANIFRESH BATHROOM CLEANER 450ML', 'productPool/1.jpg', 214 ),
( 'SANIFRESH GERM GUARD 500ML', 'productPool/1.jpg', 82 ),
( 'SANIFRESH TOILET CLEANER 500+500 COMBO', 'productPool/1.jpg', 121 ),
( 'SANIFRESH TOILET CLEANER 750ML', 'productPool/1.jpg', 173 ),
( 'SANIMAS RAMACHAM RS12', 'productPool/1.jpg', 265 ),
( 'SANIT ALL TOILET CLEANER 500ML COMBO', 'productPool/1.jpg', 223 ),
( 'SANJEEVANI MADOM DAHASAMANI KIZHI 15G', 'productPool/1.jpg', 105 ),
( 'SANTHIGIRI KARKADAKA KANJI 500G', 'productPool/1.jpg', 10 ),
( 'SANTHOOR SANDAL SET 400G', 'productPool/1.jpg', 4 ),
( 'SANTHOOR SOAP ORANGE 100G', 'productPool/1.jpg', 187 ),
( 'SANTHOOR SOAP ORIGINAL 4 IN 1 500G', 'productPool/1.jpg', 89 ),
( 'SANTHOOR SOAP PURE 100G', 'productPool/1.jpg', 208 ),
( 'SANTHOOR SOAP WHITE 100G', 'productPool/1.jpg', 50 ),
( 'SANTHOOR WHITE SOAP 500G', 'productPool/1.jpg', 212 ),
( 'SANTHOSH BRAHMI 300 GM', 'productPool/1.jpg', 189 ),
( 'SANTHOSH BRAHMI 400G', 'productPool/1.jpg', 211 ),
( 'SANTOOR 150G *2PC SET', 'productPool/1.jpg', 225 ),
( 'SANTOOR BEAUTY TALC 2*100G', 'productPool/1.jpg', 17 ),
( 'SANTOOR BEAUTY TALCUM POW 150G+1', 'productPool/1.jpg', 257 ),
( 'SANTOOR BEAUTY TALCUM POW 400G', 'productPool/1.jpg', 194 ),
( 'SANTOOR BEAUTY TALCUM POW100G', 'productPool/1.jpg', 117 ),
( 'SANTOOR CLASSIC HANDWASH 215ML BOTTLE', 'productPool/1.jpg', 265 ),
( 'SANTOOR HAND WASH 180ML', 'productPool/1.jpg', 79 ),
( 'SANTOOR HAND WASH 250G', 'productPool/1.jpg', 219 ),
( 'SANTOOR HAND WASH BUY 1GET 1', 'productPool/1.jpg', 48 ),
( 'SANTOOR HAND WASH CLASSIC SANDAL 215ML', 'productPool/1.jpg', 108 ),
( 'SANTOOR HAND WASH FRESH BUY 1 GET 1', 'productPool/1.jpg', 153 ),
( 'SANTOOR HAND WASH MILD BUY 1GET 1', 'productPool/1.jpg', 185 ),
( 'SANTOOR HAND WASH215ML', 'productPool/1.jpg', 172 ),
( 'SANTOOR HANDWASH 750+180ML', 'productPool/1.jpg', 181 ),
( 'SANTOOR HANDWASH 750+180ML FRESH', 'productPool/1.jpg', 136 ),
( 'SANTOOR HANDWASH CLASSIC 750ML', 'productPool/1.jpg', 159 ),
( 'SANTOOR HANDWASH CLASSIC REF 540ML', 'productPool/1.jpg', 131 ),
( 'SANTOOR HANDWASH FRESH 215ML BOTTLE', 'productPool/1.jpg', 12 ),
( 'SANTOOR HANDWASH FRESH B2G1 540ML POUCH', 'productPool/1.jpg', 210 ),
( 'SANTOOR HANDWASH MILD 215ML BOTTLE', 'productPool/1.jpg', 225 ),
( 'SANTOOR HANDWASH MILD B2G1 540ML POUCH', 'productPool/1.jpg', 209 ),
( 'SANTOOR MYSTIQUE TALC 400G', 'productPool/1.jpg', 205 ),
( 'SANTOOR SANDAL SOAP 4 IN 1 PACK 55G', 'productPool/1.jpg', 75 ),
( 'SANTOOR SANDAL TURMERIC 750G', 'productPool/1.jpg', 119 ),
( 'SANTOOR SET SOAP 4*48G MRP 40', 'productPool/1.jpg', 272 ),
( 'SANTOOR SOAP 150G*4', 'productPool/1.jpg', 88 ),
( 'SANTOOR SOAP ORANGE SET', 'productPool/1.jpg', 147 ),
( 'SANTOOR WHITE SET SOAP 400G', 'productPool/1.jpg', 44 ),
( 'SANTOR ORANGE SINGLE SOAP 150G', 'productPool/1.jpg', 138 ),
( 'SANYO FISH MEDICINE 20ML', 'productPool/1.jpg', 179 ),
( 'SAPANA 3*6 FOLD HAJI MAT', 'productPool/1.jpg', 72 ),
( 'SAPANA 3*6 FOLD MAT', 'productPool/1.jpg', 208 ),
( 'SAPANA MAT 4*6 FOLD', 'productPool/1.jpg', 1 ),
( 'SAPPHIRE BUTTER COOKIES 150G', 'productPool/1.jpg', 120 ),
( 'SAPPHIRE BUTTER COOKIES GOLD 400G', 'productPool/1.jpg', 80 ),
( 'SAPPHIRE BUTTER COOKIES SILVER COLLECTION 400G', 'productPool/1.jpg', 22 ),
( 'SARAS CHICKEN MASALA 100G', 'productPool/1.jpg', 157 ),
( 'SARAS CHILLY POWDER 100G', 'productPool/1.jpg', 229 ),
( 'SARAS CHILLY POWDER 250G', 'productPool/1.jpg', 41 ),
( 'SARAS CORIANDER POWDER 100G', 'productPool/1.jpg', 273 ),
( 'SARAS CORIANDER POWDER 250G', 'productPool/1.jpg', 279 ),
( 'SARAS FISH MASALA 100G', 'productPool/1.jpg', 36 ),
( 'SARAS KASHMIRI CHILLY POWDER 100G', 'productPool/1.jpg', 224 ),
( 'SARAS KASHMIRI CHILLY POWDER 250G', 'productPool/1.jpg', 201 ),
( 'SARAS MEAT MASALA 100G', 'productPool/1.jpg', 123 );