INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'SARAS RASAM POWDER 100G', 'productPool/1.jpg', 29 ),
( 'SARAS RED CHILLY POWDER 250G', 'productPool/1.jpg', 43 ),
( 'SARAS SAMBAR POWDER 100G', 'productPool/1.jpg', 21 ),
( 'SARAS TURMERIC POWDER 100G', 'productPool/1.jpg', 274 ),
( 'SARAVANAS APPALAM 180G', 'productPool/1.jpg', 222 ),
( 'SARAVANAS CURD CHILLI', 'productPool/1.jpg', 47 ),
( 'SARAVANAS GURUVAYOOR PAPPADAM 120G', 'productPool/1.jpg', 202 ),
( 'SARAVANAS MARAYOOR JAGGERY 1KG', 'productPool/1.jpg', 45 ),
( 'SARAVANAS MASALA PAPPADAM 100G', 'productPool/1.jpg', 269 ),
( 'SARAVANAS NADAN PAPPAD 70G', 'productPool/1.jpg', 211 ),
( 'SARAVANAS PAPPADAM 100G', 'productPool/1.jpg', 49 ),
( 'SARAVANAS PAPPADM 60G', 'productPool/1.jpg', 98 ),
( 'SARAVANAS PAYASAM MIX 250G', 'productPool/1.jpg', 234 ),
( 'SARAVANAS PAYASAM RICE 500G', 'productPool/1.jpg', 169 ),
( 'SARAVANAS RICE MURUKKU 200G', 'productPool/1.jpg', 18 ),
( 'SARAVANAS SPECIAL PAPPADAM 120G', 'productPool/1.jpg', 153 ),
( 'SAREE FALL', 'productPool/1.jpg', 191 ),
( 'SARKARA BLACK 1KG', 'productPool/1.jpg', 1 ),
( 'SARKARA RED 1KG', 'productPool/1.jpg', 65 ),
( 'SARVODAYA DATES LEHYAM EATHAPAZHAM 450G', 'productPool/1.jpg', 229 ),
( 'SAS LEAF BIG', 'productPool/1.jpg', 31 ),
( 'SATHURAGIRI BUTER MURUKKU 250G', 'productPool/1.jpg', 161 ),
( 'SATHURAGIRI BUTTER MURUKKU 150G', 'productPool/1.jpg', 203 ),
( 'SATHURAGIRI COCONUT MILK MURUKKU 70G', 'productPool/1.jpg', 76 ),
( 'SATHURAGIRI MURUKKU 140G', 'productPool/1.jpg', 5 ),
( 'SAVLON 1 LTR', 'productPool/1.jpg', 137 ),
( 'SAVLON 100ML', 'productPool/1.jpg', 49 ),
( 'SAVLON 50ML', 'productPool/1.jpg', 4 ),
( 'SAVLON ANTISEPTIC LIQUID 500ML', 'productPool/1.jpg', 25 ),
( 'SAVLON DEEP CLEAN HAND WASH PUMP 200ML', 'productPool/1.jpg', 128 ),
( 'SAVLON DEEP CLEAN HANDWASH 220ML+185', 'productPool/1.jpg', 185 ),
( 'SAVLON DEEPCLEAN HANDWASH 185ML BUY 2 GET 1', 'productPool/1.jpg', 247 ),
( 'SAVLON DOUBLE STRENGTH 185ML', 'productPool/1.jpg', 240 ),
( 'SAVLON DOUBLE STRENGTH HANDWASH 750ML', 'productPool/1.jpg', 64 ),
( 'SAVLON HAND SANITIZER GEL 55ML', 'productPool/1.jpg', 108 ),
( 'SAVLON HAND WASH MOISTURE SHIELD 175ML', 'productPool/1.jpg', 186 ),
( 'SAVLON HERBAL HW 220+185 ML', 'productPool/1.jpg', 240 ),
( 'SAVLON HERBAL REFIL 185 ML', 'productPool/1.jpg', 206 ),
( 'SAVLON HERBAL SENSITIVE 185ML 2+1', 'productPool/1.jpg', 237 ),
( 'SAVLON HERBAL SENSITIVE HAND WASH 175ML', 'productPool/1.jpg', 61 ),
( 'SAVLON HERBAL SENSITIVE HANDWASH POUCH 750ML', 'productPool/1.jpg', 121 ),
( 'SAVLON MOISTURE SHIELD', 'productPool/1.jpg', 87 ),
( 'SAVLON MOISTURE SHIELD 185 ML POUCH FREE', 'productPool/1.jpg', 265 ),
( 'SAVLON MOISTURE SHIELD 185ML', 'productPool/1.jpg', 1 ),
( 'SAVLON MOISTURE SHIELD 185ML BUY 2 GET 1 FREE', 'productPool/1.jpg', 175 ),
( 'SAVLON MOISTURE SHIELD 80ML', 'productPool/1.jpg', 173 ),
( 'SAVLON MOISTURE SHIELD HANDWASH 500ML PUMP', 'productPool/1.jpg', 256 ),
( 'SAVLON MOISTURE SHIELD HANDWASH 750ML', 'productPool/1.jpg', 11 ),
( 'SAVLON MOISTURE SHIELD HANDWASH 900ML', 'productPool/1.jpg', 94 ),
( 'SAVLON PEN SANITIZER SPRAY 9ML', 'productPool/1.jpg', 21 ),
( 'SAVLON200ML', 'productPool/1.jpg', 227 ),
( 'SAVORIT NOODLES 400G', 'productPool/1.jpg', 144 ),
( 'SAVORIT VEG HAKKA NOODLES 400G', 'productPool/1.jpg', 235 ),
( 'SAVORIT VEG HAKKA NOODLES 800G', 'productPool/1.jpg', 126 ),
( 'SB CHAKRA STEEL SCRUB', 'productPool/1.jpg', 111 ),
( 'SCALE', 'productPool/1.jpg', 264 ),
( 'SCALE RS 13.50', 'productPool/1.jpg', 6 ),
( 'SCALE RS9', 'productPool/1.jpg', 8 ),
( 'SCARE-AWAY BODY SPRAY 50ML', 'productPool/1.jpg', 78 ),
( 'SCARLET LINE COMB', 'productPool/1.jpg', 208 ),
( 'SCHOGETTEN CAPPUCCINO CHOCOLATE 100G', 'productPool/1.jpg', 146 ),
( 'SCHOGETTEN DARK CHOCOLATE 100GM', 'productPool/1.jpg', 122 ),
( 'SCHOGETTEN HAZELNUTS CHOCOLATE 100GM', 'productPool/1.jpg', 162 ),
( 'SCHOGETTEN MILK CHOCOLATE 100G', 'productPool/1.jpg', 240 ),
( 'SCHOGETTEN PRALINE NOISETTES CHOCOLATE 100G', 'productPool/1.jpg', 232 ),
( 'SCHOGETTEN STRACIATELLA 100G', 'productPool/1.jpg', 34 ),
( 'SCHOGETTEN STRAWBERY CHOCOLATE 100GM', 'productPool/1.jpg', 24 ),
( 'SCHOOL MATE JUMBO KIDZ COLOUR PENS', 'productPool/1.jpg', 148 ),
( 'SCHOOL MATE NEO BALL PEN', 'productPool/1.jpg', 213 ),
( 'SCHOOL MATE TOPPER GEL PEN', 'productPool/1.jpg', 30 ),
( 'SCISSORS (S)', 'productPool/1.jpg', 166 ),
( 'SCISSORS IMP', 'productPool/1.jpg', 223 ),
( 'SCISSORS IMP R33', 'productPool/1.jpg', 274 ),
( 'SCISSORS IMP RS 22.50', 'productPool/1.jpg', 95 ),
( 'SCISSORS IMP RS 39', 'productPool/1.jpg', 49 ),
( 'SCISSORS IMP RS10', 'productPool/1.jpg', 137 ),
( 'SCISSORS IMP RS105', 'productPool/1.jpg', 148 ),
( 'SCISSORS IMP RS14', 'productPool/1.jpg', 275 ),
( 'SCISSORS IMP RS15', 'productPool/1.jpg', 33 ),
( 'SCISSORS IMP RS16.50', 'productPool/1.jpg', 279 ),
( 'SCISSORS IMP RS21', 'productPool/1.jpg', 10 ),
( 'SCISSORS IMP RS32', 'productPool/1.jpg', 184 ),
( 'SCISSORS IMP RS45', 'productPool/1.jpg', 132 ),
( 'SCISSORS IMP RS60', 'productPool/1.jpg', 154 ),
( 'SCISSORS RS 14', 'productPool/1.jpg', 178 ),
( 'SCISSORS RS 18', 'productPool/1.jpg', 65 ),
( 'SCISSORS RS 28.50', 'productPool/1.jpg', 219 ),
( 'SCISSORS RS 33', 'productPool/1.jpg', 136 ),
( 'SCISSORS RS 50', 'productPool/1.jpg', 95 ),
( 'SCISSORS RS 60', 'productPool/1.jpg', 151 ),
( 'SCISSORS RS17', 'productPool/1.jpg', 123 ),
( 'SCISSORS RS19.50', 'productPool/1.jpg', 133 ),
( 'SCISSORS RS20', 'productPool/1.jpg', 62 ),
( 'SCISSORS RS25', 'productPool/1.jpg', 202 ),
( 'SCISSORS RS27', 'productPool/1.jpg', 201 ),
( 'SCISSORS RS30', 'productPool/1.jpg', 178 ),
( 'SCISSORS RS36', 'productPool/1.jpg', 233 ),
( 'SCISSORS RS46', 'productPool/1.jpg', 160 ),
( 'SCISSORS RS55', 'productPool/1.jpg', 25 ),
( 'SCISSORS RS65', 'productPool/1.jpg', 17 ),
( 'SCISSORS RS68', 'productPool/1.jpg', 230 ),
( 'SCISSORS RS70', 'productPool/1.jpg', 136 ),
( 'SCISSORS RS78', 'productPool/1.jpg', 116 ),
( 'SCISSORS RS88', 'productPool/1.jpg', 241 ),
( 'SCOCH BRITE THICK PAD', 'productPool/1.jpg', 259 ),
( 'SCOTCH BRITE ANTIBACTERIAL PAD 1N', 'productPool/1.jpg', 232 ),
( 'SCOTCH BRITE ANTIBACTERIAL SCRUB 3N', 'productPool/1.jpg', 231 ),
( 'SCOTCH BRITE ANTIBACTERIAL SCRUB PAD 1N', 'productPool/1.jpg', 152 ),
( 'SCOTCH BRITE ANTIBACTERIAL SCRUB PAD1N', 'productPool/1.jpg', 52 ),
( 'SCOTCH BRITE BATH SQUEEGEE 30CM', 'productPool/1.jpg', 238 ),
( 'SCOTCH BRITE BOTTLE CLEANER', 'productPool/1.jpg', 52 ),
( 'SCOTCH BRITE BROOM 3M', 'productPool/1.jpg', 178 ),
( 'SCOTCH BRITE CHAKRA COTTON MOP', 'productPool/1.jpg', 148 ),
( 'SCOTCH BRITE COTTON HANDLE MOP', 'productPool/1.jpg', 160 ),
( 'SCOTCH BRITE COTTON MOP REFILL', 'productPool/1.jpg', 161 ),
( 'SCOTCH BRITE FLAT MOP REFILL 3M', 'productPool/1.jpg', 195 ),
( 'SCOTCH BRITE FLOOR CLOTH POCHHA', 'productPool/1.jpg', 35 ),
( 'SCOTCH BRITE FLOOR MOP COTTON', 'productPool/1.jpg', 256 ),
( 'SCOTCH BRITE FLOOR SQUEEGE 40CM', 'productPool/1.jpg', 263 ),
( 'SCOTCH BRITE FOOT LOCK MOP 499R', 'productPool/1.jpg', 254 ),
( 'SCOTCH BRITE FOOT LOK MOP', 'productPool/1.jpg', 91 ),
( 'SCOTCH BRITE FOOTLOCK MOP REFILL', 'productPool/1.jpg', 183 ),
( 'SCOTCH BRITE HANDY SCRUBBER', 'productPool/1.jpg', 76 ),
( 'SCOTCH BRITE HANDY SCRUBBER BRUSH', 'productPool/1.jpg', 201 ),
( 'SCOTCH BRITE HEAVY DUTY', 'productPool/1.jpg', 126 ),
( 'SCOTCH BRITE HEAVY DUTY SCURB RS45', 'productPool/1.jpg', 197 ),
( 'SCOTCH BRITE HOUSE HOLD GLOVES LARGE', 'productPool/1.jpg', 84 ),
( 'SCOTCH BRITE HOUSE HOLD GLOVES MEDIUM', 'productPool/1.jpg', 237 ),
( 'SCOTCH BRITE HOUSE HOLD SCURBBER 350', 'productPool/1.jpg', 224 ),
( 'SCOTCH BRITE JET SCRUBBER', 'productPool/1.jpg', 14 ),
( 'SCOTCH BRITE JET SCRUBBER BRUSH', 'productPool/1.jpg', 210 ),
( 'SCOTCH BRITE KICHEN GLOVES 85', 'productPool/1.jpg', 174 ),
( 'SCOTCH BRITE KITCHEN GLOVES SMALL', 'productPool/1.jpg', 171 ),
( 'SCOTCH BRITE KITCHEN SCRUB CLOTH', 'productPool/1.jpg', 104 ),
( 'SCOTCH BRITE KITCHEN WIPES 29*31 MRP179', 'productPool/1.jpg', 100 ),
( 'SCOTCH BRITE LINT ROLLER 1N', 'productPool/1.jpg', 100 ),
( 'SCOTCH BRITE MICROFIBER BATHROOM WIPE', 'productPool/1.jpg', 122 ),
( 'SCOTCH BRITE MICROFIBER MULTIPURPOSE WIPE', 'productPool/1.jpg', 151 ),
( 'SCOTCH BRITE MICROFIBER STRIP MOP', 'productPool/1.jpg', 28 ),
( 'SCOTCH BRITE NETSPONGE', 'productPool/1.jpg', 7 ),
( 'SCOTCH BRITE NON SCRATCH SCRUB SPONGE', 'productPool/1.jpg', 61 ),
( 'SCOTCH BRITE PLATINUM PAD 1N', 'productPool/1.jpg', 219 ),
( 'SCOTCH BRITE PLATINUM PAD 3M', 'productPool/1.jpg', 106 ),
( 'SCOTCH BRITE PLATINUM PAD 3N', 'productPool/1.jpg', 200 ),
( 'SCOTCH BRITE PREMIUM TOILET BRUSH', 'productPool/1.jpg', 138 ),
( 'SCOTCH BRITE PREMIUM TOILET BRUSH 350R', 'productPool/1.jpg', 59 ),
( 'SCOTCH BRITE SCRUB 3M', 'productPool/1.jpg', 243 ),
( 'SCOTCH BRITE SCRUB PAD', 'productPool/1.jpg', 210 ),
( 'SCOTCH BRITE SCRUB PAD 30R', 'productPool/1.jpg', 43 ),
( 'SCOTCH BRITE SCRUB PAD 7.5', 'productPool/1.jpg', 188 ),
( 'SCOTCH BRITE SCRUB PAD MRP10', 'productPool/1.jpg', 209 ),
( 'SCOTCH BRITE SCRUBBY KITCHEN WIPES 1N', 'productPool/1.jpg', 80 ),
( 'SCOTCH BRITE SCRUP SPONG', 'productPool/1.jpg', 93 ),
( 'SCOTCH BRITE SCRUP SPONGE', 'productPool/1.jpg', 24 ),
( 'SCOTCH BRITE SCURB PAD 10R', 'productPool/1.jpg', 135 ),
( 'SCOTCH BRITE SGUEE 3M', 'productPool/1.jpg', 174 ),
( 'SCOTCH BRITE SINK BRUSH', 'productPool/1.jpg', 99 ),
( 'SCOTCH BRITE SOAP DISPENSING DISHWAND', 'productPool/1.jpg', 197 ),
( 'SCOTCH BRITE SPONG WIPE 140', 'productPool/1.jpg', 103 ),
( 'SCOTCH BRITE SPONG WIPE 75RS', 'productPool/1.jpg', 187 ),
( 'SCOTCH BRITE SPONGE WIPE', 'productPool/1.jpg', 9 ),
( 'SCOTCH BRITE SPONGE WIPE LARGER', 'productPool/1.jpg', 138 ),
( 'SCOTCH BRITE SPONGE WIPES', 'productPool/1.jpg', 176 ),
( 'SCOTCH BRITE SPONGE WIPES PRINTED 3M', 'productPool/1.jpg', 169 ),
( 'SCOTCH BRITE STEEL SCRUB', 'productPool/1.jpg', 8 ),
( 'SCOTCH BRITE STEEL SCRUB PAD', 'productPool/1.jpg', 209 ),
( 'SCOTCH BRITE STRIP HANDLED MOP', 'productPool/1.jpg', 50 ),
( 'SCOTCH BRITE THICK PAD', 'productPool/1.jpg', 114 ),
( 'SCOTCH BRITE TOILET BRUSH ROUND', 'productPool/1.jpg', 172 ),
( 'SCOTCH BRITE TOILET BRUSH SET', 'productPool/1.jpg', 185 ),
( 'SCOTCH BRITE TWISTER MOP FREE REFILL', 'productPool/1.jpg', 215 ),
( 'SCOTCH BRITESINGLE HOCKEY TOILET BRUSH', 'productPool/1.jpg', 182 ),
( 'SCOTCH MAP COTTON MAP 325R', 'productPool/1.jpg', 22 ),
( 'SCOTCHBRITE TOILET DOUBLE HOCKY BRUSH', 'productPool/1.jpg', 175 ),
( 'SCRAPER EK', 'productPool/1.jpg', 247 ),
( 'SCRUBBER', 'productPool/1.jpg', 16 ),
( 'SCRUBBER 674', 'productPool/1.jpg', 52 ),
( 'SEA SPARKLE BREADED FISH NAGGETS', 'productPool/1.jpg', 123 ),
( 'SEA SPARKLE SARDINES', 'productPool/1.jpg', 130 ),
( 'SEAL O FRESH JAR 1500ML', 'productPool/1.jpg', 147 ),
( 'SEAL O FRESH JAR 2000 ML', 'productPool/1.jpg', 251 ),
( 'SEAL O FRESH JAR 200ML 3 PCS', 'productPool/1.jpg', 56 ),
( 'SEAL O FRESH JAR 500 ML', 'productPool/1.jpg', 143 ),
( 'SEBA MED ANTI-DANDRUFF SHAMPOO200ML', 'productPool/1.jpg', 210 ),
( 'SEBA MED BABY BODY-MILK 400ML', 'productPool/1.jpg', 107 ),
( 'SEBA MED CLEANSING BAR 100G', 'productPool/1.jpg', 50 ),
( 'SEBA MED EVERYDAY SHAMPOO200ML', 'productPool/1.jpg', 27 ),
( 'SEBA MED FACE BODY WASH 200ML', 'productPool/1.jpg', 247 ),
( 'SEBA MED MOISTURIZING CREAM 50ML', 'productPool/1.jpg', 110 ),
( 'SEBA MED REVITALIZING SHAMPOO 200ML', 'productPool/1.jpg', 82 ),
( 'SEBAMED BABY BODY MILK LOTION 100ML', 'productPool/1.jpg', 178 ),
( 'SEBAMED BABY BUBBLE BATH 200ML', 'productPool/1.jpg', 275 ),
( 'SEBAMED BABY CLEANSING BAR 100G', 'productPool/1.jpg', 67 ),
( 'SEBAMED BABY CLEANSING BAR 150G', 'productPool/1.jpg', 69 ),
( 'SEBAMED BABY CREAM 200ML', 'productPool/1.jpg', 168 ),
( 'SEBAMED BABY LIP BALM 4.8G', 'productPool/1.jpg', 250 ),
( 'SEBAMED BABY LOTION 100ML', 'productPool/1.jpg', 250 ),
( 'SEBAMED BABY LOTION 400ML PUMP', 'productPool/1.jpg', 250 ),
( 'SEBAMED BABY LOTION 50ML', 'productPool/1.jpg', 41 ),
( 'SEBAMED BABY POWDER 200G', 'productPool/1.jpg', 264 ),
( 'SEBAMED BABY POWDER 400G', 'productPool/1.jpg', 265 ),
( 'SEBAMED BABY SHAMPOO 500ML', 'productPool/1.jpg', 103 ),
( 'SEBAMED BABY WASH 200ML', 'productPool/1.jpg', 174 ),
( 'SEBAMED BABY WASH 400ML PUMP', 'productPool/1.jpg', 108 ),
( 'SEBAMED CHILDRENS SHAMPOO 150ML', 'productPool/1.jpg', 204 ),
( 'SEBAMED CLEANSING WIPES 72P', 'productPool/1.jpg', 243 ),
( 'SEBAMED LEAR FACE CLEANSING BAR 100G', 'productPool/1.jpg', 173 ),
( 'SEBAMED PROTECTIVE FACIAL CREAM 50ML', 'productPool/1.jpg', 207 ),
( 'SEBAMED RASH CREAM 100ML', 'productPool/1.jpg', 141 ),
( 'SEBAMED SOOTHING MASSAGE OIL 150ML', 'productPool/1.jpg', 136 ),
( 'SEBOLIN CREAM 15G', 'productPool/1.jpg', 253 ),
( 'SEBOLIN CREAM 40G', 'productPool/1.jpg', 276 ),
( 'SEBOLIN CREAM 50GM', 'productPool/1.jpg', 188 ),
( 'SEEDLESS DATES 350G', 'productPool/1.jpg', 71 ),
( 'SENSODYNE DAILY CARE BRUSH', 'productPool/1.jpg', 4 ),
( 'SENSODYNE DEEP CLEAN 40G', 'productPool/1.jpg', 82 ),
( 'SENSODYNE DEEP CLEAN TOOTHPASTE 70G', 'productPool/1.jpg', 128 ),
( 'SENSODYNE EXPERT BRUSH', 'productPool/1.jpg', 144 ),
( 'SENSODYNE FRESH GEL 130G', 'productPool/1.jpg', 235 ),
( 'SENSODYNE FRESH GEL B 2 G 1 450G', 'productPool/1.jpg', 278 ),
( 'SENSODYNE FRESH MINT 130G', 'productPool/1.jpg', 33 ),
( 'SENSODYNE FRESH MINT PASTE 40G', 'productPool/1.jpg', 207 ),
( 'SENSODYNE FRESH MINT PASTE 75GM', 'productPool/1.jpg', 29 ),
( 'SENSODYNE FRESH MINT TOOTH PASTE 4*75G', 'productPool/1.jpg', 186 ),
( 'SENSODYNE FRESHGEL PASTE 40G', 'productPool/1.jpg', 109 ),
( 'SENSODYNE FRESHGEL TOOTH PASTE 80GM', 'productPool/1.jpg', 40 ),
( 'SENSODYNE FRESHMINT RAPID RELIF PASTE 80GM', 'productPool/1.jpg', 27 ),
( 'SENSODYNE FRESHMINT TOOTH PASTE 150G B2G1', 'productPool/1.jpg', 24 ),
( 'SENSODYNE HERBAL MULTI CARE 70G', 'productPool/1.jpg', 25 ),
( 'SENSODYNE RAPID RELIEF 40GM', 'productPool/1.jpg', 75 ),
( 'SENSODYNE REPAIR & PROTECT PASTE 70G', 'productPool/1.jpg', 78 ),
( 'SENSODYNE REPAIR PROTECT 100G', 'productPool/1.jpg', 214 ),
( 'SENSODYNE SENSITIVE SOFT BRUSH B2G1', 'productPool/1.jpg', 107 ),
( 'SENSODYNE SENSITIVE SOFT BRUSH MRP 50', 'productPool/1.jpg', 163 ),
( 'SENSODYNE SENSITIVE TOOTH BRUSH SOFT', 'productPool/1.jpg', 90 ),
( 'SENSODYNE WHITENING70G', 'productPool/1.jpg', 87 ),
( 'SESAME WHITE NATURAL 75G', 'productPool/1.jpg', 220 ),
( 'SET WET CHARM AVATAR SPRAY 150ML', 'productPool/1.jpg', 99 ),
( 'SET WET COOL 10ML', 'productPool/1.jpg', 224 ),
( 'SET WET COOL AVATAR SPRAY 150ML', 'productPool/1.jpg', 81 ),
( 'SET WET COOLAVATAR SPRAY 75ML', 'productPool/1.jpg', 142 ),
( 'SET WET DEO FUNKY AUATA 120ML', 'productPool/1.jpg', 133 ),
( 'SET WET GEL VERTICAL 100ML', 'productPool/1.jpg', 63 ),
( 'SET WET MISCHIEF AVATAR DEO 150ML', 'productPool/1.jpg', 274 ),
( 'SET WET SPUNKY AVATAR 98G', 'productPool/1.jpg', 98 ),
( 'SET WET SWAG AVATAR PERFUME 75ML', 'productPool/1.jpg', 66 ),
( 'SET WET SWAG AVATAR SPRAY 150ML', 'productPool/1.jpg', 263 ),
( 'SET WET ULTIMATE HOLD GEL 50ML', 'productPool/1.jpg', 262 ),
( 'SET WET ULTMATE HOLD STYLING GEL 100G', 'productPool/1.jpg', 251 ),
( 'SET WET WET LOOK GEL50ML', 'productPool/1.jpg', 36 ),
( 'SET WET WETLOOK 100ML', 'productPool/1.jpg', 99 ),
( 'SETWET COOL GEL 50ML', 'productPool/1.jpg', 163 ),
( 'SETWET GEL 10ML', 'productPool/1.jpg', 236 ),
( 'SETWET HAIR GEL COOL 100ML', 'productPool/1.jpg', 51 ),
( 'SETWET VERTICAL 50ML', 'productPool/1.jpg', 226 ),
( 'SETWET VERTICAL HAIR GEL 10ML', 'productPool/1.jpg', 228 ),
( 'SEVEN HORSE FACIAL TISSUE 80SHEET B2G1', 'productPool/1.jpg', 181 ),
( 'SEVEN HORSE FACIAL TISSUE SHIFT02 B2G1', 'productPool/1.jpg', 51 ),
( 'SEVEN HORSE FACIAL TISSUE SHIFT03 100S 3+1', 'productPool/1.jpg', 114 ),
( 'SEVEN HORSE FACIAL TISSUE SHINP01 200S B1G1', 'productPool/1.jpg', 84 ),
( 'SEVEN STAR WASHING BRUSH', 'productPool/1.jpg', 204 ),
( 'SEVEN-X BLEACHING POWDER 1KG', 'productPool/1.jpg', 250 ),
( 'SEVEN-X BLEACHING POWDER 250G', 'productPool/1.jpg', 31 ),
( 'SEVEN-X BLEACHING POWDER 500G', 'productPool/1.jpg', 191 ),
( 'SEWING MACHINE BELT', 'productPool/1.jpg', 20 ),
( 'SEWING MACHINE BELT 375MM', 'productPool/1.jpg', 104 ),
( 'SEWING MACHINE OIL', 'productPool/1.jpg', 26 ),
( 'SEWING NEEDLE', 'productPool/1.jpg', 49 ),
( 'SGR BOTTLE BRUSH', 'productPool/1.jpg', 256 ),
( 'SGR COLANDER STRAINER M-572', 'productPool/1.jpg', 129 ),
( 'SGR COLOR SPOON 12P', 'productPool/1.jpg', 136 ),
( 'SGR GLOVES', 'productPool/1.jpg', 20 ),
( 'SGR PLASTIC FALOODA SPOON (6PCS)', 'productPool/1.jpg', 165 ),
( 'SGR PLASTIC FORK SPOON', 'productPool/1.jpg', 44 ),
( 'SGR PLATE STAND SAG101', 'productPool/1.jpg', 175 ),
( 'SGR WALL HOOK LX10*1', 'productPool/1.jpg', 71 ),
( 'SGR WIPER', 'productPool/1.jpg', 107 ),
( 'SHAINA FOOT SCRAPER', 'productPool/1.jpg', 93 ),
( 'SHAKIRA CLOTH CLIP 12PCS', 'productPool/1.jpg', 103 ),
( 'SHALIMAR CURD CHILLI 40G', 'productPool/1.jpg', 129 ),
( 'SHALIMAR GARAM MASALA MIX 20G', 'productPool/1.jpg', 33 ),
( 'SHALIMAR PROWN DRY 25GM', 'productPool/1.jpg', 103 ),
( 'SHALIMAR VEGETABLE BAG', 'productPool/1.jpg', 226 ),
( 'SHAMAM FRUITS', 'productPool/1.jpg', 61 ),
( 'SHANTI CHOCO FLAKES 250G +50G FREE', 'productPool/1.jpg', 140 ),
( 'SHANTI CORN FLAKE 500G', 'productPool/1.jpg', 58 ),
( 'SHANTIS CHOCO FLAKES 125G', 'productPool/1.jpg', 134 ),
( 'SHANTIS CHOCO FLAKES 12G', 'productPool/1.jpg', 45 ),
( 'SHANTIS CHOCO FLAKES 27G', 'productPool/1.jpg', 211 ),
( 'SHANTIS CORN FLAKES 250G', 'productPool/1.jpg', 6 ),
( 'SHANTIS CORN FLAKES GD MNG 325G', 'productPool/1.jpg', 218 ),
( 'SHARON KUZHALAPPAM 180G', 'productPool/1.jpg', 236 ),
( 'SHARON KUZHALAPPAM 450 G', 'productPool/1.jpg', 221 ),
( 'SHARON RICE BALL 10 PCS', 'productPool/1.jpg', 184 ),
( 'SHARPNER RS 24', 'productPool/1.jpg', 252 ),
( 'SHARPNER RS 9', 'productPool/1.jpg', 273 ),
( 'SHAVING CREAM LIME 78G', 'productPool/1.jpg', 182 ),
( 'SHINGAR DEEP RED 5G', 'productPool/1.jpg', 70 ),
( 'SHINGAR GLITTER SINDOOR 10G', 'productPool/1.jpg', 32 ),
( 'SHINGAR HERBEL KAJAL', 'productPool/1.jpg', 127 ),
( 'SHINGAR KAJA BABY 2G', 'productPool/1.jpg', 161 ),
( 'SHINGAR KAJAL 2G', 'productPool/1.jpg', 61 ),
( 'SHINGAR KAJAL STICK 1.5G', 'productPool/1.jpg', 205 ),
( 'SHINGAR KAJAL STICK 3G', 'productPool/1.jpg', 71 ),
( 'SHINGAR KUMKUM70R', 'productPool/1.jpg', 88 ),
( 'SHINGAR NAIL COLOUR REMOVER 30ML', 'productPool/1.jpg', 230 ),
( 'SHINGAR NAIL REMOVER 60ML', 'productPool/1.jpg', 248 ),
( 'SHINGAR PREMIUM SINDOOR 3.5ML', 'productPool/1.jpg', 68 ),
( 'SHINGAR RED 10G', 'productPool/1.jpg', 127 ),
( 'SHINGAR SILKY EYE LINER 5ML', 'productPool/1.jpg', 37 ),
( 'SHINGAR SILKY EYEBROW PENCIL 2G', 'productPool/1.jpg', 64 ),
( 'SHIVA DHOOPAGARBATHIRS 10', 'productPool/1.jpg', 47 ),
( 'SHIVARCH COTTON BUDS JAR', 'productPool/1.jpg', 194 ),
( 'SHIVARCH COTTON BUDS PKT', 'productPool/1.jpg', 258 ),
( 'SHOE SPAA CLEANING GEL 50ML', 'productPool/1.jpg', 165 ),
( 'SHOE SPAA LEATHER KREM 150ML', 'productPool/1.jpg', 99 ),
( 'SHOE SPAA SHOE CREAM BLACK 50ML', 'productPool/1.jpg', 129 ),
( 'SHOE SPAA SHOE CREAM LIGHT BROWN 50ML', 'productPool/1.jpg', 115 ),
( 'SHOE SPAA SHOE CREAM NEUTRAL 50ML', 'productPool/1.jpg', 272 ),
( 'SHOE SPAA SMART CARE 100ML', 'productPool/1.jpg', 133 ),
( 'SHOE SPAA SPEEDY SHINE BLACK', 'productPool/1.jpg', 242 ),
( 'SHOE SPAA SPEEDY SHINE NEUTRAL', 'productPool/1.jpg', 160 ),
( 'SHOE SPAA SUEDE VELOURS CAMEL 150ML', 'productPool/1.jpg', 275 ),
( 'SHOE SPAA SUEDE VELOURS OLIVE 150ML', 'productPool/1.jpg', 64 ),
( 'SHOE SPAA SUPER SHINE BLACK 75ML', 'productPool/1.jpg', 245 ),
( 'SHOE SPAA SUPER SHINE NEUTRAL 75ML', 'productPool/1.jpg', 29 ),
( 'SHORT COAT DOG SHAMPOO 250ML', 'productPool/1.jpg', 15 ),
( 'SHOWER GEL ADIDAS', 'productPool/1.jpg', 126 ),
( 'SHOWER GEL AXE IMP', 'productPool/1.jpg', 2 ),
( 'SHOWER TO SHOWER COLOGNE COOL 150G', 'productPool/1.jpg', 181 ),
( 'SHOWER TO SHOWER COLOGNE COOL POWDER 75G', 'productPool/1.jpg', 181 ),
( 'SHOWER TO SHOWER COLOGNE COOL TALC 150G', 'productPool/1.jpg', 39 ),
( 'SHOWER TO SHOWER COOL MINT 150G', 'productPool/1.jpg', 197 ),
( 'SHOWER TO SHOWER SANDAL TALC 150G', 'productPool/1.jpg', 195 ),
( 'SHOWER TO SHOWER SUPER COOL 150G', 'productPool/1.jpg', 220 ),
( 'SHREE GANESH SAFFRON 12G', 'productPool/1.jpg', 111 ),
( 'SIGMA BOTTLE OPENER', 'productPool/1.jpg', 95 ),
( 'SIGMA HAND BLENDER', 'productPool/1.jpg', 260 ),
( 'SIGMA WONDER MAKER(6 IN 1)', 'productPool/1.jpg', 244 ),
( 'SIL BAKED BEANS IN TOMATO SAUCE 450G', 'productPool/1.jpg', 164 ),
( 'SIL BUTTON MUSHROOM IN BEINE 800G', 'productPool/1.jpg', 188 ),
( 'SIL GHERKINS IN BRINE 480G', 'productPool/1.jpg', 258 ),
( 'SIL GREEN CHILLI SAUCE 200G', 'productPool/1.jpg', 47 ),
( 'SIL HAT & SWEET TOMATA KETCHUP 200G', 'productPool/1.jpg', 274 ),
( 'SIL JALAPENO SLICES 480G', 'productPool/1.jpg', 52 ),
( 'SIL MAYONNAISE CHEESY JALAPENO TWIST 200G', 'productPool/1.jpg', 135 ),
( 'SIL MAYONNAISE GARLIC SPICE MIX 200G', 'productPool/1.jpg', 61 ),
( 'SIL MAYONNAISE MEXICAN SPICE TWIST 200G', 'productPool/1.jpg', 106 ),
( 'SIL MAYONNAISE NON VEG 200G', 'productPool/1.jpg', 137 ),
( 'SIL MAYONNAISE TIKKA SPICE MIX 200G', 'productPool/1.jpg', 109 ),
( 'SIL MAYONNAISE VEG 200G', 'productPool/1.jpg', 106 ),
( 'SIL MIXED FRUIT JAM 100G', 'productPool/1.jpg', 38 ),
( 'SIL MIXED FRUIT JAM 200G', 'productPool/1.jpg', 165 ),
( 'SIL MIXED FRUIT JAM 500G', 'productPool/1.jpg', 157 ),
( 'SIL ORANGE MARMALADE 500G', 'productPool/1.jpg', 123 ),
( 'SIL PASTA SAUCE 200G', 'productPool/1.jpg', 251 ),
( 'SIL PINE APPLE JAM 500G', 'productPool/1.jpg', 254 ),
( 'SIL REAL TASTY KETCHUP 15G', 'productPool/1.jpg', 15 ),
( 'SIL REAL TASTY TOMTO KETCHUP 200G', 'productPool/1.jpg', 104 ),
( 'SIL RED CHILLI SAUCE 200G', 'productPool/1.jpg', 98 ),
( 'SIL RED CHILLI SAUCE 90G', 'productPool/1.jpg', 254 ),
( 'SIL SCHEZWAN SAUCE 200G', 'productPool/1.jpg', 23 ),
( 'SIL SOYA SAUCE 200G', 'productPool/1.jpg', 163 ),
( 'SIL SOYA SAUCE 90G', 'productPool/1.jpg', 211 ),
( 'SIL STRAWBERRY JAM 500G', 'productPool/1.jpg', 162 ),
( 'SIL SWEET CORN CREAM SOUP 460G', 'productPool/1.jpg', 33 ),
( 'SILKY DOG SOAP', 'productPool/1.jpg', 188 ),
( 'SILVER LINE JAR 2000ML', 'productPool/1.jpg', 131 ),
( 'SILVER LINE JAR 500ML', 'productPool/1.jpg', 123 ),
( 'SILVER WRAP ALUMINIUM FOIL 9M', 'productPool/1.jpg', 8 ),
( 'SIMCO TOIN', 'productPool/1.jpg', 187 ),
( 'SIMILAC 1 400G JAR', 'productPool/1.jpg', 250 ),
( 'SIMILAC 2 400GJAR', 'productPool/1.jpg', 148 ),
( 'SIMILAC ADVANCE 1 TIN 400G', 'productPool/1.jpg', 174 ),
( 'SIMILAC ADVANCE 2 400G', 'productPool/1.jpg', 191 ),
( 'SIMILAC ADVANCE STAGE 3 400G', 'productPool/1.jpg', 14 ),
( 'SIMILAC ADVANCE1 400G', 'productPool/1.jpg', 94 ),
( 'SIMILAC ADVANCED 2 PACKET 400G', 'productPool/1.jpg', 257 ),
( 'SIMILAC IQ STAGE 1 400G', 'productPool/1.jpg', 234 ),
( 'SIMILAC IQ STAGE 2 400G', 'productPool/1.jpg', 23 ),
( 'SIMILAC ISOMIL MILK SUBSTITUTE 400G', 'productPool/1.jpg', 272 ),
( 'SIMIRA PERFUMES 15ML', 'productPool/1.jpg', 90 ),
( 'SIMLY GOOD CRACKER SUGAR FREE 200GM', 'productPool/1.jpg', 168 ),
( 'SIMPKINS FRUIT DROPS', 'productPool/1.jpg', 221 ),
( 'SIMPLY GOOD CRAKER', 'productPool/1.jpg', 41 ),
( 'SIMPLY GOOD SLIMZ 120G', 'productPool/1.jpg', 38 ),
( 'SIMPLY VENUS 3 BASIC RAZOR', 'productPool/1.jpg', 175 ),
( 'SIMPLY VENUS 3BLADES', 'productPool/1.jpg', 11 ),
( 'SIMPLY VENUS 5 PACK', 'productPool/1.jpg', 132 ),
( 'SIMPLY VENUS RS 55', 'productPool/1.jpg', 226 ),
( 'SINGAR SINDOOR STICK 1.5G', 'productPool/1.jpg', 42 ),
( 'SISO HAIR COLOR SHAMPOO 15G', 'productPool/1.jpg', 155 ),
( 'SISO HAIR COLOR SHAMPOO 4* 15G', 'productPool/1.jpg', 186 ),
( 'SISO HAIR COLOR SHAMPOO 5MINUTE 100G', 'productPool/1.jpg', 60 ),
( 'SISO HAIR COLOR SHAMPOO 5MINUTE 20G', 'productPool/1.jpg', 152 ),
( 'SISO HAIR COLOR SHAMPOO BASED 15ML', 'productPool/1.jpg', 6 ),
( 'SISO HAIR COLOR SHAMPOO MRP 330', 'productPool/1.jpg', 41 ),
( 'SISO HAIR COLOUR 15G', 'productPool/1.jpg', 113 ),
( 'SISO HAIR COLOUR CREAM 15ML', 'productPool/1.jpg', 88 ),
( 'SISO HAIR COLOUR SHAMPOO', 'productPool/1.jpg', 243 ),
( 'SISO HAIR COLOUR SHAMPOO 15G', 'productPool/1.jpg', 33 ),
( 'SISO HAIR COLOUR SHAMPOO 15ML', 'productPool/1.jpg', 65 ),
( 'SIYAD FOOD SOAN PAPADI 300G', 'productPool/1.jpg', 47 ),
( 'SIYAD FOOD SOAN ROLL SWEETS', 'productPool/1.jpg', 7 ),
( 'SK ROSE NIRLEP 5', 'productPool/1.jpg', 109 ),
( 'SK ROSE NIRLEP-1', 'productPool/1.jpg', 68 ),
( 'SK ROSE NIRLEP-2', 'productPool/1.jpg', 190 ),
( 'SK ROSE NIRLEP-3', 'productPool/1.jpg', 68 ),
( 'SK ROSE NIRLEP-4', 'productPool/1.jpg', 69 ),
( 'SKETCH PEN RS 33', 'productPool/1.jpg', 248 ),
( 'SKETCH PEN RS 72', 'productPool/1.jpg', 160 ),
( 'SKETCH PEN RS33', 'productPool/1.jpg', 102 ),
( 'SKETCH PEN RS35', 'productPool/1.jpg', 179 ),
( 'SKETCH PEN RS42', 'productPool/1.jpg', 7 ),
( 'SKETCH PEN RS45', 'productPool/1.jpg', 195 ),
( 'SKIPPING ROPE RS55', 'productPool/1.jpg', 33 ),
( 'SKIPPING ROPE RS60', 'productPool/1.jpg', 100 ),
( 'SKIPPY CREAMY BUTTER', 'productPool/1.jpg', 267 ),
( 'SKITTLES 20G', 'productPool/1.jpg', 118 ),
( 'SKORE 10S CHERRY CONDOMS', 'productPool/1.jpg', 33 ),
( 'SKORE CONDOM COOL 10S', 'productPool/1.jpg', 132 ),
( 'SKORE CONDOM SHADES 10S', 'productPool/1.jpg', 220 ),
( 'SKORE CONDOMS 10S', 'productPool/1.jpg', 95 ),
( 'SKORE CONDOMS BANANA 10S', 'productPool/1.jpg', 103 ),
( 'SKS OMYPOP POPCORN HONEY BUTTER', 'productPool/1.jpg', 56 ),
( 'SKS OMYPOP POPCORN HONEY CHEESE', 'productPool/1.jpg', 56 ),
( 'SKS OMYPOP POPCORN PINKYBERRRYCOCO', 'productPool/1.jpg', 243 ),
( 'SKS OMYPOP POPCORN SIGNATURE CARAMEL', 'productPool/1.jpg', 19 ),
( 'SKY BALEN HEAVY METAL', 'productPool/1.jpg', 256 ),
( 'SKY JCB', 'productPool/1.jpg', 93 ),
( 'SKY LEMON SQUEEZER', 'productPool/1.jpg', 16 ),
( 'SKY MASHER', 'productPool/1.jpg', 80 ),
( 'SLICE FIZZY APPLE 250ML PET', 'productPool/1.jpg', 228 ),
( 'SLICE FIZZY LEMON 250ML PET', 'productPool/1.jpg', 77 ),
( 'SLICE MANGO PET 600ML', 'productPool/1.jpg', 71 ),
( 'SLICE PU MANGO 1.2LTR', 'productPool/1.jpg', 125 ),
( 'SLIMMING GREEN TEA TEFE 50 GM', 'productPool/1.jpg', 32 ),
( 'SLIVER MASKING TAPE 2INCH', 'productPool/1.jpg', 32 ),
( 'SMALL BUTTERFLY ECLAIRS GIFT BOX 167G', 'productPool/1.jpg', 225 ),
( 'SMALL ONION', 'productPool/1.jpg', 31 ),
( 'SMALL PAYAR', 'productPool/1.jpg', 242 ),
( 'SMALL WONDER ADMIRE FEEDING BOTTLE 250ML', 'productPool/1.jpg', 264 ),
( 'SMALL WONDER CANDY FEEDING BOTTLE 125ML', 'productPool/1.jpg', 215 ),
( 'SMALL WONDER CANDY FEEDING BOTTLE 250ML', 'productPool/1.jpg', 177 ),
( 'SMALL WONDER LIQUID SILICONE NIPPLE', 'productPool/1.jpg', 48 ),
( 'SMALL WONDER PURE FEEDING BOTTLE 125ML', 'productPool/1.jpg', 59 ),
( 'SMALL WONDER PURE FEEDING BOTTLE 250ML', 'productPool/1.jpg', 119 ),
( 'SMART PET SINGLE SIDE COMB', 'productPool/1.jpg', 40 ),
( 'SMARTY PET SINGE SIDE COMB', 'productPool/1.jpg', 63 ),
( 'SNAKE GOURD', 'productPool/1.jpg', 218 ),
( 'SNAPIN CHEESY GARLIC BREAD MIX 45G', 'productPool/1.jpg', 271 ),
( 'SNAPIN HOT N SWEET 45G', 'productPool/1.jpg', 5 ),
( 'SNAPIN MINT 7G', 'productPool/1.jpg', 142 ),
( 'SNICKERS 15G', 'productPool/1.jpg', 63 ),
( 'SNICKERS 25G', 'productPool/1.jpg', 36 ),
( 'SNICKERS 50G', 'productPool/1.jpg', 146 ),
( 'SNICKERS 50GM', 'productPool/1.jpg', 15 ),
( 'SNICKERS ALMOND 22G', 'productPool/1.jpg', 218 ),
( 'SNICKERS CARAMEL INTENSE 47G', 'productPool/1.jpg', 161 ),
( 'SNICKERS CASHEW 22G', 'productPool/1.jpg', 69 ),
( 'SNICKERS MAX NUTS 50 GM', 'productPool/1.jpg', 263 ),
( 'SNICKERS MINI BAG 150G', 'productPool/1.jpg', 243 ),
( 'SNICKERS MINI BAG 150G COMBI', 'productPool/1.jpg', 66 ),
( 'SNICKERS MULTI PACK 5 IN 1', 'productPool/1.jpg', 226 ),
( 'SNOW SP IMP RS 27', 'productPool/1.jpg', 153 ),
( 'SNOW SPRAY IMP R 24', 'productPool/1.jpg', 51 ),
( 'SNOW SPRAY IMP RS 21', 'productPool/1.jpg', 1 ),
( 'SO GOOD ALMOND FRESH VANILLA 1L', 'productPool/1.jpg', 33 ),
( 'SOAP BOX 18', 'productPool/1.jpg', 69 ),
( 'SOAP BOX 24', 'productPool/1.jpg', 12 ),
( 'SOAP BOX IMP RS 15.50', 'productPool/1.jpg', 272 ),
( 'SOAP BOX IMP RS 19', 'productPool/1.jpg', 89 ),
( 'SOAP BOX RS 12.50', 'productPool/1.jpg', 88 ),
( 'SOAP BOX RS 14', 'productPool/1.jpg', 27 ),
( 'SOAP BOX RS 15.50', 'productPool/1.jpg', 149 ),
( 'SOAP BOX RS 16.50', 'productPool/1.jpg', 260 ),
( 'SOAP BOX RS 19.50', 'productPool/1.jpg', 269 ),
( 'SOAP BOX RS20', 'productPool/1.jpg', 53 ),
( 'SOAP BOX RS23', 'productPool/1.jpg', 35 ),
( 'SOAP BOX RS28', 'productPool/1.jpg', 217 ),
( 'SOAP BOX RS33', 'productPool/1.jpg', 67 ),
( 'SOAP BOX RS40', 'productPool/1.jpg', 192 ),
( 'SOAP BOX RS48', 'productPool/1.jpg', 185 ),
( 'SOAP PEARS IMP RS90', 'productPool/1.jpg', 134 ),
( 'SODA ASH WASHING 200G', 'productPool/1.jpg', 144 ),
( 'SODA PODI JAR BIG', 'productPool/1.jpg', 66 ),
( 'SODA PODI JAR SMALL', 'productPool/1.jpg', 223 ),
( 'SODIUM BENZOATE 25G', 'productPool/1.jpg', 95 ),
( 'SODIUM BENZOATE 50GM', 'productPool/1.jpg', 278 ),
( 'SOEHNLE KITCHEN SCALE AHSX', 'productPool/1.jpg', 225 ),
( 'SOFFOLA OATS MASALA & CORIANDER 40G', 'productPool/1.jpg', 14 ),
( 'SOFIT CHOCOL SOYAMILK 1LTR', 'productPool/1.jpg', 157 ),
( 'SOFIT MANGO SOYA MILK 1LITR', 'productPool/1.jpg', 58 ),
( 'SOFIT SOYA MILK 1L', 'productPool/1.jpg', 40 ),
( 'SOFIT SOYA MILK 200ML', 'productPool/1.jpg', 66 ),
( 'SOFIT SOYA MILK KESAR PISTA 1L', 'productPool/1.jpg', 238 ),
( 'SOFIT SOYA MILK MANGO FLAVOUR', 'productPool/1.jpg', 57 ),
( 'SOFT ANTI BACTRIA XL 30P', 'productPool/1.jpg', 156 ),
( 'SOFTOUCH FABRIC CONDITIONER 200ML', 'productPool/1.jpg', 36 ),
( 'SOFTOUCH FABRIC CONDITIONERBLACK 800ML', 'productPool/1.jpg', 131 ),
( 'SOFY ANTI BACTERIA DEEP 290 MM', 'productPool/1.jpg', 22 ),
( 'SOFY ANTI BACTERIA MRP 125', 'productPool/1.jpg', 259 ),
( 'SOFY COOL EXTRA LONG 290MM', 'productPool/1.jpg', 28 ),
( 'SOFY COOL XL15', 'productPool/1.jpg', 146 ),
( 'SOFY EXTRA LONG 15S', 'productPool/1.jpg', 217 ),
( 'SOFY EXTRA LONG 6S', 'productPool/1.jpg', 44 ),
( 'SOFY EXTRA LONG 7N', 'productPool/1.jpg', 111 ),
( 'SOFY EXTRE LONG 15N', 'productPool/1.jpg', 231 ),
( 'SOFY OVER NIGHT XXL 5N', 'productPool/1.jpg', 203 ),
( 'SOFY SUPER XL+ 15N', 'productPool/1.jpg', 116 ),
( 'SOFY SUPER XL+ 30N', 'productPool/1.jpg', 251 ),
( 'SOFY SUPER XL+ 7N', 'productPool/1.jpg', 163 ),
( 'SOLLO P.S BIG SPOON 100PCS', 'productPool/1.jpg', 233 ),
( 'SONA LUNCH BOX FAMILY', 'productPool/1.jpg', 145 ),
( 'SONA SS URAL-3', 'productPool/1.jpg', 251 ),
( 'SONA SS URAL-4', 'productPool/1.jpg', 279 ),
( 'SONA VEGETABLE SLICER PLAIN', 'productPool/1.jpg', 229 ),
( 'SONAKSHI CLOTH CLIP 12PCS', 'productPool/1.jpg', 49 ),
( 'SONAL 3*-6 FOLD', 'productPool/1.jpg', 211 ),
( 'SONATA ZINK GUARD -1', 'productPool/1.jpg', 128 ),
( 'SONGE RS50', 'productPool/1.jpg', 144 ),
( 'SORAY CHOCOLATE BOX 500G', 'productPool/1.jpg', 275 ),
( 'SORAY CRIPTON CHOCOLATE 340G', 'productPool/1.jpg', 50 ),
( 'SOUP TOMATO 47G BAMBINO', 'productPool/1.jpg', 273 ),
( 'SOUTH AFRICAN LEMON', 'productPool/1.jpg', 70 ),
( 'SOYA CHUNKS 200G', 'productPool/1.jpg', 186 ),
( 'SOYA CHUNKS 200GM', 'productPool/1.jpg', 44 ),
( 'SOYA MILK CHOCOLATE 200ML', 'productPool/1.jpg', 216 ),
( 'SOYA MILK VANILA 200ML', 'productPool/1.jpg', 159 ),
( 'SOYA STICKS 150G', 'productPool/1.jpg', 197 ),
( 'SOYABEAN BALL 200G', 'productPool/1.jpg', 275 ),
( 'SOYABEAN PAYAR 500G', 'productPool/1.jpg', 276 ),
( 'SOYFRESH SOYA MILK 250ML', 'productPool/1.jpg', 279 ),
( 'SOYFRESH SOYA MILK STRAWBERRY 250ML', 'productPool/1.jpg', 189 ),
( 'SOYVITA DIABETIC POWDER 200GM', 'productPool/1.jpg', 272 ),
( 'SOYVITA POWDER 200G', 'productPool/1.jpg', 30 ),
( 'SOYVITA SWEETENED 500G', 'productPool/1.jpg', 2 ),
( 'SPACHULA HS', 'productPool/1.jpg', 107 ),
( 'SPADE THREAD', 'productPool/1.jpg', 250 ),
( 'Special Gift box', 'productPool/1.jpg', 159 ),
( 'SPEED DRY BABY SHEET LARGE MB03', 'productPool/1.jpg', 98 ),
( 'SPEED DRY BABY SHEET MEDIUM MB02', 'productPool/1.jpg', 65 ),
( 'SPEED DRY KIDS MATE SMALL MB01', 'productPool/1.jpg', 1 ),
( 'SPEED PACK STOFF PIPE BROOM', 'productPool/1.jpg', 92 ),
( 'SPICY-SPICY BANANA FRUIT CHIPS 170G', 'productPool/1.jpg', 148 ),
( 'SPICY-SPICY MURUKKU 140G', 'productPool/1.jpg', 73 ),
( 'SPICY-SPICY POTATO CHIPS 100G', 'productPool/1.jpg', 214 ),
( 'SPICY-SPICY POTATO LAYS 100G', 'productPool/1.jpg', 40 ),
( 'SPICY-SPICY TAPIOCA WAFERS 170G', 'productPool/1.jpg', 44 ),
( 'SPILT CASHEW 100G', 'productPool/1.jpg', 129 ),
( 'SPILT CASHEW 1KG', 'productPool/1.jpg', 161 ),
( 'SPILT CASHEW 50G', 'productPool/1.jpg', 183 ),
( 'SPINNER TOY RS15', 'productPool/1.jpg', 248 ),
( 'SPINNER TOY RS24', 'productPool/1.jpg', 215 ),
( 'SPINNER TOY RS35', 'productPool/1.jpg', 258 ),
( 'SPINNER TOY RS80', 'productPool/1.jpg', 272 ),
( 'SPONGE', 'productPool/1.jpg', 270 ),
( 'SPONGE RS45', 'productPool/1.jpg', 149 ),
( 'SPONGE RS50', 'productPool/1.jpg', 212 ),
( 'SPONGE SCRABER', 'productPool/1.jpg', 89 ),
( 'SPONGE SCRABER RS4', 'productPool/1.jpg', 180 ),
( 'SPORTZERO COMFY MAX BRUSH', 'productPool/1.jpg', 69 ),
( 'SPORTZERO COMFY MINI BRUSH', 'productPool/1.jpg', 279 ),
( 'SPORTZERO COMFY PREMIUM CLOTH BRUSH', 'productPool/1.jpg', 64 ),
( 'SPORTZERO DUST PAN', 'productPool/1.jpg', 45 ),
( 'SPORTZERO SHUBHRA GRASS BROOM', 'productPool/1.jpg', 45 ),
( 'SPORTZERO UTENSIL SCRUBBER', 'productPool/1.jpg', 203 ),
( 'SPORTZERO ZERO DUST BROOM', 'productPool/1.jpg', 180 ),
( 'SPOT ZERO JUMBO WIPER', 'productPool/1.jpg', 147 ),
( 'SPOT ZERO NANO WIPER', 'productPool/1.jpg', 197 ),
( 'SPOT ZERO SMART WIPER', 'productPool/1.jpg', 250 ),
( 'SPOTZERO BATHROOM WATER WIPER', 'productPool/1.jpg', 79 ),
( 'SPOTZERO BOTTLE BRUSH', 'productPool/1.jpg', 216 ),
( 'SPOTZERO COZY TWIN COLOUR CLOTH BRUSH', 'productPool/1.jpg', 193 ),
( 'SPOTZERO DAILY DUSTER', 'productPool/1.jpg', 185 ),
( 'SPOTZERO DECK MOP COTTON', 'productPool/1.jpg', 61 ),
( 'SPOTZERO DEEP BUCKET 20L', 'productPool/1.jpg', 61 ),
( 'SPOTZERO FLOOR & TILE BRUSH', 'productPool/1.jpg', 226 ),
( 'SPOTZERO GLOVES', 'productPool/1.jpg', 80 ),
( 'SPOTZERO GLOVES LARGAE', 'productPool/1.jpg', 23 ),
( 'SPOTZERO HANDY SCOURER', 'productPool/1.jpg', 14 ),
( 'SPOTZERO LEVELER DUST PAN', 'productPool/1.jpg', 14 ),
( 'SPOTZERO MILTON BUCKET 1800ML', 'productPool/1.jpg', 240 ),
( 'SPOTZERO MILTON BUCKET 20L', 'productPool/1.jpg', 109 ),
( 'SPOTZERO MILTON BUCKET 25L', 'productPool/1.jpg', 261 ),
( 'SPOTZERO MILTON ELITE SPIN MOP 1U', 'productPool/1.jpg', 88 ),
( 'SPOTZERO MILTON MUG 1.5L', 'productPool/1.jpg', 97 ),
( 'SPOTZERO MILTON NON STICK UTENSIL SCOURER', 'productPool/1.jpg', 147 ),
( 'SPOTZERO MILTON PEBBLE BUCKET 25L', 'productPool/1.jpg', 76 ),
( 'SPOTZERO MILTON SMART SPIN MOP 1U', 'productPool/1.jpg', 196 ),
( 'SPOTZERO MILTON STAINLESS STEEL SCOURER', 'productPool/1.jpg', 130 ),
( 'SPOTZERO MILTON TOILET BRUSH DOUBLE SIDE BRISTLES', 'productPool/1.jpg', 203 ),
( 'SPOTZERO MILTON TOILET BRUSH SINGLE SIDE BRISTLES', 'productPool/1.jpg', 209 ),
( 'SPOTZERO MILTON TOILET BRUSH WITH CANDY SLIM', 'productPool/1.jpg', 31 ),
( 'SPOTZERO MILTON TWIST SQUEEZE MOP COTTON', 'productPool/1.jpg', 250 ),
( 'SPOTZERO POPULAR FLOOR WIPER', 'productPool/1.jpg', 271 ),
( 'SPOTZERO POWER SCRUB', 'productPool/1.jpg', 94 ),
( 'SPOTZERO PRIMA CLOTH BRUSH', 'productPool/1.jpg', 240 ),
( 'SPOTZERO ROOF DUSTER', 'productPool/1.jpg', 254 ),
( 'SPOTZERO SCRUBBER', 'productPool/1.jpg', 192 );