INSERT
	INTO
	productMaster( [name], [image], subCategoryChildId )
VALUES ( 'NYCIL COOLING SANDAL 150G', 'productPool/1.jpg', 56 ),
( 'NYCIL GERM EXPERTCOOL ALOVE 150G', 'productPool/1.jpg', 21 ),
( 'NYCIL GERM EXPERTCOOL GULABJAL150G', 'productPool/1.jpg', 93 ),
( 'NYCIL GERM EXPERTCOOL HERBAL 150G', 'productPool/1.jpg', 205 ),
( 'NYCIL GERM EXPERTCOOLCLASSIC 150G', 'productPool/1.jpg', 9 ),
( 'NYCIL LAVENDER EXCEL 150G', 'productPool/1.jpg', 200 ),
( 'NYCIL SANDAL EXCEL 150G', 'productPool/1.jpg', 3 ),
( 'NYLON ROPE', 'productPool/1.jpg', 275 ),
( 'NYLON ROPE 10 MTS', 'productPool/1.jpg', 133 ),
( 'NYLON ROPE 15 MTS', 'productPool/1.jpg', 216 ),
( 'NYLON ROPE 30MTS', 'productPool/1.jpg', 206 ),
( 'NYLON ROPE RS 65', 'productPool/1.jpg', 12 ),
( 'NYZE AMLA CANDY 150G', 'productPool/1.jpg', 200 ),
( 'OANM SPECIAL PAPPADAM RS 65', 'productPool/1.jpg', 160 ),
( 'OATS CHOCO DELIGHT 40 G', 'productPool/1.jpg', 1 ),
( 'OATS SOUP TANGY TOMATO 40 G', 'productPool/1.jpg', 215 ),
( 'OATS SPICY MEXICAN 40 G', 'productPool/1.jpg', 90 ),
( 'OATS TOMATO SALSA 40 G', 'productPool/1.jpg', 253 ),
( 'OCEAN CRISPY APPLE DRINK 500ML', 'productPool/1.jpg', 169 ),
( 'OCEAN DRINK LIME ORANGE 300ML', 'productPool/1.jpg', 6 ),
( 'OCEAN DRINK PINEAPPLE STRAWBERRY 300ML', 'productPool/1.jpg', 208 ),
( 'OCEAN DRY BIG SOLE 100G', 'productPool/1.jpg', 176 ),
( 'OCEAN DRY SHARK 100G', 'productPool/1.jpg', 272 ),
( 'OCEAN FOODS DRY ANCHOY 100G', 'productPool/1.jpg', 249 ),
( 'OCEAN FOODS DRY PRAWN', 'productPool/1.jpg', 213 ),
( 'OCEAN FOODS DRY PRAWN CLEAN 40G', 'productPool/1.jpg', 115 ),
( 'OCEAN FOODS DRY SEA BRAL 100G', 'productPool/1.jpg', 70 ),
( 'OCEAN FOODS DRY SILVER BELLY 125G', 'productPool/1.jpg', 198 ),
( 'OCEAN MANGO PASSION FRUIT DRINK 500ML', 'productPool/1.jpg', 219 ),
( 'OCEAN PEACH PASSION FRUIT DRINK 500ML', 'productPool/1.jpg', 225 ),
( 'OCEAN PINK GUAVA DRINK 500ML', 'productPool/1.jpg', 108 ),
( 'OCTANE GEL PEN BLUE', 'productPool/1.jpg', 123 ),
( 'ODOMOS MOSQU CREAM 25G', 'productPool/1.jpg', 261 ),
( 'ODOMOS MOSQU CREAM 50G', 'productPool/1.jpg', 174 ),
( 'ODOMOS MOSQUITO CREAM 50G', 'productPool/1.jpg', 86 ),
( 'ODOMOS MOSQUITO LOT 60ML', 'productPool/1.jpg', 132 ),
( 'ODOMOS MOSQUITO REPELLENT CREAM 100G', 'productPool/1.jpg', 229 ),
( 'ODOMOS NATURAL CREAM 25GM', 'productPool/1.jpg', 236 ),
( 'ODOMOS NATURAL MOSQUITO SPRAY 100ML', 'productPool/1.jpg', 37 ),
( 'ODOMOS NATURALS LOTION 120ML', 'productPool/1.jpg', 160 ),
( 'ODONIAL AIR FRESHENER JASMINE 50G', 'productPool/1.jpg', 235 ),
( 'ODONIL 1 TOUCH 12ML FLORAL AIR SANITIZER', 'productPool/1.jpg', 69 ),
( 'ODONIL 1 TOUCH 12ML NATURAL SPRING AIR SANITIZER', 'productPool/1.jpg', 8 ),
( 'ODONIL 1 TOUCH REFIL FLORAL 12ML', 'productPool/1.jpg', 141 ),
( 'ODONIL 1 TOUCH REFIL NATURAL 12ML', 'productPool/1.jpg', 41 ),
( 'ODONIL AIR FRESHENER JASMINE MIST 50G', 'productPool/1.jpg', 176 ),
( 'ODONIL AIR FRESHENER LAVENDER 3+1', 'productPool/1.jpg', 113 ),
( 'ODONIL AIR FRESHENER LAVENDER 50G', 'productPool/1.jpg', 124 ),
( 'ODONIL AIR FRESHENER MYSTIC ROSE 50G', 'productPool/1.jpg', 235 ),
( 'ODONIL AIR FRESHENER ORCHID 3+1', 'productPool/1.jpg', 227 ),
( 'ODONIL AIR FRESHENER SPRING SCENTS 100G', 'productPool/1.jpg', 217 ),
( 'ODONIL BLOCK 50G 3+1 WHITEROSE', 'productPool/1.jpg', 247 ),
( 'ODONIL BLOCK 75 GM 3+1', 'productPool/1.jpg', 149 ),
( 'ODONIL BLOCK FRUIT BLAST B3G1 200G', 'productPool/1.jpg', 200 ),
( 'ODONIL CITRUS GEL 75G', 'productPool/1.jpg', 130 ),
( 'ODONIL CITRUS SPICE 75G', 'productPool/1.jpg', 117 ),
( 'ODONIL FLIRTY STRAWBERRY 75G', 'productPool/1.jpg', 169 ),
( 'ODONIL FRUIT BLAST AIR FRESHENER 300G', 'productPool/1.jpg', 270 ),
( 'ODONIL GEL ROSE DREAMS 75G', 'productPool/1.jpg', 45 ),
( 'ODONIL GEL STRAWBERY 75G', 'productPool/1.jpg', 201 ),
( 'ODONIL JASMINE 75G', 'productPool/1.jpg', 242 ),
( 'ODONIL JASMINE AIR FRESH 75G', 'productPool/1.jpg', 64 ),
( 'ODONIL JASMINE FRESHNER 50G', 'productPool/1.jpg', 55 ),
( 'ODONIL JASMINE MIST 75G', 'productPool/1.jpg', 262 ),
( 'ODONIL LAVENDER AIR FRESH 75G', 'productPool/1.jpg', 276 ),
( 'ODONIL LAVENDER FRESH 100G', 'productPool/1.jpg', 161 ),
( 'ODONIL LAVENDER FRESHNER 50G', 'productPool/1.jpg', 82 ),
( 'ODONIL LAVENDER HANGER 50G', 'productPool/1.jpg', 276 ),
( 'ODONIL LAVENDER MEADOWS 75G', 'productPool/1.jpg', 239 ),
( 'ODONIL MY STIC LAVENDER 75G', 'productPool/1.jpg', 111 ),
( 'ODONIL MYST ROSE AIR FRESH 75G', 'productPool/1.jpg', 203 ),
( 'ODONIL MYSTIC ROSE 75G', 'productPool/1.jpg', 74 ),
( 'ODONIL MYSTIC ROSE FRESHNER 50G', 'productPool/1.jpg', 48 ),
( 'ODONIL MYTHROSE 100G', 'productPool/1.jpg', 266 ),
( 'ODONIL NAT LAVEND MIS 170ML', 'productPool/1.jpg', 221 ),
( 'ODONIL NAT ROSE GARD 300ML', 'productPool/1.jpg', 226 ),
( 'ODONIL NATU SANDAL BOU 170ML', 'productPool/1.jpg', 7 ),
( 'ODONIL NATURE CITRUS FRESH 140GM', 'productPool/1.jpg', 112 ),
( 'ODONIL NATURE GEL LAVENDER 75G', 'productPool/1.jpg', 262 ),
( 'ODONIL NATURE JASMINE GEL 75G', 'productPool/1.jpg', 31 ),
( 'ODONIL ODONIL JASMINE FRESH 100G', 'productPool/1.jpg', 77 ),
( 'ODONIL ORCHID AIR FRESH 75G', 'productPool/1.jpg', 145 ),
( 'ODONIL ORCHID DEW 50G', 'productPool/1.jpg', 33 ),
( 'ODONIL ORCHID DEW 75G', 'productPool/1.jpg', 93 ),
( 'ODONIL ORCHID FRESH 100G', 'productPool/1.jpg', 219 ),
( 'ODONIL ORCHID FRESH 50G', 'productPool/1.jpg', 165 ),
( 'ODONIL ROOM FRESHENING GEL PASSION FRUIT 75G', 'productPool/1.jpg', 86 ),
( 'ODONIL ROOM FRESHNER 140G JASMINE', 'productPool/1.jpg', 165 ),
( 'ODONIL ROOM FRESHNER 140G ROSE', 'productPool/1.jpg', 139 ),
( 'ODONIL ROOM FRESHNER 200G CITRUS FRESH', 'productPool/1.jpg', 155 ),
( 'ODONIL ROOM FRESHNER 200G JASMINE', 'productPool/1.jpg', 204 ),
( 'ODONIL ROOM FRESHNER 200G SANDAL', 'productPool/1.jpg', 160 ),
( 'ODONIL ROOM FRESHNER 250ML LAVENDER', 'productPool/1.jpg', 48 ),
( 'ODONIL ROOM SPRAY FLORAL BLISS 270ML', 'productPool/1.jpg', 106 ),
( 'ODONIL ROOM SPRAY JASMINE FRESH 108G', 'productPool/1.jpg', 151 ),
( 'ODONIL ROOM SPRAY LAVENDER MIST 108G', 'productPool/1.jpg', 139 ),
( 'ODONIL ROOM SPRAY LAVENDER MIST 270M', 'productPool/1.jpg', 62 ),
( 'ODONIL ROOM SPRAY OCEAN BREEZE 270ML', 'productPool/1.jpg', 29 ),
( 'ODONIL ROOM SPRAY ROSE GARDEN 270ML', 'productPool/1.jpg', 148 ),
( 'ODONIL ROOM SPRAY SANDAL BOUQUET 108G', 'productPool/1.jpg', 236 ),
( 'ODONIL ROSE GEL 75G', 'productPool/1.jpg', 165 ),
( 'ODONIL SMILE FRESH MELODY AIR FRESHNER 1N', 'productPool/1.jpg', 163 ),
( 'ODONIL SMILE MIAMI DREAM AIR FRESHNER 1N', 'productPool/1.jpg', 270 ),
( 'ODONIL SMILE SPANISH SUNSET AIR FRESHNER 1N', 'productPool/1.jpg', 102 ),
( 'ODONIL ZIPPER ALLURING DAFFODIL 10G', 'productPool/1.jpg', 207 ),
( 'ODONIL ZIPPER CITRUS 10G', 'productPool/1.jpg', 58 ),
( 'ODONIL ZIPPER JASMINE 10G', 'productPool/1.jpg', 53 ),
( 'ODONIL ZIPPER LAVENDER 10G', 'productPool/1.jpg', 20 ),
( 'ODONIL ZIPPER SCINTILLATING ROSE 10G', 'productPool/1.jpg', 98 ),
( 'ODOPIC DISH WASH BAR 500G', 'productPool/1.jpg', 67 ),
( 'ODOPIC DISHWASH BAR 200G', 'productPool/1.jpg', 277 ),
( 'ODOPIC DISHWASH BAR RS 61', 'productPool/1.jpg', 26 ),
( 'OIDSPICE MUSK SHAVINS CREAM 70G', 'productPool/1.jpg', 236 ),
( 'OIDSPICE ORIGINAL SHAVING CREAM 70GM', 'productPool/1.jpg', 171 ),
( 'OIL DISPENSER 24 CARAT 500ML', 'productPool/1.jpg', 98 ),
( 'OLAAM COCONUT PALM JAGGERY 500G', 'productPool/1.jpg', 235 ),
( 'OLAAM HIMALAYAN ROCK SALT LKG', 'productPool/1.jpg', 196 ),
( 'OLAAM PEANUT BALL 100G', 'productPool/1.jpg', 11 ),
( 'OLAY AGE PROTECT CREAM 40G', 'productPool/1.jpg', 253 ),
( 'OLAY ANTI AGEING CREAM 18G', 'productPool/1.jpg', 12 ),
( 'OLAY ANTI AGEING CREAM 20G', 'productPool/1.jpg', 2 ),
( 'OLAY ANTI AGEING DAY CREAM SPF 15 8G', 'productPool/1.jpg', 234 ),
( 'OLAY ANTI CREAM 18G', 'productPool/1.jpg', 238 ),
( 'OLAY ANTI-AGEING MOISTURISER 10G', 'productPool/1.jpg', 212 ),
( 'OLAY BB CREAM ALL SKIN TONES 50G', 'productPool/1.jpg', 80 ),
( 'OLAY BRIGHTENING NIGHT CREAM 50G', 'productPool/1.jpg', 160 ),
( 'OLAY BRIGHTENING WHITE CREAM 20G', 'productPool/1.jpg', 98 ),
( 'OLAY CLEANSER REGENERIST 100G', 'productPool/1.jpg', 15 ),
( 'OLAY CREAM AGE PROTECT 40GM', 'productPool/1.jpg', 17 ),
( 'OLAY DAY CREAM NORMAL SPF 15 12G', 'productPool/1.jpg', 45 ),
( 'OLAY LUMINOUS WHIP 10G', 'productPool/1.jpg', 212 ),
( 'OLAY MOISTURIZING CREAM 100G', 'productPool/1.jpg', 204 ),
( 'OLAY MOISTURIZING CREAM 50G', 'productPool/1.jpg', 75 ),
( 'OLAY NATURAL WHITE 40G', 'productPool/1.jpg', 189 ),
( 'OLAY NATURAL WHITE CREAM IGF 40G', 'productPool/1.jpg', 268 ),
( 'OLAY NATURAL WHITE DAY CREAM 50G', 'productPool/1.jpg', 203 ),
( 'OLAY NATURAL WHITE DAY SPF 24 50G', 'productPool/1.jpg', 44 ),
( 'OLAY NATURAL WHITE IGF 20G', 'productPool/1.jpg', 131 ),
( 'OLAY NATURAL WHITE NIGHT CREAM', 'productPool/1.jpg', 173 ),
( 'OLAY NATURAL WHITE NIGHT REPAIR CREAM 50G', 'productPool/1.jpg', 166 ),
( 'OLAY REGENERIST CREAM 50G', 'productPool/1.jpg', 76 ),
( 'OLAY REGENERIST NIGHT CREAM 50G', 'productPool/1.jpg', 92 ),
( 'OLAY REGENERIST WHIP 10G', 'productPool/1.jpg', 29 ),
( 'OLAY REVITALISING MOISTURISER CREAM 50G', 'productPool/1.jpg', 5 ),
( 'OLAY SMOOTHING SERUM 50ML', 'productPool/1.jpg', 98 ),
( 'OLAY TE ANTI AGEING CREAM NORMAL 50G', 'productPool/1.jpg', 279 ),
( 'OLAY TE ANTI AGEING CREAM SPF 15 8G', 'productPool/1.jpg', 147 ),
( 'OLAY TE ANTI AGEING CREAM SPF 1520G', 'productPool/1.jpg', 220 ),
( 'OLAY TE ANTI AGEING DAY CREAM 50G', 'productPool/1.jpg', 116 ),
( 'OLAY TE ANTI AGEING GENTLECREAM 50G', 'productPool/1.jpg', 12 ),
( 'OLAY TE ANTI AGEING NIGHT CREAM 50G', 'productPool/1.jpg', 263 ),
( 'OLAY TE ANTI AGEING NORMALCREAM 50G', 'productPool/1.jpg', 75 ),
( 'OLAY TE CLEANSER 100G', 'productPool/1.jpg', 2 ),
( 'OLAY TE CLEANSER 100G ANTI AGEING FW', 'productPool/1.jpg', 220 ),
( 'OLAY TE NORMAL DAY SPF 15 CRM 20G', 'productPool/1.jpg', 11 ),
( 'OLAY TE WEIGHTLESS FEEL CREAM 50G', 'productPool/1.jpg', 16 ),
( 'OLAY TOTAL EFFECT CLEANSER 100G', 'productPool/1.jpg', 180 ),
( 'OLAY TOTAL EFFECT DAY CREAM 20G', 'productPool/1.jpg', 130 ),
( 'OLAY TOTAL EFFECT NIGHT CREAM 20G', 'productPool/1.jpg', 47 ),
( 'OLAY TOTAL EFFECT NUV RS 799', 'productPool/1.jpg', 165 ),
( 'OLAY TOTAL EFFECTS BB CREAM50G', 'productPool/1.jpg', 201 ),
( 'OLAY TOTAL EFFECTS NORMAL RS799', 'productPool/1.jpg', 93 ),
( 'OLAY WHITE RADIANCE CLEANSER 100G', 'productPool/1.jpg', 225 ),
( 'OLAY WHITE RADIANCE DAY CREAM 50G', 'productPool/1.jpg', 27 ),
( 'OLAY WHITE RADIANCE DAY CREAM RS 1000', 'productPool/1.jpg', 36 ),
( 'OLAY WHITE RADIENCE DAY CREAM 50G', 'productPool/1.jpg', 36 ),
( 'OLAY WR CLENSER 100G', 'productPool/1.jpg', 73 ),
( 'OLAY WR DAY CREAM 50G +CLEANSER', 'productPool/1.jpg', 68 ),
( 'OLD SPICE AFTER SHAVE ATOMIZER ORIGINAL150ML', 'productPool/1.jpg', 38 ),
( 'OLD SPICE AFTER SHAVE LOTION FRESH LIME50ML', 'productPool/1.jpg', 13 ),
( 'OLD SPICE AFTER SHAVE LOTION MUSK 100ML', 'productPool/1.jpg', 48 ),
( 'OLD SPICE AFTER SHAVE LOTION ORIGINAL 100ML', 'productPool/1.jpg', 141 ),
( 'OLD SPICE AFTER SHAVE LOTION ORIGNAL 50ML', 'productPool/1.jpg', 179 ),
( 'OLD SPICE AFTER SHAVE SPLASH ORIGNAL150ML', 'productPool/1.jpg', 215 ),
( 'OLD SPICE ATOMIZER FRESH LIME', 'productPool/1.jpg', 238 ),
( 'OLD SPICE DANGER ZONE DEODORANT SPRAY 150ML', 'productPool/1.jpg', 210 ),
( 'OLD SPICE DEO SPARY ORIGINAL 150ML', 'productPool/1.jpg', 10 ),
( 'OLD SPICE DEO SPRAY AMBER 140ML', 'productPool/1.jpg', 208 ),
( 'OLD SPICE DEO SPRAY KRAKKENGARD 140ML', 'productPool/1.jpg', 140 ),
( 'OLD SPICE DEO SPRAY LIONPRIDE 140ML', 'productPool/1.jpg', 154 ),
( 'OLD SPICE DEO SPRAY NOMAD 140ML', 'productPool/1.jpg', 261 ),
( 'OLD SPICE DEO SPRAY TIMBER140ML', 'productPool/1.jpg', 230 ),
( 'OLD SPICE DEO SPRAY WOLFTHORN 140ML', 'productPool/1.jpg', 83 ),
( 'OLD SPICE DEOSPRAY FRESH 150ML', 'productPool/1.jpg', 213 ),
( 'OLD SPICE FRESH DEO SPRAY150ML', 'productPool/1.jpg', 265 ),
( 'OLD SPICE FRESH LIME LOTION 50ML', 'productPool/1.jpg', 276 ),
( 'OLD SPICE LATHER SHAVING CREAM MUSK', 'productPool/1.jpg', 82 ),
( 'OLD SPICE MUSK DEO 150ML', 'productPool/1.jpg', 231 ),
( 'OLD SPICE MUSK DEO SPARY 150ML', 'productPool/1.jpg', 11 ),
( 'OLD SPICE ORIGINAL ATOMIZER 150ML', 'productPool/1.jpg', 45 ),
( 'OLD SPICE SAVING LOTION MUSK 50ML', 'productPool/1.jpg', 192 ),
( 'OLD SPICE SAVING LOTION ORIGINAL 50ML', 'productPool/1.jpg', 35 ),
( 'OLD SPICE SPORT FRESH DEO SPRAY150ML', 'productPool/1.jpg', 5 ),
( 'OLD SPICE WHITEWATER DEO SPARY 150ML', 'productPool/1.jpg', 117 ),
( 'OLD SPICE WHITEWATER SPRAY 150ML', 'productPool/1.jpg', 86 ),
( 'OLDSPICE AF LOTION MUSK 100ML', 'productPool/1.jpg', 135 ),
( 'OLDSPICE AFTER SHAVE LOTION LIME 150ML', 'productPool/1.jpg', 64 ),
( 'OLDSPICE AFTER SHAVE LOTION MUSK 150ML', 'productPool/1.jpg', 135 ),
( 'OLDSPICE AFTER SHAVE LOTION ORIGINAL 100ML', 'productPool/1.jpg', 218 ),
( 'OLDSPICE AFTER SHAVE LOTION ORIGINAL 150ML', 'productPool/1.jpg', 76 ),
( 'OLDSPICE ASL ATOMISER MUSK', 'productPool/1.jpg', 32 ),
( 'OLDSPICE ASL ATOMIZER LIME 150ML', 'productPool/1.jpg', 223 ),
( 'OLDSPICE ATOMISER MUSK 150ML', 'productPool/1.jpg', 59 ),
( 'OLDSPICE DEO SPARY DANGER ZONE 150ML', 'productPool/1.jpg', 82 ),
( 'OLDSPICE FRESH LIME MAN 70GM', 'productPool/1.jpg', 85 ),
( 'OLDSPICE POCKET SPRAY LION 17ML', 'productPool/1.jpg', 79 ),
( 'OLDSPICE POCKET SPRAY NOMAD 17ML', 'productPool/1.jpg', 163 ),
( 'OLDSPICE SHAVING CREAM FRESH LIME 30G', 'productPool/1.jpg', 10 ),
( 'OLDSPICE SHAVING CREAM ORIGINAL 30G', 'productPool/1.jpg', 265 ),
( 'OLIO BEANS BISCUIT 170G', 'productPool/1.jpg', 217 ),
( 'OLIO KHARI 170G', 'productPool/1.jpg', 62 ),
( 'OLIO SWEET KHARI 170G', 'productPool/1.jpg', 184 ),
( 'OLIVA HERBAL BLEACH 60G', 'productPool/1.jpg', 88 ),
( 'OLIVA NATURAL TOILET SOAP', 'productPool/1.jpg', 218 ),
( 'OLIVA SET SOAP 3*100G', 'productPool/1.jpg', 50 ),
( 'OLIVA SET SOAP 4*100G', 'productPool/1.jpg', 261 ),
( 'OLIVIA GOLD BLEACH 9GM', 'productPool/1.jpg', 208 ),
( 'OLIVIA HERB BLEACH', 'productPool/1.jpg', 195 ),
( 'OLIVIA HERB BLEACH 15G', 'productPool/1.jpg', 101 ),
( 'OLIVIA HERB BLEACH 8G', 'productPool/1.jpg', 79 ),
( 'OLIVIA HERBAL HAIR REMOVER 30G', 'productPool/1.jpg', 198 ),
( 'OLIVIA OXY BLEACH 9G', 'productPool/1.jpg', 175 ),
( 'OLIVIA STRAWBERY HAIR REMOVER 30G', 'productPool/1.jpg', 46 ),
( 'OLIVWISH OLIVE OIL 100ML', 'productPool/1.jpg', 209 ),
( 'OM SANTHI SAMBRANI 15N', 'productPool/1.jpg', 66 ),
( 'OM SHANHI CAMPHOR 25N', 'productPool/1.jpg', 117 ),
( 'OM SHANTHI AADYAA AGARBATHI RS50', 'productPool/1.jpg', 58 ),
( 'OM SHANTHI AADYAA DHOOP AGARBATHI MRP10', 'productPool/1.jpg', 102 ),
( 'OM SHANTHI AGARPATHI 66N', 'productPool/1.jpg', 26 ),
( 'OM SHANTHI NAVIN', 'productPool/1.jpg', 177 ),
( 'OM SHANTHI PUJA OIL JASMINE 1L', 'productPool/1.jpg', 21 ),
( 'OM SHANTHI PUJA OIL JASMINE 500ML', 'productPool/1.jpg', 248 ),
( 'OM SHANTHI PUJA OIL NAVIN 1L', 'productPool/1.jpg', 189 ),
( 'OM SHANTHI PUJA OIL NAVIN 500ML', 'productPool/1.jpg', 214 ),
( 'OM SHANTHI PUJA OIL PARIJATA 1L', 'productPool/1.jpg', 32 ),
( 'OM SHANTHI PUJA OIL PARIJATA 500ML', 'productPool/1.jpg', 9 ),
( 'ON WOOD BELEN TIK', 'productPool/1.jpg', 44 ),
( 'ONATTUKARA COCONUT CHIPS 25G', 'productPool/1.jpg', 213 ),
( 'ONATTUKARA COCONUT OIL 1L BOTTLE', 'productPool/1.jpg', 215 ),
( 'ONATTUKARA COCONUT OIL 1L POUCH', 'productPool/1.jpg', 91 ),
( 'ONATTUKARA COCONUT OIL 2L BOTTLE', 'productPool/1.jpg', 68 ),
( 'ONATTUKARA COCONUT OIL 500ML BOTTLE', 'productPool/1.jpg', 68 ),
( 'ONATTUKARA GINGER MIX 100G', 'productPool/1.jpg', 161 ),
( 'ONATTUKARA INSTANT THEEYAL MIX 100G', 'productPool/1.jpg', 240 ),
( 'ONJUS APPLE DRINK 1L', 'productPool/1.jpg', 251 ),
( 'ONJUS MIXED FRUIT DRINK 1L', 'productPool/1.jpg', 272 ),
( 'ONJUS ORANG DRINK 1L', 'productPool/1.jpg', 250 ),
( 'ONLY ALL PURPOSE SEASONING GRINDER 40G', 'productPool/1.jpg', 171 ),
( 'ONLY BLACK PEPPER GRINDER 50G', 'productPool/1.jpg', 132 ),
( 'ONLY CHILLI FLAKES HERBS', 'productPool/1.jpg', 171 ),
( 'ONLY OREGANO HERBS 25G', 'productPool/1.jpg', 146 ),
( 'ONLY PINK SALT GRINDER 100G', 'productPool/1.jpg', 23 ),
( 'ONLY QUEEN HONEY NUTS 250G IMP', 'productPool/1.jpg', 140 ),
( 'ONLY QUEEN HONEY NUTS 500G IMP', 'productPool/1.jpg', 149 ),
( 'ONLY SOUP SEASONING GRINDER 45G', 'productPool/1.jpg', 165 ),
( 'OOTHU ORGANIC GREEN TEA 125G', 'productPool/1.jpg', 93 ),
( 'OOTTY BEANS', 'productPool/1.jpg', 219 ),
( 'OOTTY CARROT', 'productPool/1.jpg', 127 ),
( 'ORAGANIC INDIA GHEE 500ML', 'productPool/1.jpg', 128 ),
( 'ORAL -B BUY 5', 'productPool/1.jpg', 174 ),
( 'ORAL -B SENSITIVE WHITENING SOFT 40 BRUSH', 'productPool/1.jpg', 99 ),
( 'ORAL B 123 BLACK M 40 TOOTHBRUSH', 'productPool/1.jpg', 242 ),
( 'ORAL B 123 NEEM BRUSH SOFT B2G1', 'productPool/1.jpg', 95 ),
( 'ORAL B 123 NEEM MEDIUM BRUSH', 'productPool/1.jpg', 245 ),
( 'ORAL B 123 NEEM SOFT BRUSH', 'productPool/1.jpg', 186 ),
( 'ORAL B ALL ROUNDER BRUSH', 'productPool/1.jpg', 246 ),
( 'ORAL B BLACK ULTRATHIN SENSITIVE140RS', 'productPool/1.jpg', 161 ),
( 'ORAL B CAVITY DEFENSE 123 6 PACK SOFT', 'productPool/1.jpg', 260 ),
( 'ORAL B CAVITY DEFENSE 123 BLACK', 'productPool/1.jpg', 249 ),
( 'ORAL B CAVITY DEFENSE 123 BLACK B3G1', 'productPool/1.jpg', 186 ),
( 'ORAL B CAVITY DEFENSE 123 BLACK SOFT', 'productPool/1.jpg', 275 ),
( 'ORAL B CAVITY DEFENSE 6 PACK BRUSH', 'productPool/1.jpg', 34 ),
( 'ORAL B CHARCOAL EXTRA SOFT B2G1', 'productPool/1.jpg', 189 ),
( 'ORAL B CROSS ACTION POWER BRUSH SOFT', 'productPool/1.jpg', 123 ),
( 'ORAL B FRESH CLEAN MEDIUM', 'productPool/1.jpg', 11 ),
( 'ORAL B FRESH CLEAN NEEM MEDIUM', 'productPool/1.jpg', 156 ),
( 'ORAL B GREEN ULTRATHIN SENSITIVE', 'productPool/1.jpg', 129 ),
( 'ORAL B GUM PROTECT EXTRA SOFT', 'productPool/1.jpg', 115 ),
( 'ORAL B GUM PROTECT SOFT', 'productPool/1.jpg', 28 ),
( 'ORAL B GUMCARE BRUSH', 'productPool/1.jpg', 54 ),
( 'ORAL B KIDS 2+ YEARS', 'productPool/1.jpg', 150 ),
( 'ORAL B KIDS 2+ YEARS 3S', 'productPool/1.jpg', 52 ),
( 'ORAL B PH CHARCOAL SOFT BRUSH', 'productPool/1.jpg', 220 ),
( 'ORAL B PRO HEALTH BRUSH', 'productPool/1.jpg', 189 ),
( 'ORAL B PRO HEALTH BRUSH MEDIUM B 2G1', 'productPool/1.jpg', 24 ),
( 'ORAL B PRO HEALTH CRISSCROSS M', 'productPool/1.jpg', 3 ),
( 'ORAL B PRO HEALTH GUM CARE B2G1', 'productPool/1.jpg', 35 ),
( 'ORAL B PRO HEALTH MEDIUM M', 'productPool/1.jpg', 148 ),
( 'ORAL B PRO HEALTH MEDIUM SINGLE BRUSH', 'productPool/1.jpg', 279 ),
( 'ORAL B PRO HEALTH NEEM MEDIUM', 'productPool/1.jpg', 2 ),
( 'ORAL B PRO HEALTH NEEM MEDIUM B2G1', 'productPool/1.jpg', 259 ),
( 'ORAL B PRO HEALTH NEEM SOFT B2G1', 'productPool/1.jpg', 5 ),
( 'ORAL B PRO HEALTH SENSITIVE BRUSH B2G1', 'productPool/1.jpg', 270 ),
( 'ORAL B PRO HEALTH SENSITIVE EXTRA SOFT XS', 'productPool/1.jpg', 279 ),
( 'ORAL B PRO HEALTH SOFT 2S', 'productPool/1.jpg', 148 ),
( 'ORAL B PRO HEALTH SOFT B2G1', 'productPool/1.jpg', 275 ),
( 'ORAL B PRO HEALTH SOFT B2G2', 'productPool/1.jpg', 31 ),
( 'ORAL B PRO HEALTH SOFT BRUSH', 'productPool/1.jpg', 191 ),
( 'ORAL B SENSITIVE CARE SOFT', 'productPool/1.jpg', 110 ),
( 'ORAL B SENSITIVE EXTRASOFT BRUSH', 'productPool/1.jpg', 21 ),
( 'ORAL B SENSITIVE WHITENING', 'productPool/1.jpg', 6 ),
( 'ORAL B SENSITIVE WHITENING SOFT', 'productPool/1.jpg', 183 ),
( 'ORAL B SHINY CLEAN CLOVE SOFT', 'productPool/1.jpg', 64 ),
( 'ORAL B SHINY CLEAN MEDIUM', 'productPool/1.jpg', 32 ),
( 'ORAL B SHINY CLEAN MEDIUM BRUSH', 'productPool/1.jpg', 254 ),
( 'ORAL B ULTRA THIN BRUSH', 'productPool/1.jpg', 23 ),
( 'ORAL B ULTRA THIN SENSITIVE 0.01MM BRUSH', 'productPool/1.jpg', 53 ),
( 'ORAL B ULTRA THIN SENSITIVE SOFT BRUSH', 'productPool/1.jpg', 192 ),
( 'ORAL B ULTRATHIN SENSITIVE 2S', 'productPool/1.jpg', 120 ),
( 'ORAL B ULTRATHIN SENSITIVE B2G1', 'productPool/1.jpg', 236 ),
( 'ORAL B ULTRATHIN SENSITIVE BLACK BRUSH', 'productPool/1.jpg', 66 ),
( 'ORAL B ULTRATHIN SENSITIVE GREEN B2G1', 'productPool/1.jpg', 222 ),
( 'ORAL-B CAVITY DEFENSE 123 MEDIUM BRUSH', 'productPool/1.jpg', 251 ),
( 'ORAL-B GENTLE CARE WITH C LOVE 6+1', 'productPool/1.jpg', 80 ),
( 'ORAL-B GUM CARE MEDIUM TOOTHBRUSH', 'productPool/1.jpg', 26 ),
( 'ORAL-B GUM HEALTH MEDIUM TOOTHBRUSH', 'productPool/1.jpg', 257 ),
( 'ORAL-B KIDS 2-4YRSOFT BRUSH', 'productPool/1.jpg', 159 ),
( 'ORAL-B PRO HEALTH MEDIUM TOOTHBRUSH', 'productPool/1.jpg', 27 ),
( 'ORAL-B PRO HEALTH SMART FLEX', 'productPool/1.jpg', 11 ),
( 'ORAL-B PRO-HEALTH GUMCARE', 'productPool/1.jpg', 196 ),
( 'ORAL-B PROHEALTH BASE SFT BOD', 'productPool/1.jpg', 95 ),
( 'ORAL-B SENSITIVE WHITENING', 'productPool/1.jpg', 109 ),
( 'ORAL-B SENSITIVE WHITENING SOFT TOOTHBRUSH', 'productPool/1.jpg', 146 ),
( 'ORALB PRO HEALTH SMART FLEX TWIN PACK BRUSH', 'productPool/1.jpg', 59 ),
( 'ORALB PRO HEALTH SOFT', 'productPool/1.jpg', 42 ),
( 'ORALB PROHEALTH GUMCARE SOFT B2G1', 'productPool/1.jpg', 18 ),
( 'ORANGE', 'productPool/1.jpg', 168 ),
( 'ORANGE PEEL 100G', 'productPool/1.jpg', 144 ),
( 'ORANGE SKORE CONDOMS80R', 'productPool/1.jpg', 171 ),
( 'ORANGE SOFT DRINK', 'productPool/1.jpg', 60 ),
( 'ORANGE SQUEEZER', 'productPool/1.jpg', 87 ),
( 'ORANGE TANG 750G RS 180', 'productPool/1.jpg', 54 ),
( 'ORBIT LEMON LIME FLAVOURED 4.4G', 'productPool/1.jpg', 61 ),
( 'ORBIT MIXED FRUIT 4.4G', 'productPool/1.jpg', 77 ),
( 'ORBIT ORANGE CARDOMOM 4.4G', 'productPool/1.jpg', 260 ),
( 'ORBIT SPEARMINT', 'productPool/1.jpg', 39 ),
( 'ORBIT SWEETMINT RS 5', 'productPool/1.jpg', 278 ),
( 'ORBIT WINTERFROST 4.4G', 'productPool/1.jpg', 162 ),
( 'OREO CADBURY DIPPED 150G', 'productPool/1.jpg', 264 ),
( 'OREO CHOCOLATE 120G', 'productPool/1.jpg', 189 ),
( 'OREO DARK AND WHITE CHOCOLATE BISCUIT 137G', 'productPool/1.jpg', 259 ),
( 'OREO GIFT PACK 600G', 'productPool/1.jpg', 262 ),
( 'OREO GOLDEN VANILA CREME 150G', 'productPool/1.jpg', 105 ),
( 'OREO ICE CREAM BISCUIT 137G', 'productPool/1.jpg', 4 ),
( 'OREO ORGINAL VANILA CREME BISCUITS 120G', 'productPool/1.jpg', 222 ),
( 'OREO ORIGINAL VANILA 120G', 'productPool/1.jpg', 142 ),
( 'OREO PEANUT BUTTER BISCUIT 137G', 'productPool/1.jpg', 178 ),
( 'OREO STRAWBERRY 120G', 'productPool/1.jpg', 147 ),
( 'OREO STRAWBERRY CREME BISCUITS 120G', 'productPool/1.jpg', 66 ),
( 'OREO VANILA CREME 100G', 'productPool/1.jpg', 58 ),
( 'ORGANA APPLE JUICE 200ML', 'productPool/1.jpg', 51 ),
( 'ORGANA GUAVA JUICE 200ML', 'productPool/1.jpg', 33 ),
( 'ORGANA MANGO JUICE 200ML', 'productPool/1.jpg', 46 ),
( 'ORGANA ORANGE JUICE 200ML', 'productPool/1.jpg', 19 ),
( 'ORGANA PASSION FRUIT JUICE 200ML', 'productPool/1.jpg', 135 ),
( 'ORGANA PINEAPPLE JUICE 200ML', 'productPool/1.jpg', 99 ),
( 'ORGANA POMEGRANATE JUICE 200ML', 'productPool/1.jpg', 146 ),
( 'ORGANA REFRESHING APPLE 1 LTR', 'productPool/1.jpg', 15 ),
( 'ORGANA REFRESHING APPLE 500 ML', 'productPool/1.jpg', 69 ),
( 'ORGANA REFRESHING MANGO 1LTR', 'productPool/1.jpg', 178 ),
( 'ORGANA REFRESHING MANGO 500ML', 'productPool/1.jpg', 180 ),
( 'ORGANA RICH GUAVA 500ML', 'productPool/1.jpg', 39 ),
( 'ORGANA RICH GUAVA1 LTR', 'productPool/1.jpg', 96 ),
( 'ORGANA RICH MANGO 500ML', 'productPool/1.jpg', 261 ),
( 'ORGANA RICH MIXED FRUIT 500ML', 'productPool/1.jpg', 29 ),
( 'ORGANA RICH PULPY MANGO 1LTR', 'productPool/1.jpg', 76 ),
( 'ORGANA RICH PULPY MIXED FRUIT 1LTR', 'productPool/1.jpg', 154 ),
( 'ORGANIC 3 IN 1 FACE WASH 50ML', 'productPool/1.jpg', 22 ),
( 'ORGANIC ANTI TAN100G', 'productPool/1.jpg', 1 ),
( 'ORGANIC ARHAR DAL 500G', 'productPool/1.jpg', 38 ),
( 'ORGANIC CUCUMBER', 'productPool/1.jpg', 55 ),
( 'ORGANIC DAILY SHAMPOO225ML', 'productPool/1.jpg', 126 ),
( 'ORGANIC FACE WASH 3 IN 1100ML', 'productPool/1.jpg', 116 ),
( 'ORGANIC FLAXEED 250G', 'productPool/1.jpg', 184 ),
( 'ORGANIC HARVEST AFTER SUN GEL 50ML', 'productPool/1.jpg', 220 ),
( 'ORGANIC HARVEST ANTI PIGMENTATION CREAM 50G', 'productPool/1.jpg', 251 ),
( 'ORGANIC HARVEST BODY LOTION 100ML', 'productPool/1.jpg', 276 ),
( 'ORGANIC HARVEST BODY WASH LAVENDER 200ML', 'productPool/1.jpg', 120 ),
( 'ORGANIC HARVEST DAILY DAY CREAM 15G', 'productPool/1.jpg', 24 ),
( 'ORGANIC HARVEST DAILY NIGHT CREAM 50G', 'productPool/1.jpg', 146 ),
( 'ORGANIC HARVEST EUCALYPTUS OIL 10ML', 'productPool/1.jpg', 207 ),
( 'ORGANIC HARVEST FACE SCRUB 50G', 'productPool/1.jpg', 109 ),
( 'ORGANIC HARVEST HAIR FALL CONTROL SHAMPOO 225ML', 'productPool/1.jpg', 234 ),
( 'ORGANIC HARVEST HAIR OIL HAIRFALL CONTROL 50ML', 'productPool/1.jpg', 186 ),
( 'ORGANIC HARVEST HIR OIL HAIR STRENGTHENING', 'productPool/1.jpg', 118 ),
( 'ORGANIC HARVEST LEMON GRASS OIL 10ML', 'productPool/1.jpg', 196 ),
( 'ORGANIC HARVEST LIP BALM POMEGRANATE 10ML', 'productPool/1.jpg', 211 ),
( 'ORGANIC HARVEST LIP BALM STRAWBERY 10ML', 'productPool/1.jpg', 235 ),
( 'ORGANIC HARVEST MOISTURISING LOTION 100ML', 'productPool/1.jpg', 189 ),
( 'ORGANIC HARVEST NEEM FACEWASH100ML', 'productPool/1.jpg', 243 ),
( 'ORGANIC HARVEST PEPPERMINT OIL 10ML', 'productPool/1.jpg', 174 ),
( 'ORGANIC HARVEST SKIN LIGHTENING CREAM 50G', 'productPool/1.jpg', 138 ),
( 'ORGANIC HARVEST SKIN LIGHTENING MASK 50G', 'productPool/1.jpg', 148 ),
( 'ORGANIC HONEY SNAP SQUEEZE 160G', 'productPool/1.jpg', 127 ),
( 'ORGANIC INDA TULSI GINGER 50G', 'productPool/1.jpg', 246 ),
( 'ORGANIC INDA TULSI GREEN TEACLASSIC 25N', 'productPool/1.jpg', 230 ),
( 'ORGANIC INDIA AMALAKI CAPSULES 60N', 'productPool/1.jpg', 209 ),
( 'ORGANIC INDIA APPLE CIDER VINEGAR 500ML', 'productPool/1.jpg', 128 ),
( 'ORGANIC INDIA ASHWAGANDHA CAPSULES 60N', 'productPool/1.jpg', 192 ),
( 'ORGANIC INDIA BEAUTIFUL SKIN CAPSULE 60N', 'productPool/1.jpg', 119 ),
( 'ORGANIC INDIA BOWELCARE CAPSULE 60N', 'productPool/1.jpg', 99 ),
( 'ORGANIC INDIA BRAHMI CAPSULE 60N', 'productPool/1.jpg', 113 ),
( 'ORGANIC INDIA BREATHE FREE CAPSULE 60N', 'productPool/1.jpg', 169 ),
( 'ORGANIC INDIA CHYAWANPRASH 500G', 'productPool/1.jpg', 73 ),
( 'ORGANIC INDIA CINNAMON CAPSULE 60N', 'productPool/1.jpg', 233 ),
( 'ORGANIC INDIA FLAXSEED OIL CAPSULE 60N', 'productPool/1.jpg', 39 ),
( 'ORGANIC INDIA FLEXIBILITY CAPSULE 60N', 'productPool/1.jpg', 14 ),
( 'ORGANIC INDIA GREEN TEA TULSI CLEANSE 25N', 'productPool/1.jpg', 258 ),
( 'ORGANIC INDIA GREEN TEA TULSI LAX 25N', 'productPool/1.jpg', 118 ),
( 'ORGANIC INDIA GREEN TEA TULSI SLEEP 25N', 'productPool/1.jpg', 20 ),
( 'ORGANIC INDIA HEART GUARD CAPSULE 60N', 'productPool/1.jpg', 22 ),
( 'ORGANIC INDIA IMMUNITY CAPSULE 60N', 'productPool/1.jpg', 170 ),
( 'ORGANIC INDIA MORINGA CAPSULE 60N', 'productPool/1.jpg', 202 ),
( 'ORGANIC INDIA MORINGA POWDER 100G', 'productPool/1.jpg', 234 ),
( 'ORGANIC INDIA NEEM CAPSULE 60N', 'productPool/1.jpg', 225 ),
( 'ORGANIC INDIA ORGANUIC HONEY 250G', 'productPool/1.jpg', 189 ),
( 'ORGANIC INDIA OSTEOSEAL CAPSULE 60N', 'productPool/1.jpg', 77 ),
( 'ORGANIC INDIA PINK ROCK SALT 100G', 'productPool/1.jpg', 245 ),
( 'ORGANIC INDIA PINK ROCK SALT POWDER 1KG', 'productPool/1.jpg', 117 ),
( 'ORGANIC INDIA PROSTATE CARE CAPSULE 60N', 'productPool/1.jpg', 55 ),
( 'ORGANIC INDIA PSYLLIUM WHOLE HUSK 100G', 'productPool/1.jpg', 1 ),
( 'ORGANIC INDIA SHATAVARI CAPSULE 60N', 'productPool/1.jpg', 70 ),
( 'ORGANIC INDIA STEVIA 25 SACHETS', 'productPool/1.jpg', 134 ),
( 'ORGANIC INDIA SUGAR BALANCE CAPSULE 60N', 'productPool/1.jpg', 160 ),
( 'ORGANIC INDIA TRIPHALA CAPSULE 60N', 'productPool/1.jpg', 7 ),
( 'ORGANIC INDIA TRIPHALA POWDER 100G', 'productPool/1.jpg', 76 ),
( 'ORGANIC INDIA TULSI BRAHMI 25NIB', 'productPool/1.jpg', 60 ),
( 'ORGANIC INDIA TULSI GINGER GREEN TEA 100G', 'productPool/1.jpg', 156 ),
( 'ORGANIC INDIA TULSI GINGER GREEN TEA 25N', 'productPool/1.jpg', 201 ),
( 'ORGANIC INDIA TULSI GREEN TEA CLASSIC 50G', 'productPool/1.jpg', 248 ),
( 'ORGANIC INDIA TULSI GREEN TEA EARL GREY 25N', 'productPool/1.jpg', 233 ),
( 'ORGANIC INDIA TULSI HONEY CHAMOMILE 25N', 'productPool/1.jpg', 235 ),
( 'ORGANIC INDIA TULSI LEMON GINGER TEA 25N', 'productPool/1.jpg', 126 ),
( 'ORGANIC INDIA TULSI MASALA CHAI 25N', 'productPool/1.jpg', 122 ),
( 'ORGANIC INDIA TULSI ORIGINAL GREEN TEA 100G', 'productPool/1.jpg', 158 ),
( 'ORGANIC INDIA TULSI ORIGINAL GREEN TEA 25N', 'productPool/1.jpg', 81 ),
( 'ORGANIC INDIA TULSI ORIGINAL GREEN TEA 50G', 'productPool/1.jpg', 131 ),
( 'ORGANIC INDIA TULSI SWEET LEMON TEA25N', 'productPool/1.jpg', 124 ),
( 'ORGANIC INDIA TULSI SWEET ROSE 25NIB', 'productPool/1.jpg', 192 ),
( 'ORGANIC INDIA TULSI TUMMY 25N', 'productPool/1.jpg', 250 ),
( 'ORGANIC INDIA TURMERIC FORMULA CAPSULE 60N', 'productPool/1.jpg', 12 ),
( 'ORGANIC INDIA WHEAT GRASS POWDER 100G', 'productPool/1.jpg', 273 ),
( 'ORGANIC LIGHTENING FACE WASH50ML', 'productPool/1.jpg', 256 ),
( 'ORGANIC MOON DAL WHOLE 500G', 'productPool/1.jpg', 26 ),
( 'ORGANIC MOONG DAL WHOLE 1KG', 'productPool/1.jpg', 90 ),
( 'ORGANIC NEEM FACE WASH 50ML', 'productPool/1.jpg', 85 ),
( 'ORGANIC NIGHT CREAM15G', 'productPool/1.jpg', 258 ),
( 'ORGANIC NORMAL SKIN CLEANSING MILK 100ML', 'productPool/1.jpg', 154 ),
( 'ORGANIC ORGADYNT SHAMPOO225ML', 'productPool/1.jpg', 133 ),
( 'ORGANIC PAVAKKA', 'productPool/1.jpg', 52 ),
( 'ORGANIC RAGI 500G', 'productPool/1.jpg', 215 ),
( 'ORGANIC RAGI FLOUR 500G', 'productPool/1.jpg', 157 ),
( 'ORGANIC RAMEN NOODLES 300G', 'productPool/1.jpg', 47 ),
( 'ORGANIC SHINE & GLOW SERUM 30ML', 'productPool/1.jpg', 36 ),
( 'ORGANIC SKIN FACE WASH100ML', 'productPool/1.jpg', 273 ),
( 'ORGANIC SOBA NOODLES 300G', 'productPool/1.jpg', 42 ),
( 'ORGANIC SUNCREEN WITH SPF50G', 'productPool/1.jpg', 183 ),
( 'ORGANIC SUNSCREEN GEL 50G', 'productPool/1.jpg', 5 ),
( 'ORGANIC TULSI GINGER GREEN TEA 100G TIN', 'productPool/1.jpg', 57 ),
( 'ORGANIC TULSI GINGER TURMERIC GREEN TEA 25N', 'productPool/1.jpg', 9 ),
( 'ORGANIC TULSI GREEN TEA CLASSIC 100G', 'productPool/1.jpg', 90 ),
( 'ORGANIC TULSI GREEN TEA CLASSIC 100G TIN', 'productPool/1.jpg', 209 ),
( 'ORGANIC TULSI GREEN TEA CLASSIC 10N', 'productPool/1.jpg', 262 ),
( 'ORGANIC TULSI ORIGINAL GREEN TEA 100G TIN', 'productPool/1.jpg', 253 ),
( 'ORGANIC TULSI POMEGRANATE GREEN TEA 25N', 'productPool/1.jpg', 48 ),
( 'ORGANIC UDON NOODLES 300G', 'productPool/1.jpg', 259 ),
( 'ORGANIC UNDER EYE15G', 'productPool/1.jpg', 168 ),
( 'ORGANIC WHEAT DALIA 500G', 'productPool/1.jpg', 237 ),
( 'ORGINAL LEMON GRASS OIL 50ML', 'productPool/1.jpg', 96 ),
( 'ORIGAMI KITCHEN TOWEL', 'productPool/1.jpg', 2 ),
( 'ORIGAMI KITCHEN TOWELS 23*21', 'productPool/1.jpg', 78 ),
( 'ORIGAMI POCKET TISSUE MRP 115', 'productPool/1.jpg', 27 ),
( 'ORIGAMI POCKET TISSUE MRP 12', 'productPool/1.jpg', 19 ),
( 'ORIGANO DRY LEAF 25G', 'productPool/1.jpg', 178 ),
( 'ORIGINAL KIMIA DATES', 'productPool/1.jpg', 138 ),
( 'ORIGINAL KIMIA DATES 400G', 'productPool/1.jpg', 115 ),
( 'ORIGINAL KIMIA DATES 650G', 'productPool/1.jpg', 260 ),
( 'ORIGINAL KISMIA DATES 750G', 'productPool/1.jpg', 232 ),
( 'ORIGINAL MANGO CHUNKS DRINK 180ML', 'productPool/1.jpg', 84 ),
( 'ORIGINAL ORANGE CHUNKS DRINK 180ML', 'productPool/1.jpg', 181 ),
( 'ORIGINAL PEACH CHUNKS DRINKS 180ML', 'productPool/1.jpg', 197 ),
( 'ORIGINAL ZARGARZADEH DATES 750G', 'productPool/1.jpg', 214 ),
( 'ORMA LEMON GRASS OIL 30ML', 'productPool/1.jpg', 118 ),
( 'ORO GARLIC PAKKODA 150G', 'productPool/1.jpg', 207 ),
( 'ORO NENDRAN LONG CHIPS 150G', 'productPool/1.jpg', 65 ),
( 'ORO PEANUT GHEE ROST 150G', 'productPool/1.jpg', 7 ),
( 'ORO PEANUT SWEET 150G', 'productPool/1.jpg', 161 ),
( 'ORO RING MURUKKU 175G', 'productPool/1.jpg', 71 ),
( 'ORO SPICY MURUKKU 175G', 'productPool/1.jpg', 235 ),
( 'ORO SPRILL MURUKKU 175G', 'productPool/1.jpg', 40 ),
( 'ORTOHERB TABLET 30TAB', 'productPool/1.jpg', 247 ),
( 'ORYSA RICE BRAN OIL 1 LTR POUCH', 'productPool/1.jpg', 98 ),
( 'ORYSA RICE BRAN OIL 1L BOTTLE', 'productPool/1.jpg', 171 ),
( 'OSCAR MUG 1000ML', 'productPool/1.jpg', 210 ),
( 'OSCAR MUG 1500ML', 'productPool/1.jpg', 258 ),
( 'OSHON FRUIT CANDY', 'productPool/1.jpg', 128 ),
( 'OSHON KULFI TOFFEE 500G', 'productPool/1.jpg', 14 ),
( 'OSHON LOLLIPOP', 'productPool/1.jpg', 233 ),
( 'OSSAM PLEASURE DEO 115ML', 'productPool/1.jpg', 115 ),
( 'OSSAM PLEASURE DEO 190ML', 'productPool/1.jpg', 45 ),
( 'OSSUM BLACK HAIR SHAMPOO 25ML', 'productPool/1.jpg', 41 ),
( 'OSSUM BLOSSOM 190ML', 'productPool/1.jpg', 138 ),
( 'OSSUM BODY MIST COMFORT 115ML', 'productPool/1.jpg', 168 ),
( 'OSSUM BODY MIST FUN 115ML', 'productPool/1.jpg', 184 ),
( 'OSSUM BODY MIST PAMPER 115ML', 'productPool/1.jpg', 132 ),
( 'OSSUM DESIRE PERFUME SPRAY 25ML', 'productPool/1.jpg', 233 ),
( 'OSSUM ROMANCE 190ML', 'productPool/1.jpg', 127 ),
( 'OSSUM ROMANCE DEO 115ML', 'productPool/1.jpg', 185 ),
( 'OSSUM WITH AQUA PERFUMED BODY MIST', 'productPool/1.jpg', 126 ),
( 'OSSUM ZEAL PERFUMED BODY MIST WITH AQUA', 'productPool/1.jpg', 116 ),
( 'OUTSHINE CAR WASH 250ML', 'productPool/1.jpg', 181 ),
( 'OVALTINE CHOCOLATE POWDER 400G', 'productPool/1.jpg', 108 ),
( 'OVALTINE MALT DRINK CHOCOLATE 400G', 'productPool/1.jpg', 95 ),
( 'OVALTINE MILK POWDER 400G', 'productPool/1.jpg', 86 ),
( 'OVALTINE NUTRITION 400G', 'productPool/1.jpg', 162 ),
( 'OXY LIFE BLEACH CREAM 27G', 'productPool/1.jpg', 103 ),
( 'OXYWRAP ALUMINIUM FOIL 600 MTR', 'productPool/1.jpg', 121 ),
( 'OXYWRAP CLING FILM 100MT', 'productPool/1.jpg', 56 ),
( 'P LOVE ADULT DIAPERS LARGE 5S', 'productPool/1.jpg', 153 ),
( 'P LOVE ADULT DIAPERS M10', 'productPool/1.jpg', 74 ),
( 'P LOVE ADULT DIAPERS M5', 'productPool/1.jpg', 19 ),
( 'P LOVE ADULT DIAPERS XL 8', 'productPool/1.jpg', 260 ),
( 'P.LOVE DIAPER LARGE', 'productPool/1.jpg', 4 ),
( 'PA BODY DEO 135ML WOMAN', 'productPool/1.jpg', 222 ),
( 'PAF CORN FLAKES CANDY 9N', 'productPool/1.jpg', 102 ),
( 'PAF MALAR CANDY 9N', 'productPool/1.jpg', 41 ),
( 'PAF MIXTURE CANDY 12N', 'productPool/1.jpg', 146 ),
( 'PAF SESAME SEED CANDY 12N', 'productPool/1.jpg', 169 ),
( 'PAK CHOI', 'productPool/1.jpg', 222 ),
( 'PAKKAD SMALL', 'productPool/1.jpg', 209 ),
( 'PALA PLATE 10 INCH 10P', 'productPool/1.jpg', 91 ),
( 'PALA PLATE 5 INCH 10P', 'productPool/1.jpg', 190 ),
( 'PALADA MIX 200G BAMBINO 66*1', 'productPool/1.jpg', 164 ),
( 'PALAK', 'productPool/1.jpg', 144 ),
( 'PALAT APPAM PODI 1KG', 'productPool/1.jpg', 146 ),
( 'PALAT APPAM PODI 500GM', 'productPool/1.jpg', 53 ),
( 'PALAT CHEMBA PUTTU POWDER 500G', 'productPool/1.jpg', 264 ),
( 'PALAT CHICKEN MASALA 100GM', 'productPool/1.jpg', 89 ),
( 'PALAT CHILLI POWDEER 100GM', 'productPool/1.jpg', 127 ),
( 'PALAT CORIANDER POWDER 250GM', 'productPool/1.jpg', 15 ),
( 'PALAT KADUKU MANGO PICKLE 300GM JAR', 'productPool/1.jpg', 109 ),
( 'PALAT KASHMIRI CHILLI POWDER 250GM', 'productPool/1.jpg', 90 ),
( 'PALAT KASHMIRI CHILLY POWDER 100G', 'productPool/1.jpg', 278 ),
( 'PALAT MEAT MASALA 100GM', 'productPool/1.jpg', 28 ),
( 'PALAT MIXED FRUIT JAM 100GM', 'productPool/1.jpg', 98 ),
( 'PALAT PUTTU POWDER 500G', 'productPool/1.jpg', 214 ),
( 'PALAT PUTTUPODI 1KG', 'productPool/1.jpg', 42 ),
( 'PALAT ROASTED RAVA 500G', 'productPool/1.jpg', 249 ),
( 'PALAT SAMBAR POWDER 100GM', 'productPool/1.jpg', 22 ),
( 'PALAT TURMERIC POWDER 100GM', 'productPool/1.jpg', 12 ),
( 'PALM JAGGERY 300GM', 'productPool/1.jpg', 46 ),
( 'PALM SUGAR CANDY 100GM', 'productPool/1.jpg', 6 ),
( 'PALM SUGAR CANDY 250G', 'productPool/1.jpg', 238 ),
( 'PALMO COCONUT MILK POWDER 100G', 'productPool/1.jpg', 235 ),
( 'PALMO DESI COCONUT POWDER 100GM', 'productPool/1.jpg', 11 ),
( 'PALMOLIVE AROMA 250 ML', 'productPool/1.jpg', 168 ),
( 'PALMOLIVE AROMA ABSOLUTE RELAX SHOWER GEL', 'productPool/1.jpg', 72 ),
( 'PALMOLIVE AROMA GEL BODY WASH 250ML', 'productPool/1.jpg', 249 ),
( 'PALMOLIVE AROMA MORNING TONIC 250ML', 'productPool/1.jpg', 189 ),
( 'PALMOLIVE AYUR 250ML', 'productPool/1.jpg', 30 ),
( 'PALMOLIVE BLACK ORCHID HANDWASH 250ML', 'productPool/1.jpg', 150 ),
( 'PALMOLIVE CHARCOAl POWDER FACIAL BAR75G', 'productPool/1.jpg', 137 ),
( 'PALMOLIVE CHARCOAL SOAP 75G*4', 'productPool/1.jpg', 36 ),
( 'PALMOLIVE CLASSIC SHAVING FOAM 300ML', 'productPool/1.jpg', 208 ),
( 'PALMOLIVE COOL SHAVING FOAM 300ML', 'productPool/1.jpg', 41 ),
( 'PALMOLIVE DEEP CLEANSING 500ML', 'productPool/1.jpg', 161 ),
( 'PALMOLIVE FOAMING HAND WASH LIME MINT', 'productPool/1.jpg', 168 ),
( 'PALMOLIVE FOAMING HAND WASH RASPERY', 'productPool/1.jpg', 18 ),
( 'PALMOLIVE GLAMOROUS SHOWER GEL 250ML', 'productPool/1.jpg', 249 ),
( 'PALMOLIVE HAND WASH BLACK ORCHID MILK 250 ML', 'productPool/1.jpg', 8 ),
( 'PALMOLIVE HAND WASH SEA MINERAL 250 ML', 'productPool/1.jpg', 218 ),
( 'PALMOLIVE HANDWASH ORCHID 185ML*A', 'productPool/1.jpg', 57 ),
( 'PALMOLIVE HANDWASH SEA MINERALS 185ML*A', 'productPool/1.jpg', 216 ),
( 'PALMOLIVE LUMINOUS OIL HANDWASH 500ML', 'productPool/1.jpg', 78 ),
( 'PALMOLIVE LUMINOUS OIL SHAMPOO 350ML', 'productPool/1.jpg', 42 ),
( 'PALMOLIVE MEN BLUE REFRESHING 250ML', 'productPool/1.jpg', 81 ),
( 'PALMOLIVE MEN ENERGISING 250ML', 'productPool/1.jpg', 107 ),
( 'PALMOLIVE MEN SENSITIVE 250ML', 'productPool/1.jpg', 29 ),
( 'PALMOLIVE OIL SENSATION FEEL GOOD 250ML', 'productPool/1.jpg', 64 ),
( 'PALMOLIVE SEA MINERAL HAND WASH 250ML', 'productPool/1.jpg', 221 ),
( 'PALMOLIVE SEA MINERALS HANDWASH 185ML POUCH', 'productPool/1.jpg', 155 ),
( 'PALMOLIVE SKIN RENEWAL COCONUT 250ML', 'productPool/1.jpg', 195 ),
( 'PALMOLIVE TAMARIND SOAP 75G*4', 'productPool/1.jpg', 156 ),
( 'PALMOLIVE TSPA MINERAL.MASSAGE 250ML', 'productPool/1.jpg', 5 ),
( 'PALMOLIVE TURMERIC & TAMARIND FACIAL BAR75G', 'productPool/1.jpg', 172 ),
( 'PALMOLIVE VITAMIN C & E FACIAL BAR 75G', 'productPool/1.jpg', 12 ),
( 'PALMOLIVE VITAMIN C SOAP 75G*4', 'productPool/1.jpg', 88 ),
( 'PALMOLOVE BLACK ORCHID HANDWASH 185ML POUCH', 'productPool/1.jpg', 102 ),
( 'PALMRITE EVERYDAY GLOVES 7.5 SIZE', 'productPool/1.jpg', 145 ),
( 'PALMRITE EVERYDAY GLOVES 8.5 SIZE', 'productPool/1.jpg', 112 ),
( 'PALMRITE EVERYDAY GLOVES MRP50', 'productPool/1.jpg', 83 ),
( 'PALMRITE MULTITASK GLOVES 9-9.5 SIZE', 'productPool/1.jpg', 106 ),
( 'PALMSAFE HAND SANITIZER 60ML', 'productPool/1.jpg', 10 ),
( 'PAMOLIVE NATURALS ORCHID & MILK500ML', 'productPool/1.jpg', 218 ),
( 'PAMPAERS IMAX LARGE 18S', 'productPool/1.jpg', 253 ),
( 'PAMPERS ACTIVE BABY LARGE 18S', 'productPool/1.jpg', 150 ),
( 'PAMPERS ACTIVE BABY LARGE 50', 'productPool/1.jpg', 276 ),
( 'PAMPERS ACTIVE BABY LARGE 50S', 'productPool/1.jpg', 29 ),
( 'PAMPERS ACTIVE BABY LARGE 78S', 'productPool/1.jpg', 221 ),
( 'PAMPERS ACTIVE BABY LG 50S', 'productPool/1.jpg', 94 );